### ISSUE TITLE
Script to improve upgrading between versions of Flutter Rust Bridge

### ISSUE THREAD

**Issue by azimuthdeveloper** [fzyzcjy/flutter_rust_bridge#1012]
**Is your feature request related to a problem? Please describe.**
Lately, when I've come back to my project, I've experienced difficulties in trying to use Flutter Rust Bridge. From googling and searching the GitHub, it seems like the reason for this is because a version change in flutter rust bridge, and the version in use in my Flutter project goes out of sync with the installed Cargo version.

**Describe the solution you'd like**
I wrote a script in Powershell - probably easily convertible to shell script or whatever is required that achieves the following:

1. Removes generated FRB files
2. Updates the native project (to bring in the latest version of flutter rust bridge, in the native rust project)
3. Reinstalls `flutter_rust_bridge_codegen` to ensure the latest version is retrieved
4. Runs `flutter pub get` in case it has not been run yet
5. Executes the codegen tool.

My thought is that if this is not a completely dumb idea, I could refactor it for cross-platform use, and submit a documentation update to help people to resurrect their non-functional FRB setups.

Powershell is as follows:

```
cd $PSScriptRoot
Remove-Item ".\lib\bridge*.dart"
Remove-Item ".\native\src\bridge*.rs"
cd .\native
cargo update
cd ..
cargo install flutter_rust_bridge_codegen
flutter pub get
flutter_rust_bridge_codegen --rust-input native/src/api.rs --dart-output lib/bridge_generated.dart --c-output macos/Runner/bridge_generated.h --dart-decl-output lib/bridge_definitions.dart --wasm
```

**Describe alternatives you've considered**
Try to update FRB and then regenerate bindings, hoping that outdated files would get overwritten. Removing the generated files, and then re-running the codegen tool was the only way to get the build working again.

**Additional context**

I'm quite new to Rust and FRB, so sorry if this is a dumb idea or if I'm reinventing the wheel.

Flutter rust bridge is ✨amazing✨

**Comment by fzyzcjy** [comment]
Hi that's a good idea! Indeed it has already been implemented in the https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/justfile for example projects inside this repo. But surely, not for *users'* repo. So feel free to PR :)

A few nits about the script:

* cargo update may be too agressive since it updates *all* dependencies. try to use sth like `cargo update flutterrustbridge`
* flutter package is not updated in the script
* I personally prefer a shell script, since it is more cross platform - runnable on linux, mac, and win wsl. but surely a powershell script + a shell script is ok

**Comment by SupremeDeity** [comment]
Firstly IMO it is good practice to provide a fixed version unlike the ones provided in the docs. This ensures that packages dont break when you dont expect them to.

Other than that, In addition to changes suggested above, `pub` by default provides a really good feature, that is, `pub get` does NOT get the latest version, in contrast to `cargo update`. It uses a lockfile to ensure that all packages mentioned in `pubspec.yaml` are installed and stay at the version they were installed at until a `pub upgrade` gets run. 

As such two changes i will suggest are:
1) No need to remove frb generated files, those are automatically removed/regenerated when the codegen runs.
2) Use `pub upgrade [dependency]`. Also the dependency list for both cargo and flutter pub should include all dependencies like ffi and ffigen.

**Comment by fzyzcjy** [comment]
>  in contrast to cargo update

btw cargo also has lock `cargo.lock` so if you use `cargo run` etc it will use lockfile
