### ISSUE TITLE
debug can't find base.so on Android

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#1013]
DynamicLibrary loadDylib(String path) => Platform.isIOS
    ? DynamicLibrary.process()
    : Platform.isMacOS && Abi.current() == Abi.macosX64
        ? DynamicLibrary.executable()
        : DynamicLibrary.open(path);

**Comment by fzyzcjy** [comment]
could you please provide a bit more info?

**Comment by 107295472** [comment]
I found the file, but I don’t know how to install jniLibs

**Comment by 107295472** [comment]
cargo ndk -o ../android/app/src/main/jniLibs build.   build not found
