### ISSUE TITLE
[Bug] Subclasses of `FlutterRustBridgeBase` should be singletons

### ISSUE THREAD

**Issue by kingfisherphuoc** [fzyzcjy/flutter_rust_bridge#1025]
### Describe the bug

When I tried to build a released version of MacOS (it's working fine with debug build), I got this issue:

```
Exception: Subclasses of `FlutterRustBridgeBase` should be singletons - there should not be two instances (runtimeType=NativeImpl)
```
This is the same issue with this one: https://github.com/fzyzcjy/flutter_rust_bridge/issues/496, but on Mac OS build. I fixed it by doing exactly the same suggestion on the issue:

```
@NSApplicationMain
class AppDelegate: FlutterAppDelegate {
  override func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
    let dummy = dummy_method_to_enforce_bundling()
    print(dummy)
    return true
  }
}
```
It would be great if we can update those changes to template repository. 

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Exception: Subclasses of `FlutterRustBridgeBase` should be singletons - there should not be two instances (runtimeType=NativeImpl)
```

**Comment by fzyzcjy** [comment]
Feel free to PR to fix it!
