### ISSUE TITLE
Documentation clarity around Dart -> Rust stream support

### ISSUE THREAD

**Issue by elliotsayes** [fzyzcjy/flutter_rust_bridge#1032]
First of all, amazing project and thanks for your work on this. Making this as a feature request instead of a PR as I'm not knowledgeable enough to succinctly write this myself.

**Is your feature request related to a problem? Please describe.**
The Stream page in the docs (https://cjycode.com/flutter_rust_bridge/feature/stream.html) has no mention of Dart -> Rust streams.

**Describe the solution you'd like**
A simple explanation of the current state of Dart -> Rust streams. Maybe a possible workaround or two.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fzyzcjy** [comment]
You are welcome!

It is not supported yet but feel free to PR :)

As for workarounds, each time you want to put one data from Dart to Rust, just call a normal Rust function

**Comment by elliotsayes** [comment]
Hey @fzyzcjy thanks for the clarification. I would make a PR but I simply don't have the skills on either the Rust or Dart side to make this happen.

Regarding your workaround, I guess this also means coming up with some flow control mechanism to prevent buffering too many items at once onto the Rust side (especially since there is no `async`, e.g. to await a buffer slot). In my case of a pipeline, this can probably be solved by listening to the `StreamSink` output on the other side.
