### ISSUE TITLE
Entities using sea_orm cannot be parsed

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#1062]
![image](https://user-images.githubusercontent.com/6436116/218980455-3e593a20-2adb-4950-b7ad-8222bb431a88.png)

**Comment by fzyzcjy** [comment]
👀

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/218980571-82b037ea-7804-4c2c-b338-32a3c96b9a38.png)

**Comment by fzyzcjy** [comment]
Well, would be great to make a minimal reproducible sample :)
