### ISSUE TITLE
[Bug] Failed to parse function output type PhotonRgba

### ISSUE THREAD

**Issue by realcarlos** [fzyzcjy/flutter_rust_bridge#1064]
### Describe the bug

flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output lib/bridge_generated.dart --llvm-path /usr/local/opt/llvm/

I could run the cmd above successfully in other project, but when I run it in "flutter_photon_rs-master", I got error like this:
thread 'main' panicked at 'Failed to parse function output type ``PhotonRgba``', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.63.1/src/parser/mod.rs:234:25

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
configs=[Opts { rust_input_path: "/Users/xxx/Downloads/flutter_photon_rs-master/rust/src/api.rs", dart_output_path: "/Users/xxx/Downloads/flutter_photon_rs-master/lib/bridge_generated.dart", dart_decl_output_path: None, c_output_path: ["/var/folders/b1/0fd1b6hs7lz0fm_mh346lybm0000gn/T/.tmpvi4PiX.h"], rust_crate_dir: "/Users/xxx/Downloads/flutter_photon_rs-master/rust", rust_output_path: "/Users/xxx/Downloads/flutter_photon_rs-master/rust/src/bridge_generated.rs", class_name: "FlutterPhotonRs", dart_format_line_length: 80, skip_add_mod_to_lib: false, llvm_path: ["/usr/local/opt/llvm/"], llvm_compiler_opts: "", manifest_path: "/Users/xxx/Downloads/flutter_photon_rs-master/rust/Cargo.toml", dart_root: Some("/Users/xxx/Downloads/flutter_photon_rs-master"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: false, wasm_enabled: false, inline_rust: false }]
```

### Version of `flutter_rust_bridge_codegen`

1.63.1

**Comment by realcarlos** [comment]
in api.rs , an alias name is used:
pub use photon_rs::Rgba as PhotonRgba;

**Comment by fzyzcjy** [comment]
Hmm would be great to show more logs and make a minimal reproducible sample.

Or, if you are sure it is a bug because of import alias, feel free to PR!

**Comment by 107295472** [comment]
@fzyzcjy Found the problem, the entity type cannot be written in other packages, only in the api package

**Comment by realcarlos** [comment]
> @fzyzcjy Found the problem, the entity type cannot be written in other packages, only in the api package

Hi bro , would you like to create a PR to fix this issue?

**Comment by realcarlos** [comment]
> @fzyzcjy Found the problem, the entity type cannot be written in other packages, only in the api package

Hi bro, any ideas? could you tell me what I should do?
