### ISSUE TITLE
[Bug] Unable to find library -lunwind (new NDK support)

### ISSUE THREAD

**Issue by polypixeldev** [fzyzcjy/flutter_rust_bridge#1069]
### Describe the bug

After switching to rust nightly (1.69), (because I needed to use the `mutex_unpoison` feature), my android builds started to error with "unable to find library -lunwind". I did some research and I found that in Rust 1.68, [Rust finally updated their NDK support to r25](https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html). I was able to install the laatest NDK and the latest version of `cargo-ndk`, and I was able to build my app on Rust nightly.

This should be noted in the docs, and updated when Rust 1.68 is stable.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
N/A
```

**Comment by fzyzcjy** [comment]
Sure, feel free to PR!
