### ISSUE TITLE
[Bug] Vec<Box<XXX>> is not supported in enum.

### ISSUE THREAD

**Issue by iota9star** [fzyzcjy/flutter_rust_bridge#1072]
### Describe the bug

Dart code is generated well, but rust code is not generated correctly.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
work fine.
```

### To Reproduce

- enum
```rust
#[derive(Debug)]
#[frb(dart_metadata = ("freezed",))]
pub enum Test {
    Nothing,
    Array(Vec<Box<Test>>),
}
```
- api.rs
```rust
pub fn test() -> Test {
    Test::Nothing
}
```
- bridge_generated.rs
```rust
impl support::IntoDart for Test {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::Nothing => vec![0.into_dart()],
            Self::Array(field0) => vec![1.into_dart(), field0.into_dart()],
        }
        .into_dart()
    }
}
```
![image](https://user-images.githubusercontent.com/21272154/220139455-60daa886-16f5-410d-b94f-2b6684b9d0c2.png)

**Comment by fzyzcjy** [comment]
Hmm looks like a bug. Feel free to PR to fix it!

guess about the reason: Maybe we forget to run code generator on the type

**Comment by iota9star** [comment]
@fzyzcjy Can you solve this issue？[allo-isolate](https://github.com/sunshine-protocol/allo-isolate/issues/37)

**Comment by fzyzcjy** [comment]
IMHO the bug is unrelated to allo-isolate

**Comment by iota9star** [comment]
It seems that `allo-isolate` did not implement `into_dart` for vec<box<xxx>> @fzyzcjy I don't know the specific implementation details of frb，Is there a plan to solve it?

**Comment by fzyzcjy** [comment]
IIRC, many `impl IntoDart for WhateverType` are auto-generated by frb. You may check bridge_generated.rs etc to see that. 

> Is there a plan to solve it?

Feel free to PR to fix it! If you get stuck, just ping me :)

**Comment by fzyzcjy** [comment]
Btw does `Vec<Xxx>` work, and does `Box<Xxx>` work?

And, is it possible to workaround it by using `Vec<Xxx>` without box

**Comment by iota9star** [comment]
> Btw does Vec<Xxx> work, and does Box<Xxx> work?
It works well

**Comment by iota9star** [comment]
> IIRC, many impl IntoDart for WhateverType are auto-generated by frb. You may check bridge_generated.rs etc to see that.

`frb` doesn't need to generate vec<box<xxx>>, the following part is correct

```rust
impl support::IntoDart for Test {
    fn into_dart(self) -> support::DartAbi {
        match self {
            Self::Nothing => vec![0.into_dart()],
            Self::Array(field0) => vec![1.into_dart(), field0.into_dart()],
        }
        .into_dart()
    }
}

impl support::IntoDartExceptPrimitive for Test {}
```
The implementation of vec is in `allo-isolate`

https://github.com/sunshine-protocol/allo-isolate/blob/0d361ad97b10e7e2c355c495693bb9a82ad0f95c/src/into_dart.rs#L25-L32
![image](https://user-images.githubusercontent.com/21272154/220272581-802b3e30-61ee-4e9a-8e50-9f5cd39bc158.png)

https://github.com/sunshine-protocol/allo-isolate/blob/0d361ad97b10e7e2c355c495693bb9a82ad0f95c/src/into_dart.rs#L252-L259

![image](https://user-images.githubusercontent.com/21272154/220272662-911b3fb1-19c1-4635-b607-e9dd3c71b2fc.png)

https://github.com/sunshine-protocol/allo-isolate/blob/0d361ad97b10e7e2c355c495693bb9a82ad0f95c/src/dart_array.rs#L17-L34
![image](https://user-images.githubusercontent.com/21272154/220272872-129d4d93-70d1-44a9-b921-5ce0b40c4dad.png)

These codes do not seem to support vec<box>

**Comment by iota9star** [comment]
The implementation of vec is in `allo-isolate`

https://github.com/sunshine-protocol/allo-isolate/blob/0d361ad97b10e7e2c355c495693bb9a82ad0f95c/src/into_dart.rs#L25-L32
![image](https://user-images.githubusercontent.com/21272154/220272581-802b3e30-61ee-4e9a-8e50-9f5cd39bc158.png)

https://github.com/sunshine-protocol/allo-isolate/blob/0d361ad97b10e7e2c355c495693bb9a82ad0f95c/src/into_dart.rs#L252-L259

![image](https://user-images.githubusercontent.com/21272154/220272662-911b3fb1-19c1-4635-b607-e9dd3c71b2fc.png)

https://github.com/sunshine-protocol/allo-isolate/blob/0d361ad97b10e7e2c355c495693bb9a82ad0f95c/src/dart_array.rs#L17-L34
![image](https://user-images.githubusercontent.com/21272154/220272872-129d4d93-70d1-44a9-b921-5ce0b40c4dad.png)

These codes do not seem to support vec<box> @fzyzcjy

**Comment by iota9star** [comment]
what fk! vec`<box>` is missing
![image](https://user-images.githubusercontent.com/21272154/220277116-f072189f-8617-4d81-b802-799d3bc4dc65.png)

**Comment by fzyzcjy** [comment]
I see, good observation! Then maybe it should be implemented there. For example, I guess adding a few lines such as 

```
impl<T> IntoDart for Box<T>
where
    T: IntoDartExceptPrimitive + Sized,
{
    fn into_dart(self) -> DartCObject {
        (*self).into_dart()
    }
}
```

should work

**Comment by iota9star** [comment]
@fzyzcjy Sorry, I didn't use `Box` correctly.  https://rust-lang.github.io/rust-clippy/master/index.html#vec_box
After removing `Box`, it works well
