### ISSUE TITLE
How to convert &str to String with external type

### ISSUE THREAD

**Issue by Alex-A4** [fzyzcjy/flutter_rust_bridge#1075]
Hi there!

I have an external struct like:
```
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GeneratedKey {
    pub words: Vec<&'static str>,
    pub account_type: MnemonicType,
}
```

When I'm trying to mirror it, i write:
```
pub use external_lib::{GeneratedKey};
use flutter_rust_bridge::frb;

#[frb(mirror(GeneratedKey))]
pub struct _GeneratedKey {
    pub words: Vec<String>,
    pub account_type: MnemonicType,
}
```

But the problem with `words` field because original type `Vec<&'static str>` is not the same as `Vec<String>`.

How is it possible to convert such types?

When I run builder, it throws error:
```
let _: Vec<String> = GeneratedKey.words;
      -----------   ^^^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found `&str`
= note: expected struct `Vec<std::string::String>`
              found struct `Vec<&'static str>`
```

**Comment by fzyzcjy** [comment]
One way may be that we somehow add support for the type `&str`, then we can just mirror the original `Vec<&str>` without change.

**Comment by Alex-A4** [comment]
This looks better to do some wrapper-struct that will be able to convert with frb and in our code use passing that of original struct to hand-maded.
