### ISSUE TITLE
`cargo install flutter_rust_bridge_codegen` fails for v1.64.0

### ISSUE THREAD

**Issue by dcharkes** [fzyzcjy/flutter_rust_bridge#1085]
Following https://cjycode.com/flutter_rust_bridge/quickstart.html, `$ cargo install flutter_rust_bridge_codegen` failed with:

```
   Compiling flutter_rust_bridge_codegen v1.64.0
error[E0658]: use of unstable library feature 'bool_to_option'
   --> /Users/dacoharkes/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.64.0/src/generator/rust/mod.rs:377:44
    |
377 |             (func.mode.has_port_argument().then_some("port_"))
    |                                            ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

error[E0658]: use of unstable library feature 'bool_to_option'
   --> /Users/dacoharkes/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.64.0/src/ir/func.rs:118:34
    |
118 |         self.has_port_argument().then_some("port_")
    |                                  ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

error[E0658]: use of unstable library feature 'bool_to_option'
   --> /Users/dacoharkes/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.64.0/src/ir/ty.rs:168:18
    |
168 |                 .then_some(idx)
    |                  ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `flutter_rust_bridge_codegen` due to 3 previous errors
```

I am not familiar with the Rust eco system, so maybe I'm holding it wrong.
However, in case that this is a bug, here is the bug report.

```
$ cargo --version
cargo 1.61.0 (a028ae42f 2022-04-29)
```

MacOS, architecture arm64.

**Comment by dcharkes** [comment]
```
$ cargo --version
cargo 1.67.1 (8ecd4f20a 2023-01-10)
```

Now it works.

**Comment by fzyzcjy** [comment]
@dcharkes Btw quite curious, is Dart/Flutter going to do something related to this :)

**Comment by dcharkes** [comment]
> @dcharkes Btw quite curious, is Dart/Flutter going to do something related to this :)

https://github.com/dart-lang/sdk/wiki/Dart-GSoC-2023-Project-Ideas#idea-gogen-or-rustgen-or-

I was taking a peek at what this project can do, to see if it would make sense to build a `package:rustgen`.

However, after playing with this project, it seems quite complete already. Super cool stuff! 🎉 😄 
So, we might focus on another language in a GSoC project.

Since you're the main dev on this project, anything that is lacking that you could use help from from the Dart/Flutter team?

**Comment by fzyzcjy** [comment]
@dcharkes Hi thanks for the reply, and so happy to hear praise from you! 😄

> Since you're the main dev on this project, anything that is lacking that you could use help from from the Dart/Flutter team?

Thanks for that! I will spend more time considering before giving a more thorough reply. Btw I am a bit unsure whether you mean "from students of GSoC improving flutter_rust_bridge" or "from Dart/Flutter team members"?

Also cc @Desdaemon (who also contributed many features)

**Comment by dcharkes** [comment]
> Btw I am a bit unsure whether you mean "from students of GSoC improving flutter_rust_bridge" or "from Dart/Flutter team members"?

I meant if anything is missing in the Dart VM or Dart language for good interop with Rust. So that those issues can be on the radar on our side, and we could address them in the Dart VM / Flutter code.

Feel free to open issues on the Dart SDK and Flutter repo and tag me for anything `dart:ffi` related.

**Comment by Desdaemon** [comment]
I think flutter_rust_bridge is in a good spot right now, but there are still warts around certain type combinations, scaffolding Dart-Rust libraries (technically not our scope), and parity between Dart JS and native. Each of these issues go a long way towards making not just Rust but also other guest languages easier to adopt in Dart, but they take careful planning to get right and probably needs more eyes to look at/demand from users.

**Comment by fzyzcjy** [comment]
@dcharkes I see. Will create issues when new concrete needs happen :)
