### ISSUE TITLE
Pass Rust Stack trace to Flutter

### ISSUE THREAD

**Issue by alexthe2** [fzyzcjy/flutter_rust_bridge#1087]
**Is your feature request related to a problem? Please describe.**
Some exceptions/problems are very difficult to trace without a proper stack trace

**Describe the solution you'd like**
To pass the rust error stacktrace to flutter

**Describe alternatives you've considered**
more error catching in rust, but that leads to a lot of logs

**Additional context**
-

**Comment by alexthe2** [comment]
There is a good chance it can be done super easily and I just missed sth, or it’s already done and I’m missing sth

**Comment by fzyzcjy** [comment]
IIRC rust stacktraces are already passed to flutter? at least yes for my own app using frb

**Comment by fzyzcjy** [comment]
Have you set RUST_BACKTRACE=1 env var, otherwise even if you catch a rust error in pure rust you will not get backtraces!

If this is the case, feel free to PR to update the doc about exceptions

**Comment by alexthe2** [comment]
are they? I only get the flutter stack trace and `FfiException(RESULT_ERROR, bail_message)`

**Comment by alexthe2** [comment]
> Have you set RUST_BACKTRACE=1 env var, otherwise even if you catch a rust error in pure rust you will not get backtraces!
> 
> If this is the case, feel free to PR to update the doc about exceptions

Ohh ok, will give this a try

**Comment by alexthe2** [comment]
Nope, now am sure that this doesn’t change anything

**Comment by alexthe2** [comment]
Here is what I want:
```
Hello, world!
thread 'main' panicked at 'Test panic', src/key_turbo/simple_db.rs:46:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: v12::key_turbo::simple_db::SimpleDB::get_all_users
             at ./src/key_turbo/simple_db.rs:46:9
…
```

but here is what I get:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(PANIC_ERROR, Test panic, null)
#0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:129:9)
#1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:9)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:871:15)
…
```

So yes, the error is transferred but not the stack trace 😢

**Comment by alexthe2** [comment]
I’m not even sure how one could implement this, open for any suggestions

**Comment by fzyzcjy** [comment]
Look at here, the code provides to-string of the anyhow::Error. Thus, if the backtrace is enabled, IMHO it should be seen in flutter

![image](https://user-images.githubusercontent.com/5236035/222594453-3f6f5f3f-c075-4b85-ab4d-27c51830b56f.png)

**Comment by fzyzcjy** [comment]
> Nope, now am sure that this doesn’t change anything

How did you set that env var to 1? Maybe share the code to see

**Comment by alexthe2** [comment]
I did it in a justfile using `set export`, but to be 100% certain I also
printed it in the build.rs, I tried both 1, and FULL

**Comment by alexthe2** [comment]
Is toString passing the backtrace? Not in front of my laptop right now, I
can test it out in the morning

**Comment by fzyzcjy** [comment]
> I did it in a justfile using `set export`

No the env var should be set for the *running rust process*.

https://users.rust-lang.org/t/anybody-using-backtrace-capture-stack-trace-in-android-ios-should-backtrace-be-used-in-production-environments-mobile-phones-seems-that-iphone-with-arm-does-not-support-backtrace-at-all/65856

**Comment by alexthe2** [comment]
But if it's set on a system level it gets passed along, that's why I also
verified it in the build.rs where I printed it. So it was for sure 1 to the
process

**Comment by fzyzcjy** [comment]
> But if it's set on a system level it gets passed along

needs to set it *when flutter app is running*, not *when building it* IMHO.

then you can do `env::get_var` in rust code *when flutter app is running* to double check if you are confident

**Comment by alexthe2** [comment]
Oh, will definitely try this

**Comment by alexthe2** [comment]
tried it, with `—dart-define` and no results -.-

**Comment by fzyzcjy** [comment]
No, not dart-define. That's not a environment variable, but a special Dart "environment" variable that all the rest world does not recognize

**Comment by alexthe2** [comment]
It’s just a simple `env::set_var("RUST_BACKTRACE", "1”);` somewhere in your init, will add it to the doc

**Comment by fzyzcjy** [comment]
Great! I have mentioned it in https://github.com/fzyzcjy/flutter_rust_bridge/issues/1087#issuecomment-1452820119 ;)

**Comment by alexthe2** [comment]
Ohh, I was blind
