### ISSUE TITLE
Broken pure-dart tutorial section link

### ISSUE THREAD

**Issue by coder0xff** [fzyzcjy/flutter_rust_bridge#1090]
https://github.com/fzyzcjy/flutter_rust_bridge/blob/7a00128f57064bc9f656021e62b1f8483a566bba/frb_example/pure_dart/README.md?plain=1#L3

**Comment by fzyzcjy** [comment]
Should be https://fzyzcjy.github.io/flutter_rust_bridge/tutorial_pure_dart.html

Feel free to PR!
