### ISSUE TITLE
Ignore structs/functions to be included into bridge_generated.rs

### ISSUE THREAD

**Issue by Alex-A4** [fzyzcjy/flutter_rust_bridge#1097]
Hi there!
We found a work-around solution to merge all necessary modules into single file, but frb_codegen function use NOT suitable imports into bridge_generated.rs so it leads to crush because of non relevant types.

You can look at our [code](https://github.com/broxus/nekoton_bridge/pull/8) and here inside `src/merged.rs` we can see that structures like `GeneratedKeyG` and `_MnemonicType` are presented in this file and `bridge_generated.rs` must look at this structures, BUT for some strange reasons it looks at other modules of crate:

```rust
// Section: imports

use crate::nekoton_wrapper::models_api::GeneratedKeyG;
use crate::nekoton_wrapper::models_api::MnemonicType;
```

Is there any #[frb(ignore)] attribute that we could use for original structures so they will be ignored for frb_codegen?

I tried to write custom frb_codegen function to solve this thing, but most `mod`'s of project are private

**Comment by Alex-A4** [comment]
This is a strange behaviour, BUT for frb_codegen import of target file from `lib.rs` must be at LAST place, so it will take all code correctly

**Comment by bonomat** [comment]
In case someone else is looking at this. We had a similar issue where frb tried to import private types from a different module which obviously failed. Resorting the modules in our `lib.rs` helped: the irrelevant modules need to come first and the one with the correct imports last.

**Comment by fzyzcjy** [comment]
Looks like a bug or at least weird behavior. Feel free to PR to fix it or to mention it in doc!
