### ISSUE TITLE
External Types with private attributes

### ISSUE THREAD

**Issue by alexandru0-dev** [fzyzcjy/flutter_rust_bridge#1100]
I using a crate and i'm having issues generating bridges and compiling bc the external type has private attributes. 

Tried `#[frb(mirror(...))]` and importing it publicly, also tried with `RustOpaque` but nothing. Any help?

**Comment by fzyzcjy** [comment]
What about using `newtype` design pattern of Rust?

**Comment by alexandru0-dev** [comment]
> > "but nothing"
> 
> what is the problem?

The flutter_rust_bride_codegen panics when trying to use an external type with private attributes

**Comment by alexandru0-dev** [comment]
> > "but nothing"
> 
> what is the problem?

Flutter_rust_bridge_codegen doesn't throw any issues but when building with rust, the bridge_generated.rs throws and error saying that fields of XXX struct is private.

**Comment by fzyzcjy** [comment]
Well I mean, what is the problem when using opaque. IMHO it should work.

**Comment by alexandru0-dev** [comment]
I tried using opaque before and apparently couldn't generate some dynamic traits etc

After some tweaking i got it working using opaque and Mutex/RwLock

**Comment by fzyzcjy** [comment]
Happy to see it solved!
