### ISSUE TITLE
[Bug] raw strings don’t get renamed before being transferred to dart (`r#`)

### ISSUE THREAD

**Issue by alexthe2** [fzyzcjy/flutter_rust_bridge#1103]
### Describe the bug

When a variable is called for example `type` in rust, it must be preceeded with a `r#` (tonic does this automatically), however `r#type` is not a valid variable name in dart.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
-
```

**Comment by alexthe2** [comment]
It should be an easy fix, I can check it out later, just wanted to create the bug report

**Comment by fzyzcjy** [comment]
Totally agree this is a bug if that happens. Looking forward to your PR!

**Comment by alexthe2** [comment]
Well guess what, if you put it into a function, everything breaks and you can’t rebuild it anymore

**Comment by alexthe2** [comment]
even after just clean the generation still breaks

**Comment by alexthe2** [comment]
It seems that the `syn` module failes to parse them for functions

**Comment by fzyzcjy** [comment]
@alexthe2 hmm... maybe we should file an issue at `syn`, e.g. with reproducible samples?

**Comment by alexthe2** [comment]
I filed one without reproducible samples and got shut down 🤣, I can file one at a later point this week

**Comment by fzyzcjy** [comment]
Sure, take your time! IMHO making a reproducible sample is really important, otherwise it is time-consuming to even just figure out what's the exact problem

**Comment by alexthe2** [comment]
of course, I just hoped I’d get away without reading the documentation and/or understanding it

**Comment by fzyzcjy** [comment]
I guess maybe you can just copy-paste syn's demo, and add a `r#` that you see buggy into it, and see what's going on

**Comment by alexthe2** [comment]
I tried, and it works for the module, so that means that issue is in the bridge, I’ll try to figure it out at one point

**Comment by fzyzcjy** [comment]
I see. Take your time and looking forward to the fix!
