### ISSUE TITLE
[Bug] build.rs files can cause confounding build failures

### ISSUE THREAD

**Issue by coder0xff** [fzyzcjy/flutter_rust_bridge#1105]
### Describe the bug

When modifying this code base, it's possible for the build to be successful, but for the output of the codegen to be incorrect. When running `cargo build`, `frb_example/pure_dart/rust/build.rs` and `frb_example/pure_dart_multi/rust/build.rs` will each cause code generation to occur in their respective example projects, thereby corrupting the projects, and making them rebuildable. Because `cargo build` then goes on to try building `pure_dart` and `pure_dart_multi` with corruption, those projects will fail to build. As a result `cargo build` will also fail. As a Rust newbie, and a newbie to this project, it took me literal hours to figure out why build was failing.

The official rust-analyzer plugin for VS Code will see this failure whenever an attempt to run or test is requested, and will cancel the run or test, making it impossible to investigate the issue in the workflow. You're stuck in a catch-22.  It's possible to run `cargo build` from the command line and trap the build.rs run, attaching it to a debugger. However, this workflow is also clumsy and inconvenient.

A possible path to address this is to replicate the build.rs files as Rust tests in the frb_codegen module. If problems arise, the `build.rs` files can be renamed in the working directory to temporarily disable them, and the tests used to carry out investigation.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
N/A
```

### To Reproduce

Alter the code generation so that the output is invalid and pure_dart no longer builds. Pretend that you've forgotten why, and try to investigate why `cargo build` fails. Observe that the workflow is suboptimal.

### Expected behavior

Debugging test code is well supported

### OS

Ubuntu 20 LTS

### Version of `flutter_rust_bridge_codegen`

1.68.0

**Comment by fzyzcjy** [comment]
(good job! see my comments in the PR)
