### ISSUE TITLE
Dart enums should have their variant names in Dart style.

### ISSUE THREAD

**Issue by erikas-taroza** [fzyzcjy/flutter_rust_bridge#1110]
**Is your feature request related to a problem? Please describe.**
I am wanting to reduce code reuse in my project. I realized that the comments from Rust are transferred to Dart.  Previously, I created my own enum to document it. However, what is stopping me from using the generated enum is that the enum follows Rust's conventions.

**Describe the solution you'd like**
`MyDartEnum.VariantOne` -> `MyDartEnum.variantOne`

**Describe alternatives you've considered**
I made my own enum that is a 1 to 1 copy of the generated Dart enum to use in the public API of my project.

**Additional context**
I did some testing and modified [this line](https://github.com/fzyzcjy/flutter_rust_bridge/blob/617d52ed1c6f9d92f0d485fdafea1e034edf34ef/frb_codegen/src/generator/dart/ty_enum.rs#L241) to use `dart_style()` and it did change the generated enum's values. However, I couldn't get the code gen to work properly in the pure_dart example so I couldn't continue testing.

**Comment by fzyzcjy** [comment]
Looks reasonable, this looks like a minimal change in terms of code and it improves the style, feel free to PR!

**Comment by erikas-taroza** [comment]
> Looks reasonable, this looks like a minimal change in terms of code and it improves the style, feel free to PR!

That was the plan but I had some issues testing. I was getting errors in the generated Dart code when running `just _generate_bridge_pure_dart`. Just checked out the latest release and the errors make sense now.

**Comment by fzyzcjy** [comment]
> That was the plan but I had some issues testing. I was getting errors in the generated Dart code when running just _generate_bridge_pure_dart. Just checked out the latest release and the errors make sense now.

Feel free to ask in the PR!
