### ISSUE TITLE
[Bug] - IOS/MacOS - Multiple Files - Creates duplicate struts in the C_Output files

### ISSUE THREAD

**Issue by dinbtechit** [fzyzcjy/flutter_rust_bridge#1111]
### Describe the bug

With multi-file codegen 
The struct, `wire_uint_8_list` is being generated multiple times in the `c_output` files.  (Take a look at the full code here -> [Line 8 to 91](https://github.com/dinbtechit/aries_vcx/blob/ea18eaf361d72be390a1fea2f1a02771d36ec1ab/packages/flutter_aries_vcx/macos/Classes/agency_client.h#L8) ). This happens in every single [header files](https://github.com/dinbtechit/aries_vcx/tree/master/packages/flutter_aries_vcx/macos/Classes ) that was generated. 

#### macos/Classes/agency_client.h

```c
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct _Dart_Handle* Dart_Handle;

typedef struct DartCObject DartCObject;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

typedef struct wire_uint_8_list {
  uint8_t *ptr;
  int32_t len;
} wire_uint_8_list;

. . .

```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
N/A
```

### To Reproduce

1. git Clone https://github.com/dinbtechit/aries_vcx.git
2.  Build project
```
cargo build
```
3. Navigate to `packages/flutter_aries_vcx/macos/classes` or `packages/flutter_aries_vcx/ios/classes`. Open any of the header files.

### Expected behavior

Should not generate duplicate structs.

### Generated binding code

```shell
https://github.com/dinbtechit/aries_vcx/tree/master/packages/aries_vcx/lib/src/_generated
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

1.67.*

### Flutter info

```shell
[!] Flutter (Channel stable, 3.7.3, on macOS 13.2.1 22D68 darwin-arm64, locale en-CA)
    • Flutter version 3.7.3 on channel stable at /Users/name/Library/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.7/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/name/Library/flutter. Consider adding
      /Users/name/Library/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```

### Version of `ffigen`

^7.2.4

**Comment by fzyzcjy** [comment]
cc @dbsxdbsx - who implemented the nice multi-part frb

**Comment by dinbtechit** [comment]
Is it possible to generate a single file for `c_output` while keeping the rest of the code multi-file?

**Comment by dbsxdbsx** [comment]
It is for sure that this duplication behavior is unexpected. I would come back to see how to fix it after finishing [the shared feature](https://github.com/fzyzcjy/flutter_rust_bridge/issues/987#issuecomment-1407940083).

**Comment by dinbtechit** [comment]
@dbsxdbsx  - I know you are busy working on a million things.. but just curious... if you had any updates on this? 

I would love to contribute but I am struggling a bit to wrap my head around this project. Please point me to any developer documentation there is any.

**Comment by fzyzcjy** [comment]
@dinbtechit 

https://cjycode.com/flutter_rust_bridge/contributing/design.html

**Comment by dbsxdbsx** [comment]
> @dbsxdbsx - I know you are busy working on a million things.. but just curious... if you had any updates on this?
> 
> I would love to contribute but I am struggling a bit to wrap my head around this project. Please point me to any developer documentation there is any.

I am currently trying to move duplicated shared types from regular generated files to another file for testing. Maybe still early to see anything. Personally, I would like to update it as soon as possible. Otherwise, the later the pr is posted, the more prs need to merge.

**Comment by fzyzcjy** [comment]
@dbsxdbsx Looking forward to your PRs! Feel free to open a "draft PR" even if everything is not ready, so that interested readers can see early progress

**Comment by dbsxdbsx** [comment]
@dinbtechit , I've posted a draft request. But it is still not mature enough. https://github.com/fzyzcjy/flutter_rust_bridge/pull/1145

**Comment by dinbtechit** [comment]
Please don't close this. @dbsxdbsx  is working on it.

**Comment by franklyonnet** [comment]
(moved from https://github.com/fzyzcjy/flutter_rust_bridge/issues/987 - this belongs to here)

FYI, this is how we deal with it right now. We are using the CLI version of the codegen and we are post-processing with this:

use regex::Regex;
use std::fs::{self, OpenOptions};
use std::io::{Read, Write};
use std::path::PathBuf;
use std::collections::{HashMap, HashSet};

const C_MACOS_OUTPUT_PREFIX: &str = "./macos/Runner/bridge_generated_";
const C_IOS_OUTPUT_PREFIX: &str = "./ios/Runner/bridge_generated_";
const FILE_COUNT: usize = 6;
const MODULES: [&str; FILE_COUNT] = [
    "xxx",
    "xxx2",
    "xxx3",
    "xxx4",
    "xxx5",
    "xxx6",
];


fn create_string_vector(prefix: &str, modules: &[&str], suffix: &str) -> Vec<String> {
    modules.iter().map(|module| format!("{}{}.{}", prefix, module, suffix)).collect()
}

fn remove_duplicate_structs(file_paths: &[String]) -> std::io::Result<()> {
    let struct_pattern = Regex::new(r"(?s)typedef struct\s+[\w_]+\s*\{.*?\}\s*[\w_]+;").unwrap();
    let mut seen_structs = HashMap::new();

    for file_path in file_paths {
        let path = PathBuf::from(file_path);
        let mut file_content = String::new();
        {
            println!("Reading file: {}", file_path);
            let mut file = fs::File::open(&path)?;
            file.read_to_string(&mut file_content)?;
        }

        let mut new_file_content = String::new();
        let mut last_end = 0;

        for struct_def in struct_pattern.find_iter(&file_content) {
            let start = struct_def.start();
            let end = struct_def.end();
            let struct_name = struct_def.as_str().split_whitespace().nth(2).unwrap();

            if !seen_structs.contains_key(struct_name) {
                seen_structs.insert(struct_name.to_string(), ());
                new_file_content.push_str(&file_content[last_end..end]);
            } else {
                new_file_content.push_str(&file_content[last_end..start]);
            }

            last_end = end;
        }

        new_file_content.push_str(&file_content[last_end..]);

        let mut file = OpenOptions::new()
            .write(true)
            .truncate(true)
            .open(&path)?;
        file.write_all(new_file_content.as_bytes())?;
    }

    Ok(())
}

fn main() {

    let c_macos_output = create_string_vector(C_MACOS_OUTPUT_PREFIX, &MODULES, "h");
    let c_ios_output = create_string_vector(C_IOS_OUTPUT_PREFIX, &MODULES, "h");

    if let Err(e) = remove_duplicate_structs(&c_macos_output) {
        eprintln!("Error when removing duplicates: {}", e);
    }

    if let Err(e) = remove_duplicate_structs(&c_ios_output) {
        eprintln!("Error when removing duplicates: {}", e);
    }
}

**Comment by shanelau** [comment]
same error

**Comment by dbsxdbsx** [comment]
Sorry for the long late of this bug, but I guess there would still be 1 month before merging the [pr](https://github.com/fzyzcjy/flutter_rust_bridge/pull/1145).
