### ISSUE TITLE
How to generate freezed fromJson for external type

### ISSUE THREAD

**Issue by Alex-A4** [fzyzcjy/flutter_rust_bridge#1129]
Hi there, this is just a question.
I'm trying to generate `fromJson` freezed factory for one of external types, but it seems not working.
Example struct:

```rust
#[frb(mirror(MnemonicType))]
pub enum _MnemonicType {
    Legacy,
    Labs(u16),
}
```

I want let freezed generate fromJson method for this structure in dart side, how should I do it?

Below example not working because of 2 frb attributes. Also tried `frb(mirror(MnemonicType), dart_metadata=("freezed"))`
```rust
#[frb(mirror(MnemonicType)), frb(dart_metadata=("freezed"))]
pub enum _MnemonicType {
    Legacy,
    Labs(u16),
}
```

**Comment by fzyzcjy** [comment]
Just a guess: does this work

```
