### ISSUE TITLE
Ability to place Mirrors in seperate file

### ISSUE THREAD

**Issue by alexthe2** [fzyzcjy/flutter_rust_bridge#1135]
**Is your feature request related to a problem? Please describe.**
Having hundreds of line of code just to mirror data structs artificially bloats the api file

**Describe the solution you'd like**
An additional api_mirror file, that holds the mirrors

**Describe alternatives you've considered**
Creating multiple files, but as this feature is not officially supported (tested) it is not “safe”.

**Additional context**

**Comment by alexthe2** [comment]
Ok, and it also works with multiple C files for iOS Headers? I haven't got
that to work, maybe I did sth wrong

**Comment by fzyzcjy** [comment]
Possibly related: https://github.com/fzyzcjy/flutter_rust_bridge/issues/1111#issuecomment-1477183483

Feel free to file an issue with more details of the bug you see!
