### ISSUE TITLE
Add option for value equality (`operator==`) in Dart class

### ISSUE THREAD

**Issue by w-ensink** [fzyzcjy/flutter_rust_bridge#1141]
**Is your feature request related to a problem? Please describe.**
Most state management libraries work by checking if instances are different from previous versions and then re-render the UI when that's not the case. Right now the instances are always different when they come from Rust, since they're new instances that get compared with pointer equality. 

**Describe the solution you'd like**
It would be useful to have the option to generate the implementation of the equality operator in Dart, so class instances can be compared by value.

In terms of code it would be nice to be able to write it in terms of a macro, just like the `#[frb(mirror)]` option. So it would look like this:
```rust
#[frb(equatable)]
struct Person {
    name: String,
    age: u8,
}
```

Which is then turned into this:
```dart
class Person {
  const Person({required this.name, required this.age});

  final String name;
  final int age;

  @override
  bool operator ==(Object other) =>
    identical(this, other) ||
    other is Person &&
    runtimeType == other.runtimeType &&
    name == other.name && 
    age == other.age;

  @override
  int get hashCode => name.hashCode;
}
```

**Describe alternatives you've considered**
I've considered writing my own wrapper classes in Dart, but that gets tedious fast.

**Comment by fzyzcjy** [comment]
Yes I agree. Have you checked the generated `freezed` classes? That one has good operator== and a bunch of other things

**Comment by w-ensink** [comment]
That does look like what I'm looking for. But when I do `#[frb(freezed)]` on a struct it doesn't do anything different... In the pure_dart example it seems like a `bridge_generated.freezed.dart` should be created but it isn't in my case. I can't find any config settings for it either. Am I doing something wrong?

**Comment by fzyzcjy** [comment]
> freezed.dart

Need to run the standard Dart build-runner. See https://pub.dev/packages/freezed for more details how to run it

Btw if you find the doc does not mention this build_runner at all, feel free to PR to improve :)
