### ISSUE TITLE
Support Mutable methods

### ISSUE THREAD

**Issue by SempaiEcchi** [fzyzcjy/flutter_rust_bridge#1142]
First of all I would like to thank you for making such a tool/package.
Secondly I'm not experienced in Rust so I apologize if this is something that is expected. 

I would appriciate if you could provide me some insight as to why using mutable methods is prevented by parser : `'mutable methods are unsupported for safety reasons'.`
What I'm trying to do is modify a field of struct with this method. `pub fn runSimulation(&mut self, sink: StreamSink<Vec<CustomNodeData>>) `  I guess `&mut self` is the part that causes an issue. What would be the solution to this, to return a clone of the struct(its instance) and update it on dart side?

Thank you.

**Comment by fzyzcjy** [comment]
Hi, you are welcome! Maybe this: https://github.com/fzyzcjy/flutter_rust_bridge/issues/933

**Comment by SempaiEcchi** [comment]
@fzyzcjy I see, thank you very much! Look forward to working with this package and hoping I will be able to contribute in the future :) Cheers.

**Comment by fzyzcjy** [comment]
You are welcome and looking forward to your PRs!
