### ISSUE TITLE
Is it necessary to do callFfi when the stream is not  listen?

### ISSUE THREAD

**Issue by SakurasDuck** [fzyzcjy/flutter_rust_bridge#1143]
When I'm trying to use the logger example, I just want to listen to the log stream on the log page , In this scenario, when I call `api.createLogStream()`, the log should be recorded.  

should it be :  
```dart
  @protected
  Stream<S> executeStream<S>(FlutterRustBridgeTask<S> task) {
    final func = task.constMeta.debugName;
    final nextIndex = _streamSinkNameIndex.update(func, (value) => value + 1,
        ifAbsent: () => 0);
    final name = '__frb_streamsink_${func}_$nextIndex';
    final receivePort = broadcastPort(name);
    task.callFfi(receivePort.sendPort.nativePort);

    return _executeStream(receivePort, task);
  }


  Stream<S> _executeStream<S>(ReceivePort receivePort,
      FlutterRustBridgeTask<S> task) async* {
    await for (final raw in receivePort) {
      try {
        yield _transformRust2DartMessage(raw, task.parseSuccessData);
      } on _CloseStreamException {
        receivePort.close();
        break;
      }
    }
  }
```

**Comment by fzyzcjy** [comment]
Not quite get it. May I know which part of the current (old) code have problems?

**Comment by SakurasDuck** [comment]
The problem is here,  I want to hold a stream to get rust log, but I want to listen in the log interface, this design is unreasonable?

**Comment by fzyzcjy** [comment]
I also use it to send logs (in my production env).  https://cjycode.com/flutter_rust_bridge/feature/logging.html 

So I guess you mean that, if rust side sends log so quickly *before* the dart stream is listened, it is lost?

**Comment by SakurasDuck** [comment]
My previous idea was that after the stream is created, rust can get the `StreamSink` to send data, not whether it is listened  or not.  

Now I think it's pointless to do it

Thank you

**Comment by fzyzcjy** [comment]
> after the stream is created, rust can get the StreamSink to send data

IMHO it is already the case. Rust can always send data via sink

You are welcome!
