### ISSUE TITLE
[Bug] Enums don’t throw compile time errors if they’re incorrectly mirrored

### ISSUE THREAD

**Issue by alexthe2** [fzyzcjy/flutter_rust_bridge#1146]
### Describe the bug

According to the mirroring definition a compile time error should be thrown if types are not correctly mirrored, that’s not happening for enums

**Comment by fzyzcjy** [comment]
Looks like a bug, looking forward to the PR!

For future readers: Some context - https://github.com/fzyzcjy/flutter_rust_bridge/pull/1144#issuecomment-1483829353

**Comment by alexthe2** [comment]
for reference see https://github.com/alexthe2/flutter_rust_bridge/blob/3a9a5163a45cf4ed888df7e97d88c666f0a25fbc/frb_example/pure_dart/rust/src/api.rs
