### ISSUE TITLE
Calling rust asynchronously does not enter then

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#1150]
a.listTable().then((value) => {
          // list.value = value,
          list = value,
          debugPrint("table"),
          update(["table"]),
        });

**Comment by fzyzcjy** [comment]
Hi, could you please share a minimal reproducible sample, then it will be much easier to see what is the problem :)

**Comment by 107295472** [comment]
Found the problem, but I don't know why it locks
![image](https://user-images.githubusercontent.com/6436116/229121933-c795e053-7bc3-427e-bd6c-1717ce612651.png)
After commenting that piece of code, it's fine.
