### ISSUE TITLE
Clarify how to employ an existing crate

### ISSUE THREAD

**Issue by gisborne** [fzyzcjy/flutter_rust_bridge#1189]
Forgive me if this is a stupid question. I'm learning Rust still.

I'm keen to use a particular crate: https://docs.rs/cozo/latest/cozo/

From what I've learned so far, I thought that taking the flutter_rust_bridge_template and changing api.rs to `pub use cozo::*;` might suffice.

Codegen runs fine. But my bridge_generated.dart and bridge_definitions.dart don't obviously have anything from cozo.

All the advice I can find is about how to employ things defined in api.rs. I can't actually find any advice about employing a predefined crate from Dart.

Forgive my ignorance. Perhaps I need to keep learning Rust, and that's okay.

But maybe, a section in the docs on using a regular crate would be useful?

**Comment by fzyzcjy** [comment]
https://cjycode.com/flutter_rust_bridge/feature/lang_external.html

**Comment by gisborne** [comment]
It seems like it should work. But as I say, `pub use cozo::*;`  as the only line in my api.rs file doesn't seem to work.

That's my interpretation of the page you linked to.

**Comment by fzyzcjy** [comment]
Hmm, if I understand correctly, we need to use the `mirror` feature. But feel free to PR to make it more automatic!
