### ISSUE TITLE
[Bug] SyncReturn does not support type of `anyhow::Result`

### ISSUE THREAD

**Issue by codercengiz** [fzyzcjy/flutter_rust_bridge#1190]
### Describe the bug

According to doc, it should support.

> It supports whatever types that we have described in other places, i.e. whatever types that async mode supports.

But when I want to use, i got error

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
--- stderr
  thread 'main' panicked at 'Failed to parse function output type `SyncReturn<anyhow::Result<String>>`', /home/cengiz/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.62.1/src/parser/mod.rs:234:25
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fzyzcjy** [comment]
Ha, looks like a bug! Feel free to PR :)
