### ISSUE TITLE
[Bug] not yet implemented: generate code for type bitflags struct

### ISSUE THREAD

**Issue by takkuumi** [fzyzcjy/flutter_rust_bridge#1197]
### Describe the bug

Here is the bigflags struct:

```rust
bitflags! {
  #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
  pub struct Scenes: u8 {
    const A = 0b00000000;
    const B = 0b00000001;
    const C = 0b00000010;
    const D = 0b00000011;
    const E = 0b00000100;
    const F = 0b00000101;
    const G = 0b00000110;
    const H = 0b00000111;
    const I = 0b00001000;
    const J = 0b00001001;
    const K = 0b00001010;
    const L = 0b00001011;
    const M = 0b00001100;
    const N = 0b00001101;
    const O = 0b00001110;
    const P = 0b00001111;
    const Q = 0b00010000;
  }
}
```
when pass the `Scenes` as param, there is an error `not yet implemented: generate code for type "hal :: Scenes"`

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
2023/04/30 09:50:30 [ERROR] panicked at 'not yet implemented: generate code for type "hal :: Scenes"', /Users/takumi/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/flutter_rust_bridge_codegen-1.75.1/src/ir/ty_unencodable.rs:59:9
thread 'main' panicked at 'not yet implemented: generate code for type "hal :: Scenes"', /Users/takumi/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/flutter_rust_bridge_codegen-1.75.1/src/ir/ty_unencodable.rs:59:9
```

**Comment by fzyzcjy** [comment]
I guess frb is not compatible with fancy macros, since when frb is parsing the .rs file, the macros have not been executed. This may be a problem for many code generators - that said, if some other codegen can work around this problem, feel free to tell me!

**Comment by Desdaemon** [comment]
I checked out the official docs for bitflags, here's a possible workaround (not tested):

```rust
bitflags! {
  struct _Foo: u32 { .. }
}

#[frb(mirror(_Foo))]
pub struct Foo(pub u32);
```

**Comment by The-Mr-L** [comment]
> I checked out the official docs for bitflags, here's a possible workaround (not tested):
> 
> ```rust
> bitflags! {
>   struct Foo: u32 { .. }
> }
> 
> #[frb(mirror(Foo))]
> pub struct _Foo(pub u32);
> ```

hi  :) I have been working on a macro rule for defining structs for kv store, would  this also work  in theory if the mirror part is in the macro ? or doss this also have to be expanded for it to be picked up? Just wonder :) it could be nice if we are able to use types  defined b y macros

**Comment by Desdaemon** [comment]
> would this also work in theory if the mirror part is in the macro

Sadly no, flutter_rust_bridge only works on static code for now since we're not doing proc-macro generation yet. Furthermore, since macros may use arbitrary syntax like bitflags, it is not ideal for us to consume the macros' tokens either.
