### ISSUE TITLE
Add `+simd128` to the `serve` tool, or allow passing custom `RUSTFLAGS`

### ISSUE THREAD

**Issue by skyne98** [fzyzcjy/flutter_rust_bridge#1198]
Hey-hey!
Foremost, amazing library and tools, thanks so much!

Recently I have being trying to convince the `serve` tool to accept my `RUSTFLAGS` to enable the SIMD support for WASM (as my code uses it, and my also benefit from some auto-vectorization). However, I have discovered that the `RUSTFLAGS` env. variable is hardcoded and there are no options to enable the SIMD support.

In theory, shouldn't be hard to do, but would be amazingly useful!
Thanks :)

**Comment by Desdaemon** [comment]
Given how finicky setting RUSTFLAGS usually is, I'd say the better way is to not override it if it already exists, and add some documentation on this behavior.
