### ISSUE TITLE
could not resolve NDK version

### ISSUE THREAD

**Issue by igor-yusupov** [fzyzcjy/flutter_rust_bridge#1200]
### Describe the bug

I got error while building app for android: `thread 'main' panicked at 'could not resolve NDK version: Os { code: 2, kind: NotFound, message: "No such file or directory" }'`

NDK version: 24.0.8215888
cargo-ndk version: 2.7.0
rust version: 1.69.0
ANDROID_NDK=~/Library/Android/sdk/ndk

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
[   +1 ms] [2023-05-04T21:24:16Z INFO  cargo_ndk::cli] Using NDK at path: ~/Library/Android/sdk/ndk
[   +2 ms] thread 'main' panicked at 'could not resolve NDK version: Os { code: 2, kind: NotFound, message: "No such file or directory" }',
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

1.75.1

**Comment by erikas-taroza** [comment]
I'm on Fedora Linux. The `Android/Sdk/ndk` folder contains sub folders with different NDK versions. Is this the same for you? If it is, then update your env var to point a specific version.

**Comment by igor-yusupov** [comment]
@erikas-taroza yes, I tried. result is the same
Using NDK at path: ~/Library/Android/sdk/ndk/24.0.8215888 (ANDROID_NDK_HOME)
thread 'main' panicked at 'could not resolve NDK version: Os { code: 2, kind: NotFound, message: "No such file or directory" }',`

**Comment by erikas-taroza** [comment]
> @erikas-taroza yes, I tried. result is the same Using NDK at path: ~/Library/Android/sdk/ndk/24.0.8215888 (ANDROID_NDK_HOME) thread 'main' panicked at 'could not resolve NDK version: Os { code: 2, kind: NotFound, message: "No such file or directory" }',`

Does that folder have anything inside? You could also try replacing `~` in the path and use an absolute path.

**Comment by igor-yusupov** [comment]
@erikas-taroza yes, I set absolute path and now it works! thank you very much!

**Comment by erikas-taroza** [comment]
> @erikas-taroza yes, I set absolute path and now it works! thank you very much!

Happy to help :)
