### ISSUE TITLE
How to prevent the mac app entering the app nap state when running a long task?

### ISSUE THREAD

**Issue by farmer00317558** [fzyzcjy/flutter_rust_bridge#1203]
I am uncertain if this problem is related to frb.

I am utilizing frb to execute a lengthy Rust task within my Mac App developed with Flutter. When the application is not in the foreground, it will enter the App Nap state, resulting in a significant slowdown in task execution.

What can I do to prevent this. I tried setting NSAppSleepDisabled to true. But, it doesn't work.

**Comment by fzyzcjy** [comment]
Hmm this may be unrelated to frb? Maybe search how to do this in pure-rust, or pure-c++, or even for just natively developed code (objc/swift).

**Comment by farmer00317558** [comment]
I have made a package to resolve this issue: https://pub.dev/packages/flutter_prevent_nap
