### ISSUE TITLE
[Bug] error: failed to run custom build command for `openssl-sys v0.9.87`

### ISSUE THREAD

**Issue by igor-yusupov** [fzyzcjy/flutter_rust_bridge#1204]
### Describe the bug

When I add a tokenizers = "0.13.3" lin to Cargo.toml I got an error error: failed to run custom build command for `openssl-sys v0.9.87` while building for android.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
error: failed to run custom build command for `openssl-sys v0.9.87`
```

**Comment by erikas-taroza** [comment]
Duplicate of #1171
