### ISSUE TITLE
[Bug] After upgrading frb codegen to 1.75.* it fails parsing Result<TYPE, anyhow::Error> type

### ISSUE THREAD

**Issue by Alex-A4** [fzyzcjy/flutter_rust_bridge#1208]
### Describe the bug

Hi there!
After upgrading `frb_codegen` to 1.75.* version it fails parsing any top-level method with return type `anyhow::Result<TYPE, anyhow::Error>`.
It works fine on 1.70.* version.

Also tried enabling `qualified_names` feature, nothing changed.

After diving into changes, i found, that [this](https://github.com/fzyzcjy/flutter_rust_bridge/commit/dbd070d86c0efe28da08a2e357425d2e4ee6eddc#diff-69ebf7751e9ff8017c40b4e7257ba1289be95f8913c3552e5aaa3bf59bd7cfd1) commit broke our codegen.
It comes into
```rust
_ => None, // unencodable types not implemented
```
#

Trying to run codegen where target file contains only code below:

> <code>RUST_INPUT file</code>
> ```rust
> pub fn verify_method() -> anyhow::Result<bool, anyhow::Error> {
>     Ok(true)
> }
> ```

> <code>build.rs</code>
> ```rust
> let raw_opts = RawOpts {
>         rust_input: vec![RUST_INPUT.to_string()],
>         dart_output: vec![DART_OUTPUT.to_string()],
>         c_output: Some(vec![IOS_C_OUTPUT.to_string()]),
>         inline_rust: true,
>         wasm: true,
>         ..Default::default()
>     };
> 
>     // Generate Rust & Dart ffi bridges
>     let configs = config_parse(raw_opts);
>     let all_symbols = get_symbols_if_no_duplicates(&configs).unwrap();
>     for config in configs.iter() {
>         frb_codegen(config, &all_symbols).unwrap();
>     }
> ```

> # UPD:
> This works fine if there is only first parameter in `Result<bool>`. If added second param, it fails 
> It's strange that I cannot use rust core `Result` type and must use `anyhow::Result` to avoid second param

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
[2023-05-09T10:33:59Z DEBUG lib_flutter_rust_bridge_codegen::parser] parse_function function name: Ident { sym: verify_method, span: bytes(55..68) }
  thread 'main' panicked at 'Failed to parse function output type `anyhow::Result<bool,anyhow::Error>`'
```

### Version of `flutter_rust_bridge_codegen`

1.75.*

**Comment by fzyzcjy** [comment]
Hi, looks like the commit https://github.com/fzyzcjy/flutter_rust_bridge/commit/dbd070d86c0efe28da08a2e357425d2e4ee6eddc#diff-69ebf7751e9ff8017c40b4e7257ba1289be95f8913c3552e5aaa3bf59bd7cfd1 you mentioned is from @coder0xff, thus cc @coder0xff

**Comment by fzyzcjy** [comment]
At the same time, feel free to add a unit test for your scenario, then we can be sure the bug will not regress in the future

**Comment by kumulynja** [comment]
I am having the same problem, with version 1.63.0 I had no problem with this output `anyhow::Result<RustOpaque<BlockchainInstance>, anyhow::Error>`, now with versions > 1.71.1 I am getting the same 

> error:
> 'Failed to parse function output type `anyhow::Result<RustOpaque<BlockchainInstance>,anyhow::Error>`', /Users/personal/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.75.3/src/parser/mod.rs:255:25

**Comment by fzyzcjy** [comment]
Looks like a bug. Feel free to PR to fix it!
