### ISSUE TITLE
[Bug] CMake was unable to find a build program corresponding to "Unix Makefiles"

### ISSUE THREAD

**Issue by igor-yusupov** [fzyzcjy/flutter_rust_bridge#1209]
### Describe the bug

I add sentencepiece = "0.11.1" lib and got error `CMake was unable to find a build program corresponding to "Unix Makefiles"` while building apk. When I build linux version everything is OK.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
`CMake was unable to find a build program corresponding to "Unix Makefiles"`
```

**Comment by fzyzcjy** [comment]
Hi, could you please share more logs? And it seems like it is a bug with sentencepiece + rust + android instead of frb

**Comment by igor-yusupov** [comment]
> Hi, could you please share more logs? And it seems like it is a bug with sentencepiece + rust + android instead of frb

`CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1`


it looks like that there is no CMake tool in android. how to set up it before building? or it's not possible?

**Comment by igor-yusupov** [comment]
it seems like that I need to use this https://cjycode.com/flutter_rust_bridge/integrate/android_cmake.html .
but I don't understand how to use it)

**Comment by fzyzcjy** [comment]
As mentioned above, this seems to be an issue of sentencepiece + rust + android instead of frb. So maybe search how to use cmake + android or file a bug there.

**Comment by igor-yusupov** [comment]
> As mentioned above, this seems to be an issue of sentencepiece + rust + android instead of frb. So maybe search how to use cmake + android or file a bug there.

I got it. thanks.
