### ISSUE TITLE
Fixture tests and/or more testing examples

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#1210]
> Yes that's a problem. 
>
> An alternative may be, we somehow enhance our infrastructure to test more scenarios with various feature flags. IIRC our testing infra currently is quite limited about this - everyone who PR to make a change that only happens with *some* feature flag has to do hacky things like what you have done above...

_Originally posted by @fzyzcjy in https://github.com/fzyzcjy/flutter_rust_bridge/pull/1206#discussion_r1190517154_

**Comment by fzyzcjy** [comment]
Another possibility is to add more end-to-end examples. Currently we have with_flutter, pure_dart, pure_dart_multi. We may add several new examples with various feature flags.

Pros: Realistic. Easy to understand.
Cons: Slow to compile. A bit heavy.

Possibly related: https://github.com/fzyzcjy/flutter_rust_bridge/pull/1205#discussion_r1192375220
