### ISSUE TITLE
Use Dart 3 features for codegen

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#1211]
Generate appropriate code for records and sealed classes introduced in Dart 3. It can replace Freezed in cases where not all of its functionality is required, producing leaner code.

## Records (tuple)

Related: #329 #954

```rust
type A = (i32, String);
```

```dart
typedef A = (int, String);
```

## Sealed classes

```rust
pub enum Foo {
  Bar,
  Baz(String),
  Quux { foo: String }
}
```

```dart
sealed class Foo {
  const Foo();
}

class Bar extends Foo {
  const Bar();
}

class Baz extends Foo {
  final String field0;
  const Baz(this.field0);
}

class Quux extends Foo {
  final String foo;
  const Quux({required this.foo});
}
```

However, this is not a one-to-one replacement, since the current Freezed implementation renames enum variants from `Foo::Bar` to `Foo_Bar` to avoid name collisions, while idiomatic usage expects the names being unchanged, e.g. in switch expressions:

```dart
final foo = switch (Bar()) {
  Bar() => ..,
  Baz() => ..,
  Quux() => ..,
};
```

**Comment by fzyzcjy** [comment]
The `tuple` LGTM! Especially, I think we can also replace tuple structs https://cjycode.com/flutter_rust_bridge/feature/lang_struct.html#tuple-structs (the `field0` was a bit ugly ;) )

As for the sealed class, I personally love the `freezed` because it gives good equals/hashCode. If using sealed class, we are losing this. So maybe we can wait for Dart's metaprogramming feature (in the long future, though...), which is said to be able to simplify hashCode/equals generation IIRC.

**Comment by Desdaemon** [comment]
> Especially, I think we can also replace tuple structs

I'd hope so, but given that methods can be attached to them it makes the idea a bit harder. I could see it being used for plain tuples though.

> As for the sealed class, I personally love the freezed because it gives good equals/hashCode. If using sealed class, we are losing this.

Agreed. It might be better to wait and see how the community (i.e. Freezed) plans to handle equals/hashCode with sealed classes so we can get the best of both worlds.

**Comment by fzyzcjy** [comment]
> I'd hope so, but given that methods can be attached to them it makes the idea a bit harder. I could see it being used for plain tuples though.

Ah I see, you are right.

> Agreed. It might be better to wait and see how the community (i.e. Freezed) plans to handle equals/hashCode/... with sealed classes so we can get the best of both worlds.

Totally agree.

**Comment by Desdaemon** [comment]
It was not super publicized, but at some point two weeks ago it was clarified Freezed is compatible with sealed classes, i.e. `@freezed sealed class` is now valid syntax. Updating this should be quick enough.

**Comment by fzyzcjy** [comment]
That looks interesting!
