### ISSUE TITLE
[Bug] C bridging header "field has incomplete type" with recursive type definitions

### ISSUE THREAD

**Issue by tmpfs** [fzyzcjy/flutter_rust_bridge#1215]
### Describe the bug

Using FRB 1.75.3 codegen is successful but there are errors compiling the generated header files.

```
/Users/muji/git/sos/gui/macos/Runner/api_generated.h:119:22: error: field has incomplete type 'struct wire_Secret'
```

When defining recursive type definitions the order of the C struct declarations are incorrect which yields this error trying to compile on MacOS.

For now my only workaround is to re-order the definitions manually but it would be great to not have this overhead if the fix is not too difficult.

I have an `enum` where each variant has a `user_data` field and in the `UserData` struct is a collection of fields, so the type definitions look like this:

```
Secret -> UserData -> SecretRow -> Secret
```

Can anyone with knowledge of the FRB codebase indicate the difficulty to fix this problem?

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
N/A
```

**Comment by tmpfs** [comment]
As a temporary crude hack I have added this to the end of `build.rs`:

```rust
fn reorder_recursive_types() {
    let files = &[
        "../ios/Runner/api_generated.h",
        "../macos/Runner/api_generated.h",
    ];

    let needle = r#"typedef struct wire_UserField {
  struct wire_SecretMeta meta;
  struct wire_Secret secret;
} wire_UserField;

typedef struct wire_list_user_field {
  struct wire_UserField *ptr;
  int32_t len;
} wire_list_user_field;

typedef struct wire_UserData {
  struct wire_list_user_field *fields;
  struct wire_uint_8_list *comment;
  struct wire_uint_8_list *recovery_note;
} wire_UserData;
"#;

    let target = r#"typedef struct wire_Secret {
  int32_t tag;
  union SecretKind *kind;
} wire_Secret;
"#;

    for file in files {
        let contents = std::fs::read_to_string(file)
            .expect("failed to read file");
        let contents = contents.replace(needle, "");
        let replacement = format!("{}\n{}", target, needle);
        let contents = contents.replace(target, &replacement);
        std::fs::write(file, contents).expect("failed to write file");
    }
    
}
```

**Comment by fzyzcjy** [comment]
Hmm I suspect it is a bug of https://github.com/mozilla/cbindgen.  For example, maybe show api_generated.rs to cbindgen repository and tell them that the generated .h is incorrect?

**Comment by tmpfs** [comment]
Thanks @fzyzcjy, I [raised an issue here](https://github.com/mozilla/cbindgen/issues/832) in the `cbindgen` repository.
