### ISSUE TITLE
flag `rust-enums-style` may be better than `dart-enums-style` ?

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#1219]
Currently(frb 1.75.3),  if the flag `dart-enums-style`  i set, the generated enum type in dart file would have typical dart style like this in Pascal style:
```dart
enum Weekday {
  monday,
  tuesday,
  wednesday,
  thursday,
  friday,
  saturday,
  sunday
}
``` 
But I think this flag is redundant, since the file is in dart, then the style following dart style should be set as default. Instead, if someone want style in the original rust style, then there could be flag  `rust-enums-style`  be used.

**Comment by fzyzcjy** [comment]
Looks reasonable. But I wonder whether this is caused by historical reasons, i.e. need to be backward compatible?
