### ISSUE TITLE
`flutter_rust_bridge_codegen` broken

### ISSUE THREAD

**Issue by w-ensink** [fzyzcjy/flutter_rust_bridge#1233]
Somehow `flutter_rust_bridge_codegen` broke at some point today. My CI was failing because of it, so I decided to dig into it a bit more. It turns out to be broken for all new installs. Installing a fresh copy of it via `cargo install flutter_rust_bridge_codegen` fails with the following error message:

```
 Compiling flutter_rust_bridge_codegen v1.77.1
error[E0451]: field `config_path` of struct `Config` is private
  --> /Users/wouter/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.77.1/src/commands.rs:99:11
   |
99 |         ..Default::default()
   |           ^^^^^^^^^^^^^^^^^^ field `config_path` is private

For more information about this error, try `rustc --explain E0451`.
error: could not compile `flutter_rust_bridge_codegen` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `flutter_rust_bridge_codegen v1.77.1`, intermediate artifacts can be found at `/var/folders/65/nl89nzxs5jx73y5n5515tc1w0000gn/T/cargo-installp3vlnI`
```

Not only version `1.77.1` doesn't work, I also tried `1.76.0` with no luck...

Something really strange is happening here, since my build worked fine yesterday with the exact same version and with exactly the same code and environmet. The field `config_path` is also nowhere to be found in the first place.

Any guesses as to what is happening?

**Comment by h3x4d3c1m4l** [comment]
Weird indeed, same issue here with 1.76.0:

```
   Compiling flutter_rust_bridge_codegen v1.76.0
error[E0451]: field `config_path` of struct `Config` is private
  --> C:\Users\Sander\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.76.0\src\commands.rs:99:11
   |
99 |         ..Default::default()
   |           ^^^^^^^^^^^^^^^^^^ field `config_path` is private

For more information about this error, try `rustc --explain E0451`.
error: could not compile `flutter_rust_bridge_codegen` due to previous error
error: failed to compile `flutter_rust_bridge_codegen v1.76.0`, intermediate artifacts can be found at `C:\Users\Sander\AppData\Local\Temp\cargo-installye7coq`
```

At first I thought maybe 1.76.0 and 1.77.1 are overwritten but I don't think crates.io support overwriting a already released version at all...

**Comment by h3x4d3c1m4l** [comment]
Looks like a fix might be available soon: https://github.com/fzyzcjy/flutter_rust_bridge/pull/1232

**Comment by w-ensink** [comment]
Let's hope so. It doesn't explain why it worked yesterday and broke today tho... 🤔

**Comment by fzyzcjy** [comment]
Seems related: https://github.com/fzyzcjy/flutter_rust_bridge/pull/1232

**Comment by fzyzcjy** [comment]
@h3x4d3c1m4l Oh yes, that PR

**Comment by w-ensink** [comment]
Mozilla fixed it. Build it working again.
