### ISSUE TITLE
Too many api.rs codes generate very stuck

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#1234]
How to generate multiple files
[https://github.com/cunarist/flutter-rust-app-template](https://github.com/cunarist/flutter-rust-app-template)
Or like him, no need to generate, pass the specified logo

**Comment by fzyzcjy** [comment]
There are some PRs related to multi-file:

* #1205
* #1145

Will those work for your scenario?

**Comment by 107295472** [comment]
Thank you

**Comment by dbsxdbsx** [comment]
@107295472, Currently, the tutorial for multi-blocks is [here](https://cjycode.com/flutter_rust_bridge/feature/multiple_files.html). But don't use customized-defined structs at present, or an [issue ](https://github.com/fzyzcjy/flutter_rust_bridge/issues/987)will appear.
