### ISSUE TITLE
[Bug] The ffi link on feature page is unreachable.

### ISSUE THREAD

**Issue by jaiakash** [fzyzcjy/flutter_rust_bridge#1240]
### Describe the bug

The link for *ffi* on [feature page](https://cjycode.com/flutter_rust_bridge/feature.html) is unreachable.

<img width="847" alt="Screenshot 2023-06-16 at 4 48 24 AM" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/33419526/7d056c69-acd9-48c0-944c-ba5c649473f8">

### To Reproduce

- Visit the [feature page](https://cjycode.com/flutter_rust_bridge/feature.html)
- Click on ffi link.
<img width="847" alt="Screenshot 2023-06-16 at 4 48 24 AM" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/33419526/7d056c69-acd9-48c0-944c-ba5c649473f8">

### Expected behavior

For Android, ios and macos, there are webpage for *c-interlop*
https://docs.flutter.dev/platform-integration/android/c-interop
https://docs.flutter.dev/platform-integration/ios/c-interop
https://docs.flutter.dev/platform-integration/macos/c-interop

It should redirect to the specific page for native binding.

I would generate PR for same, if issue is accepted.

**Comment by fzyzcjy** [comment]
Looks reasonable, feel free to PR to fix it!

**Comment by jaiakash** [comment]
Sure, have send PR for same. #1241
