### ISSUE TITLE
[Bug] 1.78.0  bridge_generated.io.dart - Can't have modifier 'final' here

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#1253]
### Describe the bug

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/6436116/189d7b62-1a51-49fa-a94d-6737f81b72aa)

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Can't have modifier 'final' here.
```

### OS

win 10 lstsc 2019

### Version of `flutter_rust_bridge_codegen`

1.78.0

### Version of `ffigen`

8.0.2

**Comment by fzyzcjy** [comment]
Could you please give a minimal reproducible sample?

In addition, I guess your Flutter version is too low - need 3.x

**Comment by 107295472** [comment]
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/6436116/318a3906-97cc-4e79-b37a-87abc884843e)

**Comment by 107295472** [comment]
Ok, this needs to be changed   pubspec.yaml

**Comment by Murmele** [comment]
@107295472 what did you change?

**Comment by 107295472** [comment]
> @107295472 what did you change?

environment:
  sdk: '>=3.0.0'
