### ISSUE TITLE
Does it support 3D development?

### ISSUE THREAD

**Issue by WREQI** [fzyzcjy/flutter_rust_bridge#1254]
We want to use Trust to develop high-performance apps that support 3D and AR, such as Apple's Android app. Can this be achieved?

**Comment by anlumo** [comment]
Yes, Rust can achieve high-performance code running 3D and AR. I'm a bit confused why you're posting this in the issue tracker for this project specifically, though?

**Comment by WREQI** [comment]
Because there are many technical issues that I don't understand, I am conducting technical research

**Comment by WREQI** [comment]
Is your new project planning to support webgpu, wgpu?

**Comment by anlumo** [comment]
Yes, in fact wgpu is the only API I'm planning to implement. You can see the [first prototype here]( https://github.com/anlumo/flutter_embedder/tree/bevy).

I'm using Flutter's Vulkan renderer to integrate with wgpu. This way I can mix native 3D views with Flutter widgets via its PlatformViews feature. My plan is to integrate the game engine bevy there, so I can render bevy scenes as PlatformViews.

**Comment by fzyzcjy** [comment]
That looks interesting! Btw have you checked Impeller, is it related to 3D gaming? I did see Flutter said they use Impeller to made a custom 3D engine for demo purpose.

**Comment by anlumo** [comment]
Yeah, but it's still using Dart, which is very slow. Also, the framework is pretty far removed from the rendering API, which adds a ton of overhead.

**Comment by kjxbyz** [comment]
To be honest, I am also interested in using flutter to develop 3D games, and I am also concerned about the technical progress in this area.

**Comment by anlumo** [comment]
> How about the performance of the Impeller rendering engine?

I've heard both good and bad things. As always, shader compilation is a performance issue, no matter how it's done.

**Comment by fzyzcjy** [comment]
> As always, shader compilation is a performance issue, no matter how it's done.

I am not an expert in 3D game dev, so curious why it is an issue in Impeller? I have heard Flutter people saying Impeller have zero shader compilation and they even do not package a shader compiler inside Impeller IIRC.
