### ISSUE TITLE
example tab on pub.dev

### ISSUE THREAD

**Issue by dcharkes** [fzyzcjy/flutter_rust_bridge#1260]
frb_dart/example/main.dart could be replaced by README.md pointing to the examples in the documentation.

For reference, see FFIgen:

* https://github.com/dart-lang/ffigen/tree/main/example
* https://pub.dev/packages/ffigen/example

**Comment by fzyzcjy** [comment]
Looks reasonable, thank you!

**Comment by dcharkes** [comment]
Context: https://docs.flutter.dev/packages-and-plugins/favorites#metrics

**Comment by fzyzcjy** [comment]
Wow so Flutter favorite is restarted? I will fix this soon!
