### ISSUE TITLE
Possible low quality dependencies

### ISSUE THREAD

**Issue by dcharkes** [fzyzcjy/flutter_rust_bridge#1262]
One of the dependencies of this package has some minor quality issues:

* https://github.com/iamsalnikov/colorize/issues/created_by/dcharkes

Only depending on high quality packages could increase the quality of this package.

Context: https://docs.flutter.dev/packages-and-plugins/favorites#metrics

**Comment by fzyzcjy** [comment]
I see, I should remove / replace it.

cc @Desdaemon - it seems colorize is used in the https://github.com/fzyzcjy/flutter_rust_bridge/blob/c8e2e8d164515e7bd9ae9b50ef8d84829f68a123/frb_dart/bin/serve.dart#L12 you contributed. I may temporarily remove that coloring, and feel free to add it back using high quality package!
