### ISSUE TITLE
Reading Flutter asset files from Rust

### ISSUE THREAD

**Issue by EddieMataEwy** [fzyzcjy/flutter_rust_bridge#1271]
I have some lookup tables that would be nice to have as asset files in Flutter and read from rust.
I guess I could also generate the files on the first run with no issues on desktop, but I would like a better approach for mobile.
Is this possible? Or is there some limitation for Flutter assets?
If this is not possible, what would be a platform independent way of approaching file I/O?
Thanks!

**Comment by fzyzcjy** [comment]
Maybe search how to read the assets from native code (not only rust, but also c++ etc), and search even how Android/iOS (Kotlin/Swift) reads dart assets

**Comment by EddieMataEwy** [comment]
Thanks
