### ISSUE TITLE
[ERROR] panicked at 'Failed to parse function output type `Self`'

### ISSUE THREAD

**Issue by Seferi** [fzyzcjy/flutter_rust_bridge#1274]
Hi there,

first of all, thanks for this awesome package. I'm an open source developer and there is a rust library I'm trying to bridge with my app: https://codeberg.org/keyoxide/doip-rs

I'm getting an error and this is the output: 

`
 RUST_BACKTRACE=1 flutter_rust_bridge_codegen --rust-input /home/berker/StudioProjects/doip-rs/src/claim.rs --dart-output /home/berker/StudioProjects/keyoxide-flutter/lib/features/doip_rs/claim_generated.dart
2023/07/11 22:22:18 [ERROR] panicked at 'Failed to parse function output type `Self`', /home/berker/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.78.0/src/parser/mod.rs:255:25
thread 'main' panicked at 'Failed to parse function output type `Self`', /home/berker/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.78.0/src/parser/mod.rs:255:25
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-ujz1Py/rustc-1.66.1+dfsg0ubuntu1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /build/rustc-ujz1Py/rustc-1.66.1+dfsg0ubuntu1/library/core/src/panicking.rs:65:14
   2: lib_flutter_rust_bridge_codegen::parser::Parser::parse_function
   3: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   4: lib_flutter_rust_bridge_codegen::config::opts::Opts::get_ir_file
   5: lib_flutter_rust_bridge_codegen::utils::misc::get_symbols_if_no_duplicates
   6: flutter_rust_bridge_codegen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

I'd very much appreciate the help. I'm in contact with the developer of the library and he is ready to make changes in the library as well if need be. Thanks in advance.

**Comment by fzyzcjy** [comment]
Hi, could you please share a minimal reproducible sample :)

**Comment by fzyzcjy** [comment]
Yes and no. It would be great if we can somehow create an `api.rs` that only includes a few lines of code and reproduces the error. By doing so, we can more easily debug.

**Comment by ashim-kr-saha** [comment]
I have the same issue, it is related to https://github.com/fzyzcjy/flutter_rust_bridge/issues/838
