### ISSUE TITLE
Mutable method support

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#1294]
**Is your feature request related to a problem? Please describe.**
The `automerge`/`autosurgeon` library makes heavy use of `&mut`, e.g. [reconcile](https://docs.rs/autosurgeon/latest/autosurgeon/reconcile/fn.reconcile.html
)

**Describe the solution you'd like**
Support `&mut` directly, without `RustOpaque<Mutex<>>`. The closer to being able to generate a Dart API for an arbitrary crate, the better.

**Describe alternatives you've considered**
This comment says PRs welcome, but an open question is what design would be acceptable for safely supporting `&mut`. 

https://github.com/fzyzcjy/flutter_rust_bridge/issues/933#issuecomment-1365839657

**Comment by fzyzcjy** [comment]
I agree it is open question what design should we have. One naive way may be just generate that opaque thing automatically. Another way may be add some flag to `#[frb(...)]`. Or there can be many other approaches. What do you think about the ways?

Maybe related: https://github.com/fzyzcjy/flutter_rust_bridge/issues/1132

**Comment by aran** [comment]
Maybe safety "should" be enforced at the dart level. i.e. if there were a dart-analyzer plugin (or change to dart-analyzer, or to dart itself), and new options in 'dart:meta' to allow linear types (i.e. a reference that can be moved but never duplicated). This would help with `dispose()` discipline and frb's allowing `&mut` would be safe.

That's a medium-sized project, and probably not happening anytime soon. But it illustrates that the ffi codegen level could be a suboptimal place to solve these issues. Perhaps frb could just allow possibly-unsafe usage of `&mut` params. Dart programmers already have to manage their own `.dispose()` to avoid leaks, it's reasonable to expect programmers to avoid calling `&mut` FFI functions on objects that have been passed to multiple isolates. Dart already correctly handles the possibility of object mutation across `await`. Due to copying at the API boundary, I think the generated dart code would have to construct a tuple type object or struct that includes a new result value for every `&mut` parameter, and it would be programmer's responsibility to use the result, not the parameter.

**Comment by fzyzcjy** [comment]
Firstly, interesting suggestions!

> Maybe safety "should" be enforced at the dart level.

Changing the Dart side looks interesting. But I am also worried whether this can happen or not. Dart is a (normal) language with GC, while Rust is so special in its compiler to support its special understanding of move semantics etc.

> it's reasonable to expect programmers to avoid calling &mut FFI functions on objects that have been passed to multiple isolates

I am quite afraid of supporting `&mut` directly (without RustOpaque). It is true that frb already requires manual `dispose` calls to avoid memory leaks, and it is the same as the convention in Flutter (e.g. if you create a `ui.Image`, you should manually call dispose on that). However, if someone forgets to call `dispose`, it will leak, but the leak can be detected easily using tools, and the app will not crash (except if you leak too much and OOM - but again that is quite easy to detect by tools and fix). On the other hand, if someone accidentically call `&mut` concurrently, it will violate Rust's memory model. Then, we touch undefined behavior (correct me if I am wrong, have not checked the nomicons rust book for a while). It will lead to all weird things, and is super super hard to debug, so I would avoid it if possible!

**Comment by aran** [comment]
The only other considerations I thought about since this discussion

First consideration, true flutter parallel execution only occurs with explicit spawning of separate isolates. The typical concurrency is "just" IO concurrency but not CPU concurrency. So most programs are single-threaded as it's rare to use APIs like `foundation:compute`. 


Second thought, there's various different points of view about a tool like FRB that imply different ideals for the design. One point of view is to treat it as a boilerplate generator for safe FFI. Another is to view it as a way of making apps with communicating rust and dart components. The last point of view would be to see it mainly as a tool that lets you write Rust in place of what might otherwise be Dart code. 

The first POV, boilerplate generator, implies focusing on codegen help for common patterns of ffi coding. This would imply having configurability for issues like this one. 

The second POV, with a strong separation of rust and dart components, would encourage the most conservative point of view on concurrency, as it views the likely end app as a composition of a rust app communicating in a process with an arbitrary dart app. This would encourage maximizing the rust feature set that is available.

The third POV, a Dart-replacer, would encourage the library to focus on the subset of Rust runtime that maps best Dart's existing model. This would encourage developers to limit the Rust they are bringing in to stay on Dart's happy path.

I'm not really sure what you're aiming for with this library so it's hard to say if any of these is better than the others with respect to those goals.

**Comment by fzyzcjy** [comment]
Good idea!

It is great to make good developer experience, as long as we ensure 100% code safety - because Rust (excluding the unsafe part) and Dart are both safe languages unlike C/C++, thus a user will not expect to see weird undefined behaviors or hard-to-debug crashes because of his mistake of using it.

**Comment by fzyzcjy** [comment]
I may implement it in flutter_rust_bridge 2.0

**Comment by fzyzcjy** [comment]
FRB 2.0's auto-rust-opaque supports `&mut`. Feel free to try it!

**Comment by fzyzcjy** [comment]
I will close this since it is implemented - feel free to reopen or create a new issue if needed!
