### ISSUE TITLE
[Bug] Potential regression

### ISSUE THREAD

**Issue by raphaelrobert** [fzyzcjy/flutter_rust_bridge#1303]
### Describe the bug

After upgrading from 1.78 to 1.79, async functions using the `tokio::main` macro don't seem to work anymore, and instead yield the following error:

```
     FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, ()>(
                                              ^ the trait `IntoIntoDart<()>` is not implemented for `MyStruct`
```

where `MyStruct` is a simple struct with only one `RustOpaque` field.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
.
```

### OS

MacOS/Linux

### Version of `flutter_rust_bridge_codegen`

1.79

**Comment by JustSimplyKyle** [comment]
Make sure that Cargo.toml is
`flutter_rust_bridge = { version = "=1.79.0" }`
and the binary version is also 1.79.0, failing either one would result in this error

**Comment by raphaelrobert** [comment]
Thanks, but unfortunately that doesn't fix the issue.

**Comment by JustSimplyKyle** [comment]
Huh, you sure `flutter_rust_bridge_codegen -V` is 1.79.0?
Cause the tokio method works for me

**Comment by raphaelrobert** [comment]
> flutter_rust_bridge_codegen -V

Yes

```
% flutter_rust_bridge_codegen -V
flutter_rust_bridge_codegen 1.79.0
```

**Comment by fzyzcjy** [comment]
Hmm could you please provide your Cargo.lock?

**Comment by raphaelrobert** [comment]
Closing this, because I found the reason that caused the error:

I returned a struct in a function that took a `StreamSink` as an argument. This doesn't work obviously, but so far the code generation didn't have a problem with it.
