### ISSUE TITLE
Automatically initialized android context glue

### ISSUE THREAD

**Issue by powpingdone** [fzyzcjy/flutter_rust_bridge#1323]
**Is your feature request related to a problem? Please describe.**
When attempting to use [`oboe`](https://lib.rs/crates/oboe), it requires that the Android NDK glue [`ndk_context`](https://lib.rs/crates/ndk-context) to be initialized, or else it will panic with "android context not initialized".

**Describe the solution you'd like**
I would think that initializing the `ndk_context` crate on library load would be useful for using rust and flutter on android, as crates do depend on the `ndk_context` being initialized.

**Describe alternatives you've considered**
If this isn't possible, I would like to think that a small tutorial on initializing context for Rust would be much more helpful.

**Comment by fzyzcjy** [comment]
I personally have similar problem because I want to init Sentry, logger, etc. Doc: https://cjycode.com/flutter_rust_bridge/feature/init.html

**Comment by powpingdone** [comment]
The android-activity crate [init's it here](https://github.com/rust-mobile/android-activity/blob/main/android-activity/src/native_activity/glue.rs#L881-L893).

**Comment by fzyzcjy** [comment]
Not very sure what do you mean - it seems you mentioned oboe above, which is a standard lib, while android-activity looks like something more special

**Comment by powpingdone** [comment]
Well, I mean that it initializes the `ndk_context` static variable up there. That's the "normal" process.

**Comment by fzyzcjy** [comment]
Hmm interesting, so where do you want it to be initialized?

If in onCreate, maybe register a Flutter callback that is called at that time, and let the Flutter call the Rust code?

**Comment by powpingdone** [comment]
This seems like an interesting rabbit hole to go down... https://dart.dev/guides/libraries/java-interop

**Comment by fzyzcjy** [comment]
> It would be initialized after the flutter FFI loads the library but before the first "user code" dart2rust call.

So I still do not quite get it... https://cjycode.com/flutter_rust_bridge/feature/init.html already supports to call arbitrary init code before the first flutter_rust_bridge call. Is that sufficient or not?

**Comment by powpingdone** [comment]
The issue with that is that it's within the Dart VM. It doesn't have the Java VM variables (easily) accessible. This is not a problem at all for every platform *except* Android, because Android access is gated behind getting the `JavaVM*`.

However, I have finally found a solution, initializing the library in the JVM first, then letting FRB also load the library afterwards.

First, you would need the `ndk-context` and `jni` crates, then you need this JNI function in your Rust code:
```rust
// https://github.com/RustAudio/cpal/issues/720#issuecomment-1311813294
#[cfg(target_os = "android")]
#[no_mangle]
pub extern "C" fn JNI_OnLoad(vm: jni::JavaVM, res: *mut std::os::raw::c_void) -> jni::sys::jint {
    use std::ffi::c_void;

    let vm = vm.get_java_vm_pointer() as *mut c_void;
    unsafe {
        ndk_context::initialize_android_context(vm, res);
    }
    jni::JNIVersion::V6.into()
}
```

Then, you would need to load in your library in your activity class.
```kotlin
// https://github.com/dart-lang/sdk/issues/46027
class MainActivity : FlutterActivity() {
    init {
        // note: this is the name of the library to load, like libCRATE_NAME_HERE.so
        System.loadLibrary("CRATE_NAME_HERE") 
    }
}
```

From there, as long as you're not missing anything else (like libc++_shared.so), it should be smooth sailing.

**Comment by powpingdone** [comment]
Should this be part of the guidebook?

**Comment by fzyzcjy** [comment]
Sure, feel free to PR!

**Comment by fzyzcjy** [comment]
For future readers: #1335 adds some doc explaining this problem and solution in details
