### ISSUE TITLE
[Bug] error[E0277]: the trait bound `EventToUI: IntoIntoDart<_>` is not satisfied

### ISSUE THREAD

**Issue by jrbpower** [fzyzcjy/flutter_rust_bridge#1328]
### Describe the bug

```
./flutter/ndk_arm64.sh
error[E0277]: the trait bound `EventToUI: IntoIntoDart<_>` is not satisfied
   --> src/flutter.rs:284:18
    |
284 |                 .add(EventToUI::Event(out)),
    |                  ^^^ the trait `IntoIntoDart<_>` is not implemented for `EventToUI`
    |
    = help: the following other types implement trait `IntoIntoDart<D>`:
              <() as IntoIntoDart<()>>
              <(A, B) as IntoIntoDart<(AD, BD)>>
              <(A, B, C) as IntoIntoDart<(AD, BD, CD)>>
              <(A, B, C, D) as IntoIntoDart<(AD, BD, CD, DD)>>
              <(A, B, C, D, E) as IntoIntoDart<(AD, BD, CD, DD, ED)>>
              <Box<T> as IntoIntoDart<T>>
              <DartCObject as IntoIntoDart<DartCObject>>
              <DartOpaque as IntoIntoDart<DartOpaque>>
            and 23 others
note: required by a bound in `StreamSink::<T>::add`
   --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge-1.81.0/src/rust2dart.rs:139:12
    |
137 |     pub fn add<D: IntoDart>(&self, value: T) -> bool
    |            --- required by a bound in this associated function
138 |     where
139 |         T: IntoIntoDart<D>,
    |            ^^^^^^^^^^^^^^^ required by this bound in `StreamSink::<T>::add`

error[E0277]: the trait bound `EventToUI: IntoIntoDart<_>` is not satisfied
   --> src/flutter.rs:291:20
    |
291 |             stream.add(EventToUI::Event("close".to_owned()));
    |                    ^^^ the trait `IntoIntoDart<_>` is not implemented for `EventToUI`
    |
    = help: the following other types implement trait `IntoIntoDart<D>`:
              <() as IntoIntoDart<()>>
              <(A, B) as IntoIntoDart<(AD, BD)>>
              <(A, B, C) as IntoIntoDart<(AD, BD, CD)>>
              <(A, B, C, D) as IntoIntoDart<(AD, BD, CD, DD)>>
              <(A, B, C, D, E) as IntoIntoDart<(AD, BD, CD, DD, ED)>>
              <Box<T> as IntoIntoDart<T>>
              <DartCObject as IntoIntoDart<DartCObject>>
              <DartOpaque as IntoIntoDart<DartOpaque>>
            and 23 others
note: required by a bound in `StreamSink::<T>::add`
   --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge-1.81.0/src/rust2dart.rs:139:12
    |
137 |     pub fn add<D: IntoDart>(&self, value: T) -> bool
    |            --- required by a bound in this associated function
138 |     where
139 |         T: IntoIntoDart<D>,
    |            ^^^^^^^^^^^^^^^ required by this bound in `StreamSink::<T>::add`

error[E0277]: the trait bound `EventToUI: IntoIntoDart<_>` is not satisfied
   --> src/flutter.rs:548:20
    |
548 |             stream.add(EventToUI::Rgba);
    |                    ^^^ the trait `IntoIntoDart<_>` is not implemented for `EventToUI`
    |
    = help: the following other types implement trait `IntoIntoDart<D>`:
              <() as IntoIntoDart<()>>
              <(A, B) as IntoIntoDart<(AD, BD)>>
              <(A, B, C) as IntoIntoDart<(AD, BD, CD)>>
              <(A, B, C, D) as IntoIntoDart<(AD, BD, CD, DD)>>
              <(A, B, C, D, E) as IntoIntoDart<(AD, BD, CD, DD, ED)>>
              <Box<T> as IntoIntoDart<T>>
              <DartCObject as IntoIntoDart<DartCObject>>
              <DartOpaque as IntoIntoDart<DartOpaque>>
            and 23 others
note: required by a bound in `StreamSink::<T>::add`
   --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge-1.81.0/src/rust2dart.rs:139:12
    |
137 |     pub fn add<D: IntoDart>(&self, value: T) -> bool
    |            --- required by a bound in this associated function
138 |     where
139 |         T: IntoIntoDart<D>,
    |            ^^^^^^^^^^^^^^^ required by this bound in `StreamSink::<T>::add`

For more information about this error, try `rustc --explain E0277`.
warning: `rustdesk` (lib) generated 1 warning
error: could not compile `rustdesk` (lib) due to 3 previous errors; 1 warning emitted
note: If the build failed due to a missing target, you can run this command:
note:
note:     rustup target install aarch64-linux-android

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
RUST_LOG=debug ./flutter/ndk_arm64.sh --verbose
    Building arm64-v8a (aarch64-linux-android)
warning: function `gen_flutter_rust_bridge` is never used
  --> build.rs:80:4
   |
80 | fn gen_flutter_rust_bridge() {
   |    ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `rustdesk` (build script) generated 1 warning
   Compiling rustdesk v1.2.2 (/home/dev/rustdesk/rustdesk)
warning: unused variable: `pde`
    --> src/server/connection.rs:1563:57
     |
1563 |                 Some(message::Union::PointerDeviceEvent(pde)) =>
     |                                                         ^^^ help: if this is intentional, prefix it with an underscore: `_pde`
     |
     = note: `#[warn(unused_variables)]` on by default

error[E0277]: the trait bound `EventToUI: IntoIntoDart<_>` is not satisfied
   --> src/flutter.rs:284:18
    |
284 |                 .add(EventToUI::Event(out)),
    |                  ^^^ the trait `IntoIntoDart<_>` is not implemented for `EventToUI`
    |
    = help: the following other types implement trait `IntoIntoDart<D>`:
              <() as IntoIntoDart<()>>
              <(A, B) as IntoIntoDart<(AD, BD)>>
              <(A, B, C) as IntoIntoDart<(AD, BD, CD)>>
              <(A, B, C, D) as IntoIntoDart<(AD, BD, CD, DD)>>
              <(A, B, C, D, E) as IntoIntoDart<(AD, BD, CD, DD, ED)>>
              <Box<T> as IntoIntoDart<T>>
              <DartCObject as IntoIntoDart<DartCObject>>
              <DartOpaque as IntoIntoDart<DartOpaque>>
            and 23 others
note: required by a bound in `StreamSink::<T>::add`
   --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge-1.81.0/src/rust2dart.rs:139:12
    |
137 |     pub fn add<D: IntoDart>(&self, value: T) -> bool
    |            --- required by a bound in this associated function
138 |     where
139 |         T: IntoIntoDart<D>,
    |            ^^^^^^^^^^^^^^^ required by this bound in `StreamSink::<T>::add`

error[E0277]: the trait bound `EventToUI: IntoIntoDart<_>` is not satisfied
   --> src/flutter.rs:291:20
    |
291 |             stream.add(EventToUI::Event("close".to_owned()));
    |                    ^^^ the trait `IntoIntoDart<_>` is not implemented for `EventToUI`
    |
    = help: the following other types implement trait `IntoIntoDart<D>`:
              <() as IntoIntoDart<()>>
              <(A, B) as IntoIntoDart<(AD, BD)>>
              <(A, B, C) as IntoIntoDart<(AD, BD, CD)>>
              <(A, B, C, D) as IntoIntoDart<(AD, BD, CD, DD)>>
              <(A, B, C, D, E) as IntoIntoDart<(AD, BD, CD, DD, ED)>>
              <Box<T> as IntoIntoDart<T>>
              <DartCObject as IntoIntoDart<DartCObject>>
              <DartOpaque as IntoIntoDart<DartOpaque>>
            and 23 others
note: required by a bound in `StreamSink::<T>::add`
   --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge-1.81.0/src/rust2dart.rs:139:12
    |
137 |     pub fn add<D: IntoDart>(&self, value: T) -> bool
    |            --- required by a bound in this associated function
138 |     where
139 |         T: IntoIntoDart<D>,
    |            ^^^^^^^^^^^^^^^ required by this bound in `StreamSink::<T>::add`

error[E0277]: the trait bound `EventToUI: IntoIntoDart<_>` is not satisfied
   --> src/flutter.rs:548:20
    |
548 |             stream.add(EventToUI::Rgba);
    |                    ^^^ the trait `IntoIntoDart<_>` is not implemented for `EventToUI`
    |
    = help: the following other types implement trait `IntoIntoDart<D>`:
              <() as IntoIntoDart<()>>
              <(A, B) as IntoIntoDart<(AD, BD)>>
              <(A, B, C) as IntoIntoDart<(AD, BD, CD)>>
              <(A, B, C, D) as IntoIntoDart<(AD, BD, CD, DD)>>
              <(A, B, C, D, E) as IntoIntoDart<(AD, BD, CD, DD, ED)>>
              <Box<T> as IntoIntoDart<T>>
              <DartCObject as IntoIntoDart<DartCObject>>
              <DartOpaque as IntoIntoDart<DartOpaque>>
            and 23 others
note: required by a bound in `StreamSink::<T>::add`
   --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge-1.81.0/src/rust2dart.rs:139:12
    |
137 |     pub fn add<D: IntoDart>(&self, value: T) -> bool
    |            --- required by a bound in this associated function
138 |     where
139 |         T: IntoIntoDart<D>,
    |            ^^^^^^^^^^^^^^^ required by this bound in `StreamSink::<T>::add`

For more information about this error, try `rustc --explain E0277`.
warning: `rustdesk` (lib) generated 1 warning
error: could not compile `rustdesk` (lib) due to 3 previous errors; 1 warning emitted
note: If the build failed due to a missing target, you can run this command:
note:
note:     rustup target install aarch64-linux-android
```

### Generated binding code

```shell
~/.cargo/bin/flutter_rust_bridge_codegen --skip-deps-check  --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart
2023/08/21 14:33:15 [INFO] Running cargo expand in '/home/dev/rustdesk/rustdesk/.'
2023/08/21 14:33:43 [INFO] Running cargo expand in '/home/dev/rustdesk/rustdesk'
2023/08/21 14:33:44 [INFO] Phase: Validate config(s)
2023/08/21 14:33:44 [INFO] Picked config: Opts { rust_input_path: "/home/dev/rustdesk/rustdesk/./src/flutter_ffi.rs", dart_output_path: "/home/dev/rustdesk/rustdesk/./flutter/lib/generated_bridge.dart", dart_decl_output_path: None, c_output_path: ["/tmp/.tmpvGsrS7.h"], rust_crate_dir: "/home/dev/rustdesk/rustdesk", rust_output_path: "/home/dev/rustdesk/rustdesk/./src/bridge_generated.rs", class_name: "Rustdesk", dart_format_line_length: 80, dart_enums_style: false, skip_add_mod_to_lib: false, llvm_path: ["/opt/homebrew/opt/llvm", "/usr/local/opt/llvm", "/usr/lib/llvm-9", "/usr/lib/llvm-10", "/usr/lib/llvm-11", "/usr/lib/llvm-12", "/usr/lib/llvm-13", "/usr/lib/llvm-14", "/usr/lib/", "/usr/lib64/", "C:/Program Files/llvm", "C:/msys64/mingw64"], llvm_compiler_opts: "", manifest_path: "/home/dev/rustdesk/rustdesk/Cargo.toml", dart_root: Some("/home/dev/rustdesk/rustdesk/./flutter"), build_runner: true, block_index: BlockIndex(0), skip_deps_check: true, wasm_enabled: false, inline_rust: false, bridge_in_method: true, extra_headers: "", dart3: true, keep_going: false }
2023/08/21 14:33:44 [INFO] Phase: Parse source code to AST, then to IR
2023/08/21 14:33:44 [INFO] Phase: Transform IR
2023/08/21 14:33:44 [INFO] Phase: Generate Rust code
2023/08/21 14:33:45 [INFO] Phase: Generate Dart code
2023/08/21 14:33:47 [INFO] Phase: Generating Dart bindings for Rust
the path is "/tmp/.tmpvGsrS7.h"
2023/08/21 14:34:09 [INFO] Phase: Running build_runner
2023/08/21 14:34:09 [INFO] Phase: Formatting Dart code
2023/08/21 14:34:12 [INFO] Success!
2023/08/21 14:34:12 [INFO] Now go and use it :)
```

### OS

linux ubuntu

### Version of `flutter_rust_bridge_codegen`

22.04

### Flutter info

```shell
flutter doctor -v
[✓] Flutter (Channel stable, 3.13.0, on Ubuntu 22.04.3 LTS 5.15.90.1-microsoft-standard-WSL2, locale C.UTF-8)
    • Flutter version 3.13.0 on channel stable at /home/dev/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (6 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/dev/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/127/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    ✗ Unable to determine VS Code version.

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 5.15.90.1-microsoft-standard-WSL2
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Version of `clang++`

15

### Version of `ffigen`

8.0.2

**Comment by fzyzcjy** [comment]
Hi, could you please provide a minimal reproducible sample code? Then it will be easier to find the bug.

**Comment by jrbpower** [comment]
I'm trying to build rustdesk version 1.2.2, Rust for Flutter on android. Following these steps https://rustdesk.com/docs/en/dev/build/android/

**Comment by jrbpower** [comment]
I'm trying to build rustdesk version 1.2.2, Rust for Flutter on android. Following these steps https://rustdesk.com/docs/en/dev/build/android/. Failed to execute this script "./flutter/ndk_arm64.sh".

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1326 I am not sure whether rustdesk has finished the migration

**Comment by CodeDoctorDE** [comment]
I have the same error: I have a tuple struct with three i32:
```rust
pub struct VisualBlockPosition(pub i32, pub i32, pub i32);
```

![grafik](https://github.com/fzyzcjy/flutter_rust_bridge/assets/20452814/b5db5cb1-0c6a-4da5-80d5-3345e9a4f028)

```
some of the expressions' fields have a method of the same name: `0.`, `1.`, `2.`rustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)
api.rs(73, 54): original diagnostic
no method named `into_into_dart` found for struct `message::VisualBlockPosition` in the current scope
items from traits can only be used if the trait is implemented and in scope
the following trait defines an item `into_into_dart`, perhaps you need to implement it:
candidate #1: `IntoIntoDart`rustc
message.rs(4, 1): method `into_into_dart` not found for this struct
api.rs(73, 54): some of the expressions' fields have a method of the same name: `0.`, `1.`, `2.`
```

**Comment by fzyzcjy** [comment]
@CodeDoctorDE Hi, could you please provide a minimal reproducible sample and create a new issue?

**Comment by CodeDoctorDE** [comment]
This struct should be the minimal example

**Comment by CodeDoctorDE** [comment]
I have this manager:
```rust

pub struct WorldManager {
    pub(crate) sink : RustOpaque<Mutex<Option<StreamSink<VisualBlockPosition>>>>,
}

impl WorldManager {
  ...
 pub fn send_message(&self, message: VisualBlockPosition) {
        let sink = self.sink.lock().unwrap();
        if let Some(s) = sink.as_ref() {
            s.add(message);
        }
    }
}

```
In line `s.add(message);` I get this long error message

**Comment by fzyzcjy** [comment]
implementation of IntoIntoDart should be automatically generated. I do hope that the issue template could be followed (which includes eg the generated rust code, so it is easier to debug. But anyway, I can make a guess now: Maybe the IntoIntoDart is not generated at all for tuples? Or, did you import those generated structs?

Feel free to PR to fix it!

Also cc @MnlPhlp who did the https://github.com/fzyzcjy/flutter_rust_bridge/pull/1285

**Comment by CodeDoctorDE** [comment]
> implementation of IntoIntoDart should be automatically generated. I do hope that the issue template could be followed (which includes eg the generated rust code, so it is easier to debug. But anyway, I can make a guess now: Maybe the IntoIntoDart is not generated at all for tuples? Or, did you import those generated structs?

I would want to give more details but the problem is: This error comes from cargo check and this prvents generating these bridge files.
The same error occurs when using a normal enum like:
```rust
pub enum NativeMessage {
    Hello,
    World
}
```
I don't know what I should try next.

**Comment by CodeDoctorDE** [comment]
Okay I have the solution:
Try generating these bindings file BEFORE using these classes in the code.
I comment this part of the code, generate the bindings and then uncomment it again and it works. Thanks for creating this library!

**Comment by fzyzcjy** [comment]
@CodeDoctorDE Happy to see the solution is found!

It would be great to mention this in the doc, are you interested in making a small PR to the docs?

**Comment by fzyzcjy** [comment]
@CodeDoctorDE 

> I would want to give more details but the problem is: This error comes from cargo check and this prvents generating these bridge files.

So, where did the `cargo check` run? Is it run from flutter_rust_bridge_codegen, or somewhere else?

**Comment by raphaelrobert** [comment]
I'm running into a similar behavior with `1.81`. `flutter_rust_bridge_codegen` either only generates a fraction of the required Rust code and claims all steps passed, or it hangs forever. I could point you to a public GitHub CI for reproducing the steps.
I noticed that `1.81` now requires `cargo-expand` to be installed and I wonder if that has anything to do with it.
Finally, the `cargo check` error about `IntoIntoDart<_>` not being found simply comes from the fact that the generated Rust code is missing almost entirely and that's the first error that cargo reports.

**Comment by fzyzcjy** [comment]
cc @MnlPhlp who introduced cargo-expand into the system (to allow arbitrary macros to be used, which is a helpful feature)

**Comment by fzyzcjy** [comment]
@raphaelrobert For your case, could you please provide a minimal reproducible sample? Thanks

**Comment by TaeHagen** [comment]
I'm experiencing this too, for me it happens with any struct or enum. Here's my minimal reproducable sample:
```
pub struct Test {
    pub test: String
}

pub fn add(left: usize, right: usize) -> Test {
    Test {
        test: "hello".to_string()
    }
}```

**Comment by TaeHagen** [comment]
It appears to never fix itself, even after trying CodeDoctorDe's solution, and I don't see the trait generated anywhere.

**Comment by fzyzcjy** [comment]
@TaeHagen Hi could you please make a self-contained minimal reproducible sample? Then it will be more clear which exact part in the system is going wrong

**Comment by TaeHagen** [comment]
https://github.com/TaeHagen/flutter-rust-bridge-repro

**Comment by LucaCoduriV** [comment]
I am also having this issue. It makes really hard to start coding on a new PC.

**Comment by TaeHagen** [comment]
So I figured out what the problem was. I was using flutter_rust_bridge 1.73.5 globally because my project is dart 2. However, in dependencies of my rust project, I specified `flutter_rust_bridge = "1"`. This caused a mismatch in versions and the generated code didn't line up with the library. I changed my library in cargo to `flutter_rust_bridge = "=1.75.3"` and now everything works. Note the leading = if you omit that it will still use the old version.

**Comment by fzyzcjy** [comment]
@TaeHagen Good fix!

@LucaCoduriV Could you please make a minimal reproducible sample? The same bug can have different causes

**Comment by LucaCoduriV** [comment]
> @TaeHagen Good fix!
> 
> @LucaCoduriV Could you please make a minimal reproducible sample? The same bug can have different causes

Yes I can try to do it if I understand the reason. I'll look into it when I have time. But for now I know that I have accidently fixed it once by tring to comment my code line by line. But how I said I was not excpecting it to work like that, I just was trying to understand why it did not compile but without success haha.
It was weeks ago and I don't remember exactly what I commented.

But now I need to code on an other computer and the same issue happen again. I first thaugt it was related to my first computer but it seems to not be the case.

**Comment by fzyzcjy** [comment]
@LucaCoduriV Looking forward to your reproducible sample! From your descriptions, does https://github.com/fzyzcjy/flutter_rust_bridge/issues/1328#issuecomment-1689285241 work for you?

**Comment by LucaCoduriV** [comment]
> @LucaCoduriV Looking forward to your reproducible sample! From your descriptions, does [#1328 (comment)](https://github.com/fzyzcjy/flutter_rust_bridge/issues/1328#issuecomment-1689285241) work for you?

Still not, I am not at home. I try it tomorrow. But just to be sure which part of the code was commented  ? Code related to flutter or code related to rust ?

**Comment by fzyzcjy** [comment]
the rust code

**Comment by raphaelrobert** [comment]
> @raphaelrobert For your case, could you please provide a minimal reproducible sample? Thanks

Some progress on my side:

Freezing issue: I managed to reproduce the state where `flutter_rust_bridge_codegen` freezes. This happens when it is executed twice at the same time. In my case, this is triggered by the fact that I build the bridge in `build.rs`. That seems to now get into a cyclic dependency where `flutter_rust_bridge_codegen` launches `cargo xxx` internally, which in turn executes `build.rs`, executing `flutter_rust_bridge_codegen` again.
I see why this is generally an issue and probably bad practice to build the bridge in `build.rs`. However, so far (before `1.81`) it hasn't been an issue and it was quite practical.

Missing generation issue: It looks like the issue is triggered by the fact that in my code for the bridge is behind a feature flag. This leads to the following error when running `flutter_rust_bridge_codegen`:

```
Error: Parser bug: lex error

Caused by:
    lex error
```

This is also specific to `1.81` and wasn't an issue in previous versions. @fzyzcjy I could build a minimal reproducible example for that if this is still of interest now that the error source is clearer.

**Comment by fzyzcjy** [comment]
> this is triggered by the fact that I build the bridge in build.rs

The code should have detected this and skip `cargo expand`, so this looks like a bug to be circular executed. It is perfectly fine to run in build.rs when you do not need cargo expand (i.e. no need for frb to understand macros)!

> Missing generation issue: It looks like the issue is triggered by the fact that in my code for the bridge is behind a feature flag. This leads to the following error when running flutter_rust_bridge_codegen:

Not very sure, so this means that, maybe we should not call `cargo expand`, but should call `cargo expand --your-flags` inside frb?

> This is also specific to 1.81 and wasn't an issue in previous versions.

https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/CHANGELOG.md#1810

#1320 from @MnlPhlp 

I think this feature is quite useful, because in the past there have been multiple requests (IIRC) to let frb to understand macros. I did not predict that this PR will introduce these bugs, but feel free to PR and improve it!

Or, the simplest workaround: maybe we can PR to make the `cargo expand` an opt-in (instead of opt-out) feature. Then, (1) these issues disappears (2) whoever wants frb to resolve macros can still enable this flag and use it happily

**Comment by MnlPhlp** [comment]
> > this is triggered by the fact that I build the bridge in build.rs
> 
> The code should have detected this and skip `cargo expand`, so this looks like a bug to be circular executed. It is perfectly fine to run in build.rs when you do not need cargo expand (i.e. no need for frb to understand macros)!
> 
> > Missing generation issue: It looks like the issue is triggered by the fact that in my code for the bridge is behind a feature flag. This leads to the following error when running flutter_rust_bridge_codegen:
> 
> Not very sure, so this means that, maybe we should not call `cargo expand`, but should call `cargo expand --your-flags` inside frb?
> 
> > This is also specific to 1.81 and wasn't an issue in previous versions.
> 
> https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/CHANGELOG.md#1810
> 
> #1320 from @MnlPhlp
> 
> I think this feature is quite useful, because in the past there have been multiple requests (IIRC) to let frb to understand macros. I did not predict that this PR will introduce these bugs, but feel free to PR and improve it!
> 
> Or, the simplest workaround: maybe we can PR to make the `cargo expand` an opt-in (instead of opt-out) feature. Then, (1) these issues disappears (2) whoever wants frb to resolve macros can still enable this flag and use it happily

I think the best would be to add a runtime flag that can change this behavior. opt-in or opt-out should both be fine. Probably opt-in is better because I think calling cargo-expand when not needed takes longer than just reading the file.

**Comment by MnlPhlp** [comment]
The part with 

> > @raphaelrobert For your case, could you please provide a minimal reproducible sample? Thanks
> 
> Some progress on my side:
> 
> Freezing issue: I managed to reproduce the state where `flutter_rust_bridge_codegen` freezes. This happens when it is executed twice at the same time. In my case, this is triggered by the fact that I build the bridge in `build.rs`. That seems to now get into a cyclic dependency where `flutter_rust_bridge_codegen` launches `cargo xxx` internally, which in turn executes `build.rs`, executing `flutter_rust_bridge_codegen` again. I see why this is generally an issue and probably bad practice to build the bridge in `build.rs`. However, so far (before `1.81`) it hasn't been an issue and it was quite practical.
> 
> Missing generation issue: It looks like the issue is triggered by the fact that in my code for the bridge is behind a feature flag. This leads to the following error when running `flutter_rust_bridge_codegen`:
> 
> ```
> Error: Parser bug: lex error
> 
> Caused by:
>     lex error
> ```
> 
> This is also specific to `1.81` and wasn't an issue in previous versions. @fzyzcjy I could build a minimal reproducible example for that if this is still of interest now that the error source is clearer.

Can you give more context to the freezing case? Just calling frb_codegen in build.rs should be fine and just skip the expand. That should even be covered by the ci tests.

**Comment by Alex-A4** [comment]
Same problem using enums from external packages.
This doesn't work with pure enums, but works with enums with values:

```rust
#[frb(mirror(MnemonicType))]
pub enum _MnemonicType {
    Legacy,
    Labs(u16),
}

/// WORKS
pub fn get_type() -> MnemonicType {
    MnemonicType::Legacy
}

#[frb(mirror(PollingMethod))]
pub enum _PollingMethod {
    Manual,
    Reliable,
}

/// DO NOT WORKS
pub fn get_method() -> PollingMethod {
    PollingMethod::Manual
}
```

**Comment by LucaCoduriV** [comment]
> Okay I have the solution: Try generating these bindings file BEFORE using these classes in the code. I comment this part of the code, generate the bindings and then uncomment it again and it works. Thanks for creating this library!

So I tried this and it seems to work.
But know I have an other issue:
```bash
Launching lib/main.dart on Linux in debug mode...
   Compiling native v0.1.0 (/home/luca/dev/Notiflut-Land/notiflut_daemon/native)
warning: variant `Stop` is never constructed
  --> src/daemon.rs:26:5
   |
24 | pub enum ChannelMessage<T> {
   |          -------------- variant in this enum
25 |     Message(T),
26 |     Stop,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: method `get` is never used
  --> src/desktop_file_manager.rs:37:12
   |
11 | impl DesktopFileManager {
   | ----------------------- method in this implementation
...
37 |     pub fn get(&self, name: &str) -> Option<DesktopFile> {
   |            ^^^

warning: `native` (lib) generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 1.83s
ERROR: ../../../.pub-cache/hosted/pub.dev/flutter_layout_grid-1.0.6/lib/src/widgets/placemen
t.dart:82:55: Error: A value of type 'RenderObject?' can't be assigned to a variable of type
 'AbstractNode?'.
ERROR:  - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../.loc
al/share/flutter/packages/flutter/lib/src/rendering/object.dart').
ERROR:  - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../.loca
l/share/flutter/packages/flutter/lib/src/foundation/node.dart').
ERROR:       final AbstractNode? targetParent = renderObject.parent;
ERROR:                                                       ^
ERROR: ../../../.pub-cache/hosted/pub.dev/flutter_layout_grid-1.0.6/lib/src/widgets/placemen
t.dart:83:58: Error: The method 'markNeedsPlacement' isn't defined for the class 'AbstractNo
de?'.
ERROR:  - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../.loca
l/share/flutter/packages/flutter/lib/src/foundation/node.dart').
ERROR: Try correcting the name to the name of an existing method, or defining a method named
 'markNeedsPlacement'.
ERROR:       if (targetParent is RenderLayoutGrid) targetParent.markNeedsPlacement();
ERROR:                                                          ^^^^^^^^^^^^^^^^^^
ERROR: ../../../.pub-cache/hosted/pub.dev/flutter_layout_grid-1.0.6/lib/src/widgets/placemen
t.dart:84:54: Error: The method 'markNeedsLayout' isn't defined for the class 'AbstractNode?
'.
ERROR:  - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../.loca
l/share/flutter/packages/flutter/lib/src/foundation/node.dart').
ERROR: Try correcting the name to the name of an existing method, or defining a method named
 'markNeedsLayout'.
ERROR:       if (targetParent is RenderObject) targetParent.markNeedsLayout();
ERROR:                                                      ^^^^^^^^^^^^^^^
ERROR: ../../../.pub-cache/hosted/pub.dev/flutter_layout_grid-1.0.6/lib/src/widgets/placemen
t.dart:132:55: Error: A value of type 'RenderObject?' can't be assigned to a variable of typ
e 'AbstractNode?'.
ERROR:  - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../.loc
al/share/flutter/packages/flutter/lib/src/rendering/object.dart').
ERROR:  - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../.loca
l/share/flutter/packages/flutter/lib/src/foundation/node.dart').
ERROR:       final AbstractNode? targetParent = renderObject.parent;
ERROR:                                                       ^
ERROR: ../../../.pub-cache/hosted/pub.dev/flutter_layout_grid-1.0.6/lib/src/widgets/placemen
t.dart:133:58: Error: The method 'markNeedsPlacement' isn't defined for the class 'AbstractN
ode?'.
ERROR:  - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../.loca
l/share/flutter/packages/flutter/lib/src/foundation/node.dart').
ERROR: Try correcting the name to the name of an existing method, or defining a method named
 'markNeedsPlacement'.
ERROR:       if (targetParent is RenderLayoutGrid) targetParent.markNeedsPlacement();
ERROR:                                                          ^^^^^^^^^^^^^^^^^^
ERROR: ../../../.pub-cache/hosted/pub.dev/flutter_layout_grid-1.0.6/lib/src/widgets/placemen
t.dart:134:54: Error: The method 'markNeedsLayout' isn't defined for the class 'AbstractNode
?'.
ERROR:  - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../../.loca
l/share/flutter/packages/flutter/lib/src/foundation/node.dart').
ERROR: Try correcting the name to the name of an existing method, or defining a method named
 'markNeedsLayout'.
ERROR:       if (targetParent is RenderObject) targetParent.markNeedsLayout();
ERROR:                                                      ^^^^^^^^^^^^^^^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Exception: Build process failed
```

Do you have an idea to solve this ?

**Comment by fzyzcjy** [comment]
@Alex-A4 This seems like a different bug (eg IntoIntoDart is not generated for that kind of type?) So could you please make a self-contained minimal reproducible sample and create a new issue so it is a bit easier to track and see what's going on
