### ISSUE TITLE
After upgrading to 1.81, the stream add error

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#1332]
fn cmd_msg(s: ResMsg) {
    if let Some(sink) = &*SEND_TO_DART_LOGGER_STREAM_SINK.read() {
        sink.add(s);
    }
}

**Comment by fzyzcjy** [comment]
Hi, could you please make a minimal reproducible sample? eg the current post does not reveal much info

**Comment by 107295472** [comment]
`the trait bound `system::models::dtos::ResMsg: flutter_rust_bridge::rust2dart::IntoIntoDart<_>` is not satisfied
the following other types implement trait `flutter_rust_bridge::rust2dart::IntoIntoDart<D>`:
  <() as flutter_rust_bridge::rust2dart::IntoIntoDart<()>>
  <(A, B) as flutter_rust_bridge::rust2dart::IntoIntoDart<(AD, BD)>>
  <(A, B, C) as flutter_rust_bridge::rust2dart::IntoIntoDart<(AD, BD, CD)>>
  <(A, B, C, D) as flutter_rust_bridge::rust2dart::IntoIntoDart<(AD, BD, CD, DD)>>
  <(A, B, C, D, E) as flutter_rust_bridge::rust2dart::IntoIntoDart<(AD, BD, CD, DD, ED)>>
  <[T; C] as flutter_rust_bridge::rust2dart::IntoIntoDart<[T; C]>>
  <bool as flutter_rust_bridge::rust2dart::IntoIntoDart<bool>>
  <chrono::datetime::DateTime<chrono::offset::local::Local> as flutter_rust_bridge::rust2dart::IntoIntoDart<chrono::datetime::DateTime<chrono::offset::local::Local>>>
and 22 othersrustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B2%5D?2#file%3A%2F%2F%2Fd%253A%2Fwork%2Frust%2Falctapi1%2Frust%2Ffltoolsrust%2Fsrc%2Fapi.rs)
rust2dart.rs(139, 12): required by a bound in `flutter_rust_bridge::StreamSink::<T>::add`
flutter_rust_bridge::rust2dart::StreamSink
pub fn add<D>(&self, value: T) -> bool
where
    D: IntoDart,
    T: IntoIntoDart<D>,
Add data to the stream. Returns false when data could not be sent, or the stream has been closed.`
