### ISSUE TITLE
[Bug] `ld: Undefined symbols`

### ISSUE THREAD

**Issue by AlexV525** [fzyzcjy/flutter_rust_bridge#1344]
### Describe the bug

I'm building a Flutter application with an FRB-based plugin but I got exceptions when trying to build an iOS application on my Intel Mac.

```
ld: Undefined symbols:
  _drop_dart_object, referenced from:
      _dummy_method_to_enforce_bundling in EnforceBundling.o
```

I've checked the following requirements:
1. **Strip Style** set to **Debug Symbols**.
2. `build-apple.sh` is similar to the one that suggested in the tutorial.
3. Produced `*.xcframework` under `library/packages/library_name/ios/Frameworks/`.
4. Other M1 Mac devices seem built successfully.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Seems not related.
```

### To Reproduce

1. Add `agent_dart` with the `bdk_lite` branch as a dependency.
2. Run generates in the `agent_dart` with `melos run build:apple`.
3. Run `flutter build ipa` in the Flutter project.

`agent_dart` with the branch `bdk_lite`: https://github.com/AstroxNetwork/agent_dart/tree/bdk_lite

### Expected behavior

Built without exceptions.

### OS

macOS 13.5

### Version of `flutter_rust_bridge_codegen`

1.81.0

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at /Users/alex/Documents/flutter-stable
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision f468f3366c (7 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1
```

### Version of `clang++`

Apple clang version 14.0.3 (clang-1403.0.22.14.1) Target: x86_64-apple-darwin22.6.0 Thread model: posix

### Version of `ffigen`

^8.0.2

### Additional context

I've found [a similar issue](https://github.com/fzyzcjy/flutter_rust_bridge/issues/50) but the README suggestion does not help the building process.

**Comment by fzyzcjy** [comment]
Hmm, that looks like a bug unrelated to frb but related to the environment. 

Firstly, I guess we can check whether the `_drop_dart_object` symbol is really there, i.e. is it somehow removed (or not generated at all) accidentally?

Secondly, does the tutorials/examples (without any modification) compilable on your machine? If so, it would be great to modify the provided examples/tutorials such that it fails, or create a minimal reproducible sample.

**Comment by AlexV525** [comment]
I've found the problem:

https://github.com/fzyzcjy/flutter_rust_bridge/blob/e248cbc2df2328043843a12d61fc551b004fb9a4/book/src/library/platform_setup/ios_and_macos.md?plain=1#L68-L77

In this part, the original `Frameworks/` will be removed and extracted from the archive whenever we run `pod install`. However, in `agent_dart`, we didn't make any corresponding releases, which led the xcframework to being missing during the build.

We might consider renaming the original `Frameworks/` to a backup folder `Frameworks.bak/` first, then determine whether the archive is valid before we delete the old one.

**Comment by AlexV525** [comment]
Additional info: The archive only has *9 bytes* when it fetches from GitHub without actually releasing artifacts.

**Comment by fzyzcjy** [comment]
Good observation!

cc @Desdaemon who made that tutorial - maybe we should update it?

**Comment by Desdaemon** [comment]
cc @GregoryConrad

**Comment by fzyzcjy** [comment]
Oh yes, I should check the `git blame`!

**Comment by GregoryConrad** [comment]
> However, in agent_dart, we didn't make any corresponding releases, which led the xcframework to being missing during the build.

The tutorial there assumes a release to GitHub with binaries for every version—if you aren’t doing that, you’ll have to modify the script accordingly. 

This process is really a PITA right now, but thankfully it should get substantially better once we get Native Assets and flutter will handle all of this build glue for us 🤞

**Comment by GregoryConrad** [comment]
Also, you definitely don’t want to keep around old versions, as you might be able to then get an older copy of your binary that’s incompatible with your dart code. If this project isn’t being released to pub, you could throw a  build-apple call in there. If it is released, you’ll need to do the GitHub releases or something similar.

**Comment by fzyzcjy** [comment]
Btw, my personal solution is as follows (if anyone is interested):

* Add a stage in Android/ios build system which calls a python script (or shell script or anything if you like)
* The python script handles everything about compiling rust, generate .a/.so etc

(Unfortunately, my script tights too deep with my own internal code infra, so it is very hard to extract and open source it; but anyway, the core idea is so simple that it can be easily implemented)

**Comment by AlexV525** [comment]
We don't have to think of all general solutions. One simple way to improve this is writing something like:
```bash
#!/bin/bash

if [ ! -f $local_zip_name ] 
then 
  curl -L $url -o $local_zip_name
fi
tempdir=$(mktemp -d)
unzip -q "local_zip_name" -d "$tempdir" >/dev/null 2>&1

# Validate unzip process result.
if [ $? -eq 0 ]; then
  echo "Unzip succeed."

  # Validate if extracted contents are empty.
  if [ -z "$(ls -A $tempdir)" ]; then
    echo "Empty archive."
  else
    (
    cd Frameworks
    rm -rf #{framework_name}
    cp -r $tempdir/ Frameworks/
    )
  fi

  rm -rf "$tempdir"
else
  echo "Corrupted archive."
fi
```

**Comment by GregoryConrad** [comment]
> One simple way to improve this is writing something like:

Based on my read of that script, it looks like that will not modify the Frameworks/ folder in case of failure. That would be incorrect, since in order to complete the build you must have the newest version of the XCFramework (otherwise you may get some really weird hard-to-debug errors). That’s why the rm -rf works well—building will fail if the latest binary isn’t downloaded/unzipped properly, albeit with an unintuitive symbols not found error message.

I don’t really see why the script should be modified much, other than to perhaps improve the error somehow, or to build the binaries locally (call build-apple) instead of trying to download them.

**Comment by GregoryConrad** [comment]
If you’re trying to test locally, manually put the zip file with the proper name in the location it expects and then it’ll use that one. It’s a bit of a nuisance but it works and how I’ve tested changes locally in the past. Typically though, I leave that to CI.

**Comment by AlexV525** [comment]
I do manually build the framework locally. So the improvement would be: chech whether there is a platform-built framework and link it during the pod install if the downloaded artifact is empty?

**Comment by AlexV525** [comment]
The solution I made is to copy frameworks after builds, which also requires some variables to change for the script. https://github.com/AstroxNetwork/agent_dart/blob/50dfd58cab2e6eb67ffbce0198cba3b163693c1c/scripts/build-apple.sh#L41-L45

If this is applicable, I'd suggest recommending the script for local builds.

**Comment by GregoryConrad** [comment]
For locally *only* builds (i.e., *never released to pub.dev*), I'd instead recommend just copy-pasting build-apple.sh into the podspec and changing up the locations/etc. as necessary to just output the XCFramework into `Frameworks/`. That'll build it automatically whenever you go to build your project and ensures you will never have stale versions.

If you are releasing to pub.dev, I'd modify build-apple to output the XCFramework zip with the proper name to `Frameworks/` and then leave the podspec as-is. Just be careful when doing this however, as you will have to manually call build-apple whenever the version number or rust code changes.

**Comment by AlexV525** [comment]
> For locally _only_ builds (i.e., _never released to pub.dev_), I'd instead recommend just copy-pasting build-apple.sh into the podspec and changing up the locations/etc. as necessary to just output the XCFramework into `Frameworks/`. That'll build it automatically whenever you go to build your project and ensures you will never have stale versions.

@GregoryConrad The idea is unavailable for scripts in podspec. As I mentioned and referenced, it has to be done during builds, because the podspec only knows about the package itself, rather than the whole mono-repo structure. After the change, I got the latest built artifacts too.

Closing, as the issue is not a standardized procedure issue for a *releasable* project, and advice is mainly off-topic which leads to inefficient conversations. I'd rather submit a PR some days after.

**Comment by GregoryConrad** [comment]
> The idea is unavailable for scripts in podspec. As I mentioned and referenced, it has to be done during builds, because the podspec only knows about the package itself, rather than the whole mono-repo structure. After the change, I got the latest built artifacts too.

@AlexV525 You're given a full shell to work with, and the benefit of running locally only. Thus, you can pop something like this at the top of the podspec above the existing script:
```bash
# insert the following (including the parens) above the existing script in the podspec
(
  cd /Users/username/path/to/monorepo # should also be able to do something in relation to home directory too with ~/ if you want
  bash scripts/build-apple.sh
  # copy XCFramework zip with proper name to the Frameworks/ folder
)

# existing podspec code from tutorial...
```

Alternatively, you can symlink the absolute path to the monorepo into the ios/macos folders, but that seems more error prone and I'd suggest doing the above
