### ISSUE TITLE
Updated to 1.82, this error appears

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#1367]
The named parameter 'parseErrorData' is required, but there's no corresponding argument.
Try adding the required argument.

**Comment by fzyzcjy** [comment]
Hi, could you please provide a minimal sample? In addition, does 1.81 have this probelm?

**Comment by 107295472** [comment]
1.81 No, use the gen generated by just:
      flutter_rust_bridge_codegen \
         --rust-input rust/fltoolsrust/src/api.rs \
         --dart-output lib/api/bridge_generated.dart \
         --dart-decl-output lib/api/bridge_definitions.dart \
         --wasm

**Comment by 107295472** [comment]
My problem is that the generator has not been upgraded.

**Comment by bubnov** [comment]
> My problem is that the generator has not been upgraded.
@107295472 could you plz explain how exactly you've fixed the error? In my generated files I seeing "Generated by `flutter_rust_bridge`@ 1.79.0.", but the frb was updated to v1.82.1:

![CleanShot 2023-10-01 at 13 05 51@2x](https://github.com/fzyzcjy/flutter_rust_bridge/assets/818612/4d176139-c792-4560-9542-a4a6feb11ad9)

**Comment by 107295472** [comment]
> Ok, I managed to fix the issue. Just re-installed the `flutter_rust_bridge_codegen` from the scratch.

The version needs to be the same

**Comment by 107295472** [comment]
cargo install flutter_rust_bridge_codegen, it seems to be an upgrade

**Comment by OfficialBoyfriend** [comment]
```rust
pub fn require_run_lock(sink: StreamSink<()>) -> Result<()> {
    if RUNLOCK.load(Ordering::Relaxed) {
        return Err(anyhow::Error::msg("already require run lock"));
    }
    RUNLOCK.store(true, Ordering::Relaxed);

    Ok(())
}
```

The above code can throw error messages on the Dart side normally in 1.81.0. After upgrading to 1.82.1, you will only receive `Exception: tried to parse data but function is null`. It seems to be caused by `parseErrorData: null`. Is this the expected and correct behavior?  @fzyzcjy

**Comment by fzyzcjy** [comment]
@OfficialBoyfriend Feel free to create a new issue and show a minimal reproducible sample with logs etc!
