### ISSUE TITLE
[very silly suggestion] rename the project stardust

### ISSUE THREAD

**Issue by iapicca** [fzyzcjy/flutter_rust_bridge#1381]
### Proposal

Rename `flutter_rust_bridge` -> `stardust`

(When I asked chatGPT a name for a project that uses both dart and rust
it suggested `stardust`, my first thought was "it's too perfect, I don't deserve it!")

### Reasoning

1. the word `stardust` is the anagram of `dart` + `rust`
2. `flutter_rust_bridge` suggests that targets `flutter` while can be used for pure dart projects as well
3. `*_bridge` screams `react-native`

**Comment by fzyzcjy** [comment]
Thanks for the suggestion! Personally speaking, I prefer a bit clear names that represent what is going on; and since https://pub.dev/packages/flutter_rust_bridge is a flutter-favorite package now, I do not want to rename anything to lose it ;)

**Comment by iapicca** [comment]
> Thanks for the suggestion! Personally speaking, I prefer a bit clear names that represent what is going on; and since https://pub.dev/packages/flutter_rust_bridge is a flutter-favorite package now, I do not want to rename anything to lose it ;)

Fair enough, I will not feel sad to use the name than.
Closing the issue
