### ISSUE TITLE
callback to flutter from rust

### ISSUE THREAD

**Issue by tGrothmannFluffy** [fzyzcjy/flutter_rust_bridge#1385]
Hi, and thank you very much for your work!

**Is your feature request related to a problem? Please describe.**
Is there a way one could register a callback from flutter which is then called from rust. 

**Describe alternatives you've considered**
Right now I am polling for some events happening in rust but I would rather just like to have callback.

**Additional context**
I am not really sure if this already exists; or if this might be kind of impossible.

Thanks!

**Comment by fzyzcjy** [comment]
Firstly, you may use the `Stream` feature.

Secondly, IIRC someone has proposed similar questions before in the issue section, and it looks possible to do that. If the `Stream` does not satisfy your need, feel free to ask for more info about this!
