### ISSUE TITLE
[Bug]  Breaking change introduced required parameter `parseErrorData` to `FlutterRustBridgeSyncTask ` in a minor version increase.

### ISSUE THREAD

**Issue by juancastillo0** [fzyzcjy/flutter_rust_bridge#1386]
### Describe the bug

Hi! Thank for your work!

Breaking change introduced required parameter `parseErrorData` to `FlutterRustBridgeSyncTask ` in a minor version increase.

Uploaded packages errors out since the latest version contains the required parameter, but the generated code uploaded to pub.dev was generated with a previous version.

I am not sure if this package follows semver, but I could not find documentation for it (or the way the versions represent breaking changes) and the suggested version constraint in the [template](https://github.com/Desdaemon/flutter_rust_bridge_template/blob/2732a7f31d0cae9d9e3f33e162807a915e7623f7/pubspec.yaml#L38) is open (^) as if following semver.

Thanks again

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Failed to load "test/wasm_interface_test.dart":
  lib/src/bridge_generated.dart:1949:59: Error: Required named parameter 'parseErrorData' must be provided.
      return _platform.executeSync(FlutterRustBridgeSyncTask(
                                                            ^
/opt/hostedtoolcache/flutter/beta-3.15.0-15.2.pre-x64/.pub-cache/hosted/pub.dev/flutter_rust_bridge-1.82.1/lib/src/basic.dart:205:9: Context: Found this candidate, but the arguments don't match.
    const FlutterRustBridgeSyncTask({
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  lib/src/bridge_generated.dart:1966:57: Error: Required named parameter 'parseErrorData' must be provided.
      return _platform.executeNormal(FlutterRustBridgeTask(
                                                          ^
```

### To Reproduce

Use version 1.70 to generate the bindings and then use version 1.80 to run the code

**Comment by fzyzcjy** [comment]
You are absolutely right! It is a problem that frb does not strictly follow semver, I will try to follow in the future when possible.

There are some problems though: Currently, I hope to keep the Rust and Dart's frb's versions exactly the same to make it simpler to use the correct version. Then, if the Dart side make a breaking change, and we follow semver, then the Rust side will have to be bumped to 2.x even if the Rust side has no breaking change. Then comes the problem: Years ago I was faced with the limit https://github.com/rust-lang/cargo/issues/5640 (and it seems not implemented yet), thus end users cannot easily specify dependency overrides if we make a major version bump in rust. That will not be a super convenient feature to have :/
