### ISSUE TITLE
[Bug] Err returned in Rust not properly passed to Dart

### ISSUE THREAD

**Issue by OfficialBoyfriend** [fzyzcjy/flutter_rust_bridge#1389]
### Describe the bug

After upgrading to version 1.82.1, the Err returned by a function signature containing a StreamSink was not correctly passed to Dart.

For example, the following Rust code:
```rust
pub fn require_run_lock(_sink: StreamSink<()>) -> Result<()> {
     return Err(anyhow::Error::msg("already require run lock"));
}
```

In 1.81.0, the exception information thrown by Dart is `FfiException(RESULT_ERROR, already require run lock, null)`

In 1.82.1, the exception message thrown by Dart is `Exception: tried to parse data but function is null`

Here is a minimal example to reproduce the issue: https://github.com/OfficialBoyfriend/rust_demo, just switch to 1.82.1 to revert the issue.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
-
```

**Comment by fzyzcjy** [comment]
Looks like a bug. This looks similar to https://github.com/fzyzcjy/flutter_rust_bridge/issues/1387, and the cause may be that, after merging the PR of enhanced error handling, there are some problematic edge cases.

Feel free to PR (this looks not very hard to fix)! The first step may be to add a test case in this repository, and then debug that test case to see why "tried to parse data but function is null" is thrown and fix it.

**Comment by randsoy** [comment]
@OfficialBoyfriend 我看了你的主页，你是四川的？我看了你的技术栈和我差不多，可以多多交流学习。。。
