### ISSUE TITLE
Unable to generate dynamic library

### ISSUE THREAD

**Issue by rebaz94** [fzyzcjy/flutter_rust_bridge#1394]
I cloned this [repository](https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/with_flutter). After performing the steps to integrate the project with Xcode and generating the bridge bindings as described in the documentation, I encountered an issue when running the application on macOS. The error message suggests a problem loading the dynamic library 'libflutter_rust_bridge_example.so.'

**Steps to Reproduce:**

1. Clone the repository: https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/with_flutter

2. Integrate the project with Xcode following the steps outlined in [https://cjycode.com/flutter_rust_bridge/integrate/ios_linking.html](https://cjycode.com/flutter_rust_bridge/integrate/ios_linking.html).

<img width="756" alt="Screenshot 2023-10-12 at 3 56 39 PM" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/11982812/240ef645-6e6a-41de-9ba6-d9a10425d7f2">

<img width="644" alt="Screenshot 2023-10-12 at 3 57 23 PM" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/11982812/a62e8bf8-bc68-467e-9395-adf6fc61beca">

4. Generate the bridge bindings using the `just _generate_bridge_with_flutter` command.

5. Run the application on macOS.

**Expected Behavior:**

I expected the application to run successfully on macOS after the integration and bridge binding generation.

**Actual Behavior:**

Upon running the application on macOS, I encountered the following error message:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libflutter_rust_bridge_example.so': dlopen(libflutter_rust_bridge_example.so, 0x0001): tried: 'libflutter_rust_bridge_example.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibflutter_rust_bridge_example.so' (no such file), '/Users/rebo/Desktop/flutter_rust_bridge/frb_example/with_flutter/build/macos/Build/Products/Debug/with_flutter.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/./libflutter_rust_bridge_example.so' (no such file), '/Users/rebo/Desktop/flutter_rust_bridge/frb_example/with_flutter/build/macos/Build/Products/Debug/with_flutter.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/../../../libflutter_rust_bridge_example.so' (no such file), '/Users/rebo/Desktop/flutter_rust_bridge/frb_example/with_flutter/build/macos/Build/Products/Debug/with_flutter.app/Contents/Frameworks/libflutter_rust_bridge_example.so' (no such file), '/Users/rebo/Desktop/flutter_rust_bridge/frb_example/with_flutter/build/macos/Build/Products/Debug/with_flutter.app/Contents/MacOS/Frameworks/libflutter_rust_bridge_example.so' (no such file), '/Users/rebo/Desktop/flutter_rust_bridge/frb_example/with_flutter/build/macos/Build/Products/Debug/with_flutter.app/Contents/Frameworks/libflutter_rust_bridge_example.so' (no such file), '/usr/lib/libflutter_rust_bridge_example.so' (no such file, not in dyld cache), 'libflutter_rust_bridge_example.so' (no such file), '/usr/local/lib/libflutter_rust_bridge_example.so' (no such file), '/usr/lib/libflutter_rust_bridge_example.so' (no such file, not in dyld cache)
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
no needed
```

### OS

MacOS

### Flutter info

```shell
Flutter (Channel stable, 3.13.6, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-US)
    • Flutter version 3.13.6 on channel stable at
      /Users/rebo/fvm/versions/stable
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision ead455963c (2 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/rebo/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F770820d
      darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.
```

**Comment by OfficialBoyfriend** [comment]
On macOS `libflutter_rust_bridge_example.dylib` should be loaded instead of `libflutter_rust_bridge_example.so`, which may be the reason.

**Comment by fzyzcjy** [comment]
Hi, could you please check whether the files (dylib or so) is already there?

**Comment by rebaz94** [comment]
Hi @fzyzcjy
Inside the build folder contain only **dylib**
`../flutter_rust_bridge/frb_example/with_flutter/build/macos/Build/Products/Debug/flutter_rust_bridge_example.dylib`.

**Comment by fzyzcjy** [comment]
Hmm, could you please try https://github.com/Desdaemon/flutter_rust_bridge_template and see whether it works

**Comment by rebaz94** [comment]
I've discovered that the Flutter application on macOS runs in a sandboxed environment, which means that you can't access dynamic libraries from just anywhere on your system, except from specific locations or bundle it in your app.

Even if I have access to the full system, the `ffi.dart` unable to find dynamic library.

For development purposes, I've removed the app sandbox capability and updated the ffi.dart file as follows:
```
const base = 'flutter_rust_bridge_example';
final path = Platform.isWindows ? '$base.dll' : 'lib$base.so';
//late final dylib = loadLibForFlutter('/Desktop/flutter_rust_bridge/frb_example/with_flutter/build/macos/Build/Products/Debug/flutter_rust_bridge_example.dylib');
late final api = FlutterRustBridgeExampleImpl(dylib);
```

this work but I can't generate **.so** library
