### ISSUE TITLE
using RustOpaque got `cannot move out of self.item which is behind a shared reference`

### ISSUE THREAD

**Issue by Jhonfunk** [fzyzcjy/flutter_rust_bridge#1402]
api.rs 
```rust
trait X {
  fn foo();
}

struct A {
}

impl X for A {
  fn foo() {
    print!("foo called");
  }
}

pub struct B {
  pub item: RustOpaque<A>,
}

impl B {
  pub fn new() -> B {
    B{item: RustOpaque::new(A{})}
  }
  pub fn test(&self) {
    let a = b.item.try_unwrap(); // cannot move out of `self.item` which is behind a shared reference
    a.foo();
  }
}

```

Is there any way  i can call `A.foo()` besides  `.clone()` and `implement the Copy trait`?
`A` is a struct that contains a lot of data, I don't want to copy it every time.
And I don't want to expose `A` to Dart.

**Comment by fzyzcjy** [comment]
That sounds like a classical Rust question IMHO. There are many ways. For example, change your code such that you do not move out `item` from `b` (but just borrow it)

**Comment by fzyzcjy** [comment]
Since this is about standard Rust not flutter_rust_bridge, I will close it, but feel free to reopen!
