### ISSUE TITLE
Support Tokenizer

### ISSUE THREAD

**Issue by flutter-painter** [fzyzcjy/flutter_rust_bridge#1403]
I encountered the error : "not yet implemented: generate code for type "Tokenizer""

While running flutter_rust_bridge_codegen....

**Comment by fzyzcjy** [comment]
Hi, it would be great to give a minimal reproducible sample, especially what the "Tokenizer" type is

**Comment by flutter-painter** [comment]
Hi,
Thank you for your quick reply,
I encountered this while bridging a rust model from [candle](https://github.com/huggingface/candle).
I assume Tokenizer type comes from https://docs.rs/tokenizers/latest/tokenizers/

Here is how it is declared in the cargo.toml
tokenizers = { version = "0.13.4", features = ["onig"] }

The goal is to use the bridge to extend the amount of ML models that can be used in flutter.
My assumption is that this will be lighter and faster than tensorflow lite.
Also it would make it possible to use the model in windows, something not possible with tf lite.

I will also share the whole repo so you can reproduce, it is quite heavy...

**Comment by flutter-painter** [comment]
Here is the repo : https://github.com/flutter-painter/flutter_rust_bridge_candle

**Comment by fzyzcjy** [comment]
Hi, I see. Then it would be great to make a minimal reprodicuble sample. For example, I guess it can be caused by using a type that is in external crate? Then you need https://cjycode.com/flutter_rust_bridge/feature/lang_external.html

**Comment by flutter-painter** [comment]
Thank you for your quick reply and clear guideline.
The reproductible sample is the repo [flutter_rust_bridge_candle](https://github.com/flutter-painter/flutter_rust_bridge_candle)
if you clone it and run the codegen command you will encounter the error.
I just updated the main to use marian model which has lighter dependencies,
So now the error is : _not yet implemented: generate code for type "Device"_

The [rust file](https://github.com/flutter-painter/flutter_rust_bridge_candle/blob/main/native/src/api.rs) has the following dependencies :


```rust
#[cfg(feature = "mkl")]
extern crate intel_mkl_src;

#[cfg(feature = "accelerate")]
extern crate accelerate_src;

use anyhow::Error as E;
use clap::{Parser, ValueEnum};
use candle_core::{DType, Device, Tensor};
use candle_nn::VarBuilder;
use tokenizers::Tokenizer;
mod marian;
```

I am correct assuming that the mirroring trick should be done for all dependencies ?

**Comment by flutter-painter** [comment]
Hi,
No need for this, it was all about removing pub where not needed and also replacing args with hardcoded stuff.
Thank you for support, kudo to the unstoppable sacha arbonnel

**Comment by fzyzcjy** [comment]
You are welcome! Btw, curious what is the meaning of that phrase (I searched but seems no results)

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/5236035/616efd11-49dd-4383-911e-b13ad1e3e3c5)

**Comment by flutter-painter** [comment]
What->Who
https://github.com/sachaarbonel

**Comment by fzyzcjy** [comment]
Oh I see :) My English is pretty bad that I misinterpret it as some phrase
