### ISSUE TITLE
[Bug] windows - corrosion found no targets in 1 packages

### ISSUE THREAD

**Issue by flutter-painter** [fzyzcjy/flutter_rust_bridge#1414]
### Describe the bug

Hi,

Please help

> CMake Error at /flutter_rust_bridge/build/windows/_deps/corrosion-src/cmake/CorrosionGenerator.cmake:287 (message):
>   Found no targets in 1 packages..
> 
>   Please keep in mind that corrosion will only import Rust `bin` targets
>   or`staticlib` or `cdylib` library targets.The following packages were found
>   in the Manifest: native
> Call Stack (most recent call first):
> .../build/windows/_deps/corrosion-src/cmake/Corrosion.cmake:1011 (_generator_add_cargo_targets)
>   rust.cmake:17 (corrosion_import_crate)
>   CMakeLists.txt:59 (include)CMake Error at .../build/windows/_deps/corrosion-src/cmake/CorrosionGenerator.cmake:287 (message):
>   Found no targets in 1 packages..
> 
>   Please keep in mind that corrosion will only import Rust `bin` targets
>   or`staticlib` or `cdylib` library targets.The following packages were found
>   in the Manifest: native
> Call Stack (most recent call first):
> .../build/windows/_deps/corrosion-src/cmake/Corrosion.cmake:1011 (_generator_add_cargo_targets)
>   rust.cmake:17 (corrosion_import_crate)
>   CMakeLists.txt:59 (include)

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
I use basic flutter_rust_bridge_template
```

**Comment by fzyzcjy** [comment]
Hi, this seems like corrosion + rust configuration problem (thus unrelated to frb core indeed). Have you tried the frb_example and the flutter_rust_bridge_template on your machine?

**Comment by fzyzcjy** [comment]
> Please keep in mind that corrosion will only import Rust bin targets
orstaticlib or cdylib library targets.The following packages were found

I guess this may because the Cargo.toml needs some modification, e.g. a proper `[lib]` section. 
In addition, you can try v2's `flutter_rust_bridge_generate create` which automatically setup things.
Without more information, I will close this issue, but feel free to reopen!
