### ISSUE TITLE
Implement code generation for the type "char"

### ISSUE THREAD

**Issue by starovoid** [fzyzcjy/flutter_rust_bridge#1419]
It would be nice to implement code generation for the `char` type, and I'm surprised why it's still absent.

In my project, I use a structure from an external crate which containing a `char` filed, and mirroring it with replacing `char` with `String` requires manual editing of the code in the files "bridge_generated.io.rs " and "bridge_generated.rs".

What difficulties can there be when generating code for `char` and what type in the Dart language should it correspond to: `int` or `String`?

**Comment by fzyzcjy** [comment]
Looks reasonable - that should be trivial to implement indeed.

However, I am working on frb 2.0 (hopefully done within a week or two?), and thus do not suggest to make any PRs to the 1.x branch now. When 2.0 is released, feel free to ping me again and this should be easily implementable / PRable!

**Comment by fzyzcjy** [comment]
2.0 (beta) is released, feel free to have a look :)
