### ISSUE TITLE
CPATH alternative on Arch or non-debian Linux

### ISSUE THREAD

**Issue by trobanga** [fzyzcjy/flutter_rust_bridge#1421]
This is more or less a continuation of #1375.

I used `export CPATH=="$(clang -v 2>&1 | grep "Selected GCC installation" | rev | cut -d' ' -f1 | rev)/include"` from https://cjycode.com/flutter_rust_bridge/integrate/deps.html .
However, to build to Android one has to use an include dir from the Android NDK.
Further, I think a more elegant solution, especially when using build.rs, is to pass the include directory to frb_codegen directly via Opts.

```rust
fn llvm_config() -> PathBuf {
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();
    if target_os == "android" {
        let mut ndk: PathBuf = env::var("ANDROID_NDK_HOME").unwrap().into();
        ndk.push("toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-config");
        ndk
    } else {
        "llvm-config".into()
    }
}

// Add clang lib include path to llvm_compiler_opts.
// libs/clang/$LLVM_VERSION/include
// Newer versions of clang only use the major version for LLVM_VERSION.
fn llvm_compiler_opts() -> Option<String> {
    let llvm_version = Command::new(llvm_config())
        .arg("--version")
        .output()
        .unwrap();
    let llvm_version = llvm_version.stdout;
    let llvm_version = std::str::from_utf8(&llvm_version[..llvm_version.len() - 1]).unwrap();
    let llvm_main_version = llvm_version.split(".").next().unwrap();

    let llvm_libdir = Command::new(llvm_config())
        .arg("--libdir")
        .output()
        .unwrap();
    let llvm_libdir = llvm_libdir.stdout;
    let llvm_libdir = std::str::from_utf8(&llvm_libdir[..llvm_libdir.len() - 1]).unwrap();
    Some(format!("-I{llvm_libdir}/clang/{llvm_version}/include -I{llvm_libdir}/clang/{llvm_main_version}/include"))
}

// Then something like this

    // Options for frb_codegen
    let raw_opts = RawOpts {
        llvm_compiler_opts: llvm_compiler_opts(),        
        ..Default::default()
    };

    // Generate Rust & Dart ffi bridges
    let configs = config_parse(raw_opts);
    let all_symbols = get_symbols_if_no_duplicates(&configs).unwrap();
    for config in configs.iter() {
        frb_codegen(config, &all_symbols).unwrap();
    }

```

If you agree I would add a section to the documentation.

**Comment by fzyzcjy** [comment]
Thank you for the information! I am working on flutter_rust_bridge 2.0, and will refactor the whole thing. Therefore, I personally suggest that you wait a little bit of time (hopefully no longer than a few weeks when 2.0 is published), and see whether the new system still have the thing you want to add. However, if you PR now, I can also review and merge it to master (while manually move the doc to 2.0 later).

**Comment by trobanga** [comment]
In that case I will wait. Since you are refactoring...I was thinking that the selection and checking of llvm related paths could be done inside frb. I also found some code that goes into that direction but I did not follow it further.

**Comment by fzyzcjy** [comment]
That sounds reasonable!

>  I also found some code that goes into that direction but I did not follow it further.

Just curious, what is that code

**Comment by trobanga** [comment]
It's `get_llvm_paths()` in opts_parser.rs, but it just sets/guesses the llvm path.

**Comment by fzyzcjy** [comment]
(Since I mentioned the v2 thing before, v2 has released now :) )

**Comment by trobanga** [comment]
Oh, somehow misssed your last comment.

I thought about this a little but I'm not sure what's the best approach.

I am pretty sure that this line adds the clang header files from the system installation:
`export CPATH=="$(clang -v 2>&1 | grep "Selected GCC installation" | rev | cut -d' ' -f1 | rev)/include" `,
which can lead to problems when building for Android, if the system clang is a different version than the one from the Android toolchain. Or to be more precise if their header files are incompatible.

That's why I'm using the above functions to get the correct compiler_opts using llvm_config.

So maybe it's enough to add it to the documentation or codegen could add the include path automatically.

**Comment by fzyzcjy** [comment]
> which can lead to problems when building for Android, if the system clang is a different version than the one from the Android toolchain. Or to be more precise if their header files are incompatible.
That's why I'm using the above functions to get the correct compiler_opts using llvm_config.

Hmm I am not very sure. If I understand correctly, we are executing frb_codegen here. It is a precompiled binary (thus no changeable CARGO_CFG_TARGET_OS), and generates static code. So I guess it is not a problem to worry about platform differences.

**Comment by trobanga** [comment]
Well, what can I say...I tried to reproduce the error (#1375) but it disappeared, even for frb 1.
So, I guess we can close this issue for now and come back if it comes back.
