### ISSUE TITLE
[Bug] 1.82.4 SyncReturn Unsupported message

### ISSUE THREAD

**Issue by ZR233** [fzyzcjy/flutter_rust_bridge#1422]
### Describe the bug

my code works fine on 1.82.3
```rust
pub fn distance_meter_between(p1: Position, p2: Position)->SyncReturn<f64>{
    SyncReturn(p1.distance_to(&p2))
}
```
when update flutter and cargo package to 1.82.4，and regen code with 1.82.4 gen，flutter side throw: `Exception: Unsupported message, action=5266.679071959847 raw=[5266.679071959847, true]`

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
log is too long to commit.

#[frb(mirror(Position))]
pub struct _Position {
    pub latitude: f64,
    pub longitude: f64,
}

pub fn distance_meter_between(p1: Position, p2: Position)->SyncReturn<f64>{
    SyncReturn(p1.distance_to(&p2))
}
```

**Comment by fzyzcjy** [comment]
Given https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/CHANGELOG.md, It seems that this is related to #1407 from @rogurotus.

I am working on flutter_rust_bridge 2.0, and hopefully it can be released within a week or two. Thus, I personally suggest to wait a bit before 2.0 is released and come to this issue again :) But you are also free to fix this in v1.0!

**Comment by rogurotus** [comment]
It looks like you haven't updated the version in .yaml

**Comment by ZR233** [comment]
after clean all project, it works.

**Comment by fzyzcjy** [comment]
Since this seems to be fixed, I will close it :)
