### ISSUE TITLE
Adding ASAN (Address Sanitizer) in addition to existing Valgrind

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#1423]
### Background

More checks can increase our confidence that everything is going well, thus it would be great to add ASAN / MSAN / ... in addition to the Valgrind we are already using today. When working on flutter_rust_bridge v2, I am wondering whether we can add ASAN to our CI progress.

### Discussions

/cc @Desdaemon - IIRC you have already integrated ASAN into frb before, but I guess you forget to push the script code to github :) Anyway it does not matter to make the exact code runnable on frb v1, since v2 has overhauled the directory structure / scripting / CI etc. Instead, it is sufficient to just post the rough code, and I will continue on it.

**Comment by Desdaemon** [comment]
The only blocker to running a ASan-enabled Dart VM is having to compile the VM itself. It takes a bit of time and space so it's better to run on CI, so that could be the first step towards making this work.

Otherwise, it requires some tricks to have ASan work on a library from a non-ASan binary. Dart VM uses tcmalloc which ASan and friends mess up really easily, but I assume it would be desirable to debug usage of the library as well. I tried using ASan as a shared library and that experiment didn't go anywhere, but might be worth revisiting it.

**Comment by fzyzcjy** [comment]
Tried a little bit: https://github.com/dart-lang/sdk/issues/54193

(I simply follows steps in dart wiki using a github action runner, and it works pretty well and generate the outputs. But then comes that issue.)

**Comment by Desdaemon** [comment]
Admittedly I've only run the instrumented VM and have never tried compiling in AOT mode. The issue you mentioned doesn't seem to be listed elsewhere, but I'll take a stab at it later today.

**Comment by fzyzcjy** [comment]
It's OK! I opened the issue in dart repo, because I see they have some dart-aot-asan test, so I guess that may be something they are already using in their infra, so we only need to ask and/or find out what's that.

**Comment by fzyzcjy** [comment]
The JIT seems working now :)

**Comment by fzyzcjy** [comment]
@Desdaemon By the way (unrelated to this issue), do you remember which exact place this https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_rust/src/wasm_bindgen_src/transfer.rs comes from wasm_bindgen? I have tried to search some code snippets in this file without results in wasm_bindgen's code. If it is indeed written by you, then I can move it out of the folder "wasm_bindgen_src".

**Comment by Desdaemon** [comment]
@fzyzcjy It's from https://github.com/rustwasm/wasm-bindgen/blob/main/examples/raytrace-parallel/src/pool.rs, but some functions are renamed and include local changes.
