### ISSUE TITLE
Use FRB together with the Bazel build system

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#1424]
In the current version, the `flutter_rust_bridge_codegen` invokes Cargo directly to accomplish tasks. It reads various files from various directories to pick up inputs with minimal configuration. This is great for being easy and idiomatic for Rust-centric projects, but for polyglot/monorepo projects built with tools like Bazel, it is less convenient. It Would Be Nice™ if frb 2.0 could be friendly to alternative build systems. In Bazel's case (and other build systems with the similar design), that mostly means designing the tools to support an explicit connection between output files and input files.

**Comment by fzyzcjy** [comment]
That looks interesting! I totally agree FRB should not be tighted to build systems.

Since I am not super familiar with bazel, I guess maybe I will firstly release a 2.0-prerelease (such that the APIs are not stablized yet), and feel free to provide a Bazel example, and we can discuss the details about how to do it :)

**Comment by aran** [comment]
The main relevant idea of this family of build systems is having explicit input and output files. Take every file input on as a parameter, only output to files specified in parameters.

So, practically speaking:

`--rust-crate-dir=<dir>` would become something like `--rust-crate-spec=<path/to/Cargo.toml>`

`--dart-root=` would become `--pubspec-yaml=<path/to/pubspec.yaml>`, 
`--dart-output=...` would become a family of options like `--dart-web-output`, `--dart-io-output`, ... one for each file.
`--wasm` would become something like `--wasm-out=<path/to/mod_bg.wasm>` and `--wasm-js-out=<path/to/mod.js>`, 

The secondary idea in bazel is sandboxing by default. Any internet downloads are predeclared outside of the build step, and build steps don't require internet access and avoid using external helper tools via PATH. This is easiest to achieve if the frb binary contains its functionality as much as possible directly rather than orchestrating/scripting other tools.

I'll definitely take a look at the 2.0 alpha when there is one. Just thought I'd drop this issue as a note since you mentioned thinking about a 2.0 elsewhere, and this kind of refactoring is easiest to handle in a big rewrite.

**Comment by fzyzcjy** [comment]
I see, that looks quite reasonable!

**Comment by fzyzcjy** [comment]
Btw,

> --rust-crate-spec=<path/to/Cargo.toml>

I guess it is still rust-crate-dir, because FRB scans the whole crate's source files. For example, if you change something in your api.rs (or other files, in v2), it should generate something different.

**Comment by fzyzcjy** [comment]
The code & doc for 2.0 is on master branch now, feel free to have a look! (The 2.0.0-dev.1 is not released yet, but that is unrelated to this issue)

**Comment by fzyzcjy** [comment]
(I renamed the title, since it seems that FRB is not only coupled to cargo, but also coupled to `dart run` etc)

**Comment by aran** [comment]
As far as I can tell, this would be a significant project. FRB has a lot of features make things convenient and the underlying components would need to be extracted into a modular "plumbing" layer to make it feasible to be driven by bazel/ninja/whatever.

**Comment by fzyzcjy** [comment]
I see. Btw, the v2 code is more modularized, so I guess most things needed here are in the config module, polish module, etc.
