### ISSUE TITLE
[Bug] Lack of documentation on how to update FRB

### ISSUE THREAD

**Issue by AlienKevin** [fzyzcjy/flutter_rust_bridge#1432]
### Describe the bug

# Summary
FRB updates frequencly (which is great!) but sometimes [breaks backwards-compatability](https://github.com/fzyzcjy/flutter_rust_bridge/issues/1386) without reflecting the changes in the semver. Because FRB is split into the Dart and Rust sides and each requires a separate codegen package, **users can easily forget to update one of the packages and experience frustrating compile errors after update**.

# Specific Issue
The FRB doc is very comprehensive but **lacks instructions on how to properly update the packages**. The only discussion of update I can find is a two-liner in the [Appendix of Part III: Contributor Guide](https://cjycode.com/flutter_rust_bridge/contributing/appendix.html#upgrade-dependency-in-your-dependent-project):
```
flutter pub upgrade flutter_rust_bridge
cargo update -p flutter_rust_bridge
```

This cargo update command is actually not enough because the `flutter_rust_bridge` package internally depends on `flutter_rust_bridge_macros`, **which the `cargo update -p` command does not automatically update**. I recently experienced an issue where all the FRB packages on the Flutter and Rust were properly updated but the macros package was left untouched without my knowledge. I had to do a full `cargo update` for all my Rust dependencies to update the macros package.

While the flutter_rust_bridge package in Rust only requires ^1 of the macros package, **older versions of the macros package is not actually compatible with newer releases**. For example, using v1.57.0 of the macros package in conjunction with v1.82.1 of the flutter_rust_bridge_codegen package causes the main thread to panic during code generation:
```
2023/12/10 12:47:54 [ERROR] panicked at 'not yet implemented: generate code for type "Script"', /Users/kevin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flutter_rust_bridge_codegen-1.82.1/src/ir/ty_unencodable.rs:59:9
```
Where the "Script" type is a mirrored external type.

# Proposed Changes
## Specify version of `flutter_rust_bridge_macros`
Since the macros package is an internal dependency, users have no direct way to update it when updating their `flutter_rust_bridge` package. They have to either delete their `Cargo.lock` file or use `cargo update` to update all their packages. I think it's more appropriate for `flutter_rust_bridge` to precisely specify the version of the macros package that it depends on.

## Better doc for update
I think we can add a more prominent section in the user-facing doc on how to update FRB:

1. Update on the Dart/Flutter side:
    a. First update the FRB package
        If you are using pure Dart: `dart pub upgrade flutter_rust_bridge`
        If you are using Flutter: `flutter pub upgrade flutter_rust_bridge`

    b. Update the version of `ffigen`
        (? Does updating flutter_rust_bridge always automatically updates ffigen)
        (? is there a table of ffigen versions compatible with each FRB version)

    c. Run `dart pub global activate ffigen` to activate updated ffigen

2. Update on the Rust side:
    a. Update `flutter_rust_bridge_codegen` by:
    ```
    cargo install flutter_rust_bridge_codegen
    ```

    b. Update `flutter_rust_bridge` by:
    ```
    cargo update -p flutter_rust_bridge
    ```

Sometimes, the dependencies of FRB package in Dart have version conflicts with other dependencies of the user. One conflict I experienced involves the `uuid` package. We might want to provide an alternative set of instructions that specify the precise versions of the packages.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
N/A
```

**Comment by fzyzcjy** [comment]
Totally agree! (I am working on V2, and feel free to PR after V2 alpha is released after hopefully a week or two, or alternatively I can also implement this quickly)

In addition to the proposal above, here are my two cents and proposal:

* Flutter has a helpful `flutter doctor` command, so we may add one, which checks versions of all these packages and make a warning when problem happens. This may also make bug reports easier (no need to manually write down "version of ffigen, version of clang++, ...").
* Add a command like `flutter_rust_bridge_codegen upgrade` (same spirit as `integrate`/`create` command in V2)

**Comment by fzyzcjy** [comment]
Btw some nits:

> Run dart pub global activate ffigen to activate updated ffigen

IIRC we are no longer using the global version of ffigen, so no worries about this

>  the uuid package

V2 tries to make dependencies minimal, so no uuid dependency anymore ;)

**Comment by AlienKevin** [comment]
>Flutter has a helpful flutter doctor command, so we may add one, which checks versions of all these packages and make a warning when problem happens. This may also make bug reports easier (no need to manually write down "version of ffigen, version of clang++, ...").
Add a command like flutter_rust_bridge_codegen upgrade (same spirit as integrate/create command in V2)

I agree. I think besides checking the versions match, we can also have a central command like `frb upgrade` to upgrade to latest compatible version and `frb upgrade --major-versions` to upgrade to the latest possible version.

I think this command can also support initialization of an FRB project, which can be quite complicated depending on the platforms the users need to support. So a command like `frb init --platforms=android,ios,web` can ease the setup process tremendously. I think `frb` might be a good candidate name due to its conciseness, wide adoption in the community, and also avoids confusion with existing packages named `flutter_rust_bridge`.

>But maybe we can understand a "loose" semver in another way: The user-facing part should not have breaking changes with minor version bump. This has the drawback that users must keep Rust and Dart packages in sync, but other than that, users do not need to change their code using FRB (that's how the semver is understood when we only have exactly one package).

I think this makes sense. If the users always follow our upgrade instructions or use our upgrade tools, they should not have version mismatches. And I think this practice of upgrading the versions of multiple software in tandem is not uncommon. For example, Apple always updates system softwares like Safari along with the OS. This can reduce the need for testing different combination of different softwares, though at the cost of sometimes longer update cycles. But this shouldn't be a problem for FRB, because the Dart and Rust packages are tightly integrated so it makes sense to upgrade them at the same time.

**Comment by fzyzcjy** [comment]
> I think this command can also support initialization of an FRB project

Indeed! In v2, there is a `create` and a `integrate` which finishes initialization in one command.

> I think frb might be a good candidate name due to its conciseness

In v2 I am using `flutter_rust_bridge_codegen`, despite its name (it is not very accurate because it is more than a naive "codegen"), because there are already too many packages for this project (dart side, rust side, codegen, macro) ;)

> I think this makes sense. If the users always follow our upgrade instructions or use our upgrade tools, they should not have version mismatches. And I think this practice of upgrading the versions of multiple software in tandem is not uncommon. For example, Apple always updates system softwares like Safari along with the OS. This can reduce the need for testing different combination of different softwares, though at the cost of sometimes longer update cycles. But this shouldn't be a problem for FRB, because the Dart and Rust packages are tightly integrated so it makes sense to upgrade them at the same time.

Totally agree and thanks for providing that example!

**Comment by AlienKevin** [comment]
> Indeed! In v2, there is a create and a integrate which finishes initialization in one command.

That's great! Is there a design document or some planning doc about v2? I saw it mentioned in a few issues but couldn't find any mention of it in the readme.

**Comment by fzyzcjy** [comment]
No design doc, but the V2 doc will explain itself ;)

Btw just now (minutes ago) I have finished one more feature: Let Rust call Dart freely. (I am happy about this new feature so just want to share a bit, surely it will be fully explained in the doc)

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/5236035/55b85dd8-dcb9-42cd-8375-55a2155aa18a)
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/5236035/748b66b0-0cf3-4f40-93ca-28d04027f8b8)

**Comment by AlienKevin** [comment]
Congrats on the new feature! I recently watched a Strange Loop talk on [multi-language programs](https://www.thestrangeloop.com/2023/formal-semantics-for-multi-language-programs.html) by Amal Ahmed and there are definitely many interesting work to be done in this area. I'm glad to see that FRB is providing more convenient and high-level interops between Dart and Rust. Without FRB, my own app probably would be too slow to use so thanks a lot for your work!

**Comment by fzyzcjy** [comment]
You are welcome, and thanks for sharing the talk! (I will probably watch it later when having time). Yes there are many details in the implementation. The memory problem is fully done, while the u64 (and the inexistence of i64 on Web) is not fully settled and I may hear more voices later because it is also a problem of taste (e.g. use int? use fixnum? use BigInt?).

**Comment by fzyzcjy** [comment]
> Specify version of flutter_rust_bridge_macros

Already done

> Better doc for update

TODO

**Comment by fzyzcjy** [comment]
An alternative solution is that, when running frb_codegen, we hardcode the version in a generated constant. Then, when frb_rust and frb_dart runtime starts, it should check the version, and ensure it is exactly the same as expected.
