### ISSUE TITLE
Is garbage collecting small opaque rust data a problem?

### ISSUE THREAD

**Issue by MatthewLM** [fzyzcjy/flutter_rust_bridge#1448]
Hello,

I've discovered that a struct from a dependency cannot have code generated and returned from an API function, possibly because it uses generics:

```
not yet implemented: generate code for type "frost :: Identifier"
```

```
pub type Identifier = frost::Identifier<S>;
```

```
pub struct Identifier<C: Ciphersuite>(Scalar<C>);
```

Instead I can return this as an opaque type but I'm concerned about the discouragement of relying on garbage collection (https://github.com/fzyzcjy/flutter_rust_bridge/issues/775#issuecomment-1274635037). I want the returned data to be managed by a Dart object and freed when the Dart object is destroyed.

I understand the data is still freed/finalised upon GC, so what's the problem with allowing small amounts of data (32 bytes per object) to be managed by the GC?

If it's a problem I suppose I'll have to serialise the data returned from Rust which is not ideal.

**Comment by fzyzcjy** [comment]
I was also worried, and discussed with Dart/Flutter team, and here is the result: https://cjycode.com/flutter_rust_bridge/guides/types/arbitrary/rust-auto-opaque#dispose

**Comment by MatthewLM** [comment]
OK thanks very much. I will not worry about the dispose method given that the memory footprint is very small.

**Comment by fzyzcjy** [comment]
You are welcome!
