### ISSUE TITLE
examples for the values of the cli options

### ISSUE THREAD

**Issue by patmuk** [fzyzcjy/flutter_rust_bridge#1456]
Hi,

in my setup, I changed the folder structure quite a bit - essentially having the rust lib outside of the flutter folder structure.
`flutter_rust_bridge_codegen generate --config-file flutter_rust_bridge.yml` (v2.0.0-dev.2) fails with 
`Error: path="/Users/patmuk/code/own/sherry/examples/flutter-rust-bridge_crux_style/shell_flutter/lib/bridge/generated/bridge_generated.dart"

Caused by:
    No such file or directory (os error 2)
error: Recipe `gen` failed on line 5 with exit code 1`

my flutter_rust_bridge.yml (worked in v1.1.84.0 - but I adapted it now, mainly `skip_add_mod_to_lib` changed to `no_add_mod_to_lib`) is:
`rust_input: ../app_core/src/api.rs
rust_root: ../app_core
rust_output: ../app_core/src/bridge/generated/mod.rs
dart_output: lib/bridge/generated/bridge_generated.dart
no_add_mod_to_lib: true
c_output: ios/Runner/generated/bridge_generated.h
dart_format_line_length: 120
dumb_all: true`

I probably provide a filename where I shouldn't - but I can't see where I am going wrong?

**Comment by patmuk** [comment]
... I tried this keeping my original files ... but now I restarted with `flutter_rust_bridge_codegen create` in a new folder. Will convert to my previous setup step-by-step.
However, if you see a mistake in the options I provided, please let me know!

**Comment by fzyzcjy** [comment]
Hmm, did https://github.com/fzyzcjy/flutter_rust_bridge/issues/1458 solve this issue?

**Comment by patmuk** [comment]
I believe so - but I am adding the options part-by-part now.
For now setting dart-output and rust-output works fine, but picking up the lib is not ... but let me get back once my setup builds (tracking that in #1459) and close this issue when I can confirm :)

**Comment by fzyzcjy** [comment]
Done on master branch :)
