### ISSUE TITLE
[Bug] option "add-mod-to-lib" is named "no-add-mod-to-lib" in the docs

### ISSUE THREAD

**Issue by patmuk** [fzyzcjy/flutter_rust_bridge#1458]
### Describe the bug

The documentation [states](https://cjycode.com/flutter_rust_bridge/guides/custom/codegen) the option name wrongly as `no-add-mod-to-lib` while it is `add-mod-to-lib`.

Additionally maybe wrong configuration options should be rejected - or at least a warning should be outputted.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
not relevant
```

### Version of `flutter_rust_bridge_codegen`

v2.0.0-dev.2

**Comment by fzyzcjy** [comment]
> The documentation [states](https://cjycode.com/flutter_rust_bridge/guides/custom/codegen) the option name wrongly as no-add-mod-to-lib while it is add-mod-to-lib.

This is a bug in doc: Indeed, when using yaml, **all** things are positive; while using command line arguments, sometimes it is negative (`no-sth`).

I will auto generate a default config file and append it to doc when having time. 

> Additionally maybe wrong configuration options should be rejected - or at least a warning should be outputted.

Totally agree! I will also do that.

**Comment by fzyzcjy** [comment]
Done on master branch as well :) Feel free to open issues if needed!
