### ISSUE TITLE
flutter_rust_bridge v2 🎉

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#1465]
I am excited to announce the v2!

Links
* Reddit r/rust: https://www.reddit.com/r/rust/comments/18ncz3t/flutter_rust_bridge_v2_officially_flutter/
* Reddit r/FlutterDev: https://www.reddit.com/r/FlutterDev/comments/18nczl1/flutter_rust_bridge_v2_officially_flutter/

I want to sincerely say thanks to Dart, Flutter and Rust, the conferring of Flutter Favorite honor, the Dart/Flutter/Rust team and community members, and the contributors of this library (@Desdaemon, @rogurotus, @ngasull, @SecondFlight, @lattice0, @Unoqwy, @antonok-edm, @sagudev, @surban, @Roms1383, @dbsxdbsx, @GregoryConrad, @huang12zheng, @trobanga, @MnlPhlp, @SoLongAndThanksForAllThePizza, @hsfzxjy, @Cupnfish, @alanlzhang, @erikas-taroza, @SiongSng, @JustSimplyKyle, @Zaitam, @coder0xff, ... (truncated to avoid @ too many in one post))!

**Comment by erikas-taroza** [comment]
The [changes](https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/whats-new) look good!

**Comment by fzyzcjy** [comment]
@erikas-taroza Thank you!

**Comment by Roms1383** [comment]
thanks a lot everybody and special thanks to you @fzyzcjy 🎄🎉 can't wait to finish my current projects and getting my hands on v2 features ❤️ happy end of the year everybody 😀

**Comment by fzyzcjy** [comment]
@Roms1383 You are welcome, looking forward to it, and also happy end of year for everyone!
