### ISSUE TITLE
Doesn't work windows: `ld: error: unable to find library -lgcc` - not a bug of this library, but instead bug with cargo-ndk, a library unrelated to flutter_rust_bridge but solely used to build the examples

### ISSUE THREAD

**Issue by evergreen-trading-systems** [fzyzcjy/flutter_rust_bridge#149]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4870868/139536197-8fc691f5-2d06-4810-b009-e3049b2f43d6.png)

Running `cargo ndk -o ../android/app/src/main/jniLibs build` doesn't work on windows

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Codegen logs**

<details>
 
```
Run code generator with `RUST_LOG` environment variable set to `debug`, and paste them here.
```

</details>

**Generated binding code**

<details>
 
```
If possible, please paste your generated binding code, both `.h` (via `--c-output`), and `.dart` (via `--dart-output`), here.
```

</details>

**Development environment (please complete the following information):**
 - OS: [e.g. MacOS]
 - Version [e.g. 11]
 - Version of `flutter_rust_bridge_codegen`: [e.g. 1.0]
 - Paste output of `flutter doctor -v`: [paste below]
 - Version of `clang++`: [e.g. 12]
 - Version of `cbindgen`: [e.g. 0.20]
 - Version of `ffigen`: [e.g. 0.4]

**Smartphone, if applicable (please complete the following information):**

**Additional context**

**Comment by fzyzcjy** [comment]
Hi could you please provide

* Codegen logs: Run code generator with `RUST_LOG` environment variable set to `debug`, and paste them here.
* Generated binding code: If possible, please paste your generated binding code, both `.h` (via `--c-output`), and `.dart` (via `--dart-output`), here.

**Comment by fzyzcjy** [comment]
I personally do not have a Windows computer with Rust/Dart environment. It is @Desdaemon #130 (and @smw-wagnerma #128) who create the wonderful PR. Thus, @Desdaemon @smw-wagnerma could you please have a look?

**Comment by fzyzcjy** [comment]
By the way, have you setup the Flutter environment for developing a windows app correctly? `-lgcc` seems to unrealted to this lib but related to flutter+win.

**Comment by Desdaemon** [comment]
You might have to downgrade the Android NDK to 22.x. The related issue is [cargo-ndk#22](https://github.com/bbqsrc/cargo-ndk/issues/22). Small aside, I encountered this issue some time ago too so I don't think it's Windows-specific.

**Comment by evergreen-trading-systems** [comment]
Thanks for the response. So the workarounds are downgrade to 22 or use nightly. 

I assume `cargo +nightly ndk -t arm64-v8a build -Zbuild-std -o ../android/app/src/main/jniLibs build` no?

**Comment by evergreen-trading-systems** [comment]
Just doing `cargo +nightly ndk -t arm64-v8a build -Zbuild-std` gives same `-lgcc` error

https://user-images.githubusercontent.com/4870868/139539166-8e6b3923-e2a2-44b8-9a22-36235c7a3fff.mp4

**Comment by Desdaemon** [comment]
A bit more digging led me to [this comment](https://github.com/rust-lang/rust/pull/85806#issuecomment-941058074) which suggests that NDK version 22 is baked into the compiler, so unless you are dependent on NDK 23 features I think using an earlier version is the only way for now.

**Comment by fzyzcjy** [comment]
> @Desdaemon Maybe I should add this in the FAQ/known issues section in the readme @fzyzcjy?

Sure. Maybe PR to add text to this section: https://github.com/fzyzcjy/flutter_rust_bridge#troubleshooting Thanks!
