### ISSUE TITLE
Improve V2 migration experience

### ISSUE THREAD

**Issue by AlienKevin** [fzyzcjy/flutter_rust_bridge#1492]
Happy holidays and thanks for the timely 2.0.0-dev.4 bump!

# Problem: V2 migration is underdocumented & has unexpected quirks
I followed the "Upgrade to V2" guide and managed to upgrade to 2.0.0-dev.4. However, **the upgrade experience has a few unexpected quirks that I wish other people can avoid.** In summary, the 4 steps listed in the doc is not enough in my experience:
> 1. Follow the [quickstart](https://cjycode.com/flutter_rust_bridge/quickstart) to integrate V2 boilerplate into the existing project (in a few commands).
> 2. Move original Rust code (e.g. in api.rs) to rust/src/api/simple.rs. (You can also split into multiple files, e.g. apple.rs, orange.rs, etc.)
> 3. Run code generator (whenever your code changes).
> 4. Fix compilation errors (usually just a rename or relocation) and runtime exceptions (usually have hints).

## 1. rust_builder missing
**The `rust_builder` library is not automatically generated** by running `flutter_rust_bridge_codegen generate`. I did `flutter run` after running generate but the api failed to initialize because of a missing dylib. I was quite puzzled for a while until I realized that the binary is now generated on-the-fly rather than prebuilt.

## 2. integrate overwrites existing files silently
So a natural step was to run `flutter_rust_bridge_codegen integrate` in hope of generating the `rust_builder`. However, I was surprised that **the integrate command completely overwrote my existing `main.dart` and `Cargo.toml`**. The command also autogenerated a few files that I don't need, including `rust/src/api/simple.rs` and `integration_test/simple_test.dart`.

## 3. Rust build errors hidden at default log level
I initially did not realize that those files were overwritten and just ran `flutter run` as usual. The command then mysteriously failed with a one-liner error message: `Could not build the precompiled application for the device.` I had to do `flutter run -v`, browse through the massive trace, and finally found out that the rust library is messed up due to the overwrite. Notably, I was able to see the Rust build errors in V1 because I explicitly ran cargo build myself. However, **the cargokit build errors in V2 are not even showing up at the default log level of `flutter run`.** (I was building for a real iOS device)

## 4. Missing step for removal of old files
Another step that's not mentioned in the migration steps is the **removal of any old native binary files, old bridge_generated files, any old imports, and running `flutter clean`**. This step is trivial but can cause confusion if missed during migration. For example, I forgot to remove one of the old bridge_generated imports and directly added the new imports to a dart file. This caused conflicting imports for many api functions I'm using and took me a while to realize the cause of the issue. Also running `flutter clean` seems to be required due to some old cached files needing to be deleted.

## 5. No obvious way to configure cargokit for release mode in flutter run
And lastly, cargokit defaults to debug build for rust when running `flutter run`, which is a sensible default. However, for my use case, **I always need a release build for rust** because otherwise the api is going to be horribly slow, even for testing. This is probably a bad implementation on my part but the release build speeds things up by 10x or more. I suspect that some other devs might also need a release build for testing because my assumption is that the business logic in rust is usually very performance-sensitive and might be changed relatively infrequently during UI testing. And as long as cargokit is smart enough to not rebuild rust every time I do `flutter run`, I can bear with the cost of a release build for rust.

# Proposed Changes

**1. rust_builder missing**
* Option 1: `flutter_rust_bridge_codegen generate` should generate `rust_builder` if it's missing.
* Option 2: Add instructions in migration to manually generate `rust_builder`

**2. integrate overwrites existing files silently**
integrate command should default to *not* overwrite existing files. Output a message listing the things that need to be changed in the existing files.

**3. Rust build errors hidden at default log level**
Show rust build errors when doing `flutter run` so the developers are informed of the issues.

**4. Missing step for removal of old files**
Add a step to migration guide detailing things to remove from V1

**5. No obvious way to configure cargokit for release mode in flutter run**
* Option 1: Add a config option to `flutter_rust_bridge_codegen` to specify cargokit build modes for flutter debug/profile/release builds.
* Option 2: Add instructions on how to configure cargokit to build in release mode even when flutter is in debug mode.

**Comment by AlienKevin** [comment]
Additional thing I noticed on Android: cargokit requires the definition of `minSdkVersion` to `android/app/build.gradle`. This is currently not documented.

Another good-to-have thing in the doc website is a search functionality. The new V2 website looks great but I can't find the search button anymore.

**Comment by AlienKevin** [comment]
Additional thing for iOS:
1. If you followed [fzyzcjy's StackOverflow answer on automatic integration of Flutter and Rust](https://stackoverflow.com/a/69515060/6798201), you also need to tear down the relevant configurations carefully. You basically need to reverse the setup steps you did by either removing the old Build Phase (if using method 1) or deleting the `script_phase` in your Podfile (if using method 2). This also applies to anyone who followed the setup for Android. You need to reverse your changes to the `build.gradle` file.

2. Then, you need to delete the `ios/Runner/bridge_generated.h` file, remove the line `#import "bridge_generated.h"` in `ios/Runner/Runner-Bridging-Header.h`, and remove `bridge_generated.h` from the "Copy Bundle Resources" build phase.

3. Now, you can safely delete the `ios/Runner/libmyapp.a` and remove it from the "Link Binary With Libraries" build phase.

4. Finally, you can safely remove the `print("dummy_value=\(dummy_method_to_enforce_bundling())");` line in `ios/Runner/AppDelegate.swift` if you had that workaround.

**Comment by fzyzcjy** [comment]
Thank you very much for the detailed information! That is partially why I want to keep it beta for a while - to listen from people like you for real-world feedbacks!

**Comment by fzyzcjy** [comment]
(the comments above are done now)

**Comment by AlienKevin** [comment]
> 1. rust_builder missing
> maybe we should directly halt and print out error message saying that "please use integrate instead", if the target folder already exists?

Totally agree.

> 2. integrate overwrites existing files silently

I think there might be two slightly different use cases for `integrate`. One is for people new to FRB who wants to add Rust code to their existing Flutter project, while the other is for people already on FRB V1 who wants to migrate to V2.
> -> b/c I want the integrate command to immediately be able to create a self-contained demo and I guess this is the simplest way. feel free to propose alternatives!

I think for the second use case, maybe a command line flag like `--migrate` would be useful? As you said, it can be similar to `dart fix` and suggest some fixes. With the `migrate` flag on, FRB would no longer generate stub implementations. As for a MVP for this potential feature, I think it will just add in the `rust_builder` library and print out some instructions/links to docs on how to migrate to V2.

> 3. Rust build errors hidden at default log level

I filed [an issue](https://github.com/irondash/cargokit/issues/48) at cargokit.

> 5. No obvious way to configure cargokit for release mode in flutter run

After a few days, I suddenly realized that I can just configure the `dev` profile directly in `Cargo.toml`!
```rust
[profile.dev]
opt-level = 3
```

> 7. Search functionality

https://github.com/fzyzcjy/flutter_rust_bridge/issues/1545

4, 6, 8: Will submit a doc PR later.

**Comment by fzyzcjy** [comment]
For overriding `main.dart`, the current behavior should be, comment out all existing code, and inject the demo code.
What about this change: 
* Put the commented out existing code *above* new demo code, such that you can easily see they are commented.
* Add a line of hint saying it is commented out for demonstration

> I think for the second use case, maybe a command line flag like --migrate would be useful? As you said, it can be similar to dart fix and suggest some fixes. With the migrate flag on, FRB would no longer generate stub implementations. As for a MVP for this potential feature, I think it will just add in the rust_builder library and print out some instructions/links to docs on how to migrate to V2.

I guess you mean `dart analyze` or `flutter doctor` - good idea! e.g. we may just write down a `flutter_rust_bridge_codegen doctor`, which, in addition to checking environment etc, but also checks rust_builder folder, etc.

> After a few days, I suddenly realized that I can just configure the dev profile directly in Cargo.toml!

Good idea! This has a bit of problem: What if someone wants to really debug the binary on other scenarios, e.g. when unit test, or when developing on the computer. But yes, it should work in most of the scenarios.

Looking forward to your PRs!

**Comment by fzyzcjy** [comment]
(There are a few points that have not been solved, so maybe keep it open)

**Comment by fzyzcjy** [comment]
Tracking

- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
