### ISSUE TITLE
How about "new" logo ?

### ISSUE THREAD

**Issue by samuel-cavalcanti** [fzyzcjy/flutter_rust_bridge#1493]
Current logo:
![logo](https://github.com/fzyzcjy/flutter_rust_bridge/raw/master/website/misc/logo.png)

New logo:
![logo_2](https://github.com/fzyzcjy/flutter_rust_bridge/assets/24573157/50fbf497-9941-4123-a16f-50526147405e)

Please see this issue using dark mode

**Comment by fzyzcjy** [comment]
Hi, may I know what is the different between this and the current logo?

**Comment by OfficialBoyfriend** [comment]
Removed the original white background? Sorry I only found this 😊

**Comment by fzyzcjy** [comment]
IIRC I added that white background because for some places, if I use transparent, it looks ugly. (I do not remember exactly where though...)

**Comment by samuel-cavalcanti** [comment]
@fzyzcjy change the web site too
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/24573157/9ef7a82f-1300-4182-808a-ec5e3c9c84fe)

"new" logo:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/24573157/df9a3734-7901-4b3b-ba1f-05d4fa56f1c2)

Maybe changing the phone color to white in dark mode 

![logo_dark](https://github.com/fzyzcjy/flutter_rust_bridge/assets/24573157/18421aef-ec92-4429-bdd2-c890b63e64dc)

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/24573157/37076b97-ff18-4170-8fb5-3f71963d1427)

**Comment by fzyzcjy** [comment]
Ah, looks quite reasonable, feel free to make a PR! (For simplicity, seems white phone LGTM)

**Comment by fzyzcjy** [comment]
Closed by #1501 and later PRs
