### ISSUE TITLE
V2: `flutter_rust_bridge_codegen integrate` doesn't update `.gitignore`

### ISSUE THREAD

**Issue by damywise** [fzyzcjy/flutter_rust_bridge#1497]
**Is your feature request related to a problem? Please describe.**
Title should self-explain, but basically when building app, a lot of rust-related files are generated which should have been `.gitignore`d.

**Describe the solution you'd like**
When `integrate`, also update `.gitignore` to ignore generated folders and files.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by damywise** [comment]
OR simply adding a proper .gitignore in `/rust`

**Comment by fzyzcjy** [comment]
Good suggestion! Feel free to PR - e.g. adding a .gitignore in rust is just putting a file in https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_codegen/assets/integration_template, and run `precommit` script (follow the PR template's steps and done)
