### ISSUE TITLE
RustOpaque - wrong parameter type for generated dcoDecode method [Bug] 

### ISSUE THREAD

**Issue by Ez3kiel-dev** [fzyzcjy/flutter_rust_bridge#1505]
### Describe the bug

Hi!

The dcoDecode method generated for a class that inherits from RustOpaque has the type (dynamic) of its "wire" parameter that does not match the type (list<dynamic>) of the parent class's method.

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/76476566/b6344198-981d-4036-b49d-d0bd1f650b06)

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/76476566/6e246b0d-5efd-47ec-b938-b9ad5df752a4)

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
I can't copy-paste :
Comment is too long (maximum is 65536 characters)
```

### OS

windows 11

### Version of `flutter_rust_bridge_codegen`

flutter_rust_bridge`@ 2.0.0-dev.4

**Comment by fzyzcjy** [comment]
Hi, I guess this is because you are using a stronger linter?

But anyway, this is easily fixable, I will work on it in the next batch.
