### ISSUE TITLE
[Bug] No prints from Rust code ever make it to Flutter/Dart debug output on Android and iOS

### ISSUE THREAD

**Issue by zamanzamzz** [fzyzcjy/flutter_rust_bridge#1507]
### Describe the bug

No prints from Rust code ever make it to Flutter/Dart debug output on Android and iOS. They do however make it to the debug console when running the Flutter app as a Linux desktop app. I tested manually on the following platforms and devices: 
 1. iOS Simulator v17.2
 2. iPhone 13 on iOS v17.1.2
 3. Linux x64 (Manjaro)
 4. Android Emulators with SDK versions 28 - 33.

I'm assuming it is expected behaviour that they are supposed to make it because it is mentioned in the docs [here](https://cjycode.com/flutter_rust_bridge/guides/how-to/debug) to "Just use normal println!() (Rust) and print (Dart) to [debug](https://stackoverflow.com/questions/189562/what-is-the-proper-name-for-doing-debugging-by-adding-print-statements) - there is nothing special.".

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
https://pastebin.com/M2PnUCJq
```

### To Reproduce

Add `print!` or `println` to any arbitrary rust function, then the call the function in Flutter on an Android or iOS device. Observe that the prints in Rust code do not show up in the debug console.

### Expected behavior

The print statements in Rust should show up in the debug console as indicated/implied in the docs.

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.4

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.16.5, on Manjaro Linux 6.1.69-1-MANJARO, locale en_CA.UTF-8)
    • Flutter version 3.16.5 on channel stable at /home/ammanz/opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (8 days ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/ammanz/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/ammanz/opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6
    • cmake version 3.28.1
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/ammanz/opt/android-studio
    • Flutter plugin version 71.2.4
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /home/ammanz/opt/idea-IU-231.8109.175
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Manjaro Linux 6.1.69-1-MANJARO
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Version of `clang++`

16.0.6

### Version of `ffigen`

8.0.2

**Comment by fzyzcjy** [comment]
You are right, the doc needs some refactor!

Indeed I personally do this:

https://cjycode.com/flutter_rust_bridge/guides/how-to/logging
links to
https://github.com/fzyzcjy/flutter_rust_bridge/issues/486

You can mimic the MyMobileLogger (or the underlying android/ios logger), which outputs to correct places in android/ios.
