### ISSUE TITLE
[Bug] `capacity overflow` on `generate` command

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [fzyzcjy/flutter_rust_bridge#1513]
### Describe the bug

Hi! I'm currently following the steps to upgrade my project MomentoBooth to `flutter_rust_bridge` v2. However when running `generate` it seems like it tries to print an error but fails to do so.

```
❯ flutter_rust_bridge_codegen generate
[1.5s] Parse
  └── [0.7s] Run cargo expand
  └── [0.8s] Parse source graph
[0.0s] Generate ⠁                                                                                                             
[2023-12-28T22:11:04.834Z ERROR C:\Users\Sander\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-2.0.0-dev.5\src\library\utils\logs.rs:52] panicked at library\alloc\src\slice.rs:503:50:                                   capacity overflow
thread 'main' panicked at library\alloc\src\slice.rs:503:50:
capacity overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The current state of the upgrade can be found [here](https://github.com/h3x4d3c1m4l/momento-booth/tree/feature/rust_bridge_v2). I pretty much just:
- Ran the `integrate` command
- Reverted any changes to code formatting on the Dart side
- Moved all API code to the `api` folder on the Rust side
- Restored `main.dart` but added the init code at the right place (at least I think so :))

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
https://pastebin.com/raw/2E0eaFvs
```

### OS

Windows

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.5

**Comment by fzyzcjy** [comment]
Hi, could you please try to run `RUST_BACKTRACE=1 flutter_rust_bridge_codegen generate` and provide the stack trace - which seems to be useful to debug this bug :)

**Comment by h3x4d3c1m4l** [comment]
`RUST_BACKTRACE=1` log: https://pastebin.com/raw/yi5pqL5S

I also ran this one, as Rust suggested it:
`RUST_BACKTRACE=full` log: https://pastebin.com/raw/KckAxa7s

**Comment by fzyzcjy** [comment]
Ok, so the release stacktrace does not reveal too many things... Then, it would be great to make a minimal reproducible sample of your bug on https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal. By doing so, it is easy to find out what is going wrong by using the debug build of code generator.

**Comment by h3x4d3c1m4l** [comment]
It crashes while parsing the Rust API code right? I'll see whether I can fit my code in there and the issue reproduces, thanks!

**Comment by h3x4d3c1m4l** [comment]
Minimal repro: https://github.com/h3x4d3c1m4l/flutter_rust_bridge/tree/minimalrepro

**Comment by fzyzcjy** [comment]
Great, given 1text_generator.rs:51:43`, now the bug is quite clear!

It is because the code here should use relative path calculation to support the edge cases when code is put in `rust/src/lib.rs` or things like that.

Feel free to PR (to manipulate namespaces and relative paths), or I will PR in the next batch. At the same time, the workaround is that, try to put all code that is referenced by frb api code into files except `src/lib.rs`

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/5236035/e3f56ce6-cf74-4f79-9427-70cb8e50bd11)

**Comment by fzyzcjy** [comment]
So do you want to have a try PR for this :) If not I will fix it. Since this is quite simple and is `good-first-issue`.

**Comment by h3x4d3c1m4l** [comment]
Taking a look as we speak 👍 thanks for your guidance!

I think the alternative scenario could be possible with a clear error message, but if I can manage to fix it properly that would be way more awesome of course 🚀

**Comment by fzyzcjy** [comment]
You are welcome!

> I think the alternative scenario could be possible with a clear error message

Good idea, it is usually not needed to put things in lib.rs
