### ISSUE TITLE
Frb Attribute for ignoring function/structs

### ISSUE THREAD

**Issue by JustSimplyKyle** [fzyzcjy/flutter_rust_bridge#1542]
**Is your feature request related to a problem? Please describe.**
As suggested, I moved stuff that should be considered by frb into `shared_resources` and stuff that shouldn't into `backend_exclusive` bu I encountered an issue.
async functions are a bit tricky to deal with, since if it contains calls to async `reqwest`(or some other crate), it sometimes compains about it not being `UnwindSafe` and does not compile.
```rust
error[E0277]: the type `UnsafeCell<runtime::driver::Driver>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
    --> src/frb_generated.rs:68:33
     |
68   |     FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
     |                                 ^^^^^^^^^^ `UnsafeCell<runtime::driver::Driver>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
     |
     = help: within `runtime::scheduler::multi_thread::handle::Handle`, the trait `RefUnwindSafe` is not implemented for `UnsafeCell<runtime::driver::Driver>`
```
(tell me shall I create a new issue for this, will provide minumum producible example if you think is needed)

**Describe the solution you'd like**
So what I want to do is, for the library to implement a `frb::ignore` attribute that I can put atop functons to singify that this function should be ignored, that is not generate the bindings.

**Describe alternatives you've considered**
To put it in yet another folder, and use `pub use my_types` to manually import them, but it's not ideal.

**Additional context**
(normally I'd use `tokio::main` to circumvent the async issue, but that only a workaround that is suitble for functions that is expected to be called by frontend.

**Comment by fzyzcjy** [comment]
Totally agree that we can add a `#[frb(ignore)]`, and feel free to PR! A sketch may be:
At https://github.com/fzyzcjy/flutter_rust_bridge/blob/721a26e5f7d5e8901e0a2625c9c90303e291da43/frb_codegen/src/library/codegen/parser/function_parser/mod.rs#L68, recognize the `ignore` attribute, and return None when it says ignore.

Btw, `UnwindSafe` is a general Rust thing, and you can use `AssertUnwindSafe` when proper, which is safe Rust.
Related: https://github.com/fzyzcjy/flutter_rust_bridge/issues/1543
