### ISSUE TITLE
Discussions about `UnwindSafe`/`RefUnwindSafe`

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#1543]
## Background

Firstly, it is inevitable to use `catch_unwind`, because we surely do not want the whole app to crash (Rust's "abort") if there is just a Rust panic. Instead, we want an exception thrown in Dart side. That's the current FRB behavior.

Secondly, when using `catch_unwind`, Rust requires the related things are `UnwindSafe`. When something is not automatically considered as UnwindSafe by the Rust compiler, the programmer needs to do something manually. One way is to use `AssertUnwindSafe`, which is *safe* Rust code (not unsafe Rust code! so no big worries). 

## The question

Approach 1: Currently, I choose to leave it to the end user, i.e. the users need to manually think and wrap AssertUnwindSafe here and there.

Approach 2: An alternative approach is to wrap AssertUnwindSafe unconditionally inside FRB core, thus the users do not need to worry about this, which makes development a bit more fluent, and also avoid some edge cases like https://github.com/fzyzcjy/flutter_rust_bridge/issues/1573.

## Related: Discussions around `AssertUnwindSafe`

e.g. https://users.rust-lang.org/t/is-this-use-of-assertunwindsafe-safe-wrapping-a-future-that-is-send-static/73067

> Is it safe? Well, you have no unsafe block, so the code doesn't have UB.
That said, your code can silence the kind of issue that unwind safety tries to protect you from. I don't know whether that matters to you - most people don't care about unwind safety.

As for what to do if a type is not UnwindSafe:

> Well, you could wrap each of those values in an AssertUnwindSafe, or your own custom struct that you explicitly impl the UnwindSafe trait for.
You can also submit issues/PRs to those crates to mark the types as unwind safe.

Given alice's thoughts, it seems that it is good to use approach 2.

https://github.com/rust-lang/rust/issues/40628

> I've seen now quite a bit of people that told me that "they just wrap everything in AssertUnwindSafe" defeating the whole purpose of it.

> UnwindSafe never protects from UB, it's there to protect against logic errors.

Following hyperlinks here and there, I see notes such as:

https://github.com/rust-lang/crates.io/pull/7453

> https://github.com/rust-lang/rust/issues/40628, https://github.com/rust-lang/rust/issues/65717 and https://github.com/rust-lang/rfcs/pull/3260 all show that unwind safety isn't particularly ergonomic to use and implement, and ultimately leads to people slapping AssertUnwindSafe everywhere until the compiler stops complaining.
This situation has led to built-in test framework using catch_unwind(AssertUnwindSafe(...)) (see [rust-lang/rust@1.73.0/library/test/src/lib.rs#L649](https://github.com/rust-lang/rust/blob/1.73.0/library/test/src/lib.rs?rgh-link-date=2023-11-06T09%3A05%3A00Z#L649)) and libraries like tower-http doing the same (see [docs.rs/tower-http/0.4.4/src/tower_http/catch_panic.rs.html#198](https://docs.rs/tower-http/0.4.4/src/tower_http/catch_panic.rs.html#198)).
As people have mentioned in the threads above, trying to implement this correctly is akin to fighting windmills at the moment. Since the above cases demonstrated that catch_unwind(AssertUnwindSafe(...)) is currently the easiest way to deal with this situation, this commit does the same and refactors our background job runner code accordingly.

I quickly searched Pyo3:
https://github.com/search?q=repo%3APyO3%2Fpyo3+AssertUnwindSafe&type=code
And during my usage of pyo3, I am never required to add AssertUnwindSafe here and there.
Therefore, without deeper investigation, I guess pyo3 uses approach 2.

**Comment by fzyzcjy** [comment]
cc @Desdaemon - what do you think?

**Comment by JustSimplyKyle** [comment]
Personally I think approach two is alright, but maybe add an opt-out?(so that in the rare case if the user does care about unwindsafety they can opt-out

**Comment by fzyzcjy** [comment]
Totally agree. Maybe we can firstly use approach 2, and when someone in the future wants to opt-out, he or she can create an issue, and we can implement that in the future.

**Comment by fzyzcjy** [comment]
Tentative: https://github.com/fzyzcjy/flutter_rust_bridge/pull/1574

**Comment by fzyzcjy** [comment]
One more related: https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1575

**Comment by Desdaemon** [comment]
Personally, the largest source of friction for me has been wrapping trait objects since its implementers are not guaranteed to be unwind-safe despite being so most of the time.
