### ISSUE TITLE
Add search to V2 doc

### ISSUE THREAD

**Issue by AlienKevin** [fzyzcjy/flutter_rust_bridge#1545]
**Is your feature request related to a problem? Please describe.**
The V2 doc looks great but I miss the search feature from the V1 doc. I feel that the V2 doc is much more simplified and streamlined than V1 so I have a lesser need for global searches. However, I do feel sometimes I need to check whether a V1 feature has changed (like `#[frb(mirror(..))]`) and want to quickly search that feature to see the updated doc.

I also think a search feature can make navigating the doc more efficient. For example, I might want to checkout how the dynamic type in Dart is translated to Rust. I might need to go through a couple menu items and look around a bit to see where the relevant doc is. In this case, a quick search of `dynamic` may immediately bring up the section that discusses the DartDynamic feature.

**Describe the solution you'd like**
Add a global search feature to help users navigate the doc.

**Comment by fzyzcjy** [comment]
Totally agree!

(I will come back to this issue after a sleep ;) )

**Comment by fzyzcjy** [comment]
Plan:

* Firstly try whether algolia is OK now (last time I tried it, it weirdly fails for FRB)
* Secondly, if failed, use a local search alternative (I have checked existing ones, but they do not seem to be super smart... but anyway it is better than nothing)

>  I feel that the V2 doc is much more simplified and streamlined than V1 so I have a lesser need for global searches.

Agree, I have spent quite a bit time refactoring it and happy to see someone observe this ;)

**Comment by fzyzcjy** [comment]
Done, it did not work because algolia's official message gives the wrong API key.
