### ISSUE TITLE
Add dependency to freezed automatically, when needed

### ISSUE THREAD

**Issue by patmuk** [fzyzcjy/flutter_rust_bridge#1546]
**Is your feature request related to a problem? Please describe.**
Freezed is only needed, if the interfacing structures are more complex (e.g. Unions). Thus it is up to the user to add dependencies, if the generated code needs them (and execute the dart builder).

**Describe the solution you'd like**
It would be nice, if frb would detect this and add these dependencies, and execution of the dart builder (for freezed code generation) automatically

**Describe alternatives you've considered**
Leave it up to the user. It is quite obvious what needs to be done, tbh.

**Comment by fzyzcjy** [comment]
Totally agree!

Related issue: https://github.com/fzyzcjy/flutter_rust_bridge/issues/1459#issuecomment-1872553518
