### ISSUE TITLE
Resolves methods with the same signature in different plugins

### ISSUE THREAD

**Issue by AlexV525** [fzyzcjy/flutter_rust_bridge#1549]
**Is your feature request related to a problem? Please describe.**
Now we generate bridges based on the method signature. However, methods in different plugins that have the same signature will cause incorrect behavior when lookup for symbols. This should typically occur on iOS/macOS platforms.

**Describe the solution you'd like**
Maybe generate symbols with the package name as prefix.

**Describe alternatives you've considered**
Adding hash based identifiers would also be considered as a solution. Such as generated providers from the riverpod.

**Comment by fzyzcjy** [comment]
Totally agree!

> Adding hash based identifiers would also be considered as a solution. Such as generated providers from the riverpod.

This sounds also quite reasonable, because this can make the name shorter, at the cost that it is less readable.

TODO: Add link to an old issue, I remembered there were some discussions about adding prefixes.
