### ISSUE TITLE
Enum in StreamSink not able to call add funciton

### ISSUE THREAD

**Issue by Alps2** [fzyzcjy/flutter_rust_bridge#1557]
### Describe the bug

same as https://github.com/fzyzcjy/flutter_rust_bridge/pull/1285#issuecomment-1694508269

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
error[E0277]: the trait bound `Event: IntoIntoDart<_>` is not satisfied
   --> src\api\simple.rs:190:14
    |
190 |         sink.add(event);
    |              ^^^ the trait `IntoIntoDart<_>` is not implemented for `Event`
    |
    = help: the following other types implement trait `IntoIntoDart<D>`:
              <bool as IntoIntoDart<bool>>
              <i8 as IntoIntoDart<i8>>
              <i16 as IntoIntoDart<i16>>
              <i32 as IntoIntoDart<i32>>
              <i64 as IntoIntoDart<i64>>
              <usize as IntoIntoDart<usize>>
              <u8 as IntoIntoDart<u8>>
              <u16 as IntoIntoDart<u16>>
            and 30 others
note: required by a bound in `StreamSink::<T>::add`
   --> src\frb_generated.rs:27:1
    |
27  | flutter_rust_bridge::frb_generated_boilerplate!();
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in the macro `flutter_rust_bridge::frb_generated_boilerplate` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### To Reproduce

```
pub enum Event {
    Error { msg: String },
}
```

### Expected behavior

works in 1.x

### OS

Win11

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev8

**Comment by fzyzcjy** [comment]
Hi, have you run `flutter_rust_bridge_codegen generate`? That code should be automatically generated.

**Comment by Alps2** [comment]
Yes, it happens at rust compiling stage

**Comment by Alps2** [comment]
Seems that Enum type not implemented in src\misc\into_into_dart.rs

**Comment by fzyzcjy** [comment]
IMHO IntoIntoDart is implemented in frb_generated.rs automatically, and (without more information) I suspect it is because IntoIntoDart is not generated for your enum, either because something is missing, or because enums are somehow not used, etc.

Could you please make a minimal reproducible sample, probably by forking and adding a few lines in https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal? The current "To Reproduce" does not seem to be complete.

**Comment by Alps2** [comment]
ok, wait for a while

**Comment by fzyzcjy** [comment]
Sure, take your time!

**Comment by Alps2** [comment]
After created a new project, the error disappeared. 🥲 So it is not related to frb, I would close this comment. Sorry for that.

**Comment by fzyzcjy** [comment]
It's OK!
