### ISSUE TITLE
Clarify which directions are zero-copy

### ISSUE THREAD

**Issue by patmuk** [fzyzcjy/flutter_rust_bridge#1568]
**Is your feature request related to a problem? Please describe.**
From the [documentation](https://cjycode.com/flutter_rust_bridge/guides/types/translatable/zero-copy) it is not clear if Dart -> Rust is zero-copy as well.

**Describe the solution you'd like**
Clarify this with a clear statement (and maybe why it is not possible, if that is the case).

**Describe alternatives you've considered**
Could be clarified in this issue discussion only - but I would strongly recommend doing this in the documentation.

**Additional context**
I read somewhere that Dart->Rust can't be zero-copy, due to how FFI works. Though I am not sure if that is true ...

**Comment by fzyzcjy** [comment]
Yes, it seems cannot be zero-copy (at least yet, before Dart changes). For example, if you have a Uint8List, Dart does not provide any approaches (yet) to expose the underlying data to C (or Rust or C++), so we have to copy (at least) once into a buffer that our C/Rust own.

**Comment by fzyzcjy** [comment]
I guess this can be closed since it is answered :) Feel free to reopen!
