### ISSUE TITLE
Stream output of flutter create app

### ISSUE THREAD

**Issue by NoelJacob** [fzyzcjy/flutter_rust_bridge#1569]
Stream output while running `flutter_rust_bridge_codegen create app` because it looks like a frozen terminal.

**Comment by fzyzcjy** [comment]
Good idea, feel free to PR! I guess we only need to modify the https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_codegen/src/library/commands/command_runner.rs a little bit under the `create` scenario.

**Comment by fzyzcjy** [comment]
I think about it a little bit more when wanting to implement this, and gets worried that, this will create a lot of output, which may confuse the user. Therefore, I may firstly add a brief text saying "this may take a while" to ensure users do not think this is frozen :)
