### ISSUE TITLE
The rendering process of the README.md is quite confusing

### ISSUE THREAD

**Issue by samuel-cavalcanti** [fzyzcjy/flutter_rust_bridge#1589]
At present, the `index.md` file is the result of rendering process that takes the `README.md` as its input. Due to multiple outputs (crate.io, pub.dev, github, docusaurus) using a robust template rendering framework like [rust askama](https://github.com/djc/askama) might be beneficial. 

## What is happening

```mermaid
flowchart TD

    B["README.md"]

    F["all-contributors-custom.yaml"]
    G["all-contributorsrc"]
    B["README.md"]
    C["index.md"]

   R{"Render app"}
    B --> R
    G --> R
    
    F --> R
    R --> B
    R --> C
```
Observe that `README.md` servers as both  the input and output of rendering process

## What I'm thinking
```mermaid
flowchart TD


    D["README.md  (Pub.dev)"]
    C[".github/README.md (github)" ]
    E["index.md (docusaurus)"]
    B("README.md (crate.io)")
    A["README.template.md"]
    F["all-contributors-custom.yaml"]
    G["all-contributorsrc"]

   R{"Render app"}
    A --> R
    F --> R
    G-->R
    
    R --> B
    R --> D
    R --> C
    R --> E
    
```

_Originally posted by @samuel-cavalcanti in https://github.com/fzyzcjy/flutter_rust_bridge/issues/1501#issuecomment-1874239373_

**Comment by fzyzcjy** [comment]
Good idea! However, we also use the @all-contributors bot, which directly manipulates README.md. In addition, few people need to change the README except me, so I would like to keep it simple and do not introduce extra dependencies ;)

**Comment by samuel-cavalcanti** [comment]
Okay, I'm closing this issue, just think about when the README.md starting to become more complex.
Look:

```jinja2
<!-- README.template.md  -->

{{headers}}

         ....
[![All Contributors](https://img.shields.io/badge/all_contributors-{{contributors | length}}-orange.svg?style=flat-square)](#contributors-)

         ....

<!-- CUSTOM-MESSAGE:START - Do not remove or modify this section -->
{%- for c in contributors %}
 * [{{c.name}}]({{c.git}}): {{c.phrase}}
{% endfor %}
<!-- CUSTOM-MESSAGE:END -->
```
```dart
// rendering README.md
void renderingReadme(){
  final contributors = loadContributors();
  final headers = "";
  final readme_content = jinja.render("README.template.md",contributors,headers)
}

void renderingIndex(){
  final contributors = loadContributors();
  final headers = """---
title: Introduction
hide_title: true
---

<!-- AUTO-GENERATED FILE - DO NOT EDIT -->
"""
  final readme_content = jinja.render("README.template.md",contributors,headers)
}
```
And of course, write some tests on it

**Comment by fzyzcjy** [comment]
As mentioned above, totally agree about this! So, if in the future there are many people modifying README.md and it is complex, this suggestion will be quite useful :)

**Comment by samuel-cavalcanti** [comment]
Template rendering might be beneficial in:

- tools/frb_internal/lib/src/makefile_dart/test.dart:224:5:   
- tools/frb_internal/lib/src/makefile_dart/test.dart:179:5:   
- tools/frb_internal/lib/src/makefile_dart/release.dart:177:6:
- tools/frb_internal/lib/src/makefile_dart/release.dart:91:9:
- tools/frb_internal/lib/src/makefile_dart/release.dart:78:5: 
- tools/frb_internal/lib/src/makefile_dart/release.dart:60:3: 
- tools/frb_internal/lib/src/makefile_dart/release.dart:54:3: 
- tools/frb_internal/lib/src/makefile_dart/release.dart:49:3:  
- tools/frb_internal/lib/src/makefile_dart/generate.dart:232:5:   

I closed this issue because I'm uncertain whether template rendering is the correct answer. A good solution should be applied in different parts of this project, not only in the `README.md`

**Comment by fzyzcjy** [comment]
Indeed, the whole frb_codegen can use template rendering. I personally do not use it, because Rust/Dart already has quite good built-in templating. 

As an example, mobx, a quite good dart state management package that I use a lot, uses Dart's builtin grammar for templating: https://github.com/mobxjs/mobx.dart/blob/main/mobx_codegen/lib/src/template/action.dart
