### ISSUE TITLE
[codegen] Overriding options from arguments while still using the config file

### ISSUE THREAD

**Issue by AlexV525** [fzyzcjy/flutter_rust_bridge#1596]
**Is your feature request related to a problem? Please describe.**
If I have `.flutter_rust_bridge.yml` and write any argument during the codegen, the `.flutter_rust_bridge.yml` won't be used. What I want is to define a separate option for different platforms while keeping my original configurations. So if I wrote `flutter_rust_bridge_codegen --llvm-path "X:\SDK\LLVM"`, all my configurations will be ignored.

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/15884415/9fa2b7a9-51fc-4908-b3b5-8df45e996cd9)

**Describe the solution you'd like**
Only overrides the value provided from the command line, rather than ignoring the whole configuration when it has input.

**Describe alternatives you've considered**
Supporting configurations based on platforms would be good too.

**Additional context**
```shell
> $ flutter_rust_bridge_codegen -V                                                                                                                                                                                                 
flutter_rust_bridge_codegen 1.82.6
```

**Comment by fzyzcjy** [comment]
That sounds pretty reasonable! This can be (easily) implemented in v2 (especially given the refactored clearer codebase ;) ), but IIRC, are you still using v1?

**Comment by AlexV525** [comment]
> but IIRC, are you still using v1?

Exactly. :)

**Comment by fzyzcjy** [comment]
This is not a bug, thus the probability of porting it to v1 may not be very high. However, feel free to PR if you want!

**Comment by AlexV525** [comment]
> This is not a bug, thus the probability of porting it to v1 may not be very high :/ However, feel free to PR (for v1) if you want!

Sure, feel free to assign this to me if you're able to, I'll keep tracking my assignments periodically.

**Comment by fzyzcjy** [comment]
Btw, I created a branch from v1.82.6 -> https://github.com/fzyzcjy/flutter_rust_bridge/tree/v1-master (name may subject to change), which may be used for future development for v1.
