### ISSUE TITLE
Using a flutter flavor messes up with the build mode

### ISSUE THREAD

**Issue by pixelshot91** [fzyzcjy/flutter_rust_bridge#1606]
### Describe the bug

If I add a flavor to the build.gradle, the "release" build mode is incorrectly selected, and a warning is outputed
I link a potential fix in the "step to reproduce" below
If this is a good fix, I will need to make a PR on https://github.com/irondash/cargokit, and make a PR here to update the submodule

### Steps to reproduce

A simple way to reproduce is to clone my fork of frb, and checkout the 'flavor_test' branch
The first commit of the branch adds the flavor
The second commit fixes the warning

```sh
git clone git@github.com:pixelshot91/flutter_rust_bridge.git flutter_rust_bridge_pixelshot91
cd flutter_rust_bridge_pixelshot91/frb_example/flutter_via_create
git checkout origin/flavor_test~1
flutter run --flavor=valueA
```
You can observe the warning in the log, and the incorrect buildMode is selected:
```
$ flutter run 
Launching lib/main.dart on SM G7810 in debug mode...
Resolving dependencies...
[...]
WARNING: Unknown build configuraiton valueadebug, will assume release
[...]
Running Gradle task 'assembleDebug'...                            130.5s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Syncing files to device SM G7810...                                 97ms
```
But if you checkout my little fix
```
git checkout origin/flavor_test
flutter run --flavor=valueA
```
No warning in the log

### Logs

```shell
not relevant
```

### OS

android

### Version of `flutter_rust_bridge_codegen`

v2.0.0-dev.12

**Comment by fzyzcjy** [comment]
> If this is a good fix, I will need to make a PR on [irondash/cargokit](https://github.com/irondash/cargokit), and make a PR here to update the submodule

Good job! Given https://github.com/fzyzcjy/flutter_rust_bridge/compare/master...pixelshot91:flutter_rust_bridge:flavor_test, IMHO this is good and looking forward to seeing it fixed
