### ISSUE TITLE
Implement code generation for NaiveDate

### ISSUE THREAD

**Issue by TrackerSB** [fzyzcjy/flutter_rust_bridge#1608]
I'm using diesel to generate structs representing database entries. Given a PostgreSQL schema having a column of type `date` it generates a struct with a member of type `NaiveDate` for which `IntoDart` is not implemented. Trying to do so instantly runs into rusts orphan restriction.

Given that `IntoDart<NaiveDateTime>` is already implemented a solution should be  already within reach, I naively assume.

For the time being I can live with changing the column type to `timestamp`,  i.e. including a time resulting in `NaiveDateTime`.

**Comment by fzyzcjy** [comment]
Looks reasonable and feel free to PR! flutter_rust_bridge uses allo-isolate's `IntoDart`, thus the procedure is to PR on https://github.com/shekohex/allo-isolate/blob/master/src/chrono.rs#L56 (just mimic existing ones), and then update flutter_rust_bridge.

**Comment by TrackerSB** [comment]
--> https://github.com/shekohex/allo-isolate/pull/56

**Comment by fzyzcjy** [comment]
(close since PR merged)

**Comment by TrackerSB** [comment]
Thanks a lot for fixing and merging the PR!

**Comment by fzyzcjy** [comment]
You are welcome!
