### ISSUE TITLE
Linker undefined symbols - `ld: Undefined symbols: std::__1::basic_string ...`

### ISSUE THREAD

**Issue by Ch4s3r** [fzyzcjy/flutter_rust_bridge#1610]
### Describe the bug

Startup of application fails when adding the cargo dependency `surrealdb` with the `SpeeDb` backend enabled.
Generation of code is successful but running the application crashes right after starting.
Problem is the linker can't find some function `std::basic_string`, which is needed by `surrealdb`.
Creating a standalone cargo project with the same dependency and also a Tauri project, is working.

### Steps to reproduce

1. Add `surrealdb = { version = "1.0.2", features = ["kv-speedb"] }` as a depdencey into `rust/Cargo.toml`
2. In the rust code `rust/src/api/simple.rs` add this import: `use surrealdb::{engine::local::SpeeDb, sql::Thing};`
3. Generate and run the app on mac: `flutter_rust_bridge_codegen generate && flutter run -d macos`

### Logs

```shell
❯ RUST_LOG=debug flutter run -d macos                                                                                                                                                                 
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-001260A60A85801E }
{ platform:macOS, arch:x86_64, id:00006001-001260A60A85801E }
ld: Undefined symbols:
  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::at(unsigned long) const, referenced from:
      rocksdb::Customizable::GetOptionName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) const in librust_lib.a[arm64][293](customizable.o)
  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::find(char, unsigned long) const, referenced from:
      rocksdb::Cache::CreateFromString(rocksdb::ConfigOptions const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<rocksdb::Cache>*) in librust_lib.a[arm64][144](cache.o)
```

### Expected behavior

Starts up normally.

### OS

MacOs

### Version of `flutter_rust_bridge_codegen`

v2.0.0-dev.12

### Flutter info

```shell
❯ flutter doctor -v
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2 23C64 darwin-arm64, locale
    en-AT)
    • Flutter version 3.16.5 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.16.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (2 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lampe/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/lampe/Library/Android/sdk
    • Java binary at: /Users/lampe/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/lampe/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
    • IntelliJ at /Users/lampe/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### Version of `clang++`

15.0.0 (clang-1500.1.0.2.5)

### Additional context

Notebook: Apple M1 (arm)

**Comment by fzyzcjy** [comment]
Hi, I guess this may be an issue of Cargokit, since flutter_rust_bridge core is just a code generator and is unaware of compilation mechanism. Thus, one way is to create an issue at cargokit.

Maybe related:

* https://github.com/fzyzcjy/flutter_rust_bridge/issues/1604
* https://github.com/fzyzcjy/flutter_rust_bridge/issues/1457

**Comment by dxvid-pts** [comment]
See: https://github.com/irondash/cargokit/issues/52

**Comment by Ch4s3r** [comment]
This https://github.com/irondash/cargokit/issues/52#issuecomment-1883141494 helped me with figuring out the solution.
Because I had the same issue when adding `reqwest` and the solution to adding `-framework SystemConfiguration` fixed it.
So I tried experimenting with the flags there and found some flags with `-lc++` which sounded a bit like the error I had, as `std::__1::basic_string` was in the `std` lib which I guessed comes from `-lc++`. Which was correct in the end.

Had to change this line:
```diff
    'OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/librust_lib.a',
```
```
    'OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/librust_lib.a -l"c++" ',
```

Not sure from which project the `rust_builder` comes from, but maybe it might make sense to add some flags per default?
Would this slow down overall building if not used?
Or maybe just mention this in the FAQ or README

**Comment by Ch4s3r** [comment]
```
ld: Undefined symbols:
  _SCDynamicStoreCopyProxies, referenced from:
      system_configuration::dynamic_store::SCDynamicStore::get_proxies::hca7a3e33ea42720a in librust_lib.a[arm64][156](system_configuration-59f513f20dd3f600.system_configuration.56b5e6df31efacc4-cgu.0.rcgu.o)
```
is solved by 
```
 'OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/librust_lib.a -framework SystemConfiguration',
```
So looking at the referenced function helps identifying which eg `system_configuration` helps identifying what framework or linking argument is missing.

**Comment by fzyzcjy** [comment]
> Not sure from which project the rust_builder comes from,

From this template: https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_codegen/assets/integration_template
(And as you know, it is thin and uses cargokit under the hood)

> but maybe it might make sense to add some flags per default?
Would this slow down overall building if not used?

IMHO linking more things will slow down things; but not sure whether the slowdown is visible or not.

> Or maybe just mention this in the FAQ or README

Sure! Feel free to PR in e.g. https://cjycode.com/flutter_rust_bridge/manual/troubleshooting. (Let's put it there firstly; I may consider moving that page to somewhere more visible later)

**Comment by MateusHBR** [comment]
I'm currently encountering issues that appear to be connected to this particular problem as well.

I'm trying to usa CPAL that is a CrossPlatform Audio Library.

I was having some problems with the linking, but following the tips of @Ch4s3r adding the framework AudioToolbox to rust_builder solved the build problem

´´´
'OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/librust_lib.a -framework AudioToolbox',
´´´

But know I'm facing a runtime error during the library initialization, aborted with a payload. Does anyone have some tip?

libsystem_kernel.dylib`:
    0x1efa1c350 <+0>:  mov    x16, #0x209
    0x1efa1c354 <+4>:  svc    #0x80
->  0x1efa1c358 <+8>:  b.lo   0x1efa1c378               ; <+40>
    0x1efa1c35c <+12>: pacibsp 
    0x1efa1c360 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1efa1c364 <+20>: mov    x29, sp
    0x1efa1c368 <+24>: bl     0x1efa1176c               ; cerror_nocancel
    0x1efa1c36c <+28>: mov    sp, x29
    0x1efa1c370 <+32>: ldp    x29, x30, [sp], #0x10
    0x1efa1c374 <+36>: retab  
    0x1efa1c378 <+40>: ret

**Comment by MateusHBR** [comment]
I had experienced some issues linking CPAL because it uses AudioToolbox.framework and this tips helped me.

Just added this framework to be compiled and everything worked.

inside rust_builder/ios/rust_builder.podspec
`'OTHER_LDFLAGS' => '-force_load ${BUILT_PRODUCTS_DIR}/librust_lib.a -framework AudioToolbox',`

**Comment by Ch4s3r** [comment]
Thank you @fzyzcjy for updating the troubleshooting guide, wanted to do it sometime, but you were faster :)

**Comment by fzyzcjy** [comment]
You are welcome! Since you did not reply for a week, I originally thought you do not have the interest to PR. Anyway, looking forward to your future usage and PRs!
