### ISSUE TITLE
Support more features for Safari

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#1618]
Related: https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1611

**Comment by fzyzcjy** [comment]
btw, @uditrugman given https://github.com/flutter/flutter/issues/55323, seems that it is minified, and we need `--profile` to get stack trace.

```
(cd frb_example/flutter_via_create && just codegen build-web && flutter build web --profile)
(cd frb_utils && dart run flutter_rust_bridge_utils serve-web --web-root ../frb_example/flutter_via_create/build/web)
```

**Comment by fzyzcjy** [comment]
> @uditugman: I'd guess that Safari does not allow that. (https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1611#discussioncomment-8022421)

I checked into details (as was promised in https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1611#discussioncomment-8020010). Seems that Safari does allow it. It is the headers that we need to set correctly.

**Comment by uditrugman** [comment]
WOW! That would be amazing. 

Do you know which header should be set in order for Safari to allow creating nested workers with shared buffers?

**Comment by fzyzcjy** [comment]
Just look at my PR (or wait a bit more, I am still checking and working on it)
