### ISSUE TITLE
[Android] Warning during CMake `No project() command is present`

### ISSUE THREAD

**Issue by AlexV525** [fzyzcjy/flutter_rust_bridge#1619]
### Describe the bug

`flutter run`

```console
[        ] C/C++: CMake Warning (dev) in CMakeLists.txt:
[        ] C/C++:   No project() command is present.  The top-level CMakeLists.txt file must
[        ] C/C++:   contain a literal, direct call to the project() command.  Add a line of
[        ] C/C++:   code such as
[        ] C/C++:     project(ProjectName)
[        ] C/C++:   near the top of the file, but after cmake_minimum_required().
[        ] C/C++:   CMake is pretending there is a "project(Project)" command on the first
[        ] C/C++:   line.
```

### Steps to reproduce

Follow the guide described in https://cjycode.com/flutter_rust_bridge/v1/library/platform_setup/android.html.

### Logs

```shell
As above.
```

### OS

Windows

### Version of `flutter_rust_bridge_codegen`

1.82.6

### Additional context

Adding `set(PROJECT_NAME "project_name")` and `project(PROJECT_NAME)` should resolve the problem.

**Comment by fzyzcjy** [comment]
> Adding set(PROJECT_NAME "project_name") and project(PROJECT_NAME) should resolve the problem.

Looks reasonable, feel free to PR! 

(btw, should I add you as `assignee` as you mentioned a few days ago?)
