### ISSUE TITLE
Duplicate enum element

### ISSUE THREAD

**Issue by sealter** [fzyzcjy/flutter_rust_bridge#1629]
I have a rust enum type:

`
 enum NamedType {
      NewYork,
      London,
      Other,
 }
`

the generate code has two NamedType::other.

I removed `Other` element, and regenerate, but the two `NamedTYpe::other`  still exists.

**Comment by fzyzcjy** [comment]
Hi, could you please provide a minimal reproducible sample? (steps are in https://github.com/fzyzcjy/flutter_rust_bridge/issues/new?assignees=&labels=bug&projects=&template=bug_report.yaml template). Otherwise it does not seem to be easy to reproduce, since it works well in test cases.

**Comment by sealter** [comment]
Sorry, It's the problem of [graphql-client](https://github.com/graphql-rust/graphql-client) , It will generate `Other(String)` element for Enum type. 

[fragments_other_variant option is always on](https://github.com/graphql-rust/graphql-client/issues/446). 
[Other(string)](https://github.com/graphql-rust/graphql-client/blob/main/graphql_client_codegen/src/codegen/enums.rs)

I have defined `other` in my Enum, so There are two `other`  in the `frb_generated.io.rs` like: 
```
7 => crate::api::NamedType::other,
8 => {
    let ans = unsafe { self.kind.Other };
    crate::api::NamedType::Other(ans.field0.cst_decode())
}
```

The same, there are two `other` field in the generated dart like:
```
const factory NamedType.other() = NamedType_other;
const factory NamedType.other(
  String field0,
) = NamedType_Other;

```
 in the freezed dart file there are too many `other`, so the project cann't  run.


Thank you, I will close this issue.

**Comment by fzyzcjy** [comment]
You are welcome, and happy to see it solved!
