### ISSUE TITLE
Missing import in generated dart file

### ISSUE THREAD

**Issue by Corban-Dallas** [fzyzcjy/flutter_rust_bridge#1630]
There are some bugs with missing imports in generated Dart files If bridge is consist of multiple Rust files containing struct declarations that are used between these files. Below is an example of such situation.

I also encounter a similar bug with missing import but in `frb_generated.rs` if struct declared in `api/feature_a.rs` has additional `impl FeatureA { ... }` in other bridge file `api/feature_b.rs`.

### Steps to reproduce

```rust
// flutter_app/rust/lib/api/feature_a.rs

#[frb(opaque)]
pub struct FeatureA;
```

```rust
// flutter_app/rust/lib/api/feature_b.rs

use super::feature_a::FeatureA;

#[frb(opaque)]
pub struct FeatureB

impl FeatureB {
    pub async fn get_feature_a(&self) -> FeatureA { ... }
}
```

```dart
// flutter_app/lib/src/rust/api/feature_b.dart 

import './feature_a.dart'; // <= this import is missing after generation
// other imports 

@sealed
class FeatureB extends RustOpaque {
  ...
  Future<FeatureA> getFeatureA({dynamic hint}) => ...
  ...
}
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

2.0dev14

**Comment by fzyzcjy** [comment]
Looks like a bug, and feel free to fix it! Alternatively, I will fix it in the next batch (hopefully within a few days)

**Comment by Corban-Dallas** [comment]
The generator is like a magic box for me, not sure i can fix it)

**Comment by fzyzcjy** [comment]
Sure, then I will fix it :) Btw, this is the inside of the box: https://cjycode.com/flutter_rust_bridge/guides/contributing/overview
