### ISSUE TITLE
Can't used mirrored, translatable type as translated HashMap value

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#1643]
### Describe the bug

In integrating FRB 2.0 (amazing to see this shaping up!), a mirrored, translatable type can't be used as a mirrored, translatable HashMap value due to a missing IntoDart trait bound on the outside crate's type.

### Steps to reproduce

Other crate, imported:

```
#[derive(Clone)]
pub struct TestInner {}
#[derive(Clone)]
pub struct TestOuter {
    pub test_inner: HashMap<String, TestInner>,
}
```

FRB Rust crate:
```
#[frb(mirror(TestInner))]
pub struct _TestInner {

}

#[frb(mirror(TestOuter))]
pub struct _TestOuter {
    pub test_inner: HashMap<String, TestInner>,
}
```

Error message from `flutter_rust_bridge_codegen generate && flutter_rust_bridge_codegen build-web`

```
error[E0599]: the method `into_into_dart` exists for struct `HashMap<String, TestInner>`, but its trait bounds were not satisfied
    --> front/getplans_io/rust/src/frb_generated.rs:1234:28
     |
1234 |         [self.0.test_inner.into_into_dart().into_dart()].into_dart()
     |                            ^^^^^^^^^^^^^^ method cannot be called on `HashMap<String, TestInner>` due to unsatisfied trait bounds
     |
    ::: /Users/aran/Projects/plans/code/back/editor/commands/src/lib.rs:177:1
     |
177  | pub struct TestInner {}
     | -------------------- doesn't satisfy `TestInner: IntoDart`
     |
    ::: /Users/aran/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/collections/hash/map.rs:214:1
     |
214  | pub struct HashMap<K, V, S = RandomState> {
     | ----------------------------------------- doesn't satisfy `_: IntoIntoDart<HashMap<String, TestInner>>`
     |
     = note: the following trait bounds were not satisfied:
             `TestInner: IntoDart`
             which is required by `HashMap<std::string::String, TestInner>: IntoIntoDart<HashMap<std::string::String, TestInner>>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rust_lib` (lib) due to previous error
```

### Logs

```shell
N/A
```

### OS

macos

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.16

### Flutter info

```shell
N/A
```

### Version of `clang++`

Apple clang version 15.0.0 (clang-1500.1.0.2.5)

**Comment by fzyzcjy** [comment]
Without digging further, I guess it can because https://github.com/fzyzcjy/flutter_rust_bridge/blob/e67f3114634327c1a02b2813c77da0bd77baf5bf/frb_rust/src/misc/into_into_dart.rs#L78 does not consider `K: IntoIntoDart` / `V: IntoIntoDart`. Feel free to PR! Alternatively, I will fix it in probably a few days in the next batch

**Comment by aran** [comment]
I did a fast sketch of it up here: https://github.com/aran/flutter_rust_bridge/tree/1643-hashmap-mirror but having trouble figuring out how to test. I'm seeing`./frb_internal precommit --mode fast` show errors on `master`.  Was hoping to knock this out real quick, sorry I won't be able to do that.

**Comment by fzyzcjy** [comment]
For precommit, is it https://github.com/fzyzcjy/flutter_rust_bridge/pull/1635#issuecomment-1888371324? (I will fix soon, or you can workaround it temporarily)

To test, what about `./frb_internal generate-run-frb-codegen-command-generate --package frb_example/pure_dart`

**Comment by aran** [comment]
Is there an existing test that runs the equivalent of `build-web`? flutter_rust_bridge_codegen generate runs fine.

**Comment by fzyzcjy** [comment]
Sure, `./frb_internal test-dart-web --package frb_example/pure_dart`

Btw, if one CI fails, you can look at it, and will see a line like `./frb_internal ......`, just copy-paste and run locally to reproduce it

**Comment by fzyzcjy** [comment]
Seems that it is already implemented and only miss some tests: https://github.com/fzyzcjy/flutter_rust_bridge/compare/master...aran:flutter_rust_bridge:1643-hashmap-mirror

Then I will PR and finish the rest minor work :)
