### ISSUE TITLE
`flutter_rust_bridge_codegen create` says `program not found`

### ISSUE THREAD

**Issue by OnClickListener2048** [fzyzcjy/flutter_rust_bridge#1654]
### Describe the bug

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/22124534/1e13783f-f363-4158-b1fd-036bffeca6bf)
I run flutter_rust_bridge_codegen create my_app and i got this error
it says that flutter create my_app my have sone problem, but i run flutter create and it'ok on my powershell, and i don't know why i got this error

### Steps to reproduce

Hint: A simple way to reproduce is to clone and modify the https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal example package according to your needs.
1. ...
2. ...
3. ...

### Logs

```shell
PS C:\Users\wang2> flutter_rust_bridge_codegen create my_app
Error: The target folder "C:\\Users\\wang2\\my_app" already exists. Please use the `integrate` command in this case
PS C:\Users\wang2> rm C:\\Users\\wang2\\my_app

Confirm
The item at C:\Users\wang2\my_app has children and the Recurse parameter was not specified. If you continue, all
children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
PS C:\Users\wang2> flutter_rust_bridge_codegen create my_app
[2024-01-13T02:58:16.650Z INFO C:\Users\wang2\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-2.0.0-dev.18\src\library\commands\flutter.rs:13] Execute `flutter create ["my_app"]`
Error: "powershell" "-noprofile -command & "flutter" "create" "my_app"" failed

Caused by:
    program not found
PS C:\Users\wang2>
```

### OS

Windows11

**Comment by fzyzcjy** [comment]
Hmm, how do you install your `flutter` command? Or, does directly run `powershell -noprofile -command & flutter create my_app` finds the command or not

**Comment by OnClickListener2048** [comment]
first of all I didn't expect you this quick 😄，and flutter command is working and 
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/22124534/f2035ccd-de43-463c-86a4-6570a767c3af)
It looks okay for me

**Comment by fzyzcjy** [comment]
> first of all I didn't expect you this quick 😄

I am PRing so is looking at github 😄

> and flutter command is working and

Hmm, could you please provide more info about where your flutter is installed, and how is it installed (following official guide? fvm? etc)

**Comment by OnClickListener2048** [comment]
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/22124534/bb492981-9299-494e-bbbd-0f6fc35068c3)
I do install fvm but i didn't use it for now, i just download flutter installer and unzip it to my D disk and did some setup on my env, i think it's as offcial guide, did i miss somthing?

**Comment by fzyzcjy** [comment]
I do not use windows often, so your configuration looks reasonable for me. For this command, I tested both in a windows10 virtual machine, and on the CI, both works well.

Some guesses: 

* Have you rebooted your computer? From my old memory it seems that env variables may not fully work before a reboot
* If it still fails, one way may be create a simple reproducible sample like: Create a empty rust project, call rust's https://doc.rust-lang.org/std/process/struct.Command.html directly, and observe the bug. Then it may be easier to debug.

**Comment by OnClickListener2048** [comment]
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/22124534/5188e842-0ddf-4b80-aeb5-f2204270b87a)
I did as the rust document said, and i got the same error, but i change "powershell" to "cmd" and this code runs fine, i don't know why is that

**Comment by fzyzcjy** [comment]
Interesting, seems your powershell does not recognize flutter...

**Comment by fzyzcjy** [comment]
I tried to add support to use `cmd` in addition to `powershell` in #1662, and realize it seems that `powershell` is the suggested and preferred way (correct me if I am wrong!), and there are some pitfalls e.g. https://stackoverflow.com/questions/44757893/cmd-c-doesnt-work-in-rust-when-command-includes-spaces.

**Comment by fzyzcjy** [comment]
Since this issue is unrelated to flutter_rust_bridge core, but instead "we cannot use rust's Command to execute Flutter", I guess it may be great to ask a general question for this in e.g. stackoverflow, rust community, etc.

Btw, does replacing `flutter` word with `flutter.bat` works for you?

**Comment by OnClickListener2048** [comment]
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/22124534/ee18b781-e4a6-4b30-9da3-e8335c1b02e8)
Na , flutter.bat isn't work, i'll close it

**Comment by fzyzcjy** [comment]
More brainstorms (in addition to the suggestion of asking this general Rust question) here:

* Maybe try WSL?
* What about `Command::new("powershell").arg("-noprofile").arg("-command").arg("& flutter create my_app")` (i.e. the last one is a long arg)
* What about `Command::new("powershell").arg("-command").arg("& flutter create my_app")`, i.e. remove "noprofile", since I suspect profile has something related.

**Comment by OnClickListener2048** [comment]
okay I’ll try it. Thanks.&nbsp;



发自我的iPhone


------------------ Original ------------------
From: fzyzcjy ***@***.***&gt;
Date: Sun,Jan 14,2024 11:56 AM
To: fzyzcjy/flutter_rust_bridge ***@***.***&gt;
Cc: watson wang ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [fzyzcjy/flutter_rust_bridge] `flutter_rust_bridge_codegencreate` says `program not found` (Issue #1654)





 
More brainstorms (in addition to the suggestion of asking this general Rust question) here:
  
Maybe try WSL?
 
What about Command::new("powershell").arg("-noprofile").arg("-command").arg("&amp; flutter create my_app") (i.e. the last one is a long arg)
 
What about Command::new("powershell").arg("-command").arg("&amp; flutter create my_app"), i.e. remove "noprofile", since I suspect profile has something related.

**Comment by fzyzcjy** [comment]
You are welcome!
