### ISSUE TITLE
Add tutorial for pure dart scenario

### ISSUE THREAD

**Issue by goodperson9** [fzyzcjy/flutter_rust_bridge#1659]
Is it possible to use this package for pure dart and rust bridge, without involving the Flutter SDK?

**Comment by fzyzcjy** [comment]
Sure, why not :) 

* https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal is a minimal working example
* https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/pure_dart contains a ton of tests of flutter_rust_bridge, and is pure-dart (without flutter)

**Comment by fzyzcjy** [comment]
> But flutter_rust_bridge binary itself requires flutter, does it not?

IMHO no, it does not. It is `flutter_rust_bridge_codegen create`, which *creates* a new flutter+rust project for you.

> Is there a tutorial on how to use the flutter_rust_bridge commands with pure dart?

Let me create one later. For short, you can:

1. Clone flutter_rust_bridge repo and enter `frb_example/dart_minimal`
2. As a sanity check, run `dart --enable-experiment=native-assets test` and you should see tests passing (that's a pure dart project)
3. Write, e.g. `lib/main.dart` with some code, and run `dart --enable-experiment=native-assets run lib/main.dart`.

Btw `--enable-experiment=native-assets` is needed for current dart version, but that will be no longer needed in the future.
