### ISSUE TITLE
Got error while calling one of the rust function

### ISSUE THREAD

**Issue by igor-yusupov** [fzyzcjy/flutter_rust_bridge#1660]
### Describe the bug

```
E/flutter ( 6423): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter_rust_bridge/src/basic.dart': Failed assertion: line 138 pos 12: 'rawData.length == 2': is not true.
E/flutter ( 6423): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 6423): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 6423): #2      FlutterRustBridgeBase._parseData (package:flutter_rust_bridge/src/basic.dart:138:12)
E/flutter ( 6423): #3      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:126:15)
E/flutter ( 6423): #4      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:51)
```

### Steps to reproduce

flutter_rust_bridge: ^1.75.3

### Logs

```shell
E/flutter ( 6423): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter_rust_bridge/src/basic.dart': Failed assertion: line 138 pos 12: 'rawData.length == 2': is not true.
E/flutter ( 6423): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 6423): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 6423): #2      FlutterRustBridgeBase._parseData (package:flutter_rust_bridge/src/basic.dart:138:12)
E/flutter ( 6423): #3      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:126:15)
E/flutter ( 6423): #4      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:51)
```
```


### Expected behavior

_No response_

### Generated binding code

_No response_

### OS

MacOS and Linux

### Version of `flutter_rust_bridge_codegen`

1.78.0

### Flutter info

_No response_

### Version of `clang++`

_No response_

### Additional context

after codegen it asks to add parseErrorData. I set up parseErrorData: null everywhere

**Comment by fzyzcjy** [comment]
> flutter_rust_bridge: ^1.75.3
### Version of `flutter_rust_bridge_codegen`
1.78.0

Firstly, maybe try to ensure everything is the same latest version: flutter_rust_bridge dart library, rust library, code generator. 

Secondly, v2 is out and feel free to try that! (I guess v2 should not have this bug)

**Comment by igor-yusupov** [comment]
@fzyzcjy I set up 1.82.6 version and no I got an error:
```
E/flutter ( 4584): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'PanicException'
E/flutter ( 4584): #0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:128:9)
E/flutter ( 4584): #1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:51)
E/flutter ( 4584): <asynchronous suspension>
```

**Comment by fzyzcjy** [comment]
@igor-yusupov This means your rust function panics (and is correctly captured and presented in Dart).

However, it is a known bug in 1.82.6 that the PanicException does not have a good toString to show the panic details. Thus, I suggest upgrade to v2. Alternatively, you can use rust `catch_unwind` to catch panics in the function and print out to see what is happening (as for how to print out things - v2 has builtin supports but v1 did not have, so if using v1 you may need a bit of boilerplate to setup).

**Comment by igor-yusupov** [comment]
@fzyzcjy is it possible to use v2 in the same project as I use now? It seems that for v2 you need to redo the project a bit. also i tried to run the command: `cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0' && \
    flutter_rust_bridge_codegen create my_app && cd my_app && flutter run` and the application did not run, because cargo-ndk could not find the path to ndk version 23 installation

**Comment by fzyzcjy** [comment]
> It seems that for v2 I need to redo the project a bit.

The migration https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/upgrade/v2 may not be very hard. If you find any problems during migration, feel free to create issues in github!

> and the application did not run, because cargo-ndk could not find the path to ndk version 23 installation

Maybe need to remove the old cargo-ndk or other integrations, since v2 uses Cargokit which automatically handles everything about rust+flutter compilation details.

**Comment by igor-yusupov** [comment]
can you tell me what I need to do to be able to print rust code to the logs in v1)?

**Comment by fzyzcjy** [comment]
copy-paste and run this function: https://github.com/fzyzcjy/flutter_rust_bridge/blob/ee71b1ce99e5d26f4504d978004fb2a3fa143bab/frb_rust/src/misc/user_utils.rs#L25

**Comment by igor-yusupov** [comment]
you help me to find an error, thank you so much!

**Comment by fzyzcjy** [comment]
You are welcome and happy to see it is solved!
