### ISSUE TITLE
How to support `mlua` types

### ISSUE THREAD

**Issue by ghost** [fzyzcjy/flutter_rust_bridge#1665]
### Describe the bug

Used the dart_minimal example and added https://crates.io/crates/mlua to cargo dependencies
Edited rust/src/api/minimal.rs file to include the package types, and added a function to use them

Once running main.dart, it starts compiling the rust files but gives such error (however it works without the mlua crate package, and just the minimal_adder function)

```
error[E0277]:` the trait bound `allo_isolate::ffi::DartCObject: From<LuaError> ` is not satisfied

  --> src/frb_generated.rs:42:53
   |
42 |         move || move |context| transform_result_dco((move || crate::api::test::test_lua())()),
   |                                -------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<LuaError>` is not implemented for `allo_isolate::ffi::DartCObject`
   |                                |
   |                                required by a bound introduced by this call
   |
   = help: the following other types implement trait `From<T>`:
             <allo_isolate::ffi::DartCObject as From<DartOpaque>>
             <allo_isolate::ffi::DartCObject as From<RustOpaqueBase<T, A>>>
   = note: required for `LuaError` to implement `Into<allo_isolate::ffi::DartCObject>`
   = note: required for `LuaError` to implement `IntoDart`
note: required by a bound in `transform_result_dco`
  --> /testing/flutter_rust_bridge/frb_rust/src/codec/dco.rs:67:8
   |
61 | pub fn transform_result_dco<T, T2, E>(
   |        -------------------- required by a bound in this function
...
67 |     E: IntoDart,
   |        ^^^^^^^^ required by this bound in `transform_result_dco`

Some errors have detailed explanations: E0277, E0603.
For more information about an error, try `rustc --explain E0277`.
warning: `frb_example_dart_minimal` (lib) generated 2 warnings
error: could not compile `frb_example_dart_minimal` (lib) due to 2 previous errors; 2 warnings emitted
```

### Steps to reproduce

Steps to reproduce:

1. Add the mlua package to cargo.yaml:
```
[dependencies]
mlua = { version = "0.9.4", features = ["lua54", "vendored"] }
```

2. Add to minimal.rs:

```
use mlua::prelude::*;

pub fn test_lua() -> LuaResult<()> {
    let lua = Lua::new();

    let map_table = lua.create_table()?;
    map_table.set(1, "one")?;
    map_table.set("two", 2)?;

    lua.globals().set("map_table", map_table)?;

    lua.load("for k,v in pairs(map_table) do print(k,v) end").exec()?;

    Ok(())
}
```

3. Run it in the same way as normal dart_minimal example

### Logs

```shell
Does not happen when using the flutter_rust_bridge_codegen command, but happens when using the dart run command
```

**Comment by fzyzcjy** [comment]
Looks like custom named and result in another crate, `LuaResult`, is not recognized here.

If you do not need the exact details of the result, maybe we can use `anyhow::Result<...>` as return type instead.

If you really need that type, one way is to try mirroring https://cjycode.com/flutter_rust_bridge/guides/types/translatable/external/diff-crate

**Comment by fzyzcjy** [comment]
> error[E0277]: `*mut lua_State` cannot be sent between threads safely

Seems that `Lua` is not Send. Similar to the famous https://github.com/PyO3/pyo3, flutterr_rust_bridge currently requires object to be Send.

Quickly searched, does this work: https://docs.rs/mlua/latest/mlua/#send-requirement

However, a quick brainstorm: If something really needs to be non-Send, one way is to pin it to a single thread. This can be done either at user level or at frb level.

**Comment by fzyzcjy** [comment]
I see. https://doc.rust-lang.org/std/sync/struct.RwLock.html#impl-Sync-for-RwLock%3CT%3E / https://docs.rs/tokio/latest/tokio/sync/struct.RwLock.html#impl-Sync-for-RwLock%3CT%3E requires `T` to be Send+Sync in order to let the lock be Sync, but `Lua` is Send (and not Sync).

I will think about it a bit deeper later (too tired now), probably within a day!

**Comment by fzyzcjy** [comment]
More brainstorm: What about this workaround:

```rust
pub use mlua::prelude::*;

pub fn hello(lua_state: &Mutex<Lua>, name: String) {
    println!("hello, {}!", name);
}
```

**Comment by fzyzcjy** [comment]
> Invalid argument(s): Failed to load dynamic library '/testing/flutter_rust_bridge/frb_example/dart_minimal/rust/target/release/libfrb_example_dart_minimal.so': /testing/flutter_rust_bridge/frb_example/dart_minimal/rust/target/release/libfrb_example_dart_minimal.so: undefined symbol: lua_settop

A first guess: This seems like not a bug of flutter_rust_bridge, but that `mlua` may not successfully find out needed symbols (lua_settop)?

**Comment by fzyzcjy** [comment]
flutter_rust_bridge does not require how Rust+Flutter are integrated (e.g. how rust is compiled, how dart loads rust .so, etc), and this looks like a general "my .so from Rust code says undefined symbols" problem. Thus, I guess standard methods like checking the symbols, etc, may be helpful.

**Comment by fzyzcjy** [comment]
Happy to hear that and looking forward to more details!

**Comment by fzyzcjy** [comment]
(I changed the title to make it a bit more reflect the content; feel free to change)
