### ISSUE TITLE
RangeError (index): Invalid value: Not in inclusive range 0..9: 10

### ISSUE THREAD

**Issue by cryptoctl** [fzyzcjy/flutter_rust_bridge#1674]
### Describe the bug

when i return a list<Struct> or hashMap<someEnum, somStruct> from rust code,
get this error, 
flutter_rust_bridge version "=2.0.0-dev.20"

```
#0      _Array.[] (dart:core-patch/array.dart:10:36)
#1      RustLibApiImpl.sse_decode_stem (package:zwds/src/rust/frb_generated.dart:1060:23)
#2      RustLibApiImpl.sse_decode_house (package:zwds/src/rust/frb_generated.dart:913:20)
#3      RustLibApiImpl.sse_decode_list_house (package:zwds/src/rust/frb_generated.dart:997:16)
#4      RustLibApiImpl.sse_decode_horoscope (package:zwds/src/rust/frb_generated.dart:892:22)
#5      _SseSimpleDecoder.decodeSuccess (package:flutter_rust_bridge/src/codec/sse.dart:60:47)
#6      SimpleDecoder.decode (package:flutter_rust_bridge/src/codec/base.dart:29:16)
#7      SseCodec._decode (package:flutter_rust_bridge/src/codec/sse.dart:42:55)
#8      SseCodec.decodeObject (package:flutter_rust_bridge/src/codec/sse.dart:32:12)
<asynchronous suspension>
#9      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:624:31)
<asynchronous suspension>
```

the struct just like this

```
#[derive(Debug, Clone, Default)]
pub struct House {
    pub id:String,
    pub name: HouseName, //
    pub stem:Stem,  // when decode this field got error
    pub branch:Branch, 
    pub house_name:String,
    pub branch_name:String
}

#[derive(Debug, Copy, Clone, PartialEq,  IntoPrimitive, FromPrimitive,   Default)]
#[repr(u8)]
pub enum Stem
{
    #[default]
    Jia=1,
    Yi=2,
    Bing=3,
    Ding=4,
    Wu=5,
    Ji=6,
    Geng=7,
    Xin=8,
    Ren=9,
    Gui=10
}
```

when i use 2.0.0-dev.15, every thing goes fine
any help will be grateful

### Steps to reproduce

Hint: A simple way to reproduce is to clone and modify the https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal example package according to your needs.
1. ...
2. ...
3. ...

### Logs

```shell
...
```

### OS

window 10

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.20

**Comment by cryptoctl** [comment]
thank you, let me try..

**Comment by fzyzcjy** [comment]
Alternatively, another workaround is temporarily try <=2.0.0-dev.19 (until I fix it)

**Comment by cryptoctl** [comment]
since put full_dep: true to my flutter_rust_bridge.yaml, regenerate code  ,the error still.

**Comment by cryptoctl** [comment]
thans for your time, i will Downgrade to 19 for the moment

**Comment by fzyzcjy** [comment]
`since put full_dep: true to my flutter_rust_bridge.yaml, regenerate code ,the error still.`

Hmm that's weird. I will check later.
