### ISSUE TITLE
Fix error "the trait `SseEncode` is not implemented for `anyhow::Error`"

### ISSUE THREAD

**Issue by starovoid** [fzyzcjy/flutter_rust_bridge#1675]
### Describe the bug

The  `SseEncode` trait implementation for `anyhow::Error`  seems to be skipped during code generation.

### Steps to reproduce

In fact, I haven't figured out how to reproduce this error yet, because my code is in **api** module does not explicitly use anyhow.

### Logs

```shell
error[E0277]: the trait bound `anyhow::Error: SseEncode` is not satisfied
   --> src/frb_generated.rs:266:38
    |
266 |                   transform_result_sse((move || {
    |  _________________--------------------_^
    | |                 |
    | |                 required by a bound introduced by this call
267 | |                     let api_id = api_id.rust_auto_opaque_decode_sync_owned();
268 | |                     Result::<_, flutter_rust_bridge::for_generated::anyhow::Error>::Ok(
269 | |                         crate::api::simple::id2str(api_id),
270 | |                     )
271 | |                 })())
    | |____________________^ the trait `SseEncode` is not implemented for `anyhow::Error`
    |
    = help: the following other types implement trait `SseEncode`:
              bool
              i32
              usize
              u8
              u16
              u32
              f64
              OpCode
            and 13 others
note: required by a bound in `transform_result_sse`
   --> src/frb_generated.rs:29:1
    |
29  | / flutter_rust_bridge::frb_generated_boilerplate!(
30  | |     default_stream_sink_codec = SseCodec,
31  | |     default_rust_opaque = RustOpaqueMoi
32  | | );
    | | ^
    | | |
    | |_required by a bound in this function
    |   required by this bound in `transform_result_sse`
    = note: this error originates in the macro `$crate::frb_generated_sse_codec` which comes from the expansion of the macro `flutter_rust_bridge::frb_generated_boilerplate` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### OS

Fedora Workstation

### Version of `flutter_rust_bridge_codegen`

"=2.0.0-dev.20"

**Comment by fzyzcjy** [comment]
Hmm, what is your `id2str` function signature? Maybe by looking at its return type we can find something.

**Comment by starovoid** [comment]
> Hmm, what is your `id2str` function signature? Maybe by looking at its return type we can find something.

The function looks pretty simple:
```rust
pub fn id2str(id: ID) -> String {
    id.to_string()
}
```

The external type `ID` implements `fmt::Display` and uses mirroring.

**Comment by fzyzcjy** [comment]
I see. Can this be reproduced on the `frb_example/dart_minimal` example?

**Comment by Andrepuel** [comment]
I think I can reproduce this on version dev20 by having a stream that emits opaque values:

    use flutter_rust_bridge::frb;
    use crate::frb_generated::StreamSink;

    pub fn anyhow_test(a: StreamSink<Undurchsichtiger>) {
        todo!()
    }

    #[frb(opaque)]
    pub struct Undurchsichtiger {
        a: std::fs::File,
    }
    impl Undurchsichtiger {
        pub fn read(&self) -> Vec<u8> {
            todo!()
        }
    }

**Comment by fzyzcjy** [comment]
Looks great! I will check this later
