### ISSUE TITLE
Add example using `build.rs` (web site broken link)

### ISSUE THREAD

**Issue by uditrugman** [fzyzcjy/flutter_rust_bridge#1687]
### Describe the bug

this page: https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/build-rs
has a broken link to build.rs file.
If possible, It'd be nice to have a build.rs in a project that demonstrates how to both compile rust and run codegen. 

### Steps to reproduce

just click the "build.rs" link inside the page above.

### Logs

```shell
no logs. just website issue
```

**Comment by fzyzcjy** [comment]
Oh yes, the examples in v2 do not have build.rs. I will update in the next batch, probably in a few days.
