### ISSUE TITLE
Question about flutter `Isolate`

### ISSUE THREAD

**Issue by guchengxi1994** [fzyzcjy/flutter_rust_bridge#1698]
I was using Isolate to upload files with v1.82.6 and it worked fine. But after I upgrade frb to 2.0.0.dev.21, when I use Isolate, it throws 
should init Rustlib. I have inited RustLib in `main` function. I have 2 questions.
1. should I init RustLib everytime in a new Isolate?
2. should I dispose RustLib after works done in Isolate?

**Comment by fzyzcjy** [comment]
Good question - I should add the multi-isolate scenario in the tests.

**Comment by guchengxi1994** [comment]
I see. Thanks for the answer.

**Comment by fzyzcjy** [comment]
You are welcome!
