### ISSUE TITLE
2.0.0-dev.21 moves `RustOpaque` and `StreamSink` compared with previous beta versions, causing confusion

### ISSUE THREAD

**Issue by BppleMan** [fzyzcjy/flutter_rust_bridge#1701]
### Describe the bug

I upgraded from dev.12 to dev.21

But `RustOpaque` and `StreamSink` seem to be no longer available?

Has `RustOpaque` been migrated to `RustOpaqueNom`?

So where does `StreamSink` migrate to?

### Steps to reproduce

Nothing

### Logs

```shell
Nothing
```

### Expected behavior

Nothing

### Generated binding code

```shell
Nothing
```

**Comment by fzyzcjy** [comment]
No, just use `crate::frb_generated::ThoseThings` - it is moved

**Comment by BppleMan** [comment]
Looking forward to seeing updated documentation

Is there any other things being moved?

**Comment by fzyzcjy** [comment]
Just compile - if it compiles, surely you have moved everything! If it does not compile, then it is evident to see which one moves.
