### ISSUE TITLE
How to custom the executor thread count in v2

### ISSUE THREAD

**Issue by Alps2** [fzyzcjy/flutter_rust_bridge#1708]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For example, replace the 4 thread count by writing a new FLUTTER_RUST_BRIDGE_HANDLER in v1

**Describe alternatives you've considered**
Can you please provide a parameter to assign the default thread count of executor.

**Additional context**
-

**Comment by fzyzcjy** [comment]
Just customize your handler https://cjycode.com/flutter_rust_bridge/guides/custom/rust#customize-handler

This is the default code: https://github.com/fzyzcjy/flutter_rust_bridge/blob/345c3f5fc74dbe85a82c8b4fa0afa4781a453454/frb_rust/src/for_generated/boilerplate.rs#L136
And you can copy-paste-modify it in your project. If frb detects the FLUTTER_RUST_BRIDGE_HANDLER variable, it will stop using the default template automatically.
