### ISSUE TITLE
Struct Ignore or if possible we can Ignore whole mod

### ISSUE THREAD

**Issue by debojyoti452** [fzyzcjy/flutter_rust_bridge#1715]
**Is your feature request related to a problem? Please describe.**
Struct Ignore or if possible we can Ignore the whole mod file.

**Comment by fzyzcjy** [comment]
IIRC you can ignore functions currently. However, feel free to implement the proposed ignore scopes! Alternatively, I will implement it in the next batch.

**Comment by debojyoti452** [comment]
Thank you so much @fzyzcjy

**Comment by fzyzcjy** [comment]
You are welcome!
