### ISSUE TITLE
I am trying to use sqlx for sqlite through `rust frb v2` 

### ISSUE THREAD

**Issue by debojyoti452** [fzyzcjy/flutter_rust_bridge#1719]
### Describe the bug

I am trying to use sqlx for sqlite through `rust frb v2` but getting this error on android run. Building is working fine. 

```logs
E/flutter ( 9868): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librust_lib.so': dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~4t8ZBCcFskEbsMOKdY79Ag==/com.swing.hexagon.hexagon_flutter-OI2Iz7v_OHZHUI6KqbGHuw==/lib/x86_64/librust_lib.so"...
E/flutter ( 9868): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 9868): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 9868): #2      new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:39:47)
E/flutter ( 9868): #3      loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:56:28)
E/flutter ( 9868): #4      loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10)
E/flutter ( 9868): #5      BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:107:13)
E/flutter ( 9868): #6      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:53:31)
E/flutter ( 9868): #7      RustLib.init (package:hexagon_flutter/generated_rust/frb_generated.dart:26:20)
E/flutter ( 9868): #8      main (package:hexagon_flutter/main.dart:44:17)
E/flutter ( 9868): #9      _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter ( 9868): #10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter ( 9868): #11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 9868): 
```

### Steps to reproduce

Hint: A simple way to reproduce is to clone and modify the https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal example package according to your needs.
1. ...
2. ...
3. ...

### Logs

```shell
E/flutter ( 9868): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librust_lib.so': dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~4t8ZBCcFskEbsMOKdY79Ag==/com.swing.hexagon.hexagon_flutter-OI2Iz7v_OHZHUI6KqbGHuw==/lib/x86_64/librust_lib.so"...
E/flutter ( 9868): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 9868): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 9868): #2      new ExternalLibrary.open (package:flutter_rust_bridge/src/platform_types/_io.dart:39:47)
E/flutter ( 9868): #3      loadExternalLibraryRaw (package:flutter_rust_bridge/src/loader/_io.dart:56:28)
E/flutter ( 9868): #4      loadExternalLibrary (package:flutter_rust_bridge/src/loader/_io.dart:14:10)
E/flutter ( 9868): #5      BaseEntrypoint._loadDefaultExternalLibrary (package:flutter_rust_bridge/src/main_components/entrypoint.dart:107:13)
E/flutter ( 9868): #6      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:53:31)
E/flutter ( 9868): #7      RustLib.init (package:hexagon_flutter/generated_rust/frb_generated.dart:26:20)
E/flutter ( 9868): #8      main (package:hexagon_flutter/main.dart:44:17)
E/flutter ( 9868): #9      _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter ( 9868): #10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter ( 9868): #11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 9868):
```

**Comment by fzyzcjy** [comment]
> dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~4t8ZBCcFskEbsMOKdY79Ag==/com.swing.hexagon.hexagon_flutter-OI2Iz7v_OHZHUI6KqbGHuw==/lib/x86_64/librust_lib.so"

Looks like this symbol is not found, thus this may not be a bug of flutter_rust_bridge, but related to how the Rust code is copiled. One reason may be that, sqlx/sqlite needs some special configurations in order to be used on android.

**Comment by debojyoti452** [comment]
> > dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~4t8ZBCcFskEbsMOKdY79Ag==/com.swing.hexagon.hexagon_flutter-OI2Iz7v_OHZHUI6KqbGHuw==/lib/x86_64/librust_lib.so"
> 
> Looks like this symbol is not found, thus this may not be a bug of flutter_rust_bridge, but related to how the Rust code is copiled. One reason may be that, sqlx/sqlite needs some special configurations in order to be used on android.

Yeah, it is working on real device, but not on emulator.

**Comment by fzyzcjy** [comment]
Aha, then is it possible because sqlx/sqlite does not have things like precompiled binaries for x86/x64?

**Comment by debojyoti452** [comment]
yeah exactly, trying to figure out whether there is any other way around. btw tried rusqlite, that too didn't worked on emulator.

**Comment by fzyzcjy** [comment]
Then one way may be to ask in wrapper libs like sqlx, e.g. I guess maybe they will add x64 files.

**Comment by debojyoti452** [comment]
Seems like even Mozilla also faced similar issues

there is some NDK version issues, and setting up the compiler for x86_x64 

- https://github.com/mozilla/application-services/issues/5165
- https://github.com/mozilla/application-services/pull/5442/files
- https://github.com/mozilla/rust-android-gradle/pull/83

**Comment by gridbox** [comment]
@debojyoti452 How do you have your project configured?  I am currently using sqlcipher with sqlx via FRB.  I had to configure `libsqlite3-sys` in my `Cargo.toml` to use the bundled version of sqlcipher but you should be able to do the same with the vanilla sqlite.  I have been able to run on MacOS, Android Emulator, and iOS Simulator.

Here's a snippet from my `Cargo.toml`

```toml
libsqlite3-sys = { version = "*", features = [
    "bundled-sqlcipher-vendored-openssl",
] }
sqlx = { version = "0.7", features = [
    "sqlite",
    "runtime-tokio",
    "macros",
    "uuid",
    "chrono",
] }
```

**Comment by debojyoti452** [comment]
Thanks @gridbox for the suggestion. I am currently shifted to rusqlite. But not working on android emulator. Working fine on real device though. And working fine all other platforms too. 
Let try with libsqlite3 🙏

**Comment by debojyoti452** [comment]
@fzyzcjy btw is there any way we can set NDK version?

**Comment by debojyoti452** [comment]
x86 emulator working fine, but not at all able to make it work on x86_x64 emulator 😢

**Comment by fzyzcjy** [comment]
> btw is there any way we can set NDK version?

Since flutter_rust_bridge is using cargokit for the default template (assuming you are using the default template), I guess cargokit may have some options to configure that.

**Comment by debojyoti452** [comment]
> > btw is there any way we can set NDK version?
> 
> Since flutter_rust_bridge is using cargokit for the default template (assuming you are using the default template), I guess cargokit may have some options to configure that.

@fzyzcjy trying to find it in `cargokit`

**Comment by mike-lloyd03** [comment]
I had a problem getting sqlite projects to build for Android using uniffi. [This comment](https://github.com/mozilla/uniffi-rs/issues/1923#issuecomment-1875626730) pointed me in the right direction. This is what my `build.rs` looks like for that project to solve this problem:

```rust
use std::env;

fn main() {
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap();

    if target_arch == "x86_64" && target_os == "android" {
        let android_home = env::var("ANDROID_HOME").expect("ANDROID_HOME not set");
        const ANDROID_NDK_VERSION: &str = "26.1.10909125";
        const LINUX_X86_64_LIB_DIR: &str =
            "toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/lib/linux/";
        println!("cargo:rustc-link-search={android_home}/ndk/{ANDROID_NDK_VERSION}/{LINUX_X86_64_LIB_DIR}");
        println!("cargo:rustc-link-lib=static=clang_rt.builtins-x86_64-android");
    }
}
```

Modified from this [build.rs](https://github.com/p2panda/meli/pull/21/commits/b8f02d192e80565a65f20aeec56d83bfe440513a).
