### ISSUE TITLE
Allow generated struct fields to be non-final

### ISSUE THREAD

**Issue by mezeipetister** [fzyzcjy/flutter_rust_bridge#1721]
### Describe the bug

I have started using flutter_rust_bridge, and I realized when it generates a class from a given rust struct, all the fields become final. Is there any way to produce a mutable dart class from a rust struct?

### Steps to reproduce

basic behavior.

### Logs

```shell
...
```

**Comment by mezeipetister** [comment]
Ok I found under 1.30.0 that #[rfb(non_final)] attribute solves it. I havent found any info about rfb attributes in the doc site.

**Comment by fzyzcjy** [comment]
Sure! just use https://cjycode.com/flutter_rust_bridge/guides/types/translatable/detailed/struct#non-final-fields

**Comment by mezeipetister** [comment]
Thank you! This is not a bug, and seems to be solved, so if you dont mind I close it.

**Comment by fzyzcjy** [comment]
You are welcome!
