### ISSUE TITLE
Documentation request: need more detailed description on how to avoid memory leaks

### ISSUE THREAD

**Issue by NightBlaze** [fzyzcjy/flutter_rust_bridge#1723]
**Is your feature request related to a problem? Please describe.**

It seems that it's pretty easy to get memory leak in Rust part. I created a demo project to demonstrate it https://github.com/NightBlaze/frb_memory

In case if user would like to use a stateful pattern, ie use Flutter only for UI part and implement all logic and state management in Rust it's pretty easy to get leaked Rust object if user will use `StreamSink`.

There are three screens in the demo project. All behave similar:
1. All have `<ScreenName>Logic` struct in Rust.
2. Each screen instantiates corresponding Rust object and holds it.
3. Each screen communicates with the Rust with `StreamSink`.

The first screen, which is named `Leaked Screen`, will never release Rust object because of retain cycle.
The second screen, `GC Free Screen`, will release Rust object on GC.
And the third screen, `Instant Free Screen`, will release Rust object immediately after screen close.
(each, naming is not my favorite part :) )

**Describe the solution you'd like**

I would like to have more detailed documentation about best practices of memory usage/memory safety in FRB.

**Comment by fzyzcjy** [comment]
Thanks for the detailed report!

Firstly, as mentioned in the doc, if you have some heavy object, it is suggested by official flutter to free them manually. Thus, e.g. call `yourObject.dispose()` when leaving screen (i.e. during widget state's dispose). But if the rust object is lightweight, there is no worry about this.

Secondly, it seems that you are reporting some memory leak scenarios when using StreamSink. Could you please provide a bit more details about that?

**Comment by NightBlaze** [comment]
> Secondly, it seems that you are reporting some memory leak scenarios when using StreamSink. Could you please provide a bit more details about that?

Unfortunately, I can't provide more technical details. I just tested different scenarios/architectures and found this issue. Technically, it doesn't seem to be a bug, just need to call `rustObject.dispose()` (and it good to have info about it in docs near an example of `Sink` usage).

It some sort of "retain cycle" (but it's not because if it will be a real retain cycle then a screen (Flutter's widget instance) will not be deallocated/disposed too).

How to reproduce:

If a screen holds an instance of a Rust object
Flutter part: https://github.com/NightBlaze/frb_memory/blob/main/lib/leaked_screen.dart#L13
Rust part: https://github.com/NightBlaze/frb_memory/blob/main/rust/src/api/leaked_screen_logic.rs#L13

AND

Rust holds Flutter's `StreamSink`
Flutter part: https://github.com/NightBlaze/frb_memory/blob/main/lib/leaked_screen.dart#L16
Rust part: https://github.com/NightBlaze/frb_memory/blob/main/rust/src/api/leaked_screen_logic.rs#L20

AND

there is no call of `rustObject.dispose()`
Flutter part: https://github.com/NightBlaze/frb_memory/blob/main/lib/leaked_screen.dart#L51

THEN

rust object will never be deallocated.

The second part of the issue (I mean the issue #1723 in the repo) is that it's good to have some section in docs that describes how memory works across Flutter runtime and Rust part (which can have runtime too). I found a potential memory leak with `StreamSink` but probably the same when passing closures from Flutter to Rust? I understand that it's a lot of work to maintain documentations so it's low priority request.

**Comment by fzyzcjy** [comment]
> Technically, it doesn't seem to be a bug, just need to call rustObject.dispose() (and it good to have info about it in docs near an example of Sink usage).

Btw, for "when I have a rust object, should I call dispose manually, or can I wait for it to be GCed", docs are here: https://cjycode.com/flutter_rust_bridge/guides/types/arbitrary/rust-auto-opaque#dispose.

> THEN rust object will never be deallocated.

Hmm, do you mean it will not be deallocated, even though dart has triggered a GC? If so, I will add some tests to see more about this.

> good to have some section in docs that describes how memory works across Flutter runtime and Rust part

There seems to be some doc here: https://cjycode.com/flutter_rust_bridge/guides/contributing

**Comment by NightBlaze** [comment]
> Btw, for "when I have a rust object, should I call dispose manually, or can I wait for it to be GCed", docs are here: https://cjycode.com/flutter_rust_bridge/guides/types/arbitrary/rust-auto-opaque#dispose.
Thanks for the link. I missed it.

> Hmm, do you mean it will not be deallocated, even though dart has triggered a GC? If so, I will add some tests to see more about this.
Yes. I tried to trigger GC through DevTools and rust object doesn't deallocated.

**Comment by fzyzcjy** [comment]
> Yes. I tried to trigger GC through DevTools and rust object doesn't deallocated.

Then I will look at it in the next batch (hopefully within several days)!
