### ISSUE TITLE
version solving failed when adding two local packages which are integrated with flutter_rust_bridge

### ISSUE THREAD

**Issue by santoshakil** [fzyzcjy/flutter_rust_bridge#1732]
### Describe the bug

This is the structure,

- app
- - package1
- - - rust_builder
- - package2
- - - rust_builder

the rust_builder causing a "version solving failed" issue during the build. My app has two packages, each with its own rust_builder which is causing this issue.

### Steps to reproduce

A simple way to reproduce is to clone and modify the https://github.com/santoshakil/flutter_rust_bridge_version_solving_failed_issue

### Logs

```shell
Because every version of fpr2 from path depends on rust_builder from path fp1/fpr2/rust_builder and every version of fpr1 from path
  depends on rust_builder from path fp1/fpr1/rust_builder, fpr2 from path is incompatible with fpr1 from path.
And because every version of fp1 from path depends on fpr1 from path, fpr2 from path is incompatible with fp1 from path.
So, because fa1 depends on fp1 from path which depends on fpr2 from path, version solving failed.
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

 2.0.0-dev.22

**Comment by fzyzcjy** [comment]
Hmm, I guess one way is to modify the template in https://github.com/fzyzcjy/flutter_rust_bridge/blob/10fded8d70f5af616f6c90720e4184bf65ad3467/frb_codegen/assets/integration_template/rust_builder/pubspec.yaml#L1

For example, we can make it `name: rust_builder_REPLACE_ME_DART_PACKAGE_NAME` (where `REPLACE_ME_DART_PACKAGE_NAME` will be replaced automatically when using this template). 

Feel free to PR for this!

**Comment by santoshakil** [comment]
> Hmm, I guess one way is to modify the template in
> 
> https://github.com/fzyzcjy/flutter_rust_bridge/blob/10fded8d70f5af616f6c90720e4184bf65ad3467/frb_codegen/assets/integration_template/rust_builder/pubspec.yaml#L1
> 
> For example, we can make it `name: rust_builder_REPLACE_ME_DART_PACKAGE_NAME` (where `REPLACE_ME_DART_PACKAGE_NAME` will be replaced automatically when using this template).
> 
> Feel free to PR for this! Alternatively, I will fix it (but this looks like a `good-first-issue`)

Please make rust_builder customizable. Otherwise, it wouldn't be possible to use multiple packages that are integrated with flutter_rust_bridge.

**Comment by fzyzcjy** [comment]
I mean, just rename `rust_builder` to `rust_builder_REPLACE_ME_DART_PACKAGE_NAME`. Since your dart package name is unique, this name will also be unique.
