### ISSUE TITLE
Mention flutter_logger in "send logs to dart" section

### ISSUE THREAD

**Issue by MnlPhlp** [fzyzcjy/flutter_rust_bridge#1740]
**Is your feature request related to a problem? Please describe.**
The documentation mentions how you could implement a logging logic to pass rust log messages to dart in [Example 3: Send Rust logs to Dart](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging#example-3-send-rust-logs-to-dart).
It's tedious to do this for single projects so i created the crate [flutter_logger](https://github.com/mnlphlp/flutter_logger) that set's up everything with one macro call.

**Describe the solution you'd like**
If it is ok with you i would like to mention this in the doc section about logging.
Especially for new users of the library this might make stuff easier.
I can do a pull request with a short description/mention of the crate if it is something of interest.

Also feel free to just close this issue if you don't want this mentioned somewhere.

**Describe alternatives you've considered**
Alternative is implementing the logging for each app yourself.

**Additional context**
Example:

### rust
```rs
flutter_logger::flutter_logger_init!();

pub fn test(i: i32) {
    // using the 'log' crate macros
    info!("test called with: {i}")
}
```
### dart/flutter

```dart
void setupLogger(){
    setupLogStream().listen((msg){
    // This should use a logging framework in real applications
        print("${msg.logLevel} ${msg.lbl.padRight(8)}: ${msg.msg}");
    });
}

void main(){
    await RustLib.init();
    await setupLogger();
    await test(i: 5);
}
```

**Comment by fzyzcjy** [comment]
Looks great and thanks for pointing out :) I will add that to doc.
