### ISSUE TITLE
a flutter + dart-lib + cli template

### ISSUE THREAD

**Issue by uditrugman** [fzyzcjy/flutter_rust_bridge#1748]
Hi,
First, thanks for a great project!

Larger projects, typically have more than one target and in many cases also CLI tools that use the rust library.

For that, It would be very useful to have a template project with the below structure:
1. commons - a dart package that includes the frb_generated... files and loads the relevant rust library according to current platform
2. app - a flutter app that depends on commons
3. rust - the rust code

is there such a reference project already?

**Comment by fzyzcjy** [comment]
Hi, this seems like:

1. https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal pure-dart + rust, for point 1+3
2. Create an empty package that depends on that dart_minimal package for your point 2

**Comment by fzyzcjy** [comment]
Hmm, one way is to somehow utilize (and maybe modify a bit?) the cargokit, which is used by frb default template. The build.dart may be helpful for the pure-dart (cli) case as well. After the Dart's native assets (build.dart) feature is stablized, it may be easier.

Btw this question is somehow related to https://github.com/fzyzcjy/flutter_rust_bridge/issues/1749

**Comment by patmuk** [comment]
Hi @uditrugman,

maybe my sample project can help:
https://github.com/patmuk/flutter-rust-bridge_crux_style

In „app_core“ is the library - but written in rust. 
„shell_flutter“ is using this lib, within a flutter app. 
„shell_cli“ is a cli tool which uses this lib as well - but it is written in rust, not dart. 

You won’t find a dart library. It should be not too hard to wrap the rust lib („app_core“) into a dart lib and use that in the flutter app. 
But IMHO rust is superior when used as a lib and cli. 

Hope that helps!

**Comment by uditrugman** [comment]
Hi,
I appreciate the time and effort to share this! I finally managed to compile and use rust from both CLI and the Flutter app.
I'll anyway take a look at how you implemented this.
Thanks :)

**Comment by patmuk** [comment]
Hi,
you are welcome. If you have any questions - I am here to help :)

Best,
Patrick

**Comment by jasonwun** [comment]
@patmuk Are you able to run your sample Flutter app on Windows? Somehow I wasn't able to run it successfully on Windows. I can provide logs later on as I gave up investigating and have it blocked the development of my project

**Comment by patmuk** [comment]
> @patmuk Are you able to run your sample Flutter app on Windows? Somehow I wasn't able to run it successfully on Windows. I can provide logs later on as I gave up investigating and have it blocked the development of my project

No, I was running it on a Mac (x86). But that should actually not matter … I did not update it to the latest frb version - take care that the flutter-rust-bridge-codegen binary is at the same version as the flutter and rust dependencies. 

Otherwise, does a clean standard setup work? (“cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.30' && \
    flutter_rust_bridge_codegen create my_app && cd my_app && flutter run”)?

Feel free to send the error log, maybe I can see something there.

**Comment by jasonwun** [comment]
@patmuk So when I run the flutter shell directly using `flutter run`, this is what dart throws
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': The specified procedure could not be found.

 (error code: 127)
This is often because the Rust library is not loaded correctly.
Debug information of the external library: by open(C:\Users\user\Documents\Application\flutter-rust-bridge_crux_style\app_core\target\release\app_core.dll)
Original stack trace: #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      MultiPackageCBinding._store_dart_post_cobjectPtr (package:flutter_rust_bridge/src/ffigen_generated/multi_package.dart:218:76)
#2      MultiPackageCBinding._store_dart_post_cobjectPtr (package:flutter_rust_bridge/src/ffigen_generated/multi_package.dart)
#3      MultiPackageCBinding._store_dart_post_cobject (package:flutter_rust_bridge/src/ffigen_generated/multi_package.dart:220:41)
#4      MultiPackageCBinding._store_dart_post_cobject (package:flutter_rust_bridge/src/ffigen_generated/multi_package.dart)
#5      MultiPackageCBinding.store_dart_post_cobject (package:flutter_rust_bridge/src/ffigen_generated/multi_package.dart:212:12)
#6      GeneralizedFrbRustBinding.storeDartPostCObject (package:flutter_rust_bridge/src/generalized_frb_rust_binding/_io.dart:21:16)
#7      _setUpRustToDartCommunication (package:flutter_rust_bridge/src/main_components/entrypoint.dart:145:29)
#8      new _EntrypointState (package:flutter_rust_bridge/src/main_components/entrypoint.dart:134:5)
#9      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:61:15)
<asynchronous suspension>
#10     RustLib.init (package:shell_flutter/bridge/frb_generated/frb_generated.dart:27:5)
<asynchronous suspension>
#11     main (package:shell_flutter/main.dart:15:3)
<asynchronous suspension>

#0      GeneralizedFrbRustBinding._userFriendlyDynamicLibraryErrorReporting (package:flutter_rust_bridge/src/generalized_frb_rust_binding/_io.dart:102:7)
#1      GeneralizedFrbRustBinding.storeDartPostCObject (package:flutter_rust_bridge/src/generalized_frb_rust_binding/_io.dart:23:7)
#2      _setUpRustToDartCommunication (package:flutter_rust_bridge/src/main_components/entrypoint.dart:145:29)
#3      new _EntrypointState (package:flutter_rust_bridge/src/main_components/entrypoint.dart:134:5)
#4      BaseEntrypoint.initImpl (package:flutter_rust_bridge/src/main_components/entrypoint.dart:61:15)
<asynchronous suspension>
#5      RustLib.init (package:shell_flutter/bridge/frb_generated/frb_generated.dart:27:5)
<asynchronous suspension>
#6      main (package:shell_flutter/main.dart:15:3)
<asynchronous suspension>
```

Two problems:
1. It seems like dart is always looking for release build of rust binary
2. Even if I manually compile rust code with release profile, there is still problem of referencing it from dart code. Did you install any dependency for ffi?

**Comment by jasonwun** [comment]
okay, seems like the second issue is more of a frb symbol link issue instead of the new directory. https://github.com/Desdaemon/flutter_rust_bridge_template/commit/e9c36d672216c23ae4399a5e088643f4f36be447.

**Comment by patmuk** [comment]
I did not made any ffi changes ... the only setting needed is 
```
rust_input: ../app_core/src/api/**/*.rs
rust_output: ../app_core/src/bridge/frb_generated/mod.rs
```
in `shell_flutter/flutter_rust_bridge.yaml`

`shell_flutter/rust_builder` should take care of configuring an Xcode project, which uses the correct rust library. (Note that I only compiled it for iOS so far ...).

frb doesn't run with the latest ffi/ffigen version, the versions used are in `shell_flutter/rust_builder/pubspec.yam`.

But having said this all ... this is already configured in the repo, so you most probably have these same settings.

frb made quite some changes to come to this simplified version, and I changed this setup from frb 1.x to the current 2.0.0.-dev.22. There were more steps to configure involved, and especially setting the path to the rust lib correctly was quite hard. But now, as far as I remember, all is äutomagically" done by `shell_flutter/rust_builder`, which is another project.

I am suspecting that this has never been tested in Windows - at least I only used it with a Mac and the CI is executing this setup on Linux.

@fzyzcjy have you tested having the rust sources in a sibling directory (instead of the standard subfolder) on windows? Do you know what the error message above could mean?

**Comment by fzyzcjy** [comment]
I personally have not tested that, but theoretically it looks pretty reasonable.

> Debug information of the external library: by open(C:\Users\user\Documents\Application\flutter-rust-bridge_crux_style\app_core\target\release\app_core.dll)

Could you please check whether the file is there?

**Comment by patmuk** [comment]
yes - but it will take a while ... I made a transition from an x86 Mac to an apple silicon one, and decided to setup the new machine with nix ... so currently I cannot run the project, but once I can I will let you know here!

**Comment by jasonwun** [comment]
@fzyzcjy I can confirm that the file is there in the exact same path.

**Comment by fzyzcjy** [comment]
Hmm, then could you make a minimal reproducible sample to narrow down the problem?

rust_builder is for building the Rust source code into binary files; if the compiled binaries are already there (and suppose they have correct content), then the loading logic is indeed quite simple: https://github.com/fzyzcjy/flutter_rust_bridge/blob/625b11ee6288330b0436cfd998f24e8f78b53085/frb_dart/lib/src/loader/_io.dart#L59

**Comment by fzyzcjy** [comment]
> @jasonwun okay, seems like the second issue is more of a frb symbol link issue instead of the new directory.

Oh then seems this is not a problem.

Then seems this is the only problem left:

> It seems like dart is always looking for release build of rust binary
