### ISSUE TITLE
multi flutter engine is ok?

### ISSUE THREAD

**Issue by ggslayer** [fzyzcjy/flutter_rust_bridge#1752]
Hi, If I use this package: https://pub.dev/packages/desktop_multi_window,  which is based on multiple flutter engine,  will frb support in every engine?   will there have some problem?

**Comment by fzyzcjy** [comment]
I guess it should be OK, since flutter_rust_bridge uses almost nothing about Flutter, but mainly uses the underlying Dart API. However, I have not personally tried it yet. If you see any problem, feel free to create an issue!

**Comment by ggslayer** [comment]
ok  thankyou, I'll try it

**Comment by fzyzcjy** [comment]
You are welcome!
