### ISSUE TITLE
[docs] `StreamSink` not exported by flutter_rust_bridge

### ISSUE THREAD

**Issue by Dampfwalze** [fzyzcjy/flutter_rust_bridge#1755]
### Describe the bug

In [website/docs/guides/types/translatable/stream.md#simple-timer](https://github.com/fzyzcjy/flutter_rust_bridge/blob/ed163209ffefff4b4c524ca17557bcc3c43f92b6/website/docs/guides/types/translatable/stream.md#simple-timer), the `StreamSink` is imported from `flutter_rust_bridge`, but it is actualy in the generated code `crate::frb_generated::StreamSink`.

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.24

**Comment by fzyzcjy** [comment]
You are right, feel free to PR to fix this slightly outdated doc!
