### ISSUE TITLE
The bridge always wants to load a framework on iOS

### ISSUE THREAD

**Issue by Berrysoft** [fzyzcjy/flutter_rust_bridge#1772]
### Describe the bug

I'm trying to upgrade a frbv1 project to frbv2. The upgrade is successful on Android, but not iOS. With frbv1, the native lib is built as staticlib with a project generated by cargo-xcode. However, after upgrading to frbv2, the dart side always wants to load `native.framework/native`. I looked through the examples in this repo, but they all use cargokit. Is there a smooth upgrade path to still use the static lib without framework, or a way to change the xcode project to generate a dummy framework?

### Steps to reproduce

The instructions here is interesting. Does `dart_minimal` really run well on iOS?

### Logs

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'native.framework/native': dlopen(native.framework/native, 0x0001): tried: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRootnative.framework/native' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/native.framework/native' (errno=2), '/usr/lib/swift/native.framework/native' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/native.framework/native' (errno=2), '/usr/lib/swift/native.framework/native' (errno=2, not in dyld cache), '/Users/berrysoft/Library/Developer<…>
```

**Comment by fzyzcjy** [comment]
Hi, one way is to customize how the library is loaded: https://cjycode.com/flutter_rust_bridge/guides/how-to/load-library

**Comment by Berrysoft** [comment]
@fzyzcjy Thank you for your advice! However after I choose to load the library from the process, the bridge complains cannot find `store_dart_post_cobject`. I revert back the changes to use the `dummy_method_to_enforce_bundling` method, but the generated header by codegen doesn't include the declaration of `drop_dart_object`, `get_dart_object`, `new_dart_opaque` and `store_dart_post_cobject`. Did I missed some steps?

**Comment by Berrysoft** [comment]
Or, where should I change the link args to make the linker always link the static lib so that I don't need the dummy method to enforce bundling?

**Comment by fzyzcjy** [comment]
> but the generated header by codegen doesn't include the declaration of drop_dart_object, get_dart_object, new_dart_opaque and store_dart_post_cobject.

Ok this seems to be a bug, because dummy_method_to_enforce_bundling is not used in the cargokit-based approach so I missed it - feel free to PR (looks like a `good-first-issue`)! I guess it is as simple as, editing https://github.com/fzyzcjy/flutter_rust_bridge/blob/cfd88621f77de211a9c214508b2dfcca29efd4e7/frb_codegen/src/library/codegen/generator/wire/c/spec_generator/dummy_function.rs#L25 and make it `func_names + EXTRA_EXTERN_FUNC_NAMES`.

Before fixing it, maybe firstly try to manually add that few functions, and see whether it works.

**Comment by Berrysoft** [comment]
> EDIT: Seems that it is already generated

The *declaration* is not generated:) I mean the signature `void store_dart_post_cobject(DartPostCObjectFnType ptr);` is not generated.

And by the way it seems that the other 3 methods are no longer needed.

**Comment by fzyzcjy** [comment]
Oh looks reasonable!
