### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by a937983423** [fzyzcjy/flutter_rust_bridge#1777]
Hello developer, I have tried out this framework and it's really great, but there are a few significant issues that significantly impact the user experience which I hope can be changed. Firstly, the framework outputs text not only in the title bar but also in the middle of the interface, which is aesthetically unpleasing. Secondly, as a beginner, I am unsure where to start writing code; I would greatly appreciate it if the documentation could include an example demonstrating how to write code in Rust for loading an image and text. My gratitude would be immense for such a provision.

**Comment by fzyzcjy** [comment]
Hi,

> Firstly, the framework outputs text not only in the title bar but also in the middle of the interface, which is aesthetically unpleasing.

I am not sure which part do you mean - do you mean the logs when running codegen?

> Secondly, as a beginner, I am unsure where to start writing code; I would greatly appreciate it if the documentation could include an example demonstrating how to write code in Rust for loading an image and text.

What about https://cjycode.com/flutter_rust_bridge/demo/ (with source code included)
