### ISSUE TITLE
Incompatibility with windows crate

### ISSUE THREAD

**Issue by TallonIV** [fzyzcjy/flutter_rust_bridge#1784]
### Describe the bug

Hello, I am writing a rust app with the windows crate _https://github.com/microsoft/windows-rs_ in my rust code. When I generate the glue of flutter with rust with `flutter_rust_bridge_codegen generate`, I get an error when I compile the rust code that in _frb_generated.rs_. What happens is that the imports of the windows crate don´t get generated, like` use windows::Win32::Foundation::HANDLE;` or `use windows::Win32::System::Memory::MEMORY_BASIC_INFORMATION;`.

When I manually add the imports most of the errors disappear, but I still get the error:
`419  | / flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
420  | |     flutter_rust_bridge::for_generated::rust_async::RwLock<MEMORY_BASIC_INFORMATION>
421  | | );
     | |_^ `*mut c_void` cannot be sent between threads safely
`. and I can´t compile my app. 
How could I compile the app when using the import of _MEMORY_BASIC_INFORMATION_?

### Steps to reproduce

1. Create flutter_rust_bridge app and add the _windows_ crate.
2. Import the module _MEMORY_BASIC_INFORMATION_.
3. Write code that uses `std::mem::size_of::<MEMORY_BASIC_INFORMATION>()` or `let mut regions: Vec<MEMORY_BASIC_INFORMATION> = Vec::new();`
4. Execute in terminal `flutter_rust_bridge_codegen generate`
5. Try to compile the app.

### Logs

```shell
error[E0277]: `*mut c_void` cannot be sent between threads safely
    --> src\frb_generated.rs:419:1
     |
419  | / flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
420  | |     flutter_rust_bridge::for_generated::rust_async::RwLock<MEMORY_BASIC_INFORMATION>
421  | | );
     | |_^ `*mut c_void` cannot be sent between threads safely
     |
     = help: within `Memory::MEMORY_BASIC_INFORMATION`, the trait `std::marker::Send` is not implemented for `*mut c_void`
note: required because it appears within the type `MEMORY_BASIC_INFORMATION`
```

### Expected behavior

Compile the app for windows and be able to execute it.

### OS

Windows 11

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.24

### Flutter info

```shell
[√] Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.22631.3155])
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (5 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34616.47
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • Flutter plugin version 78.1.1
    • Dart plugin version 233.13763.5

[√] VS Code (version 1.86.2)
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.189
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.52

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by fzyzcjy** [comment]
Hi, firstly try `pub use` for the things that you want to export.

Secondly, yes it requires Send/Sync currently in order to be safe Rust. The simplest way is to wrap using a `Mutex`.

**Comment by TallonIV** [comment]
Thanks, I am already fixing it.

**Comment by fzyzcjy** [comment]
You are welcome!
