### ISSUE TITLE
Asynchronous notification from Rust

### ISSUE THREAD

**Issue by smw-wagnerma** [fzyzcjy/flutter_rust_bridge#179]
**Is your feature request related to a problem? Please describe.**
A use case is to get data from the Rust side asynchronous through some kind of event to signal that new data is ready

**Describe the solution you'd like**
It would be nice to trigger a dart callback function to get the data from Rust 

**Describe alternatives you've considered**
Send back the data asynchronous to the dart side

**Additional context**
–

**Comment by fzyzcjy** [comment]
That is what `Stream` is about.

**Comment by fzyzcjy** [comment]
Have a look at this example: https://github.com/fzyzcjy/flutter_rust_bridge/blob/275651b2636795dfddad46968a4756b718902f06/frb_example/pure_dart/rust/src/api.rs#L133

**Comment by smw-wagnerma** [comment]
Thanks, I haven‘t look at the dart example, only Flutter;-). It works. I should start a PR to improve the doc…

**Comment by fzyzcjy** [comment]
Sure, no problem :)
