### ISSUE TITLE
Error: Try to use `RustArc<dynamic>` after it has been disposed

### ISSUE THREAD

**Issue by kjzl** [fzyzcjy/flutter_rust_bridge#1791]
### Describe the bug

I made a minimal reproducible project to my problem and I am having trouble understanding what I am doing wrong.
I mainly use frb with Web, but also tested if the problem occurs with the project compiled to linux, which it does for me.

I uploaded the few necessary files to reproduce my issue. Just create a new frb project and paste the source files.
[frb_problem.zip](https://github.com/fzyzcjy/flutter_rust_bridge/files/14431810/frb_problem.zip)

When the Widgets build first, everything displays as expected, when they rebuild I get the error `Try to use RustArc<dynamic> after it has been disposed`.
The State from which the widgets are being built is held in a frb struct on the dart side using `get_it`.

PS: When compiling to linux I encountered [this issue](https://github.com/irondash/cargokit/issues/57) as it seems, for which a fix was already merged, which has me wondering whether this project includes a outdated version of cargokit and how one is supposed to update it?

### Steps to reproduce

1. flutter_rust_bridge_codegen generate && flutter run
2. click the 'refresh' Button
3. Exception is thrown

### Logs

```shell
-
```

### OS

Linux

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.25

**Comment by fzyzcjy** [comment]
Hi, it would be great to make it a github repo to make it easy to view :) I will check it then

> PS: When compiling to linux I encountered https://github.com/irondash/cargokit/issues/57 as it seems, for which a fix was already merged, which has me wondering whether this project includes a outdated version of cargokit and how one is supposed to update it?

Just copy-paste latest cargokit to replace the old one in your project folder. Cargokit suggests doing so IIRC.

**Comment by kjzl** [comment]
https://github.com/kjzl/frb_dropped_arc_min_reproducible

**Comment by kjzl** [comment]
Great, thank you!

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by kjzl** [comment]
I believe the changes introduced in #1805 result in undesired behavior. In case one creates a opaque struct which is to be stored inside another struct/enum it also becomes opaque by default.
Consider the following scenario where my enum Baz will be made opaque by default in the newest version of frb:
```
#[flutter_rust_bridge::frb(opaque)]
pub struct Foo(...);
impl Foo {...}

#[flutter_rust_bridge::frb(opaque)]
pub struct Bar(...);
impl Bar {...}

pub enum Baz {
    FooVariant(Foo),
    BarVariant(Bar),
}
```

Can one somehow force a type to be non-opaque?

**Comment by fzyzcjy** [comment]
Yes, by `#[frb(non_opaque)] pub enum Baz`.

**Comment by fzyzcjy** [comment]
Close since this seems to be solved. Feel free to reopen if having any issues!
