### ISSUE TITLE
Can this package build rust for release ant not just debug?

### ISSUE THREAD

**Issue by jdiaz97** [fzyzcjy/flutter_rust_bridge#1806]
Hello!

I'm seeing that `flutter_rust_bridge generate `builds the rust binaries in debug mode, is it possible to do it for a release mode?

**Comment by fzyzcjy** [comment]
Sure!

Firstly, this seems to be something related to cargokit, instead of flutter_rust_bridge code. IIRC just `flutter run --release` and it should auto make Rust in release mode. If that somehow does not work, feel free to tell me!
