### ISSUE TITLE
flutter_rust_bridge_codegen@^2.0.0-dev.0 not found

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#1812]
Follow the official website https://cjycode.com/flutter_rust_bridge/ step by step, the first step is wrong

**Comment by fzyzcjy** [comment]
Hi, could you please show the exact command and outputs for debugging?

**Comment by fzyzcjy** [comment]
> No need for llvm now?

Yes, the default version does not need that.
