### ISSUE TITLE
I am a newcomer who just learned rust, how do I create RustOpaque <RwLock<Client>>?

### ISSUE THREAD

**Issue by mdddj** [fzyzcjy/flutter_rust_bridge#1813]
I found this function in the documentation, but I don't know how to create and return it
<img width="1062" alt="image" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/29020213/8f245f33-d1f9-4f80-8443-e526271af1a6">
my code 
```rs
use std::sync::RwLock;

use aria2_ws::Client;

use crate::frb_generated::{RustAutoOpaque, RustOpaque};

pub enum ConnectError {
    Fail,
}

pub async fn connect_aria2_client(url: String, token: Option<&str>) -> RustOpaque<RwLock<Client>> {
    let client = Client::connect(&url, token).await.unwrap();
    return RustOpaque::new(RwLock::new(client));
}

```
This is its error message.
<img width="1143" alt="image" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/29020213/0664d60e-3767-4dcf-9b8a-76b970cb4782">

**Comment by fzyzcjy** [comment]
Hi, maybe try to `pub use aria2_ws::Client;`

**Comment by mdddj** [comment]
Thanks, that's solved now.
