### ISSUE TITLE
[Question] How to do transient update from v2.0.0-dev.X to v2.0.0-dev.Y

### ISSUE THREAD

**Issue by NightBlaze** [fzyzcjy/flutter_rust_bridge#1814]
Is it enough to?
• remove package with `cargo uninstall v2.0.0-dev.X`
• install new version with `cargo install v2.0.0-dev.Y`
• update version in Cargo.toml

**Comment by fzyzcjy** [comment]
Hi, just do https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/upgrade/regular is enough. e.g.

```
cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0' && flutter_rust_bridge_codegen generate

**Comment by NightBlaze** [comment]
Thanks

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by fzyzcjy** [comment]
Close since this is solved. Feel free to reopen if having any issues!
