### ISSUE TITLE
multiple isolates in flutter

### ISSUE THREAD

**Issue by ggslayer** [fzyzcjy/flutter_rust_bridge#1817]
Hi, when I create a new isolate in flutter,  call rust api in the new isolate, the error report: "flutter_rust_bridge has not been initialized. Did you forget to call `await  RustLib.init();`?".

So, I have two question:
1. does RustLib.init must be called in every isolate?
2. if multiple isolate, the rust lib will exists multiple instance  or one instance  shared by multiple isolate?

thank you

**Comment by fzyzcjy** [comment]
Hi, does this doc work for you: https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/isolates

**Comment by fzyzcjy** [comment]
Close since this seems to be solved. Feel free to reopen if having any issues!
