### ISSUE TITLE
How to package into a dart package and upload it to pub.dev for others to use

### ISSUE THREAD

**Issue by mdddj** [fzyzcjy/flutter_rust_bridge#1819]
I found that the plugin depends on this package, there are some scripts in it, but it can't be uploaded to pub.dev, is there any other way to do it?
```yaml
  rust_lib_aria2_plugin:
    path: rust_builder
```

**Comment by fzyzcjy** [comment]
Hi, you can have a look at cargokit (which is also used by flutter_rust_bridge's default template). Its sample usage will guide you through how to make a publishable package.

**Comment by mdddj** [comment]
Hi, and thank you for your response. I tried adding the cargokit to the plugins folder as outlined in the blog article, along with certain configuration settings. Unfortunately, the cargokit does not initialize correctly. Please find below the list of files I have added or modified for your reference. ([Flutter plugin in Rust with no prebuilt binaries](https://matejknopp.com/post/flutter_plugin_in_rust_with_no_prebuilt_binaries/))

```dart
  await RustLib.init();
```
<img width="1138" alt="image" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/29020213/3ba8c642-82f2-4337-81fc-6f2093885730">
<img width="1024" alt="image" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/29020213/dbd0f2ac-34b6-4497-bac5-b296635a8f0f">
<img width="790" alt="image" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/29020213/6853a941-62d6-4985-a447-bd95fbb9946f">

**Comment by fzyzcjy** [comment]
> Unfortunately, the cargokit does not initialize correctly.

Hi, seems that the cargokit part has not succeed yet. Then one way is to firstly go through the cargokit tutorial to make a running demo, and (only after success) add flutter_rust_bridge and make it work.

**Comment by fzyzcjy** [comment]
You are welcome and happy to see it is solved!
