### ISSUE TITLE
Is there a way to completely remove flutter_rust_bridge support from specific platforms?

### ISSUE THREAD

**Issue by JohnnnyWang** [fzyzcjy/flutter_rust_bridge#1820]
**Is your feature request related to a problem? Please describe.**
This is a question, not a feature suggestion.
I would like to be able to retain flutter_rust_bridge support for macos, windows and android, but would like to completely remove support for the ios platform.
Since rust_libs introduces the ring component, it cannot be compiled on ios x86_64 (simulator)
Or run normally, and ios does not need rust_libs support. I hope to completely remove it (complete removal means that ios compilation no longer relies on rust_libs)

Additional information:
I have created the project through flutter_rust_bridge, is there a way to accomplish the goal without re-create the entire project?

Thanks

**Comment by fzyzcjy** [comment]
> Since rust_libs introduces the ring component

Curious what is that? A quick search in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/dart_minimal/rust/Cargo.lock does not show anything about "ring".

If it is your code that adds that dependency, you can use rust's https://stackoverflow.com/questions/29854912/how-to-have-different-dependencies-depending-on-os-family

> I have created the project through flutter_rust_bridge, is there a way to accomplish the goal without re-create the entire project?

Maybe try to remove https://github.com/fzyzcjy/flutter_rust_bridge/blob/39ab69e52193586004a463b52757de7fde745b59/frb_example/flutter_via_create/rust_builder/ios/rust_lib_flutter_via_create.podspec#L29-L38 this part in your project. It should remove the hook to build rust. Maybe https://github.com/fzyzcjy/flutter_rust_bridge/blob/39ab69e52193586004a463b52757de7fde745b59/frb_example/flutter_via_create/rust_builder/ios/rust_lib_flutter_via_create.podspec#L43 also needs to be removed.

**Comment by JohnnnyWang** [comment]
OK, thanks for your reply. According to my investigation, it is because my business code uses ring instead of flutter_rust_bridge

**Comment by fzyzcjy** [comment]
I see. You are welcome!
