### ISSUE TITLE
Not working on chrome

### ISSUE THREAD

**Issue by dhrubrawat66** [fzyzcjy/flutter_rust_bridge#1829]
### Describe the bug

1. i create the by using standard template
2. then when i run it on browser
3. it render on browser but it doesnot any content
![one](https://github.com/fzyzcjy/flutter_rust_bridge/assets/85351405/f1554e68-cdf9-4b7f-8420-26e61a39a738)
5. but i remove follwing the, but i render the chrome with content
![two](https://github.com/fzyzcjy/flutter_rust_bridge/assets/85351405/5060a79b-a1c7-4f90-975d-42081077a36b)

### Steps to reproduce

Hint: A simple way to reproduce is to clone and modify the https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal example package according to your needs.
1. ...
2. ...
3. ...
s

### Logs

```shell
d
```

### Generated binding code

```shell
#[flutter_rust_bridge::frb(sync)] // Synchronous mode for simplicity of the demo
pub fn greet(name: String) -> String {
    format!("Hello, {name}!")
}

#[flutter_rust_bridge::frb(init)]
pub fn init_app() {
    // Default utilities - feel free to customize
    flutter_rust_bridge::setup_default_user_utils();
}
```

### OS

window

### Version of `flutter_rust_bridge_codegen`

flutter_rust_bridge_codegen 2.0.0-dev.28

### Flutter info

```shell
Flutter 3.19.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68bfaea224 (32 hours ago) • 2024-03-20 15:36:31 -0700
Engine • revision a5c24f538d
Tools • Dart 3.3.2 • DevTools 2.31.1
```

### Version of `clang++`

clang version 17.0.1

**Comment by fzyzcjy** [comment]
Hi, could you please check/paste the browser's console output?

**Comment by fzyzcjy** [comment]
Close since inactivity, but feel free to reopen if still having any questions!
