### ISSUE TITLE
How to support RefCell ?

### ISSUE THREAD

**Issue by mdddj** [fzyzcjy/flutter_rust_bridge#1832]
function
```rs
pub fn create_sql_connect() -> Result<Connection, String> {
    let conn = Connection::open_in_memory();
    match conn {
        Ok(r) => Ok(r),
        Err(e) => Err(format!("error:{e}")),
    }
}

```
Struct definition (From third-party libraries)
```rs
pub struct Connection {
    db: RefCell<InnerConnection>,
    cache: StatementCache,
}
```
The generated code reports an error `frb_generated.rs`
<img width="733" alt="image" src="https://github.com/fzyzcjy/flutter_rust_bridge/assets/29020213/8a9db31a-a4e4-4e1f-8676-64250f6e608a">

**Comment by fzyzcjy** [comment]
Hi, firstly it would be great to paste the error logs as text for future searches.

Secondly, the log says `Sync` is not implemented for it. What about using Mutex/RwLock?

**Comment by mdddj** [comment]
Thanks, it will work normally if changed to this.
```rs
pub fn create_sql_connect() -> Result<Box<Mutex<Connection>>, String> {
    let conn = Connection::open_in_memory();
    match conn {
        Ok(r) => Ok(Box::new(Mutex::new(r))),
        Err(e) => Err(format!("error:{e}")),
    }
}

pub fn execute_sql(connect: Box<Mutex<Connection>>, sql: String) {
    let conn = connect.lock().unwrap();
    let _ = conn.execute(&sql, ());
}
```

**Comment by fzyzcjy** [comment]
You are welcome and happy to see it works!
