### ISSUE TITLE
Support converting chrono::NaiveDate to Dart

### ISSUE THREAD

**Issue by TrackerSB** [fzyzcjy/flutter_rust_bridge#1833]
Recent updates of the dependency to allo-isolate introduced support `chrono::NaiveDate` in FRB. However, when converting a Rust struct containing a field of type `chrono::NaiveDate` a (working 👍🏻) Dart class which extends from `RustOpaque` is generated.

Despite the fact that this should be enough to technically utilize the Dart class it would be much nicer if it generated a field of type `DateTime` instead of depending on `RustOpaque`. This enables quite more capabilities on the Dart side. In my case especially reflection.

**Comment by fzyzcjy** [comment]
Sure! Looking forward to reviewing and merging #1834 :)

**Comment by TrackerSB** [comment]
It is still currently worked on trying to keep up with resolving conflicts with origin/master and adapting to CI requirements.

**Comment by fzyzcjy** [comment]
(Mark as `awaiting` since there is ongoing PR, thus the issue is awaiting PR)
