### ISSUE TITLE
Add ability for using freezed to generate classes

### ISSUE THREAD

**Issue by jquesada2016** [fzyzcjy/flutter_rust_bridge#1837]
**Is your feature request related to a problem? Please describe.**

Currently, it seems like only sum-type enums are using `@freezed` to generate their classes. It would be really nice if we could opt in to using `@freezed` for other transferable classes, mostly to get the nice codegen that comes with the `copyWith()` method.

**Describe the solution you'd like**

Add something like `#[frb(freezed)]`.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by jquesada2016** [comment]
Nevermind, I just found [this](https://cjycode.com/flutter_rust_bridge/guides/types/translatable/detailed/struct).

Can we please get a link to these docs in the docs.rs documentation? I always have to hunt down the link in the github repo

**Comment by fzyzcjy** [comment]
> Can we please get a link to these docs in the docs.rs documentation? I always have to hunt down the link in the github repo

Sure! Where do you think we should put it?

**Comment by jquesada2016** [comment]
It could be one of the first things at the top of the crate's docs as well as in the attribute macro's docs. There it says to go read the docs but doesn't say where to find them :p

**Comment by fzyzcjy** [comment]
Good idea, feel free to PR!

**Comment by fzyzcjy** [comment]
Close since doc is updated and the feature is there. Feel free to reopen if needed!
