### ISSUE TITLE
Static methods/getters aren't generated correctly in dart

### ISSUE THREAD

**Issue by jquesada2016** [fzyzcjy/flutter_rust_bridge#1838]
### Describe the bug

Given the following code:

```rust
pub struct MyStruct {}

impl MyStruct {
  pub fn my_function() {}
  }
```

Does not output the `MyStruct` class in dart, presumably because it's not being referenced anywhere else, but this is often needed for better code organization, rathern than relying solely on top-level functions.

Regarding getters

```rust
#[frb(opaque)]
pub struct MyStruct {}

impl MyStruct {
  #[frb(sync)]
  pub fn new() -> Self {
    Self {}
  }

  #[frb(sync, getter)]
  pub fn a() -> String {
    "apple".into()
  }
}
```

generates invalid dart code, because it tries to pass a hint parameter which doesn't exist in a getter

### Steps to reproduce

1. Copy/paste the above examples into a new project
2. Run codegen
3. Observe the errors from dart

### Logs

```shell
N/A
```

### Expected behavior

Static methods should always be generated on classes, even if the struct isn't part of a public API directly.

Static getters should be generated correctly.

**Comment by fzyzcjy** [comment]
This looks like a bug, I do expect them to work. Feel free to PR, alternatively I will fix in the next batch (possibly within several days)

**Comment by fzyzcjy** [comment]
(oops close by mistake)
