### ISSUE TITLE
Methods aren't being generated for structs declared at the api root

### ISSUE THREAD

**Issue by jquesada2016** [fzyzcjy/flutter_rust_bridge#1841]
### Describe the bug

If I put a struct at the root of the api, i.e. `src/api/mod.rs`, structs are converted to classes, but no methods are added to them.

```rust
struct MyStruct {}

impl MyStruct {
  #[frb(sync)]
  pub fn do_it(&self) {}
}
```

The class `MyStruct` is generated, but with no methods. This behavior is the same whether the struct is opaque or not.

If I move the struct anywhere else in the api sub-module, it then works.

### Steps to reproduce

1. Copy the above example into `src/api/mod.rs`
2. Generate the code
3. Observe the lack of methods
4. Move the example to `src/api/works.rs`
5. Generate the code
6. Observe it now works

### Logs

```shell
N/A
```

**Comment by fzyzcjy** [comment]
That looks like a bug, but the workaround is to try to put it at non-mod.rs. I may look at it later to see whether there is an easy fix.

**Comment by fzyzcjy** [comment]
Hope #2000 will make declared at api root supported :)
