### ISSUE TITLE
Support conversion of &[T] and &str between languages

### ISSUE THREAD

**Issue by w-utter** [fzyzcjy/flutter_rust_bridge#1853]
Maybe this isn't the way to pass references across the ffi boundary, but say we have a rust defined struct which has been crossed over to dart, say `List<RustType>`, if we wanted to modify that type by taking a `&mut [RustType]` in rust. In Flutter, the corresponding type in the function declaration would be `RustType` which isn't completely correct.

Similarily, on the other side, if we wanted to return a &str from rust into flutter, we would have to clone the string in order to send it across the ffi boundary, since `the trait SSeEncode is not implemented for &str`. 

Having to send owned variants across FFI is a way to bypass this, but I think that being able to pass references would be a much better option (aside from issues that may arise from lifetimes).

**Comment by fzyzcjy** [comment]
Hi, have you tried the `opaque` feature? That one seems to be related.

**Comment by fzyzcjy** [comment]
Close since inactivity, but feel free to reopen!
