### ISSUE TITLE
Cannot implement custom async runtime

### ISSUE THREAD

**Issue by TaeHagen** [fzyzcjy/flutter_rust_bridge#1858]
### Describe the bug

According to the docs, in v2 you should be able to implement your own `BaseAsyncRuntime`. However, I created a struct that implements it, but it is never called. I think I need to declare a new executor, but there appears to be no way to access all the types I need to do that because many of them are not exported. How can I provide a custom async runtime? I need to manage it's lifecycle outside of the context of this project for background work when the dart VM is not active.

Thank you!

### Steps to reproduce

Hint: A simple way to reproduce is to clone and modify the https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal example package according to your needs.
1. ...
2. ...
3. ...

### Logs

```shell
None applicable
```

### Version of `flutter_rust_bridge_codegen`

2.0

**Comment by fzyzcjy** [comment]
>  I think I need to declare a new executor, but there appears to be no way to access all the types I need to do that because many of them are not exported

Hmm then that looks like a bug! Feel free to PR to fix it (export needed variables), or alternatively I will fix it in the (hopefully within a week) next batch.

**Comment by TaeHagen** [comment]
Could I instead change the `DefaultExecutor` type to have another type parameter, one for the async runtime?

**Comment by fzyzcjy** [comment]
Sure, you are free to use whatever executor you like.
