### ISSUE TITLE
Adding auto generation from Rust to Dart for toString() and compareTo() methods

### ISSUE THREAD

**Issue by VladTheJunior** [fzyzcjy/flutter_rust_bridge#1869]
**Is your feature request related to a problem? Please describe.**
I can not find a way to override default Dart toString() and compareTo() method for my Rust struct that implements custom Display (or ToString) Eq, PartiqlEq, Ord, PartialOrd traits.

**Describe the solution you'd like**
Adding auto generation of code for Display (or ToString) Eq, PartiqlEq, Ord, PartialOrd traits to Dart class

**Comment by fzyzcjy** [comment]
Currently you can provide arbitrary extra Dart code via https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/dart-code.

Also related: https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/eq-hash#custom-arbitrary

**Comment by VladTheJunior** [comment]
Thanks, it works!

**Comment by fzyzcjy** [comment]
You are welcome!
