### ISSUE TITLE
How to make a flutter package with the built librust.a or .so for iOS/Android?

### ISSUE THREAD

**Issue by kanx99** [fzyzcjy/flutter_rust_bridge#1872]
Now I can use v2.0.0-dev.28 to build running iOS/Android app. 
I've checked https://cjycode.com/flutter_rust_bridge/manual/integrate/library/creating-libraries/dart-only and https://cjycode.com/flutter_rust_bridge/manual/integrate/library/creating-libraries/flutter-wrapper, but still can't get it to work.
I wonder how to turn it into a flutter package with the built librust.a or .so that other developers can use it without any rust related settings.

**Comment by fzyzcjy** [comment]
Hi, could you please point out specific errors such that I can have a look?

**Comment by Zacchaeus-Oluwole** [comment]
> Hi, could you please point out specific errors / issues such that I can have a look?

How can I create flutter package with the flutter_rust_bridge? Is there any documentation on that?

**Comment by fzyzcjy** [comment]
Close since inactivity. Feel free to reopen if having any issues!
