### ISSUE TITLE
After #1867, StreamSink never returns

### ISSUE THREAD

**Issue by Jhonfunk** [fzyzcjy/flutter_rust_bridge#1873]
After #1867, StreamSink does not return until the rust function has finished. So how about those streams that need to last a long time?

**Comment by fzyzcjy** [comment]
Hi, what about this:

```rust
pub fn func(sink: StreamSink<String>) {
    (FLUTTER_RUST_BRIDGE_HANDLER.thread_pool()).execute(transfer!(|| {
        ... your long executing code here ...
    }));
}
```

Alternatively, you can spawn a thread by whatever other approaches you like.

**Comment by NightBlaze** [comment]
I don't have issues with StreamSink but agree with @fzyzcjy solution. I think that the right approach is that an application should always be asynchronous/multithreaded and should not block waiting for a response.
