### ISSUE TITLE
Async Rust to Dart Stream Conversion Issue

### ISSUE THREAD

**Issue by 7reax** [fzyzcjy/flutter_rust_bridge#1874]
### Describe the bug

For synchronous Rust methods returning a stream, the Dart code generation in works correctly, providing a `Stream<String>`. However, with the recent update, when Rust methods are async and should return a stream, the Dart code generation produces a `Future<Stream<String>>`. This leads to all stream elements being emitted at once after the async Rust method completes.

### Steps to reproduce

1. Create an asynchronous Rust method that is intended to return a stream of strings. For example:
```rust
pub async fn lsx_get_event_stream(pid: u32, game_sink: StreamSink<String>) -> anyhow::Result<()>  {
    // code
}
```
2. Generate the Dart bindings.
3. Attempt to use the generated Dart method expecting a stream of strings to be processed as they are send. Instead, find that the stream only starts emitting values after the entire async Rust method has completed execution.

### Logs

```shell
-
```

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.31

**Comment by fzyzcjy** [comment]
Hi, could you please check https://github.com/fzyzcjy/flutter_rust_bridge/issues/1873 - does that solve your scenario?

**Comment by fzyzcjy** [comment]
Also related #1836, cc @uditrugman

**Comment by fzyzcjy** [comment]
Brainstorms: one solution may be that, we by default use the old semantics, and at the same time allow `#[frb(dart_async)]` (which creates the semantics today) and `#[frb(sync)]`.

**Comment by 7reax** [comment]
> Hi, could you please check #1873 - does that solve your scenario?

Correct me if I'm wrong, but it looks like this thread pool would escape the tokio runtime. We need to be able to use async functions while pushing to the stream, is that still possible?

**Comment by fzyzcjy** [comment]
Hmm, then does tokio::spawn work for you?

**Comment by 7reax** [comment]
> Hmm, then does tokio::spawn (instead of thread pool spawn) work for you?

Yeah, tokio::spawn works for us. Thanks!

**Comment by fzyzcjy** [comment]
You are welcome!

In addition, you want wait for the next release, since in #1877 I revert the default semantics. (But you can still have today's semantics via a simple `#[frb(...)]` annotation)
