### ISSUE TITLE
Portable application possible?

### ISSUE THREAD

**Issue by acul009** [fzyzcjy/flutter_rust_bridge#1902]
**Is your feature request related to a problem? Please describe.**
I would love to compile my app into a single executable, as if I was statically compiling my rust application

**Describe the solution you'd like**
From what I have read, flutter doesn't actually support this.
[Link to the flutter issue](https://github.com/flutter/flutter/issues/33835)

Maybe a small self-extractor could be included?

**Describe alternatives you've considered**
I could use another framework like sciter, tauri or dioxus

**Additional context**
I just wanted to ask if this is possible with the help of rust, though I'm guessing it is not :(

**Comment by fzyzcjy** [comment]
Hi, may I know what platform are you planning to use? 

> Maybe a small self-extractor could be included?

I guess this is possible. For example, for windows, a quick search using `windows create self extracting exe` gives some tools.

Btw, maybe ask on flutter community as well, since this looks like general flutter question.

**Comment by acul009** [comment]
I plan on supporting Windows, Linux, Mac, Android and IOS.

Though this is mostly just an issue on Windows and Linux, since the other platforms use native app archive formats.

I already searched around quite a bit, but it seems flutter just doesn’t support static linking. I just wanted to know if someone here maybe knew a trick using rust.

For Linux maybe Appimage might be a nice option. For Windows I think the only Option would be a self-extractor - either one in rust, like rustdesk seems to be using or maybe one made with 7-zip.


Thanks for your help, you can close this issue if you want :)

**Comment by fzyzcjy** [comment]
I see. Maybe we can make it open for a while to see whether someone else has some ideas (though I guess the probability is low given you have done this much searches)
