### ISSUE TITLE
Use --remap-path-prefix RUSTFLAG to canonicalize build directory

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#1909]
**Is your feature request related to a problem? Please describe.**
Panic messages/stack traces include the full path to the cargo directory on the build machine, e.g. /Users/aran/.cargo<...> in my case. 

**Describe the solution you'd like**
Use `--remap-path-prefix` or some other solution to canonicalize (and disguise!) the build path in `build-web` command.  e.g. https://users.rust-lang.org/t/how-to-properly-use-remap-path-prefix/104406/6

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fzyzcjy** [comment]
Now we support `--wasm-pack-rustflags`, which can provide arbitrary custom RUSTFLAGS env variable. Therefore, I guess this issue can be solved by providing a custom one. Feel free to reopen if there are any problems!

**Comment by aran** [comment]
If I pass `--wasm-pack-rustflags` to pass in `--remap-path-prefix`, it loses the default `-C target-feature=+atomics,+bulk-memory,+mutable-globals`. Don't know if there is a rust convention for situations like that, or maybe I can do --wasm-pack-rustflags="$DEFAULT_FRB_RUSTFLAGS --remap-path-prefix ..." or something like that.

**Comment by fzyzcjy** [comment]
Totally agree. I am not sure whether we should use "$DEFAULT_FRB_RUSTFLAGS" though, since it looks like an environment variable, and users may gets confused.

**Comment by aran** [comment]
I haven't been able to think of an elegant way to express it.

**Comment by fzyzcjy** [comment]
More brainstorms: Another way may be, check whether the user-provided wasm-pack-rustflags does *contain* the default one or not. If not, hint the user.

**Comment by aran** [comment]
That would have saved me some confusing broken builds!

**Comment by fzyzcjy** [comment]
Let me reopen this issue to track that ;)
