### ISSUE TITLE
Implement `Vec<String>`

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#191]
**Is your feature request related to a problem? Please describe.**

I came across this hiccup when designing my API, I think this is easy enough yet has high impact and should be implemented soon.

**Describe the solution you'd like**

Make `wire_list_String` hold a `*mut *mut wire_list_uint_8` and implement the missing methods (api_fill).

**Describe alternatives you've considered**

I haven't tried, but a `Vec<Vec<u8>>` might work but not very ergonomically.

I'm a bit busy right now, so I might not make a PR right away but I will eventually come around to it.

**Comment by fzyzcjy** [comment]
Sounds wonderful and looking forward to the PR!

To add my two cents, maybe we can also write down a new `Delegate` type named `ListString` and manually do the things.
