### ISSUE TITLE
Improve Documentation about borrow types

### ISSUE THREAD

**Issue by patmuk** [fzyzcjy/flutter_rust_bridge#1916]
I am not totally sure, but I assume that a struct with borrowed fields is `auto opaque`?

If so, can this be stated better in the documentation, for others?

My use case is having a viewModel, but defined in Rust. Thus it needs to be read by flutter, so I can't use an opaque type. But being a viewModel, I want to use borrowed values from the Model ... so the only option left is cloning the model's fields on each access ... or implementing the view logic in Flutter. So either the performance is suboptimal, or the logic might be repeated for different UIs (Flutter, cli, ...).

For example, a model like
```
struct MyModel {
    items : Vec<Field>
}
```

could have the viewModel

```
struct MyViewModel {
    my_items : Vec<&Field>
    not_my_items : Vec<&Field>
    total_item_count : u64
}
```

This is all very theoretical - as the performance hit might be not noticeable and I might never have a second UI, as Flutter covers all platforms.
But back to my request: It would be good to document this more clear if I understood it correctly.

**Comment by fzyzcjy** [comment]
> a struct with borrowed fields is auto opaque?

By default IMHO; try to add `#[frb(non_opaque)]` and see whether it works.

IIRC this was originally non-opaque, but later it gives problems on some scenarios and thus the default is flipped and it looks like this...

**Comment by patmuk** [comment]
Thanks! But it doesn't seem to work:
The lifetime parameter is missing in the generated code:
```
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::domain::share_cycle::ShareCycleViewModel {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.wanted_items.into_into_dart().into_dart(),
self.to_share_tems.into_into_dart().into_dart(),
self.completely_shared_items.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::domain::share_cycle::ShareCycleViewModel {}
impl flutter_rust_bridge::IntoIntoDart<crate::domain::share_cycle::ShareCycleViewModel> for crate::domain::share_cycle::ShareCycleViewModel {
            fn into_into_dart(self) -> crate::domain::share_cycle::ShareCycleViewModel {
                self
            }
        }
```
my struct is
```
#[flutter_rust_bridge::frb(non_opaque)]
#[derive(Debug, PartialEq, Eq)]
pub struct ShareCycleViewModel<'a> {
    pub wanted_items: Vec<&'a MediaItem>,
    pub to_share_tems: Vec<&'a MediaItem>,
    pub completely_shared_items: Vec<&'a MediaItem>,
}
```

Probably this was where the problem with non-opaque borrowed fields started?

**Comment by fzyzcjy** [comment]
Hmm, it looks like borrowed opaque types are not supported (at least yet). To work on it, maybe we can first discuss - what code should it generate? Unsafe code can definitely handle it, but I would like to have as little unsafe code as possible, surely ;)

**Comment by patmuk** [comment]
Yes, I agree - I would not like unsafe code as well.
Honestly, I think it might not be worth the effort. Probably modifying a Model to be shown in a view is part of the view, not the core ... even if different views have to do the same.
Or more general: If something in rust should be used by flutter (and not just passed through), it should be owned. Technically it might work - but I have the feeling that along the way one gets into trouble sooner or later.

**Comment by fzyzcjy** [comment]
Rethinking this, I guess another way may be:

```rust
struct MyModel {
    items : Vec<Arc<Field>>
}

struct MyViewModel {
    my_items : Vec<Arc<Field>>,
    not_my_items : Vec<Arc<Field>>,
    total_item_count : u64
}
```

i.e. use `Arc` to make `Field` shared by MyModel and MyViewModel, instead of borrowed.

**Comment by patmuk** [comment]
@fzyzcjy thanks, that is a great idea! I currently implemented it with each (complex) item having a distinct ID, and sharing a lookup table of these between dart and rust. But an Arc sounds like a better, more direct approach. Will try that :)

**Comment by fzyzcjy** [comment]
Btw there is a new feature, "proxy", that also handles some of this issue

(doc: https://cjycode.com/flutter_rust_bridge/guides/how-to/borrowed#proxy)

**Comment by fzyzcjy** [comment]
Update: I may implement support for borrow type (not guarantee but I hope so!). Then, the `MyViewModel` can be done easily.

**Comment by fzyzcjy** [comment]
New version supports lifetime: https://cjycode.com/flutter_rust_bridge/guides/lifetimes

**Comment by patmuk** [comment]
Hi @fzyzcjy,
I finally came around to read and think more about this topic. Though not enough to look into your code :/
Would you mind to briefly elaborate what are the constraints to the approaches?

Taking the example from above: 

```
struct MyModel {
    items : Vec<Field>
}
```
```
struct MyViewModel {
    my_items : Vec<&Field>
    not_my_items : Vec<&Field>
    total_item_count : u64
}
```

the MyViewModel should be read by Dart, so that the content can be shown in Flutter. MyModel is not to be manipulated by Dart directly, but Rust will update it (depending on received events, MyModel is (part of) the apps state).

The idea of having (read only) borrow types in MyModelView is to avoid copying the Field(s). In my case, these are pictures of some MBs, so I am afraid there would be performance costs.

Is it possible with one/all of the approaches to 
1. Add/remove items in MyModel::Vec<Field>
2. Read-access the items in dart over the reference in MyModelView::myItems Vec<&Field>

It looked to me that the mentioned `proxy` is made for this use case - but I am confused that this is  `Opaque`, which I (wrongly?) understood that Dart can pass around such a variable, but not read it. 
Now, as &references are supported, I wonder if this allows read access, but until Dart drops the variable, Rust would not be able to write?

I am sure I did get that all wrong ;)

If it helps: I plan to create the MyViewModel on each request (from Dart), and dispose it afterwards - it is only to show some data on some screen. MyModel, on the other hand, will be 'static, I even persist and load it to/from a file. However, the items in it will change (add/remove).

I think this is a quite general use case, basically handing a persistent app state in rust :)

**Comment by fzyzcjy** [comment]
Hi,

* Yes, if you treat `MyViewModel` using the lifetime feature, then, before it is disposed, `MyModel` will never be able to be written. But after you disposed `MyViewModel`, you can modify `MyModel` freely. That's just like how you do it on pure Rust (even without Dart).
* If such constraints of mutation is too strong, the `Vec<Arc<Field>>` way can be used.
* Proxy does not seem to solve this specific problem, because I guess your MyViewModel is expensive (at least nontrivial) to compute, while proxy indeed computes it on every access. Thus, proxy is especially useful for field getters (because it is so trivial to compute).
* Btw, I guess `MyModel` does not need to be `'static`. For example, in my mind it can be the following:

```rust
struct MyModel { ... }

impl MyModel {
  pub fn new() -> Self { ... }
  pub fn whatever_mutation_etc(&mut self, ...) { ... }
}
```

Then Dart can have `var myModel = MyModel();` at `main()`, or at widget `initState`, etc.

**Comment by patmuk** [comment]
Hi,
many thanks for the detailed answer!
Yes, I mean it more conceptual, that MyModel is 'static - I do initialize it in main.dart, by loading it from a file or creating a default instance. And mutate it quite frequently - I should have better said `singleton` maybe :)

Thanks for clarifying about `proxy`. My fields are not computation heavy, they are Hugh in size. Abstractly, each field is a picture of some MB, a users might have thousands of pictures. Thus I want to avoid copy.

One follow-up question: 
If using the lifetime feature, where does MyViewModel get disposed?
When Rust passed it to Dart? When the Dart GC did his work?

Basically, I use MyModel as state.
When the user does some action (e.g. activates a button), Dart calls a `process_event` fn in rust, which mutates the MyModel. It returns an `Effect` (an Enum variant) so that the Dart side knows that it needs to do something, e.g. rendering the mutated model. But it is up to Dart to decide when. Following this instruction, Dart calls a `fn view()` to get the MyViewModel.
(Sorry for the long buildup!)

So, when `fn view()`create a MyViewModel instance and returns it to Dart, rust could `.drop()` it, as rust doesn't need it anymore. However, Dart needs it, or more specifically the content behind the references so it can display them in an UI to the user. The user might do another action, which sends another Event to rust, which would like to mutate the MyModel ...
(I realize that this might be more of a concurrency problem, not so much an frb one :) ).

So, did I understand correctly, that as long as Dart is holding to the variable returned (MyViewModel), it is considered `&` and rust can't `& mod`? Is setting the variable to `null` disposing it?
Or is it actually using copy on the value read behind the pointer(s)?

Sorry for that probably quite basic questions ... ffi is a new field to me :/

I assume your answer will be "use Arc<Mutex<Field>>", as I anyways have a concurrency situation ... but nevertheless, I am interesting how the current lifetime implementation works :)

**Comment by fzyzcjy** [comment]
Hi, you are welcome!

> If using the lifetime feature, where does MyViewModel get disposed?
> Is setting the variable to null disposing it?

Like everything else in frb world: Either you `.dispose()` it, or it gets disposed by GC. But I guess you want a manual dispose to "unlock" MyModel.
Related: https://cjycode.com/flutter_rust_bridge/guides/lifetimes/multi-borrows

> So, did I understand correctly, that as long as Dart is holding to the variable returned (MyViewModel), it is considered & and rust can't & mod?

Yes. Just like, if you replace the word "Dart" to "Rust" in this sentence, it still holds ;)

> I assume your answer will be "use Arc<Mutex>", as I anyways have a concurrency situation ... 

Partially yes, indeed I guess using `RustAutoOpaque<...>` (which is indeed Arc + RwLock with grammar sugar) may be useful.

> but nevertheless, I am interesting how the current lifetime implementation works :)

Sure, feel free to ask!

**Comment by patmuk** [comment]
Great, many thanks!

**Comment by fzyzcjy** [comment]
You are welcome!
