### ISSUE TITLE
dart_format_line_length on configuration file does not apply to generated freezed.dart files

### ISSUE THREAD

**Issue by erdemyerebasmaz** [fzyzcjy/flutter_rust_bridge#1929]
### Describe the bug

`dart_format_line_length` on configuration file(_flutter_rust_bridge.yaml_) does not apply to generated `*.freezed.dart` files. 

`flutter_rust_bridge_codegen generate --dart-format-line-length <DART_FORMAT_LINE_LENGTH>` isn't tested but I suspect it behaves the same when generate is run from configuration file.

This behavior caused unwanted false positives on our CI workflows for static analysis & formatting.

### Steps to reproduce

N/A

### Logs

```shell
N/A
```

### Expected behavior

`--dart-format-line-length` should be applied to all generated Dart files.

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.33

### Additional context

As a workaround, we've moved generated files to a directory with no project files and we're running `dart format -l 110 <dart_output-dir>` after `flutter_rust_bridge_codegen generate` finishes.

**Comment by fzyzcjy** [comment]
Good point and feel free to PR for this! I guess the primary reason may be that, maybe the freezed is generated after formatting is applied, or the formatting forgets those files.
