### ISSUE TITLE
Hash mismatch on linux with matching hashes

### ISSUE THREAD

**Issue by TaeHagen** [fzyzcjy/flutter_rust_bridge#1932]
### Describe the bug

`Bad state: Content hash on Dart side (-1867643805) is different from Rust side (1953154019), indicating out-of-sync code. This may happen when, for example, the Dart code is hot-restarted/hot-reloaded without recompiling Rust code. (Note: This is just a sanity check. Even if content hash does not change, the code may still change and needs to be recompiled)`

However, the content hash in both the generated dart and rust source are the same `-1867643805`

### Steps to reproduce

no clue why this happens

### Logs

```shell
logs are too long for post
```

### Additional context

Is the new rust library somehow not being used? I ran `flutter clean`, still same problem

**Comment by fzyzcjy** [comment]
> Is the new rust library somehow not being used? 

I suspect so. What about trying to delete the whole `target` directory in `rust`, which contains all compiled Rust files.

**Comment by TaeHagen** [comment]
I did that, and now it works! I can't believe I didn't think of that 🤦. I suspect that would have resolved my other bug report that fixed itself upon wiping. You might want to document that as a troubleshooting step, or add it to the error message. Thank you!

**Comment by fzyzcjy** [comment]
(For potential future readers: The other issue is https://github.com/fzyzcjy/flutter_rust_bridge/issues/1863)

**Comment by fzyzcjy** [comment]
You are welcome, and happy to see that this checker does catch the problem in #1863!

> You might want to document that as a troubleshooting step, or add it to the error message.

Looks reasonable, and feel free to PR to change the https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/website/docs/manual/troubleshooting.md :)

**Comment by fzyzcjy** [comment]
Close since fixed. Feel free to reopen if needed!
