### ISSUE TITLE
Missing imports when spreading Impl blocks in multiple files

### ISSUE THREAD

**Issue by kjzl** [fzyzcjy/flutter_rust_bridge#1933]
### Describe the bug

When having a struct and an Impl for the struct in one file, and another impl for the same struct in another file with 'use' statements which werent made in the other file, they will be missing on the dart side's merged class implementation.

### Steps to reproduce

-

### Logs

```shell
-
```

**Comment by fzyzcjy** [comment]
Hi, could you please provide an exact minimal reproducible sample?

**Comment by kjzl** [comment]
https://github.com/kjzl/frb_impl_dart_missing_imports

**Comment by fzyzcjy** [comment]
Ah I see, then this is a bug. Feel free to PR for it, alternatively I will fix it later! Since this has simple workaround (move the multiple impl block for one single struct in one file), I may not fix it with highest priority.
