### ISSUE TITLE
For u64 and i128/u128 types, use BigInt in the Dart side.

### ISSUE THREAD

**Issue by iota9star** [fzyzcjy/flutter_rust_bridge#1934]
**Is your feature request related to a problem? Please describe.**

In version `2.0.0-dev.33`, the Dart code generated for `u64` uses `int`, but the value range of `u64` exceeds that of Dart's `int`. As for `i128`/`u128` types, there's no available type in Dart. I think using `BigInt` in Dart could be a good solution.

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/21272154/bcef429f-e93c-4621-8248-ab0673017b4f)

**Comment by fzyzcjy** [comment]
Looks reasonable, and feel free to PR for this! Alternatively I will try to find time to fix it later.

P.S. `usize` may also be considered the same as `u64`

**Comment by iota9star** [comment]
@fzyzcjy Do you have plans to release a new version in the next couple of days?

**Comment by fzyzcjy** [comment]
Sure! Hopefully within a day, because I want to finish some other PRs
