### ISSUE TITLE
For char types, use String on the Dart side.

### ISSUE THREAD

**Issue by iota9star** [fzyzcjy/flutter_rust_bridge#1935]
**Is your feature request related to a problem? Please describe.**
In version 2.0.0-dev.33, the Dart types generated for char types do not use the String type.
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/21272154/dc4fbceb-1d0d-4633-8bdc-e10693152562)

**Comment by fzyzcjy** [comment]
Related: https://github.com/fzyzcjy/flutter_rust_bridge/pull/1640#issuecomment-1886110024

Thus cc @Desdaemon - do you have interest in finishing the PR, or I work on the PR?

**Comment by Desdaemon** [comment]
Please do take over the PR, I'm not doing much with Flutter recently. Thanks!

**Comment by fzyzcjy** [comment]
Sure!
