### ISSUE TITLE
For the type `pub struct A(pub B)` in Dart, use either `B` or `class A { final B value; }`.

### ISSUE THREAD

**Issue by iota9star** [fzyzcjy/flutter_rust_bridge#1936]
**Is your feature request related to a problem? Please describe.**
Just like the title says.
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/21272154/82af714e-fa0c-485b-a21b-b643db25c867)

**Comment by fzyzcjy** [comment]
Looks reasonable! (I prefer the latter, since that's partially why people need newtype pattern). Feel free to PR, alternatively I will work on it in the next batch.

**Comment by Zacchaeus-Oluwole** [comment]
> **Is your feature request related to a problem? Please describe.** Just like the title says. ![image](https://private-user-images.githubusercontent.com/21272154/330107153-82af714e-fa0c-485b-a21b-b643db25c867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTI3NDAsIm5iZiI6MTcxNTY5MjQ0MCwicGF0aCI6Ii8yMTI3MjE1NC8zMzAxMDcxNTMtODJhZjcxNGUtZmEwYy00ODViLWEyMWItYjY0M2RiMjVjODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEzMTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYWU2ZGQ3YzA3ODdjMmNkOTk4ZDBiZGNhOWNiNWMzOTg2N2Q4NmEzNjMyYjViNzM2YzJhMzI2NDc1NTk1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QPyJzs7pgf1XTJ5tXhgrw7CCN_FngdJ_GQZSuAQnomo)

I have a similar issue:

@sealed
class FrSerialport extends RustOpaque {
  FrSerialport.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  FrSerialport.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FrSerialport,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FrSerialport,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FrSerialportPtr,
  );

  static Future<FrSerialport> connect(
          {required String portName, dynamic hint}) =>
      RustLib.instance.api.frSerialportConnect(portName: portName, hint: hint);
      
  static Future<List<String>> getPorts({dynamic hint}) =>
      RustLib.instance.api.frSerialportGetPorts(hint: hint);

  Future<String> get({dynamic hint}) => RustLib.instance.api.frSerialportGet(
        that: this,
      );
  Future<void> send({required String data, dynamic hint}) =>
      RustLib.instance.api.frSerialportSend(
        that: this,
        data: data,
      );
}

In the above code, i can only access FrSerialport.connect and FrSerialport.getPorts but i can't access FrSerialport.get and FrSerialport.send.
I noticed it's all the methods that take in self as an argument are the ones i can't access.

Please, what is the way out of this issue. is there a solution to it already?

**Comment by fzyzcjy** [comment]
> In the above code, i can only access FrSerialport.connect and FrSerialport.getPorts but i can't access FrSerialport.get and FrSerialport.send.
I noticed it's all the methods that take in self as an argument are the ones i can't access.

@Zacchaeus-Oluwole Hi, could you please create a separate issue and provide a minimal reproducible sample? Without the corresponding Rust code it is not easy to say what is going on :/

**Comment by Zacchaeus-Oluwole** [comment]
Alright,I will do that. Thank you

**Comment by fzyzcjy** [comment]
You are welcome

**Comment by fzyzcjy** [comment]
It seems that this is already supported. For example, in the tests:

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/5236035/36a608d6-7a8d-4519-8d42-eee697572fde)

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/5236035/13116348-2f40-4893-bc26-9e191876adc3)

Thus, I guess your question is "why it is opaque instead of non-opaque". Thus try to put `#[frb(non_opaque)]` on it.

Feel free to open if this does not solve your question!
