### ISSUE TITLE
custom ignore_for_file in generated dart file

### ISSUE THREAD

**Issue by Krysl** [fzyzcjy/flutter_rust_bridge#1948]
**Is your feature request related to a problem? Please describe.**
Show too much lint messages in VSCode problem panel, if I had defined some strict lint rules in analysis_options.yaml.
Even if I add a exclude config in analysis_options.yaml, As soon as I open the generated code file in VSCode, the exclude option does not work and the lint error is displayed again.

**Describe the solution you'd like**
Add a config in `flutter_rust_bridge.yaml`, something like to the `preamble` config in [ffigen](https://github.com/dart-lang/native/blob/main/pkgs/ffigen/README.md)

<table>
<thead>
  <tr>
    <th>Key</th>
    <th>Explaination</th>
    <th>Example</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>preamble</td>
    <td>Raw header of the file, pasted as-it-is.</td>
    <td>

```yaml
preamble: |
  // ignore_for_file: camel_case_types, non_constant_identifier_names
```

  </td>
</tr>
</tbody>

**Comment by fzyzcjy** [comment]
Looks reasonable, and feel free to PR for this!

**Comment by Krysl** [comment]
> Looks reasonable, and feel free to PR for this!看起来很合理，请随意为此进行公关！

Seems easy, I'll give it a try.

**Comment by fzyzcjy** [comment]
Feel free to ping me if needing any hints!

**Comment by Krysl** [comment]
Just done，but I don't know if there's anything missing.
