### ISSUE TITLE
Initial Add template

### ISSUE THREAD

**Issue by elsadeny** [fzyzcjy/flutter_rust_bridge#196]
Can you make a simple template example of adder programmer, the same as comes with flutter create new program. Where the adding/substract part is done with rust. Thank you.

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge#-tutorial-a-flutterrust-app This tutorial provides a more complicated example, and you can easily reduce it to a simple adder ;)
