### ISSUE TITLE
dart_code does not accept code blocks

### ISSUE THREAD

**Issue by uditrugman** [fzyzcjy/flutter_rust_bridge#1968]
### Describe the bug

codegen fails on the below:
```
#[frb(dart_code = "
    int testDartCode() {
        return 3;
    }
"
)]
```

this is the error:
```
Error: cannot parse string into token stream
```

### Steps to reproduce

Hint: A simple way to reproduce is to clone and modify the https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal example package according to your needs.
1. ...
2. ...
3. ...

### Logs

```shell
no logs needed. this is just a bug in the parser.
very easy to reproduce. just paste the above code in a rust project and it will fail to gen dart code
```

**Comment by fzyzcjy** [comment]
Good observation and feel free to PR for it! Alternative I will work on it later.

Btw, try to run with `RUST_LOG=debug` and paste the stack trace, and I guess this will be fairly easy to fix.

**Comment by fzyzcjy** [comment]
(Reopen since that one is accidentally merged)

**Comment by fzyzcjy** [comment]
Current workaround before https://github.com/dtolnay/cargo-expand/issues/227 is solved: Try to avoid having a single line with exact content `    }`, which confuses cargo-expand output parser.
