### ISSUE TITLE
For a Flutter project generated with version 2.0.0, how should I publish it to pub.dev for others to use?

### ISSUE THREAD

**Issue by iota9star** [fzyzcjy/flutter_rust_bridge#1969]
### Describe the bug

For version 2.0, I don't know how to publish the Flutter library to pub.dev.

### Steps to reproduce

...

### Logs

```shell
...
```

### Version of `flutter_rust_bridge_codegen`

2.0.0+

**Comment by fzyzcjy** [comment]
You can use arbitrary ways. One way is to use https://cjycode.com/flutter_rust_bridge/manual/integrate/cargokit (the article discusses how to create a package to be published).

**Comment by iota9star** [comment]
I've read about these, but haven't connected them. It depends on the Rust, I'll think about how to explain this dependency issue.

**Comment by fzyzcjy** [comment]
I guess one way is to follow the tutorial https://matejknopp.com/post/flutter_plugin_in_rust_with_no_prebuilt_binaries/ (IIRC they have demo repo as well), and then add flutter_rust_bridge (copy the flutter_rust_bridge.yaml, and run codegen).

Maybe I can find some time creating a template for this in flutter_rust_bridge (but cannot guarantee)

**Comment by iota9star** [comment]
Yeah, frb is cool. When I used version 2.0, I was puzzled why the previous build scripts were gone until I closely read the docs and checked the project structure.

**Comment by iota9star** [comment]
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/21272154/276fd247-53f5-4a34-accb-04688df3b42f)
There will be a dependency on the local directory of `rust_builder`, which could pose some challenges during publishing.

**Comment by fzyzcjy** [comment]
That's the default `flutter_rust_bridge_codegen create` template. My suggestion above is that, use cargokit's template (which is for a package to publish), and then add `flutter_rust_bridge.yaml` file, and run `flutter_rust_bridge_codegen generate` as usual.

**Comment by fzyzcjy** [comment]
Btw, after the PR, there will be an example: frb_example/flutter_package
