### ISSUE TITLE
Is Result<()> as return type unsupported?

### ISSUE THREAD

**Issue by surban** [fzyzcjy/flutter_rust_bridge#197]
**Describe the bug**
I am getting the following error when running flutter_rust_bridge_codegen on a file that uses `Result<()>` as return type for a function.

```
thread 'main' panicked at 'unsupported type_string: Result<()>'
```

Is it indeed a limitation on the Dart side that a function cannot return no value?

**Comment by fzyzcjy** [comment]
It is currently a limit of this package (I forgot to write it), and Dart does support it. Firstly, you can workaround by using things like `Result<i32>`. Secondly, feel free to make a PR! I will also check it later.
