### ISSUE TITLE
Generation of flutter interface to an existing lib

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#1980]
Is there a way to create a flutter interface to an existing lib ?
When I try, I have an error saying that the rust code must be in an "api" module but not directly in the lib.

The big problem is that it is very difficult to reorganize the sources because I am not the owner of the lib, and because all the code references the modules from the crate root and not from a new "api" mod.

Sorry if my question is stupid : I am very new with rust.

**Comment by fzyzcjy** [comment]
Looks like it is related to https://github.com/fzyzcjy/flutter_rust_bridge/issues/1903.

Currently, you can manually write down some wrappers in the api folder. For example, say the 3rd party crate has a function `fn f() {}`, then in api/simple.rs you can write down `fn f() { third_party_crate::f(); }`.

In the future, it would be great to support 3rd party crates directly. However, there may be some difficulty, for example, 3rd party crate may have very complex signatures, making it impossible to automatically handle.

Btw, may I know what is the 3rd party crate you want to use?

**Comment by Larpoux** [comment]
Thank you @fzyzcjy for your quick response.
Yes, I understand that I have to write myself a rust interface to the library.
My problem is that the library is huge and I would like to offer a complete interface to it to my own clients. Not just a subset.
The library is [web-audio-api-rs](https://crates.io/crates/web-audio-api/0.30.0).

I am closing this issue because it is a duplicate of [#1903].
Congratulation for this amazing tool. My first tries with it is very encouraging.

**Comment by fzyzcjy** [comment]
You are welcome!

I briefly checked it, and see there are many places that may not be easily translatable. For exmaple,

* https://docs.rs/web-audio-api/latest/web_audio_api/context/trait.BaseAudioContext.html#method.decode_audio_data_sync: The `input: R`. Maybe we need to somehow support generic, and support traits, etc.
* https://docs.rs/web-audio-api/latest/web_audio_api/node/trait.AudioNode.html#method.connect: It returns a reference type with complex lifetime. That may also not be super easy to solve.
