### ISSUE TITLE
 Enhance Type Scanning for Non-API Modules

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#1987]
Currently, `flutter_rust_bridge`[dev.36](https://github.com/fzyzcjy/flutter_rust_bridge/releases/tag/v2.0.0-dev.36) only scans types thoroughly in the Rust module `api`. However, it does not scan thoroughly for other modules. This means that types in other modules are not thoroughly scanned to generate Dart code for the fields and methods of the corresponding Rust types.

**Suggestion**:
Enhance the type scanning to include thorough scanning for all(or necessary) modules, not just the `api` module.

**Reasoning**:
Under current frb desgin. A frb project APP is like that a human body with all organs under a module called `brain` as the top organ (like the `api` module) just because the brain controls all other organs and some functionalities of the organs would be used by brain---I think it is not a good design, because according to the **Single Responsibility Principle**, different organs (modules) should be placed in different modules rather than being grouped under the CPU: the  `brain`/`api` module.

**Benefits**:
- Improved modularity and maintainability.
- Better adherence to the Single Responsibility Principle.
- More accurate and comprehensive Dart code generation for all Rust types.

**Suggested Technical Implementation Options**:
1. **Recursive Parsing**:
   - Start from the first explicit custom Rust type used in the `api` module.
   - Recursively parse each type, following the fields and parameter/return types of the current root type, as long as they are public.

2. **Configuration-Based Flexibility**:
   - Introduce a new tag in the configuration file `flutter_rust_bridge.yaml`.
   - Allow users to specify types, modules, or folders(not sure the exact scanning level yet, it is just a draft) to be scanned in addition to the `api` module.
   - Ensure that only public parts of the specified types/modules/folders are generated.

Thank you for considering this enhancement.

**Comment by fzyzcjy** [comment]
Thanks for elaborating!

> only scans types thoroughly in the Rust module api. However, it does not scan thoroughly for other modules. This means that types in other modules are not thoroughly scanned to generate Dart code for the fields and methods of the corresponding Rust types.

IMHO we do scan the whole crate currently, but we just ignore if functions are completely outside the configured folder.

Some brainstorms:

* In addition, as mentioned earlier, not only module `api` - e.g. can configure to scan whole crate.
* "[...] Introduce a new tag": Similarly, we can also allow https://github.com/fzyzcjy/flutter_rust_bridge/blob/d46844b8855891385509d4a4726f8ac0ec8aabf5/frb_example/flutter_via_create/flutter_rust_bridge.yaml#L1 to support *multiple* glob patterns. For example, suppose we write down `rust/src/api/**/*.rs,rust/src/another/**/*.rs,rust/src/a/b/c/d/e/**/*.rs`.

Does solutions like above solve your problem?

**Comment by dbsxdbsx** [comment]
> Thanks for elaborating!
> 
> > only scans types thoroughly in the Rust module api. However, it does not scan thoroughly for other modules. This means that types in other modules are not thoroughly scanned to generate Dart code for the fields and methods of the corresponding Rust types.
> 
> IMHO we do scan the whole crate currently, but we just ignore if functions are completely outside the configured folder.
> 
> Some brainstorms:
> 
> * In addition, as mentioned earlier, not only module `api` - e.g. can configure to scan whole crate.
> * "[...] Introduce a new tag": Similarly, we can also allow https://github.com/fzyzcjy/flutter_rust_bridge/blob/d46844b8855891385509d4a4726f8ac0ec8aabf5/frb_example/flutter_via_create/flutter_rust_bridge.yaml#L1
>    to support _multiple_ glob patterns. For example, suppose we write down `rust/src/api/**/*.rs,rust/src/another/**/*.rs,rust/src/a/b/c/d/e/**/*.rs`. The syntax can also be something like, `rust_input: [something, another]` (i.e. a YAML array), but maybe need to check whether command line is OK for that.
> 
> Does solutions like above solve your problem?

Yes, I think this pattern `rust/src/api/**/*.rs,rust/src/another/**/*.rs,rust/src/a/b/c/d/e/**/*.rs` is good enough to balance over Single Responsibility Principle, enhancement of frb project and flexibility for the user.

**Comment by fzyzcjy** [comment]
Feel free to PR, alternatively I will work on it :)

**Comment by dbsxdbsx** [comment]
> Feel free to PR, alternatively I will work on it :)

Frankly, I hope you could do so, because I know little about the new version, and I am afraid of some incomplete thoughts on the new version.

**Comment by fzyzcjy** [comment]
Sure, no worries!

**Comment by fzyzcjy** [comment]
Btw, I may deal with it together with https://github.com/fzyzcjy/flutter_rust_bridge/issues/1903, since that one also requires some modification about how to specify inputs.

**Comment by dbsxdbsx** [comment]
I guess with dev.38, this should be solved.  But I can't find [guidance ](https://cjycode.com/flutter_rust_bridge/guides/functions/methods) on how to deal with rust types' field/methods out of API modules.

**Comment by fzyzcjy** [comment]
Yes, now we can specify multiple inputs: https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/multi-input
