### ISSUE TITLE
frb would accept a "lib" crate and not obligate us to have an "api" module

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#1991]
This issue is more on less related to [#1903] , [#1980] and [#1990]

frb does not like a crate with a lib.rs instead of a mod.rs.
It really wants something like an "api" module and not a library.
I was able to generate a dart interface to my lib (for a very few modules) after creating an "api" module and moving all the dart code to this module.

It was not a funny task : I had to spend one full day modifying all the uses ```use crate::<something>;``` by ```use crate::api::<something>;```. 

Of course I don't like the idea to redo that each time a new library version is released. I will probably write a perl script to do that automatically. But this is really a hack. It would be  better if frb was able to accept a "lib' instead of requiring a 'mod'

**Comment by fzyzcjy** [comment]
> I had to spend one full day

IMHO, IDE can do it for you automatically. For example, when using RustRover, just drag-and-drop the files, and all are done.

> if frb was able to accept a "lib' instead of requiring a 'mod'

I agree, but to be honest, this may not be of highest priority.
Maybe when working on #1903, I will work on it as well.

**Comment by Larpoux** [comment]
Which IDE do you suggest (actually I use vi which is probably not the best IDE in the fields) ?

**Comment by fzyzcjy** [comment]
I personally use RustRover, but other IDEs are often also good (just not tried personally).

**Comment by fzyzcjy** [comment]
Btw I realize that, do you want to use that Rust crate for https://pub.dev/packages/flutter_sound? Now I can see why you want to work on that big API! Originally I thought you just want to use audio for your personal project, then usually writing a dozen lines of wrapper code is sufficient.

**Comment by Larpoux** [comment]
My project is to offer a complete Web Audio Api to flutter users, (and then I will be able to depend on it in the high level Flutter Sound plugin).
Flutter Sound offers some way to create audio streams, but the code is now broken for an obscure reason.

The Web Audio Api from W3C is really amazing. I Really want to be able to use it in a dart project.
I really want to be as closed as possible to the W3C specifications and not create a custom API that will be not very good.

**Comment by fzyzcjy** [comment]
I see, that's pretty reasonable! It is great to mimic a standard instead of creating a new API - then users need to learn something new to use the specific lib.

**Comment by fzyzcjy** [comment]
I see, that's pretty reasonable! It is great to mimic a standard instead of creating a new API - then users need to learn something new to use the specific lib.

**Comment by Larpoux** [comment]
Actually, Flutter users can access the W3C Web Audio Api in Web App, but not in iOS and Android.
I do not want to implement all the API myself : I will not be able to do it.
So I looked for an implementation that I can interface. I Found a C++ implementation (that seems to be dead), and the Rust implementation (that I want to try to use).

Here is a specification that I did two years ago but that I have not worked on that until recently:

You can see on this diagram that Flutter Sound is above τ (Tau). τ is a plugin above Rust-Audio-Api-rs (The Rust lib).
Rust-Audio-Api is above CPAL, and CPAL is above Oboe for Android.

That seems to be clean. The big point is that I am not sure that Rust-Audio-Api is stable and complete.
I am almost sure that thanks to frb, it will be possible (perhaps with work) to interface this Lib. frb seems very great.
I had some pain to include it as a flutter plugin, but it seems now OK. 
And *I AM ABLE TO USE THE XCODE DEBUGGER ON RUST CODE RUNNING iOS*. I am very happy of that 👍 

![bitmap](https://github.com/fzyzcjy/flutter_rust_bridge/assets/45900255/52816d35-c6da-49a4-a1b6-2cf2da8577f7)
