### ISSUE TITLE
Code inside mod.rs

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#1992]
This issue is more on less related to [#1991].

frb does not like mod.rs files with some code and macro inside them.
I had to remove this code from those files and create a new module with that code.

The problem is that I had also to modify the rust code to use this new module instead of the original mod.rs.

**Comment by fzyzcjy** [comment]
Looks similar to https://github.com/fzyzcjy/flutter_rust_bridge/issues/1991 (and please see reply there)
