### ISSUE TITLE
Proposal to automatically strip `get_` or `set_` prefixes from struct impl

### ISSUE THREAD

**Issue by cabaucom376** [fzyzcjy/flutter_rust_bridge#1996]
Current workaround for defining custom getter/setter implementations on structs (add the name frb attribute):
```rs
use surrealdb::sql::{Thing, thing};

#[derive(Serialize, Deserialize, Debug, Clone)]
#[frb(opaque)]
pub struct ShardModel {
    id: Thing,
    pub sequence: u16,
    pub name: String,
    pub description: Option<String>,
    pub collections: Option<Vec<CollectionModel>>,
    pub notes: Option<Vec<NoteModel>>,
    pub tasks: Option<Vec<TaskModel>>,
}
impl ShardModel {
    #[frb(sync, getter)]
    pub fn id (&self) -> String {
        self.id.to_raw()
    }
    #[frb(sync, setter, name="id")]
    pub fn set_id (&mut self, id: &str) {
        self.id = thing(id).unwrap();
    }
}
```

Purposed syntax: strip `get_` if present on a fn with the `getter` attribute, or `set_` from a fn with the `setter` attribute. This is to avoid naming conflicts when defining both a setter and getter, while maintaining the same getting/setting variable within the generated dart class.

Example:
```rs
use surrealdb::sql::{Thing, thing};

#[derive(Serialize, Deserialize, Debug, Clone)]
#[frb(opaque)]
pub struct ShardModel {
    id: Thing,
    pub sequence: u16,
    pub name: String,
    pub description: Option<String>,
    pub collections: Option<Vec<CollectionModel>>,
    pub notes: Option<Vec<NoteModel>>,
    pub tasks: Option<Vec<TaskModel>>,
}
impl ShardModel {
    #[frb(sync, getter)]
    // `get_` is automatically detected and stripped, resulting in the getter `id`
    pub fn get_id (&self) -> String {
        self.id.to_raw()
    }
    #[frb(sync, setter)]
    // `set_` is automatically detected and stripped, resulting in the setter `id`
    pub fn set_id (&mut self, id: &str) {
        self.id = thing(id).unwrap();
    }
}
```

_Originally posted by @cabaucom376 in https://github.com/fzyzcjy/flutter_rust_bridge/issues/1975#issuecomment-2137949385_

**Comment by fzyzcjy** [comment]
Totally agree, feel free to PR, alternatively I will work on it in the next batch!

**Comment by aran** [comment]
$0.02 Controls for the way that FRB translates things could be encoded explicitly in `#[frb...]` annotations, without having additional codegen transformation rules that need to be learned/documented and may introduce additional edge cases.

**Comment by fzyzcjy** [comment]
@aran That is reasonable in some scenarios! In some other scenarios, we do need raw information to make decisions, thus the current approach is quite suitable.

**Comment by cabaucom376** [comment]
@aran Maybe I'm not understanding but isn't that already a thing with `#[frb(name='')]`? This proposal is to automate getter/setter impl fn's name stripping of `get_` for a getter and `set_` for a setter, as the most common use case for the getter/setter attributes would be to define a custom transformation and reuse the same name as the struct field to adhere with common dart class structure. With a Rust impl you cant define fn's with the same name, therefore the stripping is just a nice quality of life feature so you don't have to manually override the `name` attribute as its implied with the getter/setter attributes.

I agree this would probably result in some extra documentation, but I would argue its almost a natural decision to add `get_` or `set_` before a fn once you realize you cant use the same name for both getter/setter. This is exactly the path I had already taken before @fzyzcjy notified me of the existence of the `name` attribute.

**Comment by fzyzcjy** [comment]
Btw, I am working on https://github.com/fzyzcjy/flutter_rust_bridge/issues/1903, thus would like to work on this simple PR after that one is done - that one is quite big and causes a lot of change in internal code.

**Comment by fzyzcjy** [comment]
@cabaucom376 Totally agree!

I guess @aran may be discussing something else or more general, which may not apply here, but the general logic is reasonable in some other scenarios, though has some limitations as well (like everything in the world).

**Comment by cabaucom376** [comment]
I wish I could make a PR for this for my first open source contribution, but when I pulled the repository and started sifting through the code, being a Rust newbie, I got drastically lost 🤣. I'm very used to clicking around Dart code.

**Comment by fzyzcjy** [comment]
No worries, I can provide some hints!

The core logic happens here: https://github.com/fzyzcjy/flutter_rust_bridge/blob/96edf2432175bf3e2c270e3387036aafe98ee6b1/frb_codegen/src/library/codegen/parser/mir/function_parser/mod.rs#L65

But I would like to provide hints after the external library feature is done (I do hope within several days but cannot guarantee) if you are not urgent, because the detailed code here will possibly change a bit, thus if your PR is not super fast (i.e. begin and finish within a day) you will face merge conflicts.

**Comment by fzyzcjy** [comment]
Ok the codebase is roughly stable now. Here are some hints:

Here, https://github.com/fzyzcjy/flutter_rust_bridge/blob/8dbd4c242955066df30f53ee421e89556383461b/frb_codegen/src/library/codegen/parser/mir/parser/function/real/mod.rs#L172, we construct a `MirFunc`, i.e. information for a function.

The thing interesting to us is the `dart_name` and `accessor`. If we set dart_name to be the stripped name when accessor is getter/setter, then we are done!

**Comment by cabaucom376** [comment]
@fzyzcjy honestly I'm not sure my solution is working, I understand the goal and concept well with your helpful hints. Unfortunately I cant figure out the new code generation structure and have spent way too long on this side journey I have to get back to my main project. Thank you for the hints again and giving me a shot :)

**Comment by fzyzcjy** [comment]
It's OK! Then I will PR for this, no worries

**Comment by virtualritz** [comment]
On that note, a canonical Rust API will not have getters prefixed with `get_` to start with.

See [Getter names follow Rust convention (C-GETTER)](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter).

**Comment by fzyzcjy** [comment]
That looks reasonable! But anyway, with and without prefix are both supported.
