### ISSUE TITLE
Simplify of using #[frb(ignore)]

### ISSUE THREAD

**Issue by NightBlaze** [fzyzcjy/flutter_rust_bridge#1997]
**Is your feature request related to a problem? Please describe.**
I use Rust for stateful implementation so every app's screen has at least
```
api/screens/<screen>/<screen>_logic.rs
api/screens/<screen>/<screen>_state.rs
```
files.

Because I need to use `state.rs` in `logic.rs` I must to make state's structs and the structs' functions in impls public but at the same time I do not need to generate Dart code for the state's things. To achieve this I must to mark structs and all public functions for the structs with the `#[frb(ignore)]`.

**Describe the solution you'd like**
I would like to mark struct with `#[frb(ignore)]` or `#[frb(ignore_impl)]` only. If the struct has this annotation than frb should ignore all public functions in impls for the struct.

**Comment by fzyzcjy** [comment]
> Because I need to use state.rs in logic.rs I must to make state's structs and the structs' functions in impls public

What about making it `pub(crate)` or `pub(super)`, then it can be used by another file within crate, but at the same time, it is not really public (thus frb will skip it).

**Comment by NightBlaze** [comment]
Hmm... Why I didn't think about `pub(crate)`? Thanks!

**Comment by fzyzcjy** [comment]
You are welcome!
