### ISSUE TITLE
Flutter errors with `dlopen failed: library "librust_lib_proxy.so" not found)` because of Rust compilation error

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2005]
Coding on Win10, I'm experiencing an issue when running my Flutter app that uses the frb(v2.0 dev.37) on Android devices (both real devices and emulators). The app runs fine on Windows, but on Android, it either displays a blank black or white screen, or it crashes with the following error:
```
ArgumentError (Invalid argument(s): Failed to load dynamic library 
'librust_lib_proxy.so': dlopen failed: library "librust_lib_proxy.so" not found)
``` 

![ffi_err](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/a5d17c76-1a62-41be-816b-f656276468de)

The `proxy` is my app name. And this error occurs even with a minimal `main.dart` file that only initializes the Rust library without calling any Rust functions:
```dart
import 'package:flutter/material.dart';
import 'package:my_app/rust/frb_generated.dart';


Future<void> main() async {
  await RustLib.init();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('flutter_rust_bridge test my_app')),
        body: Center(
          child: Text('Action: Call Rust `greet("Tom")`\nResult: `'),
          // 'Action: Call Rust `greet("Tom")`\nResult: `${greet(name: "Tom")}`'),
        ),
      ),
    );
  }
}
```

Further investigation revealed that the issue might be related to the following three packages that FRB forces me to add to my project:
```
Error: MissingDep: Please add freezed_annotation to your dependencies. (version >=1.0.0)
Error: MissingDep: Please add freezed to your dev_dependencies. (version >=1.0.0)
Error: MissingDep: Please add build_runner to your dev_dependencies. (version >=1.0.0)
```

The error message prompting me to add these packages appeared after I copied some Rust code from another project into the `rust/src` folder for the newly inited FRB project, and ran the code generation process.

I'm unsure when these packages are required and how they are related to the issue I'm facing on Android. The issue may be caused by using macros like `serde` in my Rust structs, but I'm not certain.

I would appreciate any advice or suggestions on how to fix this problem and successfully run my Flutter app with FRB on Android devices and other platforms.

**Comment by fzyzcjy** [comment]
> I'm unsure when these packages are required

When using enums (except for primitive enums), these are needed, since Dart does not have good native complex enum support.

> how they are related to the issue I'm facing on Android

I suspect it may be related to failing to compile / failing to generate, etc, if it fixes after these packages are added.

So, do you have problem when creating a brand new project using `flutter_rust_bridge_codegen create`? If not, could you please provide a minimal self-contained example (e.g. a github repo), s.t. I can check it. Check build logs to look for errors may also help.

**Comment by dbsxdbsx** [comment]
The core reason for the issue is quite perplexing. It is caused by the `reqwest` crate in a Flutter Rust Bridge (FRB) project.

## Steps to Reproduce

1. Create a new FRB project:
   ```bash
   flutter_rust_bridge_codegen create app
   ```

2. Modify the `Cargo.toml` file as follows:
   ```toml
   [package]
   name = "rust_lib_app"
   version = "0.1.0"
   edition = "2021"

   [lib]
   crate-type = ["cdylib", "staticlib"]

   [dependencies]
   flutter_rust_bridge = "=2.0.0-dev.37"
   reqwest = "*"  # Add this line
   # reqwest = {version="0.11", features=["json", "blocking"]} # this is used with FRB v1
   ```

3. Run the app on an Android (emulator) device:
   ```bash
   flutter run
   ```

The output of the app would be a completely blank screen.

## Is the issue related to the FRB framework?

Based on the steps above, it appears that the issue is not directly related to the FRB framework but rather to a bug in the `reqwest` crate. However, since the `reqwest` crate worked with FRB v1 on Android earlier in 2023, there might be some indirect relation to the FRB framework.

I've never tried to use Rust in an Android app before using FRB, so I can't say for certain. It might be proper to test the `reqwest` crate without any other crate (including FRB) to fully diagnose the issue.

**Comment by fzyzcjy** [comment]
Hi, could you please show full `flutter run --verbose` log? I guess maybe the rust compilation somehow fails, etc (since it says `.so` not found).

**Comment by dbsxdbsx** [comment]
The full log after running `flutter run --verbose` and choose the emulated Android TV device:
[log.log](https://github.com/user-attachments/files/15524013/log.log)

**Comment by fzyzcjy** [comment]
Log says:

```
[ +392 ms] SEVERE: ================================================================================
[   +1 ms] SEVERE: Cargokit BuildTool failed with error:
[        ] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE: External Command: rustup "run" "stable" "cargo" "build" "--manifest-path"
"D:\DATA\BaiduSyncdisk\project\personal\test_repo\app\rust\Cargo.toml" "-p" "rust_lib_app" "--target" "i686-linux-android" "--target-dir"
"D:\DATA\BaiduSyncdisk\project\personal\test_repo\app\build\rust_lib_app/build"
[        ] SEVERE: Returned Exit Code: 101
[        ] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE: STDOUT:
[        ] SEVERE: --------------------------------------------------------------------------------
[        ] SEVERE: STDERR:
[        ] SEVERE: Compiling openssl-sys v0.9.102
[        ] SEVERE:    Compiling backtrace v0.3.72
[        ] SEVERE:    Compiling env_logger v0.10.2
[        ] SEVERE:    Compiling futures-util v0.3.30
[        ] SEVERE:    Compiling pin-project v1.1.5
[        ] SEVERE:    Compiling h2 v0.4.5
[        ] SEVERE: error: failed to run custom build command for `openssl-sys v0.9.102`
[        ] SEVERE:
[        ] SEVERE: Caused by:
[        ] SEVERE:   process didn't exit successfully:
`D:\DATA\BaiduSyncdisk\project\personal\test_repo\app\build\rust_lib_app/build\debug\build\openssl-sys-61cad2940aa4466e\build-script-main`
(exit code: 101)
[        ] SEVERE:   --- stdout
```

So seems Rust fails to copmile.

**Comment by fzyzcjy** [comment]
> One thing need to mention is that I don't think rust compilation failed(but missed something I guess), otherwise the app can't be launched.

Maybe we can create an issue at Cargokit repo about this - I personally also think it is reasonable to ensure the whole `flutter run` directly fails if Rust compilation fails.

**Comment by fzyzcjy** [comment]
As for that specific SSL error, IIRC someone discussed about it before in issue tracker, so if google does not reveal answers maybe search here as well

**Comment by dbsxdbsx** [comment]
> As for that specific SSL error, IIRC someone discussed about it before in issue tracker, so if google does not reveal answers maybe search here as well

Yes ,exactly, I remember I mentioned the SSL error [here ](https://github.com/fzyzcjy/flutter_rust_bridge/issues/1171)early in 2023, when the newly FRB V1 can't be build with android.   Yes, never succeeded then until now with Android.  

I would try to search again....

**Comment by dbsxdbsx** [comment]
Finally,  I found a  workaround, which no need to care of OPENSSL--- use the rustls TLS backend instead of OpenSSL.
```toml
[dependencies]
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
```

By the way,  I think when any crate is compilied failed, frb should panic when running `flutter run` as before in v1.

**Comment by fzyzcjy** [comment]
> By the way, I think when any crate is compiled failed, FRB should panic when running flutter run as before in v1.

That seems what I mentioned above:

> Maybe we can create an issue at Cargokit repo about this - I personally also think it is reasonable to ensure the whole flutter run directly fails if Rust compilation fails.

https://github.com/irondash/cargokit/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by dbsxdbsx** [comment]
> > By the way, I think when any crate is compiled failed, FRB should panic when running flutter run as before in v1.
> 
> That seems what I mentioned above:
> 
> > Maybe we can create an issue at Cargokit repo about this - I personally also think it is reasonable to ensure the whole flutter run directly fails if Rust compilation fails.
> 
> https://github.com/irondash/cargokit/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Is it an issue with rust/cargo, not flutter/dart?  I am not sure about it when it is related with FFI.

**Comment by fzyzcjy** [comment]
I guess it is related to cargokit, which is a tool (roughly speaking) to trigger Rust compilation when running `flutter run`.
