### ISSUE TITLE
After mapping usize to BigInt, the generated Dart code with #[frb(default = 10)] throw casting error.

### ISSUE THREAD

**Issue by garyhai** [fzyzcjy/flutter_rust_bridge#2035]
### Describe the bug

Error report:
A value of type 'int' can't be assigned to a variable of type 'BigInt'.
Try changing the type of the variable, or casting the right-hand type to 'BigInt'.dart[invalid_assignment](https://dart.dev/diagnostics/invalid_assignment)

### Steps to reproduce

```rust

#[frb(mirror(VadConfig))]
pub struct _VadConfig {
  #[frb(default = 1536)]
  pub chunk_size: usize,
  #[frb(default = 0.6)]
  pub threshold: f32,
  #[frb(default = 0.15)]
  pub hysteresis: f32,
  #[frb(default = 16000)]
  pub sample_rate: usize,
  #[frb(default = 200)]
  pub min_speech_ms: usize,
  #[frb(default = 10)]
  pub max_speech_s: usize,
  #[frb(default = 200)]
  pub min_silence_ms: usize,
  #[frb(default = 98)]
  pub min_silence_ms_at_max_speech: usize,
  #[frb(default = 400)]
  pub speech_pad_ms: usize,
  #[frb(default = false)]
  pub return_ms: bool,
}
```

Generated dart code:
```dart
class VadConfig {
  final BigInt chunkSize;
  final double threshold;
  final double hysteresis;
  final BigInt sampleRate;
  final BigInt minSpeechMs;
  final BigInt maxSpeechS;
  final BigInt minSilenceMs;
  final BigInt minSilenceMsAtMaxSpeech;
  final BigInt speechPadMs;
  final bool returnMs;

  const VadConfig({
    this.chunkSize = 1536,
    this.threshold = 0.6,
    this.hysteresis = 0.15,
    this.sampleRate = 16000,
    this.minSpeechMs = 200,
    this.maxSpeechS = 10,
    this.minSilenceMs = 200,
    this.minSilenceMsAtMaxSpeech = 98,
    this.speechPadMs = 400,
    this.returnMs = false,
  });
```

### Logs

```shell
Compiling error without log.
```

**Comment by garyhai** [comment]
There is no constructor for BigInt(value). 
`  #[frb(default = "const BigInt(1)")]` raise the error:
The default value of an optional parameter must be constant.dart[non_constant_default_value](https://dart.dev/diagnostics/non_constant_default_value)
The class 'BigInt' doesn't have an unnamed constant constructor.

So I have no solution for const default value for BigInt.

**Comment by fzyzcjy** [comment]
Hmm, looks like a problem: https://github.com/dart-lang/sdk/issues/33893#issuecomment-2149402659

**Comment by garyhai** [comment]
How about adding an argument in the frb macro for number type map? It's better to give the choice to the developer.

**Comment by fzyzcjy** [comment]
That looks reasonable! Feel free to PR for it (maybe discuss about detailed design before implementing), alternatively I may work on it in the next batch after #1903

**Comment by garyhai** [comment]
Thank you very much. Unfortunately, I don’t have experience with Rust macro programming, and since frb is a very critical macro, it would be better for you to implement it.

**Comment by fzyzcjy** [comment]
It's OK, no worries! 

Btw it is indeed not a macro, but a command line program that parses code and generates code; but yes, the logic is similar to a usual macro.
