### ISSUE TITLE
How to catch error when use StreamSink? 

### ISSUE THREAD

**Issue by lunxinfeng** [fzyzcjy/flutter_rust_bridge#2036]
Thanks for this lib, but I hava a problem.  I have a method like this:

```rust
pub fn sftp_upload_file(attr: String, remote_path: String, local_path: String, sink: StreamSink<(u64, u64)>) -> Result<(), SessionError> {
  .....
}
```
gen dart:
```dart
  Stream<(BigInt, BigInt)> crateApiSftpUploadFile(
      {required String attr,
      required String remotePath,
      required String localPath});
```

but when return Err from rust, I cannot catch this error by dart, this is my code, how can I do?

```dart
    try {
      final stream = rust.crateApiSshSftpUploadFile(attr: attr, remotePath: remotePath, localPath: localPath);
      await for (var item in stream) {
        ...
      }
    } catch (e) {
      // not fire when an error occurs
    }
```

**Comment by lunxinfeng** [comment]
> Good question!
> 
> The first way (workaround) may be change the return type. For example,
> 
> ```rust
> pub enum MyType {
>   Data(u64, u64),
>   Error(String),
> }
> 
> pub fn sftp_upload_file(..., sink: StreamSink<MyType>)
> ```
> 
> Another way may be, enhance `StreamSink` by adding an `add_error` method (just mimic the `add` method today), and it will call Dart's Stream add error and throw exceptions accordingly. Feel free to PR for this - I think it will be a fairly short PR (if you need hints about implementation just ping me)! Alternatively, I may try to squeeze some time working on this.

Thanks reply, but I am a rust novice, sorry, I can only try the first solution, thank you

**Comment by fzyzcjy** [comment]
You are welcome!
