### ISSUE TITLE
Feature Request: Allow extern paths (& custom serializers) to play nicely with other code generators

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#2038]
**Is your feature request related to a problem? Please describe.**

Consider the case of a project like mine that has some protobuf files, call one message AwesomeMessage. In Rust there is `prost_build` generating a crate, call it "awesome_proto_crate". I may also have some Rust code that uses the `prost_build`-generated types, call it "awesome_rust_code". In Dart there is `protoc_builder` generating some Dart files for the same .proto files, call it "package:awesome_proto". What happens is that when FRB translates "awesome_rust_code", it will end up making a Dart file like "package:awesome/src/rust/api/api.dart", which will have an `AwesomeMessage` type, and the FRB-generated `AwesomeMessage` will not be compatible with the `package:awesome_proto` version of `AwesomeMessage`. 

**Describe the solution you'd like**
To solve this, something like 

```rust
#[frb(external, ExistingType(package='awesome_proto'))]`
impl AwesomeMessage {}
``` 
 would be able to declare to FRB that instances of `awesome_proto_crate::AwesomeMessage` should become imports & references to `package:awesome_proto`'s copy of `AwesomeMessage`. Now there would only be one `AwesomeMessage` in the Dart project, but there's a question: How does FRB serialize/deserialize `AwesomeMessage`? To answer this, FRB must maintain a per-type list of (rust serializer, dart deserializer) pairs to send data to Dart and (rust deserializer, dart serializer) pairs to send data to Rust.

**Describe alternatives you've considered**
Another alternative is to build a bunch of boilerplate to effective implement .into() on the Dart side to translate the FRB-copy of some data into the other Dart version. This could be built into FRB as well, for example, 

#[frb(external, ExistingType(package='awesome_proto', converter='frb_awesome_message_into_other_awesome_message')] and then FRB could keep its serialization and just help the programmer by tacking on an extra conversion step after deserialization.

**Additional context**

Obviously protobuf serialization isn't always as good as the native serialization from a performance perspective but in many cases it will be adequate when the project must use certain existing Dart classes. (Also, if one side has serialized data cached already, it could be fast...) Note also that this idea is driven by protobufs but it could apply to anything where there is an existing Dart type that is hard to modify for some reason.

**Comment by fzyzcjy** [comment]
Looks reasonable! A quick brainstorm of API, maybe we can do something like:

```rust
#[frb(some_marker_name_to_be_determined(dart = AwesomeMessage, package = awesome_proto))]
fn encode_awesome_message(obj: AwesomeMessage) -> Vec<u8> {
  obj.serialize_protobuf_into_bytes()
}
```

and we auto extract the Rust type (AwesomeMessage), the intermediate type (`Vec<u8>`, and corresponding `Uint8List`), and the Dart type (from annotation)

(just a draft, feel free to propose anything else!)

**Comment by aran** [comment]
That looks nice and clean to me. One wrinkle is the encode fn probably needs to support a `Result`.

e.g. in this code:

            let mut buf = vec![];
            let r = prost::Message::encode(&l2, &mut buf);
            
`r` is a `Result<(), prost::EncodeError>`. 

Another type I looked at just returns a straight `Vec<u8>`, so that would work there as well.

**Comment by fzyzcjy** [comment]
Oh yes, totally reasonable, we can do something like 

```rust
#[frb(some_marker_name_to_be_determined(dart = AwesomeMessage, package = awesome_proto, decode = "AwesomeMessage.from_bytes(raw)"))]
fn encode_awesome_message(obj: AwesomeMessage) -> anyhow::Result<Vec<u8>> {
  obj.serialize_protobuf_into_bytes()
}
```

(for simplicity maybe support anyhow Result first)

**Comment by aran** [comment]
Makes total sense considering `anyhow` is used so widely within FRB already.

**Comment by fzyzcjy** [comment]
(... and widely used within whole Rust ecosystem I guess ;) )

**Comment by aran** [comment]
Got a chance to look at the docs and start implementing it. Impressive change. 

Can you share if/how this works when the custom serialized type is a member of a translated or opaque type?

e.g.

```rust
#[frb(mirror(Thing))]
pub struct _Thing {
    pub inner: Option<Vec<HasCustomSerDer>>,
}
```

Whether the custom-serialized type is `pub use` or `use`, and whether the containing type is translated or opaque, I am seeing compile errors on `build web` around the trait `IntoIntoDart<_>` due to `transform_result_dco`, the trait bound `wasm_bindgen::JsValue: frb_generated::CstDecode<_>`. I think this might mean that those other serializers/deserializers don't know they should switch to the custom serializer/deserializer when they encounter this type, but I'm not sure.

**Comment by aran** [comment]
Apparently I still don't understand `full_dep`, I think you told me to use it for a different bug, but without it, I can compile and use this feature which is super helpful. Thanks!

**Comment by fzyzcjy** [comment]
You are welcome! Roughly speaking full_dep controls default codec to use etc. You can also manually specify codec function by function as well but that will be tedious.
