### ISSUE TITLE
Migrate to dart:js_interop

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#2039]
**Is your feature request related to a problem? Please describe.**
`dart:js` and `package:js` are deprecated by Flutter. https://docs.flutter.dev/platform-integration/web/wasm

**Describe the solution you'd like**
Migrate to `dart:js_interop` where `js` is currently used.

https://github.com/search?q=repo%3Afzyzcjy%2Fflutter_rust_bridge%20package%3Ajs&type=code

**Comment by fzyzcjy** [comment]
Totally agree! Will do that after https://github.com/fzyzcjy/flutter_rust_bridge/issues/1903
