### ISSUE TITLE
What is the folder `logs` used after creating a new FRB project?

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2040]
After the cmd `flutter_rust_bridge_codegen create my_app`, there would be folder `logs` created aside of the project folder. I wonder when it is needed since there is also another `log` folder inside the project folder.

And is there a way to avoid creating the outer `logs` in the creating command?

**Comment by fzyzcjy** [comment]
Totally agree - IMHO that logs folder should not exist, and feel free to tweak logs configuration to avoid that!

IIRC long time ago someone made a PR to log to files (maybe you? or another one), and at that time there was no `create` command, so I guess that is the historical reason.

**Comment by dbsxdbsx** [comment]
I did add log pr(I can't find it) by adding a crate `fern`, which is for the developer of this project, but not for FRB user.
