### ISSUE TITLE
Visibility of modules

### ISSUE THREAD

**Issue by raphaelrobert** [fzyzcjy/flutter_rust_bridge#2048]
### Describe the bug

Not sure if this is a bug or if it is by design, but I can't seem to expose Rust modules to Dart.

Consider the following code in `src/api/mod.rs`:
```rust
pub use my_mod::{my_stream, MyStruct};

pub mod my_mod {
    pub struct MyStruct {}

    pub fn my_stream(x: StreamSink<MyStruct>) {
        let _ = x;
    }
}
```

Neither `MyStruct` nor `my_stream` are exposed to Dart. So my question is: is this by design? Or am I just doing it wrong?

### Steps to reproduce

Hint: A simple way to reproduce is to clone and modify the https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal example package according to your needs.
1. Copy & paste the code above in `src/api/mod.rs`
2. Run `flutter_rust_bridge_codegen generate`
3. Inspect `frb_generated.rs` and realize what's missing.

### Logs

```shell
N/A
```

**Comment by fzyzcjy** [comment]
Just wait for next release (2.0.0.dev-38 I guess) - this week I have done many refactors to add new features, one of them is about correctly work with things like nested modules. If it is still there, feel free to ping me!

**Comment by raphaelrobert** [comment]
Thanks for your hard work!

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by fzyzcjy** [comment]
New version has released - if still buggy feel free to tell me!
