### ISSUE TITLE
Trouble with loading dynamic library on macOS Monterey

### ISSUE THREAD

**Issue by AlienKevin** [fzyzcjy/flutter_rust_bridge#206]
# Set Up
OS: macOS Monterey 12.0.1 on M1

Starting from a blank flutter desktop app generated for macOS, I added my `wordshk_tools` crate to a `rust/` folder. Then, I generated bindings for `api.rs` following the steps in the tutorial. Because flutter_rust_bridge_codegen doesn't support arm64 yet, I installed an x86_64 version of llvm and run the codegen command with a custom llvm path:
```
flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output lib/make_dict.dart --llvm-path /usr/local/homebrew/opt/llvm/
```
Codegen generated the bindings successfully with some warnings about missing a nullability type specifier:
```
...
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:361:13: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [Nullability Issue]
Finished, Bindings generated in /var/folders/qb/j41twqwd0nxdb3zy_y1wk4900000gn/T/.tmpUPLAtR\n", stderr: "" }
```
 Then, in my `main.dart` code, I loaded the api and tried to call it on a button press:
```dart
const base = 'wordshk_tools';
final path = 'lib$base.dylib';
late final dylib = DynamicLibrary.open(path);
late final api = WordshkTools(dylib);
...
onPressed: () await {
await api.makeDict();
}
```

# Problem
**I tested the code with `flutter run` and it runs fine until I hit the button. Flutter printed out an error message that seems to indicate that `DynamicLibrary.open` failed to find the dylib file:**
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception:
Invalid argument(s): Failed to load dynamic library 

'libwordshk_tools.dylib': dlopen(libwordshk_tools.dylib, 0x0001): tried: '/Users/kevin/development/dictionary/wordshk/wordshk_macos/build/macos/Build/Products/Debug/wordshk_macos.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/./libwordshk_tools.dylib' (no such file), '/Users/kevin/development/dictionary/wordshk/wordshk_macos/build/macos/Build/Products/Debug/wordshk_macos.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/../../../libwordshk_tools.dylib' (no such file), '/usr/lib/swift/libwordshk_tools.dylib' (no such file), '/Users/kevin/development/dictionary/wordshk/wordshk_macos/build/macos/Build/Products/Debug/wordshk_macos.app/Contents/MacOS/../Frameworks/libwordshk_tools.dylib' (no such file), 'libwordshk_tools.dylib' (no such file), '/usr/local/lib/libwordshk_tools.dylib' (no such file), '/usr/lib/libwordshk_tools.dylib' (no such file), '/Users/kevin/Library/Containers/com.example.wordshkMacos/Data/libwordshk_tools.dylib' (no such file), '/usr/local/lib/libwordshk_tools.dylib' (no such file), '/usr/lib/libwordshk_tools.dylib' (no such file)
```

**All of my source code can be found in [this GitHub repo](https://github.com/AlienKevin/wordshk_macos/tree/master/). I have done some research and found that there's a [change in the handling of dylib](https://developer.apple.com/forums/thread/655588) since macOS Big Sur. However, it shouldn't affect codes calling `dlopen` so DynamicLibrary.open() shouldn't be affected.**

**Comment by fzyzcjy** [comment]
let me have a look

**Comment by fzyzcjy** [comment]
It should be a problem with Flutter MacOS + Rust setup, instead of the bug of this bridge, since this bridge only generates code that mimics a human being (and humans can look at it as well). You may need to find a tutorial or file a bug about "flutter macos + rust", or more generally, "flutter macos + dylib".

**Comment by Desdaemon** [comment]
I can't test this, but the [Flutter docs](https://docs.flutter.dev/development/platform-integration/c-interop#compiled-dynamic-library-macos) has some instructions on exposing a dylib to Flutter on MacOS.

Linux and Windows both uses CMake so I was able to add support for it, but it seems to differ greatly when it comes to building for MacOS.

**Comment by AlienKevin** [comment]
According to [this Medium article](https://medium.com/flutter-community/flutterdesktop-and-c-7cd2e0106bd8) which uses CMake, it seems that you need to generate a dylib file and manually integrate it into Runner/Frameworks in yourapp/macos/Runner.xcworkspace through XCode. The problem is that I can't find the dylib file so I can't drag it into XCode.

**Comment by Desdaemon** [comment]
> According to [this Medium article](https://medium.com/flutter-community/flutterdesktop-and-c-7cd2e0106bd8) which uses CMake, it seems that you need to generate a dylib file and manually integrate it into Runner/Frameworks in yourapp/macos/Runner.xcworkspace through XCode. The problem is that I can't find the dylib file so I can't drag it into XCode.

The dylib is Rust output when you compile your code, it will be in `target/{debug|release}/*.dylib` and you need to add 2 lines to your Crate.toml:

```
[lib]
crate-type = ["cdylib"]
```

**Comment by AlienKevin** [comment]
> > According to [this Medium article](https://medium.com/flutter-community/flutterdesktop-and-c-7cd2e0106bd8) which uses CMake, it seems that you need to generate a dylib file and manually integrate it into Runner/Frameworks in yourapp/macos/Runner.xcworkspace through XCode. The problem is that I can't find the dylib file so I can't drag it into XCode.
> 
> The dylib is Rust output when you compile your code, it will be in `target/{debug|release}/*.dylib` and you need to add 2 lines to your Crate.toml:
> 
> ```toml
> [lib]
> crate-type = ["cdylib"]
> ```

Thanks! I finally see the dylib file. I'm gonna follow the flutter doc and see if it works this time.

**Comment by AlienKevin** [comment]
The app now compiles and runs! So the dylib issue should be resolved😄  However, I have trouble reading external files in api.rs as flutter complained that "No such file or directory (os error 2), null)", when I tried to do io operations like:
```rust
let mut rdr = csv::Reader::from_path("./rust/wordshk_apple/wordshk.csv")?;
```
and
```rust
let front_back_matter_filename = "./rust/wordshk_apple/front_back_matter.html";
    let front_back_matter = fs::read_to_string(front_back_matter_filename).expect(&format!(
...
```
My project structure looks like this (I boxed the two resources I want to access)

![截圖 2021-11-23 上午10 30 35](https://user-images.githubusercontent.com/22850071/143054190-85e5aa71-fccb-4a97-af91-e44e7a75b15b.png)

**Comment by AlienKevin** [comment]
Anyways, I found a solution by moving the io to dart and passing in the files as strings. It's sort of slow I think but I can't think of better ways. There doesn't seem to be a way of passing streams through the bridge.
And about using flutter_rust_bridge on M1 macs in general, I think I can add some docs to help guide people because there are just too many caveats with rosetta, ffi, and dylib that I don't want more people to spend time digging around.

**Comment by fzyzcjy** [comment]
Congratulations!

> And about using flutter_rust_bridge on M1 macs in general, I think I can add some docs to help guide people because there are just too many caveats with rosetta, ffi, and dylib that I don't want more people to spend time digging around.

Thanks and welcome for the PR!

>  have trouble reading external files in api.rs as flutter complained that "No such file or directory (os error 2), null)"

I guess it is because relative paths? could you please try *absolute* paths, such as `/Users/myusername/a.txt` and so on? If that works, you can easily get absolute paths (or path prefixs) in Flutter and pass it to Rust, which is quick.
