### ISSUE TITLE
Missing extern method for external crate struct in dev.38

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#2068]
### Describe the bug

I have an external type and a method on it I expose:

```rust
pub use automerge::ScalarValue;

//...

#[frb(external)]
impl ScalarValue {
    #[frb(sync)]
    pub fn is_str(&self) -> bool {}
}
```

In dev.37 I used this function as normal. In dev.38, with no other changes, it is removed, with 

```+// These functions are ignored: `is_str` ``` visible in the generated output. I don't see any other warnings or errors to understand why this function is removed, even in `-v` mode.

In dev.38, I need to add a mirror type for it to get it to generate the `isStr` method. 

### Steps to reproduce

1. 

```
pub use automerge::ScalarValue;

//...

#[frb(external)]
impl ScalarValue {
    #[frb(sync)]
    pub fn is_str(&self) -> bool {}
}`
```

2. Upgrade to dev.38 

### Logs

```shell
N/A
```

**Comment by fzyzcjy** [comment]
Looks like a bug. I will check it now.

**Comment by fzyzcjy** [comment]
Btw, possibly related: https://cjycode.com/flutter_rust_bridge/guides/third-party Now we can automatically scan a *whole* third party crate :)

**Comment by aran** [comment]
> Btw, possibly related: https://cjycode.com/flutter_rust_bridge/guides/third-party Now we can automatically scan a _whole_ third party crate and no need to repeat signatures manually :)

That's insane, I am looking forward to trying it out.

**Comment by fzyzcjy** [comment]
Looking forward to your tries!
