### ISSUE TITLE
Generated code reference to private module and makes errors

### ISSUE THREAD

**Issue by svr2kos2** [fzyzcjy/flutter_rust_bridge#2074]
With a new flutter_rust_bridge_codegen project
add `api/internal_mod.rs`
``` rust
pub fn internal_hello() {
    println!("Hello from internal_mod.rs!");
}
```
add `api/external_mod.rs`
``` rust
#[path ="internal_mod.rs"] mod internal_hello;
pub fn external_hello() {
    println!("Hello from external_mod.rs!");
    internal_hello::internal_hello();
}
```
modify `api/mod.rs`
``` rust
pub mod simple;
pub mod external_mod;
```
`flutter_rust_bridge_codegen generate` and `build(web or windows)` then get

```
error[E0603]: module `internal_hello` is private
   --> src\frb_generated.rs:103:51
    |
103 |                         crate::api::external_mod::internal_hello::internal_hello();        
    |                                                   ^^^^^^^^^^^^^^  -------------- function `internal_hello` is not publicly re-exported
    |                                                   |
    |                                                   private module
```
As a beginner, I'm not sure if this is the wrong way to use internal code or a bug.  
But I found that I can use this way to avoid this by changing `internal_mod.rs` to:
``` rust
pub(in crate::api) fn internal_hello() {
    println!("Hello from internal_mod.rs!");
}
```

_Originally posted by @svr2kos2 in https://github.com/fzyzcjy/flutter_rust_bridge/discussions/2073#discussioncomment-9757353_

**Comment by fzyzcjy** [comment]
Yes, one simple way is to write down `pub(crate) fn internal_hello()` (or `pub(in crate::api)` or something like that).

I may modify the codegen such that it ignores `mod ...;`, but it may complicate things, since Rust has really complicated `pub` system...
