### ISSUE TITLE
A simple and a complex issue related to rust type defined in non-API module

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2075]
## Env
win10+ FRB dev.38
## Issues
1. the simple one: the FRB generation failed with  the below msg:
```
[2024-06-13T01:56:54.416Z WARN C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\flutter_rust_bridge_codegen-2.0.0-dev.38\src\library\commands\command_runner.rs:153] command="cargo" "expand" "--lib" "--theme=none" "--ugly" "-p" " crate" stdout= stderr=error: invalid character ` ` in package name: ` crate`, the first character must be a Unicode XID start character (most letters or `_`)
```
, where is the issue? (Plz take 5 secs to infer) The message is hard to infer right?   The answer is due to the config file :
```yaml
rust_input: crate::api, crate::media
dart_output: lib/src/rust
``` 
. There is a ` ` before `crate::media` lead to fail.

2.  the complex one:
this one is hard to explain since there are many issues both in Rust and Dart side, so I uploaded the repo [here](https://github.com/dbsxdbsx/xiao_dong_tv/):
The Rust screenshot:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/203387af-f416-4c18-bcac-46de50492d0a)
The Dart screenshot:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/e11d4470-c74a-4ffe-a784-d1443c108677)

I know the 2ed issue is complex(it is not even a single issue) and heavy to put them as a whole case, which would take more time to analyze. But I do think that putting it as a whole here is proper and efficient to expose potential issues with current FRB v2(Somehow, it is mainly related to the Rust struct `pub struct MediaDoc` [here](https://github.com/dbsxdbsx/xiao_dong_tv/blob/main/rust/src/media/media_doc.rs)).

**Comment by fzyzcjy** [comment]
For the first issue - feel free to PR to fix this! I guess it would be as simple as "check whether there is space inside it, if so just throw error".

For the second, I guess it is because of https://github.com/dbsxdbsx/xiao_dong_tv/blob/642d4bf974d0d0f0a2171e2f00f1bb54aa3f5894/rust/src/media/mod.rs#L428

```rust
pub async fn fetch_cms_media_detail(
    url: &str,
    media_ids: Option<&[i64]>,
) -> Result<CmsMediaDetailJson> {
```

That type seems not to be supported. What about `Option<Vec<i64>>` instead?

**Comment by dbsxdbsx** [comment]
For the issue with `fetch_cms_media_detail`, actually, it is a side effect since it is not need to be generated, which I can
work around it by tagging it with `#[frb(ignore)]`.
But there is still some other issues like this: 
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/f64f13e0-2641-4adf-be2b-24fcca019d95)
which is unavoidable

**Comment by dbsxdbsx** [comment]
> For the first issue - feel free to PR to fix this! I guess it would be as simple as "check whether there is space inside it, if so just throw error".

I would still prefer to let frb to parse automatically to figure out which type is needed and which is not needed, otherwise there would a great bulk of needless fn be generated(currently, it would be work around by ``#[frb(ignore)]` but tedious to do).

I don't mean eliminate the module mechanism in `rust_input:` of config file, which I know is useful for external crate module.  
I just suggest to let FRB could automatically solve the exposable methods/fileds of types recursively within the internal crate context(the local Rust code except for external crate).

**Comment by fzyzcjy** [comment]
> which I can
work around it by tagging it with #[frb(ignore)].

Or use `pub(crate)` instead of `pub`

> But there is still some other issues like this: ... File

What about marking the struct (for example) that has a field with type File to be opaque? Then, frb will not translate the File.

> I would still prefer to let frb to parse automatically to figure out which type is needed and which is not needed, otherwise there would a great bulk of needless fn/type be generated

Frb simply scans all `pub` functions, and all types that are directly or indirectly used by those functions are picked. If you do not need some function, just make it non-pub (e.g. `pub(crate)`)

**Comment by dbsxdbsx** [comment]
> What about marking the struct (for example) that has a field with type File to be opaque? Then, frb will not translate the File.

For the `File` import issue(somehow related to auto opaque), 
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/afeca6a4-a068-40f0-86d2-ac813da563a3)
which is at this [line](https://github.com/dbsxdbsx/xiao_dong_tv/blob/3deda0fbfa4279ca83123c6c3e8b4ccf7153aeb0/rust/src/frb_generated.io.rs#L21C1-L22C1),  the core problem is that **I don't even know what my code it refers to**(Since `File` is quite common used, without more detailed info, I can't find the right place to debug), when I see the signature `frbgen_xiao_dong_tv_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFile`.

**Another Core Issue**
for a mutable and exposable(to Dart) method `set_content`  of struct `MediaDoc` at [this line](https://github.com/dbsxdbsx/xiao_dong_tv/blob/3deda0fbfa4279ca83123c6c3e8b4ccf7153aeb0/rust/src/media/media_doc.rs#L300), it has to be set with `#[frb(opaque)]`, now it has issue:
```
the name `wire__crate__media__media_doc__MediaDoc_set_content_impl` is defined multiple times
`wire__crate__media__media_doc__MediaDoc_set_content_impl` must be defined only once in the value namespace of this modulerustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B6%5D?6#file%3A%2F%2F%2Fd%253A%2FDATA%2FBaiduSyncdisk%2Fproject%2Fpersonal%2FTV_APP_PROJECT%2Fxiao_dong_tv%2Frust%2Fsrc%2Ffrb_generated.rs)
frb_generated.rs(1406, 1): previous definition of the value `wire__crate__media__media_doc__MediaDoc_set_content_impl` here
rust_lib_xiao_dong_tv::frb_generated
fn wire__crate__media__media_doc__MediaDoc_set_content_impl(ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr, rust_vec_len_: i32, data_len_: i32) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse
Go to [WireSyncRust2DartSse](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
```
within [this line](https://github.com/dbsxdbsx/xiao_dong_tv/blob/3deda0fbfa4279ca83123c6c3e8b4ccf7153aeb0/rust/src/frb_generated.rs#L1457) of file `frb_generated.rs`.

I have no idea why it is multiply defined.

**Comment by fzyzcjy** [comment]
> I don't even know what my code it refers to

Hmm I see.

* Workaround: `dump: all` in flutter_rust_bridge.yaml, and look at `rust/target/frb_dump/mir/2_filter_trait_impl_transformer.json`. Maybe a global search about `File`.
* Later, I may need to somehow introduce a nicer dump format to debug things like this.

**Comment by fzyzcjy** [comment]
> the name `wire__crate__media__media_doc__MediaDoc_set_content_impl` is defined multiple times

I suspect it is because of the newly introduced "auto opaque accessors" feature https://cjycode.com/flutter_rust_bridge/guides/types/arbitrary/rust-auto-opaque/properties.

For your scenario, maybe ensure the `MediaDoc.content` field is *not* public, then it will not be generated.

**Comment by fzyzcjy** [comment]
Oops, I mean: `dump_all: true`. full dep is another unrelated thing.

**Comment by dbsxdbsx** [comment]
> Oops, I mean: dump_all: true. full dep is another unrelated thing.

Thanks, now I see it.   Issues stated in this post are almost solved, except for the simple issue, which seems to be trivial to fix. I would try to fix it once I am free.

**Comment by fzyzcjy** [comment]
You are welcome and happy to see it works!
