### ISSUE TITLE
Missing types in generated code

### ISSUE THREAD

**Issue by virtualritz** [fzyzcjy/flutter_rust_bridge#2078]
### Describe the bug

I get a bunch of errors related to `PathBuf` not being found in the generated code.

I.e.:
```
❯ cargo build
   Compiling rust_lib_fl_test v0.1.0 (/home/moritz/code/crates/metadata_preview/rust)
error[E0412]: cannot find type `PathBuf` in this scope
   --> src/frb_generated.rs:105:61
    |
105 |     flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PathBuf>
    |                                                             ^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
24  + use std::path::PathBuf;
```

### Steps to reproduce

Clone https://github.com/virtualritz/metadata-test and do a `cargo build` inside the `rust` folder.

### OS

Ubuntu 23.04

### Version of `flutter_rust_bridge_codegen`

 `2.0.0-dev.38`

### Flutter info

```
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (8 days ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

### Version of `clang++`

```
Ubuntu clang version 16.0.6 (15)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/13
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

### Additional context

This can be fixed by manually adding `use std::path::PathBuf` to `rust/src/frb_generated.rs`.
What is weird is that the latter imports everything from `metadata.rs` which does include `PathBuf`.

On a sidenote, I changed `Path` in my public API to `PathBuf` because I got a bunch of errors about `Path` not being `Sized`.

It seems Flutter-facing Rust methods can not take types as parameters that are not `Sized`?

**Comment by fzyzcjy** [comment]
Hi, maybe try to add `pub use std::path::PathBuf` in your function that uses PathBuf, then frb imho will pick it up.

**Comment by virtualritz** [comment]
> Hi, maybe try to add pub use std::path::PathBuf in your function that uses PathBuf, then frb imho will pick it up.

@fzyzcjy, thanks, this fixed it but this is really non-idiomatic. I also wonder how that will help with arbitray crates you add in `flutter_rust_bridge.yaml` to make them accessible?

Third party types used in `pub` APIs of any crate become `pub` themselves automatically, or else a user of that crate could never call the resp. method as they couldn't instantiate the required type(s).

I.e. if I take any Rust crate that uses e.g. `PathBuf` in its public API and add this to the `rust_input`s in `flutter_rust_bridge.yaml`, won't I run into exactly this issue?

IMHO this is a bug in `frb` and should be fixed.

> >It seems Flutter-facing Rust methods can not take types as parameters that are not Sized?
>
> IIRC yes currently.

It seems the same is true for return types? This is probably noteworthy in the docs since you claim "zero copy". :grin:

If I have:

```rust
#[derive(Clone)]
pub struct VeryComplexFoo {
    ...
}

struct Foo {
    very_complex_foo: Option<VeryComplexFoo>
}

imp Foo {
    pub fn very_complex_foo(&self) -> Option<&VeryComplexFoo> {
         self.very_complex_foo.as_ref()
    }
}
```

That will presumably not work because we are returning a `!Sized` reference to `VeryComplexFoo` whose lifetime is tied to the owning `Foo` `(&self)`?

What I will have to do instead is:
```rust
#[derive(Clone)]
pub struct VeryComplexFoo {
    ...
}

... 

imp Foo {
    pub fn very_complex_foo(&self) -> Option<VeryComplexFoo> {
         self.very_complex_foo.clone()
    }
}
```

I tried something like this in my crate and I got:

```rust
error[E0277]: the trait bound `Option<&metadata::SpecificMetadata>: SseEncode` is not satisfied
   --> src/frb_generated.rs:126:42
    |
126 |                       transform_result_sse((move ||  {
    |  _____________________--------------------_^
    | |                     |
    | |                     required by a bound introduced by this call
127 | |                         let mut api_that_decoded = None;
128 | | let decode_indices_ = flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![flutter_rust_bridge::for_generated::LockableOrderInfo::new(&api_that, 0, false)]);
129 | |         for i in decode_indices_ {
...   |
136 | |  Result::<_,()>::Ok(crate::api::metadata::Metadata::specific(api_that))
137 | |                     })())
    | |________________________^ the trait `SseEncode` is not implemented for `Option<&metadata::SpecificMetadata>`
    |
    = help: the trait `SseEncode` is implemented for `Option<RustOpaqueBase<RustAutoOpaqueInner<metadata::SpecificMetadata>, frb_generated::MoiArc<RustAutoOpaqueInner<metadata::SpecificMetadata>>>>`
note: required by a bound in `transform_result_sse`
   --> src/frb_generated.rs:38:1
    |
38  | / flutter_rust_bridge::frb_generated_boilerplate!(
39  | |     default_stream_sink_codec = SseCodec,
40  | |     default_rust_opaque = RustOpaqueMoi,
41  | |     default_rust_auto_opaque = RustAutoOpaqueMoi,
42  | | );
    | | ^
    | | |
    | |_required by a bound in this function
    |   required by this bound in `transform_result_sse`
    = note: this error originates in the macro `$crate::frb_generated_sse_codec` which comes from the expansion of the macro `flutter_rust_bridge::frb_generated_boilerplate` (in Nightly builds, run with -Z macro-backtrace for more info)
```

It would really be great if there was an overview/a list of all the things someone using `frb` has to be aware of/limitations of `frb`.
I.e. especially what *does not work* as one woild expect, when coming from Rust. 

Also is there a list of stuff the `frb` macro does/can do? I couldn't find it.
I only found examples of its use scattered over docs/examples and the [`docs.rs` section on it](https://docs.rs/flutter_rust_bridge/2.0.0-dev.39/flutter_rust_bridge/attr.frb.html) has zero information and just links back to the `README` of this repo.

**Comment by fzyzcjy** [comment]
Another way about the `Option<&VeryComplexFoo>` is discussed in https://cjycode.com/flutter_rust_bridge/guides/how-to/borrowed. Shortly speaking, maybe try to use `Arc<VeryComplexFoo>` (or similar `RustAutoOpaque<VeryComplexFoo>`)  to have shared ownership.

**Comment by virtualritz** [comment]
> In the next batch (possibly in a few days?), I will implement feature that you can return arbitrary type that has lifetime, such as the -> Option<&VeryComplexFoo>. Then, there is no cloning needed!

That is awesome!

> Another way about the Option<&VeryComplexFoo> is discussed in https://cjycode.com/flutter_rust_bridge/guides/how-to/borrowed. Shortly speaking, maybe try to use Arc<VeryComplexFoo> (or similar RustAutoOpaque<VeryComplexFoo>) to have shared ownership.

True. My main complaint here is: as a new user of your bridge, it is difficult to understand for me where I have diverge from idiomatic Rust with my API. Returning an `Arc<VeryComplexFoo>` is not idiomatic in the case at hand.

I.e. what I would actually do then is factor out my code into a pure Rust crate and write another Rust wrapper that has the `frb`-compliant API.

The guides kind of give the impression that this isn't neccessary. My gut feeling is that the more honest way to put this would be:

```
The frb covers a lot of cases when reflecting Rust to Dart.
But some things require different approaches. These are:
1. ...
2. ...
```

What I mean is that the guides are great but they have *tutorial* character mosly.
It would be cool to have stuff like the `frb` macro extensively covered on [`docs.rs/flutter_rust_bridge`](https://docs.rs/flutter_rust_bridge/) in form of *reference* documentation.

In my case I work with a very experienced Flutter developer that takes care of the Dart side. I only care about the Rust side.
I.e. for me docs that tell me: you need to diverge from idiomatic Rust in this or that way, in very compact form, are what I need.

That said: I am taking notes of everything I come accross so I hope I can contribute some of that back to the crate docs in exactly that way (i.e. ending up on `docs.rs`).

**Comment by fzyzcjy** [comment]
I see. Currently such things seems to be accompany with specific features. Looking forward to your list of such limitations! (I may not directly merge that as-is, but instead try to improve frb to make the list as short as possible ;) )

**Comment by fzyzcjy** [comment]
New version supports lifetimes: https://cjycode.com/flutter_rust_bridge/guides/lifetimes
