### ISSUE TITLE
Override  `set_` method with `#[frb(opaque)]` struct 

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2079]
## Env
Win10, FRB V2 DEV 39,  Flutter 3.22.2, Rust 1.79

## Issue
For a Rust struct with pub field named `a` along with `#[frb(opaque)]`, if there is a method called `pub fn set_a(&mut self ....)`, then the generated file `frb_generated.rs`(along with correspondingly dart file) would be panic because of duplicated implementation.

example screenshot for field `content`:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/51b724d1-4def-4b18-a08e-5260c14bd2f8)

## WorkAround
Currently, if the field and the method is made to be exposed to Dart, a workaround is rename the `set_a` to another name.

## Suggestion
It seems to be related to the auto generated get/set reflection methods for each pub field of a  `#[frb(opaque)]` Rust type. Hopefully, this could be refined by NOT generating corresponding get or set reflection methods correspondingly once FRB detects there is already a manual method in form `pub fn set_<field_name>(&mut self,....)` or `pub fn <field_name>(&self,....)->&a`.

I am not sure what I said above is the correct way to refine it. Just intuitionally, it seems that it is related to the[ reflection field methods](https://github.com/fzyzcjy/flutter_rust_bridge/pull/2058).

**Comment by dbsxdbsx** [comment]
Hmm.... maybe this suggestion is still flawable.    Because if FRB not generate the corresponding get/set reflection code, then user can't get/set the field directly in Dart.

**Comment by fzyzcjy** [comment]
What about this: Currently, https://github.com/fzyzcjy/flutter_rust_bridge/blob/954c9661348072dbe5ff3dbaca4e04b71bb66886/frb_codegen/src/library/codegen/parser/mir/parser/function/auto_accessor/field.rs#L31 generates `set_thefieldname` as dummy name. However, maybe we can change that *single* line to something like:

```rust
    let rust_method_name = format!("auto_accessor_{}_{}", accessor_mode.verb_str(), field.name.rust_style());
```

Then there will be no conflict.

**Comment by dbsxdbsx** [comment]
Yes, I like this prefix solution. Actually, I just come up a similar way with surfix like `<field_name>_only_for_dart_reflection`(or even make it with a random number surfix, but this way would make the generated file be different after each generation, seems to be not good in practice).  Anyway, as long as the default reflection signature name has little chance to conflict with manual fn signature, then it is ok.

**Comment by fzyzcjy** [comment]
Feel free to PR for this! Alternatively I will work on it in the next batch.

**Comment by fzyzcjy** [comment]
@dbsxdbsx Do you want to PR for this? If not, I will work on it.

**Comment by dbsxdbsx** [comment]
> @dbsxdbsx Do you want to PR for this? If not, I will work on it (since quite trivial).

I want to give it a shot.

**Comment by fzyzcjy** [comment]
Take your time and looking forward to it!

**Comment by dbsxdbsx** [comment]
By the way, I wonder what is the basic routine before pr.  I've referred guidance [here](https://cjycode.com/flutter_rust_bridge/guides/contributing/tip), but still unclear.

For example,  after modifying code in `frb_codegen`, what local test to do before pr?  I noticed `frb_internal.bat`, and it seems that `./frb_internal precommit --mode slow` is the cmd to make sure the local test?  
For the default code, this command finally ended with :
```
 19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: BaseThreadInitThunk
  24: RtlUserThreadStart)
Done!
Pick temporary directory: D:\DATA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge\target\GenerateRunFrbCodegenCommandIntegrate\temp_2024-06-15T100130429485_564399070
Pick temporary directory: D:\DATA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge\target\GenerateRunFrbCodegenCommandIntegrate\temp_2024-06-15T100130432485_255319736
Unhandled exception:
PathAccessException: Rename failed, path = 'D:\DATA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge\frb_example/flutter_via_create' (OS Error: 拒绝访问。
, errno = 5)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:195:7)
<asynchronous suspension>
#2      generateRunFrbCodegenCommandIntegrate.<anonymous closure> (package:flutter_rust_bridge_internal/src/makefile_dart/generate.dart:334:7)
<asynchronous suspension>
#3      wrapMaybeSetExitIfChangedRaw (package:flutter_rust_bridge_internal/src/makefile_dart/generate.dart:411:3)
<asynchronous suspension>
#4      _wrapMaybeSetExitIfChanged (package:flutter_rust_bridge_internal/src/makefile_dart/generate.dart:400:3)
<asynchronous suspension>
#5      generateRunFrbCodegenCommandIntegrate (package:flutter_rust_bridge_internal/src/makefile_dart/generate.dart:317:3)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      precommitIntegrate (package:flutter_rust_bridge_internal/src/makefile_dart/misc.dart:89:3)
<asynchronous suspension>
#8      precommit (package:flutter_rust_bridge_internal/src/makefile_dart/misc.dart:52:5)
<asynchronous suspension>
#9      SimpleConfigCommand.run (package:flutter_rust_bridge_internal/src/utils/makefile_dart_infra.dart:88:31)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     main (file:///D:/DATA/BaiduSyncdisk/project/personal/test_repo/flutter_rust_bridge/tools/frb_internal/bin/flutter_rust_bridge_internal.dart:30:3)
<asynchronous suspension>
```
Is it the correct output before pr?

**Comment by fzyzcjy** [comment]
For your scenario, try

```
./frb_internal precommit-generate
```

which runs codegen on all projects.

Alternatively, suppose you are in `flutter_rust_bridge/frb_example/pure_dart` folder, then can run `just codegen generate` to generate for that single repo.

**Comment by dbsxdbsx** [comment]
After running `./frb_internal precommit-generate` for the default code, it has over hundreds of dart file diffs, seems all are due to format difference.   
So I guess `./frb_internal precommit-generate` is not the final command before pr?

**Comment by fzyzcjy** [comment]
It should have that... Maybe paste the logs, is there any errors?

**Comment by dbsxdbsx** [comment]
> It should not have that... Maybe paste the logs, is there any errors?

Seems no error.
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/e149fd4b-dccf-4334-b89a-751b9dd9f487)

By the way, I am eliminated the `end of line` issue, since I am on win10.

**Comment by fzyzcjy** [comment]
That's weird, which looks like Dart formatter is never executed... What if

> in flutter_rust_bridge/frb_example/pure_dart folder, then run `just codegen generate`

**Comment by dbsxdbsx** [comment]
> That's weird, which looks like Dart formatter is never executed... What if
> 
> > in flutter_rust_bridge/frb_example/pure_dart folder, then run `just codegen generate`

for `just codegen generate`, it has error:
```
cd D:\DATA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge\frb_example\pure_dart && cargo run --manifest-path D:\DATA\BaTA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge/frb_codegen/Cargo.toml -- generate
error: Recipe `codegen` could not be run because just could not find the shell: program not found
```

And for the err of `./frb_internal precommit-generate`, I've tried in PowerShell and Gith Bash---both occurs the same issue. And the output  diff files are only for Dart, the Rust files are ok.

**Comment by fzyzcjy** [comment]
Hmm, then maybe execute the equivalent of 

```
cd D:\DATA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge\frb_example\pure_dart && cargo run --manifest-path D:\DATA\BaTA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge/frb_codegen/Cargo.toml -- generate
```

Manually?

**Comment by dbsxdbsx** [comment]
> Hmm, then maybe execute the equivalent of
> 
> ```
> cd D:\DATA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge\frb_example\pure_dart && cargo run --manifest-path D:\DATA\BaTA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge/frb_codegen/Cargo.toml -- generate
> ```
> 
> Manually?

The correct cmd for it should be `cd D:\DATA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge\frb_example\pure_dart ; cargo run --manifest-path D:\DATA\BaiduSyncdisk\project\personal\test_repo\flutter_rust_bridge/frb_codegen/Cargo.toml -- generate` using PowerShell on win10, which ends with this:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/f297d9c3-e000-4c30-a1bb-b175554f2652)

Still, there are lots of dart files diffs.

**Comment by dbsxdbsx** [comment]
I've also tried to make a `ps1` script for powershell based on this section [Format and lint everything](https://cjycode.com/flutter_rust_bridge/manual/miscellaneous/archived/misc-contributing#format-and-lint-everything), but still ran into some issues.

Maybe I should wait until there is refined version for windows developer.

**Comment by fzyzcjy** [comment]
That's weird. The "run dart formatter" section is already there. Most importantly, CI does check windows codegen and it works well, and nobody using frb did say on windows the formatter is not run...

For that formatter problem, maybe run `dart format .` on e.g. `frb_example/pure_dart`, then it should be OK, since frb codegen also just simply call like that.

**Comment by dbsxdbsx** [comment]
I just found that  running `dart format .` after `./frb_internal precommit-generate` could fix most format issues,except for those in `frb_codegen\test_fixtures\`:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/2c4955ed-8225-49c6-b483-0519f503eb8b)
I think now it is time to pr.

**Comment by fzyzcjy** [comment]
> frb_codegen\test_fixtures\

Those are not formatted at all IIRC, so just leave them untouched (unformatted) and it will not have diff.
