### ISSUE TITLE
`chrono::NaiveDateTime` with `non_opaque` generates wrong and missing dart code

### ISSUE THREAD

**Issue by devgony** [fzyzcjy/flutter_rust_bridge#2080]
### Describe the bug

When i convert `chrono::NaiveDateTime` with `non_opaque` like below, it generates wrong and missing dart code

### Steps to reproduce

```rs
#[frb(non_opaque)]
pub enum DartValue {
  ..
  Timestamp(NaiveDateTime),
  ..
}
```

```sh
flutter_rust_bridge_codegen generate
flutter run
1

```

### Logs
it gets error: 
> no method named `into_into_dart` found for struct `NaiveDateTime` in the current scope
method not found in `NaiveDateTime`

```dart
impl flutter_rust_bridge::IntoDart for crate::api::value::DartValue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
      ..
      crate::api::value::DartValue::Timestamp(field0) => {
          [18.into_dart(), field0.into_into_dart().into_dart()].into_dart() // no method named `into_into_dart` found for struct `NaiveDateTime` in the current scope
method not found in `NaiveDateTime`
      }
      ..
```

So i manully implemented those missing dart codes
```rs
impl flutter_rust_bridge::IntoDart for FrbWrapper<NaiveDateTime> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<NaiveDateTime> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<NaiveDateTime>> for NaiveDateTime {
    fn into_into_dart(self) -> FrbWrapper<NaiveDateTime> {
        self.into()
    }
}
```
and more dependent codes [(see full diff)](https://github.com/gluesql/gluesql/pull/1503/commits/f51262f2cfee4a8bce9f94b7344b1e9a2886297b)
 and it solved.

> How can i solve it in better way? It give me any hint, I'm opened to contribute this as well.

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

2.0.0-dev.39

### Flutter info

3.22.2

_No response_

**Comment by fzyzcjy** [comment]
I see: Could you please try to add feature `chrono` in cargo.toml like:

```
flutter_rust_bridge = { ..., features = ["chrono"] }
```

**Comment by devgony** [comment]
@fzyzcjy Thanks for quick reply.
Sadly.. I tried with `flutter_rust_bridge = { version = "=2.0.0-dev.39", features = ["chrono"] }` but the result is identical.

**Comment by fzyzcjy** [comment]
hmm that's weird... https://github.com/fzyzcjy/flutter_rust_bridge/blob/954c9661348072dbe5ff3dbaca4e04b71bb66886/frb_rust/src/misc/into_into_dart.rs#L217 shows that `IntoIntoDart` should be implemented for `NaiveDateTime`.

> How can i solve it in better way? It give me any hint, I'm opened to contribute this as well.

To debug this issue, one way is to:

*  clone flutter_rust_bridge
* Add a few lines in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/dart_minimal/rust/src/api/minimal.rs to reproduce the issue
* under that `dart_minimal` folder, run `just codegen generate` (which executes the local development of flutter_rust_bridge_codegen generate)
* compile that `dart_minimal/rust` crate and should see the error reported
* then can play with everything inside flutter_rust_bridge to find out the problem

**Comment by devgony** [comment]
I might have done something dumbo, features = ["chrono"] works well now.
Thank you !

**Comment by fzyzcjy** [comment]
You are welcome!
