### ISSUE TITLE
There are still multiple objects with same key after merging warning

### ISSUE THREAD

**Issue by NightBlaze** [fzyzcjy/flutter_rust_bridge#2082]
### Describe the bug

After update from dev.37 to dev.39 I began to receive warnings `There are still multiple objects with same key after merging, thus randomly pick one`
```
> flutter_rust_bridge_codegen generate
[2024-06-14T08:32:10.602Z WARN .../flutter_rust_bridge_codegen-2.0.0-dev.39/src/library/codegen/parser/hir/flat/transformer/merge_duplicate_transformer/mod.rs:72] There are still multiple objects with same key after merging, thus randomly pick one (key="User", objects={"name":"crate::internal::network::user_network/User","visibility":"Restricted","sources":["Normal"],"mirror":false}, {"name":"crate::internal::services::user_service/User","visibility":"Restricted","sources":["Normal"],"mirror":false})
... more similar warnings
```

My application features a layered structure, comprising `network` and `service` layers. The `service` layer employs `network` and `storage` as dependencies, and the application utilizes solely the `service` layer. To avoid verbosity, I elected for succinct naming conventions, where the "type" (be it network, storage, or service) of an object is indicated by the module name.

All of this code is housed within the `internal` folder, which is situated on the same hierarchical level as `api`, not within it. Additionally, I use `pub(crate)` instead of simply `pub` to avoid generating code for the code.

My `flutter_rust_bridge.yaml` contains
```
rust_input: rust/src/api/**/*.rs
dart_output: lib/src/rust
```
so `flutter_rust_bridge_codegen generate` probably should to ignore all code in `internal`.

### Steps to reproduce

-

### Logs

```shell
-
```

### Expected behavior

I would like to `flutter_rust_bridge_codegen generate` ignore `internal` package or to have documentation about naming conventions.

**Comment by NightBlaze** [comment]
@fzyzcjy Does it mean that I can just ignore the warnings?

**Comment by fzyzcjy** [comment]
If you do not use those types, then yes just ignore it currently.
