### ISSUE TITLE
Getter returning borrowed type gets translated to getter that returns `void` on Dart side.

### ISSUE THREAD

**Issue by virtualritz** [fzyzcjy/flutter_rust_bridge#2083]
The issue is that `rfb` does not translate some Rust code into something useful in Dart and there is no warning/error.

The `generate` command should at least warn or even error if it can't reflect a signature meaningfully to the Dart side.

In my code I have (zero copy):

```rust
impl FileInfo {
    pub fn metadata(&self) -> &Metadata {
        &self.metadata
    }
    
    ...
}
```

This gets translated to:
```dart
Future<void> metadata();
```

If I switch to copying the data:

```rust
impl FileInfo {
    pub fn metadata(&self) -> Metadata {
        self.metadata.clone()
    }
    
    ...
}
```

I get something usable in Dart:

```dart
Future<Metadata> metadata();
```

I guess this is related to what we discussed in #2078?

**Comment by fzyzcjy** [comment]
This is a workaround when working with "translate a whole crate" (more specifically, using the example of auto translating the web-audio-api crate).

I am planning (working on it!) to support returning borrowed types. So wait for several days (I hope I can finish in that time), and I guess this is no longer an issue ;)
