### ISSUE TITLE
Generation Err with param type `std::sync::MutexGuard<>`

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2094]
## Issue
When transferring an old project from FRB V1 to FRB V2,  I accidentally found that param type `std::sync::MutexGuard<>` is not supported. For example:
```rust
// my real example
pub(crate) fn get_unside_piece_by_pos(
    board_array: &std::sync::MutexGuard<[u8; 256]>,
    board_pos: u8,
) -> PieceType {
...
}
// the same issued example
pub fn test_mutex_guard(board_array: &std::sync::MutexGuard<u8>) {
    println!("{}", board_array);
}
```
The generation is finished with no error, but the output `frb_generated.rs` has the below error:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/8b1d9741-576e-4ae5-8ced-b07fe98ee5fb)
along with 2 errors within `frb_generated.io.rs` related to code:
```rust
#[no_mangle]
pub extern "C" fn frbgen_meng_ru_ling_shi_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstdsyncMutexGuardu8(
    ptr: *const std::ffi::c_void,
) {
    MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<std :: sync :: MutexGuard < u8 >>>::increment_strong_count(ptr as _);
}

#[no_mangle]
pub extern "C" fn frbgen_meng_ru_ling_shi_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerstdsyncMutexGuardu8(
    ptr: *const std::ffi::c_void,
) {
    MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<std :: sync :: MutexGuard < u8 >>>::decrement_strong_count(ptr as _);
}
```

## Should be supported?
Here, I said I found it accidentally, which means that the fn `get_unside_piece_by_pos` is not planned to be exposed. It is used in another module. And it is used in an exposed API like this:
```rust
pub(crate) static BOARD_ARRAY: Lazy<Mutex<[u8; 256]>> = Lazy::new(|| Mutex::new([0; 256]));
...

pub fn is_legal_move(src_row: u8, src_col: u8, dst_row: u8, dst_col: u8) -> bool {
    let src_pos = crate::chess::get_board_pos_from_row_col(src_row, src_col);
    let dst_pos = crate::chess::get_board_pos_from_row_col(dst_row, dst_col);

    // get src piece|
    let board_array = BOARD_ARRAY.lock().unwrap();
    let unside_src_piece = crate::chess::get_unside_piece_by_pos(&board_array, src_pos);   // here it used !

    ...
}
```
So practically, I can ignore it.  

But now I wonder whether the type `std::sync::MutexGuard<...>`  is useful for an API fn in some (corner) cases?  
 If this kind of type is really useful, then hopefully, it could be supported in the future.

**Comment by fzyzcjy** [comment]
Looks like the guard has some lifetime, thus it may not be supported until #2093.

**Comment by fzyzcjy** [comment]
Lifetime is supported in new version
