### ISSUE TITLE
Bigdecimal crate does not translate.

### ISSUE THREAD

**Issue by virtualritz** [fzyzcjy/flutter_rust_bridge#2106]
### Describe the bug

In my `flutter_rust_bridge.yaml`:

```yaml
rust_input: crate::api,num-rational,bigdecimal
```

Then:

```
❯ flutter_rust_bridge_codegen generate
[0.9s] Parse  
  └── [0.8s] Cargo expand & syn parse  
  └── [0.1s] Parse HIR  
  └── [0.0s] Parse MIR  
[0.1s] Generate 
Error: Will generate duplicated class names (["BigDecimalRef"]).
This is often because the type is auto inferred as both opaque and non-opaque.
Try to add `#[frb(opaque)]` or `#[frb(non_opaque)]` to the struct, or change code that uses it.
Another way to debug is to temporarily set environment variable `FRB_DEBUG_SKIP_SANITY_CHECK_CLASS_NAME_DUPLICATES=1` and check the generated code.
```

As `bigdecimal` is a third party crate, I can't really add any `#[frb(...)]` stuff anywhere ...

### OS

Linux

### Version of `flutter_rust_bridge_codegen`

Latest (git)

**Comment by fzyzcjy** [comment]
Hmm, maybe num-rational or decimal is too complex to be fully automatically scanned?

As for the error, try what it suggests - `FRB_DEBUG_SKIP_SANITY_CHECK_CLASS_NAME_DUPLICATES=1` and see (maybe paste here) what is wrong

**Comment by fzyzcjy** [comment]
Oh I see, seems that you want to use https://github.com/fzyzcjy/flutter_rust_bridge/issues/2105, then see my suggestion there.

**Comment by fzyzcjy** [comment]
Close since the suggestions of BigDecimal are in https://github.com/fzyzcjy/flutter_rust_bridge/issues/2103#issuecomment-2178131466, but feel free to reopen or create new issues if you do need to translate this crate!
