### ISSUE TITLE
Collision between getter and field in scanned struct

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#2108]
### Describe the bug

I am trying the new whole module scanning feature, and I attempted to use it with the generated output of a prost protobuf.

One of the structs there has:

```rust
    #[prost(uint32, optional, tag = "3")]
    pub selected_contact: ::core::option::Option<u32>,
```

The generated dart has:
```
class GeneratedDartForTheStruct {
  final int? selectedContact;

  const GeneratedDartForTheStruct({
    this.selectedContact,
  });

  ///Returns the value of `selected_contact`, or the default value if `selected_contact` is unset.
  Future<int> selectedContact() => RustLib.instance.api
          .moduleAndGeneratedDartForTheStructSelectedContact(
        that: this,
      );
```

This is a compile error because the field and getter names match and they're not allowed to.

### Steps to reproduce

Unsure

### Logs

```shell
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
lib/src/rust/third_party/module/file.dart:58:15:
Error: 'selectedContact' is already declared in this scope.
  Future<int> selectedContact() => RustLib.instance.api
```

### Version of `flutter_rust_bridge_codegen`

dev.40

**Comment by fzyzcjy** [comment]
Hmm, I guess prost auto generate a getter function, so they conflict?

If it is third party, try to use https://cjycode.com/flutter_rust_bridge/guides/third-party/automatic/override-attributes to `#[frb(ignore)]` that specific method and see whether it works.

**Comment by aran** [comment]
Sounds like this is user error on my side. I can get around it with the extern serializer feature.

**Comment by fzyzcjy** [comment]
Happy to see it is workarounded!
