### ISSUE TITLE
Force usage of WASM in main-thread only

### ISSUE THREAD

**Issue by Slixe** [fzyzcjy/flutter_rust_bridge#2111]
**Is your feature request related to a problem? Please describe.**
I'm mocking my DB system for Web by using the LocalStorage from `web-sys` crate, unfortunately, it looks like I cannot access to the Windows object because its running in a web worker.

I would like to know if it was possible to force/stick the WASM to run in the main thread directly to have access to the window and local Storage or to provide a proxy to do so?

**Describe the solution you'd like**
Add a flag to run the WASM in "main thread" or provide a proxy to be compatible with LocalStorage usage from workers.

**Describe alternatives you've considered**
Try to use IndexedDB instead of LocalStorage because it seems IndexedDB can be used in workers.

**Comment by fzyzcjy** [comment]
> I would like to know if it was possible to force/stick the WASM to run in the main thread directly to have access to the window and local Storage or to provide a proxy to do so?

If you use `async fn`, or use `#[frb(sync)] fn`, then it will be run on main thread (as long as you did not use your own async runner).

**Comment by Slixe** [comment]
Thanks for the reply, we've tried using `#[frb(sync)] fn on the exposed function (called by Dart side) and it's still the same.

But by passing it as a `async fn` it is working but the UI is lagging a lot.

Any recommendations ?

**Comment by fzyzcjy** [comment]
> but the UI is lagging a lot

Hmm, is it because the Rust function is too slow to compute? Then maybe use `spawn_blocking` https://cjycode.com/flutter_rust_bridge/guides/cross-platform/async to make the heavy computation on other threads, and only the lightweight code on main thread.

**Comment by Slixe** [comment]
I've find out why the UI was lagging, it is due to the fact we're hashing the password during validation with Argon2, but `flutter_rust_bridge_serve` is serving the WASM in dev profile, which is normal. But that make everything lagging.

So, I tried to run it using `--release` and boom, surprise, I think there is a memory leak somewhere to compile flutter_rust_bridge lib even with following command `cargo build --target wasm32-unknown-unknown --no-default-features --lib --release`
my Linux with 32GB memory and 16GB swap just completely freeze and need to restart the whole computer (or to wait the SIGKILL)

I'm confused and I don't know from what it comes, if I try from your `dart_minimal` it build fine.
If I try from my libs directly, it build fine.
It looks like its specially for wasm32-unknown-unknown in release mode with the generated boiletplate ?

Still looking into...

**Comment by fzyzcjy** [comment]
> I think there is a memory leak somewhere to compile flutter_rust_bridge lib even with following command cargo build --target wasm32-unknown-unknown --no-default-features --lib --release

Hmm, firstly try to find out the exact command that eats so much memory. For example, suppose copy-paste that `cargo build` command and execute on terminal directly causes that much memory. Then maybe I can do nothing - I am not a developer of `cargo`/Rust language itself :/ Then maybe ask on Rust forums or issue section.

**Comment by Slixe** [comment]
Of course haha, just informing you in case someone else reported it :)

I keep debugging, but no I don't have LTO parameters enabled, I was almost able to reproduce a minimal version, and it depends on how the frb generate rust files... When I find something I'll create a new issue to be well separated.

Thanks for your work again!

**Comment by fzyzcjy** [comment]
You are welcome, and ping me when there are new clues!
