### ISSUE TITLE
third party crate scanning with features

### ISSUE THREAD

**Issue by vhdirk** [fzyzcjy/flutter_rust_bridge#2116]
### Describe the bug

I have 2 crates:
 - a library crate that contains all logic and is platform agnostic
 - a dart/flutter crate that adds stuff to bind with android/ios

The now third party crate scanning feature seems to work rather well (kudos for that). That way I don't have to type so much myself :). 

Since I can make modifications to the library crate, I have annotated some structs and methods with `#[frb(...)]`.
Now, I don't want this library to always depend upon flutter_rust_bridge. That would make no sense for python bindings I'm also making.

So, I did this instead: `#[cfg_attr(feature = "dart", frb(opaque))]`. In the flutter bindings crate, I enable the `dart` feature on my library crate. However, the crate scanning seems to completely ignore it. Does it take the dependency features defined in `Cargo.toml` into account?

### Steps to reproduce

/

### Logs

```shell
/
```

**Comment by fzyzcjy** [comment]
> Since I can make modifications to the library crate, I have annotated some structs and methods with #[frb(...)].

One way is: `/// frb:blahblah`. Then there is no need to depend on frb on that crate.

**Comment by fzyzcjy** [comment]
Close since this seems to solve the issue. However, feel free to reopen if you have any questions!
