### ISSUE TITLE
Support for Future return type in Rust

### ISSUE THREAD

**Issue by AlienKevin** [fzyzcjy/flutter_rust_bridge#212]
# Problem
Many IO and network tasks require async/await and Future in Rust. To avoid passing large files through the bridge, I attempted to move the http.get requests from Flutter to Rust. I use the popular reqwest library and all functions like get are async. This feature is not supported yet and I had to device a messy workaround. I saw support for Future return type on the roadmap and a comment saying that it shouldn't be too hard. I'd love to contribute a solution but my knowledge of Rust, Dart, and FFI is too insufficient to do so.

# Intended Solution
flutter_rust_bridge can generate bindings for functions that return a Future or uses async/await, so I can write code like below:
```rust
pub async fn make_dict(output_path: String) -> anyhow::Result<i32> {
    block_on(async {
        let csv_url = "https://.../all.csv.gz";
        let csv_gz_data = reqwest::get(csv_url).await?.bytes().await?;
        ...
        // do something with gziped csv data
        ...
        let front_back_matter_url = "https://sourceforge.net/projects/.../download";
        let front_back_matter_data = reqwest::get(front_back_matter_url).await?.text().await?;
        let dict_xml = to_apple_dict(front_back_matter_data, dict);

        // write xml to file
        fs::write(&output_path, dict_xml).map(|_| 0)
            .map_err(|_| anyhow!("Unable to write dictionary XML to {}", output_path))
    })
}
```

# Messy Workaround
I tried to run the requests in an async block and runs the futures to completion by wrapping the async block with `block_on`. This is not successful and Flutter produces an error saying "Unhandled Exception: FfiException(PANIC_ERROR, not currently running on a Tokio 0.2.x runtime., null)". I did some research and attempted to solve the perceived tokio compatability issue with `tokio-compat-02`. It did not work. So I further constrainted reqwest to `{version = "0.10.9", default-features = false, features = ["rustls-tls"]}` based on the suggestion of [this GitHub issue](https://github.com/awslabs/aws-lambda-rust-runtime/issues/270#issuecomment-735432763). With the two measures in place, the requests finally works! The code, however, is very ugly and the dependency is very messy. Here's the code I used:
```rust
pub fn make_dict(output_path: String) -> anyhow::Result<i32> {
    block_on(async {
        let csv_url = "https://.../all.csv.gz";
        let csv_gz_data = reqwest::get(csv_url).compat().await?.bytes().compat().await?;
        ...
        // do something with gziped csv data
        ...
        let front_back_matter_url = "https://sourceforge.net/projects/.../download";
        let front_back_matter_data = reqwest::get(front_back_matter_url).compat().await?.text().compat().await?;
        let dict_xml = to_apple_dict(front_back_matter_data, dict);

        // write xml to file
        fs::write(&output_path, dict_xml).map(|_| 0)
            .map_err(|_| anyhow!("Unable to write dictionary XML to {}", output_path))
    })
}
```
Here's the messy dependency I'm referring to:
```
reqwest = {version = "0.10.9", default-features = false, features = ["rustls-tls"]}
tokio-compat-02 = "0.2"
```

**Comment by fzyzcjy** [comment]
> I saw support for Future return type on the roadmap and a comment saying that it shouldn't be too hard.

Sure!

> I'd love to contribute a solution but my knowledge of Rust, Dart, and FFI is too insufficient to do so.

Thank you for the love to contribute! I can provide suggestions and hints.

> This is not successful and Flutter produces an error saying "Unhandled Exception: FfiException(PANIC_ERROR, not currently running on a Tokio 0.2.x runtime., null)".

For this error, I guess it is because you do not set up the async runtime successfully? Try to create a brand new rust project (without dart or flutter or this bridge, etc) and make async work firstly. There should be a few lines of code setup for async support.

Some hints of what to do:

Currently, the generated code (e.g. https://github.com/fzyzcjy/flutter_rust_bridge/blob/e1a5aec26feb6ca5b650cc47d7ed10904a277b38/frb_example/with_flutter/rust/src/bridge_generated.rs#L16) will use the handler (https://github.com/fzyzcjy/flutter_rust_bridge/blob/e1a5aec26feb6ca5b650cc47d7ed10904a277b38/frb_rust/src/handler.rs) to actually execute logic. The handler currently uses a very simple thread pool and users are free to change it. The approach to solve this proposed issue may to change a bit of the handler as well as change a bit of code generator.

**Comment by AlienKevin** [comment]
Thanks for the advice! I set up a blank rust project to test the reqwest library and figured out the problem! This has something to do with the various approaches to async in rust, which is summarized succinctly in the [Rust Book](https://rust-lang.github.io/async-book/01_getting_started/03_state_of_async_rust.html#language-and-library-support):
> The most fundamental traits, types and functions, such as the Future trait are provided by the standard library. The async/await syntax is supported directly by the Rust compiler.

> Many utility types, macros and functions are provided by the futures crate. They can be used in any async Rust application.

> Execution of async code, IO and task spawning are provided by "async runtimes", such as Tokio and async-std. Most async applications, and some async crates, depend on a specific runtime.

While the futures crate provides an executor called `futures::executor::block_on`, libraries that use Tokio runtime cannot use this executor. According to [Rust-lang community wiki](https://runrust.miraheze.org/wiki/Async_crate_comparison), crates like Tokio that provide both a runtime and IO abstractions often have their IO depend on the runtime. This can make it difficult to write runtime-agnostic code. And this is precisely what went wrong when I tried to wrap `block_on` around an async block containing reqwest calls. Reqwest uses the Tokio runtime and panicked with the error "there is no reactor running, must be called from the context of a Tokio 1.x runtime". After some research, I figured out two ways to execute async codes useing the Tokio runtime. Approach 1 is the simplest and uses the convenient [`tokio::main`](https://docs.rs/tokio/1.14.0/tokio/attr.main.html) macro to turn an async function to a synchronous one. Approach 2 requires you to explicitly create a new Tokio runtime and use its block_on function to run the future to completion.

## Approach 1
```rust
use anyhow;

#[tokio::main(flavor = "current_thread")]
async fn get() -> anyhow::Result<String> {
    let url = "https://link/to/file/download";
    let data = reqwest::get(url).await?.text().await?;
    Ok(data)
}
```
It has the following dependencies:
```toml
[dependencies]
futures = "0.3"
reqwest = "0.11.6"
tokio = { version = "1.14.0", features = ["rt", "macros"] }
anyhow = { version = "1.0.44", features = ["backtrace"] }
```

## Approach 2
```rust
use anyhow;
use tokio::runtime::Runtime;

fn get() -> anyhow::Result<String> {
    let rt = Runtime::new().unwrap();
    rt.block_on(async {
        let url = "https://link/to/file/download";
        let data = reqwest::get(url).await?.text().await?;
        Ok(data)
    })
}
```
It has the following dependencies:
```toml
[dependencies]
futures = "0.3"
reqwest = "0.11.6"
tokio = { version = "1.14.0", features = ["rt-multi-thread"] }
anyhow = { version = "1.0.44", features = ["backtrace"] }
```

Lastly, if you are using the plain futures crate without runtimes like Tokio, you should be safe to wrap the asynchronous code in an async block and use the [`futures::executor::block_on`](https://docs.rs/futures/0.3.18/futures/executor/fn.block_on.html) to run the future to completion:

```rust
use anyhow;
use futures::executor::block_on;

fn get() -> anyhow::Result<String> {
    block_on(async {
	let url = "https://link/to/file/download";
    	let data = reqwest::get(url).await?.text().await?;
    	Ok(data)
    })
}
```

I can make a PR to include a guide on how to essentially "return a future" with flutter_rust_bridge by converting asynchronous functions to synchronous. I tried to follow your advice on how to add support for future as a return type but the code seems beyond my comprehension and I don't wanna mess up things unintentionally. Hence I take the other way and figured out some workarounds listed above.

**Comment by fzyzcjy** [comment]
> I can make a PR to include a guide on how to essentially "return a future" with flutter_rust_bridge by converting asynchronous functions to synchronous.

Sure, thanks!

> I tried to follow your advice on how to add support for future as a return type but the code seems beyond my comprehension and I don't wanna mess up things unintentionally.

Do not worry about that: We have tests, and I will manually review your code as well.

**Comment by AlienKevin** [comment]
Since my macOS PR is still ongoing, I probably need to wait until it's resolved to be able to make this new PR.

**Comment by fzyzcjy** [comment]
PR merged ;)

**Comment by AlienKevin** [comment]
Thanks, I made a new PR to add documentation about async in rust
