### ISSUE TITLE
No trait method generated for enum type

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2129]
The Rust enum code like this:
```rust
#[derive(Debug)]
pub enum ProxyNodeEnum {
    Trojan(TrojanNode),
    VMess(VMessNode),
    VLESS(VLessNode),
}

impl ProxyNode for ProxyNodeEnum {
    fn new(uri: &str) -> Result<Self> {
        if let Ok(node) = TrojanNode::new(uri) {
            return Ok(ProxyNodeEnum::Trojan(node));
        }
        if let Ok(node) = VMessNode::new(uri) {
            return Ok(ProxyNodeEnum::VMess(node));
        }
        if let Ok(node) = VLessNode::new(uri) {
            return Ok(ProxyNodeEnum::VLESS(node));
        }
        Err(anyhow!("无法解析的节点: {}", uri))
    }

    #[frb(generate_impl_enum)]
    fn hostname(&self) -> &str {
        match self {
            ProxyNodeEnum::Trojan(node) => &node.hostname,
            ProxyNodeEnum::VMess(node) => &node.host,
            ProxyNodeEnum::VLESS(node) => &node.hostname,
        }
    }

    fn port(&self) -> u16 {
        match self {
            ProxyNodeEnum::Trojan(node) => node.port,
            ProxyNodeEnum::VMess(node) => node.port,
            ProxyNodeEnum::VLESS(node) => node.port,
        }
    }
}
```
And  I want to use it in Dart like this:
```dart
  final x = await fetchProxyNodes();
  ProxyNodeEnum oneNode = x[0];
  final hostName = oneNode.hostname(); // not ok
```
But it failed, because the generated Dart Code is just like this:
```dart
@freezed
sealed class ProxyNodeEnum with _$ProxyNodeEnum {
  const ProxyNodeEnum._();

  const factory ProxyNodeEnum.trojan(
    TrojanNode field0,
  ) = ProxyNodeEnum_Trojan;
  const factory ProxyNodeEnum.vMess(
    VMessNode field0,
  ) = ProxyNodeEnum_VMess;
  const factory ProxyNodeEnum.vless(
    VLessNode field0,
  ) = ProxyNodeEnum_VLESS;
}
```
Nothing else.

I thought this feature is already solvded by https://github.com/fzyzcjy/flutter_rust_bridge/pull/2024 and https://github.com/fzyzcjy/flutter_rust_bridge/pull/2045.

And by the way,  the ` #[frb(generate_impl_enum)]` listed above is not added original, but was tried after 1st generation failure.  It is hard to find the macro  corresponding usage in the doc, which I hope will be refined for easy search :
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/34520711-e9b5-41ef-8371-1186703d1045)

Also, there is no useful info in [Trait Impl page](https://cjycode.com/flutter_rust_bridge/guides/traits/implementations) and [Enum page](https://cjycode.com/flutter_rust_bridge/guides/types/translatable/detailed/enum).

**Comment by fzyzcjy** [comment]
Hmm, maybe I only generated things for RustAutoOpaques? Thus, one workaround is `#[frb(opaque)]` on that enum and see whether it works.

Generation for non-opaque enums and structs later looks pretty reasonable, thus feel free to PR! Alternatively, I may work on it in the next batch.

**Comment by dbsxdbsx** [comment]
>Thus, one workaround is #[frb(opaque)] on that enum

I've tried it before, but it doesn't solve the issue:
![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/17372655/4e454174-6c3d-4d21-b741-4e24bf0cea77)

**One thing I missed**:
For all above,  I forget to say that the `ProxyNodeEnum` is defined in module `proxy`, and there is only `rust_input: crate::api` in config file before!  After making it `rust_input: crate::api, crate::proxy`, now the issue is solved.

Why I missed to realize it? Because, 1, I just didn't realize to take care module  place defining the Rust type at first; 2,  the whole generation is finished successfully(though the generated corresponding dart file has a syntax issue as the above image). Therefore, hopefully, the generation would fail directly for this case in the future .

> Another workaround is to make it a normal method, instead of a trait method.
Yes, it seems to be anthor workable workaround.

> Generation for non-opaque enums and structs later looks pretty reasonable, thus feel free to PR! Alternatively, I may work on it in the next batch.

For this feature, I would  expect your effort, which is out of my capability.

>generate_impl_enum is removed IIRC, because I later make it automatic. Now you can write down &dyn TraitName directly without using that.

Since it is removed, then it is reasonable there is no info in doc. And it seems to be a macro used for param with ` &dyn TraitName`?  

Anyway, I want to suggest again adding a page for introducing the new FRB macros systematically, maybe better in a table form.   The biggest change in FRB v2 is there are lots of new macros, some of which I think are a little inconvenient to use(unintuitively to realize to use a certain macro) and hard to remember them all.

**Comment by fzyzcjy** [comment]
> Why I missed to realize it? Because, 1, I just didn't realize to take care module place defining the Rust type at first; 2, the whole generation is finished successfully(though the generated corresponding dart file has a syntax issue as the above image). Therefore, hopefully, the generation would fail directly for this case in the future .

Hmm, maybe I will check about how we can improve this scenario later.

> Anyway, I want to suggest again adding a page for introducing the new FRB macros systematically, maybe better in a table form. The biggest change in FRB v2 is there are lots of new macros, some of which I think are a little inconvenient to use(unintuitively to realize to use a certain macro in a certain case) and hard to remember them all.

Hmm, could you please elaborate it a bit more?  Especially, which ones are inconvenient/unintuitive to use - we should try to improve it? Then we can see whether add a page of such macros solve the problem, and if so it would be great.

**Comment by dbsxdbsx** [comment]
>Could you please elaborate it a bit more? Especially, which ones are inconvenient/unintuitive to use - we should try to improve it? Then we can see whether add a page of such macros solve the problem, and if so it would be great!

>EDIT: I think maybe there can be a page, briefly listing all macros and all other customization approaches.

For example, on the stand of my own feeling: `#[frb(sync)]` is quite easy to guess what it would be used for and easy to remember after reading its usage example doc. But some others like `opaque`, `proxy` is unintuitive to guess and remember.  

But after all,  I think as long as there is a clear tutorial doc listing all macros' usage, and as long as the semantics of a certain macro doesn't bias its usage too much, then it is good enough.

**Comment by fzyzcjy** [comment]
I see. That's reasonable!

**Comment by dbsxdbsx** [comment]
I just found anthor 2 issues for both v41 and v42.
1. the generated trait class:
```dart
abstract class ProxyNodeEnum implements RustOpaqueInterface, ProxyNode {
  Future<void> hostname();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ProxyNodeEnum> newInstance({required String uri}) =>
      RustLib.instance.api.crateProxyNodeProxyNodeEnumNew(uri: uri);

  Future<int> port();

  Future<String> toString();
}
```
Here `  Future<String> toString();` has issue `'ProxyNodeEnum.toString' ('Future<String> Function()') isn't a valid override of 'Object.toString' ('String Function()').dart[invalid_override](https://dart.dev/diagnostics/invalid_override)`.

For this, it could be worked around by set the rust trait method `to_string()` with ignore macro like this:
```rust
pub trait ProxyNode: std::fmt::Debug {
    fn new(uri: &str) -> Result<Self>
    where
        Self: Sized;

    fn hostname(&self) -> &str;
    fn port(&self) -> u16;

    #[frb(ignore)]
    fn to_string(&self) -> String {
        format!("{:?}", self)
    }
    // TODO: delete
    // fn to_json_string(&self) -> String {
    //     serde_json::to_string_pretty(self).unwrap()
    // }
}
```

2.  after fixing the 1st one above, it has anthor issue related to each Enum object, for example:
```dart
class TrojanNode {
  final String scheme;
  final String password;
  final String hostname;
  final int port;
  final Map<String, String> parameters;
  final String? tag;

  const TrojanNode({
    required this.scheme,
    required this.password,
    required this.hostname,
    required this.port,
    required this.parameters,
    this.tag,
  });

  Future<void> hostname() =>
      RustLib.instance.api.crateProxyNodeTrojanNodeHostname(
        that: this,
      );
...
```
for `hostname()`, it has issue `The name 'hostname' is already defined.
Try renaming one of the declarations.`, because `hostname` is indeed defined for Enum:
```dart
abstract class ProxyNodeEnum implements RustOpaqueInterface, ProxyNode {
  Future<void> hostname();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ProxyNodeEnum> newInstance({required String uri}) =>
      RustLib.instance.api.crateProxyNodeProxyNodeEnumNew(uri: uri);

  Future<int> port();
}
```

For this, I guess that the only workaround is to rename the fn method name or rename the name of `hostname` in the Enum class itself.  But this way would make the usage of the method in dart be different, which seems to be inconvenient.

**Comment by fzyzcjy** [comment]
For that toString, try `#[frb(sync)]` and see whether it works

For the 2nd, I guess has to have some rename or ignore here, and this may not be a bug of flutter_rust_bridge itself, but language constraints - we cannot have same name two things.

**Comment by dbsxdbsx** [comment]
> For that toString, try #[frb(sync)] and see whether it works

Yes, it is fixed, but has a warning suggesting to add `@override` for `ToString`--- this could be fixed by running `dart format .` finally.

>For the 2nd, I guess has to have some rename or ignore here, and this may not be a bug of flutter_rust_bridge itself, but language constraints - we cannot have same name two things.
It seems that no workaround if both the method of the wrapper Enum and item are needed and with the same signature.  Currently I just use `#[frb(ignore)]` to remove all item methods of the same method, like `hostname()` and `port()`.

For this, I found the most clear work around is NOT define method with the same name with ANY Enum item field, my whole workable code is like this:
```Rust
use anyhow::{anyhow, Result};
use flutter_rust_bridge::frb;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use super::{parse_base64, remove_known_prefixes};

fn parse_from_base64_node<T, S>(bytes: T) -> Result<S>
where
    T: AsRef<[u8]> + std::fmt::Debug,
    S: ProxyNode + serde::de::DeserializeOwned,
{
    let from_utf8 = parse_base64(bytes)?;
    serde_json::from_str::<S>(&from_utf8).map_err(|err| err.into())
}

// 定义通用的代理服务器特性
pub trait ProxyNode: std::fmt::Debug {
    fn new(uri: &str) -> Result<Self>
    where
        Self: Sized;

    // TODO: delete
    fn get_hostname(&self) -> &str;

    fn get_port(&self) -> u16;

    #[frb(sync)]
    fn to_string(&self) -> String {
        format!("{:?}", self)
    }
    // TODO: delete
    // fn to_json_string(&self) -> String {
    //     serde_json::to_string_pretty(self).unwrap()
    // }
}

// 枚举类型，用于封装不同的节点类型
#[derive(Debug)]
pub enum ProxyNodeEnum {
    Trojan(TrojanNode),
    VMess(VMessNode),
    VLESS(VLessNode),
}

impl ProxyNode for ProxyNodeEnum {
    fn new(uri: &str) -> Result<Self> {
        if let Ok(node) = TrojanNode::new(uri) {
            return Ok(ProxyNodeEnum::Trojan(node));
        }
        if let Ok(node) = VMessNode::new(uri) {
            return Ok(ProxyNodeEnum::VMess(node));
        }
        if let Ok(node) = VLessNode::new(uri) {
            return Ok(ProxyNodeEnum::VLESS(node));
        }
        Err(anyhow!("无法解析的节点: {}", uri))
    }

    fn get_hostname(&self) -> &str {
        match self {
            ProxyNodeEnum::Trojan(node) => &node.hostname,
            ProxyNodeEnum::VMess(node) => &node.hostname,
            ProxyNodeEnum::VLESS(node) => &node.hostname,
        }
    }

    fn get_port(&self) -> u16 {
        match self {
            ProxyNodeEnum::Trojan(node) => node.port,
            ProxyNodeEnum::VMess(node) => node.port,
            ProxyNodeEnum::VLESS(node) => node.port,
        }
    }
}

// 为 ProxyNodeEnum 实现 Deserialize
impl<'de> Deserialize<'de> for ProxyNodeEnum {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        #[derive(Deserialize)]
        #[serde(untagged)]
        enum ProxyNodeEnumHelper {
            Trojan(TrojanNode),
            VMess(VMessNode),
            VLESS(VLessNode),
        }

        let helper = ProxyNodeEnumHelper::deserialize(deserializer)?;
        Ok(match helper {
            ProxyNodeEnumHelper::Trojan(node) => ProxyNodeEnum::Trojan(node),
            ProxyNodeEnumHelper::VMess(node) => ProxyNodeEnum::VMess(node),
            ProxyNodeEnumHelper::VLESS(node) => ProxyNodeEnum::VLESS(node),
        })
    }
}

// Trojan服务器节点的结构体
#[derive(Serialize, Deserialize, Debug)]
#[frb(opaque)]
pub struct TrojanNode {
    pub scheme: String,
    pub password: String,
    pub hostname: String,
    pub port: u16,
    pub parameters: HashMap<String, String>,
    pub tag: Option<String>,
}

impl ProxyNode for TrojanNode {
    fn new(uri: &str) -> Result<Self> {
        let url = url::Url::parse(uri)?;
        let scheme = url.scheme().to_string();
        let password = url.username();
        let hostname = url.host_str().ok_or(anyhow!("主机名未找到"))?.to_string();
        let port = url.port().ok_or(anyhow!("端口未找到"))?;

        let mut parameters = HashMap::new();
        if let Some(query) = url.query() {
            for (key, value) in url::form_urlencoded::parse(query.as_bytes()) {
                parameters.insert(key.into_owned(), value.into_owned());
            }
        }

        let tag = url.fragment().map(|s| urlencoding::decode(s).unwrap());

        Ok(TrojanNode {
            scheme,
            password: password.to_string(),
            hostname,
            port,
            parameters,
            tag,
        })
    }

    fn get_hostname(&self) -> &str {
        &self.hostname
    }

    fn get_port(&self) -> u16 {
        self.port
    }
}

// VMess服务器节点的结构体
#[derive(Serialize, Deserialize, Debug)]
pub struct VMessNode {
    pub port: u16,
    pub ps: String,
    pub tls: String,
    pub id: String,
    pub aid: String,
    pub v: String,
    #[serde(rename = "host")] // TODO: need?
    pub hostname: String,
    #[serde(rename = "type")]
    pub node_type: String,
    pub path: String,
    pub net: String,
    pub add: String,
}

impl ProxyNode for VMessNode {
    fn new(uri: &str) -> Result<Self> {
        let refined = remove_known_prefixes(uri);

        parse_from_base64_node(refined)
    }

    fn get_hostname(&self) -> &str {
        &self.hostname
    }

    fn get_port(&self) -> u16 {
        self.port
    }
}

// VLESS服务器节点的结构体
#[derive(Serialize, Deserialize, Debug)]
pub struct VLessNode {
    pub id: String,
    pub hostname: String,
    pub port: u16,
    pub parameters: VlessParameters,
    pub tag: Option<String>,
}

impl ProxyNode for VLessNode {
    fn new(uri: &str) -> Result<Self> {
        let url = url::Url::parse(uri)?;
        let id = url.username();
        let hostname = url.host_str().ok_or(anyhow!("主机名未找到"))?.to_string();
        let port = url.port().ok_or(anyhow!("端口未找到"))?;

        let mut parameters_map = HashMap::new();
        if let Some(query) = url.query() {
            for (key, value) in url::form_urlencoded::parse(query.as_bytes()) {
                parameters_map.insert(key.into_owned(), value.into_owned());
            }
        }

        let parameters = VlessParameters::from_hashmap(&parameters_map);
        let tag = url.fragment().map(|s| urlencoding::decode(s).unwrap());

        Ok(VLessNode {
            id: id.to_string(),
            hostname,
            port,
            parameters,
            tag,
        })
    }

    fn get_hostname(&self) -> &str {
        &self.hostname
    }

    fn get_port(&self) -> u16 {
        self.port
    }
}

#[derive(Serialize, Deserialize, Debug)]
pub struct VlessParameters {
    pub flow: String,
    pub sni: String,
    pub fp: String,
    pub sid: String,
    pub pbk: String,
}

impl VlessParameters {
    pub fn from_hashmap(parameters: &HashMap<String, String>) -> Self {
        VlessParameters {
            flow: parameters.get("flow").cloned().unwrap_or_default(),
            sni: parameters.get("sni").cloned().unwrap_or_default(),
            fp: parameters.get("fp").cloned().unwrap_or_default(),
            sid: parameters.get("sid").cloned().unwrap_or_default(),
            pbk: parameters.get("pbk").cloned().unwrap_or_default(),
        }
    }
}
```
I changed `hostname()` to `get_hostname()` and ,etc.    If you change back to `hostname`, since there is field named `hostname`, whatever the `enum ProxyNodeEnum` is marked with no macro or `#[frb(opaque)]` or `#[frb(non_opaque)]`, it failed sometimes, or even with different issues each time after generation---- It is complex to describle.

And for this post issue, I am all ok. Feel free to close.

**Comment by fzyzcjy** [comment]
>  but has a warning suggesting to add @override for ToString

Btw you can also use dart_preamble to suppress this warning `// ignore_for_file: ...`

>  NOT define any method with the same name with ANY Enum item field

That looks also pretty reasonable (at least until Dart one day supports such name conflict)

**Comment by dbsxdbsx** [comment]
I just realized that for the code pasted above, which may be a good corner case but a bad practical example. Because for `enum ProxyNodeEnum`, there is no need to `impl ProxyNode for ProxyNodeEnum` but only `imp ProxyNodeEnum` is enough.

Also I found anothor issue, but I think it should be posted in anothor post.
