### ISSUE TITLE
These functions are ignored because they have generic argument

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2131]
In web-audio-api-rs : 
The abstract class `node` (very important) has a very very important method : 
```rust
    fn connect<'a>(&self, dest: &'a dyn AudioNode) -> &'a dyn AudioNode {
        self.connect_from_output_to_input(dest, 0, 0)
    }
```
But this method does not generate any dart interface.
```dart
// These functions are ignored because they have generic arguments: `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect_from_output_to_input`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `connect`, `set_onended`, `set_onended`, `set_onended`, `set_onended`
```
Is there any hope to have this processed by FRB ?

**Comment by fzyzcjy** [comment]
IIRC the frb_example one does have this generated. That's probably done by: https://github.com/fzyzcjy/flutter_rust_bridge/blob/52696786b18624a5aa008153adeb9e01037d4a83/frb_example/integrate_third_party/rust/src/api/override_web_audio_api.rs#L62

**Comment by Larpoux** [comment]
> IIRC the frb_example one does have this generated. That's probably done by:
> 
> https://github.com/fzyzcjy/flutter_rust_bridge/blob/52696786b18624a5aa008153adeb9e01037d4a83/frb_example/integrate_third_party/rust/src/api/override_web_audio_api.rs#L62
>
> Alternatively, currently users can already use `connect` method of a concrete node, so that abstract method does not add concrete things. For example, users today can already do `GainNode().connect(anoterNode)`

Yes, my code compiles, now, thanks to /rust/src/api/override_web_audio_api.rs.
I cannot yet test if it runs correctly, because I have other problems with CPAL. I am closing this issue and I will reopen it if I encounter problems.

**Comment by fzyzcjy** [comment]
Sure, take your time!
