### ISSUE TITLE
Missing an `import` in a generated dart file.

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2132]
### Describe the bug

In web-audio-api-rs :
file `media_recorder.dart' : missing an import from `media_streams.dart` : 
```dart
import 'media_streams.dart';
```

### Steps to reproduce

```yaml
rust_input: crate::api,web-audio-api
```

### Logs

```shell
-
```

### Expected behavior

Shoud generate an import in `media_recorder.dart` : 
```dart
import 'media_streams.dart';
```

### Generated binding code

```dart
// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.40.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../web_audio_api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

 flutter_rust_bridge_codegen 2.0.0-dev.40

**Comment by fzyzcjy** [comment]
> flutter_rust_bridge_codegen 2.0.0-dev.40

Hmm, iirc I fixed some bug of import recently. Could you please check `2.0.0` (latest version)?

**Comment by Larpoux** [comment]
Oh, yes. It seems better in the last version. Thanks

**Comment by fzyzcjy** [comment]
You are welcome!
