### ISSUE TITLE
`BigInt` instead of `int`

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2134]
```rust
fn create_buffer
(
    &self,
    number_of_channels: usize,
    length: usize,
    sample_rate: f32,
) -> AudioBuffer
```
Generates this dart : 
```dart
Future<AudioBuffer> createBuffer(
      {required BigInt numberOfChannels,
      required BigInt length,
      required double sampleRate});
```

I think that it should not be `BigInt` but `int` .

**Comment by fzyzcjy** [comment]
Yes, that's why I mentioned before copy the flutter_rust_bridge.yaml in the frb_example - I enabled a flag to make it int for nicer api in this specific case :)

**Comment by Larpoux** [comment]
> I enabled a flag to make it int for nicer api in this specific case

Good 😄 . How can I enable this flag ?

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/blob/52696786b18624a5aa008153adeb9e01037d4a83/frb_example/integrate_third_party/flutter_rust_bridge.yaml#L7
