### ISSUE TITLE
The frb_generated.rs file does not contain use statements for the corresponding third-party library.

### ISSUE THREAD

**Issue by limitLiu** [fzyzcjy/flutter_rust_bridge#2135]
### Describe the bug

I used a third-party library `ndarray` in my project, but after using `flutter_rust_bridge_codegen generate`, the corresponding use statements were not correctly generated.

### Steps to reproduce

When using a third-party library (such as `ndarray`) in Rust code and then generating with frb, I found that the corresponding use statements were not generated in `frb_generated.rs`.

### Logs

```shell
help: consider importing this type alias
    |
28  + use ndarray::Array1;
    |                            
error[E0412]: cannot find type `Array1`
```

### OS

macOS

### Version of `flutter_rust_bridge_codegen`

2.0.0

**Comment by fzyzcjy** [comment]
Hi, could you please try to `pub use` the ndarray in the file that you use it. Then the generated file will contain it.

**Comment by limitLiu** [comment]
> Hi, could you please try to `pub use` the ndarray in the file that you use it. Then the generated file will contain it.

Well done, I noticed that the code u generated includes this statement `use crate::api::algorithm::*;`.
