### ISSUE TITLE
Provide an option to not generate frb_generated.web.dart and frb_generated.web.rs

### ISSUE THREAD

**Issue by Ferry-200** [fzyzcjy/flutter_rust_bridge#2137]
**Is your feature request related to a problem? Please describe.**
In v2.0.0, there is an error in frb_generated.web.dart. 

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/98510207/c3ec1794-3f04-4c00-9e66-bd1ce8c8787b)

If we have a option to not generate the frb_generated.web.dart file, the error will not exist. :)

**Comment by fzyzcjy** [comment]
Hmm, what about `web: false`?

**Comment by Ferry-200** [comment]
> And you can update your minimum Dart version in pubspec.yaml, then that error will disappear.

Yes! The error is gone after upgrading Dart. Thanks for your help and apologize for this needless feature request :)

**Comment by fzyzcjy** [comment]
You are welcome and it's OK!
