### ISSUE TITLE
return type `&str` in Rust turns to return `null` in Dart

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2142]
For a Rust Enum:
```rust
#[derive(Debug)]
pub enum ProxyNodeEnum {
    Trojan(TrojanNode),
    VMess(VMessNode),
    VLESS(VLessNode),
}

impl ProxyNodeEnum {
    pub fn new(uri: &str) -> Result<Self> {
        if let Ok(node) = TrojanNode::new(uri) {
            return Ok(ProxyNodeEnum::Trojan(node));
        }
        if let Ok(node) = VMessNode::new(uri) {
            return Ok(ProxyNodeEnum::VMess(node));
        }
        if let Ok(node) = VLessNode::new(uri) {
            return Ok(ProxyNodeEnum::VLESS(node));
        }
        Err(anyhow!("无法解析的节点: {}", uri))
    }

    pub fn get_hostname1(&self) -> String {
        match self {
            ProxyNodeEnum::Trojan(node) => node.hostname.clone(),
            ProxyNodeEnum::VMess(node) => node.hostname.clone(),
            ProxyNodeEnum::VLESS(node) => node.hostname.clone(),
        }
    }

    pub fn get_hostname2(&self) -> &str {
        match self {
            ProxyNodeEnum::Trojan(node) => &node.hostname,
            ProxyNodeEnum::VMess(node) => &node.hostname,
            ProxyNodeEnum::VLESS(node) => &node.hostname,
        }
    }

...
}
```
with the corresponding Dart code:
```Dart
...
  final hostname1 = await node1.getHostname1();
  final hostname2 = await node1.getHostname2();
```
The `hostname2` returns `null`, but why?  Do I miss something?

**Comment by fzyzcjy** [comment]
Yes, there should be a log hinting you returning `&str` is not supported, thus it changes to void. Try returning `String` which is supported.

**Comment by dbsxdbsx** [comment]
> there should be a log hinting you returning &str is not supported

Why not directly panic during generating?

**Comment by fzyzcjy** [comment]
The direct reason is when translating third party crates, that seems better than panicking. Another reason is that, now the philosophy is try to finish generation even if there are something wrong, thus e.g. if there are 5 errors users can fix them at the same time.

**Comment by dbsxdbsx** [comment]
Hopefully, `&str` could be supported in future.

**Comment by fzyzcjy** [comment]
I think so. Feel free to PR! Alternatively I may work on it later.

**Comment by dbsxdbsx** [comment]
> I think so. Feel free to PR! Alternatively I may work on it later.

It is out of my capability. Looking forward to you.
