### ISSUE TITLE
There is no reactor running, must be called from the context of a Tokio 1.x runtime

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2148]
### Describe the bug

Panic at src/api/override_web_audio_api.rs:124
When I set a callback function for the `ended`event of my audio_buffer_source node.

### Steps to reproduce

```dart
  Future<void> finished(Event event) async
  {
    Tau.tau.logger.d('lolo');
    await stop();
  }
....
src = await audioCtx.createBufferSource();
...
await src.setOnEnded(callback: finished);
```

### override_web_audio_api.rs:124
```
handle_audio_scheduled_source_node_trait_impls_override!(AudioBufferSourceNode);
```

### Logs

```shell
'<unnamed>' panicked at src/api/override_web_audio_api.rs:124:1:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: tokio::task::spawn::spawn_inner::panic_cold_display
   4: tokio::task::spawn::spawn_inner
   5: tokio::task::spawn::spawn
   6: <web_audio_api::node::audio_buffer_source::AudioBufferSourceNode as tau::api::override_web_audio_api::AudioBufferSourceNodeScheduledSourceNodeMiscExt>::set_on_ended::{{closure}}
   7: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
   8: web_audio_api::node::scheduled_source::AudioScheduledSourceNode::set_onended::{{closure}}
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
  11: web_audio_api::events::EventLoop::handle_event
  12: web_audio_api::events::EventLoop::run_in_thread::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### OS

Macos

### Version of `flutter_rust_bridge_codegen`

flutter_rust_bridge_codegen 2.0.0

**Comment by fzyzcjy** [comment]
Ok I guess that's because of something like: https://github.com/fzyzcjy/flutter_rust_bridge/blob/7e2a5f1ca930216697a785c9e29ef258cd8ca766/frb_example/integrate_third_party/rust/src/api/override_web_audio_api.rs#L114 (and various other places). I did not run them before (since that was just a prototype). I will check it a bit later/

**Comment by fzyzcjy** [comment]
PR: https://github.com/fzyzcjy/flutter_rust_bridge/pull/2151 (Just copy-paste the update code)

I have not run it to test whether it is fixed though, since `integrate_third_party` does not contain things to be run but only things at compile time.

**Comment by fzyzcjy** [comment]
Looks great!
