### ISSUE TITLE
Feature: Consider a sanity check on rust version for flutter_rust_bridge_codegen build-web 

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#2157]
**Is your feature request related to a problem? Please describe.**
It's possible for a user's system to have a version of Rust and its libs that is not compatible with the testing / features used for FRB. In these cases, compiler errors from flutter_rust_bridge_codegen build-web can be mysterious.

**Describe the solution you'd like**
Consider embedding the versions of rust used in FRB's CI into the build somewhere, and warning if the user's rust version does not match.

**Describe alternatives you've considered**
N/A

**Comment by fzyzcjy** [comment]
Good idea and feel free to PR since this looks like a good-first-issue! Alternatively I may work on it later.

> In these cases, compiler errors from flutter_rust_bridge_codegen build-web can be mysterious.

May I know a bit more, e.g. what is the error, what is the rust output

**Comment by fzyzcjy** [comment]
Close since inactivity, but feel free to reopen if having more information!

We already specify the min rust version in frb rust library, so I guess the rust toolchain should detect it when the version is too low and warn users.
