### ISSUE TITLE
[cli] unexpected argument '--template' found

### ISSUE THREAD

**Issue by AlexV525** [fzyzcjy/flutter_rust_bridge#2165]
### Describe the bug

https://cjycode.com/flutter_rust_bridge/quickstart#2-create-new-projects--add-to-existing-projects The doc suggested creating the plugin template using `--template` option, but it throws when calling like that.

![image](https://github.com/fzyzcjy/flutter_rust_bridge/assets/15884415/07f0c49e-b406-4077-b7f3-0284d9592e8e)

### Steps to reproduce

1. `cargo install flutter_rust_bridge_codegen`
2. `flutter_rust_bridge_codegen create my_plugin --template plugin`

### Logs

```shell
 flutter_rust_bridge_codegen create my_package --template plugin
error: unexpected argument '--template' found                                                                                                                                                                                                     tip: to pass '--template' as a value, use '-- --template'

Usage: flutter_rust_bridge_codegen.exe create <NAME>

For more information, try '--help'.
```

### OS

Windows 11 23H2 (22631.3737)

### Version of `flutter_rust_bridge_codegen`

2.0.0

### Additional context

The `create` helping messages also do not show anything about templates.

```console
 flutter_rust_bridge_codegen create -h
Create a new Flutter + Rust project

Usage: flutter_rust_bridge_codegen.exe create [OPTIONS] <NAME>

Arguments:
  <NAME>  Name of the new project

Options:
      --org <ORG>
          The organization responsible for your new Flutter project, in reverse domain name notation
      --rust-crate-name <RUST_CRATE_NAME>
          The name of the generated Rust crate
      --rust-crate-dir <RUST_CRATE_DIR>
          The directory of the generated Rust crate
  -h, --help
          Print help
```

**Comment by fzyzcjy** [comment]
Yes, because it is on master, not released yet!

**Comment by AlexV525** [comment]
> Before it is released, feel free to try master (at least for this "generate a template directory" functionality)

Will do. :)

**Comment by fzyzcjy** [comment]
(awaiting for next release since there is no other op needed)

**Comment by BestOwl** [comment]
tried on master and got this error:
```
[2024-07-05T17:02:01.012Z INFO frb_codegen/src/library/integration/creator.rs:45] Step: Inject flutter_rust_bridge related code
[2024-07-05T17:02:01.013Z INFO frb_codegen/src/library/integration/integrator.rs:34] Overlay template onto project
[2024-07-05T17:02:01.016Z INFO frb_codegen/src/library/integration/integrator.rs:62] Modify file permissions
Error: No such file or directory (os error 2)
```

**Comment by fzyzcjy** [comment]
@BestOwl Hi, could you please try `RUST_LOG=debug` env var and rerun the command, and paste logs around that error?

**Comment by fzyzcjy** [comment]
Close since 2.1.0 is released. Feel free to create new issues for other problems!
