### ISSUE TITLE
Add ioDirectory override to the yaml file

### ISSUE THREAD

**Issue by 0xNF** [fzyzcjy/flutter_rust_bridge#2168]
I'm using an external rust repo which uses workspaces for its project layout. Running `flutter_rust_bridge_codegen generate` works well except for a portion of `frb_generated.dart`:

```dart
  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'libsometool',
    ioDirectory: '../../sometool/src/workspace_a/target/release/',
    webPrefix: 'pkg/',
  );
```

the generated ioDirectory is assumed to be the `target/release` folder underneath the frb project, but because its a workspace project, the output is at the project root: `sometool/target/release`.

It'd be nice to have a way of specifying the ioDirectory wthout manually rewriting it every time it is generated.

**Comment by fzyzcjy** [comment]
To customize it, the simplest way is to use https://cjycode.com/flutter_rust_bridge/guides/how-to/load-library and set the ExternalLibraryLoaderConfig.ioDirectory when loading it.

However, feel free to PR to enhance the auto detection to find the correct release dir!

**Comment by 0xNF** [comment]
I'll look into seeing if I can extend the auto detection.
With respect to workspace dirs, the documentation [here](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) suggests that `target` will never be in any other location:

> The workspace has one target directory at the top level that the compiled artifacts will be placed into; the adder package doesn’t have its own target directory. Even if we were to run cargo build from inside the adder directory, the compiled artifacts would still end up in add/target rather than add/adder/target. Cargo structures the target directory in a workspace like this because the crates in a workspace are meant to depend on each other. If each crate had its own target directory, each crate would have to recompile each of the other crates in the workspace to place the artifacts in its own target directory. By sharing one target directory, the crates can avoid unnecessary rebuilding.

**Comment by fzyzcjy** [comment]
Looks great - then we only need to extract "what is the workspace dir" from cargo metadata and done.
