### ISSUE TITLE
Bug with the reference count of an AudioBuffer

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2174]
### Describe the bug

I guess that it is not a bug for FRB but a problem for τ. I Enter this bug here, because I would like some feedback from FRB users : 
- I create an AudioSourceNode (I get an FRB object)
- I create and AudioBuffer (I get an FRB object)
- I call the verb audioSourceNode.setBuffer(audioBuffer); (the buffer is affected to the AudioSourceNode)
- Later, AudioSourceNode is disposed
- Rust dispose itself the rust AudioBuffer now owned by the audioSourceNode
- The audioBuffer is now a FRB object in dart with a reference count = 0 .  BAD! 👎 

I guess I can fix the bug by incrementing the audioBuffer reference count during `setBuffer(audioBuffer)`.
But I wonder if it is not a more general problem for every FRB verbs setting a member with another object ?

### Steps to reproduce

-

### Logs

```shell
-
```

**Comment by Larpoux** [comment]
The rust code for `setBuffer()` is : 
```rust
    /// Provide an [`AudioBuffer`] as the source of data to be played bask
    ///
    /// # Panics
    ///
    /// Panics if a buffer has already been given to the source (though `new` or through
    /// `set_buffer`)
    pub fn set_buffer(&mut self, audio_buffer: AudioBuffer) {
        let clone = audio_buffer.clone();

        assert!(
            self.buffer.is_none(),
            "InvalidStateError - cannot assign buffer twice",
        );
        self.buffer = Some(audio_buffer);

        self.registration.post_message(clone);
    }

```
I don't completely understand why I have a referece count error : the AudioBuffer is cloned, so there is no reason that my own buffer is disposed when the AudioSourceNode is disposed...

**Comment by Larpoux** [comment]
Here is my dart code : 
```dart
      if ( audioBuffer!.isDisposed )
      {
          Tau.tau.logger.d('Is disposed before setbuffer');
      }
      await source!.setBuffer(audioBuffer: audioBuffer!);
      if ( audioBuffer!.isDisposed )
      {
        Tau.tau.logger.d('Is disposed, after setbuffer');
      }
```
I confirm: the buffer is disposed AFTER `setBuffer()`

**Comment by fzyzcjy** [comment]
Looking at signature

```
pub fn set_buffer(&mut self, audio_buffer: AudioBuffer) {
```

This means that, (non-rigorously speaking) the AudioBuffer object is moved into that function.

If we have this Rust code

```rust
let audio_buffer = AudioBuffer(...);
set_buffer(audio_buffer);
// <-- here, audio_buffer cannot be used anymore
```

Then, after the set_buffer, the audio_buffer variable will not be able to be used since it is moved into the function.

Similarly in Dart, the audioBuffer object will not be able to be used after that.

**Comment by fzyzcjy** [comment]
In short, Dart side is trying to mimic the pure Rust behavior. But sometimes we cannot generate errors at compile-time (since Dart compiler/linter surely does not know that much), then we guarantee at runtime.

**Comment by fzyzcjy** [comment]
If you want to use the audiobuffer after calling set_buffer, try to clone it and provide the cloned object into set_buffer

**Comment by Larpoux** [comment]
I see. I understand. but the rust code is 
```rust
```rust
    /// Provide an [`AudioBuffer`] as the source of data to be played bask
    ///
    /// # Panics
    ///
    /// Panics if a buffer has already been given to the source (though `new` or through
    /// `set_buffer`)
    pub fn set_buffer(&mut self, audio_buffer: AudioBuffer) {
        let clone = audio_buffer.clone();

        assert!(
            self.buffer.is_none(),
            "InvalidStateError - cannot assign buffer twice",
        );
        self.buffer = Some(audio_buffer);

        self.registration.post_message(clone);
    }
```
I thought that the `clone()` should have prevented to loose access to my argument after `setbuffer()`.
For a dart user, it is not possible to have an object which is disposed() during a call to the API.

**Comment by fzyzcjy** [comment]
> I thought that the clone() should have prevented to loose access to my argument after setbuffer().

Well, the clone is *inside* the function, and this is indeed things about standard Rust ownership.

> prevented to loose access to my argument

As mentioned, try something like

```rust
impl AudioBuffer {
  // maybe we can auto generate `clone` later, but for now let's say we do this manually
  pub fn my_clone(&self) -> Self { self.clone() }
}
```

```dart
var audioBuffer = ...;
var audioBufferCloned = audioBuffer.clone();
setBuffer(audioBufferCloned);
// audioBuffer can still be used here
```

**Comment by Larpoux** [comment]
Oh, I understand : there is a `clone()` but this is not this new object which is set to the self.buffer

**Comment by Larpoux** [comment]
When I code : 
```dart
mySourceNode.connect(myDestNode);
```
I don't loose access to `mySourceNode`. I Think that it should be always like that for a dart point of view..

**Comment by Larpoux** [comment]
I think that it works for `connect` because the result of the function returns the argument. So Rust knows that the argument must not be disposed on returning

**Comment by Larpoux** [comment]
I maintain that it is not acceptable for a dart point of view to have its argument disposed after a call to the API.

**Comment by fzyzcjy** [comment]
frb does not have magic indeed ;) it tries to mimic standard Rust behavior.

**Comment by Larpoux** [comment]
I overrided `audioSourceBuffer.setBuffer()` by `setAudioBuffer()`. This function clone its argument before calling `setBuffer()`

I Committed this change in my Pull Request [#2169]
