### ISSUE TITLE
Globally generates `sync API` instead of `async API`

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2175]
What about generation of a `sync API` instead of an `async API`  when creates a dart interface of a public rust lib ?
`Web Audio API` is designed to be a non blocking API. So no need to generate an `async` interface.

Note : this is not a major request from me. I can live with the actual behavior.

**Comment by fzyzcjy** [comment]
Try `default_dart_async: false` on flutter_rust_bridge.yaml. (I forgot whether it is on 2.0.0 release or not, but it is on master branch at least)
