### ISSUE TITLE
Enum values did not respect the case in the Rust definition

### ISSUE THREAD

**Issue by AlexV525** [fzyzcjy/flutter_rust_bridge#2176]
### Describe the bug

Enum values' case were changed in generated Dart files.

### Steps to reproduce

```rust
pub enum Network {
    Testnet,
    Regtest,
    Signet,
}
```

```dart
enum Network {
  testnet,
  regtest,
  signet,
  ;
}
```

In previous FRB:
```dart
enum Network {
  Testnet,
  Regtest,
  Signet,
  ;
}
```

### Logs

```shell
N/A
```

### Expected behavior

Generated classes should follow their original case.

### Version of `flutter_rust_bridge_codegen`

2.0.0

### Flutter info

3.22.2

**Comment by fzyzcjy** [comment]
Yes, because in Dart, the convention is to have lowercase enums instead of uppercase (example: https://dart.dev/language/enums), thus using the chance of doing breaking changes before v2 stablized, I choose to follow the convention, since frb always try to follow language convention when possible.

**Comment by AlexV525** [comment]
> Yes, because in Dart, the convention is to have lowercase enums instead of uppercase (example: https://dart.dev/language/enums), thus using the chance of doing breaking changes before v2 stablized, I choose to follow the convention, since frb always try to follow language convention when possible.

True. But the camel case example is only following the Dart recommend rules, not saying that everyone should follow those rules because they are configurable.

> However, maybe we can add a flag to allow users to choose the "do not change case" version.

That would be a convenient option, such as `recase_enum: true/false`.

> I guess to maintain backward compatibility?

Exactly.

**Comment by fzyzcjy** [comment]
Feel free to PR! Alternatively I will work on it hopefully in the next batch.

**Comment by fzyzcjy** [comment]
Looks like there is a flag for this since v1: set `dart_enums_style: false` to use the unchanged case. I guess v2 may just flip the default value.

Feel free to PR for documentations of this (e.g. add a line in the migration guide telling this default behavior change)

**Comment by AlexV525** [comment]
> Looks like there is a flag for this since v1: set `dart_enums_style: false` to use the unchanged case. I guess v2 may just flip the default value.

Haha, that's crazy.

**Comment by fzyzcjy** [comment]
Close since the feature seems to be implemented (but feel free to reopen!)
