### ISSUE TITLE
Add option to ignore "Automatically rename function names to avoid keyword conflict" check

### ISSUE THREAD

**Issue by erdemyerebasmaz** [fzyzcjy/flutter_rust_bridge#2194]
### Describe the bug

Re: [Automatically rename function names to avoid keyword conflict #2150](https://github.com/fzyzcjy/flutter_rust_bridge/pull/2150#issuecomment-2213773291) 

We have **method** named `sync()` on our project, which didn't cause any keyword conflict issues so far*, and with this new change, it's generated as `sync_()`.

Force renaming it as `sync` via #[frb(name = "...")] macro isn't applied.
```
#[frb(name = "sync")]
pub fn sync(&self) {
    ...
}
```
Can we add a macro to ignore this check or apply the rename macro after this check?

Thanks!

---

### *: After investigating, not all Dart keywords cause an issue when used as a function name so there has to be made a distinction between problematic & unproblematic ones when automatically renaming.

---

### Steps to reproduce

Create an empty Dart project & class, then create functions using Dart keywords. Here are a couple of the cases I run into and there ought to be more.

- `default()`
  - error: 'default' can't be used as an identifier because it's a keyword.
- `false()`
  - error: The expression doesn't evaluate to a function, so it can't be invoked.
- `else()` 
  - info: Statements in an if should be enclosed in a block.
- `sync()`
  - non-problematic

### Expected behavior

Automatic rename should not apply to Dart keywords that are not problematic to be used as a function name.

### Generated binding code

```
// Rust input
pub async fn sync() {
    ...
}

// Dart output
Future<void> sync_();
```

### OS

`macOS Sonoma Version 14.5`

### Version of `flutter_rust_bridge_codegen`

`2.1.0`

### Flutter info

```
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (5 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```

### Version of `clang++`

`clang version 18.1.5`

**Comment by fzyzcjy** [comment]
Looks reasonable! Then we should change the check when it is used as function name.

Feel free to PR for this, alternatively I will work on it in the next batch.

For completeness: The workaround - as you have already done - is to stick to 2.0.0 before it is fixed

**Comment by erdemyerebasmaz** [comment]
> Looks reasonable! Then we should change the check when it is used as function name.
> 
> Feel free to PR for this, alternatively I will work on it in the next batch.
> 
> For completeness: The workaround - as you have already done - is to stick to 2.0.0 before it is fixed

Thank you for the swift response!

Some notes: See footnote on [Dart keywords](https://dart.dev/language/keywords), keywords that are flagged 2-3 should be good to use as a function name. 

Keywords that are flagged 1 are not safe to use as a function name **in some contexts**. 
_For example; using `yield()` inside a [generator function](https://dart.dev/language/functions#generators) is unsafe_
Which, imo, should be overwriteable using a macro if you are certain they won't be used in such contexts.

**Comment by fzyzcjy** [comment]
I see. 

> Which, imo, should be overwriteable using a macro if you are certain they won't be used in such contexts.

Then a simpler method may be:

* When user provide a dart name via `#[frb(name = ...)]`, we should NOT run the auto checker and should directly follow what the user requires.
