### ISSUE TITLE
Duplicate class names when translating structs that have generic trait

### ISSUE THREAD

**Issue by psengrith** [fzyzcjy/flutter_rust_bridge#2202]
```Rust
#[derive(Debug, Default)]
#[frb(non_opaque)]
pub struct QuestionData {
    markdown: String,
    explanation: String,
}

impl ChangeEventHandler<QuestionData> for QuestionData {}
```

The above will result in the following error:

``` Will generate duplicated class names (["QuestionData"]). This is often because the type is auto inferred as both opaque and non-opaque. Try to add `#[frb(opaque)]` or `#[frb(non_opaque)]` to the struct, or change code that uses it.```

Is there any way to generate dart code from rust struct that implements trait with generic as in the above case?

**Comment by fzyzcjy** [comment]
Hmm, what about trying `#[frb(opaque)]`?

And, try to use latest version 2.1.0, and it will provide a env variable for debugging.

**Comment by fzyzcjy** [comment]
Close since inactivity, but feel free to reopen if you see any problems!
