### ISSUE TITLE
Error overriding attributes of a function

### ISSUE THREAD

**Issue by danijourdain** [fzyzcjy/flutter_rust_bridge#2204]
I'm using a rust module I've written as an external crate for my Flutter app. I've been able to translate everything automatically so far which has been great! 

I've overridden attributes for a few methods in one of the structs and everything works perfectly. I'm trying to do the same for a standalone function not in any struct, and now my app won't launch. 

**Struct method overriding**
```rust
#![allow(unused_variables)]
 
use std::collections::HashMap;
 
use flutter_rust_bridge::frb;
use windows_rust_anc::zsi::ZSI;
 
#[frb(external)]
impl ZSI {
    #[frb(sync)]
    pub fn new(
        fs: u32,
        training_duration: u32,
        testing_duration: u32,
        goal_panel_db: f32,
        use_backfilter: bool,
        training_signal: Option<Vec<i32>>,
    ) -> Self {
    }
 
    #[frb(sync)]
    pub fn get_audio_device_mapping(&self) -> anyhow::Result<HashMap<String, u8>, anyhow::Error> {}
 
    #[frb(sync)]
    pub fn set_training_signal(&mut self, signal: Vec<i32>) {}
}
```

**Function overriding**
```rust
#![allow(unused_variables)]
 
use flutter_rust_bridge::frb;
 
#[frb(sync)]
pub fn backfilter_mute(muted: bool, channel: u8) {}
 
#[frb(sync)]
pub fn get_mic_on_off_mute(channel: u8) -> anyhow::Result<bool, anyhow::Error> {}
```

The methods are perfectly fine, even with the "unsatisfied" return types. However, after adding the function ```get_mic_on_off_mute```, the app will no longer launch. I have the following error in my IDE. ```flutter_rust_bridge_codegen``` generate executes with no issues. The functions with no return types were perfectly fine and work exactly as expected as synchronous functions.

**Error**
```
mismatched types
  expected enum `Result<bool, anyhow::Error>`
found unit type `()
```

How can I fix this so that ```get_mic_on_off_mute``` also works as async?

**Comment by fzyzcjy** [comment]
Firstly, if you are controlling the third party crate, then an easier method is not to do overriding, but directly use things like `/// flutter_rust_bridge: whatever_thing_here` on the third party crate directly.

Secondly, also try `anyhow::Result<bool>` (and re-generate) and see whether it works.

Thirdly, it would be great to provide a minimal reproducible sample as well as error logs, then it is easier to see what is going on.

**Comment by danijourdain** [comment]
Thanks for your suggestions. I tried just ```anyhow::Result<bool>``` and that didn't work. However, removing the return type entirely worked. The app now launches and runs perfectly fine!

**Comment by fzyzcjy** [comment]
Looks great! Feel free to ping me if you have a reproducible sample.
