### ISSUE TITLE
Allow using rust release libs with flutter debug builds

### ISSUE THREAD

**Issue by Markus43** [fzyzcjy/flutter_rust_bridge#2205]
**Is your feature request related to a problem? Please describe.**
I'm using thisw library to wrap some rust signal processing libraries. These come with heavy runtime differences between debug and release builds, I saw ~20x slower code execution with rustfft in some cases.

**Describe the solution you'd like**
Make it possible to run flutter debug builds with rust release libs. Either make this an option in the generator, or document how to achieve this editing the generated code.

**Describe alternatives you've considered**
Of course one could also externally build the library, and remove the rust build from the project build. But that somehow goes against the purpose of frb ;-)

**Comment by fzyzcjy** [comment]
IIRC you can configure cargokit, the one which frb uses to compile rust, like: https://github.com/irondash/cargokit/blob/main/docs/architecture.md#configuration-for-the-rust-crate

**Comment by Markus43** [comment]
Hmm... These configs are to change how a release and debug build is being built, but I found nothing in order to change from debug to release.
Anyhow: So should I better report this to cargokit then, since it would require a parameter from their side?

**Comment by fzyzcjy** [comment]
Hmm, then what about turning on optimizations when cargo debug build, e.g. https://users.rust-lang.org/t/why-does-cargo-build-not-optimise-by-default/4150

**Comment by Markus43** [comment]
> Hmm, then what about turning on optimizations when cargo debug build, e.g. https://users.rust-lang.org/t/why-does-cargo-build-not-optimise-by-default/4150

That's probably the best idea :-)

Added this to my _cargo.toml_:

> [profile.dev]
> opt-level = 3

... and now debug builds just work like I would like them to, performance is really OK for a debug build this way.

No more need for release builds -> so I close this feature request. Thank you!!!

**Comment by fzyzcjy** [comment]
You are welcome, and happy to see it working!
