### ISSUE TITLE
Custom Thread Pool Needs More Exports from flutter_rust_bridge Runtime

### ISSUE THREAD

**Issue by anlumo** [fzyzcjy/flutter_rust_bridge#2215]
### Describe the bug

I can't figure out how to make a custom thread pool (I want to stop it from doing thread pools at all). There are a couple of things that strike me as if this was never actually tried out:

* In codegen the detection whether to generate the default handlers doesn't actually work, as far as I can see. It apparently tries to search for the string "`static FLUTTER_RUST_BRIDGE_HANDLER`" in source files (I can't tell which ones, this is undocumented), but when using `lazy_static` as recommended in the documentation (by replicating the output of `frb_generated_default_handler!`), it's "`static ref FLUTTER_RUST_BRIDGE_HANDLER`" with an extra `ref`. I tried using `LazyLock` instead of `lazy_static` (as recommended by the Rust team now) that doesn't have that `ref`, but that still doesn't stop codegen from generating that default handler.

https://github.com/fzyzcjy/flutter_rust_bridge/blob/9e5c6e54723700e8436bc76016173e0391befa8e/frb_codegen/src/library/codegen/parser/hir/flat/parser/existing_handler.rs#L32-L35

* Disabling the `thread-pool` feature on the crate causes the `frb_generated_default_handler!` macro to generate invalid code:

> the trait bound `&'static std::thread::LocalKey<flutter_rust_bridge::for_generated::SimpleThreadPool>: flutter_rust_bridge::for_generated::BaseThreadPool` is not satisfied
> the trait `flutter_rust_bridge::for_generated::BaseThreadPool` is implemented for `flutter_rust_bridge::for_generated::SimpleThreadPool`

Which is not surprising, since this implementation is behind a feature gate for `thread-pool`. This wouldn't be a problem if I could get codegen to not include that macro instantiation, though.

* In order to implement my own threadpool, I have to implement BaseThreadPool. However, this trait is in `flutter_rust_bridge::thread_pool`. That module is declared as `pub(crate)` in `lib.rs`, so I can't actually use it.

There also isn't any example for this.

### Version of `flutter_rust_bridge_codegen`

2.1.0

**Comment by fzyzcjy** [comment]
> I want to stop it from doing thread pools at all

IIRC, if you always use `async fn` + `#[frb(sync)] fn` but never `fn`, then no thread pool will be used. 

> this was never actually tried out

I guess the story is, in v1 it worked pretty well, but when doing v2 it may not be implemented properly, and I accidentially missed the test, and nobody realize it until today.

Anyway, could you please provide a minimal reproducible sample? Then it is easier to see what is going on and fix it. (e.g. I want to check where you define the custom handler variable, etc).

I will fix it in the next batch (hopefully within a week), but also feel free to PR!

> it's "static ref FLUTTER_RUST_BRIDGE_HANDLER" with an extra ref

Btw we search the code *after* macro expansion, so imho the "ref" will disappear since the lazy_static will expand to standard static variables.

> However, this trait is in flutter_rust_bridge::thread_pool. That module is declared as pub(crate) in lib.rs, so I can't actually use it.

Agree - this is a bug of not being pub enough, and feel free to PR for this (which is quite easy and just add a few `pub`)!

**Comment by anlumo** [comment]
Still trying stuff...

I discovered that `BaseThreadPool` is re-exported in `flutter_rust_bridge::for_generated` (like so many other things). Maybe that module name is a misnomer, since there are lots of essential items in there to create my own scheduling.

I've managed to trigger the `FLUTTER_RUST_BRIDGE_HANDLER` detection code, but one issue I've run into is that if I declare it twice like in the boilerplate code (once for web and once for everybody else) I get the error that there's more than one declaration. I guess it doesn't detect the `#[cfg(target_famliy = "wasm")]` properly.

> IIRC, if you always use `async fn` + `#[frb(sync)] fn` but never `fn`, then no thread pool will be used. If your goal is to avoid thread pools, then I guess this is sufficient.

Tried that, but disabling the `thread-pool` causes the `FLUTTER_RUST_BRIDGE_HANDLER` detection handler to fail for some reason.

**Comment by fzyzcjy** [comment]
> Maybe that module name is a misnomer, since there are lots of essential items in there to create my own scheduling.

That module *is* for generated only; if something should be used by normal people, it should be re-exported in `flutter_rust_bridge`. (so yes, feel free to PR!)

> I get the error that there's more than one declaration. I guess it doesn't detect the #[cfg(target_famliy = "wasm")] properly.

Hmm reasonable. Then maybe we can just remove that check of more than one declaration, or change the error into a simple warning/info log and tell users this may normal under scenarios like you mentioned.

> Also, the detection code only works when running codegen from the command line. When I use it in build.rs, it doesn't trigger properly. This took me for a detour right now while trying stuff.

Yes, as mentioned, build.rs cannot expand macros (at least now).

> Tried that, but disabling the thread-pool causes the FLUTTER_RUST_BRIDGE_HANDLER detection handler to fail for some reason.

Well, I mean not *using* the pool when running it. May I know why you want to completely *remove* the existence of that pool? (That sounds pretty reasonable, but it would be great to know a bit more details)

**Comment by anlumo** [comment]
> May I know why you want to completely remove the existence of that pool?

The problem is deeper than that. I want to deploy on the web, and the thread pool code depends on cross origin isolation (which is required for multithreading due to the use of SharedArrayBuffer, which btw also requires Rust nightly, which is bad in itself). Enabling cross origin isolation is not an option for me, because it stops many features I need from working, like talking to other browser tabs. I basically spent a few weeks trying to make it work and then gave up, deciding that getting rid of the thread pool is easier than that.

So, just creating the thread pool already fails, even when I'm not using it.

**Comment by anlumo** [comment]
> IIRC, if you always use `async fn` + `#[frb(sync)] fn` but never `fn`, then no thread pool will be used. If your goal is to avoid thread pools, then I guess this is sufficient.

One issue I ran into with this is that even `#[derive(Default)]` triggers the threadpool. I think it'd be better if the default implementation would always be sync, since it should be a very short function that just adds overhead if it's scheduled on the thread pool.

**Comment by fzyzcjy** [comment]
Ah I see. 

>  if the default implementation would always be sync

Maybe try `default_dart_async: false` in flutter_rust_bridge.yaml.

**Comment by anlumo** [comment]
I got it to work! It needed the following symbols from `flutter_rust_bridge::for_generated`:

* BaseCodec
* ErrorListener
* Executor
* HandlerError
* Rust2DartMessageTrait
* SimpleHandler
* TaskContext
* TaskInfo
* TaskRetFutTrait

It also needs calling codegen from the command line (or a build script) as mentioned, as build.rs doesn't work. Additionally, I had to copy `PanicBacktrace` into my code, since it's declared `pub(crate)` and I need it or something equivalent for panic tracking.

I also had to make sure that absolutely nothing creates a threadpool-managed function, otherwise the generated `frb_generated.rs` doesn't compile.

**Comment by fzyzcjy** [comment]
Happy to hear it works! Feel free to PR for these (since they are mainly changing some `pub`)
