### ISSUE TITLE
Can a Flutter plugin include an option for publishing binary files?

### ISSUE THREAD

**Issue by cnwzhu** [fzyzcjy/flutter_rust_bridge#2217]
Can a Flutter plugin include an option for publishing binary files?
This can effectively protect the code.

**Comment by fzyzcjy** [comment]
I guess yes -> https://github.com/irondash/cargokit/blob/main/docs/precompiled_binaries.md

**Comment by fzyzcjy** [comment]
Close since this seems to be answered, but feel free to reopen if needed!

**Comment by cnwzhu** [comment]
I want the results of precompiled builds to be placed in the local file system and not use GitHub.

**Comment by cnwzhu** [comment]
> I guess yes -> https://github.com/irondash/cargokit/blob/main/docs/precompiled_binaries.md (cargokit is the lib that is used to compile/use rust in flutter project)

I want the results of Precompiled builds to be placed in the local file system and not use GitHub.

**Comment by fzyzcjy** [comment]
Then I guess you can ask on the cargokit repo, since flutter_rust_bridge uses it under the hood to compile/integrate rust.

**Comment by cnwzhu** [comment]
> Then I guess you can ask on the cargokit repo, since flutter_rust_bridge uses it under the hood to compile/integrate rust.

Ok, thank you.

**Comment by fzyzcjy** [comment]
You are welcome
