### ISSUE TITLE
[Feature request] isLeaf support

### ISSUE THREAD

**Issue by Rahiche** [fzyzcjy/flutter_rust_bridge#2218]
**Is your feature request related to a problem? Please describe.**
`isLeaf` has less overhead, and is good for calling short non blocking functions
https://api.flutter.dev/flutter/dart-ffi/Native/isLeaf.html

**Describe the solution you'd like**
A parameter when annotating a function to decode if it is leaf or not, it should not.

```rust
#[frb(isLeaf = true)]
pub fn f() {}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fzyzcjy** [comment]
That looks pretty reasonable!

We are currently using the dynamiclibrary approach yet, so we may do it after migrating to the new ffi approach.

Btw, do you see performance issues? If so, feel free to ping me to show your concrete case and we can discuss how to improve performance!

**Comment by fzyzcjy** [comment]
Close since inactivity, but feel free to discuss if you see any performance issues etc!
