### ISSUE TITLE
Returning additional data with a stream from Rust to Dart. 

### ISSUE THREAD

**Issue by TimMeiwald** [fzyzcjy/flutter_rust_bridge#2233]
Firstly, I am loving Flutter Rust Bridge so far it's great and I wish I'd known about it sooner. The following request is just one small annoyance that if it's possible to do would make life easier

**Is your feature request related to a problem? Please describe.**
I have multiple CPU bound tasks that run indefinitely so I spawn a thread to handle that to prevent blocking the main thread and in order to communicate with this thread(via mpsc inwards and streams outwards) I need to pass back a thread_id, I currently hold it in a struct and need to call an additional function in Dart to get that thread_id to get around the StreamSink functions not seemingly allowing an additional return value. Whilst this works it's inconvenient and imo ugly since it adds technically internal controller code to the Dart code as it requires a specific order of calls.  

**Describe the solution you'd like**
Ideally, at a minimum, I'd like to be able to pass back a u32 with a stream so the Dart code can know which thread to send data too/close/interact with. 

**Describe alternatives you've considered**
I tried various approaches and found one functioning one as described above so it's not urgent. I did struggle to understand the threading model of Flutter Rust Bridge so I'd appreciate perhaps a more detailed page in the documentation(I did read the Concurrency chapter in the documentation), It still locked up despite the claim that it uses a threadpool for Rust(not doubting the claim), So maybe add a bit that explains how some example code exactly jumps around threads for the various models.

**Comment by fzyzcjy** [comment]
> in order to communicate with this thread(via mpsc inwards and streams outwards) I need to pass back a thread_id

Not very sure and maybe unrelated, but seems you can directly use mpsc etc w/o a thread id.

> Ideally, at a minimum, I'd like to be able to pass back a u32 with a stream so the Dart code can know which thread to send data too/close/interact with.

I guess a simpler approach is to use objects and methods? e.g.

```rust
pub struct MyRustComputation { ... }

impl MyRustComputation {
  pub fn heavy_compute_and_return_a_stream(&self, sink: StreamSink) {
    thread::spawn(|| {
      let result_1 = do_heavy_compute();
      sink.add(result_1);
      let result_2 = do_heavy_compute();
      sink.add(result_2);
    })
  }
}
```

Then there is no need for the thread_id thing.

Anyway, also feel free to provide a minimal reproducible sample, since it is possible that I do not quite get your specific scenario.

**Comment by fzyzcjy** [comment]
Hmm I am still a bit confused. What if your stream sink is `StreamSink<(i64, String)>`, i.e. both thread id and the data? Or what if one stream is created per thread (like my suggestion above)? - will it work or not

**Comment by fzyzcjy** [comment]
> I'm going to have up to 4 'terminals' each with their own thread and Stream each connected to a different embedded device

So that's what confuses me: what if you have 4 *objects* of the class `MyRustComputation`, one for each "terminal"? Then you will have 4 streams and 4 places to communicate, all isolated.

**Comment by TimMeiwald** [comment]
That would work I suppose, Guess I fell into trying to have all the state in Rust in one object but yeah I suppose it would work. Thanks.

**Comment by fzyzcjy** [comment]
You are welcome! In the ancient days yes your original approach may be the only way, but now frb has many many features ;)
