### ISSUE TITLE
Dart2Wasm not working because of dart:js_util usage

### ISSUE THREAD

**Issue by flowhorn** [fzyzcjy/flutter_rust_bridge#2237]
### Describe the bug

In src/dart_opaque/_web.dart the dart:js_util package is used for the allowInterop Function. This prevents flutter from building using dart2wasm. As other parts of the app were already adjusted to js_interop, I wanted to notify you about this.

According to the docs, this should no longer be necessary and can be replaced by a .toJS Function (https://dart.dev/interop/js-interop/past-js-interop#dart-js_util). As I am not so confident in checking whether this directly works, I didn't directly created a PR (I can file a PR if this is desired)

Also it might be useful to increase the web package from ^0.5.1 to ">=0.5.1 <2.0.0" or even bump it to "1.0.0"

### Steps to reproduce

Run: flutter build web --wasm.

### Logs

```shell
../../../.pub-cache/hosted/pub.dev/flutter_rust_bridge-2.2.0/lib/src/dart_opaque/_web.dart:1:1: Error: JS interop library 'dart:js_util' can't be imported
when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'dart:js_util';
```

### Version of `flutter_rust_bridge_codegen`

2.2.0

**Comment by fzyzcjy** [comment]
> According to the docs, this should no longer be necessary and can be replaced by a .toJS Function ([dart.dev/interop/js-interop/past-js-interop#dart-js_util](https://dart.dev/interop/js-interop/past-js-interop#dart-js_util)). As I am not so confident in checking whether this directly works

No worries: just change that one line, and make a PR. The CI will check each and every thing!

> I can file a PR if this is desired

Looking forward to your PR! Alternatively I can do it in the next batch, but since this looks like a good-first-issue I will not immediate do it.

> Also it might be useful to increase the web package from ^0.5.1 to ">=0.5.1 <2.0.0" or even bump it to "1.0.0"

Looks reasonable, again feel free to PR

**Comment by flowhorn** [comment]
Thank you, I tried it but apparently my solution won't work,
The reason is the following:
 Error: `Function.toJS` requires a statically known function type, but Type 'Function' is not a precise function type, e.g., `void Function()`.
 - 'Function' is from 'dart:core'.
Insert an explicit cast to the expected function type.
    return (raw as Function).toJS;
Unfortunately I have no idea right now how we should no the expected function type (for what exactly this is used)

**Comment by fzyzcjy** [comment]
Hmm, then it seems nontrivial to implement encoding of DartOpaque, because it is Dart dynamic and users can indeed pass anything at runtime.

One quick hack is to temporarily disable this in wasm (by conditional compiling - currently the native and web has two different files, and we just simply introduce a third file when wasm), until someone needs to use it and we can discuss the specific use case.

**Comment by CJBuchel** [comment]
Is there an update on this? or any future plans?

With the newer flutter 3.24 release I was hoping to try and use wasm as my main compiling target for flutter. But FRB causes build errors.

**Comment by fzyzcjy** [comment]
Yes, I will work on it soon (hopefully within a week)
