### ISSUE TITLE
Logs not showing no matter the macro invocation

### ISSUE THREAD

**Issue by zhpixel517** [fzyzcjy/flutter_rust_bridge#2243]
### Describe the bug

I'm trying to get some logs to show up in the console when I run my app. I have tried calling `println!`, `debug!`, `info!` and `warn!`, and no matter which I call, none of the messages I try to print show up. 

### Steps to reproduce

Create a new project, and make a function called `test_logs()` and try this:

```rust
 debug!("Called debug");
 println!("Called println");
 info!("called info");
 warn!("called warn");
 ```    
 run the generate command and call this function immediately, inside `initState()`, perhaps. 
 
 and the output looks like this for me:
 ```
 Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 27J95Y9584
Xcode build done.                                           28.4s
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
Connecting to VM Service at ws://127.0.0.1:61019/Qt697_cX2HA=/ws

```
... nothing.  I verified that the `flutter_rust_bridge::setup_default_user_utils()` was present. I also tried manually configuring this following example 2 in the [logging doc](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging) to no success either, and made sure to add the correct bundle ID for ios as well. 

Where am I going wrong here? 

### Logs

```shell
(logs would be too long to include. there are no errors when running the codegen)
```

**Comment by dikatok** [comment]
@fzyzcjy is this related to https://github.com/fzyzcjy/flutter_rust_bridge/discussions/2240?

**Comment by zhpixel517** [comment]
For extra context, this is my Cargo.toml:
```
[package]
name = "rust_lib_flutter_rust_test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
android_logger = "0.14.1"
cpal = "0.15.3"
# opus_sys = { path = "opus_sys" }
opus = {path = "../../../RustPlayground/opus-rs"}
# oboe = { version = "0.4", features = [ "java-interface", "shared-stdcxx" ] }
flutter_rust_bridge = "=2.1.0"
jni = "0.21.1"
log = "0.4.22"
ndk-context = "0.1.1"
rtcp = "0.11.0"
rtp-rs = "0.6.0"
rtrb = "0.3.1"
socket2 = "0.5.7"

[target.'cfg(any(target_os = "ios"))'.dependencies]
oslog = "0.2.0"
```

**Comment by fzyzcjy** [comment]
@dikatok I think it is possible!

**Comment by fzyzcjy** [comment]
> I also tried manually configuring this following example 2 in the [logging doc](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging) to no success either

Hmm, maybe try the underlying mechanism of that logging helper, i.e. call low-level things to directly log to system and see whether it works. Also maybe ask/discuss on the related crates (oslog for example), and/or rust forum, since it looks like a general Rust question "why logging does not work" and may not be related to frb core.

**Comment by wxitcode** [comment]
[Approach 1: Use the default one](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging#approach-1-use-the-default-one)

Setps:

1. add log feature as blow
2. init log
3. for ios (oslog), you can view the log with **Instruments** or **Console** App on macOS;
    for macos (oslog), same as ios. **version 2.2.0 only for ios, so just wait for new version release.**;
    for android (android_logger), you can view with `adb logcat`

``` toml
[dependencies]
flutter_rust_bridge = { version = "=2.2.0", features = ["log"] }
log = "0.4.22"
```

``` rust
#[flutter_rust_bridge::frb(init)]
pub fn init_app() {
    // Default utilities - feel free to customize
    flutter_rust_bridge::setup_default_user_utils();
}
```

View all logs in one place. just try other Approach, such as
[Example 4: Send Rust logs to Dart](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging#example-4-send-rust-logs-to-dart)
[Example 5: A step-by-step guide to send Rust logs to Dart](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging#example-5-a-step-by-step-guide-to-send-rust-logs-to-dart)

**Comment by dikatok** [comment]
> [Approach 1: Use the default one](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging#approach-1-use-the-default-one)
> 
> Setps:
> 
> 1. add log feature as below
> 2. init log
> 3. for ios (oslog), you can view the log with **Instruments** or **Console** App on macOS;
>    for macos (oslog), same as ios. **version 2.2.0 only for ios, so just wait for new version release.**;
>    for android (android_logger), you can view with `adb logcat`
> 
> ```toml
> [dependencies]
> flutter_rust_bridge = { version = "=2.2.0", features = ["log"] }
> log = "0.4.22"
> ```
> 
> ```rust
> #[flutter_rust_bridge::frb(init)]
> pub fn init_app() {
>     // Default utilities - feel free to customize
>     flutter_rust_bridge::setup_default_user_utils();
> }
> ```
> 
> View all logs in one place. just try other Approach, such as [Example 4: Send Rust logs to Dart](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging#example-4-send-rust-logs-to-dart) [Example 5: A step-by-step guide to send Rust logs to Dart](https://cjycode.com/flutter_rust_bridge/guides/how-to/logging#example-5-a-step-by-step-guide-to-send-rust-logs-to-dart)

Are the logs emitted by rust layer not exposed to flutter debug console by default?

**Comment by dikatok** [comment]
I created new app using `flutter_rust_bridge_codegen create my_app`, added log macros `warn`, `info`, `error`, none are emitted in either flutter debug console or adb logcat. 😢

**Comment by fzyzcjy** [comment]
I still guess it is probably an issue with the specific logging library, instead of a frb (core) issue. So asking/searching there may help.

**Comment by wxitcode** [comment]
@dikatok 
> I created new app using flutter_rust_bridge_codegen create my_app, added log macros warn, info, error, none are emitted in either flutter debug console or adb logcat. 😢

Did you follow the steps above?  
You should enable log feature `flutter_rust_bridge = { version = "=2.2.0", features = ["log"] }`

For Android
Note: adb logcat is just used for Android logs and even you can see the log like this `I/rust_lib_xxx::xx..(pid number): hello world` in the console, When you debug android.

Currently frb v2.2.0, the default utils only for Android and iOS, you can customize for support other platforms.

**Comment by zhpixel517** [comment]
enabling the `log` feature allows `debug!`, `info!`, and `warn!` to show, but not `println!`

**Comment by fzyzcjy** [comment]
`println` will not show iirc because it is a builtin thing and cannot be very easily configured.
