### ISSUE TITLE
allow frb mirror on concrete generic enum

### ISSUE THREAD

**Issue by acul009** [fzyzcjy/flutter_rust_bridge#2252]
**Is your feature request related to a problem? Please describe.**
I have a struct like this:

```rust
pub enum RemoteLiveData<T> {
    Unavailable,
    Pending,
    Ready(T),
}
```

I can also already define methods and it works fine:
```rust
#[frb(external)]
impl RemoteLiveData<RealtimeStatus> {
    pub fn is_pending(&self) -> bool {}
}
```

obviously frb can't yet handle full generics by itself, but I'd like to propose an intermediate.

**Describe the solution you'd like**
When frb encounters a return value like `RemoteLiveData<RealtimeStatus>` it monomorphisizes (what a freaking word) that type into `RemoteLiveDataRealtimeStatus` which is totaly fine and works great.

All I'd like to do is define a mirror for the concrete type of generic enum:

```rust
#[frb(non_opaque, mirror(RemoteLiveData<RealtimeStatus>))]
pub enum _RemoteLiveDataRealtimeStatus {
    Unavailable,
    Pending,
    Ready(RealtimeStatus),
}
```

Unfortunately this does not register as a mirrored type and just produces this comment:

```dart
// These types are ignored because they are not used by any `pub` functions:  `_RemoteLiveDataRealtimeStatus`
```

**Describe alternatives you've considered**
I've tried experimenting with wrappers and additional helper functions, but that get's out of hand quickly.
These mirrors on the other hand might be easy to generate using macros.

I've tried digging through the generator codebase to find which parts to change, but that seems to be way beyond my skill level at the moment.

**Comment by fzyzcjy** [comment]
Totally agree, that would be a useful feature. Given the internal implementation, it may be convenient to implement the enum feature at the same time (and then this will be auto done). I may work on it later but cannot guarantee the time, since this is a new nontrivial feature.

**Comment by nightscape** [comment]
I've started working on generic enums with type alias in https://github.com/fzyzcjy/flutter_rust_bridge/pull/2933
The idea is to be able to do something like this:

```rust
pub enum Change<T> {
    Created { data: T },
    Updated { id: String, data: T },
    Deleted { id: String },
}

pub type StringChange = Change<String>;
pub type MapChange = Change<HashMap<String, String>>;
```
