### ISSUE TITLE
Generation of procedures with positional parameters

### ISSUE THREAD

**Issue by Larpoux** [fzyzcjy/flutter_rust_bridge#2255]
Is there a way to generate by default (globally) interface with positional parameters for the dart functions and not keyword parameters?

**Comment by fzyzcjy** [comment]
Currently there hasn't, but feel free to PR (which may not be super hard: just change `f({A b})` to `f(A b)`, or I will try to squeeze some time to implement it!

**Comment by Larpoux** [comment]
Yes, I need this feature. It is too bad that rust is so hard to be mastered for me.
I am going to see what I can do. I will learn a lot if I find time to look to frb code.

**Comment by fzyzcjy** [comment]
Take your time! This feature does not need to master rust, just treat Rust as simple scripting language is enough (because we do not need to handle complex lifetime etc in the code generator). If you find any issue just ping me.

**Comment by Larpoux** [comment]
At the end, this feature would not be a solution for me : I need to generate some functions with positional parameters and some other with keyword parameters.
For this reason and for some other reasons that I don’t want to elaborate, I decided to implement a simple wrapper above the library.

**Comment by fzyzcjy** [comment]
Ah I see. Feel free to discuss if you think frb can do anything!
