### ISSUE TITLE
Question on a `pub` fn/type  inside a `pub(crate)` module

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2256]
Frb v2.2, win10.

Suppose the api module `rust\src\api\mod.rs` is this:
```rust
//
// Do not put code in `mod.rs`, but put in e.g. `simple.rs`.
//
pub(crate) mod log;
pub mod api;
```
and there is struct or fn with prefix `pub(crate)` in `log`, then everything is fine, this `log`module is transparent to dart and frb.
But if the struct or fn is prefixed with `pub`, then it is exposed to frb---But should it be visible or not?

I realize this issue when I lint fix rust code with this cmd:
```
cargo clippy --fix --allow-dirty --allow-staged --allow-no-vcs --all-targets -- -W clippy::all -W clippy::pedantic -W clippy::nursery -A clippy::missing_docs_in_private_items -A clippy::missing_inline_in_public_items -A clippy::redundant_pub_crate -A clippy::module_name_repetitions -A clippy::must_use_candidate ;
```
with removing `-A clippy::redundant_pub_crate`, after when rust automatically change my`pub(crate) fn` into `pub fn` in a `pub(crate)` module(`log` in this case).

So officially, Rust team thinks that anything inside a `pub(crate)` module would NOT surpass its visibility over its parent module---that is why `pub` is already enough inside a `pub(crate)` module. I wonder if frb should make the logic consistent to rust, though I am ok with the current logic.

**Comment by fzyzcjy** [comment]
Yes that looks reasonable. IIRC, frb does not strictly follow the semantics of `pub` of Rust, because the rules and all edge cases are somehow nontrivial. And fixing it will cause a breaking change (!), so we may consider this improvement in 3.0 version.

**Comment by dbsxdbsx** [comment]
Ok, then just leave it as it is now. Feel free to close.

**Comment by fzyzcjy** [comment]
Ok, no problem
