### ISSUE TITLE
rust calls dart 

### ISSUE THREAD

**Issue by liuxingyubm** [fzyzcjy/flutter_rust_bridge#2270]
### Describe the bug

I tested it with methods in the flutter_rust_bridge instance, but the app startup kept getting stuck and couldn't proceed to the next step

### Steps to reproduce

<img width="1296" alt="WeChat8a999badbdb2f77eb0711fba5f4ac04e" src="https://github.com/user-attachments/assets/bbaa558a-e411-40c4-a989-08685bc11b18">
这是rust实例
<img width="904" alt="WeChat1f47f6b0ffd8f38fe7e69ebe4b72a117" src="https://github.com/user-attachments/assets/9fd388c0-bc8c-46a7-9641-fe65ee07fcfb">
在dart里调用

### Logs

```shell
无
```

**Comment by fzyzcjy** [comment]
👀 what happened
