### ISSUE TITLE
Implement trait deriving for RustAutoOpaque (Clone, Debug, PartialEq, Eq)

### ISSUE THREAD

**Issue by patmuk** [fzyzcjy/flutter_rust_bridge#2272]
### Describe the bug

```
#[derive(Debug, PartialEq, Eq, Default, Clone)]
pub struct MyStruct {
    pub content: RustAutoOpaque<String>,
}
```
leads to the compiler error
```
error[E0277]: `RustAutoOpaqueBase<String, MoiArc<RustAutoOpaqueInner<String>>>` doesn't implement `std::fmt::Debug`
 --> app_core/src/domain/example.rs:5:5
  |
3 | #[derive(Debug, PartialEq, Eq, Default, Clone)]
  |          ----- in this derive macro expansion
4 | pub struct MyStruct {
5 |     pub content: RustAutoOpaque<String>,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `RustAutoOpaqueBase<String, MoiArc<RustAutoOpaqueInner<String>>>` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
  |
  = note: the full name for the type has been written to '/Users/patmuk/code/own/sherry/examples/flutter-rust-bridge_crux_style/target/debug/deps/app_core-7c266d89184dc8da.long-type-9818281645063396442.txt'
  = note: consider using `--verbose` to print the full type name to the console
  = help: the trait `std::fmt::Debug` is not implemented for `RustAutoOpaqueBase<String, MoiArc<RustAutoOpaqueInner<String>>>`, which is required by `&flutter_rust_bridge::for_generated::RustAutoOpaqueBase<std::string::String, application::bridge::frb_generated::MoiArc<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<std::string::String>>>: std::fmt::Debug`
  = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Steps to reproduce

1. copy the code
2. run frb generate
3. see cargo's error message

### Logs

```shell
see the error in the description
```

### Expected behavior

RustAutoOpaque goes out of the way and uses the underlying type's derived traits.

### Additional context

A workaround is to implement the traits on the wrapped type, for example
```
struct MyStruct {
   content: RustAutoOpaque<String>
}
```
needs to wrap the string, so we can implement a trait
```
struct content {
  inner: String,
}

struct MyStruct {
   content: RustAutoOpaque<Content>
}
```
and then implement the missing trait
```
    fn clone(&self) -> Self {
        panic!("I should not be called");
    }
```
While Clone is needed (even if not called, see https://github.com/fzyzcjy/flutter_rust_bridge/discussions/2244#discussioncomment-10538600), the other traits are more of a "nice to have".

It should be as easy as 
```
impl Display for RustAutoOpaque<T> {
   fn display(&self) -> &str {
     self.inner.display
  }
}
```
though the devil might be in the details :)

Having 
```
impl Clone for RustAutoOpaque{
    fn clone(&self) -> Self {
        panic!("I should not be called");
    }
}
```
might be sufficient for now :)

**Comment by fzyzcjy** [comment]
I guess there are several separated issues here

1. Add `#[derive(Debug, PartialEq, Eq)] struct RustAutoOpaque` should solve the first 3
2. Using my suggestion in https://github.com/fzyzcjy/flutter_rust_bridge/discussions/2244#discussioncomment-10547281 should solve the Clone thing

Since this looks not hard (several lines of code), again, feel free to PR! Alternatively I may work on it later if you explicitly not do it :)

**Comment by fzyzcjy** [comment]
Just a double check: Do you want to have fun PR for this? If so I will leave it to you, if not I will make a small PR ;)

**Comment by patmuk** [comment]
> Just a double check: Do you want to have fun PR for this? If so I will leave it to you, if not I will make a small TR ;)

Thanks for asking :) I was about to approach it - but then wanted to get the other PRs done first ...
So, please go ahead and make that PR - I will look into it and lean :)

I am taking care of the logging now (investigating `env_logger`), PR this, write up how to use nix and PR that.

I guess you are done by then with this PR, so please go ahead! Thanks!

**Comment by fzyzcjy** [comment]
Btw, `PartialEq, Eq` may not be implementable, since RustAutoOpaque has a RwLock inside, and https://doc.rust-lang.org/stable/std/sync/struct.RwLock.html does not have it (since that would require a lock)

**Comment by patmuk** [comment]
> Btw, `PartialEq, Eq` may not be implementable, since RustAutoOpaque has a RwLock inside, and https://doc.rust-lang.org/stable/std/sync/struct.RwLock.html does not have it (since that would require a lock)

Great that you already implemented it! Thanks!
Yes, that sounds reasonable ... I only needed it in tests for the `assert`- but actually a better test design is using getters of the inner fields, so `PartialEq, Eq` isn't necessary on RustAutoOpaque.
