### ISSUE TITLE
Publish flutter_rust_bridge_utils to pub.dev

### ISSUE THREAD

**Issue by Tienisto** [fzyzcjy/flutter_rust_bridge#2274]
**Is your feature request related to a problem? Please describe.**
I cannot publish a Dart-only package on pub.dev because `flutter_rust_bridge_utils` itself is not published yet.

**Describe the solution you'd like**
Publish the package on pub.dev

**Describe alternatives you've considered**
None.

**Additional context**
This is just an issue to easier track the process. If you feel that this is too bleeding edge, then feel free to wait until native assets are stabilized in Dart.

**Comment by fzyzcjy** [comment]
Firstly, I wonder which exact part of flutter_rust_bridge_utils are you using? By knowing this I could give more specific advice (e.g. copy-paste it to your project, or I should publish it, etc)

**Comment by Tienisto** [comment]
I think to enable Dart-only support, we need to add a `build.dart` file.

According to https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/dart_minimal/build.dart
FRB provides `simpleBuild` that abstracts of the complexity.

`simpleBuild` itself doesn't seem to do too much, so I could theoretically copy-paste it

**Comment by fzyzcjy** [comment]
I guess copy-paste may be a good way, since the utils are mainly ad-hoc scripts that are useful mainly inside frb, and has no enough encapsulation etc.

However, a even better way may be using: https://pub.dev/packages/native_toolchain_rust (which did not exist at the time when I wrote `simpleBuild`)

**Comment by fzyzcjy** [comment]
Close since seems to be solved, but feel free to reopen if you have anything to discuss!
