### ISSUE TITLE
Allow non-recursive import in rust_input

### ISSUE THREAD

**Issue by aran** [fzyzcjy/flutter_rust_bridge#2277]
**Is your feature request related to a problem? Please describe.**

If I do `rust_input: foo::bar`, FRB runs on `foo::bar`, but also on `foo::bar::baz` if `baz` is a `pub mod`. 

**Describe the solution you'd like**
Maybe something like: 

`rust_input: foo::bar` causes scanning and generation just on `foo::bar`
`rust_input: foo::bar::*` causes scanning and generation on `foo::bar::baz` and others inline with the Rust semantics of `::*`

**Describe alternatives you've considered**

N/A

**Additional context**
N/A

**Comment by fzyzcjy** [comment]
Currently, you can `/// flutter_rust_bridge: ignore` on the `pub mod baz` line.

Also feel free to PR for this new feature!

**Comment by aran** [comment]
That's a good point, this would have to be a breaking change.
