### ISSUE TITLE
How to build ios binary small like in other platforms?

### ISSUE THREAD

**Issue by vimaxwell** [fzyzcjy/flutter_rust_bridge#2287]
I'm trying to build a wrapper for `similar` library for flutter. I also config build tool for it like your document. Everything work well but the binary in ios is larger (>16MB) than other platforms (<1M). Can you help me what am I doing wrong? Thanks

This is my repo
https://github.com/CoryApp/similar_flutter

**Comment by fzyzcjy** [comment]
Firstly, what is your method to check ios binary size? IIRC there are many sizes, some are not the ones that will be downloaded (s.t. we do not need to worry)

**Comment by fzyzcjy** [comment]
The `.a` file is static lib, which means, even if it is 100MB, if you only use 1MB of it in your app, it will only make your app +1MB size. On the other hand, `.so` file is dynamic lib, so if it is 100MB then your app size +100MB.

(The real case is a bit more complex, you also need to consider compression, so a 1MB .so file may only make your apk about 0.3MB larger, for example)

**Comment by fzyzcjy** [comment]
You are welcome!
