### ISSUE TITLE
Struct field attribute to skip field

### ISSUE THREAD

**Issue by raphaelrobert** [fzyzcjy/flutter_rust_bridge#230]
**Is your feature request related to a problem? Please describe.**
Currently all fields of a struct are parsed. This means that the field type needs to be declared in the same file. This is problematic when referencing types that are declared in other files. It is impossible to use structs as opaque pointers to wrap other (non-visible) structs.

**Describe the solution you'd like**
It would be great to have the following syntax:

```rust
use crate::some_mod::CustomType;

pub struct WorksInRustAndDart {
    a_string: String,         // Visible in Dart
    #[skip_field]
    hidden_field: CustomType, // Not visible in Dart
}
```

**Describe alternatives you've considered**
Other alternatives would involve unsafe pointer manipulation, let's not go there.

**Additional context**

**Comment by raphaelrobert** [comment]
Alternatively, this could be implemented by looking at the visibility of the fields (like it's done for the structs and the functions): Any field that is not marked as `pub` will be skipped.
This would be far easier to implement, but comes at the cost of being a breaking change.

**Comment by Desdaemon** [comment]
I think this would be a nice feature to have. I'm wondering how this would work for structs in parameter positions? Should we enforce that the field's type implement `Default` or raise an error if a function receiving that struct as a parameter is detected?

**Comment by raphaelrobert** [comment]
Good point. My intention was to use the struct as an opaque pointer, but obviously that means it can only be created in Rust, not on the Dart side. Maybe this would require a completely different mechanism then.

**Comment by fzyzcjy** [comment]
Sounds interesting. Notice that in your example, if you pass WorksInRustAndDart from Rust to Dart (i.e. return value), Dart will never receive the data of `hidden_field`. I am not sure whether this is what you need.

> looking at the visibility of the fields (like it's done for the structs and the functions): Any field that is not marked as pub will be skipped. This would be far easier to implement, but comes at the cost of being a breaking change.

No it is not a breaking change. Currently everything should be `pub` (or at least `pub(crate)`, otherwise the generated Rust code will not compile, which is enforced by the compiler.

Feel free to make a PR! ;)

**Comment by raphaelrobert** [comment]
This won't be needed if #243 gets implemented.

**Comment by Desdaemon** [comment]
#260 was implemented recently, so this might still have some relevance.
