### ISSUE TITLE
Missing "File" module for the generated "frb_generated.rs"

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#2310]
win10, frb 2.4.0

For a certain frb project, I found that the generated `frb_generated.rs` needs module `std::file`(or maybe the tokio version),

It is trivial to fix it by import `use std::fs::File;`, but annoying each time to do so after doing the generating task.

The screenshot
![image](https://github.com/user-attachments/assets/de5f908a-5fbf-42d5-87a7-fc0db16129d2)

I don't know when the `File` is needed, since I didn't directly use `File` module for my rust API,  
the whole content of `frb_generated.rs`  is this:
[gen.log](https://github.com/user-attachments/files/17107386/gen.log)

**Comment by fzyzcjy** [comment]
You can `pub use std::fs::File` in your code that uses File (instead of `use std::fs::File`) and see whether it works. Alternatively, you can use the preamable feature.

**Comment by dbsxdbsx** [comment]
I did do `pub use std::fs::File` in `lib.rs`, but seems no effect, meanwhile I just have no idea where I use the module; so  I take the 2ed way, thanks.

**Comment by fzyzcjy** [comment]
You are welcome!

It is not in lib.rs, but in the position where you use it (e.g. in a.rs you use std::fs::File, then add "pub" to it).
