### ISSUE TITLE
v2.4.0 runs `dart fix` thus modifies codes not generated by frb

### ISSUE THREAD

**Issue by lbhfuture** [fzyzcjy/flutter_rust_bridge#2316]
### Describe the bug

I run `flutter_rust_bridge_codegen integrate` to add frb to my existed project, and it modified my codes which is not generated by frb.

The console shows:
```
[2024-09-26T06:14:49.361Z INFO .../flutter_rust_bridge_codegen-2.4.0/src/library/integration/integrator.rs:79] Apply Dart fixes
[2024-09-26T06:15:00.092Z INFO .../flutter_rust_bridge_codegen-2.4.0/src/library/integration/integrator.rs:82] Format Dart code
```

The formatter above should only modify dart code in lib/src/rust, but it seems not works well, and my `flutter_rust_bridge.yaml` is below:
```
rust_input: crate::api
rust_root: rust/
dart_output: lib/src/rust
enable_lifetime: true
```

frb version is 2.4.0

### Steps to reproduce

1. Run `flutter_rust_bridge_codegen integrate` to add frb to a existed project.

### Logs

```shell
[2024-09-26T06:14:49.361Z INFO .../flutter_rust_bridge_codegen-2.4.0/src/library/integration/integrator.rs:79] Apply Dart fixes
[2024-09-26T06:15:00.092Z INFO .../flutter_rust_bridge_codegen-2.4.0/src/library/integration/integrator.rs:82] Format Dart code
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

2.4.0

**Comment by fzyzcjy** [comment]
1. Firstly, you can go back to older 2.x version without the "auto run dart fix" feature, before this is handled
2. cc @AlexV525 who introduced the "auto run `dart fix`" feature (which is quite useful in some scenarios) - maybe we should at least make a bool flag for this feature?

**Comment by AlexV525** [comment]
The tricky part is that `dart fix` does not support for fixing a single file. We can support opt-out of the feature first, then consider further support with handling a specific batch of files.

**Comment by fzyzcjy** [comment]
Totally agree!

**Comment by AlexV525** [comment]
Oh, I just ran `dart fix --apply ./dir_name` and it works.

**Comment by AlexV525** [comment]
We can only apply to `dart_output`, don't we?

**Comment by fzyzcjy** [comment]
Yes and no. Yes because usually that folder should only be touched by frb and not but normal users; no because theoretically we did not forbid users from adding any extra files there...

**Comment by AlexV525** [comment]
> no because theoretically we did not forbid users from adding any extra files there...

Fair enough. We can improve our guides and warnings to tell users not to put extra files into the output path as the best practice.

**Comment by fzyzcjy** [comment]
Related: https://github.com/fzyzcjy/flutter_rust_bridge/discussions/2328

(manually add this comment since github does not auto backlink between discussion and issues)

**Comment by Ferry-200** [comment]
Just upgraded from flutter_rust_bridge 2.0.0 to 2.4.0 and this issue surprised me lol
