### ISSUE TITLE
`rust_features` unknown field

### ISSUE THREAD

**Issue by codercengiz** [fzyzcjy/flutter_rust_bridge#2324]
### Describe the bug

According to documentation, we can use `rust_features: xyz` in flutter_rust_bridge.yaml, 
https://cjycode.com/flutter_rust_bridge/guides/custom/codegen/full-list#flutter_rust_bridge_codegen-generate
but it gives error.

```
❯ flutter_rust_bridge_codegen generate
Error: Could not parse flutter_rust_bridge.yaml

Caused by:
    unknown field `rust_features`, expected one of `base_dir`, `rust_input`, `dart_output`, `c_output`, `duplicated_c_output`, `rust_root`, `rust_output`, `dart_entrypoint_class_name`, `dart_format_line_length`, `dart_preamble`, `rust_preamble`, `dart_enums_style`, `add_mod_to_lib`, `llvm_path`, `llvm_compiler_opts`, `dart_root`, `build_runner`, `extra_headers`, `web`, `deps_check`, `dart3`, `full_dep`, `local`, `default_external_library_loader_web_prefix`, `dart_type_rename`, `enable_lifetime`, `type_64bit_int`, `default_dart_async`, `stop_on_error`, `dump`, `dump_all` at line 4 column 1
```

And I checked the doc of crate codegen
https://docs.rs/flutter_rust_bridge_codegen/latest/lib_flutter_rust_bridge_codegen/codegen/struct.Config.html
There is no the parameter `rust_features`

I think the help files are not updated.

How can I set the rust feature? 

### Steps to reproduce

Hint: A simple way to reproduce is to clone and modify the https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/dart_minimal example package according to your needs.
1. ...
2. ...
3. ...

### Logs

```shell
❯ flutter_rust_bridge_codegen generate
Error: Could not parse flutter_rust_bridge.yaml

Caused by:
    unknown field `rust_features`, expected one of `base_dir`, `rust_input`, `dart_output`, `c_output`, `duplicated_c_output`, `rust_root`, `rust_output`, `dart_entrypoint_class_name`, `dart_format_line_length`, `dart_preamble`, `rust_preamble`, `dart_enums_style`, `add_mod_to_lib`, `llvm_path`, `llvm_compiler_opts`, `dart_root`, `build_runner`, `extra_headers`, `web`, `deps_check`, `dart3`, `full_dep`, `local`, `default_external_library_loader_web_prefix`, `dart_type_rename`, `enable_lifetime`, `type_64bit_int`, `default_dart_async`, `stop_on_error`, `dump`, `dump_all` at line 4 column 1
```

**Comment by fzyzcjy** [comment]
Firstly, could you please show `flutter_rust_bridge_codegen --version` to check whether it is the latest version?

**Comment by codercengiz** [comment]
the last version
❯ flutter_rust_bridge_codegen --version
flutter_rust_bridge_codegen 2.4.0

**Comment by fzyzcjy** [comment]
That's weird. We even have it in tests: https://github.com/fzyzcjy/flutter_rust_bridge/blob/4f5cf68f56ed56df62264227d81891744c356403/frb_example/pure_dart/flutter_rust_bridge.yaml#L22

**Comment by codercengiz** [comment]
Hmm, I saw
Sorry my bad, I updated it to master branch, it works now.

**Comment by fzyzcjy** [comment]
Happy to see it works!
