### ISSUE TITLE
rust_lib_crate dependencies framework has been removed at rebuild

### ISSUE THREAD

**Issue by niuhuan** [fzyzcjy/flutter_rust_bridge#2330]
**Is your feature request related to a problem? Please describe.**

`I hope to keep the dependencies`

I often fail to compile recently, The github actions platform never compiles pass.  Like this https://github.com/fzyzcjy/flutter_rust_bridge/issues/2267

This was my previous solution https://github.com/fzyzcjy/flutter_rust_bridge/issues/1790

I had dependency reqwest ,

Until I used flutter clean, I found the problem.

`rust_lib_crate` dependencies framework has been removed at rebuild.  every time `flutter clean` or `rm build/macos`

![image](https://github.com/user-attachments/assets/a19943dc-ca3e-4d44-bd51-cd9e4718b0c8)

**Describe the solution you'd like / Describe alternatives you've considered**
I'm sorry that my macOS skills are very poor, I don't know how to solve this problem. I believe that maybe using sed, backing up some files, or other methods can temporarily solve my problem.

**Comment by fzyzcjy** [comment]
Hmm, this seems to be related to Cargokit instead of frb core, since frb uses it to compile Rust within Flutter programs.

**Comment by niuhuan** [comment]
When flutter_rust_bridge call `Cargokit`? Give me some ideas, please.

**Comment by niuhuan** [comment]
If there is a solution in the future I will leave a message here
