### ISSUE TITLE
`build.rs` ignores the `rust_release` parameter 

### ISSUE THREAD

**Issue by codercengiz** [fzyzcjy/flutter_rust_bridge#2338]
### Describe the bug

If we want to use `rust_release` parameter with `build.rs` ,
`cargo build`  generates without considering frb attributes. For example, even if you specify `#[cfg_attr(feature = "mobile",frb(sync))]`, it generates async function. However, `flutter_rust_bridge_codegen generate` generates as expected.

The two method are generating different codes.

### Steps to reproduce

1. Download the simple app https://github.com/codercengiz/frb_test/
2. Go to rust folder and run `cargo build` then you will see on generated file `lib/src/rust/api/simple.dart` 
```dart
Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);
```
3. To compare this generated code with the generated codes by codegen 
Install the `codegen` from git on master branch `cargo install --git https://github.com/fzyzcjy/flutter_rust_bridge --branch master flutter_rust_bridge_codegen`
 4. run `flutter_rust_bridge_codegen generate`, then you will see on generated file `lib/src/rust/api/simple.dart` 
```dart
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);
```

### Logs

```shell
❯ flutter_rust_bridge_codegen --version
flutter_rust_bridge_codegen 2.4.0
```

**Comment by fzyzcjy** [comment]
Yes, `build.rs` currently has some limitations such as not able to parse macros to avoid deadlock (you know, when build.rs is executed, you are already running a Rust build, so if you further call `cargo expand` you will trigger a nested Rust build). Thus I suggest to use the normal `generate` command.

**Comment by codercengiz** [comment]
Ok, I see
