### ISSUE TITLE
Repostory name is confusing

### ISSUE THREAD

**Issue by mrgzi** [fzyzcjy/flutter_rust_bridge#2342]
Its pretty hard to understand how to use it with pure dart. Perhaps the repo name should be dart_rust_bridge and more focus on using direct with dart and also flutter integration should be seperated?

**Comment by fzyzcjy** [comment]
> Its pretty hard to understand how to use it with pure dart

Could you please discuss a bit more about what is hard to understand, maybe we can update doc etc to solve that

> Perhaps the repo name should be dart_rust_bridge and more focus on using direct with dart and also flutter integration should be seperated?

But we should not change names ;)

**Comment by fzyzcjy** [comment]
Close since inactivity, but feel free to reopen if you have any questions!
