### ISSUE TITLE
The method 'initMockImpl' isn't defined for the class 'RustLib' after Upgrade from 2.1.0 to 2.5.0

### ISSUE THREAD

**Issue by mitissen** [fzyzcjy/flutter_rust_bridge#2362]
Hello, i'am upgraded with

`cargo install flutter_rust_bridge_codegen && flutter_rust_bridge_codegen generate`

from Version 2.1.0 to 2.5.0

and suddenly getting:

```bash
Failed to build iOS app
Error (Xcode): modules/my_flutter_rust_lib/lib/src/rust/frb_generated.dart:39:14: Error: The method 'initMockImpl' isn't defined for the class 'RustLib'.
```

I checked the generated code and everything looks fine. 
The 'initMockImpl' exists also

Do i need to clean something in the ios Project? (Tried delete and recreate pods)

**Comment by fzyzcjy** [comment]
Hmm could you please firstly `flutter pub get` to upgrade your dependencies and see whether it works

**Comment by mitissen** [comment]
Now it works!  
Thank you @fzyzcjy  for your wonderful library and your quick help!
