### ISSUE TITLE
[experimental-feature] Return custom Rust errors

### ISSUE THREAD

**Issue by oo-work** [fzyzcjy/flutter_rust_bridge#2369]
Now there is an Error in a third-party crate, which may be like this.
 ```rust
#[derive(Debug)]
pub enum CustomError {
    ConnectionError(Box<dyn std::error::Error + Send + Sync>),
    Io(std::io::Error),
    Other(Box<dyn std::error::Error + Send + Sync>),
    EOF,
}
```

flutter_rust_bridge.yaml
```yaml
rust_input: crate::api,crate-name::error
```

When returning a `Result<(), CustomError)`, Dart uses print(e.runtimeType); to print out `CustomErrorImpl`.

```rust
pub fn foo() -> Result<(), CustomError>{
    ...
}
```

```dart
try {
    await foo();
} catch(e) {
    print(e.runtimeType);
}

```

I want it to be a CustomError and have access to the type in the enum and call toString().

But dart generates such code, and the Exception type is not CustomError.
```dart
abstract class CustomError implements RustOpaqueInterface {
}

```

**Comment by fzyzcjy** [comment]
https://cjycode.com/flutter_rust_bridge/guides/third-party/manual/external-types#example Seems that `mirror` is:

> Enums with struct variants are not yet supported

A workaround may be, create your own enum in first party package (and convert it between the 3rd party one).

**Comment by oo-work** [comment]
I tried changing the enum to a normal struct and it working.

**Comment by fzyzcjy** [comment]
Happy to see that!

**Comment by fzyzcjy** [comment]
Close since this seems to be solved, but feel free to reopen if you have any questions!
