### ISSUE TITLE
Changing the flow from 1 to 2, what is wrong

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#2374]
```
lazy_static! {
    static ref SEND_TO_DART_LOGGER_STREAM_SINK: RwLock<Option<StreamSink<ResMsg>>> =
        RwLock::new(None);
}
fn cmd_msg(s: ResMsg) {
    if let Some(sink) = &*SEND_TO_DART_LOGGER_STREAM_SINK.read() {
        sink.add(s);
    }
}
pub fn create_msg(sink: StreamSink<ResMsg>) {
    let mut guard = SEND_TO_DART_LOGGER_STREAM_SINK.write();

    *guard = Some(sink);
}
```

this error originates in the macro `$crate::frb_generated_stream_sink` which comes from the expansion of the macro `flutter_rust_bridge::frb_generated_boilerplate` (in Nightly builds, run with -Z macro-backtrace for more info)
![image](https://github.com/user-attachments/assets/d2b0f96c-d50d-4bbe-8fa7-d4111b1cdc5a)

**Comment by fzyzcjy** [comment]
Hi, could you please check your `ResMsg` type? For example, if it is not of lifetime static, then it will not work, because stream items needs to live arbitrarily long.

**Comment by 107295472** [comment]
```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResMsg<'a> {
    pub percentage: f32,
    pub count: i32,
    pub message: &'a str,
    pub code: i32,
}
```

**Comment by 107295472** [comment]
![image](https://github.com/user-attachments/assets/b461966f-802c-4b0a-b152-2fef0fd89f58)

**Comment by fzyzcjy** [comment]
Happy to see it is solved (closed)!
