### ISSUE TITLE
How to remove these prompts

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#2378]
INFO C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\flutter_rust_bridge_codegen-2.5.1\src\library\codegen\parser\hir\flat\transformer\merge_duplicate_transformer\mod.rs:72] There are still multiple objects with same key after merging, thus randomly pick one. This is an issue only if the object is indeed used. (key="ActiveModel", objects={"name":"crate::system::entitys::alct_api_driver_new/ActiveModel","visibility":"Public","sources":["Normal"],"mirror":false}, {"name":"crate::system::entitys::alct_logs/ActiveModel","visibility":"Public","sources":["Normal"],"mirror":false}, {"name":"crate::system::entitys::cols_name/ActiveModel","visibility":"Public","sources":["Normal"],"mirror":false}, {"name":"crate::system::entitys::test/ActiveModel","visibility":"Public","sources":["Normal"],"mirror":false})

INFO C:\Users\Administrator\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\flutter_rust_bridge_codegen-2.5.1\src\library\codegen\parser\mir\parser\ty\lifetimeable.rs:52] 
To handle some types, `enable_lifetime: true` may need to be set. Please visit https://fzyzcjy.github.io/flutter_rust_bridge/guides/lifetimes for more details

**Comment by 107295472** [comment]
There is still a problem, flutter_rust_bridge_codegen generate, after the original file rs was modified, the generation had no effect. Finally, frb_generated.rs was deleted and regenerated to work

**Comment by 107295472** [comment]
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.

**Comment by fzyzcjy** [comment]
Since this issue is closed, I guess your question is solved. If not, feel free to reopen and ask!
