### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by MrCasCode** [fzyzcjy/flutter_rust_bridge#238]
**Is your feature request related to a problem? Please describe.**
Trying to generate an enum results in `thread 'main' panicked at 'parse_type failed for ty=EnumName'`

**Describe the solution you'd like**
Rusts enums are super powerful (and I would say impossible to fully support) but it would be nice to at least support the most basic enum types 

```
pub enum StartFrom {
    Beginning,
    End,
}
```

**Describe alternatives you've considered**
Passing Strings now is the workaround for this limitation

**Additional context**
-

**Comment by fzyzcjy** [comment]
Sounds reasonable! It is not hard to implement the proposed case: For example, we can encode enum into a integer, send it through ffi, and then decode integer back into a dart enum. If needed I can provide more hints.

Do not hesitate to make a PR and I am looking forward to it!
