### ISSUE TITLE
Slow performance when calling opaque function

### ISSUE THREAD

**Issue by Tienisto** [fzyzcjy/flutter_rust_bridge#2385]
**Is your feature request related to a problem? Please describe.**
I don't know if it's the nature of SSE or if it's specifically to opaque function calls, but calling opaque functions with binary data is very slow.

**Describe the solution you'd like**
Improve performance of calling opaque functions

**Describe alternatives you've considered**
Maybe use CST (mentioned in https://cjycode.com/flutter_rust_bridge/guides/miscellaneous/codec#comparison), but I could not find an annotation to change that.

**Additional context**
```rust
pub struct Dart2RustStreamSink {
    sender: mpsc::Sender<Vec<u8>>,
}

pub struct Dart2RustStreamReceiver {
    pub(crate) receiver: mpsc::Receiver<Vec<u8>>,
}

pub fn create_stream() -> (Dart2RustStreamSink, Dart2RustStreamReceiver) {
    let (sender, receiver) = mpsc::channel(16 * 1024); // 16KB buffer
    println!("create_stream");
    (
        Dart2RustStreamSink { sender },
        Dart2RustStreamReceiver { receiver },
    )
}

impl Dart2RustStreamSink {
    pub async fn add(&mut self, data: Vec<u8>) -> Result<(), RhttpError> {
        // This method still needs 100ms or more to complete from Dart side, even without calling mpsc

        // self.sender
        //     .send(data)
        //     .await
        //     .map_err(|_| RhttpError::RhttpUnknownError("Failed to send data".to_string()))
        Ok(())
    }

    pub async fn close(&mut self) -> Result<(), RhttpError> {
        self.sender
            .close()
            .await
            .map_err(|_| RhttpError::RhttpUnknownError("Failed to close stream".to_string()))
    }
}
```

**Comment by Tienisto** [comment]
After some debugging, I found out that the call of an opaque function itself is expensive, regardless of the payload.

Tried to remove the parameter, so no payload is needed. Still it takes very long to call the function.

```rust
pub async fn add(&mut self) -> Result<(), RhttpError> {
        // This method still needs 100ms or more to complete from Dart side.
        Ok(())
    }
```

**Comment by Tienisto** [comment]
My buffer implementation was causing the slowness.

**Comment by fzyzcjy** [comment]
Happy to see it is solved! If there are any questions just ping me :)
