### ISSUE TITLE
analyzer >=6.8.0 is incompatible with flutter from sdk.   but frb require analyzer 6.11.0

### ISSUE THREAD

**Issue by cryuhy** [fzyzcjy/flutter_rust_bridge#2408]
### Describe the bug

analyzer >=6.8.0 is incompatible with flutter from sdk.   but frb require analyzer 6.11.0

### Steps to reproduce

no

### Logs

```shell
no
```

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.6.1 23G93 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.79.1)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for chenrui. Ensure the device
      is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources
```

### Additional context

our flutter is newest version

**Comment by fzyzcjy** [comment]
Hi, could you please show your pubspec.yaml? I am confused why latest flutter does not support recent analyzer...

**Comment by fzyzcjy** [comment]
`flutter_rust_bridge: 2.0.0-dev.33`

Hmm, firstly could you please try latest frb and see whether it works?

**Comment by cryuhy** [comment]
ok thank you

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by fzyzcjy** [comment]
Close since this seems to be solved, but feel free to reopen if you find any problems!
