### ISSUE TITLE
Generate Box<Fn()> error

### ISSUE THREAD

**Issue by lbhfuture** [fzyzcjy/flutter_rust_bridge#2409]
### Describe the bug

1. Write Rust code with a Fn running in tokio::spawn, as below:
```rust
pub async fn start(&self, callback: Box<dyn Fn() -> DartFnFuture<bool> + Send>) {
        tokio::spawn(async move {
            loop {
                callback().await;
            }
        });
    }
```
2. Then the FRB generated codes as below:
```dart
Future<void> start({required BoxFnDartFnFutureBool callback});

abstract class BoxFnDartFnFutureBool implements RustOpaqueInterface {}
```
3. When I use the `start` function in Dart, I cannot return a bool value in the `callback`. Is it a bug, or how can I use the `start` function correctly? The analyzer error report is `The argument type 'Future<bool> Function()' can't be assigned to the parameter type 'BoxFnDartFnFutureBool'.`.

### Steps to reproduce

Just do as the description above.

### Logs

```shell
No logs.
```

**Comment by xuxiaocheng0201** [comment]
Try `callback: impl Fn() -> DartFnFuture<bool> + Send`?

**Comment by fzyzcjy** [comment]
Totally agree with @xuxiaocheng0201, maybe have a try about that :)

**Comment by lbhfuture** [comment]
I use `callback: impl Fn() -> DartFnFuture<bool> + Send + 'static` works, thanks.

**Comment by lbhfuture** [comment]
I use callback: impl Fn() -> DartFnFuture<bool> + Send + 'static works, thanks.
