### ISSUE TITLE
Error: 'initMockImpl' isn't defined for the type 'RustLib'

### ISSUE THREAD

**Issue by ethicnology** [fzyzcjy/flutter_rust_bridge#2413]
### Describe the bug

I maintain the [rust-bip85](https://github.com/ethicnology/rust-bip85/tree/master/bindings/dart-bip85) library and am working on porting it to the Flutter community, leveraging your excellent tool.

I’ve encountered an issue in a Flutter project that involves multiple packages using `flutter_rust_bridge`.

I've noticed that some package such as `bdk_flutter` works with [pre-compiled binaries](https://github.com/LtbLightning/bdk-flutter/blob/main/rust/cargokit.yaml).
Other package like `lwk` has a dedicated [await LibLwk.init()](https://github.com/SatoshiPortal/lwk-dart/blob/trunk/lib/src/utils/loader.dart)

Could you help me understand why in the case of a new project I face no issues, but run into problems when working with multiple other `flutter_rust_bridge` projects ?

What are the steps to produce a package that is compatible with others ?

It would be really helpful to have a step-by-step guide for properly wrapping a Rust project for pub.dev

### Steps to reproduce

1. `git clone git@github.com:SatoshiPortal/bullbitcoin-mobile.git`
2. `flutter pub add bip85`
3. Add in `lib/main.dart` 
```dart 
import 'lib/package:bip85/bip85.dart' as bip85;
…

  runZonedGuarded(() async {
    if (!fromTest) WidgetsFlutterBinding.ensureInitialized();
    await LibLwk.init();
    await LibBoltz.init();

    await bip85.RustLib.init();
    const xprv = 'xprv9s21ZrQH143K2LBWUUQRFXhucrQqBpKdRRxNVq2zBqsx8HVqFk2uYo8kmbaLLHRdqtQpUm98uKfu3vca1LqdGhUtyoFnCNkfmXRyPXLjbKb';
    final mnemonic = bip85.toMnemonic(xprv: xprv, wordCount: 12, index: 0);
    print(mnemonic);
…
```

4. `flutter run` ios/android simulator

### Logs

```shell
Error (Xcode):
/lib/src/rust/frb_generated.dart:39:14: Error: The method 'initMockImpl' isn't defined for
the class 'RustLib'.
```

### OS

MacOS

### Version of `flutter_rust_bridge_codegen`

2.6

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.0.1 24A348 darwin-arm64, locale
    en-US)
    • Flutter version 3.24.5 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.24.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (7 days ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/azad/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)            
    • iPhone 16 Plus (mobile)         • 4662AA9C-CCDA-427E-892A-D3F0F981B7F0 •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    • macOS (desktop)                 • macos                                •
      darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                •
      darwin         • macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                               •
      web-javascript • Google Chrome 130.0.6723.119

[✓] Network resources
    • All expected network resources are available.
```

**Comment by fzyzcjy** [comment]
> What are the steps to produce a package that is compatible with others ?

What about:

https://cjycode.com/flutter_rust_bridge/quickstart

![image](https://github.com/user-attachments/assets/2bb38477-b08b-49cb-8630-3973c295d791)

Feel free to ping me if you have other questions after using this!

**Comment by ethicnology** [comment]
Yes, I've built my package using the `plugin` template but is it enough ?

I've also follow the [guide](https://github.com/irondash/cargokit/blob/main/docs/architecture.md#configuring-cargokit) for `precompiled_binaries` using `cargokit`

**Comment by ethicnology** [comment]
To solve this error:
```sh
Error (Xcode):
/lib/src/rust/frb_generated.dart:39:14: Error: The method 'initMockImpl' isn't defined for
the class 'RustLib'.
```


I have deleted the `initMock` code from `frb_generated.dart` but `flutter_rust_bridge_codegen generate` keep re-generate it:
```dart
  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required LibBip85Api api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }
```

**Comment by fzyzcjy** [comment]
Hmm, looks like a bug that some functions is not generated? Could you please provide a minimal reproducible sample (probably just a almost blank project)?

**Comment by ethicnology** [comment]
Using 2.6.0 execute `flutter_rust_bridge_codegen create new_plugin --template plugin` and you can see `initMock` with an undefined `initMockImpl`, I guess it happened when I bump 2.5.0 to 2.6.0:
```dart
  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }
```

**Comment by fzyzcjy** [comment]
Great, I will check that later.

Btw, is your flutter_rust_bridge dart dependency in pubspec.yaml latest? IMHO in https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_dart/lib/src/main_components/entrypoint.dart#L68 the initMockImpl is there, so it should be able to find it.

**Comment by ethicnology** [comment]
When I execute the command `flutter_rust_bridge_codegen create new_plugin --template plugin` the `flutter_rust_bridge` dependency is `2.6.0` in the pubspec.yaml.

On my own project, I started with `2.5.0`, then upgraded to `2.6.0` and later, I had to downgrade to `2.0.0` because most other projects that rely on flutter_rust_bridge are stuck in this version and it creates incompatibility.

By the way, to reduce incompatibilities between packages made by people using `rust_flutter_bridge` , it would be great if version is `^2.X.X` instead of strictly `2.X.X` but I don't know if there are restrictions about this.

This tool is great, it help us to grow the dart/flutter ecosystem

**Comment by ethicnology** [comment]
> Ok then I guess this is the issue: The 2.6.0 codegen generates code that is compatible with 2.6.0 runtime, instead of 2.0.0, which does not have that new function.  

On my project yes. But the error  `initMockImpl isn't defined for the type 'RustLib'`.
appears on a brand new `--template plugin` that is fully `2.6.0`

> Thanks and happy to see the ecosystem growing!

Thank to your work!

**Comment by fzyzcjy** [comment]
> But the error 

Hmm then it's a bug. I guess it is relatively easy to fix, so feel free to PR! Alternatively I will work on it in the next batch.

> Thank to your work!

You are welcome!

**Comment by fzyzcjy** [comment]
No, indeed I think it should work, because the class extends BaseEntrypoint, and BaseEntrypoint has a initMockImpl method

**Comment by fzyzcjy** [comment]
I still guess it may be because your dart runtime version is not 2.6.0...

**Comment by ethicnology** [comment]
Here is a test [repository](https://github.com/ethicnology/frb_bug)

1. `cargo install --version 2.6.0 flutter_rust_bridge_codegen`

2. `flutter_rust_bridge_codegen --version`
```sh
flutter_rust_bridge_codegen 2.6.0
```

3. `flutter_rust_bridge_codegen create frb_bug --template plugin`
4. `cd frb_bug`

5. `pubspec.yaml`
```yml
flutter_rust_bridge: 2.6.0
```

6. `dart analyze lib/`
```sh
  error • src/rust/frb_generated.dart:39:14 • The method 'initMockImpl' isn't defined for
          the type 'RustLib'. Try correcting the name to the name of an existing method,
          or defining a method named 'initMockImpl'. • undefined_method

1 issue found.
```

7. `cd example`
8. `flutter run -d macos`
```sh
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008112-0004119A3E2A201E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00008112-0004119A3E2A201E, name:My Mac }
../lib/src/rust/frb_generated.dart:39:14: Error: The method 'initMockImpl' isn't defined for the class 'RustLib'.
 - 'RustLib' is from 'package:frb_bug/src/rust/frb_generated.dart' ('../lib/src/rust/frb_generated.dart').
Try correcting the name to the name of an existing method, or defining a method named 'initMockImpl'.
    instance.initMockImpl(
             ^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **
```




`flutter doctor -v`
```sh
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.0.1 24A348 darwin-arm64, locale
    en-US)
    • Flutter version 3.24.5 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.24.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (9 days ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/azad/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.0.1 24A348 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.0.1 24A348 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 130.0.6723.119

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by fzyzcjy** [comment]
Weird... I will check this soon.

**Comment by fzyzcjy** [comment]
I git cloned the repo, modify pubspec.yaml to use lower min dart version, run `flutter pub get`, then

```
 dart analyze lib
Analyzing lib...                       1.6s
No issues found!
```

I will upgrade my local flutter and retry to reproduce.

**Comment by ethicnology** [comment]
🤯 

If you don't have a `dev` or updated version of `flutter_rust_bridge_codegen`, I don't see what it can be…

**Comment by ethicnology** [comment]
I switched to 2.5.0 and repeated the same experience without any issue

**Comment by ethicnology** [comment]
I tried, and I still error:
1. git clone git@github.com:ethicnology/frb_bug.git
2. flutter pub get
3. dart analyze lib
```sh
Analyzing lib...                       0.9s

  error • src/rust/frb_generated.dart:39:14 • The method 'initMockImpl'
          isn't defined for the type 'RustLib'. Try correcting the name to
          the name of an existing method, or defining a method named
          'initMockImpl'. • undefined_method

1 issue found.
```

**Comment by ethicnology** [comment]
Do you think it's the flutter or cargo cache, maybe both  ?

**Comment by fzyzcjy** [comment]
flutter cache i guess, because it is the dart runtime package being weird

**Comment by ethicnology** [comment]
`flutter clean` correctly deleted `.dart_tool`.

Solving the issue:
1. `rm -rf ~/.pub-cache/hosted/pub.dev/*`
2. cd <flutter_project_path> && flutter pub get

`pub-cache` **corrupted**, good catch, thank you

**Comment by fzyzcjy** [comment]
Happy to see it is solved, you are welcome!
