### ISSUE TITLE
Doc Question: How to Build?

### ISSUE THREAD

**Issue by sgon00** [fzyzcjy/flutter_rust_bridge#2417]
Hi, Sorry to ask a question here. I am a newbie. I am trying to study how to use flutter and rust together. I first saw `rinf`, then `flutter_rust_bridge`. I am trying to see which one is eaiser to use. 

Now, I can not find a "build" doc in `flutter_rust_bridge` doc https://cjycode.com/flutter_rust_bridge/.

For rinf, it's very clear that there is a separate section link: https://rinf.cunarist.com/running-and-building/

Am I missing anything? Where is the build doc?

Thanks a lot.

**Comment by fzyzcjy** [comment]
Hi, it is named "quickstart", and is the first page (after introduction) in the doc: https://cjycode.com/flutter_rust_bridge/quickstart

**Comment by fzyzcjy** [comment]
Btw, there is a single command (see the red arrow in the screenshot) to quickly quickstart.

![image](https://github.com/user-attachments/assets/a87562cc-aff2-45e1-af1d-775af5d38e64)

**Comment by sgon00** [comment]
@fzyzcjy Thank you very much for your reply and detail screenshot. But that is how to **Run** instruction. But I would like to know how to **Build** package for all platforms.  
For example, in https://rinf.cunarist.com/running-and-building, it shows the instructions how to build for native platform and for the web platform clearly. That rinf URL is also very clear in the first level header so that I can find it easily. 

![rinf_build](https://github.com/user-attachments/assets/7bfa2d2e-8e71-4ead-8f61-504f70ad3c69)
![rinf_build2](https://github.com/user-attachments/assets/88dc0018-c7f1-4911-a403-75331b0d8dc9)

**Comment by sgon00** [comment]
OK, cool. I was wondering if I need any extra steps for building native and web packages. Thanks a lot for your time and help.

**Comment by fzyzcjy** [comment]
You are welcome!

For web, yes you need a bit as below. (I will add doc tomorrow, but the idea is all here)

1. `flutter_rust_bridge_codegen build-web --release`
2. Cross origin header setup https://cjycode.com/flutter_rust_bridge/manual/miscellaneous/web-cross-origin

![image](https://github.com/user-attachments/assets/f374115c-9691-463a-8a26-2d5154784367)

**Comment by fzyzcjy** [comment]
Doc added: https://github.com/fzyzcjy/flutter_rust_bridge/pull/2421
