### ISSUE TITLE
Switch from `dart-sys-fork` to `dart-sys` crate

### ISSUE THREAD

**Issue by evdokimovs** [fzyzcjy/flutter_rust_bridge#2434]
Are there any blockers to switching to the `dart-sys` crate from crates.io instead of using `dart-sys-fork`? From what I can tell, the changes in `dart-sys-fork` have already [been merged][1] upstream. Would it make sense to use the `dart-sys` crate directly instead?

[1]: https://github.com/dart-sys/dart-sys/commit/3d8ebd6fddbbade907dc5e0c54bf1a3f8328a55e

**Comment by fzyzcjy** [comment]
Looks pretty reasonable, feel free to PR for this!
