### ISSUE TITLE
Delete frb_generated.rs after each generation

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#2446]
If you don't delete the generated new method, you won't find it

**Comment by fzyzcjy** [comment]
Sorry but I do not quite get it. Could you please elaborate a bit more and give a minimal reproducible sample?

**Comment by 107295472** [comment]
flutter_rust_bridge_codegen generate

**Comment by fzyzcjy** [comment]
Well that does not seem to be a reproducible sample...

**Comment by 107295472** [comment]
![image](https://github.com/user-attachments/assets/9719269d-f7d4-49cd-82bb-eb4a0f5508ca)

**Comment by 107295472** [comment]
![image](https://github.com/user-attachments/assets/a8578040-dc3d-4149-bdb1-e7d19f5a7676)

**Comment by 107295472** [comment]
![image](https://github.com/user-attachments/assets/0dfbcb48-abfa-43bb-827e-97a7783274cb)

**Comment by 107295472** [comment]
Yes, vscode is slow to respond

**Comment by fzyzcjy** [comment]
Well this still does not seem to be a minimal reproducible sample IMHO...

**Comment by 107295472** [comment]
#[frb(sync)]
pub fn demorust()  Changed to demo_rust, frb_generated.dart generation did not change
