### ISSUE TITLE
How to optimize parameter passing time between Flutter and Rust?

### ISSUE THREAD

**Issue by 826327700** [fzyzcjy/flutter_rust_bridge#2447]
I'm trying to call a Rust method from Flutter, passing an image byte array as a parameter. After adding timing logs, I discovered that just the parameter passing alone takes 97ms, which is unacceptable. I'd like to know how to optimize this parameter passing overhead.

Additionally, I noticed that when running Flutter in development mode (`flutter run`), the Rust code seems to be running in debug mode as well. Is there a way to make the Rust code run in release mode while Flutter is in development mode?

Here's a minimal example demonstrating the issue:
```rust
#[flutter_rust_bridge::frb(sync)]
pub fn decodeJpeg(image_data: Vec<u8>) {
    let now = SystemTime::now().duration_since(UNIX_EPOCH).expect("Time went backwards");
    println!("Rust received dart call: {:?}", now.as_millis());
}
```
```dart
final imageBytes = await File("xxxx.jpeg").readAsBytes();
print('dart call rust start ${DateTime.now().millisecondsSinceEpoch}');
decodeJpeg(imageData: imageBytes);
```

flutter: dart call rust start 1733836198398
Rust received dart call: 1733836198495

**Comment by fzyzcjy** [comment]
Hi, firstly:

1. Use release mode instead of debug mode
2. Enable `full_dep: true` and install LLVM dependency, then it will generate a faster codec

**Comment by 826327700** [comment]
> Hi, firstly some quick tries:
> 
> 1. Use release mode instead of debug mode
> 2. Enable `full_dep: true` and install LLVM dependency, then it will generate a faster codec
> 
> > Is there a way to make the Rust code run in release mode while Flutter is in development mode?
> 
> https://cjycode.com/flutter_rust_bridge/guides/how-to/rust-compilation

Oh my god! It's realy fast in --release mode! only 4ms! Thank you!

**Comment by fzyzcjy** [comment]
You are welcome!
