### ISSUE TITLE
Ignore enum case warning in generated dart files if dart_enums_style: false

### ISSUE THREAD

**Issue by VladTheJunior** [fzyzcjy/flutter_rust_bridge#2461]
**Is your feature request related to a problem? Please describe.**
I have `dart_enums_style: false` in flutter_rust_bridge.yaml to generate enums with rust upper camel case. And because of that I have a lot of warnings  by dart analyzer for my enums

**Describe the solution you'd like**
Possibly add  `// ignore: constant_identifier_names` after each item in enum or make it ignore for whole file in generated dart files if dart_enums_style set to false

**Comment by fzyzcjy** [comment]
https://cjycode.com/flutter_rust_bridge/guides/misc-features/preambles may be used to add ignores, such as `dart_preamble: "// ignore_for_file: this_is_a_lint_rule"`

**Comment by VladTheJunior** [comment]
Ohh, right, I forgot about this feature. Thanks

**Comment by fzyzcjy** [comment]
You are welcome
