### ISSUE TITLE
flutter_rust_bridge_codegen generate does not pass --enable-experiment=native-assets when calling dart run ffigen

### ISSUE THREAD

**Issue by MohiuddinM** [fzyzcjy/flutter_rust_bridge#2471]
### Describe the bug

ffigen fails when running `flutter_rust_bridge_codegen generate` because `native-assets` experiment flag is not passed to the dart cmd. Also, there is no way to pass that flag externally because the generator throws an error: `error: unexpected argument '--enable-experiment' found`

### Steps to reproduce

Create a pure dart project that is using` build.dart` and `ffigen`, and run `flutter_rust_bridge_codegen generate`

### Logs

```shell
Enable native assets with `--enable-experiment=native-assets`
[7.5s] Parse
  └── [7.5s] Cargo expand & syn parse
  └── [0.0s] Parse HIR
  └── [0.0s] Parse MIR
[0.8s] Generate
  └── [0.2s] Run cbindgen
  └── [0.6s] Run ffigen 

Error: ffigen failed. Please refer to https://fzyzcjy.github.io/flutter_rust_bridge/manual/ffigen-troubleshooting for details
```

### Version of `flutter_rust_bridge_codegen`

2.7.0

**Comment by fzyzcjy** [comment]
Hmm, what about using `full_dep: false` to avoid calling ffigen?

**Comment by MohiuddinM** [comment]
Using `full_dep: false` works. What effect does it have?

**Comment by fzyzcjy** [comment]
`full_dep: true` will assume you have full dependencies installed, primarily LLVM, on your machine. Then it will `ffigen` (an official Dart package) to generate code. By disabling it, ffigen is not called, thus the issue disappear.
