### ISSUE TITLE
Marker attributes

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#260]
As this project is growing in functionality, there are some places where Rust is not expressive enough to generate quality Dart code.
The idea is that bridging libraries e.g. wasm_bindgen also use attributes to guide code generation, for example in this case `#[wasm_bindgen(...)]`.

A simple use-case for our library would be declaring non-final fields: today, a struct in Rust corresponds to a class in Dart where
all fields are final with no way to configure. For example, this code in Rust:

```rust
struct Foo {
  pub foo: String
  pub bar: Option<String>
}
```

would be translated into this Dart code:

```dart
class Foo {
  final String foo;
  final String? bar;
  Foo({
    required this.foo,
    this.bar
  });
}
```

It would be impossible to update Foo.bar if it's null once it's sent to Dart, which might be undesirable for some usages.

With an attribute e.g. `#[frb]`, we can signal that some field actually needs to be non-final in Dart:

```rust
#[frb]
struct Foo {
  pub foo: String
  #[frb(mut)]
  pub bar: Option<String>
}
```

so that this Dart code is generated:

```dart
class Foo {
  final String foo;
  String? bar;
  Foo({
    required this.foo,
    this.bar
  });
}
```

These attributes will be beneficial for other features in the future as well, so there are many advantages to implementing attributes first.

**Comment by fzyzcjy** [comment]
Great suggestion and I am looking forward to the PR! Seems that we need to have some procedural macros (even if they are empty) to allow attributes. So maybe we can add another root folder `/frb_proc` or something like that, and later publish it to crates.io as well.
