### ISSUE TITLE
Enum struct wire2api does not convert raw data

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#265]
Missed calling wire2api on raw data received from Rust on enum structs. For example, this code doesn't work:

```rust
pub enum Foo { Bar, Baz }
pub enum Letters {
  Alpha,
  Beta(Foo)
}
```

Foo is represented as an integer when passed to Dart, which is used before being re-converted to a Dart enum.

**Comment by fzyzcjy** [comment]
Thanks for the report and looking forward to PR!
