### ISSUE TITLE
Boolean fields cannot be used

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#266]
In structs and enum structs, if one of the fields is of boolean type, that field is mapped as a `u8` field in the corresponding wire struct.
This leads to the issue where ffigen generates wire functions that takes in boolean parameters but structs with integer fields (ffigen does its own bool-to-int conversions in the wire functions case), therefore wrong signatures of api2wire functions.

**Comment by fzyzcjy** [comment]
Agree!
