### ISSUE TITLE
Maybe refactor documentations

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#272]
See discussions in https://github.com/fzyzcjy/flutter_rust_bridge/issues/250

TODO:

- [x] the basics
- [ ] configure mdbook (since it is by rust ;))

**Comment by Roms1383** [comment]
I think you could even consider a book and a step-by-step extended example IMHO.
This crate looks awesome, but difficult to grasp without some prior knowledge and digging informations scattered around.

**Comment by fzyzcjy** [comment]
@Roms1383 Great, I will consider that

**Comment by fzyzcjy** [comment]
Will do mdbook tomorrow (e.g. by https://rust-lang.github.io/mdBook/continuous-integration.html)

**Comment by fzyzcjy** [comment]
almost done
