### ISSUE TITLE
[Bug] `frb_codegen` fails with enum as a function argument, because only types defined in the input file are transformed

### ISSUE THREAD

**Issue by SecondFlight** [fzyzcjy/flutter_rust_bridge#294]
### Describe the bug

`frb_codegen` fails when an enum is given as a function argument.

### To Reproduce

1. Start with the pure dart example
2. Add the following to `rust/src/data.rs`:
```rust
pub enum MyEnum {
    One,
    Two,
}
```
3. Add the following to `rust/src/lib.rs`:
```rust
mod data;
```
4. Add the following to `rust/src/api.rs`:
```rust
use crate::data::MyEnum;

pub fn do_something(data: MyEnum) -> Result<i32> {
    match data {
        MyEnum::One => Ok(1),
        MyEnum::Two => Ok(2),
    }
}
```
5. Run codegen:
```ps1
flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output 
dart/lib/bridge_generated.dart
```

### Expected behavior

Codegen succeeds.

### Codegen logs

```shell
[2022-01-05T23:24:28Z INFO  flutter_rust_bridge_codegen] Picked config: Opts { rust_input_path: "C:\\Users\\qbgee\\Documents\\Code\\flutter_rust_bridge\\frb_example\\pure_dart\\rust/src/api.rs", dart_output_path: "C:\\Users\\qbgee\\Documents\\Code\\flutter_rust_bridge\\frb_example\\pure_dart\\dart/lib/bridge_generated.dart", c_output_path: "C:\\Users\\qbgee\\AppData\\Local\\Temp\\.tmp9PsTF6.h", rust_crate_dir: "C:\\Users\\qbgee\\Documents\\Code\\flutter_rust_bridge\\frb_example\\pure_dart\\rust", rust_output_path: "C:\\Users\\qbgee\\Documents\\Code\\flutter_rust_bridge\\frb_example\\pure_dart\\rust/src\\bridge_generated.rs", class_name: "FlutterRustBridgeExample", dart_format_line_length: 80, skip_add_mod_to_lib: false, llvm_path: "", llvm_compiler_opts: "" }
[2022-01-05T23:24:28Z INFO  flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2022-01-05T23:24:28Z INFO  flutter_rust_bridge_codegen] Phase: Parse AST to IR
[2022-01-05T23:24:28Z DEBUG flutter_rust_bridge_codegen::parser] parse_function function name: Ident(do_something)
[2022-01-05T23:24:28Z DEBUG flutter_rust_bridge_codegen::parser] parse_type: MyEnum
thread 'main' panicked at 'parse_type failed for ty=MyEnum', C:\Users\qbgee\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.13.0\src\parser.rs:151:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Generated binding code

```shell
N/A, since codegen failed
```

### OS

Windows 10 21H1

### Version of `flutter_rust_bridge_codegen`

1.13.0

### Flutter info

```shell
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1415], locale en-US)
    • Flutter version 2.8.1 at C:\Users\qbgee\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.10.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.10.31424.327
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\qbgee\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1415]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 96.0.1054.62

! Doctor found issues in 2 categories.
```

### Version of `clang++`

I don't think I have `clang++` installed, though I may be wrong.

### Version of `cbindgen`

0.20.0

### Version of `ffigen`

No `ffigen` listed in `pubspec.yaml` for the pure dart example.

**Comment by Desdaemon** [comment]
This doesn't work yet because only types that are defined in the input file are transformed. If you move `MyEnum` into api.rs, it will work as expected.

Related: #249

**Comment by SecondFlight** [comment]
Ah that makes sense, thanks for the explanation!

I have a shared crate in a multi-crate project that includes some types I want to serialize and deserialize. I thought I was being clever to get around #249 by copying files from there into the crate that `flutter_rust_bridge` lives in, but evidently not clever enough 😅

Is anyone working on #249? I have only a little experience with macros but I'm willing to give it a shot. This is turning into a blocker for my project, as the complexity of my workaround is probably higher at this point than just implementing it properly in `flutter_rust_bridge`.

And in case I'm on a completely wrong track, here's my use-case: I'm hoping to use `flutter_rust_bridge` to facilitate IPC between my main process and a self-contained Rust process. I have a set of message types in a separate Rust crate that can be serialized and sent via IPC to the Rust process. I'd like to use `flutter_rust_bridge` to allow for a `send` function that can be used to send messages to the Rust process in a way that is type-safe, hence trying to get `flutter_rust_bridge` to serialize external types.

**Comment by fzyzcjy** [comment]
> as the complexity of my workaround is probably higher at this point than just implementing it properly in flutter_rust_bridge.

You are welcomed to make a PR! I can always help and comment if you get stuck.

> between my main process and a self-contained Rust process

main process is also rust or not?

>  I'd like to use flutter_rust_bridge to allow for a send function that can be used to send messages to the Rust process in a way that is type-safe

flutter_rust_bridge does not have builtin IPC. You may need to cooperate with another IPC library

**Comment by SecondFlight** [comment]
> main process is also rust or not?

The main process is my Flutter app. I'm currently trying to use `flutter_rust_bridge` to 

> flutter_rust_bridge does not have builtin IPC. You may need to cooperate with another IPC library

Yeah sorry, I should have given more context. I have IPC figured out, but I'm doing IPC by serializing a set of message objects and sending them back and forth. I want to be able to define a message object in Rust and run `frb_codegen` to create an equivalent object in Flutter. Then I can hopefully write a `send()` method in Rust that can be called via FFI from Dart. This method would serialize a message argument (currently via `serde` + `bincode`) and send it to the other Rust process (currently via `interprocess`).

The end goal is to define my message data structures in one place and use them across my Dart + Rust codebase.

**Comment by fzyzcjy** [comment]
Aha I get it. It sounds very reasonable.
