### ISSUE TITLE
First step of cooperating `flutter_rust_bridge` with `package:rfw`: Make the simple demo run

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#297]
Tracking issue of https://github.com/fzyzcjy/flutter_rust_bridge/issues/296#issuecomment-1008128397

> I was imagining something similar to https://github.com/flutter/packages/tree/main/packages/rfw/example/wasm — the first step would be to experiment with creating a similar example that uses this package instead of wasm. It may not even require any changes in the packages themselves.

**Comment by Mohsen7s** [comment]
This could bring Flutter to next level with 'Hot Update' 'Code Push'.
Is anyone working on this ?

**Comment by fzyzcjy** [comment]
@Mohsen7s You are welcomed to make a PR :)

**Comment by fzyzcjy** [comment]
To make the issue tracker cleaner, I will close this and let us discuss in https://github.com/fzyzcjy/flutter_rust_bridge/issues/296
