### ISSUE TITLE
Issue building on Mac m1 arm64

### ISSUE THREAD

**Issue by saward** [fzyzcjy/flutter_rust_bridge#302]
Hi,

I'm using the example template from this repository, and was able to get this working on MacOS m1 by building the rust library targeting x86_64.  However, now I'm trying another rust library and it wasn't building for x86, so I thought I'd try to target arm64 instead.  I had to remove arm64 from excluded list of architectures, and added x86_64 to excluded list.  However, now when I try to build I get this error and not sure what to do with it.  It probably has nothing to do with this project, so please close if you can't help, but thought I'd check if you've seen it before and know what to do!

```
Multiple devices found:
macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71
[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             996ms
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:45E0E381-7147-5276-8D19-82457684B2FF }
{ platform:macOS, name:Any Mac }
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in parallel
/Users/mark/projects/flutter-rust-test/macos/Runner.xcodeproj: error: The linked framework 'Pods_Runner.framework' is missing one or more architectures required by this target: arm64. (in target 'Runner' from project 'Runner')
** BUILD FAILED **

Building macOS application...
Exception: Build process failed
```

**Comment by fzyzcjy** [comment]
Well it seems really unrelated to this repo.

`/Users/mark/projects/flutter-rust-test/macos/Runner.xcodeproj: error: The linked framework 'Pods_Runner.framework' is missing one or more architectures required by this target: arm64. (in target 'Runner' from project 'Runner')`

Maybe this is a Flutter problem? (since Pods_Runner.framework is a flutter thing). Try to search on internet, and maybe raise a StackOverflow question or issue in flutter repo.

**Comment by fzyzcjy** [comment]
If you successfully find the answer, feel free to post it here as well since it may help later people and I can write it in the book.

**Comment by saward** [comment]
Yep, I've done a lot of searching on internet already and experimenting :)  If I find a solution I will indeed post here, and will close this issue for now (I assume you don't want it hanging around open).  Thanks!

**Comment by fzyzcjy** [comment]
You are welcome 😄
