### ISSUE TITLE
Support for `std::path::PathBuf`

### ISSUE THREAD

**Issue by theRookieCoder** [fzyzcjy/flutter_rust_bridge#310]
**Is your feature request related to a problem? Please describe.**
The [library](https://github.com/theRookieCoder/libium) I'm trying to interface with uses `PathBuf`s quite extensively to deal with config files. However, `std::path::PathBuf` doesn't seem to be supported by the bindgen.

**Describe the solution you'd like**
`PathBuf` is actually just an `OsString` with some added convenience methods for adjoining paths (`PathBuf::join()`) etc. I don't know how this bindgen works but I think `OsString`s wouldn't be to hard implement?

**Comment by fzyzcjy** [comment]
Sounds quite reasonable. Maybe we should add an extra converter converting `PathBuf` to `Vec<u8>`, and then we can happily pass it around. @Desdaemon what do you think?

You are welcomed to contribute and I am willing to review the PR ;)

**Comment by Desdaemon** [comment]
I don't think there's a wrong way to design this, only that byte strings are awkward to represent in Dart right now. We could define an API like this to make it easier for users:
```dart
typedef Path = Uint8List;
extension PathExt on Path {
  String toString({ bool? allowMalformed }); // abort on non-utf8
}
```

**Comment by theRookieCoder** [comment]
Also we would have to keep the difference between a `Path` and a `PathBuf` in mind. The difference is basically the same as the difference between a `String` and `&str`

**Comment by fzyzcjy** [comment]
@Desdaemon Sounds interesting! Only a small problem: The code you provide will make `Path` equivalent to `Uint8List`, i.e. they have no difference, just alias. Then everyone using `Uint8List` will see that strange method. In addition, we cannot override system's toString method, so maybe rename to sth else as well.

**Comment by fzyzcjy** [comment]
@theRookieCoder Currently seems that we only deal with `String`, so maybe only `PathBuf` currently

**Comment by theRookieCoder** [comment]
That's fine for me but most importantly it's probably fine for most people because it's pretty much impossible to mutate paths using `Path` because it's an immutable reference. AFAIK pretty much no one (other then `std` I guess) uses `Path`s anyways
