### ISSUE TITLE
[Regression] Rust code can no longer contain use renames, even though we don't try to parse them

### ISSUE THREAD

**Issue by SecondFlight** [fzyzcjy/flutter_rust_bridge#326]
Any Rust code that contains an import rename will cause `source_graph.rs` to panic. This is bad, since imports are not currently used by codegen and so shouldn't matter.

I'm working on a fix for this, but just leaving this issue here in case someone gets to releasing before I open a PR.

**Comment by fzyzcjy** [comment]
Sure. I will not release a new version before this is solved.
