### ISSUE TITLE
Support for `HashMap<K, V>`

### ISSUE THREAD

**Issue by SecondFlight** [fzyzcjy/flutter_rust_bridge#329]
I am modelling complex data, some of which is best described with `HashMap`s.

My app's architecture is as follows:
1. There is a pure-Rust process
2. There is a Flutter+Rust process
3. There is a shared messaging model + core data model, which is run through flutter_rust_bridge and used to facilitate IPC

I have considered two alternatives:
1. Create two separate core data models, one with `HashMap`s and one without, and translate between the two (this does not scale)
2. Use `Vec` throughout (this doesn't "feel" right, but it's what I'm going with for now)

**Comment by fzyzcjy** [comment]
Some thoughts about implementation:

To utilize existing infra, maybe we can convert `HashMap<K,V>` to/from `Vec<(K, V)>` and happily reuse the existing feature for Vec.

@Desdaemon What do you think?

Looking forward to your PR!

**Comment by Desdaemon** [comment]
> To utilize existing infra, maybe we can convert HashMap<K,V> to/from Vec<(K, V)> and happily reuse the existing feature for Vec.

The catch is that we haven't implemented anonymous tuple types yet -- a simpler way yet could be pushing both the keys and values in a vector then extract them pairwise, but there's room for new ideas.

**Comment by SecondFlight** [comment]
> Looking forward to your PR!

I'm actually interested in the problem, especially after getting my feet wet elsewhere in the project, but I can't commit to attacking it right now. I have some pressing TODOs on my project and can use `Vec` there for the time being.

I'll comment here if I'm able to take it on at some point.

I am very grateful for this project and I hope to contribute more in the future!

**Comment by fzyzcjy** [comment]
@SecondFlight Take your time and happy to see that this project helps you!

**Comment by fzyzcjy** [comment]
👀

**Comment by SecondFlight** [comment]
👀

**Comment by TENX-S** [comment]
👀

**Comment by fzyzcjy** [comment]
Feel free to PR!

**Comment by fzyzcjy** [comment]
Given interest in this issue (at https://github.com/fzyzcjy/flutter_rust_bridge/issues/954), this issue is unklocked :)

**Comment by fzyzcjy** [comment]
For future readers:

> https://github.com/fzyzcjy/flutter_rust_bridge/issues/954#issue-1521895082 by @dbsxdbsx 
> I currently met a situation needs to pass a struct with a field of `Vec<HashMap<String, String>>`, just like this: #329. I tried to work around it by making the type of `Vec<Vec<(String,String)>>`, but then frb errors with : ` 'parse_type failed for ty=Vec<Vec<(String,String)>>'`.
> 
> I wonder:
> 
> 1. Is there some progress on this issue?
> 2. Should rust type `HashMap` be supported to map into `Map` in Dart, or other type?
> 3. If this issue is intended to be solved by directly mapping rust  `HashMap`  into a kind of `Map` in Dart, what about other map in rust, like `BtreeMap` or `SortedMap`-- say, doing the same as that on `HashMap`?
