### ISSUE TITLE
[Bug] Freezed file is sometimes not generated when it should be

### ISSUE THREAD

**Issue by SecondFlight** [fzyzcjy/flutter_rust_bridge#330]
In hindsight, I probably should have tested #319 a bit more thoroughly 😅

I'm running codegen on a larger test project with enums, and flutter_rust_bridge is not generating a freezed file.

I'm early in investigating this, but I think this is happening because `distinct_types()` in `api_types.rs` doesn't know how to find imported types. I have no idea why this isn't causing more things to break, so it might be a red herring.

If all goes well I'll have a fix for this soon. @fzyzcjy This issue shouldn't cause any existing code to break, so it's up to you if you want to wait for the fix.

**Comment by fzyzcjy** [comment]
Hmm maybe I will wait for the fix. Since this bug is related to #319, and the next release is mainly about #319 as well. Take your time!

**Comment by SecondFlight** [comment]
Turns out, not running `build_runner` can cause issues 🤦‍♂️

I'm still seeing something, but it's unrelated to #319 as best I can tell. I'll open a separate bug for that momentarily.
