### ISSUE TITLE
Return types other than `Result<_>`

### ISSUE THREAD

**Issue by antonok-edm** [fzyzcjy/flutter_rust_bridge#332]
I tried to get started with this library and instantly ran into some problematic function signatures. I had to dig into the code to find out that... [only `Result<_>` is supported as a return type](https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_codegen/src/parser.rs#L132-L136).

Some functions should never fail; is there a reason to enforce that restriction everywhere? If it's an intentional design decision, it'd be nice to have it listed in the documentation somewhere with an explanation (I'm aware of https://github.com/fzyzcjy/flutter_rust_bridge/issues/318). But, either way, the error messages could provide much more useful guidance to users starting out. Currently a signature like the following:

```rust
pub fn concat_strings(a: String, b: String) -> String {
```

gives the following error:

```
thread 'main' panicked at 'unsupported type_string: String', /home/antonok/.config/cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.16.0/src/parser.rs:135:21
```

...whereas something like `` Functions must return `Result<_>` `` would be immensely more helpful for identifying the issue and suggesting a solution.

**Comment by fzyzcjy** [comment]
Thanks for pointing out!

> If it's an intentional design decision, it'd be nice to have it listed in the documentation somewhere with an explanation

Well this simplifies implementation of this lib, as you can imagine ;) I agree we should support functions that do not fail, and you are welcomed to make a PR as well.

> whereas something like Functions must return `Result<_>` would be immensely more helpful for identifying the issue and suggesting a solution.

code edited

**Comment by antonok-edm** [comment]
Makes sense, thanks! I might make a PR after playing with this a bit more, if nobody else gets around to it first :smiley:

**Comment by fzyzcjy** [comment]
You are welcome! Looking forward to your PR!
