### ISSUE TITLE
Document edge cases regarding Flutter Linux

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#354]
Thanks to @tmpfs's [comment](https://github.com/fzyzcjy/flutter_rust_bridge/issues/318#issuecomment-1045614165), an issue with running Corrosion on ARM Linux has been found.

Detail: Flutter ARM only ships with Snaps which bundle CMake 3.10 and cannot use FetchContent.

Needs to investigate whether Corrosion itself is compatible with older versions of CMake. I will raise this issue with upstream as needed.

**Comment by tmpfs** [comment]
@Desdaemon , from my research into this [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) requires cmake `3.11` and trying to install Corrosion from source failed for me (I was trying to avoid using `FetchContent` and just `include` it but I hit a different error).

Ultimately, this seems to be a problem with the flutter snap shipping old cmake IMO.

**Comment by Desdaemon** [comment]
A few findings I got for now:
- Corrosion requires CMake 3.12, so Flutter Snap users (both x86 and ARM) cannot use this method
- This may potentially be fixed by [canonical/flutter-snap#61](https://github.com/canonical/flutter-snap/pull/61)
- I haven't found satisfactory replacements for Corrosion, I will update this issue when I have more info.
