### ISSUE TITLE
[Bug] Weird problem about corrosion

### ISSUE THREAD

**Issue by coolit** [fzyzcjy/flutter_rust_bridge#355]
### Describe the bug

In the rust.cmake, I have enabled this:
find_package(Corrosion REQUIRED)
And have install corrosion as per here:
https://github.com/corrosion-rs/corrosion#installation
And put the following in the system PATH: (as I'm not sure which one should be used, so I use all)
C:\Program Files (x86)\Corrosion\Corrosion\lib
C:\Program Files (x86)\Corrosion\Corrosion
C:\Program Files (x86)\Corrosion

But when I ran exactly the same command such as "flutter build windows", sometimes the problem occurred, sometimes didn't.
According to the log, it was trying to access 'https://github.com/AndrewGaspar/corrosion.git/', regardless of that corrosion is already installed.
Do you have an idea how to solve this problem?
Thanks.

### Codegen logs with `RUST_LOG=debug` env variable

```shell
Performing update step for 'corrosion-populate'
  fatal: unable to access 'https://github.com/AndrewGaspar/corrosion.git/': OpenSSL SSL_read: Connection was aborted, errno 10053
  CMake Error at D:/genie/build/windows/_deps/corrosion-subbuild/corrosion-populate-prefix/tmp/corrosion-populate-gitupdate.cmake:97 (execute_process):
    execute_process failed command indexes:

      1: "Child return code: 128"
......
```

**Comment by fzyzcjy** [comment]
possibly related: https://github.com/fzyzcjy/flutter_rust_bridge/issues/318#issuecomment-1045614165 https://github.com/fzyzcjy/flutter_rust_bridge/issues/354

**Comment by coolit** [comment]
Sorry to not mentnion. In my case, it was windows not linux.

**Comment by Desdaemon** [comment]
@coolit Have you tried removing the FetchContent lines from your rust.cmake? When you already have the package you should only need the find_package line.

**Comment by coolit** [comment]
@Desdaemon  Yeas, after removing thm, seems the problem is gone now. Thanks so much.
