### ISSUE TITLE
Not run `build_runner` for whole package, but instead for one single file

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#365]
#363 is great since users do not need to call `build_runner` manually. However there is a small problem: When the package is huge, build_runner may run for a long time. Therefore, we may use things like https://github.com/dart-lang/build/issues/2928 to only execute build_runner for one file.

**Comment by Desdaemon** [comment]
Given that this is already a well-documented feature, I think it's sufficient for us to leave a link in our documentation to build_runner's so that people will at least be aware of the possibility.
