### ISSUE TITLE
[Bug] Windows CI is failing (again)

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#375]
e.g. https://github.com/fzyzcjy/flutter_rust_bridge/runs/5312283556?check_suite_focus=true

There does not seem to be related code change that makes CI fail...

**Comment by SecondFlight** [comment]
This doesn't look related to #324/#325. At first glance, I wonder if it's a tooling or dependency bug. The error doesn't look familiar to me, though I haven't written many Dart unit tests.

**Comment by fzyzcjy** [comment]
@SecondFlight I am also considering that. Maybe GitHub upgraded some dependencies, making us fail?

**Comment by Desdaemon** [comment]
> LINK : fatal error LNK1104: cannot open file '..\Debug\flutter_rust_bridge_example.dll.lib' 
My guess is that something changed with MSVC build tools recently, we can try using the old `windows-2019` environment instead. Might be relevant to Corrosion as well.

**Comment by fzyzcjy** [comment]
Good idea!
