### ISSUE TITLE
check not performed in rust release mode leading to error undetected

### ISSUE THREAD

**Issue by coolit** [fzyzcjy/flutter_rust_bridge#379]
### Describe the bug

Failed to build after using the latest version of rust and flutter_rust_bridge.

**Comment by fzyzcjy** [comment]
Hi, could you please share the code, or even better, a reproducible sample (possibly hosted as a github repo)

I will check it tomorrow morning

**Comment by coolit** [comment]
@fzyzcjy  
After hours of debugging, it seemed the bug lied with the unused lib use. Just comment out those unused lib, will make the build run successfully.

But a new problem occur. When I tried to calal the function, dart threw the error below:
FfiException (FfiException(PANIC_ERROR, attempt to subtract with overflow, null))

**Comment by fzyzcjy** [comment]
> FfiException (FfiException(PANIC_ERROR, attempt to subtract with overflow, null))

That is problem with your code IMHO. Look at stacktrace please.

By the way, please provide code and/or minimal reproducible sample, otherwise not possible to solve anything.

**Comment by coolit** [comment]
@fzyzcjy 
But the code worked fine when run in rust.  
btw, we should now comment out those unused lib to use the bridge?  Hopefully not.

**Comment by fzyzcjy** [comment]
Hi, **please give enough logs and enough reproducible sample.** Otherwise, I cannot do anything.

**Comment by coolit** [comment]
@fzyzcjy 
yes, I know. I will do that if I can. 
I add println! in rust code to check which snippet went wrong. And found that the wrong snippet was similar to the right snippet, only args were different. So far it is different to come up with a reproducible sample.
I use rust_backtrace="full" and below is the trace:
stack backtrace:
[   +1 ms]    0:     0x7ff8f3c1eabf - <unknown>
[        ]    1:     0x7ff8f3c3187a - <unknown>
[   +1 ms]    2:     0x7ff8f3c1bfa8 - <unknown>
[        ]    3:     0x7ff8f3c2163b - <unknown>
[        ]    4:     0x7ff8f3c21134 - <unknown>
[        ]    5:     0x7ff8f3c21b3c - <unknown>
[        ]    6:     0x7ff8f3c219cf - <unknown>
[        ]    7:     0x7ff8f3c1f407 - <unknown>
[        ]    8:     0x7ff8f3c216f9 - <unknown>
[        ]    9:     0x7ff8f3d6abc0 - <unknown>
[        ]   10:     0x7ff8f3d6ab0c - <unknown>
[        ]   11:     0x7ff8f39f3eff - <unknown>
[        ]   12:     0x7ff8f39f3f26 - <unknown>
[        ]   13:     0x7ff8f39ce1e8 - <unknown>
[        ]   14:     0x7ff8f39b6a43 - <unknown>
[        ]   15:     0x7ff8f39b3a44 - <unknown>
[        ]   16:     0x7ff8f39b7dd5 - <unknown>
[   +1 ms]   17:     0x7ff8f39b1cb1 - <unknown>
[        ]   18:     0x7ff8f39b1ef3 - <unknown>
[        ]   19:     0x7ff8f39b1b2b - <unknown>
[        ]   20:     0x7ff8f39b5354 - <unknown>
[        ]   21:     0x7ff8f39b7b6a - <unknown>
[        ]   22:     0x7ff8f39b7620 - <unknown>
[        ]   23:     0x7ff8f3bf6595 - <unknown>
[        ]   24:     0x7ff8f3beeefb - <unknown>
[        ]   25:     0x7ff8f3bfa21e - <unknown>
[        ]   26:     0x7ff8f3beef3e - <unknown>
[        ]   27:     0x7ff8f3bef03c - <unknown>
[   +1 ms]   28:     0x7ff8f3bef1f3 - <unknown>
[        ]   29:     0x7ff8f3beef9a - <unknown>
[        ]   30:     0x7ff8f3bfa2ee - <unknown>
[        ]   31:     0x7ff8f3bfa0ad - <unknown>
[        ]   32:     0x7ff8f3bed16e - <unknown>
[        ]   33:     0x7ff8f3c253fc - <unknown>
[        ]   34:     0x7ff934ec7034 - BaseThreadInitThunk
[        ]   35:     0x7ff936ec2651 - RtlUserThreadStart

**Comment by fzyzcjy** [comment]
That stacktrace is useless since it only contains addresses without symbols.

Could you please firstly learn how to provide useful information for other people to debug. Thanks.

**Comment by coolit** [comment]
@fzyzcjy 
Finally found the bug as below, which is not deteced by rustc 1.59.0, but deteced by the bridge.
```rust
pub fn go_inside(
    string_trans_direction: String,
    str_source_ori: String,
    str_target_ori: String,
) -> String {
    test_now();
    return "hellonow".to_owned();
}
fn test_now() {
    println!("hello 002");
    let map: HashMap<usize, String> = HashMap::new();
    let mut map_you: HashMap<usize, Vec<String>> = HashMap::new();
    map_you.insert(0, vec!["0===5".to_owned()]);
    for (k, v) in &map_you {
        if map.contains_key(&(k - 1)) {
            println!("hello");
        }
    }
}
```

**Comment by fzyzcjy** [comment]
Sounds like not a problem with bridge, but build mode. In Rust's debug build, this should throw overflow error (as expected). In Rust's release build, no check is performed even if this is a bad operation.

**Comment by coolit** [comment]
yes, thank you.

**Comment by fzyzcjy** [comment]
You are welcome.
