### ISSUE TITLE
C header generator add white-list or black-list or only exports input rust file includes functions and structs

### ISSUE THREAD

**Issue by chenbaiyu0414** [fzyzcjy/flutter_rust_bridge#388]
**Is your feature request related to a problem? Please describe.**
Current C header generator seems only suits for pure rust lib, but when it is a mixed project (rust with C/C++, etc), the generator will generate other language's extern functions or structs, which are use for internal rust project but exported from rust lib. 

for example

```c
// function.h
int add(int a, int b) {
    return a + b;
}
```

```rust
// bindings.rs
extern "C" fn add(a:i32, b:i32) -> i32;
```

```rust
// api.rs
pub fn add_use_c(a:i32,b:i32) -> i32 {
    add(a, b)
}
```

then generate it
`flutter_rust_bridge_codegen -r api.rs -d generated_bridge.dart -c api.h`

the generated C header will both contains `int add(int a, int b)` and `int add_use_c(int a, int b)` which fisrt comes from `bindings.rs` and seconed comes from `api.rs`

obviouslly, the `add` function in `bindings.rs` just used in internal, the `add_use_c` funtion in `api.rs` is the real actual funtion should be exported because it already specified as the input for generator

and those some structs has same problem

**Describe the solution you'd like**
Add white-list or black-list to allow/disallow which functions and structs should generate/ignore like `bindgen`.
or only resolve the input file contains functions/structs (personally prefer)

**Comment by Desdaemon** [comment]
A temporary workaround is to put a `/// cbindgen:ignore` on items you don't want to expose.

**Comment by fzyzcjy** [comment]
Agree with @Desdaemon. We use `cbindgen` under the hood

**Comment by Heasn** [comment]
> A temporary workaround is to put a `/// cbindgen:ignore` on items you don't want to expose.

That's work! Thanks



> Agree with @Desdaemon. We use `cbindgen` under the hood

Maybe you could add some tips about `cbindgen` in docs,  thanks for such awesome project.

**Comment by fzyzcjy** [comment]
@Heasn You are welcomed to make a simple PR for it :)
