### ISSUE TITLE
[Bug] generated rust file called ambiguous `into_dart` method

### ISSUE THREAD

**Issue by Congyuwang** [fzyzcjy/flutter_rust_bridge#390]
### Describe the bug

In generated `bridge_generated.rs`, the number used for encoding enum variants called an ambiguous `into_dart` method:
![截屏2022-03-13 下午11 28 43](https://user-images.githubusercontent.com/52687642/158069016-66cd71fd-9d1c-414c-83fe-3de0c230c293.png)
which makes the compiler emit the following error:
![截屏2022-03-13 下午11 02 01](https://user-images.githubusercontent.com/52687642/158069020-e02087c4-ed6c-4a8c-893e-e73aa6770cf3.png)
This is because `IntoDart` is implemented for `i32`, `i64` and many other integer types, and the compiler seem unable to decide which integer type the literal here means.

This can be fixed by specifying the integer type for the encoding integer (i.e. `27i32.into_dart()`)

### Codegen logs with `RUST_LOG=debug` env variable

```shell
NULL
```

**Comment by fzyzcjy** [comment]
Nice catch! You are welcomed to make a PR for it, possible just one line here:

https://github.com/fzyzcjy/flutter_rust_bridge/blob/458fc115bbf67011ea82d87652624defd0e8926c/frb_codegen/src/generator/rust/ty_enum.rs#L207

`let tag = format!("{}.into_dart()", idx);` change to `let tag = format!("{}i32.into_dart()", idx);`.

Btw interestingly it compiles nicely on the example (https://github.com/fzyzcjy/flutter_rust_bridge/blob/458fc115bbf67011ea82d87652624defd0e8926c/frb_example/pure_dart/rust/src/bridge_generated.rs#L1822) and on CI, maybe b/c rust versions? Anyway that should be a bug.

**Comment by Congyuwang** [comment]
Kind of strange, I fail to reproduce the problem today. I guess integer literal should default to `i32`. Though I don't really understand what caused this issue, it perhaps is not a problem of `flutter_rust_bridge`.

**Comment by fzyzcjy** [comment]
Interesting. Maybe a problem of Rust compiler version? For example, old/new rust compiler may not understand it is i32?
