### ISSUE TITLE
Question on async and thread with rust

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#396]
From official tutorial here:http://cjycode.com/flutter_rust_bridge/feature/async_dart.html,
It is recommended that  the rust code should be set at the same thread as the dart (UI)thread, and the rust code would be translated into aysnc code when interacting with the flutter(UI) part as default.

My question is , since async is not always the best practice if the time-consuming part code(the rust part) is NOT IO-intensive code (usually compute-intensive), why would your still suggest that putting all parts to the same thread?

By the way, I've a side question related to flutter:  when building flutter as a windows application, does it still has a runtime with garbage collector --- The flutter officially says that code woulde be compiled into native code, I guess it is just binary code on windows, right? ---but still with a runtime of garbage collector?

**Comment by fzyzcjy** [comment]
> My question is , since async is not always the best practice if the time-consuming part code(the rust part) is NOT IO-intensive code (usually compute-intensive), why would your still suggest that putting all parts to the same thread?

I am not suggesting putting rust and dart in the same thread. Indeed, by default, the rust functions you write in `api.rs` will be run in a thread pool, so rust code will be executed in *different* thread than dart.

**Comment by fzyzcjy** [comment]
> By the way, I've a side question related to flutter: when building flutter as a windows application, does it still has a runtime with garbage collector --- The flutter officially says that code woulde be compiled into native code, I guess it is just binary code on windows, right? ---but still with a runtime of garbage collector?

Sure. This is because its runtime (e.g. garbage collector, memory allocator, thread manager, anything else...) is *also* compiled into the native binary that ships to your windows :)

**Comment by dbsxdbsx** [comment]
@fzyzcjy , thanks your reply. Just another question on dart.   As C# also has a garbage collector, so I think the biggest difference between dart and C# is that there is no need for dart to translate code when application is running, am I right?

If this is the case, does it mean that flutter could run faster than C# on platform with native code compiled into, like linux, windows and embedding system ... but not android (since there is a JVM)?

And also, is this an ALWAYS correct statement  --- "Languages with garbage collector is slower and more memory cost compared to language with no runtime, suppose there is no memory safety issue" ?

I came up the above questions when I want to build application with UI on an embedding system, and flutter team just has the ambition to cross all platforms, meanwhile people still suspect the efficiency of language with GC. 

I did refer to this link a lot time : https://medium.com/flutter/flutter-dont-fear-the-garbage-collector-d69b3ff1ca30, but I didn't get convinced.


Usually people don't like doing system coding with garbage collector, even it runs as native binary, since it would slow down

**Comment by fzyzcjy** [comment]
> As C# also has a garbage collector, so I think the biggest difference between dart and C# is that there is no need for dart to translate code into binary like C# does when application is running, am I right?

Dart has both a JIT and AOT mode. For performance, we use AOT in release build. Then it creates a binary containing assembly code.

> If this is the case, does it mean that flutter could run faster than C# on platform with native code compiled into, like linux, windows and embedding system ... but not android (since there is a JVM)?

Well you may need to learn about JIT and AOT.

> And also, is this an ALWAYS correct statement --- "Languages with garbage collector is slower and more memory cost compared to language with no runtime, suppose there is no memory safety issue" ?

Surely not "always" since too absolute :)

Imagine this case: Your code create a million small objects and then quickly you never need it (common for flutter build methods). With GC language, the garbage collector may collect them later in one go, and for Dart'c GC it is quite efficient if most of your objects are not needed any more. But for a lang without GC, maybe you will write down code that frees the object whenever you do not need it. Then a million `free` may not be very fast (but surely, you can tailor your code to make it run faster by adding complexity, or even simulating the GC's behavior if you like)

I am not an expert in compilers (just amateur), so take the words above with a grain of salt :)

> I came up the above questions when I want to build application with UI on an embedding system, and flutter team just has the ambition to cross all platforms, meanwhile people still suspect the efficiency of language with GC.
Usually people don't like doing system coding with garbage collector, even it runs as native binary, since it would doing extra work with extra memory cost.

Good question! 

Maybe have a look at: https://flutter.dev/multi-platform/embedded

**Comment by fzyzcjy** [comment]
By the way, what embedding system are you targeting on? I guess some very old android devices (which I myself do need to support) has so weak cpu/memory that it may even be weaker than some embedding systems

**Comment by dbsxdbsx** [comment]
> > As C# also has a garbage collector, so I think the biggest difference between dart and C# is that there is no need for dart to translate code into binary like C# does when application is running, am I right?
> 
> Dart has both a JIT and AOT mode. For performance, we use AOT in release build. Then it creates a binary containing assembly code.
> 
> > If this is the case, does it mean that flutter could run faster than C# on platform with native code compiled into, like linux, windows and embedding system ... but not android (since there is a JVM)?
> 
> Well you may need to learn about JIT and AOT.
> 
> > And also, is this an ALWAYS correct statement --- "Languages with garbage collector is slower and more memory cost compared to language with no runtime, suppose there is no memory safety issue" ?
> 
> Surely not "always" since too absolute :)
> 
> Imagine this case: Your code create a million small objects and then quickly you never need it (common for flutter build methods). With GC language, the garbage collector may collect them later in one go, and for Dart'c GC it is quite efficient if most of your objects are not needed any more. But for a lang without GC, maybe you will write down code that frees the object whenever you do not need it. Then a million `free` may not be very fast (but surely, you can tailor your code to make it run faster by adding complexity, or even simulating the GC's behavior if you like)
> 
> I am not an expert in compilers (just amateur), so take the words above with a grain of salt :)
> 
> > I came up the above questions when I want to build application with UI on an embedding system, and flutter team just has the ambition to cross all platforms, meanwhile people still suspect the efficiency of language with GC.
> > Usually people don't like doing system coding with garbage collector, even it runs as native binary, since it would doing extra work with extra memory cost.
> 
> Good question!
> 
> Maybe have a look at: https://flutter.dev/multi-platform/embedded
> 
> And, what about building a prototype? For example, a complex list view, some complex UI, etc. Just do the UI part that you think is the most complex and may have problems, and you will see how good/bad it is.

Related to the question on comparison to C#, I do know the difference between JIT and AOT, and I know there is no VM in release mode of dart.   I just not quite sure what my application code compiled into within android in release mode --- assembly code or java bytecode (which need to be dynamically translated).  

the section "How does Flutter run my code on Android" in this [link](https://docs.flutter.dev/resources/faq) said "The engine’s C and C++ code are compiled with Android’s NDK. The Dart code (both the SDK’s and yours) are ahead-of-time (AOT) compiled into **native**, ARM, and x86 libraries.". The word native is little unclear in the context of android.

**Comment by dbsxdbsx** [comment]
> By the way, what embedding system are you targeting on? I guess some very old android devices (which I myself do need to support) has so weak cpu/memory that it may even be weaker than some embedding systems

@fzyzcjy, frankly, there are 3 projects I want to do---all need UI and some AI technique.
1. a chess program--- I want to run it on platform windows first, then put it on web;
2. a video play program on android TV --- and I want to do some fancy things like "object detection" when video is rendering, and also I want to make it as a mobile app later;
3. mechanical arm with a screen--- I also hope there is camera on it, which detects my arm posture and simulate correspondingly.

All these projects require similar technology stack, so I hope there is  a single framework can work around over.

On the AI side (the logic part), I've worked around it with rust crate: https://github.com/LaurentMazare/tch-rs.  I made it worked on windows, but still don't know how to transfer it into android like platform. 

On the UI side, I decided to use flutter, since it is best for cross-platform.

And finally when combining, I've yet decided how to do it , maybe with this your  project,   or maybe something else , like this: https://github.com/nativeshell/nativeshell.

**Comment by fzyzcjy** [comment]
> Related to the question on comparison to C#, I do know the difference between JIT and AOT, and I know there is no VM in release mode of dart. I just not quite sure what my application code compiled into within android in release mode --- assembly code or java bytecode (which need to be dynamically translated).

assembly. Indeed, `libapp.so`. It has exactly same format like when you compile a C program or something like that in android.

**Comment by fzyzcjy** [comment]
> on android TV

android TV sounds like powerful enough to run Flutter :)

> do some fancy things like "object detection" when video is rendering

that may be more resource consuming compared with flutter. write this in rust (possibly with `tflite` as I have done)

> On the AI side (the logic part), I've worked around it with rust crate: https://github.com/LaurentMazare/tch-rs. I worked it out on windows, but still don't know how to transfer it (as it need extra library) into android like platform.

tflite works for me

> And finally when combining, I've yet decided how to do it , maybe with this your project, or maybe something else , like this: https://github.com/nativeshell/nativeshell.

IMHO mine is more suitable (and is more stable - that one is "experimental"), and the advantages can be seen in https://github.com/fzyzcjy/flutter_rust_bridge#-advantages so I do not repeat here. But I am also quite curious how that framework performs, so feel free to provide some insights if you use that framework :)

**Comment by dbsxdbsx** [comment]
@fzyzcjy , thanks your reply again, I would give it a second thought at present, so I closed the issue now. Maybe it woulde be reopened if I meet new question. ^_^

**Comment by fzyzcjy** [comment]
You are welcome!
