### ISSUE TITLE
[Question/Feature request] Executor

### ISSUE THREAD

**Issue by LambdaMan2K** [fzyzcjy/flutter_rust_bridge#397]
Hi :) thanks for sharing. 

well I am just thinking here. but I can see you are using a threadpool with a fixed num of threads,. I think it would be great if we had a wrapper around an executer instead, so we could use rayon, tokio etc as long they have a spawn method. 
and then expose this so we can use the pool in our crates ?  this should  be posable with feature flags right?

maybe this is out of the scope for your vison for the lib. but  anyway thanks again

**Comment by fzyzcjy** [comment]
You are welcome!

>  but I can see you are using a threadpool with a fixed num of threads,. I think it would be great if we had a wrapper around an executer instead, so we could use rayon, tokio etc as long they have a spawn method.
and then expose this so we can use the pool in our crates ? this should be posable with feature flags right?

You can create your own Executors and use that. So you are free to do anything, e.g. not use a threadpool.

http://cjycode.com/flutter_rust_bridge/feature/handler.html

**Comment by LambdaMan2K** [comment]
cool , I  will look into that . thanks!

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by LambdaMan2K** [comment]
and sorry for not reading the docs good enough :o

**Comment by fzyzcjy** [comment]
That's all right :)
