### ISSUE TITLE
[Question] Sending data from rust

### ISSUE THREAD

**Issue by LambdaMan2K** [fzyzcjy/flutter_rust_bridge#398]
Hi again :) well okay I am trying to figure out what is the best approach to use a stream for events  when it is not possible to send rust enums with data. 
so is the only way to this using a global state with streams for each type and guard it with a mutex?  if  that is possible. 
thanks

**Comment by LambdaMan2K** [comment]
this this I read the doc before asking and yes it is a good example of a stream. but what I am looking for is a way to use a stream for multi[e data types like a enum with  like so
```
pub enum Test{
    LoginUrl(String),
    LoginStatus(bool),
    UserInfo(Arc<UserInfo>),
    Accounts(Vec<AccountInfo>),
}
```

or way to setup multipe streams at once. for each type

**Comment by LambdaMan2K** [comment]
and in the doc it says it is not supported yet
for external types
```
// It works with basic enums too
// Enums with struct variants are not yet supported
#[frb(mirror(ApplicationMode))]
pub enum _ApplicationMode {
    Standalone,
    Embedded,
}

```

**Comment by fzyzcjy** [comment]
Oh I see your question.

Enums with struct variants are not yet supported for *mirror* types. If your type is defined in your crate (instead of 3rd party) it should be ok imho.

Btw I am worried `Arc` may not be supported.

**Comment by LambdaMan2K** [comment]
ok yes my enum is sadly in a external crate cuz I use it in more than one crate crates, and yes i can understand why arc is not supported.  the only way this can work then if all crates are in one single crate, hmm okay will just think about it some more. thanks

**Comment by LambdaMan2K** [comment]
okay a dirty solution might be this

```

static X: Lazy<XXXX> = Lazy::new(|| XXXX{
    x: Stream::new(),
    x_1: Stream::new(),
});

pub struct Stream<T>(OnceCell<StreamSink<T>>)
where
    T: IntoDart;
impl<T: IntoDart> Stream<T> {
    pub fn new() -> Self {
        Self { 0: OnceCell::new() }
    }

    pub fn init(&self, s: StreamSink<T>) {
        let _ = self.0.set(s);
    }
    pub fn add(&self, v: T) {
        self.0.get().unwrap().add(v);
    }
}

pub struct XXXX{
    pub x: Stream<bool>,
    pub x_1: Stream<bool>,
}
```
then it them all like this
```
pub fn x(stream: StreamSink<bool>) -> anyhow::Result<()> {
    let _ = X.x.init(stream);
    Ok(())
}
```
etc

then just call X.x.add

**Comment by fzyzcjy** [comment]
`OnceCell` seems like a good solution for singletons like that!

**Comment by fzyzcjy** [comment]
Btw I update the doc mentioning OnceCell https://github.com/fzyzcjy/flutter_rust_bridge/commit/6b84e77141cd9c2fbafaac30074b0721014fd0c4 Thanks

**Comment by LambdaMan2K** [comment]
great :)

**Comment by LambdaMan2K** [comment]
can you please guide me how I would go about sending a struct via stream when structs doss not impl  IntoDart?

**Comment by fzyzcjy** [comment]
It should automatically implement imho. try to put struct in api.rs, or the same crate. or use the "mirror" feature

**Comment by LambdaMan2K** [comment]
hm the Test struct is in api.rs that what is strange

**Comment by fzyzcjy** [comment]
could you plz make a reproducible sample since this seems to be a bug

**Comment by LambdaMan2K** [comment]
btw I am using 
flutter_rust_bridge = "1.23.0"
and I also tried with version "1"  which the template comes with

**Comment by LambdaMan2K** [comment]
returning a struct works 

```
pub struct Test {
    pub name: String,
}
pub fn test() -> Test {
    Test {
        name: "hello".to_string(),
    }
}
```
but StreamSink<Test> doss not, so yes I guess this is bug as you said.

**Comment by fzyzcjy** [comment]
Oh I did not realize your comment is a reproducible sample. Could you please provide a self-contained `api.rs` file, or better, a github repo reproducing the behavior?

**Comment by LambdaMan2K** [comment]
yes okay, 
just use this template: https://github.com/Desdaemon/flutter_rust_bridge_template
and the api.rs paste this in
```
use flutter_rust_bridge::StreamSink;

pub struct Test {
    pub name: String,
}
pub fn test(sink: StreamSink<Test>) -> anyhow::Result<()> {
    Ok(())
}
```

**Comment by fzyzcjy** [comment]
Sounds great! Could you please also paste all logs

> Run code generator with RUST_LOG environment variable set to debug. For example, RUST_LOG=debug flutter_rust_bridge_codegen your_args.

**Comment by fzyzcjy** [comment]
By the way I suspect it is because we forget to address the `Test` class inside StreamSink to generate the into-dart trait.

What about adding something like

```
pub fn dummy(a: Test) {}
```

does it generate correctly? If so this is a temporary workaround

**Comment by LambdaMan2K** [comment]
well yes 
```
pub fn test(test: Test)
```
works, but StreamSink<Test> doss not.

**Comment by fzyzcjy** [comment]
Good. Then we know

1. The cause of bug: It forgets to notice that the generic parameter inside `StreamSink`
2. There is a workaround currently

Do you have interest in making a PR and fixing it?

**Comment by LambdaMan2K** [comment]
I just dont know what the workaround or the solution is at this pont. I havent looked at the source code too  much atm

**Comment by fzyzcjy** [comment]
> I just dont know what the workaround or the solution is at this point.

Whenever rust complains sth like "the trait `From<YourStructName>` is not implemented for `DartCObject`", add a line: `pub fn dummy(a: YourStructName, b: YourAnotherStructNameThatFails, c: YetAnother) {}`

**Comment by LambdaMan2K** [comment]
doss not seam to work,  you mean just do that in the api.rs file? 
like you said
```
pub fn dummy(a: Test) {}
```
same error

**Comment by fzyzcjy** [comment]
All right. I will examine that.

**Comment by LambdaMan2K** [comment]
:) and again, take your time.  
I appreciate it.

**Comment by fzyzcjy** [comment]
:)

**Comment by LambdaMan2K** [comment]
hi again, have you had a chance to confirm if this is a bug? or it is just me :)

**Comment by fzyzcjy** [comment]
I am busy doing something else other than rust so have no time now. But I guess this is a bug and you are welcomed to make a PR and fix it.

**Comment by LambdaMan2K** [comment]
Sure I will make a PR if I fix it myself at some point :)

**Comment by LambdaMan2K** [comment]
Okay this seams to  be a problem for all types you define yourself even (String, String),  do you have any idea of where to look? is this in a macro ? it is just odd that this has  not been noticed before :O  I makes streams limited in use :)

And I am not saying you are the one to fix it,  I am just confused where to look especially if this is in a proc macro  :)

**Comment by fzyzcjy** [comment]
Interesting... 

FYI, I have this in my own code in production and it works great:

```
pub struct LogEntry {
    pub time_millis: i64,
    pub level: i32,
    pub tag: String,
    pub msg: String,
}

pub fn create_log_stream(s: StreamSink<LogEntry>) -> Result<()> {
    ...
}

// it generates

#[no_mangle]
pub extern "C" fn wire_create_log_stream(port_: i64) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "create_log_stream",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || move |task_callback| create_log_stream(task_callback.stream_sink()),
    )
}

impl support::IntoDart for LogEntry {
    fn into_dart(self) -> support::DartCObject {
        vec![
            self.time_millis.into_dart(),
            self.level.into_dart(),
            self.tag.into_dart(),
            self.msg.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for LogEntry {}
```

**Comment by fzyzcjy** [comment]
Could you please provide a full reproducible sample, and put it into a github repository, such that I can examine it.

**Comment by fzyzcjy** [comment]
I try to reproduce it, but it works well without errors. See https://github.com/fzyzcjy/flutter_rust_bridge/commit/788c524911f73914d600984ed7c68f4a7e79dc42.

Maybe it is because you misuse it? Could you please share a minimal reproducible sample and put it into a separate github repository?

**Comment by LambdaMan2K** [comment]
here you go 
https://github.com/LambdaMan2K/TestAppTmp.git

```
 fn test(sink: StreamSink<(String, String)>) -> anyhow::Result<()> {
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<(String, String)>` is not implemented for `DartCObject`
```

**Comment by fzyzcjy** [comment]
https://github.com/LambdaMan2K/TestAppTmp/blob/94b46f1640f3469e8a46252db5c73311ac373bb5/native/Cargo.lock#L49

1.15.1 is so ancient

**Comment by LambdaMan2K** [comment]
well it give the same error when using flutter_rust_bridge = "1.25.0"

**Comment by LambdaMan2K** [comment]
oh and it is not my template I just forked it. I think I found it from the book

**Comment by LambdaMan2K** [comment]
well same error using 
flutter_rust_bridge = "1.25.0"

**Comment by LambdaMan2K** [comment]
it just wont compile, I have no idea what I am doing wrong.  and rust analyzer detect the error as well

**Comment by LambdaMan2K** [comment]
done

**Comment by fzyzcjy** [comment]
Could you please try the struct mode, like what I did here: https://github.com/fzyzcjy/flutter_rust_bridge/commit/788c524911f73914d600984ed7c68f4a7e79dc42

I am not sure anonymous tuples are supported or not here. But anyway converting them to structs are more clear for the readers, and Dart does not support anonymous tuples as well.

**Comment by LambdaMan2K** [comment]
yes it was just for showcase i used tuples the effect is the same sadly

**Comment by fzyzcjy** [comment]
What about follow my code in https://github.com/fzyzcjy/flutter_rust_bridge/commit/788c524911f73914d600984ed7c68f4a7e79dc42 and migrate them to your https://github.com/LambdaMan2K/TestAppTmp.git . IMHO it should not have problems.

**Comment by fzyzcjy** [comment]
Wait a minute: You seem to **not run the code generator**! Please:

1. Run the code generator to update bridge_generated.rs
2. Use structs instead of anonymous tuples as in 788c524

**Comment by LambdaMan2K** [comment]
doss the repo compile for you??

**Comment by fzyzcjy** [comment]
The `fn test` seems wrong. What about `pub fn test`

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/commit/788c524911f73914d600984ed7c68f4a7e79dc42 compiles excellently so please follow that exactly.

**Comment by LambdaMan2K** [comment]
adding pub to the fn did nothing, and I am not sure what you want me to try ? the link is  a bunch of commits of dart code?

**Comment by LambdaMan2K** [comment]
If  you just wanted me to do  
```
pub struct MyStreamEntry {
    pub hello: String,
}

// https://github.com/fzyzcjy/flutter_rust_bridge/issues/398 reports a compile error like this
pub fn handle_stream_of_struct(sink: StreamSink<MyStreamEntry>) -> anyhow::Result<()> {
    Ok(())
}

```
then 
| pub fn handle_stream_of_struct(sink: StreamSink<MyStreamEntry>) -> anyhow::Result<()> {
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<MyStreamEntry>` is not implemented for `DartCObject`

**Comment by Desdaemon** [comment]
@LambdaMan2K I was just checking your repo, I think you haven't run the codegen (`flutter_rust_bridge_codegen`) yet since bridge_generated.rs is missing some code. Can you try running it and see if it changes anything?

**Comment by fzyzcjy** [comment]
> @LambdaMan2K I was just checking your repo, I think you haven't run the codegen (`flutter_rust_bridge_codegen`) yet since bridge_generated.rs is missing some code. Can you try running it and see if it changes anything?

+1

**Comment by LambdaMan2K** [comment]
you are totally right! turns out that what threw me off all the time was the version, feels bad man. I thought I had the latest version cuz  I missed the cargo lock file :s sorry for the confusion guys and thank you for your time. 

can I ask more last thing when I add new dependencies to the crate do I have to update the rust cmake file in some way am not use to cmake?  if you dont have the answer then please just close this question :)

**Comment by Desdaemon** [comment]
> can I ask more last thing when I add new dependencies to the crate do I have to update the rust cmake file in some way am not use to cmake?

No, you don't have to because Cargo handles that; what is in the CMake file is to make Cargo work *with* CMake, so ideally you shouldn't have to edit it.

**Comment by LambdaMan2K** [comment]
great thanks again!

**Comment by LambdaMan2K** [comment]
> > can I ask more last thing when I add new dependencies to the crate do I have to update the rust cmake file in some way am not use to cmake?
> 
> No, you don't have to because Cargo handles that; what is in the CMake file is to make Cargo work _with_ CMake, so ideally you shouldn't have to edit it.

when building I get cmake warrnings like 
No linker preference for target "crate_name" 
do you know what this  means :)  it is all local crate dependencies I use. My project is split up into multiple crates in a workspace and the cmake file is just wired against the  toml file in the native lib where the api.rs is  located.  and the native lib is of cuz the entry point for the rust side of my project.
