### ISSUE TITLE
Is it possbile to build an Android app with  a third party library as dependent on rust side?

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#399]
From the rust side, if there is a crate like [this](https://github.com/twistedfall/opencv-rust), which need to install some libraries as dependency, is  it possible  to transfer the whole as an app without issue on Android？

**Comment by fzyzcjy** [comment]
Sure. Indeed I have opencv + rust in my app in production.

**Comment by dbsxdbsx** [comment]
> Sure. Indeed I have opencv + rust in my app in production, using exactly that crate.

@fzyzcjy, Is it essential to install the linux library manually  on Android, or do nothing just wrap the whole project with `flutter_rust_bridge` as an Apk and do installation normally?

If the second one is the case, does it mean that I can debug and test it even on windows?  Does the dependencies copied to android when doing installation?    

And also, how do you solve the cuda issue， since cuda canot be installed on android.

**Comment by fzyzcjy** [comment]
> Is it essential to install the opencv linux library manually on Android, or do nothing just wrap the whole project with flutter_rust_bridge as an Apk and do installation normally?

Just bundle `libopencv.so` or something like that in the android app and everything is fine. Just like when people use opencv with c++ for android app. In other words, the user only see a very normal apk and nothing special.

**Comment by fzyzcjy** [comment]
> If the second one is the case, does it mean that I can debug and test it even on windows? Does the dependencies copied to android when doing installation?

Surely you can run rust+opencv+flutter on windows. you need a new compilation pipeline, but the code is the same.

**Comment by fzyzcjy** [comment]
> And also, how do you solve the cuda issue， since cuda canot be installed on android.

opencv does not need cuda, and cuda is for nvidia GPU which android usually do not have. If you want to run neural networks, try `tflite`.

**Comment by dbsxdbsx** [comment]
> > If the second one is the case, does it mean that I can debug and test it even on windows? Does the dependencies copied to android when doing installation?
> 
> Surely you can run rust+opencv+flutter on windows. you need a new compilation pipeline, but the code is the same.

@fzyzcjy, thanks your answer. But I mean that I  have no doubt on windows, as I am coding on windows. I  curious on how to transfer the opencv lib to android, since the complied opencv lib shouln't be able to run on android directly.

**Comment by fzyzcjy** [comment]
> I curious on how to transfer the opencv lib to android, since the complied opencv lib shouln't be able to run on android directly.

opencv has android build on official website.

**Comment by dbsxdbsx** [comment]
@fzyzcjy , now I see.  So generally, if the 3rd dependencies has no target-platform library, It is impossible to work it around through by  `flutter_rust_bridge`.

**Comment by fzyzcjy** [comment]
> So generally, if the 3rd dependencies has no target-platform library, It is impossible to work it around through by flutter_rust_bridge.

frb is just a tiny bridge. You will then need to discuss with *that* lib's owner.
