### ISSUE TITLE
[Bug] impl support::IntoDartExceptPrimitive is not generated for complex enum

### ISSUE THREAD

**Issue by alanlzhang** [fzyzcjy/flutter_rust_bridge#403]
### Describe the bug

![image](https://user-images.githubusercontent.com/59032810/163677411-93e24734-7110-4e8e-a706-5300bccae947.png)

related code:
```
pub enum Primitive {
    Text {
        version: i64,
        text_data: String,
        x: f64,
        y: f64,
    },
    Polygon {
        version: i64,
        polygon_data: Vec<f64>,
    },
    Polyline {
        version: i64,
        polygon_data: Vec<f64>,
        polyline_data: Vec<f64>,
        stroke_width: f64,
    },
}

pub struct LayerData {
    pub id: LayerId,
    pub data: Vec<Primitive>,
}
```

if add 
```
impl support::IntoDartExceptPrimitive for Primitive {}
```
manually, then everything goes ok.

### Codegen logs with `RUST_LOG=debug` env variable

```shell
Not relative
```

### OS

Windows

### Version of `flutter_rust_bridge_codegen`

1.24.0

**Comment by fzyzcjy** [comment]
Hmm... Seems to be related to enums? /cc @Desdaemon who wrote that great part.

By the way can you try rename `Primitive` to something else since `IntoDartExceptPrimitive` looks quite confusing as it also mentions "primitive". I am not sure whether the code misunderstands the word (though most probably not)

**Comment by alanlzhang** [comment]
Just tried renaming to Element which does not change anything.  

IntoDartExceptPrimitive means except Rust primitive (aka u8, u16 ...). It's primary for Vec<T> so structs and enums will convert to List<T> in dart, but Vec<u8> will convert to Int8List.
