### ISSUE TITLE
[Bug] Failed to load dynamic library for android 

### ISSUE THREAD

**Issue by DAOCUONG** [fzyzcjy/flutter_rust_bridge#405]
### Describe the bug

Tried  template project for android build but got error can load 
Have check there are so files in jniLibs folder under android/app/main/jniLibs

The following ArgumentError was
thrown building Builder:
Invalid argument(s): Failed to load
dynamic library 'libnative.so':
dlopen failed: library
"libnative.so" not found

### Codegen logs with `RUST_LOG=debug` env variable

```shell
Flutter run

The following ArgumentError was
thrown building Builder:
Invalid argument(s): Failed to load
dynamic library 'libnative.so':
dlopen failed: library
"libnative.so" not found
```

### Expected behavior

Flutter run should work in android

### OS

Mac OS

**Comment by fzyzcjy** [comment]
/cc @Desdaemon who made the template

By the way have you tried following *all* steps of the book?

**Comment by DAOCUONG** [comment]
yeah follow all the steps it should work 
<img width="383" alt="Screen Shot 2022-04-17 at 7 30 59 PM" src="https://user-images.githubusercontent.com/5289711/163738015-7b9dd481-3d1c-473d-9271-7984627ac037.png">

**Comment by Desdaemon** [comment]
I can't verify this yet, but a possible cause is that you're running on x86 Android (simulator or otherwise), in which case you need to add these targets to the call to cargo-ndk in build.gradle.

```
cargo ndk ... -t x86 -t x86_64 ...
```

**Comment by DAOCUONG** [comment]
<img width="289" alt="Screen Shot 2022-04-18 at 4 10 03 PM" src="https://user-images.githubusercontent.com/5289711/163878603-0ac8b84e-a8c6-4fa0-a0b8-47a54864c392.png">

**Comment by DAOCUONG** [comment]
I think it solve me issue Thanks for helping @fzyzcjy @Desdaemon

**Comment by DAOCUONG** [comment]
For running with simulator need to build for x86 and x86_64

**Comment by fzyzcjy** [comment]
@Desdaemon Maybe we should add a bit doc about this scenario in the book?

**Comment by Desdaemon** [comment]
> @Desdaemon Maybe we should add a bit doc about this scenario in the book? (Maybe a section at http://cjycode.com/flutter_rust_bridge/template/setup_android.html or somewhere else?)

I'm considering making this option the default in the template as well, so maybe when I'm less preoccupied I'll put in the changes.

**Comment by fzyzcjy** [comment]
@Desdaemon Take you time :)
