### ISSUE TITLE
Publish precompiled binary.

### ISSUE THREAD

**Issue by nurmohammed840** [fzyzcjy/flutter_rust_bridge#436]
I suggest , you to publish precompiled binary in [release section](https://github.com/fzyzcjy/flutter_rust_bridge/releases/).

I am using windows (x64)

**Comment by fzyzcjy** [comment]
What about directly install it using cargo install? That sounds like the standard approach.

**Comment by nurmohammed840** [comment]
> What about directly install it using cargo install? That sounds like the standard approach.

Will I did, It took about 5+ minutes to compile...
and everybody need to compile, same thing over and over

**Comment by fzyzcjy** [comment]
Hmm good suggestion. I will consider that.

**Comment by fzyzcjy** [comment]
I have published macos precompiled version by github actions long ago. Feel free to PR for windows :)

**Comment by Desdaemon** [comment]
I'd be interested in this as well. I've done some work on my fork, but I think the biggest blocker on MacOS is signing binaries for the convenience of the users. If @fzyzcjy has an idea how to manage this I'd love to get this issue done.

**Comment by fzyzcjy** [comment]
> I have published macos precompiled version by github actions long ago. Feel free to PR for windows :)

Ah wait... I have been replied to the wrong repo. I meant binary for https://github.com/fzyzcjy/flutter_convenient_test.

**Comment by fzyzcjy** [comment]
@Desdaemon IMHO we can do it step by step. For example, windows/linux first, and then macos.

For macos signing, maybe we can refer to `brew`'s documentation, which is a package manager like `apt-get` (linux) for macos people.

I am also considering a few other distributing possibilities:

1. provide the binary at the "github releases" (most inconvenient for users)
2. maybe https://github.com/alsuren/cargo-quickinstall? (sounds promising? haven't looked into details)
3. maybe release to package managers, such as apt-get for linux and brew for macos? (take some efforts to implement all these)

**Comment by Desdaemon** [comment]
I had a look at `cargo-binstall` and I was quite impressed by it! I do think it's more important now however to get CI builds to work so that people can distribute on top of them. I'm thinking of some common targets for distribution:
- Windows: `winget`, `scope`, Chocolatey etc.
- Unix: Linuxbrew, `cargo-binstall`, Appimages
- MacOS: Homebrew

On MacOS however I don't have as much experience with notarizing binaries on MacOS so I will have to defer to others.
