### ISSUE TITLE
[Bug] CI fails (seemingly due to reasons that will not affect users - but anyway should fix it)

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#450]
### Describe the bug

-

### Codegen logs with `RUST_LOG=debug` env variable

```shell
-
```

**Comment by sagudev** [comment]
Codegen should be rerun on repo and formater. https://github.com/fzyzcjy/flutter_rust_bridge/runs/6382440565?check_suite_focus=true is failing due to old [Cargo.toml.release](https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/Cargo.toml.release).

**Comment by fzyzcjy** [comment]
Agree. Feel free to make a PR :) (I am quite busy recently and may not have much time for this repo)
