### ISSUE TITLE
Allow rust struct generating freezed class in dart 

### ISSUE THREAD

**Issue by alanlzhang** [fzyzcjy/flutter_rust_bridge#459]
In rust we often define:
```rust
struct UserId(value: u64);
```
And use UserId in HashMap as keys.

Since tuple is not well supported in dart, we can define:
```rust
struct UserId { value: u64 }
```
And use it in maps/dicts as keys

But frb currently doesn't generate `==` and `hashCode` method for UserId in dart/flutter, so we can't use UserId as keys in dart, we had to unwrap it and use u64 as key type, it's not quit convient.

If we support generate @freezed (or even better any annotation) on struct, then we got `==` and `hashCode`, and can use it directly in maps.

**Comment by fzyzcjy** [comment]
Good suggestion! Looking forward to your PR :)

**Comment by alanlzhang** [comment]
Please review my PR ^_^

**Comment by fzyzcjy** [comment]
Sure :)
