### ISSUE TITLE
Refactor `mirror/non_final/...` annotations in a uniform way

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#468]
See discussion here:

https://github.com/fzyzcjy/flutter_rust_bridge/pull/463#discussion_r876517135

/cc @alanlzhang

**Comment by fzyzcjy** [comment]
👀 @alanlzhang

**Comment by alanlzhang** [comment]
I am too busy these days... -_-b 
Maybe I'll try it later, when I have some time.

**Comment by fzyzcjy** [comment]
Take your time :)
