### ISSUE TITLE
Use FFI with nativeshell

### ISSUE THREAD

**Issue by farshed** [fzyzcjy/flutter_rust_bridge#474]
Hi, I'm working with [nativeshell](https://github.com/nativeshell/nativeshell/) and I was wondering if it's possible to use flutter_rust_bridge with it. I'm following the docs but can't seem to figure out how the XCode linking part will work on macOS since nativeshell is a custom embedder and abstracts away all of that. Is there a "cross-platform" way to compile and link binaries or am I missing something?

**Comment by fzyzcjy** [comment]
> Hi, I'm working with [nativeshell](https://github.com/nativeshell/nativeshell/)

Btw are you project owner of nativeshell, or just using it :)

> if it's possible to use flutter_rust_bridge with it.

firstly try to run a hello-world rust function with that package. If that works, flutter_rust_bridge should work. Because flutter_rust_bridge is nothing but a code generator that generates some very normal Rust & Dart code.

**Comment by fzyzcjy** [comment]
Maybe you need to ask nativeshell's people about "how can I use my Rust code with it"

**Comment by farshed** [comment]
Appreciate your quick response.

> Btw are you project owner of nativeshell, or just using it :)

I'm just using it :p

> try to run a hello-world rust function with that package. If that works, flutter_rust_bridge should work

Okay so just an FYI, you can run rust code with nativeshell. It allows you to communicate between dart and rust via platform channels but I've noticed that they carry some overhead so I wanted to avoid it. 

The thing is that in nativeshell projects there is no platform specific code required because it's almost seamlessly cross-platform and the way it achieves that is by embedding the flutter engine into its own desktop port written in rust. This means that there are no macos, windows or linux folders. You just write your flutter code, `cargo run`, and it works. I hope this makes things a little clear.

> Maybe you need to ask nativeshell's people about "how can I use my Rust code with it"

You're right. I'll try asking this in the nativeshell repo. Someone might have already made it work. Thanks.

**Comment by fzyzcjy** [comment]
> via platform channels

Well, I mean "how to communicate via `dart:ffi` package" indeed.
