### ISSUE TITLE
Support chrono::NaiveDateTime mapping to dart DateTime

### ISSUE THREAD

**Issue by wentao** [fzyzcjy/flutter_rust_bridge#475]
**Is your feature request related to a problem? Please describe.**
We have a lot of data types that are using chrono::NaiveDateTime as properties, and we would like to be able to convert them to dart DateTime directly without creating proxy types that use i64 as the timestamps.

**Describe the solution you'd like**
The bridge converter can support mapping of chrono::NaiveDateTime to dart's DateTime type

**Describe alternatives you've considered**
We have used a walk around that for each struct we want to pass to dart, we create a proxy type of that and make the chrono::NaiveDateTime to i64 first, then pass that to the dart side; One the dart side, we have to do something similar, converting in64 timestamp into a DateTime object.

**Additional context**
N/A

**Comment by fzyzcjy** [comment]
Sounds like a great feature!

I have two ideas about implementation:

Idea 1: Mimic what is done to a `String` (a String is using a `Vec<u8>` under the hood), e.g. https://github.com/fzyzcjy/flutter_rust_bridge/blob/9ba325bc9cecb83bfa90c96d51875f1755ae10c9/frb_codegen/src/generator/rust/ty_delegate.rs#L13 . Then do the same for NaiveDateTime.

Idea 2: Add an interesting and may be widely used feature: Custom type converters.
For example, you may use the feature like:

```
// api.rs

frb_register_custom_converter!(MyNaiveDateTimeToDateTime)

struct MyStruct {
  my_field: NaiveDateTime, // will be converted by my_NaiveDateTime_to_DateTime
}

struct MyNaiveDateTimeToDateTime;
impl FrbConverter<NaiveDateTime, i64> for MyNaiveDateTimeToDateTime {
  fn convert(raw: NaiveDateTime) -> i64 {
    return raw.get_the_i64_value();
  }
}
```

Looking forward to your PR :)

**Comment by wentao** [comment]
Thank you for the reply. I'd love to implement this but unfortunately I'm still very new to rust and I don't think I'm capable of doing this. I was in the hope of someone could take a look at this and implement the feature request for the community.

**Comment by fzyzcjy** [comment]
@wentao Practice makes perfect :) You may try to make a PR later and I will review it
