### ISSUE TITLE
Multiple input files for a single output file.

### ISSUE THREAD

**Issue by FormidablePencil** [fzyzcjy/flutter_rust_bridge#495]
Could there be multiple input rust files to output to a single output so that modularity could be achieved for separation of concerns?

**Comment by fzyzcjy** [comment]
That would be quite useful, and looking forward to your PR! That should not be quite hard IMHO

A related discussion: https://github.com/fzyzcjy/flutter_rust_bridge/discussions/479 @sccheruku

**Comment by FormidablePencil** [comment]
Idk if generating a file is per input file is the most ideal. Aren't enums and structs of dependent functions generated in both output files where both files had functions dependent on them. It would duplicated the types and furthermore, each functions of the output file will be sensitive to only accept the structs and enums from the same file the function came from. Function dependency sensitivity will be a mess especially if two functions from two different files were needed to manipulate some data.

Here's my proposition. Create separate rust file for each separation of concern and merge then into one. 1 bundled input file and 1 output file at the end of the day.

**Comment by fzyzcjy** [comment]
Looking forward to your PR - I guess only need some minor modifications to existing code

**Comment by dbsxdbsx** [comment]
> Thanks for ccing. I took an early crack at trying to achieve separation of concerns.
> 
> The cli tool was already capable of generating separate dart file per each rust input file (we have to specify it in the arguments). However, one blocker was a function `free_WireSyncReturnStruct` being declared in each bridge_generated.rs file. Which was causing the build to fail. I added an option called `exclude_sync_execution_mode_utility` to prevent this file from being generated.
> 
> Rather than trying to generate one dart file from several rust files, I took the approach of creating a separate dart file per each rust input file. (which was straight-forward because it required preventing a duplicate function from being generated)
> 
> The PR and some instructions on how to use the command line arguments are here: [#479 (comment)](https://github.com/fzyzcjy/flutter_rust_bridge/discussions/479#discussioncomment-2906367) #481
> 
> I hope that adds some context.

Just one thing may be related,  after using `exclude_sync_execution_mode_utility` like this in `justfile`:
```
gen:
    # api for chess rule
    export REPO_DIR="$PWD"; cd /; flutter_rust_bridge_codegen {{llvm_path}} \
        --rust-input "$REPO_DIR/native/src/rule_api.rs" \
        --rust-output "$REPO_DIR/native/src/gened_rule_api.rs" \
        --dart-output "$REPO_DIR/lib/gened_rule_api.dart" \
        --class-name RuleApi
    # api for connecting ucci engine
    export REPO_DIR="$PWD"; cd /; flutter_rust_bridge_codegen {{llvm_path}} \
        --rust-input "$REPO_DIR/native/src/ucci_api.rs" \
        --rust-output "$REPO_DIR/native/src/gened_ucci_api.rs" \
        --dart-output "$REPO_DIR/lib/gened_ucci_api.dart" \
        --class-name UcciApi \
        --exclude-sync-execution-mode-utility true

    # Uncomment this line to invoke build_runner as well
    flutter pub run build_runner build --delete-conflicting-outputs
```
I succeeded in generating my two separated files and the whole app is compilable with `ffi.dart` like this:
```dart
// This file initializes the dynamic library and connects it with the stub
// generated by flutter_rust_bridge_codegen.

import 'dart:ffi';
import 'dart:io' as io;

import 'gened_rule_api.dart';
import 'gened_ucci_api.dart';
export 'gened_rule_api.dart';  // ok
// export 'gened_rule_api.dart';  // also ok

const _base = 'native';

// On MacOS, the dynamic library is not bundled with the binary,
// but rather directly **linked** against the binary.
final _dylib = io.Platform.isWindows ? '$_base.dll' : 'lib$_base.so';

// The late modifier delays initializing the value until it is actually needed,
// leaving precious little time for the program to quickly start up.
final RuleApi ruleApi = RuleApiImpl(io.Platform.isIOS || io.Platform.isMacOS
    ? DynamicLibrary.executable()
    : DynamicLibrary.open(_dylib));

final UcciApi ucciApi = UcciApiImpl(io.Platform.isIOS || io.Platform.isMacOS
    ? DynamicLibrary.executable()
    : DynamicLibrary.open(_dylib));
```
But how to change the export statement `export 'gened_rule_api.dart';` to a more meaningful file name, like `api.dart`?

**Comment by fzyzcjy** [comment]
> But how to change the export statement export 'gened_rule_api.dart'; to a more meaningful file name, like api.dart?

Not sure what is your question. You can just use `ruleApi` and `ucciApi` variables. And `export 'gened_ucci_api.dart'; export 'gened_rule_api.dart';` export both. Then users (i.e. yourself in other files) just `import ffi.dart` and completely no need to import gened_rule_apir or gened_ucci_api at all

**Comment by dbsxdbsx** [comment]
> > But how to change the export statement export 'gened_rule_api.dart'; to a more meaningful file name, like api.dart?
> 
> Not sure what is your question. You can just use `ruleApi` and `ucciApi` variables. And `export 'gened_ucci_api.dart'; export 'gened_rule_api.dart';` export both. Then users (i.e. yourself in other files) just `import ffi.dart` and completely no need to import gened_rule_apir or gened_ucci_api at all

If I export both, it throw error:`The name 'wire_uint_8_list' is defined in the libraries 'package:[appName]/gened_rule_api.dart' and 'package:[[appName]]/gened_ucci_api.dart'.
Try removing the export of one of the libraries, or explicitly hiding the name in one of the export directives.`

So, what I did now is just not exporting either of them in `ffi.dart`.

**Comment by fzyzcjy** [comment]
```
export 'gened_ucci_api.dart';
export 'gened_rule_api.dart' hide wire_uint_8_list;
```

Well, or maybe the implementation details like wire_sth should be private instead of public.

Or, use `--dart-decl-output` to make declaration and implementation separate, so you can only import declaration.

Feel free to PR!

**Comment by dbsxdbsx** [comment]
> ```
> export 'gened_ucci_api.dart';
> export 'gened_rule_api.dart' hide wire_uint_8_list;
> ```
> 
> Well, or maybe the implementation details like wire_sth should be private instead of public.
> 
> Or, use `--dart-decl-output` to make declaration and implementation separate, so you can only import declaration.
> 
> Feel free to PR!

Now I encounter a more severe issue, I  posted here:https://github.com/fzyzcjy/flutter_rust_bridge/issues/511.

**Comment by fzyzcjy** [comment]
http://cjycode.com/flutter_rust_bridge/article/generate_multiple_files.html
