### ISSUE TITLE
Question: Whether there is an enum instead of freeze

### ISSUE THREAD

**Issue by huang12zheng** [fzyzcjy/flutter_rust_bridge#505]
**Is your feature request related to a problem? Please describe.**
Nowadays, enum in dart 2.17 support construct function,
Is it possible to replace freeze with this

```enum
enum Vehicle {
// enum Vehicle implements Comparable<Vehicle> {
  car(tires: 4, passengers: 5, carbonPerKilometer: 400),
  bus(tires: 6, carbonPerKilometer: 800),
  bicycle(tires: 2, passengers: 1, carbonPerKilometer: 0);

  const Vehicle({
    this.tires,
    this.passengers,
    this.carbonPerKilometer,
  });

  final int? tires;
  final int? passengers;
  final int? carbonPerKilometer;

  // int get carbonFootprint => (carbonPerKilometer / passengers).round();

  // @override
  // int compareTo(Vehicle other) => carbonFootprint - other.carbonFootprint;
}
```
[dart enum sample](https://dart.dev/samples#enums)

* **As you can see, vehicle. bus has only two parameters**

**Describe the solution you'd like**
```dart
enum Vehicle { car, bus, bicycle }

typedef F = Vehicle Function(int, int, int);
Vehicle _carFn(int a, int b, int c) => Vehicle.car;

enum VehicleX {
  car(carFn: _carFn);

  const VehicleX({
    this.carFn,
  });

  final F? carFn;

}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by huang12zheng** [comment]
enum in rust look like nest class
enum in dart is just enum.

**Comment by fzyzcjy** [comment]
> enum in rust look like nest class
enum in dart is just enum.

Yes, kind of like that. Enums in dart is not that expressive... So I guess it is not possible.
