### ISSUE TITLE
`StreamSink` registered too late in test

### ISSUE THREAD

**Issue by w-ensink** [fzyzcjy/flutter_rust_bridge#517]
When I write code like the following:

```rust
lazy_static! {
    static ref LISTENER: Arc<Mutex<Option<StreamSink<i64>>>> = Default::default();
}

pub fn register_listener(listener: StreamSink<i64>) -> Result<()> {
    (*LISTENER.lock().unwrap()) = Some(listener);
}

pub fn create_event() {
    if let Some(ref listener) = *LISTENER.lock().unwrap() {
        listener.add(42);
    } else {
        println!("no listener!");
    }
}
```

and then call it in my Dart code:

```dart
test('event passed to listener', () async {
  var called = false

  registerListener().listen((e) {
    called = true;
    print('event: $e');
  });

  await createEvent();

  expect(called, equals(true));
});
```

What gets printed from Rust is: `"no listener!"`.

Dart doesn’t produce anything and the test fails…

Is this expected behavior?

**Comment by fzyzcjy** [comment]
IMHO `registerListener()` is an async function and it takes time for it to run. But you are doing `registerListener(); await createEvent();` which does not give it any time to register.

**Comment by w-ensink** [comment]
That’s what I thought too, but when I change it to this:

```rust
lazy_static! {
    static ref LISTENER: Arc<Mutex<Option<StreamSink<i64>>>> = Default::default();
}

pub fn register_listener(listener: StreamSink<i64>) -> Result<()> {
    println!("listener registered");
    (*LISTENER.lock().unwrap()) = Some(listener);
}

pub fn create_event() {
    if let Some(ref listener) = *LISTENER.lock().unwrap() {
        listener.add(42);
    } else {
        println!("no listener!");
    }
}

```

```dart
test('event passed to listener', () async {
  var called = false

  registerListener().listen((e) {
    called = true;
    print('event: $e');
  });

  await Future.delayed(Duration(seconds: 1));
  await createEvent();

  expect(called, equals(true));
});
```

Rust prints:
`"no listener!"`
`"listener registered"`

Changing `await Future.delayed(Duration(seconds: 1));` to `sleep(Duration(seconds: 1));` doesn’t solve it either.

What other ways are there to wait for it to finish registering?

**Comment by w-ensink** [comment]
Okay, I'm left entirely confused now... Yesterday I had this error, even with the `await Future.delayed(Duration(seconds: 1));` (I can see it in my git history). Now when I run it again it doesn't fail, even with as low as 1 millisecond of delay... When I remove the delay completely it still does fail, like expected as you said.

I don't know why it didn't work yesterday, but it's nice that it works now (though it does make me slightly scared).
Thanks anyway!

**Comment by w-ensink** [comment]
I might create a PR later today, adding a similar test to CI for this project if that's ok with you

**Comment by fzyzcjy** [comment]
You are welcome!

Sure, looking forward to your PR!
