### ISSUE TITLE
[Bug] `wire_<struct>` should `#[derive(Default)]` for nested structs without a `Box`

### ISSUE THREAD

**Issue by w-ensink** [fzyzcjy/flutter_rust_bridge#525]
### Describe the bug

`wire_<struct>` should `#[derive(Default)]`, because I'm getting errors after `bridge_generated.rs` is generated. These errors are from structs that use other structs that get passed as an argument to an api function.

These errors get solved when I `#[derive(Debug)]` for these types as the compiler suggests.

I reproduced it on this [branche](https://github.com/w-ensink/flutter_rust_bridge/tree/derive-default-bug).
Just run `just test-pure` and you'll get a rust compiler error.

```
error[E0277]: the trait bound `wire_Part: Default` is not satisfied
    --> src/bridge_generated.rs:1932:21
     |
1932 |             part_0: Default::default(),
     |                     ^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `wire_Part`
     |
help: consider annotating `wire_Part` with `#[derive(Default)]`
     |
801  | #[derive(Default)]
     |
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Was too long to post
```

### To Reproduce

Clone my repo and check out the `derive-default-bug` branch.

### Expected behavior

Should compile just fine (I think?)

### Generated binding code

```shell
Can see for yourself on branch provided
```

### OS

macOS

### Version of `flutter_rust_bridge_codegen`

1.34.2

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-arm, locale nl-NL)
    • Flutter version 3.0.2 at /Users/wouter/Dev/Flutter/flutter_tools
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (12 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5787.37

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
```

### Version of `clang++`

Apple clang version 13.1.6 (clang-1316.0.21.2)

### Version of `ffigen`

5.0.1

**Comment by w-ensink** [comment]
Correction: when I derive Default it says some api2wire functions related to the nested struct are found in Dart. 
When I change the generator to always add `#[derive(Default)]` it results in problems with `*mut T` pointers that don't have a default. 
Any thoughts on this?

**Comment by fzyzcjy** [comment]
The error code

```
// Bug while generating bridge code for this:
pub struct Part {
    value_0: u64,
    value_1: u64,
}

pub struct Whole {
    part_0: Part,
    part_1: Part,
}

pub fn use_whole(whole: Whole) {}
```

maybe because we do not support having a field of struct without box. In other words:

```
struct A {b: B}
```

is not supported.

You should use 

```
struct A {b: Box<B>}
```

**Comment by fzyzcjy** [comment]
Feel free to make a PR! I guess there are two workarounds/solutions:

a. Output some errors when the frb codegen faces such conditions, instead of blindly generate it and let the user be confused

b. Enhance the codegen, such that it really allows such non-boxed struct fields.

**Comment by w-ensink** [comment]
> maybe because we do not support having a field of struct without box.
Ah that makes sense...

I'll see what I can do, but this probably going to take a little longer, since i'll need to understand more of the code now.

**Comment by fzyzcjy** [comment]
Take your time :) Feel free to ask questions

**Comment by Roms1383** [comment]
:+1: same here I always forget to `Box` my nested struct and face this issue very often lol

**Comment by fzyzcjy** [comment]
Yes I do see a lot of issues raised in this repo b/c this. So at least a PR generating a hard error (panic) about this would be quite helpful
