### ISSUE TITLE
Support for opaque boxed types

### ISSUE THREAD

**Issue by lattice0** [fzyzcjy/flutter_rust_bridge#534]
I have a pretty complex type that does not translate (and I don't want to) to flutter. Normally if I didn't have this amazing lib I'd keep a pointer on the Flutter side (as an integer) and call Rust methods passing the pointer and the args. I could not see anything on the docs about the opaque type technique I did before on Flutter. I came up with this idea which is a bit ugly but should work:

```rust
// Do not use this on Flutter side
struct ComplexType {
    complex_type_1: ...,
    complex_type_2: ...
    //...
}

// Use this on the dart side
pub struct ComplexTypeOpaque {
    inner: Box<dyn Any>
}

impl ComplexTypeOpaque {
    fn do_something(&self, simple_supported_type_1: SimpleSupportedType1) {
         //downcast inner into ComplexType, call stuff 
    }
}
```

Is there a better way currently?

**Comment by lattice0** [comment]
Well, `Box<dyn Any>` won't work also

**Comment by fzyzcjy** [comment]
Personally I use object pools: https://github.com/fzyzcjy/flutter_rust_bridge/pull/333

P.S. #333 is already used in production in my app. It is WIP *only* because the users have to copy-and-paste those code into their own codebase currently - which is not that elegant so I do not merge PR

**Comment by lattice0** [comment]
@fzyzcjy the opaque idea is very nice, would be nice to get it merged. I just tested. PS: didn't you get https://github.com/fzyzcjy/flutter_rust_bridge/pull/293#issuecomment-1169366921?

Cancelable tasks look great also, gonna take a try.

PS: which copy-paste code? The trait implementation?

**Comment by lattice0** [comment]
Ok, just understood. Personally I prefer opaque types as there's no handle search every time a function call is made. I don't know how this Opaque is implemented but I think it should be faster (even though it doesn't matter for most projects). I used to use handles before when I used my own handwritten implementations but started using opaque types after. 

It would be nice to have both of them merged. I wish I could do it but I'm still learning how this lib works. Maybe in the future, but currently I'm gonna be stuck with the Opaque PR old version.

I also don't understand why `cancel_token.rs` cannot be in the dependency that is already included in the project, as well as the dart version.

Also, what are the safety concerns with opaque?

**Comment by fzyzcjy** [comment]
> I wish I could do it but I'm still learning how this lib works. Maybe in the future

Take your time and looking forward to PR :)

> I also don't understand why cancel_token.rs cannot be in the dependency that is already included in the project, as well as the dart version.

https://github.com/fzyzcjy/flutter_rust_bridge/pull/333#issuecomment-1037079219

> Also, what are the safety concerns with opaque?

See my discussions at that PR

**Comment by lattice0** [comment]
I tried to merge the new stuff into https://github.com/fzyzcjy/flutter_rust_bridge/pull/293 but couldn't make it work. I've ran into https://github.com/fzyzcjy/flutter_rust_bridge/issues/344 because my branch is old, but running:

`flutter pub run build_runner build --delete-conflicting-outputs`

gives

`[INFO] Succeeded after 85ms with 0 outputs (0 actions)`

so it does not change anything. 

I'm learning how `syn` works and maybe I can help more, but currently I was unable to merge (wouldn't compile after carefully merging some conflicts in how I though it should work)

**Comment by fzyzcjy** [comment]
#293 is still not mature, and I am worried even if you can use it you will sometimes encounter very weird and hard-to-debug bugs because it is not safe yet.

If you are willing to contribute and finish that PR, feel free to discuss with @Desdaemon who made that great PR

**Comment by lattice0** [comment]
Ok I was able to merge at least: https://github.com/lattice0/flutter_rust_bridge/tree/opaque-redux-merge

now gonna understand more of the lib and also which unsafety problems we have with this approach. Thank you all!

**Comment by fzyzcjy** [comment]
@lattice0 You are welcome and looking forward to your progress!
