### ISSUE TITLE
Supporting methods

### ISSUE THREAD

**Issue by lattice0** [fzyzcjy/flutter_rust_bridge#539]
Just to know, isn't there support for methods?

```
pub struct MyStruct{
    something: String
}

impl MyStruct{
    fn do_something() {
        todo!()
    }
}

pub fn return_my_struct() -> MyStruct {
    todo!()
}
```

does not translate any methods.

Should I create my own pseudomethods by doing

```
pub fn my_struct_do_something(my_struct: &MyStruct) {
    //...
}
```

?

Also, I have to do

```
pub fn return_my_struct() -> MyStruct {
    todo!()
}
```

otherwise it won't create MyStruct on dart side. Is it supposed to be like this?

**Comment by fzyzcjy** [comment]
Duplicate of #67
