### ISSUE TITLE
[Bug] `fn(a: u32, s: StreamSink<i32>)` generates wiring function with wrong order, i.e. `stream_sink` is always the first parameter

### ISSUE THREAD

**Issue by lattice0** [fzyzcjy/flutter_rust_bridge#541]
### Describe the bug

At https://github.com/fzyzcjy/flutter_rust_bridge/blob/fa7685afbe5971e347d688cdac85f6b3f534dafb/frb_codegen/src/generator/rust/mod.rs#L246

it does first the stream_sink parameter, then the function parameters.

So, for a function:

```rust
pub fn tick(a: u32, sink: StreamSink<i32>) -> Result<(), anyhow::Error> {
    todo!()
}
```

it generates

```rust

#[no_mangle]
pub extern "C" fn wire_tick(port_: i64, a: u32) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "tick",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            let api_a = a.wire2api();
            move |task_callback| tick(task_callback.stream_sink(),api_a)
        },
    )
}
```
which does not compile. It should be

```rust

#[no_mangle]
pub extern "C" fn wire_tick(port_: i64, a: u32) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "tick",
            port: Some(port_),
            mode: FfiCallMode::Stream,
        },
        move || {
            let api_a = a.wire2api();
            move |task_callback| tick(api_a, task_callback.stream_sink())
        },
    )
}
```

I changed to

```rust
let inner_func_params = [
            func.inputs
                .iter()
                .map(|field| format!("api_{}", field.name.rust_style()))
                .collect::<Vec<_>>(),
            match func.mode {
                IrFuncMode::Normal | IrFuncMode::Sync => vec![],
                IrFuncMode::Stream => vec!["task_callback.stream_sink()".to_string()],
            },
        ]
        .concat();
```

and it works but obviously it generates errors if 

```rust
pub fn tick(sink: StreamSink<i32>, a: u32) -> Result<(), anyhow::Error> {
    todo!()
}
```

but I think it's better for `sink` to be the last argument because then I can do things like

```rust
fn my_object_set_stream_sink(my_object_opaque: MyObjectOpaque, sink: StreamSink<i32>)
```

it makes sense for the sink to be last, because the object (which is the "self"), should be the first.

Does it make sense?

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
_
```

**Comment by fzyzcjy** [comment]
> it makes sense for the sink to be last, because the object (which is the "self"), should be the first.

Hmm that sounds reasonable.

But on the other hand, I am thinking sink as a special argument so it is placed always at the first place (a bit like "self" being first).

So, what about modifying the code such that it allows sink to be *anywhere*

Feel free to PR!

**Comment by lattice0** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/pull/542
