### ISSUE TITLE
why does the frb require the "Default" trait bound?

### ISSUE THREAD

**Issue by TENX-S** [fzyzcjy/flutter_rust_bridge#548]
<img width="951" alt="Screen Shot 2022-07-02 at 20 59 04" src="https://user-images.githubusercontent.com/40336192/177001787-05d4eb1b-9d2c-413c-9007-ef7527047b65.png">
<img width="951" alt="Screen Shot 2022-07-02 at 20 59 40" src="https://user-images.githubusercontent.com/40336192/177001814-98af6969-7243-4945-ac1d-5a504c965f1c.png">

**Comment by fzyzcjy** [comment]
That is `wire_LinkType` not `LinkType`. In other words, the `Default` trait bound should be auto-generated on `wire_LinkType`. Indeed you should do nothing about it.

Have you run codegen?

And, please add `Box`. `kind: Box<LinkType>`

**Comment by TENX-S** [comment]
I had to run codegen twice to succeed. emm... is that normal?

**Comment by TENX-S** [comment]
<img width="1001" alt="Screen Shot 2022-07-02 at 21 37 47" src="https://user-images.githubusercontent.com/40336192/177003258-ce1c9bed-a1d3-4e82-b048-356caf9df018.png">
<img width="1001" alt="Screen Shot 2022-07-02 at 21 39 28" src="https://user-images.githubusercontent.com/40336192/177003311-782638d0-a14a-4444-bfa5-f9c3a2055b6d.png">

**Comment by TENX-S** [comment]
Problem solved. I just need `Box` `Link` somewhere again 🤣. Is this "Box a enum" in the [doc](http://cjycode.com/flutter_rust_bridge/feature/lang_enum.html)? Or I missed it somewhere..

**Comment by fzyzcjy** [comment]
Feel free to PR and add some compile time errors to such cases! AFAIK, the following are not supported (yet): (1) field of an enum without box (2) field of a struct without box.

**Comment by TENX-S** [comment]
Doesn't mean to bother you, but I got this odd error:
![Screen Shot 2022-07-04 at 13 25 26](https://user-images.githubusercontent.com/40336192/177086986-9882fce9-0829-4c63-a8ba-f1f75b7d3ee1.png)

**Comment by fzyzcjy** [comment]
Try using ffigen 5.x instead of 6.x, with flutter_rust_bridge 1.34.2

**Comment by fzyzcjy** [comment]
If that works, then it is the 1.35.0 fix https://github.com/fzyzcjy/flutter_rust_bridge/pull/536 by @SecondFlight misses this edge case.

**Comment by fzyzcjy** [comment]
Btw please file a separate issue since this seems not to be "require Default trait"

**Comment by TENX-S** [comment]
I got this error again :(
frb: 1.38.0
<img width="1031" alt="Screen Shot 2022-07-17 at 14 29 59" src="https://user-images.githubusercontent.com/40336192/179386916-023b1f34-3d0b-4021-afe2-e4ceafaf20ee.png">
<img width="1031" alt="Screen Shot 2022-07-17 at 14 30 29" src="https://user-images.githubusercontent.com/40336192/179386917-299bfb9b-d325-48fe-88bf-b161f64d1261.png">

**Comment by fzyzcjy** [comment]
Oops could you please try which exact version bump causes this?

**Comment by TENX-S** [comment]
I have tried 1.37.2, no lucky.

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/CHANGELOG.md

Maybe bisect to see where it regresses

**Comment by fzyzcjy** [comment]
And check the generated source code - which new version of frb generates the wrong code, and where is the code wrong? (May just diff the good and code)

**Comment by TENX-S** [comment]
I'm not sure. It seems like 1.35.0 introduce more bugs...
I can only use version >= 1.37.2 because of this bug #560

**Comment by fzyzcjy** [comment]
Well maybe file a reproducible sample (probably a PR)... So why did you close the issue - does some version solve it?

**Comment by TENX-S** [comment]
I'll try to make a PR in the next week. Last time I solved it by box that enum, but this time it's a struct...

**Comment by fzyzcjy** [comment]
Oh wait, you are having a struct without a box? Add a box to it and it will be solved

**Comment by TENX-S** [comment]
Yeah, `Box` solves this problem. I will look for a time to make a PR.
