### ISSUE TITLE
Type not match in generated code

### ISSUE THREAD

**Issue by TENX-S** [fzyzcjy/flutter_rust_bridge#549]
rust 1.62.0
flutter 3.0.2
ffigen 5.0.1

![Screen Shot 2022-07-04 at 13 25 26](https://user-images.githubusercontent.com/40336192/177089031-3f19774a-c3a0-448d-92cb-412bdae52f40.png)

**Comment by fzyzcjy** [comment]
What is that "Dir"? please share the code.

In addition, it would be great to add a reproducible test case at https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/src/api.rs and https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/dart/lib/main.dart. In other words, add a few lines there, and make a PR, and the PR's CI should fail and show those errors.

**Comment by TENX-S** [comment]
I'm trying to make reproducible test case, but the codegen doesn't generate the `*.freezed.dart` file.

**Comment by TENX-S** [comment]
FYI
`flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output ./dart/bridge.dart`

**Comment by TENX-S** [comment]
api.rs
```rust
#[derive(Debug)]
pub enum LinkType {
    File,
    Dir { include_all: bool },
    Http,
    Git,
}

#[derive(Debug)]
pub struct Link {
    pub inner: String,
    pub kind: Box<LinkType>,
}

pub fn print_link(link: Link) -> anyhow::Result<()> {
    println!("{:#?}", link);
    Ok(())
}
```

**Comment by fzyzcjy** [comment]
> but the codegen doesn't generate the *.freezed.dart file.

Have you add dependency in yaml

**Comment by fzyzcjy** [comment]
You forgot dev_dependencies

**Comment by fzyzcjy** [comment]
Hmm please show full code, probably just fork this repo, add code in api.rs and .dart, and make a PR. Then we can discuss in the PR and look at CI etc.

No worries to PR before fully implemented a feature - just mark PR as draft

**Comment by TENX-S** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/pull/550
