### ISSUE TITLE
Support method Fn()

### ISSUE THREAD

**Issue by Zaitam** [fzyzcjy/flutter_rust_bridge#566]
Is there anyway of sharing a void as a return type of rust function?

```
fn example() -> Fn(/*Maybe a String*/) {
   //Do something
}
```

I have tried the void type `()` explained in the [Book](https://cjycode.com/flutter_rust_bridge/feature/lang.html), however I couldn't get anything done.

This is all due to an array containing voids, which I need to select one to run. My current workaround contains and an array and a straight method which is called as `api.run_func(id)` and gets the void from a rust array.

**Comment by fzyzcjy** [comment]
Callables/callbacks are not supported yet. But feel free to PR!
