### ISSUE TITLE
More on precompiled binaries

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#567]
try to make it monorepo:

- [ ] scoop
- [ ] brew
- [ ] doc
- [x] credits

Related: https://github.com/fzyzcjy/flutter_rust_bridge/pull/565#issuecomment-1179816346

**Comment by Desdaemon** [comment]
I'm thinking of gathering all the distribution-specific files in a `contrib` folder, so it might look like this:
```
- contrib/
  - scoop_frb/
    - flutter_rust_bridge_codegen.json
  - homebrew_frb/
    - flutter_rust_bridge_codegen.rb
- frb_codegen
- ..
```

It makes better sense with regards to the individual bundling systems as well, so I prefer this approach.

**Comment by fzyzcjy** [comment]
Totally agree! Since the scoop/brew is like a repository which can hold multiple packages.

**Comment by fzyzcjy** [comment]
I have just released 1.38.0. Let's see whether the CI works :)

**Comment by Desdaemon** [comment]
Nice, it's a good opportunity to refine the install scripts as well.

**Comment by fzyzcjy** [comment]
bump

**Comment by fzyzcjy** [comment]
oh this seems to be solved already?
