### ISSUE TITLE
error in documentation code compiling android target on Windows

### ISSUE THREAD

**Issue by juzi5201314** [fzyzcjy/flutter_rust_bridge#579]
**Is your feature request related to a problem? Please describe.**
In this paragraph [https://github.com/Desdaemon/flutter_rust_bridge_template/blob/main/android/app/build.gradle#L86](https://github.com/Desdaemon/flutter_rust_bridge_template/blob/main/android/app/build.gradle#L86) (also in [docs](http://cjycode.com/flutter_rust_bridge/integrate/android_tasks.html)), uses `'sh', '-c'..` and `ANDROID_NDK_HOME =.. ..`, but when I build on Windows (android studio), the problem obviously occurs.

**Describe the solution you'd like**
Maybe here should differentiate Windows and use `cmd` instead of `sh`

**Describe alternatives you've considered**
I modified it a bit. This code works fine on my computer:
```
workingDir "../../$crate"
environment "ANDROID_NDK_HOME", "$ANDROID_NDK"
if (org.gradle.nativeplatform.platform.internal.DefaultNativePlatform.currentOperatingSystem.isWindows()) {
    commandLine 'cmd', '/C', """cargo ndk \
            -t armeabi-v7a -t arm64-v8a -t x86_64 -t x86 \
            -o ../android/app/src/main/jniLibs build $profileMode"""
} else {
    commandLine 'sh', '-c', """cargo ndk \
            -t armeabi-v7a -t arm64-v8a -t x86_64 -t x86 \
            -o ../android/app/src/main/jniLibs build $profileMode"""
}
```

**Additional context**

**Comment by fzyzcjy** [comment]
Sounds pretty reasonable. Looking forward to your PR!
