### ISSUE TITLE
Support for exposing `SendPort` like `StreamSink`?

### ISSUE THREAD

**Issue by LLouice** [fzyzcjy/flutter_rust_bridge#586]
**Is your feature request related to a problem? Please describe.**

Currently,we need wrap async function in a sync function,and generally the async task run in a seperate async runtime(or block on current thread), if the async task has return value, it will block the thread(one thread of thread pool) to wait the result.

If we have many long running tasks, it'll run out of all threads of the thread pool.

How about cancel this waiting, just let task itself return it's result in async runtime.

**Describe the solution you'd like**

I found a [article: Dart and Rust: the async story](https://dev.to/sunshine-chain/rust-and-dart-the-async-story-3adk) of shekohex, he shows a solution: async runtime captures the Isolate and when task is Ready, post the result through isolate handle directly.

The relevant code is as follows:
- Rust part code snippet

https://github.com/shekohex/flutterust/blob/9ab881627a42294114e54e039dc293df14df4e7e/native/scrap-ffi/src/lib.rs#L71
```rust
#[no_mangle]
pub extern "C" fn load_page(port: i64, url: *const raw::c_char) -> i32 {
    let rt = runtime!();
    let url = cstr!(url);
    rt.spawn(async move {
        let result = scrap::load_page(url).await;
        let isolate = Isolate::new(port);
        isolate.post(result); // <---
    });
    1
}
```

- Dart part code snippet
https://github.com/shekohex/flutterust/blob/9ab881627a42294114e54e039dc293df14df4e7e/packages/scrap_ffi/lib/scrap.dart#L19
```dart
Future<String> loadPage(String url) {
    var urlPointer = Utf8.toUtf8(url);
    final completer = Completer<String>();
    final sendPort = singleCompletePort(completer);
    final res = native.load_page(
      sendPort.nativePort, // <---
      urlPointer,
    );
    if (res != 1) {
      _throwError();
    }
    return completer.future;
  }
```

**Comment by fzyzcjy** [comment]
Btw about async in Rust, here are some previous doc: http://cjycode.com/flutter_rust_bridge/feature/async_rust.html, http://cjycode.com/flutter_rust_bridge/article/async_in_rust.html, by @AlienKevin

**Comment by fzyzcjy** [comment]
This lib is trying to provide safe and automatic wrappers. Therefore, it may be a bit too low-level if we directly expose SendPort.

However, there seems to be a solution: What about improving the code generator, such that it automatically generate code similar to what you have mentioned.

Feel free to PR and I am looking forward to review it :)

/cc @Desdaemon btw what do you think?

**Comment by Desdaemon** [comment]
This is related to the ongoing work for web support, but SendPort is only an implementation detail! (MessagePort replaces it on the web.) Regardless, their API is roughly similar so we can try to abstract over their differences, but I'll have to work more on the web support to have a definite answer.
