### ISSUE TITLE
Code cleanup: dart/ty.rs is accidentically modified

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#590]
See https://github.com/fzyzcjy/flutter_rust_bridge/pull/543#discussion_r928319745 for details

/cc @lattice0 Maybe we can simply PR and revert this?

/cc @Desdaemon I also find this snippet in #589...

**Comment by lattice0** [comment]
I'll take a better look on this once I finish the exceptions PR, cause I'm really bad at multitasking. Is it ok?

**Comment by fzyzcjy** [comment]
Sure, take your time!

**Comment by Roms1383** [comment]
I can come up with a PR if you want guys.
The only point of friction when applying the change is that in `fn structs(&self) -> String` current state, `dart_api_class_name` is explicitly set to `None`.
<details><summary>should None be preserved ?</summary>

either:

```rust
fn structs(&self) -> String {
    if let IrTypeDelegate::PrimitiveEnum { ir, .. } = &self.ir {
        super::TypeEnumRefGenerator {
            ir: ir.clone(),
            context: self.context.clone(),
        }
        .structs()
    } else {
        "".into()
    }
}
```

or:

```rust
fn structs(&self) -> String {
    if let IrTypeDelegate::PrimitiveEnum { ir, .. } = &self.ir {
        let mut context = self.context.clone();
        context.dart_api_class_name = None;
        super::TypeEnumRefGenerator {
            ir: ir.clone(),
            context,
        }
        .structs()
    } else {
        "".into()
    }
}
```
</details>

**Comment by fzyzcjy** [comment]
@Roms1383 That would be great :)

The immutable approach looks better IMHO
