### ISSUE TITLE
Add brief documentation about implementations for new contributors

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#593]
Currently, we already have a lot of features and documentations, but still lack doc which introduces the internals. In other words, when someone wants to contribute to the codebase, he/she has to dig into the source code to understand what is happening. Thus maybe we can add some brief doc about implementations (e.g. what is the overall design etc).

Example: https://github.com/fzyzcjy/flutter_rust_bridge/issues/585

**Comment by Roms1383** [comment]
This is a great idea to ease contributions process IMHO. 
I'd personally like a section explaining how flutter_rust_bridge is designed to extend Rust ownership and borrowing rule across FFI boundaries, if that makes sense.

**Comment by fzyzcjy** [comment]
http://cjycode.com/flutter_rust_bridge/contributing/design.html

finished parts:

* folder structure
* Code-generator structure (wait for a few minutes for that website to refresh to see this section)

**Comment by fzyzcjy** [comment]
Done!
