### ISSUE TITLE
[Bug] Network request over HTTPS

### ISSUE THREAD

**Issue by Roms1383** [fzyzcjy/flutter_rust_bridge#598]
### Describe the bug

Hi, I was [following the book and using reqwest blocking](http://cjycode.com/flutter_rust_bridge/article/async_in_rust.html#avoid-async) to request a url over HTTPS.
The app launches and crashes instantly with this error :
```sh
Invalid argument(s): Failed to load dynamic library 'libnative.so': dlopen failed: cannot locate
symbol "SSL_do_handshake" referenced by
"/data/app/fr.cerclo.Cerclo-FpPF8zqv3_KY6JL-J0lH3w==/lib/arm64/libnative.so"...
```
I've already tried to add `native-tls` or `rustls` feature to `reqwest`, to no avail.

How do you usually fix this ?
Thanks :pray:

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
-
```

### To Reproduce

Just follow the [avoid async section inside Async in Rust chapter](http://cjycode.com/flutter_rust_bridge/article/async_in_rust.html#avoid-async), and call any url over `https://`

### OS

MacOS M1

### Version of `flutter_rust_bridge_codegen`

1.38.1

### Flutter info

```shell
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-TH)
    • Flutter version 3.0.5 at /Users/romain/Development/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/romain/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM G955F (mobile) • ce061716aaf37cd40d • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos              • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### Version of `clang++`

13.1.6 (clang-1316.0.21.2.5)

### Version of `ffigen`

6.0.1

**Comment by fzyzcjy** [comment]
I guess it wants to use that function in system? That does not sound like a problem with frb itself, but rather a general question with Rust: How to run https calls on Android/iOS with Rust? Maybe ask that in Rust/Android/iOS/reqwest community

**Comment by Roms1383** [comment]
Yes you're correct.
By the way I got it fixed by using `native-tls-vendored` feature from `reqwest`.
I guess it's either this or setting the certificate / security context on the client (but not sure where to grab it in the context of Flutter).

**Comment by Roms1383** [comment]
Feel free to close it 👌
