### ISSUE TITLE
Investigate usage of new cargo-ndk release

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#609]
bbqsrc/cargo-ndk#22 was closed a week ago, it might be worth checking if the issue has been fixed for our use-cases and update the template+documentation accordingly.

**Comment by fzyzcjy** [comment]
Just add my two cents: Old ndk (e.g. ndk 21) should still be supported since it is widely used and people may be using other tools that dep on it
