### ISSUE TITLE
Bidirectional streaming between rust and flutter.

### ISSUE THREAD

**Issue by iamguid** [fzyzcjy/flutter_rust_bridge#632]
Now flutter_rust_bridge provides the ability to return a stream from a called function, this is implemented using the StreamSink primitive, but what if you need to pass a stream as an argument? I mean to do it like it is implemented in WebSocket, GRPCWeb, etc. Of course, to organize a bidirectional stream, you can call a function with the necessary arguments and return a stream, but it seems to me that it would be more useful to be able to both transfer a stream and return a stream.

I suggest to make 2 primitives
1) rust -> dart streaming
2) dart -> rust steaming

What do you think ?

**Comment by fzyzcjy** [comment]
* rust->dart stream: already exists
* dart->rust stream: for each stream.add we can simply call a rust function, this can also be easily wrapped

Anyway feel free to PR for the feature you like!
