### ISSUE TITLE
Calling external libraries from native code with FFI

### ISSUE THREAD

**Issue by alerdenisov** [fzyzcjy/flutter_rust_bridge#638]
I'm building native module which depends on `gmp`, but it failed on load library because cannot resolve symbol (in my case it is `__gmpz_add_ui`).

I have required `libgmp.so` inside my jniLib folder and successfully load and call it from flutter: 

```
typedef __gmpz_add_ui = Pointer<NativeType> Function(Pointer<NativeType> a, Pointer<NativeType> b);
typedef GMPZAddUI = Pointer<NativeType> Function(Pointer<NativeType> a, Pointer<NativeType> b);

final DynamicLibrary gmp = loadLibrary("gmp");
final GMPZAddUI gmpzAddUi = gmp.lookup<NativeFunction<__gmpz_add_ui>>("__gmpz_add_ui").asFunction();
```

But it doesn't work for my rust library. Do you have any example or open-source projects which use external native libraries from rust code?

**Comment by fzyzcjy** [comment]
That sounds like a problem with Flutter/Rust instead of this bridge. 

> Do you have any example or open-source projects which use external native libraries from rust code?

My own app uses, but is not open source... Maybe google it?
