### ISSUE TITLE
Allow `SyncReturn<impl IntoDart>` as return type

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#639]
**Is your feature request related to a problem? Please describe.**
In anticipation of web support and the inability of Safari to spawn subworkers, we should allow synchronous execution of functions that need to manually spawn threads (think rayon's `.par_iter`).

**Describe the solution you'd like**
Refactor `execute_sync` to work with any types that implement `IntoDart` instead of just `SyncReturn<Vec<u8>>`.

**Describe alternatives you've considered**
None yet.

**Additional context**
None.

**Comment by fzyzcjy** [comment]
That would be quite helpful, because for very small functions, users may not want to pay the extra overhead of async (though small)

**Comment by Desdaemon** [comment]
Partially addressed by #663.

**Comment by fzyzcjy** [comment]
You are right, I forget to close this issue :)
