### ISSUE TITLE
[Question] How do we work with mutable structs?

### ISSUE THREAD

**Issue by TheLumbee** [fzyzcjy/flutter_rust_bridge#653]
My initial thought was to use static methods and pass the class from dart then modify and return the struct. Is that the best approach? I've been looking through the examples but I didn't see any that modified structs.

Also, would that approach cause some memory issues? I'd imagine Dart disposes of the memory from the previous object when it is assigned the new object.

**Comment by fzyzcjy** [comment]
Currently no mutability is supported, because *copy* has to happen given Dart's native API.

But if you find out a better approach, feel free to discuss!

**Comment by TheLumbee** [comment]
That makes sense. I didn't know that about Dart's API. Thank you
