### ISSUE TITLE
[Feature Request] Desktop support?

### ISSUE THREAD

**Issue by TENX-S** [fzyzcjy/flutter_rust_bridge#66]
It's very inspiring to have such a library for those who like both flutter and rust, but it would be better if it can also support the desktop. Any plans on that ?

**Comment by yoroshikun** [comment]
I just tested the example with windows and it crashes with 
```dart
late final dylib =
    Platform.isAndroid ? DynamicLibrary.open('libflutter_rust_bridge_example.so') : DynamicLibrary.process();
// DynamicLibrary.process is not available on this platform
```

Would this be a simple fix? (I have not looked into it just ran the simple example), and as expected dart:ffi does not work for web target at all XD wonder if there is room for a wasm implementation of this bridge 🤔

**Comment by fzyzcjy** [comment]
No, that flutter app is not tested on desktop. I mean, following Flutter's official tutorials, to create a simplest Flutter app that runs on Desktop and talks to Rust via ffi - that simplest app should *not* use this package (yet).

**Comment by fzyzcjy** [comment]
I did a bit of research. Seems that Flutter desktop has the ffi functionality, [such as this windows (complex) example](https://timsneath.medium.com/windows-fun-with-dart-ffi-687c4619e78d). So this lib should work well as long as you set up the Flutter desktop app's ffi functionality successfully.

I may modify my `with_flutter` example supporting that later. Feel free to make a PR if you want!

**Comment by fzyzcjy** [comment]
Sure. I may add that later.
