### ISSUE TITLE
Unreleased Dart Web test is flaky, probably because puppeteer timeouts when downloading Chromium

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#680]
https://github.com/fzyzcjy/flutter_rust_bridge/runs/8222107994?check_suite_focus=true#step:9:164

We should at least ensure CI is passing before we publish the new version.

/cc @Desdaemon 

@Desdaemon Btw, maybe we should print out some log to ease debugging - currently seems no log after `🦀 Server listening on http://localhost:8080 🎯`

p.s. I triggerred a rerun https://github.com/fzyzcjy/flutter_rust_bridge/actions/runs/3005531372

**Comment by Desdaemon** [comment]
The CI usually times out if the internet connection is unstable while `puppeteer` downloads a local copy of Chromium. Should we trigger a rerun just in case?

**Comment by fzyzcjy** [comment]
> while puppeteer downloads a local copy of Chromium.

Weird... Why downloading chromium in *github actions machine* will timeout?

> Should we trigger a rerun just in case?

IIRC the with_flutter integration tests already have retry mechanism, e.g. https://github.com/fzyzcjy/flutter_rust_bridge/blob/7df2ecb6ccd46fd3ae383d32fe5e27fdb40a5bd5/.github/workflows/ci.yaml#L214-L237 Maybe we can mimic it.


Anyway since it is only a timeout it is not blocking our releasing progress.

**Comment by fzyzcjy** [comment]
Btw, it is possible we print out more logs? For example, is there a debug flag that can be enabled, so we can see what is happening (and what is timing out), instead of seeing no logs.
