### ISSUE TITLE
Sync post_release.yaml with ci.yaml and justfile, otherwise it is failing

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#683]
e.g. https://github.com/fzyzcjy/flutter_rust_bridge/runs/8223049993?check_suite_focus=true

/cc @Desdaemon 

This may block us from releasing the new version and announce it, since code with a big red failing CI looks (at first glance) like buggy (though surely the failure does not mean buggy if digged deeper!).

**Comment by Roms1383** [comment]
An option could be to use github reusable workflows.

**Comment by fzyzcjy** [comment]
Good idea

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/issues/803
