### ISSUE TITLE
Add Chinese translation to the book

### ISSUE THREAD

**Issue by trdthg** [fzyzcjy/flutter_rust_bridge#700]
Hi, I've done a [Chinese translation](https://github.com/trdthg/flutter_rust_bindgen_book_zh) for this book.
(it's mostly done now, except for some deprecated parts and the latest web updates.)
Some people may need it and I will try to catch up with the latest book as much as possible.
So would you like to add a link to the [gh-page](https://trdthg.github.io/flutter_rust_bindgen_book_zh/) in the README or merge the translations of the book?

**Comment by fzyzcjy** [comment]
Good job!

> So would you like to add a link to the [gh-page](https://trdthg.github.io/flutter_rust_bindgen_book_zh/) in the README or merge the translations of the book?

Merging the translations LGTM :)

**Comment by trdthg** [comment]
Thanks : D ( I saw that you mentioned in your book that you replied very quickly, but never thought it would be so fast 😆 )

**Comment by fzyzcjy** [comment]
>  I saw that you mentioned in your book that you replied very quickly, but never thought it would be so fast 😆

😆

**Comment by fzyzcjy** [comment]
Btw, for a multi-lang book, as suggested in https://github.com/rust-lang/mdBook/issues/5#issuecomment-1245990552, maybe we can try about https://github.com/rust-lang/mdBook/pull/1864

**Comment by trdthg** [comment]
Ok, I'll take a look. Hoping it can make tracking updates easier.
Now I use workflow to copy the translated book directly to the _gh-pages_ branch as a subdirectory and It works fine.
