### ISSUE TITLE
[Bug] Broken links in the docs

### ISSUE THREAD

**Issue by Roms1383** [fzyzcjy/flutter_rust_bridge#731]
### Describe the bug

I was reading the docs and realized some intra links are broken. Apparently this is related to well-known issue with `mdbook` and turns out that links from subfolders are not generated when not referenced in `SUMMARY.md`.

People also pointed out to [mdbook-linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck) which I gave a quick try and indeed shows the broken links (it could probably be a nice addition to the CI).

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
_unrelated_
```

### To Reproduce

For example in [Simple correspondence](http://cjycode.com/flutter_rust_bridge/feature/lang_simple.html) when clicking on the link at the bottom of the page.

Same issue confirmed when generating the book locally.

### Additional context

I haven't filled most of the fields above since it's purely related to `mdbook`, from content generated locally or in the CI.
So the local context doesn't really matter here.

**Comment by Roms1383** [comment]
It's a good first issue, if someone wants to get started.
Otherwise I'll address it later.

**Comment by fzyzcjy** [comment]
Looks great, we may

- [ ] apply checker in CI
- [ ] fix it

**Comment by thomas725** [comment]
I'm unsure if this is related but no matter what link to what docs page I try to open, I always get 404 errors now. I believe they still worked a few days ago:
For example:
https://fzyzcjy.github.io/flutter_rust_bridge/
http://cjycode.com/flutter_rust_bridge/template/setup_web.html

**Comment by fzyzcjy** [comment]
@thomas725 That's a big problem #741

**Comment by Roms1383** [comment]
Did I break something?! It was supposed to fix it 😅

**Comment by fzyzcjy** [comment]
Well reverting that PR makes doc work now, so I guess it does accidentically break sth

**Comment by Roms1383** [comment]
Ok I'll look into it 👌 Sorry for the inconvenience

**Comment by fzyzcjy** [comment]
That's OK!
