### ISSUE TITLE
can we use rust sdk with flutter_rust_bridge

### ISSUE THREAD

**Issue by rawquesh** [fzyzcjy/flutter_rust_bridge#733]
First of all, thank you for the great package, so we want to use a rusk SDK that has multiple files (20+), is there any way we can generate all of them? Would love to hear from your side, that will be a big help.
Thank You

**Comment by fzyzcjy** [comment]
Maybe wrap around it. Or, feel free to PR to add a feature for, e.g. run codegen on another package

**Comment by rawquesh** [comment]
hey @fzyzcjy, thank you for the response, i was wondering if there's any way to generate dart files for multiple rust files.

**Comment by fzyzcjy** [comment]
http://cjycode.com/flutter_rust_bridge/feature/multiple_files.html
