### ISSUE TITLE
template stopped working

### ISSUE THREAD

**Issue by thomas725** [fzyzcjy/flutter_rust_bridge#749]
I'm unsure if it's something on my machine but I can't get [the template](https://github.com/Desdaemon/flutter_rust_bridge_template) [referenced in the docs](http://cjycode.com/flutter_rust_bridge/template/setup.html) to work anymore: https://github.com/Desdaemon/flutter_rust_bridge_template/issues/16 - Also my own [flutter playground app](https://gitlab.com/thomas351/flutter-playground) which I've based on that template stopped working.

The flutter sample included in this repository still works though, including the code generator call included in the `justfile` in the root of this repository.

Can you help me to get a standalone flutter+rust app working again please?

**Comment by Desdaemon** [comment]
Don't know how much works on your setup, but I pulled @thomas725's repository and ran codegen (1.48.0). Aside from a few dependency errors, it works fine:
![Screenshot from 2022-09-28 19-32-54](https://user-images.githubusercontent.com/36768030/192906382-8a1975cf-8f5e-4aff-9380-0d137ea03a7e.png)

**Comment by thomas725** [comment]
Oh wow! Thanks for trying to run my playground app! So something in my laptops environment must be broken.

I should have included the error messages I get in the first post, sorry:
```
$ flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
   Compiling native v0.1.0 (/home/thomas/Development/git/flutter-playground/native)
error[E0412]: cannot find type `MessagePort` in this scope
  --> src/bridge_generated.rs:22:39
   |
22 | fn wire_rust_release_mode_impl(port_: MessagePort) {
   |                                       ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `MessagePort` in this scope
  --> src/bridge_generated.rs:32:38
   |
32 | fn wire_environment_info_impl(port_: MessagePort) {
   |                                      ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `MessagePort` in this scope
  --> src/bridge_generated.rs:42:26
   |
42 | fn wire_tick_impl(port_: MessagePort) {
   |                          ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `MessagePort` in this scope
  --> src/bridge_generated.rs:52:34
   |
52 | fn wire_stop_ticking_impl(port_: MessagePort) {
   |                                  ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `MessagePort` in this scope
  --> src/bridge_generated.rs:62:39
   |
62 | fn wire_create_log_stream_impl(port_: MessagePort) {
   |                                       ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `MessagePort` in this scope
  --> src/bridge_generated.rs:72:33
   |
72 | fn wire_rust_set_up_impl(port_: MessagePort) {
   |                                 ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `DartAbi` in module `support`
   --> src/bridge_generated.rs:105:36
    |
105 |     fn into_dart(self) -> support::DartAbi {
    |                                    ^^^^^^^ not found in `support`

For more information about this error, try `rustc --explain E0412`.
error: could not compile `native` due to 7 previous errors
```

**Comment by fzyzcjy** [comment]
Suspect you have old cargo lock.

Your Cargo.lock is not in version control.

@Desdaemon download and run it, then it is fine, since auto download latest.

But in your own cargo.lock, maybe it is very old frb_rust lib, e.g. 1.34.2, no wonder there are no such structs :) https://gitlab.com/thomas351/flutter-playground/-/blob/main/native/Cargo.toml

**Comment by thomas725** [comment]
Ohhh!!! Thank you, that was exactly the right guess, after adding an ".old" suffix to both pubspec.lock & cargo.lock files and rerunning `flutter pub get` and `just` everything works again :)
