### ISSUE TITLE
[Help] Mutable Struct Example

### ISSUE THREAD

**Issue by TheLumbee** [fzyzcjy/flutter_rust_bridge#751]
I understand that you can't pass mutable values as arguments, but there aren't any example of modifying structs.

If a simple one could be provided, it would be appreciated.

Thank you

**Comment by fzyzcjy** [comment]
If you modify struct in rust, the value in dart will not be changed.

But you are free to declare as mut, say, `pub fn hello(mut a: MyStruct){}`

**Comment by TheLumbee** [comment]
So if the class/struct from dart is passed into the above function, it would move the struct but the dart object will remain. Correct?

**Comment by fzyzcjy** [comment]
yes

**Comment by TheLumbee** [comment]
Thanks for the clarification.

**Comment by fzyzcjy** [comment]
You are welcome
