### ISSUE TITLE
Using the web build with convenient tester

### ISSUE THREAD

**Issue by rob-mur** [fzyzcjy/flutter_rust_bridge#760]
**Is your feature request related to a problem? Please describe.**
I am looking to be able to use your [flutter_convenient_test](https://github.com/fzyzcjy/flutter_convenient_test) library if possible, and currently am having issues getting that to work with Web. From what I've been able to tell so far you have to be able to do flutter run ... in order to use the tester, however that doesn't seem to be possible currently with frb.

**Describe the solution you'd like**
I'd like to be able to either:
- use flutter run with frb project
- be able to connect with the convenient tester with some other command

**Describe alternatives you've considered**
I've currently been trying to just use the inbuilt flutter run with chrome but am running into a CORS error. This CORS error doesn't go away when you disable it in flutter and so I _think_ its from the function _ensureCrossOriginIsolated() in src/ffi/web.dart in frb dart.

I'm not sure what I'm trying to do would actually work if you could turn off the CORS error, but it could be worth a go - to do so I'd need to know how to set crossOriginIsolated to null (line 64).

Apologies if this isn't clear - I am relatively new to wasm in general.

**Comment by rob-mur** [comment]
Using a local version of frb I tested removing the CORS check, and whilst it does get further it's clear this was required:
```
Error: Expected a value of type 'WasmModule', but got one of type 'LegacyJavaScriptObject'
```
Will keep trying things.

**Comment by fzyzcjy** [comment]
Not very sure whether the current convenient_test codebase supports web. May need some modification (i.e. PR) to the codebase

**Comment by Desdaemon** [comment]
The `crossOriginIsolated` check exists to diagnose common problems with browsers and WASM, though I am aware that there are ways to circumvent them. Perhaps we can relax this requirement by demanding the user add a `--dart-define` so they may freely troubleshoot their own programs.

**Comment by rob-mur** [comment]
> Not very sure whether the current convenient_test codebase supports web. May need some modification (i.e. PR) to the codebase

Just did a test with a non WASM project and you are correct in that some modification would be needed to the tester as well. However I'll leave this issue up for your discussion on how to be able to pass in the right args, and create a new issue in that repo. Thanks!
