### ISSUE TITLE
[Bug] Logging sample doesn't work

### ISSUE THREAD

**Issue by azimuthdeveloper** [fzyzcjy/flutter_rust_bridge#765]
### Describe the bug

At http://cjycode.com/flutter_rust_bridge/feature/logging.html, the sample code given is this:

```
pub struct LogEntry {
    pub time_millis: i64,
    pub level: i32,
    pub tag: String,
    pub msg: String,
}

// Simplified just for demonstration.
// To compile, you need a OnceCell, or Mutex, or RwLock
// Also see https://github.com/fzyzcjy/flutter_rust_bridge/issues/398
lazy_static! { static ref log_stream_sink: StreamSink<LogEntry>; }

pub fn create_log_stream(s: StreamSink<LogEntry>) {
    stream_sink = s;
}
```

But, within the `create_log_stream` rust function, where we assign `stream_sink` to the value of `s`, `stream_sink` is not known. The only occurance of `stream_sink` occurs within the function and has not been initialised prior. So, as it is, it seems the example doesn't work. Below, we can see the assignation without creation of `stream_sink`.

![image](https://user-images.githubusercontent.com/9065229/194246680-662655af-3820-4878-88e5-84f04be0922e.png)

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
N/A
```

**Comment by fzyzcjy** [comment]
That just demonstrates the idea :) Feel free to PR for a full sample

**Comment by azimuthdeveloper** [comment]
I'm looking at the sample to try to work out how I can have a stream exposed in rust, that other functions within the rust code can write to. As it stands at the moment I can't get that to even *begin* to work because the sample doesn't work in it's current form 😭

**Comment by fzyzcjy** [comment]
This is a standard Rust question :) Maybe you need a little bit more familiarity with Rust

**Comment by azimuthdeveloper** [comment]
That's true, I'm learning Rust at the same time which is proving to be a bit of a challenge. However, as it seems at the moment, the sample code on the page doesn't compile because the variable names refer to variables that don't exist. So it does seem like a genuine documentation issue.

Once I understand more about the underlying tech and I get my stuff to work I'll definitely submit a PR though.

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/pull/537/files

Does this work for you?

Take your time!

**Comment by fzyzcjy** [comment]
LGTM. Btw you should handle the Result in the OnceCell, probably via a `?`.
