### ISSUE TITLE
Question: Does the plugin require now an additional dependency on `build_runner` and `freezed`?

### ISSUE THREAD

**Issue by gredajustyna** [fzyzcjy/flutter_rust_bridge#766]
Hello,
I've been generating bindings using this plugin for a while. In my last project, I encountered an issue `Could not find package "build_runner"` which I resolved by adding such dependency to pubspec.yaml. After running codegen, my bridge_generated.dart contained a few errors, including underlining following lines:

```
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

part 'bridge_generated.freezed.dart';
```

Now, when I added a dependency to freezed in pubspec, all errors are gone. Has something changed in the plugin or I should be searching for a source of those errors in my code solely? This is the first time I needed to add those dependencies.

**Comment by fzyzcjy** [comment]
Yes, this package does need freezed as dependency.
