### ISSUE TITLE
Opaque type support

### ISSUE THREAD

**Issue by rogurotus** [fzyzcjy/flutter_rust_bridge#775]
Hello. How is the support for opaque types. I saw that the PR #293 was abandoned. 
Is there any hope that support will be introduced or are there any problems that need to be solved

**Comment by rogurotus** [comment]
I read the PR #293 story. I did not find any blocking problem and it is not clear why it was abandoned. 
I am ready to complete this task.

**Comment by fzyzcjy** [comment]
@rogurotus Hi thanks for your interest :) I will check the history and list blockers here, probably after 10 minutes.

**Comment by fzyzcjy** [comment]
Oh I see it. In addition to

* https://github.com/fzyzcjy/flutter_rust_bridge/pull/293

Also need to read

* https://github.com/fzyzcjy/flutter_rust_bridge/issues/243
* https://github.com/fzyzcjy/flutter_rust_bridge/issues/68

And the comment says:

>         (Sad) updates:
> 
> > External size is just an input to GC scheduling heuristic.
> > **However please don't use this type. It was introduced for some internal usage and has somewhat confusing semantics.**
> 
> https://github.com/dart-lang/sdk/issues/47900
> 
> > Please don't use this type. It was introduced for some internal usage and has somewhat confusing semantics.
> 
> https://github.com/dart-lang/sdk/issues/47901
> 
> ### In short: We should **NOT** use type `Dart_CObject_kNativePointer`.

_Originally posted by @fzyzcjy in https://github.com/fzyzcjy/flutter_rust_bridge/issues/243#issuecomment-1038525958_

**Comment by fzyzcjy** [comment]
I have quickly gone through the issues and PRs. Looks like, if we want *fully automatic* way, i.e. let Dart GC to free Rust memory, we are "strongly discouraged" in https://github.com/fzyzcjy/flutter_rust_bridge/issues/243#issuecomment-1002827809. However, if we just do a *half automatic* way, i.e. let users manually call `dispose`, and the Dart GC is just a sanity checker, then I have not see immediate blockers yet.

**Comment by fzyzcjy** [comment]
> @rogurotus I am ready to complete this task.

I am willing to review and merge the PR :)

**Comment by Desdaemon** [comment]
> I read the PR #293 story. I did not find any blocking problem and it is not clear why it was abandoned. 
> I am ready to complete this task.

A lot of things have changed since that PR was opened, the most significant of which are WeakReference and FinalizationRegistry. Now there might be a better way to do this that doesn't force the user to use the `Opaque` wrapper anymore.

**Comment by fzyzcjy** [comment]
For future readers: It is sometimes strongly needed to have `dispose()` manually called; but for other cases, it is unneeded, and you can forget dispose(): https://github.com/fzyzcjy/flutter_rust_bridge/issues/1448
