### ISSUE TITLE
[Bug] code generation can't be compiled with v1.49.0 of multi blocks of modules.

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#777]
### Describe the bug

With frb 1.49.0 on win10,  Flutter 3.4.4, the project I test with generation code in `justfile`:
```
gen:
    flutter pub get
    flutter_rust_bridge_codegen \
        --rust-input \
        "native/src/rule_api.rs" \
        "native/src/ucci_api.rs" \
        "native/src/util_api.rs" \
        --dart-output \
        "lib/gened_rule_api.dart" \
        "lib/gened_ucci_api.dart" \
        "lib/gened_util_api.dart" \
        --rust-output \
        "native/src/gened_rule_api.rs" \
        "native/src/gened_ucci_api.rs" \
        "native/src/gened_util_api.rs" \
        --class-name \
        "RuleApi" \
        "UcciApi" \
        "UtilApi" \
        --dart-decl-output lib/bridge_definitions.dart \
        --wasm
```
It is easy to see there are 3 blocks of rust modules.
But it seems that it can't generate code successfully with the command `just`:
```log
[SEVERE] : Header C:\WINDOWS\TEMP\.tmpGHyO0z.h: Total errors/warnings: 2.
[SEVERE] :     C:\WINDOWS\TEMP\.tmpGHyO0z.h:20:16: error: redefinition of 'wire_uint_8_list' [Semantic Issue]
[SEVERE] :     C:\WINDOWS\TEMP\.tmpGHyO0z.h:23:3: error: typedef redefinition with different types ('struct (unnamed struct at C:\WINDOWS\TEMP\.tmpGHyO0z.h:20:16)' vs 'struct wire_uint_8_list') [Semantic Issue]
```
The command indeed finished, but with the log above during generation, I guess these should not appear, right? 
Moreover, when checking the generated dart code, say class of `RuleApi` in `gened_rule_api.dart`:
```dart
class RuleApiImpl implements RuleApi {
  final RuleApiPlatform _platform;
  factory RuleApiImpl(ExternalLibrary dylib) =>
      RuleApiImpl.raw(RuleApiPlatform(dylib));
...
}
```
It raised an issue on word `RuleApi`, saying: `"Classes and mixins can only implement other classes and mixins.
Try specifying a class or mixin, or remove the name from the list."  And there are many other issues:
![issue frb](https://user-images.githubusercontent.com/17372655/195264116-fa8d88e9-894c-4909-8b6e-a7f5e02372c7.jpg)

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
[SEVERE] : Header C:\WINDOWS\TEMP\.tmpGHyO0z.h: Total errors/warnings: 2.
[SEVERE] :     C:\WINDOWS\TEMP\.tmpGHyO0z.h:20:16: error: redefinition of 'wire_uint_8_list' [Semantic Issue]
[SEVERE] :     C:\WINDOWS\TEMP\.tmpGHyO0z.h:23:3: error: typedef redefinition with different types ('struct (unnamed struct at C:\WINDOWS\TEMP\.tmpGHyO0z.h:20:16)' vs 'struct wire_uint_8_list') [Semantic Issue]
```

### OS

win10

### Version of `flutter_rust_bridge_codegen`

1.49.0

### Flutter info

 Flutter 3.4.4

### Version of `ffigen`

6.1.2

### Additional context

Since the SEVERE ISSUE is related to `wire_uint_8_list`, and this is the inner type of rust `String`. 
I hope someone could test the [multi_test](https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/pure_dart_multi) with API contains String as input parameter, to see if CI test passed or not.

**Comment by fzyzcjy** [comment]
> I hope someone could test the [multi_test](https://github.com/fzyzcjy/flutter_rust_bridge/tree/master/frb_example/pure_dart_multi?rgh-link-date=2022-10-12T06%3A09%3A36Z) with API contains String as input parameter, to see if CI test passed or not.

Feel free to add a test into the CI, so next time nobody can break the feature you have created :) (I always ensure CI passes before merging any PR.)

**Comment by fzyzcjy** [comment]
As for the bug itself, maybe we can bisect frb so we will know which commit/PR cause the regression

**Comment by dbsxdbsx** [comment]
> As for the bug itself, maybe we can bisect frb so we will know which commit/PR cause the regression

I think it needed to check if the string parameter is ok with the multiple blocks example, first.  But I have no idea what is wrong [here](https://github.com/dbsxdbsx/flutter_rust_bridge/actions/runs/3232601944/jobs/5293417499) with the CI test. I just added some API with string parameters.
