### ISSUE TITLE
Question: How to pass enum from external library to dart?

### ISSUE THREAD

**Issue by edytapawlak** [fzyzcjy/flutter_rust_bridge#782]
In the external crate I have enum that wraps structs from that crate. Can I mirror it to pass this enum between dart/flutter and rust?

Here is [repo with an example](https://github.com/edytapawlak/frb_enum_problem) that imitates external crate structure in [`external_lib` folder](https://github.com/edytapawlak/frb_enum_problem/tree/master/external_lib). Basic idea is to have enum [`TransformedText`](https://github.com/edytapawlak/frb_enum_problem/blob/0be2c516cdef9c45c2e32590097c1f289bdbaf09/external_lib/src/lib.rs#L41) for possible transformations represented by `PrefixedText` and `SufixedText` structures. To use this enum in dart I tried `mirror` it [here](https://github.com/edytapawlak/frb_enum_problem/blob/0be2c516cdef9c45c2e32590097c1f289bdbaf09/rust/src/api.rs#L40) but in [generated code](https://github.com/edytapawlak/frb_enum_problem/blob/0be2c516cdef9c45c2e32590097c1f289bdbaf09/rust/src/bridge_generated.rs#L228) I have following error:
```
error[E0599]: the method `into_dart` exists for struct `external_lib::PrefixedText`, but its trait bounds were not satisfied
   --> rust/src/bridge_generated.rs:229:77
    |
229 |             TransformedText::Prefixed(field0) => vec![1.into_dart(), field0.into_dart()],
    |                                                                             ^^^^^^^^^ method cannot be called on `external_lib::PrefixedText` due to unsatisfied trait bounds
    |
   ::: /home/edyta/Pracka/frb_enum_problem/external_lib/src/lib.rs:50:1
    |
50  | pub struct PrefixedText {
    | -----------------------
    | |
    | doesn't satisfy `_: flutter_rust_bridge::IntoDart`
    | doesn't satisfy `external_lib::PrefixedText: Into<DartCObject>`
    |
    = note: the following trait bounds were not satisfied:
            `external_lib::PrefixedText: Into<DartCObject>`
            which is required by `external_lib::PrefixedText: flutter_rust_bridge::IntoDart`
            `&external_lib::PrefixedText: Into<DartCObject>`
            which is required by `&external_lib::PrefixedText: flutter_rust_bridge::IntoDart`
            `&mut external_lib::PrefixedText: Into<DartCObject>`
            which is required by `&mut external_lib::PrefixedText: flutter_rust_bridge::IntoDart`

```

and analogous error for `SufixedText`.
Is it possible to pass this enum between dart/flutter and rust? Any tips on how to do this?

**Comment by fzyzcjy** [comment]
Hmm I suspect it is a bug. (For example, a quick guess, maybe need to modify the codegen so it generates mirror_PrefixedText not PrefixedText?)

/cc @Unoqwy who implemented this great feature

You are also welcomed to make a PR!

**Comment by alexthe2** [comment]
one could probably simplify it to this:
```rust
impl support::IntoDart for SummaryObjectAFibV1 {
    fn into_dart(self) -> support::DartAbi {
        mirror_SummaryObjectAFibV1(self).into_dart()
    }
}
```

**Comment by alexthe2** [comment]
for now, for anyone having this issue here is the py code, but make sure to replace "Summary" with whatever u have to identify the objects else you will mirror everything:
```python
implementations = []

# Open src/bridge_generated.rs for reading
with open("src/bridge_generated.rs", "r") as f:
    # Read each line in the file, if a line contains "impl support::" and "for mirror_SummaryObject" then add the line to the implementations list
    for line in f:
        if "impl support::" in line and "for mirror_SummaryObject" in line:
            implementations.append(line)


code_chunks_to_add = []
for implementation in implementations:
    # If the implementation contains "IntoDartExceptPrimitive" then add the same line to the code_chunks_to_add list
    # but remove "mirror_" from the start of the struct name
    if "IntoDartExceptPrimitive" in implementation:
        code_chunks_to_add.append(implementation.replace("mirror_", ""))
        continue

    # If the implementation contains "IntoDart" then
    if "IntoDart" in implementation:
        # Get the struct name from the implementation
        struct_name = implementation.split("mirror_")[1].split(" ")[0]
        # Add the code chunk to the code_chunks_to_add list
        code_chunks_to_add.append("""
impl support::IntoDart for {struct_name} {{
    fn into_dart(self) -> support::DartAbi {{
        mirror_{struct_name}(self).into_dart()
    }}
}}
""".format(struct_name=struct_name))
        continue

# Open src/bridge_generated.rs for appending
with open("src/bridge_generated.rs", "a") as f:
    # Write the code_chunks_to_add list to the file
    f.write("".join(code_chunks_to_add))
```

**Comment by fzyzcjy** [comment]
@alexthe2 basically speaking, you are writing down a (small) code generator while flutter-rust-birdge itself is a (big) code generator ;) thus, it would be great to directly fix the bug

**Comment by alexthe2** [comment]
> @alexthe2 basically speaking, you are writing down a (small) code generator while flutter-rust-birdge itself is a (big) code generator ;) thus, it would be great to directly fix the bug

Ok, but then is the official way to just duplicate the Intodart? Because it seems to be a sketchy fix

**Comment by fzyzcjy** [comment]
@alexthe2 Feel free to PR and see what CI thinks :) If CI is happy (i.e. does not break anything else) then I guess that is reasonable.
