### ISSUE TITLE
> @Desdaemon Maybe we should add a bit doc about this scenario in the book? (Maybe a section at http://cjycode.com/flutter_rust_bridge/template/setup_android.html or somewhere else?)

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#788]
> @Desdaemon Maybe we should add a bit doc about this scenario in the book? (Maybe a section at http://cjycode.com/flutter_rust_bridge/template/setup_android.html or somewhere else?)

I'm considering making this option the default in the template as well, so maybe when I'm less preoccupied I'll put in the changes.

_Originally posted by @Desdaemon in https://github.com/fzyzcjy/flutter_rust_bridge/issues/405#issuecomment-1102039427_

On win10 and frb v1.49.0, I found it still necessary to manually generate `libnative.so` for x86 and x86_64, which is used for the android simulator.

~~ In addition,  with the simulation of Android TV (1080p)API 25,  even with the above library, it still cannot compile successfully, with the error :  ~~
```
adb: failed to install C:\Users\dbsx\Desktop\test_frb\build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
Error launching application on sdk google atv x86.
```
For this error, I've tried to wipe out data following [this](https://stackoverflow.com/questions/53532810/error-launching-application-on-android-sdk-built-for-x86), but it still occurred.

**Comment by fzyzcjy** [comment]
INSTALL_FAILED_INSUFFICIENT_STORAGE

looks like you have insufficient storage?

**Comment by fzyzcjy** [comment]
)Btw the title may needs a change)

**Comment by dbsxdbsx** [comment]
> (Btw the title may needs a change)

The title is generated automatically, you can change it as you like.  
By the way, do you know how to generate `libnative.so` for x86 and x86_64 by default?

**Comment by Desdaemon** [comment]
> > (Btw the title may needs a change)
> 
> The title is generated automatically, you can change it as you like.  
> By the way, do you know how to generate `libnative.so` for x86 and x86_64 by default? 

It should be two more flags to supply to `cargo ndk` IIRC. It is not by default however, you have to specify each arch to build a dylib for.

**Comment by dbsxdbsx** [comment]
> however
I know the whole correct command is like this `cargo ndk -t armeabi-v7a -t arm64-v8a -t x86 -t x86_64 -o ../android/app/src/main/jniLibs build`.

If it is agreed to make it generated for all platform by default. I am happy to pr to make it done, if you have no time.  But I need to know where need to change.

**Comment by fzyzcjy** [comment]
I am wondering whether we should generate those two by default? It will make build time twice slower by default.

**Comment by dbsxdbsx** [comment]
> I am wondering whether we should generate those two by default? It will make build time twice slower by default.

For me, making it by default would just let me know little things about how does frb works when dealing with android and corresponding simulator, and pay more attention on the project itself.

Still for me, the speed for another 2 generations is not a big deal, but the time to figure out how the android simulator works with frb does.

And personally, to make this more suitable for all users, maybe a custom flag is a good practice.

But at present, I still don't know which part of frb triggers the command `cargo ndk ...`.

**Comment by fzyzcjy** [comment]
Good idea, maybe make it default, and add sth to doc saying that "...if you feel slow and do not need this, turn off something..."

**Comment by Desdaemon** [comment]
> If it is agreed to make it generated for all platform by default. I am happy to pr to make it done, if you have no time. But I need to know where need to change.

It should be in `android/app/build.gradle` off the top of my head.

**Comment by dbsxdbsx** [comment]
> > If it is agreed to make it generated for all platform by default. I am happy to pr to make it done, if you have no time. But I need to know where need to change.
> 
> It should be in `android/app/build.gradle` off the top of my head.

I found it easy to do so. Therefore, I made a pr:https://github.com/Desdaemon/flutter_rust_bridge_template/pull/23.  Maybe document should also be updated in the future.
