### ISSUE TITLE
Flutter ffi bridge web fails 

### ISSUE THREAD

**Issue by spelltasticsoup** [fzyzcjy/flutter_rust_bridge#797]
**Is your feature request related to a problem? **
I would like to implement a Flutter Web dashboard with rust ffi bridge.

**Describe the solution you'd like**
![flutter_web_ffi_bridge](https://user-images.githubusercontent.com/105917916/197248546-ea64af2a-4549-488d-ad7e-9ba88ea96a15.png)

**Describe alternatives you've considered**
The web dashboard will only have a web endpoint. There is no requirement for a mobile native client like Android/iOS.

Alternative is YEW based dashboard.

**Additional context**
https://github.com/microscaler/dasher

This is the current repo and a run fails with the following errors

`
dasher % dart run flutter_rust_bridge:serve --crate rust
> which wasm-pack
/Users/casibbald/.cargo/bin/wasm-pack
> cargo read-manifest
> wasm-pack build -t no-modules -d /Users/casibbald/Workspace/microscaler/dev/dasher/web/pkg --no-typescript --out-name rust --dev rust -- -Z build-std=std,panic_abort
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
[WARN]: :-) origin crate has no README
[INFO]: Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 0.23s
[INFO]: :-) Your wasm pkg is ready to publish at /Users/casibbald/Workspace/microscaler/dev/dasher/web/pkg.
> flutter build web --profile

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                          
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
lib/bridge_generated.dart:11:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi' as ffi;
       ^
lib/bridge_generated.dart:90:16:
Error: Type 'ffi.DynamicLibrary' not found.
  RustPlatform(ffi.DynamicLibrary dylib) : super(RustWire(dylib));
               ^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:106:43:
Error: Type 'ffi.NativeType' not found.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                                          ^^^^^^^^^^^^^^
lib/bridge_generated.dart:106:9:
Error: Type 'ffi.Pointer' not found.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
        ^^^^^^^^^^^
lib/bridge_generated.dart:110:12:
Error: Type 'ffi.DynamicLibrary' not found.
  RustWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;
           ^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:114:41:
Error: Type 'ffi.NativeType' not found.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                                        ^^^^^^^^^^^^^^
lib/bridge_generated.dart:114:7:
Error: Type 'ffi.Pointer' not found.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      ^^^^^^^^^^^
lib/bridge_generated.dart:190:24:
Error: Type 'ffi.Bool' not found.
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
                       ^^^^^^^^
lib/bridge_generated.dart:190:64:
Error: Type 'ffi.Void' not found.
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
                                                               ^^^^^^^^
lib/bridge_generated.dart:190:52:
Error: Type 'ffi.Pointer' not found.
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
                                                   ^^^^^^^^^^^
lib/bridge_generated.dart:190:5:
Error: Type 'ffi.NativeFunction' not found.
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
    ^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:189:33:
Error: Type 'ffi.Pointer' not found.
typedef DartPostCObjectFnType = ffi.Pointer<
                                ^^^^^^^^^^^
lib/bridge_generated.dart:191:20:
Error: Type 'ffi.Int64' not found.
typedef DartPort = ffi.Int64;
                   ^^^^^^^^^
lib/bridge_generated.dart:104:7:
Error: The non-abstract class 'RustWire' is missing implementations for these members:
 - FlutterRustBridgeWireBase.storeDartPostCObject
class RustWire implements FlutterRustBridgeWireBase {
      ^^^^^^^^
/opt/homebrew/Caskroom/flutter/2.5.3/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.49.0/lib/src/ffi/web.dart:87:8:
Info: 'FlutterRustBridgeWireBase.storeDartPostCObject' is defined here.
  void storeDartPostCObject() {}
       ^^^^^^^^^^^^^^^^^^^^
lib/main.dart:11:35:
Error: Member not found: 'DynamicLibrary.open'.
late final dylib = DynamicLibrary.open(libpath);
                                  ^^^^
lib/bridge_generated.dart:127:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
                                     ^^^^
lib/bridge_generated.dart:127:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:141:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                     ^^^^
lib/bridge_generated.dart:141:56:
Error: 'Int64' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                                       ^^^^^
lib/bridge_generated.dart:141:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:155:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                     ^^^^
lib/bridge_generated.dart:155:56:
Error: 'Int64' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                                       ^^^^^
lib/bridge_generated.dart:155:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:169:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                     ^^^^
lib/bridge_generated.dart:169:56:
Error: 'Int64' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                                       ^^^^^
lib/bridge_generated.dart:169:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:183:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
                                     ^^^^
lib/bridge_generated.dart:183:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:90:20:
Error: 'DynamicLibrary' isn't a type.
  RustPlatform(ffi.DynamicLibrary dylib) : super(RustWire(dylib));
                   ^^^^^^^^^^^^^^
lib/bridge_generated.dart:106:47:
Error: 'NativeType' isn't a type.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                                              ^^^^^^^^^^
lib/bridge_generated.dart:106:13:
Error: 'Pointer' isn't a type.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
            ^^^^^^^
lib/bridge_generated.dart:110:16:
Error: 'DynamicLibrary' isn't a type.
  RustWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;
               ^^^^^^^^^^^^^^
lib/bridge_generated.dart:114:45:
Error: 'NativeType' isn't a type.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                                            ^^^^^^^^^^
lib/bridge_generated.dart:114:11:
Error: 'Pointer' isn't a type.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          ^^^^^^^
Error: Compilation failed.

Compiling lib/main.dart for the Web...                              3.7s
Exception: Failed to compile application for the Web.
Unhandled exception:
ProcessException: Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
lib/bridge_generated.dart:11:8:
Error: Not found: 'dart:ffi'
import 'dart:ffi' as ffi;
       ^
lib/bridge_generated.dart:90:16:
Error: Type 'ffi.DynamicLibrary' not found.
  RustPlatform(ffi.DynamicLibrary dylib) : super(RustWire(dylib));
               ^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:106:43:
Error: Type 'ffi.NativeType' not found.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                                          ^^^^^^^^^^^^^^
lib/bridge_generated.dart:106:9:
Error: Type 'ffi.Pointer' not found.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
        ^^^^^^^^^^^
lib/bridge_generated.dart:110:12:
Error: Type 'ffi.DynamicLibrary' not found.
  RustWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;
           ^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:114:41:
Error: Type 'ffi.NativeType' not found.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                                        ^^^^^^^^^^^^^^
lib/bridge_generated.dart:114:7:
Error: Type 'ffi.Pointer' not found.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      ^^^^^^^^^^^
lib/bridge_generated.dart:190:24:
Error: Type 'ffi.Bool' not found.
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
                       ^^^^^^^^
lib/bridge_generated.dart:190:64:
Error: Type 'ffi.Void' not found.
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
                                                               ^^^^^^^^
lib/bridge_generated.dart:190:52:
Error: Type 'ffi.Pointer' not found.
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
                                                   ^^^^^^^^^^^
lib/bridge_generated.dart:190:5:
Error: Type 'ffi.NativeFunction' not found.
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
    ^^^^^^^^^^^^^^^^^^
lib/bridge_generated.dart:189:33:
Error: Type 'ffi.Pointer' not found.
typedef DartPostCObjectFnType = ffi.Pointer<
                                ^^^^^^^^^^^
lib/bridge_generated.dart:191:20:
Error: Type 'ffi.Int64' not found.
typedef DartPort = ffi.Int64;
                   ^^^^^^^^^
lib/bridge_generated.dart:104:7:
Error: The non-abstract class 'RustWire' is missing implementations for these members:
 - FlutterRustBridgeWireBase.storeDartPostCObject
class RustWire implements FlutterRustBridgeWireBase {
      ^^^^^^^^
/opt/homebrew/Caskroom/flutter/2.5.3/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.49.0/lib/src/ffi/web.dart:87:8:
Info: 'FlutterRustBridgeWireBase.storeDartPostCObject' is defined here.
  void storeDartPostCObject() {}
       ^^^^^^^^^^^^^^^^^^^^
lib/main.dart:11:35:
Error: Member not found: 'DynamicLibrary.open'.
late final dylib = DynamicLibrary.open(libpath);
                                  ^^^^
lib/bridge_generated.dart:127:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
                                     ^^^^
lib/bridge_generated.dart:127:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:141:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                     ^^^^
lib/bridge_generated.dart:141:56:
Error: 'Int64' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                                       ^^^^^
lib/bridge_generated.dart:141:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:155:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                     ^^^^
lib/bridge_generated.dart:155:56:
Error: 'Int64' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                                       ^^^^^
lib/bridge_generated.dart:155:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:169:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                     ^^^^
lib/bridge_generated.dart:169:56:
Error: 'Int64' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                                                       ^^^^^
lib/bridge_generated.dart:169:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:183:38:
Error: 'Void' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
                                     ^^^^
lib/bridge_generated.dart:183:19:
Error: 'NativeFunction' isn't a type.
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
                  ^^^^^^^^^^^^^^
lib/bridge_generated.dart:90:20:
Error: 'DynamicLibrary' isn't a type.
  RustPlatform(ffi.DynamicLibrary dylib) : super(RustWire(dylib));
                   ^^^^^^^^^^^^^^
lib/bridge_generated.dart:106:47:
Error: 'NativeType' isn't a type.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                                              ^^^^^^^^^^
lib/bridge_generated.dart:106:13:
Error: 'Pointer' isn't a type.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
            ^^^^^^^
lib/bridge_generated.dart:110:16:
Error: 'DynamicLibrary' isn't a type.
  RustWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;
               ^^^^^^^^^^^^^^
lib/bridge_generated.dart:114:45:
Error: 'NativeType' isn't a type.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                                            ^^^^^^^^^^
lib/bridge_generated.dart:114:11:
Error: 'Pointer' isn't a type.
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          ^^^^^^^
Error: Compilation failed.

Exception: Failed to compile application for the Web.

  Command: flutter build web --profile
#0      system (file:///Users/casibbald/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.49.0/bin/serve.dart:75:5)
<asynchronous suspension>
#1      build (file:///Users/casibbald/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.49.0/bin/serve.dart:273:5)
<asynchronous suspension>
#2      main (file:///Users/casibbald/.pub-cache/hosted/pub.dartlang.org/flutter_rust_bridge-1.49.0/bin/serve.dart:215:5)
<asynchronous suspension>

`

**Comment by Desdaemon** [comment]
You'll need to import `bridge_generated.web.dart` instead. The with_flutter example should have a snippet of how to use the generated web bindings.
