### ISSUE TITLE
Support of std::any with dart dynamic?

### ISSUE THREAD

**Issue by alexthe2** [fzyzcjy/flutter_rust_bridge#798]
**Is your feature request related to a problem? Please describe.**
I had a small issue when I tried to wrap a Command Pattern around the flutter bridge, with a struct like this:
```rust
pub struct FireEvent {
    pub source: FireSource,
    pub id: Box<dyn std::any::Any>,
}
```
Now instead of doing it this way, I need a bunch lot of optionals for all possible datatypes that my FireEvent should support. 

**Describe the solution you'd like**
A support for `std::any::Any` mapping to dart `dynamic` would be amazing

**Describe alternatives you've considered**
A lot of optionals 😞 

**Additional context**
I have tried to add this functionality myself, but I didn't get particularly far, mainly due to my missing knowledge of `Any`

**Comment by fzyzcjy** [comment]
What about `enum`?

**Comment by alexthe2** [comment]
yeah you're right, I used an enum for the source and then totally forgot about it. Also an enum is propably more type safe and allows for less stupid mistakes

**Comment by fzyzcjy** [comment]
I agree, rust enums are really wonderful :)

**Comment by alexthe2** [comment]
maybe it's a worthy update to the docs, how a `dynamic` field could be wrapped? Though it's not truly dynamic but I think it's worth the mention

**Comment by fzyzcjy** [comment]
Sure, feel free to PR

**Comment by alexthe2** [comment]
Actually, the enums don't work, the bridge is creating a new class but is lacking the subimplementations (though creating a reference lacking the implementations). I'll share an example when I get home.

**Comment by alexthe2** [comment]
so I have this on the rust side:
```rust
pub struct FireEvent {
    pub source: FireSource,
    pub data: FireData,
}

pub enum FireData {
    CGM(CGM),
    User(User),
    Fast(Fast),
}

pub enum FireSource {
    User,
    Fast,
    CGM,
    Event,
    Summary,
}
```
which generates this on the dart side:
```dart
FireData _wire2api_fire_data(dynamic raw) {
    switch (raw[0]) {
      case 0:
        return FireData_CGM(
          _wire2api_box_autoadd_cgm(raw[1]),
        );
      case 1:
        return FireData_User(
          _wire2api_box_autoadd_user(raw[1]),
        );
      case 2:
        return FireData_Fast(
          _wire2api_box_autoadd_fast(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }
```

and this:
```dart
@freezed
class FireData with _$FireData {
  const factory FireData.cgm(
    CGM field0,
  ) = FireData_CGM;
  const factory FireData.user(
    User field0,
  ) = FireData_User;
  const factory FireData.fast(
    Fast field0,
  ) = FireData_Fast;
}
```

but there is no `FireData_CGM`, `FireData_User` ... generated

**Comment by alexthe2** [comment]
actually it's probably more of a `freezed` problem, I'll try to figure it out cause the builder is not fixing it

**Comment by alexthe2** [comment]
nvm, I have just forgot to add `flutter pub add --dev freezed` in the project I was using

**Comment by alexthe2** [comment]
I'll close this as it doesn't seem relevant for now
