### ISSUE TITLE
[Bug] vec<bool> not supported 

### ISSUE THREAD

**Issue by alexthe2** [fzyzcjy/flutter_rust_bridge#801]
### Describe the bug

I found out that `Vec<bool>` is not supported, when having the following function included in my `api.rs`.
```rust
pub fn write_foo(basis_events: Vec<Foo>) -> anyhow::Result<Vec<bool>> {
    ***
}
```

This is the function as when I replace it it starts to work. Is this a bug or a missing feature?
```rust
pub fn write_foo(foo_events: Vec<Foo>) -> anyhow::Result<bool> {
    ***
}
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
PS C:\Users\alexp\foo> $env:RUST_BACKTRACE = 'debug'; flutter_rust_bridge_codegen --rust-input v12\src\api.rs --dart-output .\lib\bridge_generated.dart --dart-decl-output .\lib\bri
dge_definitions.dart
[2022-10-23T23:22:17Z WARN  lib_flutter_rust_bridge_codegen::source_graph] Skipping unresolvable module io (tried \\?\C:\Users\alexp\Basis\basis-hybrid\v12\src\io.rs, \\?\C:\Users\alexp\foo\v12\src\io\mod.rs, \\?\C:\Users\alexp\foo\v12\src\bridge_generated\io.rs, \\?\C:\Users\alexp\foo\v12\src\bridge_generated\io\mod.rs, )
thread 'main' panicked at 'does not support Bool yet', C:\Users\alexp\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.49.0\src\ir\ty_primitive_list.rs:31:18
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### OS

Windows

### Additional context

I simplified most of the stuff to foo

**Comment by fzyzcjy** [comment]
> thread 'main' panicked at 'does not support Bool yet', C:\Users\alexp\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.49.0\src\ir\ty_primitive_list.rs:31:18

Looks like problem is:

* When seeing `Vec<bool>`, it uses IRPrimitiveList not IRGeneralList
* However, IRPrimitiveList only supports `Vec<u8>`, `Vec<i8>`, ..., not `Vec<bool>`, since there is only Uint8List/Int8List/... no BoolList

solution:

* when seeing Vec bool, categorize it as IRGeneralList, *not* IRPrimitiveList, in the *parser*

**Comment by fzyzcjy** [comment]
(undo automatic github action, since https://github.com/fzyzcjy/flutter_rust_bridge/pull/1353 links to this)
