### ISSUE TITLE
`flutter_rust_bridge_codegen` panics: `system cannot find the file specified.` when executing `dart` command using Rust's `Command`

### ISSUE THREAD

**Issue by mohamedSulaimanAlmarzooqi** [fzyzcjy/flutter_rust_bridge#81]
When trying to generate using flutter_rust_bridge, The bridge_generated.rs file gets created, However, It scene to crash after doing that with a not foudn file panic.

I ran the command like this
flutter_rust_bridge_codegen --rust-input src/api.rs --dart-output fastengine.dart --c-output fastengine.h

The error is this

[2021-10-15T12:54:22Z INFO  flutter_rust_bridge_codegen] Picked config: Opts { rust_input_path: "C:\\Users\\mohamed\\projects\\lom\\fastengine\\src/api.rs", dart_output_path: "C:\\Users\\mohamed\\projects\\lom\\fastengine\\fastengine.dart", c_output_path: "C:\\Users\\mohamed\\projects\\lom\\fastengine\\fastengine.h", rust_crate_dir: "C:\\Users\\mohamed\\projects\\lom\\fastengine", rust_output_path: "C:\\Users\\mohamed\\projects\\lom\\fastengine\\src\\bridge_generated.rs", class_name: "Fastengine", dart_format_line_length: 80 }
[2021-10-15T12:54:22Z INFO  flutter_rust_bridge_codegen] Phase: Parse source code to AST
[2021-10-15T12:54:22Z INFO  flutter_rust_bridge_codegen] Phase: Parse AST to IR
[2021-10-15T12:54:22Z INFO  flutter_rust_bridge_codegen] Phase: Transform IR
[2021-10-15T12:54:22Z INFO  flutter_rust_bridge_codegen] Phase: Generate Rust code
[2021-10-15T12:54:22Z INFO  flutter_rust_bridge_codegen] Phase: Generate Dart code
[2021-10-15T12:54:22Z INFO  flutter_rust_bridge_codegen] Phase: Other things
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\mohamed\.cargo\registry\src\github.com-1ecc6299db9ec823\flutter_rust_bridge_codegen-1.1.0\src\commands.rs:20:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 - OS: Windows
 - Version: 10
 - Version of `flutter_rust_bridge_codegen`: 1.1.0
 - Version of `clang++`: 11.0.0
 - Version of `cbindgen`: 0.2.0.0

**Comment by fzyzcjy** [comment]
let me have a look

**Comment by fzyzcjy** [comment]
I am using Rust's `Command` to execute commands - that should be quite standard

**Comment by mohamedSulaimanAlmarzooqi** [comment]
Yes, I did the steps on the main github page, And running dart pub global run ffigen gives

Running in Directory: 'C:\Users\mohamed\projects\lom'
[SEVERE] : Couldn't find an entry for 'ffigen' in pubspec.yaml.

Tried the rust code, And

execute command: "dart" "pub" "global" "run" "ffigen"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', rusttest.rs:18:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by fzyzcjy** [comment]
Aha, so that is problem of Rust's builtin `Command`. 

> Running in Directory: 'C:\Users\mohamed\projects\lom'
[SEVERE] : Couldn't find an entry for 'ffigen' in pubspec.yaml.

This means the `dart` command *can* be found (ignore the "SEVERE" since we really do not give it a yaml).

> thread 'main' panicked at 'called Result::unwrap() on an Err value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', rusttest.rs:18:35

This means Rust's builtin `Command` fails to work.

It seems to be the setup problem of your computer.

**Comment by mohamedSulaimanAlmarzooqi** [comment]
So what should I do? Reinstall rust?

**Comment by fzyzcjy** [comment]
No. I guess it is problem of environment variables. Search for things like, e.g., Rust's `Command` says `The system cannot find the file specified.

**Comment by fzyzcjy** [comment]
I do not have a windows computer at my hand. You may also look at the CI: https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/.github/workflows/codegen.yml it  runs code generator on windows (as well as mac and linux) and it works

**Comment by fzyzcjy** [comment]
I suspect how you install `dart` command. Maybe you need to consider `PATH` environment variable as well.

**Comment by mohamedSulaimanAlmarzooqi** [comment]
Alright, I see now, It seems since I was using the dart installation used with flutter, It was erroring for some reason, So I replaced the flutter dart with the dart from the official site and it works, Thanks for the help.

**Comment by fzyzcjy** [comment]
You are welcome! Glad you find out the solution.
