### ISSUE TITLE
functions differ on different platforms

### ISSUE THREAD

**Issue by clsx524** [fzyzcjy/flutter_rust_bridge#811]
Hi, I am trying to use this framework within a flutter app to call backend APIs defined in protobuf. The generated client (use prost) can send requests with tokio for non-wasm platforms, however for wasm I have to use other libraries such as tonic-web-wasm-client. Therefore I need to implement two methods to make such calls for different platforms. What is the recommended setup in general to write methods specific to a platform and declare dependencies for that platform as well?

**Comment by fzyzcjy** [comment]
e.g. https://rustwasm.github.io/docs/book/reference/add-wasm-support-to-crate.html (a quick google shows this)

**Comment by clsx524** [comment]
Hi, thanks for quick response. I was trying the following setup but got errors.

in Cargo.toml
```
[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic-web-wasm-client = "0.2.2"
```

in api.rs
```
#[cfg(target_arch = "wasm32")]
pub fn register_account_wasm(email: String, password: String) -> anyhow::Result<i64> {
// use tonic-web-wasm-client here
}
```
the bridge_generated.rs and other files are generated fine and `flutter run` with chrome has no error. However it won't work in browser later due to cross origin errors.

Then I tried `flutter_rust_bridge_serve`. it would fail because it's trying to compile mio which comes from tonic-web-wasm-client and reqwest. Reqwest would exclude mio under wasm32, so I suspect the target when running `flutter_rust_bridge_serve` is not wasm32. How should I use this type of package that only works for certain targets?

**Comment by fzyzcjy** [comment]
Btw do not use `#[cfg(target_arch = "wasm32")]` etc in api.rs. Instead, do it in another .rs file which flutter_rust_bridge do not scan.

It is unrelated to this package how to solve cross origin errors etc :)

**Comment by clsx524** [comment]
Sorry, I am pretty new to this package and rust.

Sure. I moved those functions to a separate file but I still need to write a function in api.rs to call one of them like
```
pub fn register_account(email: String, password: String) -> anyhow::Result<i64> {
    if matches!(platform(), Platform::Wasm) {
        return crate::api_web::register_account_wasm(email, password);
    }
    return crate::api_web::register_account_io(email, password);
}
```
however this won't work because register_account_wasm has `#[cfg(target_arch = "wasm32")]` and would definitely fail on desktop build.

Do you know any alternative approach that would make it work with api.rs?

**Comment by fzyzcjy** [comment]
No.

```rust

//api.rs
pub fn register_account(email: String, password: String) -> anyhow::Result<i64> {
    return crate::another_file::register_account(email, password);
}

//another_file.rs

#[cfg(target_arch = "wasm32")]
pub fn register_account(email: String, password: String) -> anyhow::Result<i64> {...}
#[cfg(not(target_arch = "wasm32"))]
pub fn register_account(email: String, password: String) -> anyhow::Result<i64> {...different implementation...}
```

**Comment by clsx524** [comment]
Thanks, this works great.

**Comment by fzyzcjy** [comment]
You are welcome
