### ISSUE TITLE
Question: How can I send a Stream<Uint8List> to Rust?

### ISSUE THREAD

**Issue by redsolver** [fzyzcjy/flutter_rust_bridge#814]
**Is your feature request related to a problem? Please describe.**
I would like to send a `Stream<Uint8List>` I receive in Dart over the network to a Rust function that hashes the entire stream using https://lib.rs/crates/blake3

**Describe the solution you'd like**
Somehow hold a state for a specific computation in Rust and keep adding data from Dart to it and then finalize it.

**Describe alternatives you've considered**
I tried to create a `struct` that holds the `blake3::Hasher` state and has methods to update the hash and finalize it. Unfortunately this doesn't work because `flutter_rust_bridge` tries to bridge the `blake3::Hasher` to Dart which doesn't seem to work and is also unnecessary. The hashing state only needs to exist on the Rust side.

**Comment by fzyzcjy** [comment]
Maybe use https://github.com/fzyzcjy/flutter_rust_bridge/pull/795

Or, use static variables in rust to hold states

Or, https://cjycode.com/flutter_rust_bridge/feature/object_pool.html

**Comment by redsolver** [comment]
Thank you, object pools seem to be exactly what I'm looking for. Is there maybe an example of an app using them somewhere? That would really help me implementing them.

**Comment by fzyzcjy** [comment]
is this example helpful? https://github.com/fzyzcjy/flutter_rust_bridge/pull/333#issuecomment-1037079219
