### ISSUE TITLE
Chrono dependency is fixed (conflict)

### ISSUE THREAD

**Issue by vincent-herlemont** [fzyzcjy/flutter_rust_bridge#820]
Here Chrono dependency:

https://github.com/fzyzcjy/flutter_rust_bridge/blob/2f77dc606af7acbbd9ab5ec77ca4094ba06587fe/Cargo.toml#L22

However, that can be come into conflict with others libs like sentry for example:
```bash
error: failed to select a version for `chrono`.
    ... required by package `sentry-types v0.28.0`
    ... which satisfies dependency `sentry-types = "^0.28.0"` of package `sentry-core v0.28.0`
    ... which satisfies dependency `sentry-core = "^0.28.0"` of package `sentry v0.28.0`
    ... which satisfies dependency `sentry = "^0.28"` of package `my-lib v0.1.0 (/rust)`
versions that meet the requirements `^0.4.22` are: 0.4.22

all possible versions conflict with previously selected packages.

  previously selected package `chrono v0.4.20`
    ... which satisfies dependency `chrono = "=0.4.20"` of package `flutter_rust_bridge v1.49.0`
    ... which satisfies dependency `flutter_rust_bridge = "^1.49.0"` of package `my-lib v0.1.0 (/rust)`
````
How do you think to set Chrono lib with a not strict minor version like ` chrono = "0.4" ` instead of `chrono = "=0.4.20"` ?

**Comment by fzyzcjy** [comment]
Sure, I totally agree.

/cc @Roms1383 IIRC seems this is implemented by you - is there reasons we should lock this?

**Comment by fzyzcjy** [comment]
Feel free to PR!

**Comment by Roms1383** [comment]
sure, if it fixes go ahead!
0.4.20 was the last one working for me at that time. (after there was a dependency related issue but honestly I don't remember the details 😅
