### ISSUE TITLE
unable to read external files on macos

### ISSUE THREAD

**Issue by clsx524** [fzyzcjy/flutter_rust_bridge#827]
Similar to this [issue](https://github.com/fzyzcjy/flutter_rust_bridge/issues/206), I am trying to read a local yaml file in rust, i put the file in native_config directory under my project top directory. it works fine on linux however it complains not able to find the file on MacOS. I have tried the following but none of them work.
- absolute path to the file.
- add the directory and file into macos directory and they can appear in the Resources of the xcode project.
- add the directory and file into "Copy Bundles Resources" of the Runner target or native-cdylib target in xcode

Is there any guidance to read external files on MacOS?

**Comment by fzyzcjy** [comment]
IMHO this is a rust problem instead of flutter_rust_bridge problem. Anyway, looks like it is a macos "sandbox" problem?
