### ISSUE TITLE
[Bug] Wrapping an enum parameter in Option

### ISSUE THREAD

**Issue by GregoryConrad** [fzyzcjy/flutter_rust_bridge#828]
### Describe the bug

Looks like I might've ran into a bug with code gen:

```rust
pub enum BugTest {
    Foobar,
}
pub fn bug_test(foo: Option<BugTest>) {}
```

 Yields the following output (I have this with a `build.rs` if it matters):

![Screenshot](https://user-images.githubusercontent.com/15874617/200197347-54b24266-8618-4b1d-81f6-62e76c3e951a.png)

This happens only when wrapping the enum in `Option`. Passing the enum directly without `Option` runs ok.

Is this intentional behavior or is it an issue with codegen? I would love to contribute with a PR, but I unfortunately only started learning rust a few days ago, and would have no clue where to start.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Output too long to paste here, so here's a link:

https://pastebin.com/uDJ71iS7
```

### To Reproduce

```rust
pub enum BugTest {
    Foobar,
}
pub fn bug_test(foo: Option<BugTest>) {}
```

### OS

macOS

### Version of `flutter_rust_bridge_codegen`

1.49.1

**Comment by fzyzcjy** [comment]
Looks like it is a bug. Feel free to PR!

https://cjycode.com/flutter_rust_bridge/contributing/design.html this may be helpful

**Comment by GregoryConrad** [comment]
Finally getting around to a PR for this. I'm sure I'll have some questions but I'll see how far I can get first.

**Comment by GregoryConrad** [comment]
I'm just going to leave some notes here for myself for the PR

# What's missing in Rust (`bridge_generated.*.rs`)
```rust
// For "complex" enums
impl Wire2Api<ComplexEnum> for *mut Option<wire_ComplexEnum> {
    fn wire2api(self) -> ComplexEnum {
        todo!()
    }
}

// For "simple" enums
impl Wire2Api<SimpleEnum> for *mut Option<i32> {
    fn wire2api(self) -> SimpleEnum {
        todo!()
    }
}
```

# What's missing in Dart (`bridge_generated.*.dart`)
TODO

**Comment by fzyzcjy** [comment]
When unsure, maybe we can look at how existing code is implemented. For example, what happens for a `Option<some_struct>`?

also cc @Desdaemon who implemented that wonderful enum feature

**Comment by GregoryConrad** [comment]
I actually just looked into `Option` of `struct`s, which appears to be Boxed in `Ir`. However, `enum`s are not wrapped in `Ir`.

**Comment by GregoryConrad** [comment]
Something is off with the enum implementation in a few parts here (should they actually be boxed? Should they always be a pointer when not wasm?) but I simply do not know enough about enums/ffi/Rust to be able to give a definitive answer on how the enum implementation should look.

**Comment by GregoryConrad** [comment]
I still am fairly new to Rust (started learning less than a month ago), but here is what I am guessing about the enum implementation. @Desdaemon please correct me if I am wrong.

Enums are not wrapped in `Box` because of "simple" enums, when you only need an `i32` to pass it across the wire:
```rust
enum Color {
    Red, Green, Blue
}
```
(where red = 0, green = 1, blue = 2.)

However, it looks as though when dealing with structs, by wrapping `struct` in `Boxed`, we get the needed `Option` handling (and others) for free.

Because of that, I think the proper solution here would just be forcing all enums to be boxed, even though it is detrimental for when dealing with non-option "simple" enums like the `Color` above. Having a heap initialization for just one integer for that one case should be ok to give us everything else related to enums for free.

I will note, though, as I simply do not know how this enum implementation was made. Perhaps there is a technical reason I am overlooking for why `enum`s were not boxed.

**Comment by Desdaemon** [comment]
I saw a `*mut Option<i32>` in the error, I suspect this is an edge case I didn't account for in the tests. The correct wire type should be `*mut i32`.

**Comment by GregoryConrad** [comment]
@Desdaemon The bug actually goes a bit beyond what I outlined in the initial bug report. https://github.com/fzyzcjy/flutter_rust_bridge/issues/828#issuecomment-1337972415 is much more descriptive of the true underlying errors that I *think* would both be fixed by forcing enum to be boxed.

**Comment by Desdaemon** [comment]
The fix seems to be another condition, however I think this is also an opportunity to refactor EnumRef and Optional to play better with each other. Perhaps we can start by separating EnumRef into a value-only Enum and payload-carrying EnumStruct.

**Comment by Desdaemon** [comment]
There *is* one optimization that we can do: for certain combinations such as `Option<NonZeroI32>` or `Option<T>` where T is an enum that can never be 0, we can *optimize* the 0-case to be None. It is doubtful this will be a great performance gain, but perhaps someone wishing to pursue it in the future can do it.

**Comment by Desdaemon** [comment]
:eyes:
