### ISSUE TITLE
Opaque Dart type support

### ISSUE THREAD

**Issue by rogurotus** [fzyzcjy/flutter_rust_bridge#837]
adding support for opaque dart types.
Let's add the ability for rust to receive dart objects (Dart_Handle). 

The dart API(`dart_api_dl.h`) provides functions for dart object persistence.
https://github.com/dart-lang/sdk/issues/47356#issuecomment-1302306273

- Dart_NewPersistentHandle
- Dart_HandleFromPersistent
- Dart_DeletePersistentHandle

something like that
```
// internal implementation
struct DartOpaque(Dart_PersistentHandle);

impl Drop for DartOpaque {
  fn drop(&mut self) {
    Dart_DeletePersistentHandle(self.0);
  }
}

// Rust
pub fn dart_opaque(obj: DartOpaque) {
  // rust can save, delete, or use as needed.
}

// Dart
api.dartOpaque(Object obj);
```

about !Send, !Sync `Dart_Handle`:
the easiest way is to provide only `syncReturn executor`.

**Comment by fzyzcjy** [comment]
> the easiest way is to provide only syncReturn executor.

hmm IIRC syncreturn is very limited and async is the main thing, so hopefully we can support async

maybe via object pool?

**Comment by rogurotus** [comment]
if I'm not mistaken, we still can't use dart_handle in the thread pool (unless we save it, give it back). And so with object pool we lose compatibility with dart api \ c api. 
I also have a development for an opaque syncReturn type. This covers a wide range of needs.

**Comment by rogurotus** [comment]
I understand the idea, but it would be highly desirable to maintain compatibility with the Dart_Handle api.
And for safe `drop` on the threadpool, instead of manual deletion, we can delegate this to Dart through the Dart port

**Comment by fzyzcjy** [comment]
> but it would be highly desirable to maintain compatibility with the Dart_Handle api.

May I know a bit more why we need to have this compatibility? IMHO most flutter/rust dev do not use that API directly, and even if use it, I have not seen where compatibility has advantage.

> And for safe drop on the threadpool, instead of manual deletion, we can delegate this to Dart through the Dart port

looks interesting. But that will cause objects never freed until the current sync thing is finished in dart thread. For example, inside one (possibly janky) frame.

**Comment by fzyzcjy** [comment]
Again, this feature is quite interesting and complex, that's why we need to consider it carefully :)

**Comment by rogurotus** [comment]
> May I know a bit more why we need to have this compatibility? IMHO most flutter/rust dev do not use that API directly, and even if use it, I have not seen where compatibility has advantage.

Dart_handle is used to call dart functions from rust, which is just safe for syncReturn.

> looks interesting. But that will cause objects never freed until the current sync thing is finished in dart thread. For example, inside one (possibly janky) frame.

We can use different drop for sync\async

**Comment by fzyzcjy** [comment]
> Dart_handle is used to call dart functions from rust, which is just safe for syncReturn.

Yes I know it. What I get confused is: when saying "be highly desirable to maintain compatibility with the Dart_Handle api", what is to be compatible with?

Currently, IIRC flutter_rust_bridge does not use Dart_Handle at all. (It uses DartCObject though but it is different).

**Comment by rogurotus** [comment]
by dart_hanle api I mean the ability to get dart_handle on the rust side.

**Comment by fzyzcjy** [comment]
Still confused :( Why do an end user needs to get the handle?

I guess I am lacking some context, or maybe this is an X-Y problem.

**Comment by rogurotus** [comment]
for example, call a dart function with a dart object argument directly from rust.

**Comment by fzyzcjy** [comment]
I see. Without the Dart_Handle, we will have to do one more indirection by adding a wrapper function etc (though that overhead may be small)

**Comment by rogurotus** [comment]
Yes use dart.ffi directly from rust

**Comment by rogurotus** [comment]
we can also create a wrapper on top of this mechanism

**Comment by fzyzcjy** [comment]
Sure, we should not expose too low-level things

**Comment by rogurotus** [comment]
if you are against Dart_Handle. I will take on PR for the object pool

**Comment by fzyzcjy** [comment]
It depends on you. Personally I prefer object pool for reasons above, but you can also choose the Dart_Handle approach if you think it has more advantages :)

**Comment by rogurotus** [comment]
That is, the main thing is to ensure safety. And so I can start PR with Dart_Handle

**Comment by rogurotus** [comment]
Regarding using `ReceivePort` to drop `DartOpaque` on the thread pool. Here comes the following problem:
while there is a `ReceivePort`, the `Dart isolate` cannot be completed. As a consequence, we must close the `ReceivePort`.

- way 1 - require manually closing the port for each instance of ApiClass (not good).
- way 2 - only `syncReturn`

If we are using a one-time `ReceivePort`, then we will need to require rust to drop all `DartOpaque`.

https://github.com/dart-lang/sdk/issues/49083

**Comment by fzyzcjy** [comment]
> Regarding using ReceivePort to drop DartOpaque on the thread pool. Here comes the following problem

Hmm, so do we have this problem for Flutter apps? If this is a problem for pure Dart app only, then way 1 may not be bad (e.g. `main() { ...main body...; api.close(); }` is enough)

In addition, what is flutter_rust_bridge currently using - IIRC it uses some ReceivePort already?

**Comment by rogurotus** [comment]
> Hmm, so do we have this problem for Flutter apps? If this is a problem for pure Dart app only, then way 1 may not be bad (e.g. `main() { ...main body...; api.close(); }` is enough)

which was pretty strange for me, but the open ReceivePort doesn't block flutter (integration_test at least).
so the way with api.close() is acceptable

> Or, just a random thought appeared in my mind: Can we create one port for one object? Then when we want to drop that dart object, we utilize that one-time port.

getting a hang of `Dart` if somewhere inside `Rust` remains `DartOpaque` is not good.
especially if it's the end of main() fn and we expect the app to just close.
