### ISSUE TITLE
[feat] generate web file in dart if dart_decl_output = None

### ISSUE THREAD

**Issue by huang12zheng** [fzyzcjy/flutter_rust_bridge#860]
**Is your feature request related to a problem? Please describe.**

generate web file in dart if dart_decl_output = None
```
let raw_opts = RawOpts {
        // Path of input Rust code
        rust_input: RUST_INPUTS.into_vecs(),
        // Path of output generated Dart code
        dart_output: dart_outputs,
        wasm: true,
        rust_output: Some(rust_outputs),
        // dart_decl_output: Some("../lib/bridge_definitions.dart".into()),   /// would never gen .web
        dart_format_line_length: 120,
        class_name: Some(CLASS_NAMES.into_vecs()),
        // for other options use defaults
        ..Default::default()
    };
```
* some code change
https://github.com/huang12zheng/flutter_rust_bridge/commit/a12ddc9e2bc5f4aa6c4c52ebeba30f21cb27415c

* expect
would generator .web file
> ps My final scenario is in a multi-file case

**Comment by fzyzcjy** [comment]
Feel free to PR!

**Comment by huang12zheng** [comment]
* a more info for ci:
example pure_dart_multi would no use flag dart_decl_output,
and other examples like pure_dart which use flag dart_decl_output
