### ISSUE TITLE
support `pub struct IDb(pub Opaque<Surreal<Db>>)`

### ISSUE THREAD

**Issue by huang12zheng** [fzyzcjy/flutter_rust_bridge#863]
I'm not sure if that mode is supported. Or how to support it

```rs
pub struct IDb(pub Opaque<Surreal<Db>>);
```
```dart
@sealed
class SurrealDb extends FrbOpaque {
  final Db bridge;
  SurrealDb.fromRaw(int ptr, int size, this.bridge) : super.unsafe(ptr, size);
  @override
  DropFnType get dropFn => bridge.dropOpaqueSurrealDb;  //  error

  @override
  ShareFnType get shareFn => bridge.shareOpaqueSurrealDb;

  @override
  OpaqueTypeFinalizer get staticFinalizer => bridge.SurrealDbFinalizer;
}

class IDb {
  final SurrealDb field0;

  IDb({
    required this.field0,
  });
}
```
* error
```
The getter 'shareOpaqueSurrealDb' isn't defined for the type 'Db'.
Try importing the library that defines 'shareOpaqueSurrealDb', correcting the name to the name of an existing getter, or defining a getter or field named 'shareOpaqueSurrealDb'.
```

**Comment by huang12zheng** [comment]
Is it related to 773?

**Comment by fzyzcjy** [comment]
Hmm looks like a bug.

/cc @rogurotus who implemented the wonderful Opaque feature - a naive guess, maybe we forget to trigger code generation for this case?

**Comment by rogurotus** [comment]
I was unable to reproduce the error. Can I take a look at the generated Db (frb api class)

**Comment by huang12zheng** [comment]
https://github.com/huang12zheng/flutter_rust_bridge_template/tree/reproduce_863
you can find object from `native/src/surreal.rs`
To be honest, I just saw Opaque today.
I probably don't understand the code generation properly
@rogurotus

**Comment by rogurotus** [comment]
flutter_rust_bridge/frb_codegen/src/generator/rust/mod.rs  line - 139

Yes, this is indeed a bug. related functions are generated for arguments, not for return type.

```
        lines += distinct_input_types (should be distinct_output_types)
            .iter()
            .map(|f| self.generate_related_funcs(f, ir_file))
            .collect();
```

until fixed, you can create an empty function:
```
pub fn touch(opauqe: Opaque<Surreal<Db>>) {}
```
