### ISSUE TITLE
cannot find type `MessagePort` in this scope

### ISSUE THREAD

**Issue by coolit** [fzyzcjy/flutter_rust_bridge#865]
### Describe the bug

Anybody knows how to fix this warning in vscode? Thanks.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
no idea how to use this, I just use just + flutter run
```

### Version of `flutter_rust_bridge_codegen`

^1.15.1

### Flutter info

it said: could not compile `native` due to previous error.

### Version of `ffigen`

^7.2.0

**Comment by fzyzcjy** [comment]
Please provide more context, thanks

**Comment by coolit** [comment]
@fzyzcjy  I have downloaded the new template, and changed some configs, not it is ok.
