### ISSUE TITLE
[Bug] hide seems to be reserved

### ISSUE THREAD

**Issue by alexthe2** [fzyzcjy/flutter_rust_bridge#874]
### Describe the bug

If a field has the name `hide` the bridge renames it to `hide1`, but not the codegen on the dart side.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
-
```

### Version of `flutter_rust_bridge_codegen`

1.51.0

**Comment by fzyzcjy** [comment]
Feel free to PR to fix it!
