### ISSUE TITLE
Allow Rust to call Dart functions

### ISSUE THREAD

**Issue by fzyzcjy** [fzyzcjy/flutter_rust_bridge#880]
@rogurotus IIRC you have mentioned that, your recent PRs allows Rust to call arbitrary Dart functions. Looking forward to that!

**Comment by czy-29** [comment]
I am very interested in this feature, is there any related pr or tracking issues that I can observe?

**Comment by fzyzcjy** [comment]
@czy-29 Not yet. @rogurotus mentioned this IIRC in the opaque type PR, but seems there is no update yet

**Comment by rogurotus** [comment]
In principle, such an opportunity now exists. something like this

Rust
```
pub fn call_dart_fn(ptr: usize, opaque: DartOpaque) -> SyncReturn<String> {
    let fun: fn(Dart_Handle) = unsafe{std::mem::transmute(ptr)};
    let handle = opaque.try_unwrap().unwrap().into_raw();
    let res = fun(handle);
    SyncReturn("TEST".to_owned())
}
```

Dart
```
void dart_fn(dynamic obj) {
  print(obj);
}

var ptr = Pointer.fromFunction<Void Function(Handle)>(dart_fn);
api.callDartFn(ptr: ptr.address, opaque: () => () => 'Magic');
```

Output
```
Closure: () => () => String
```

but ideally, we need to implement the system as for api.rs, that is, parse api.dart and register functions in rust.
I'm not ready to do it right now

**Comment by rogurotus** [comment]
we also have to be careful with the lifetime of Dart_Handle (the result of calling a dart function from rust can be cleaned up by the dart GC (see more Dart_PersistentHandle / Dart_Handle))

**Comment by rogurotus** [comment]
Especially considering that Dart functions take the usual Dart_Handle, and DartOpaque is Dart_PersistentHandle, this should also be taken into account

**Comment by fzyzcjy** [comment]
That looks great!
