### ISSUE TITLE
`SyncReturn` should be transparent

### ISSUE THREAD

**Issue by ngasull** [fzyzcjy/flutter_rust_bridge#881]
In many scenarios async return is overkill and create a lot of complexity:

* Non-primitive getters and setters
* Constructors
* Iterators
* Other simple/fast calls
* Use of libs that require single threaded execution because of their locking machanisms

Async can be unnecessarily painful, especially when working hand in hand with flutter build functions.

Moreover, this is an opportunity to simplify the code base significantly and facilitate maintainability.

**Describe the solution you'd like**
`SyncReturn` should be transparent and support anything that would be returned otherwise (probably `IntoDart`).

Is there a drawback or any reason why `SyncReturn` is serialized to bytes so far?

**Describe alternatives you've considered**
I tried working with current implementation, working around with sync pointers or async structs, but I eventually figured I'd make a better use of my energy working on the bridge directly, which I did.

[You can find here my current work on it](https://github.com/fzyzcjy/flutter_rust_bridge/pull/882)

If my suggestion is not acceptable for some reason (transparent `SyncReturn`), feel free to explain me why :)

**Additional context**
I'm so happy that such a project exists and that it is active, thank you ❤️ it will be a pleasure to help as well.

**Comment by fzyzcjy** [comment]
> In many scenarios async return is overkill and create a lot of complexity

Totally agree :)

> Is there a drawback or any reason why SyncReturn is serialized to bytes so far?

Because SyncReturn needs somehow a different mechanism than async return, so it *is* like this currently. However, surely, feel free to implement more complicated approaches, which should be great!

By the way, async is also quite useful in some scenarios: https://cjycode.com/flutter_rust_bridge/feature/async_dart.html

> I tried working with current implementation, working around with sync pointers or async structs, but I eventually figured I'd make a better use of my energy working on the bridge directly, which I did.
> I'm so happy that such a project exists and that it is active, thank you ❤️ it will be a pleasure to help as well.

You are welcome and looking forward to your PR!

> You can find here my current work on it: (link will be pasted after issue is created)

👀

**Comment by ngasull** [comment]
Added [the link to the PR](https://github.com/fzyzcjy/flutter_rust_bridge/pull/882) in the issue.

> By the way, async is also quite useful in some scenarios: https://cjycode.com/flutter_rust_bridge/feature/async_dart.html

Of course yes! I absolutely won't minimize your great work and how useful function calls as async task executions are!

>However, surely, feel free to implement more complicated approaches, which should be great!

Simple note about me: fighting against complexity is basically the story of my developer's life, so I hope you don't find my changes complex :)

And many thanks for your hospitality!

**Comment by fzyzcjy** [comment]
You are welcome! Cannot wait to review and merge your PR :)
