### ISSUE TITLE
[Bug] Android problem: libc++_shared.so not found [SOLVED]

### ISSUE THREAD

**Issue by kmueller** [fzyzcjy/flutter_rust_bridge#883]
### Describe the bug

I am using a Mac Book Air (ARM architecture). In the following I want to share my SOLUTION for a problem I was struggling with.

In my project, I'm trying to integrate an extensive Rust library on Android and make some function calls in my api.rs.

The 3rd party library can be cross-compiled, which is already a good thing. So I can incorporate functions from the library into my code without errors and the app launches with flutter run.

However, if I added a certain line of code in api.rs which was using a specific struct of the 3rd party lib, the following exception was thrown when executing the app. 

```
E/flutter (32120): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'librust.so': dlopen failed: library "libc++_shared.so" not found: needed by /data/app/~~IHSP2UVm41Zp_pFGk8AyYQ==/com.example.playground-he-dhEflhVP4jJ5YyaXI3Q==/lib/arm64/librust.so in namespace classloader-namespace
E/flutter (32120): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)

```
So I couldn't use my cross-compiled library (in my case librust.so) because the libc++_shared.so lib was not found.

When you Google you'll find https://developer.android.com/ndk/guides/cpp-support

> Note: libc++ is not a system library. If you use libc++_shared.so, it must be included in your app. If you're building your application with Gradle this is handled automatically.

Obviously that is not the case.

My solution - there are definitely better ones - is that I copied the libc++_shared.so ONCE into the project, as you can see in the following picture:
![Solution_Android](https://user-images.githubusercontent.com/811789/206696288-6714f6e4-3f8b-4a40-8430-2f58392b6c1b.png)

Additional info

macOS Ventura 13.0.1 
Android NDK 22.1.7171670
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Not necessary
```

**Comment by fzyzcjy** [comment]
Thanks for the documented solution!

**Comment by kmueller** [comment]
Thank YOU for Flutter Rust Bridge. It's awesome!

**Comment by fzyzcjy** [comment]
You are welcome! :)
