### ISSUE TITLE
How to integrate OpenCV + Rust + Flutter?

### ISSUE THREAD

**Issue by MertTanyur** [fzyzcjy/flutter_rust_bridge#884]
Sure. Indeed I have opencv + rust in my app in production, using exactly that crate.

_Originally posted by @fzyzcjy in https://github.com/fzyzcjy/flutter_rust_bridge/issues/399#issuecomment-1094032837_

**Comment by fzyzcjy** [comment]
?

**Comment by MertTanyur** [comment]
Hi, @fzyzcjy  could you plesae give some details about build options, enironment variables etc.
I have been thinking to use exactly the same stack and read your issues on also rust-opencv repo.

**Comment by fzyzcjy** [comment]
Well my configuration integrates a lot with my own python-based script infra... So IMHO it will not work for you out of the box. But I can post my configs here: (wait a minute)

**Comment by fzyzcjy** [comment]
cargo.toml

```
[dependencies]
opencv = ...
```

android build script

```
def _query_needed_android_env():
    opencv_base_dir = flutter_wrapper_base_dir / 'android/OpenCV-android-sdk'
    return {
        'DYLD_FALLBACK_LIBRARY_PATH': query_dyld_fallback_library_path(),
        'OPENCV_LINK_PATHS': ','.join([
            str(val)
            for android_abi in _all_android_abi_arr
            for val in (
                opencv_base_dir / 'sdk/native/staticlibs' / android_abi,
                opencv_base_dir / 'sdk/native/3rdparty/libs' / android_abi,
            )
        ]),
        'OPENCV_LINK_LIBS': "opencv_imgcodecs,opencv_imgproc,opencv_core,tbb,cpufeatures,ittnotify,tegra_hal,IlmImf,liblibpng,liblibtiff,liblibwebp,liblibopenjp2,liblibjpeg-turbo,z",
        'OPENCV_INCLUDE_PATHS': str(opencv_base_dir / "sdk/native/jni/include/"),
    }

def query_dyld_fallback_library_path():
    # https://github.com/twistedfall/opencv-rust#troubleshooting
    raw = run_command("xcode-select --print-path | tr -d '\n'", return_stdout=True)
    ans = raw + '/Toolchains/XcodeDefault.xctoolchain/usr/lib/'
    logger_main.message(f'query_dyld_fallback_library_path: {ans}')
    return ans

```

and set them as env variable.

ios build script:

```
def ios_prepare_opencv():
    # ref https://github.com/twistedfall/opencv-rust/issues/270
    opencv_framework_parent = flutter_wrapper_base_dir / 'ios'
    opencv_framework_name = "opencv2.framework"

    temp_header_dir = rust_base_dir / "target/temp_ios_headers"
    shutil.rmtree(temp_header_dir, ignore_errors=True)
    shutil.copytree(opencv_framework_parent / opencv_framework_name / 'Headers', temp_header_dir / 'opencv2')

    # ref https://github.com/twistedfall/opencv-rust/issues/270#issuecomment-930264481
    ocl_hpp_path = temp_header_dir / 'opencv2/core/ocl.hpp'
    ocl_hpp_content = ocl_hpp_path.read_text() \
        .replace('int versionMajor() const;', '// NOTE XXX hack remove: int versionMajor() const;') \
        .replace('int versionMinor() const;', '// NOTE XXX hack remove: int versionMinor() const;')
    ocl_hpp_path.write_text(ocl_hpp_content)

    os.environ['OPENCV_LINK_PATHS'] = str(opencv_framework_parent)
    os.environ['OPENCV_LINK_LIBS'] = opencv_framework_name
    os.environ['OPENCV_INCLUDE_PATHS'] = str(temp_header_dir)

def ios_or_macos_prepare_opencv():
    os.environ['DYLD_FALLBACK_LIBRARY_PATH'] = query_dyld_fallback_library_path()

```

**Comment by MertTanyur** [comment]
Thank you so much, please let me work on this and repost my results.

**Comment by MertTanyur** [comment]
Thank you so much, please let me work on this and repost my results.

**Comment by MertTanyur** [comment]
Hi with the help of your  guidance, I have tried  different options for passing environment variables. Directly configuring config.toml was the easiest. I'm wonder if it's a good practice for cross platform compiling. 



After configuring 

config.toml in flutter_wrapper/$rust_directory/.cargo/config.toml as

**Comment by MertTanyur** [comment]
Could you give some tips about writing a startup script for ios ? 
Should I create a custom CI ? Or adjusting AppDelegate.swift will do the trick ? 
Passing environment variables in platforms natively is a better practice than configuring config.toml I guess for cross-platform apps.

https://github.com/twistedfall/opencv-rust/issues/270#issuecomment-930677051 ?

**Comment by fzyzcjy** [comment]
The error looks quite general, so maybe search that in google

As for scripts, I later migrate all my internal scripts using my python scripting infra. The link you pasted shows my old configuration (based on ruby)

**Comment by MertTanyur** [comment]
With the help of frb static binding generation,
after taking the warnings like that (6000 lines)

`std::__1::vector<cv::Mat, std::__1::allocator<cv::Mat> > const&)", referenced from:
          _cv_line_descriptor_BinaryDescriptorMatcher_match_const_MatR_vectorLDMatchGR_const_vectorLMatGR in librust_static.a(line_descriptor.o)
      "cv::line_descriptor::BinaryDescriptorMatcher::train()", referenced from:
          _cv_line_descriptor_BinaryDescriptorMatcher_train in librust_static.a(line_descriptor.o)`
          
          
    Build failed just because of  a couple undefined symbols for ios64_86 architectures 
   `Error (Xcode): Undefined symbol: cv::imreadmulti(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<cv::Mat, std::__1::allocator<cv::Mat> >&, int)

Error (Xcode): Undefined symbol: cv::imreadmulti(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<cv::Mat, std::__1::allocator<cv::Mat> >&, int, int, int)

Error (Xcode): Undefined symbol: cv::large_kinfu::LargeKinfu::create(cv::Ptr<cv::large_kinfu::Params> const&)
Error (Xcode): Undefined symbol: cv::large_kinfu::Params::coarseParams()

Error (Xcode): Undefined symbol: cv::large_kinfu::Params::defaultParams()
Error (Xcode): Undefined symbol: cv::large_kinfu::Params::hashTSDFParams(bool)
Error (Xcode): Undefined symbol: cv::mixChannels(cv::_InputArray const&, cv::_InputOutputArray const&, int const*, unsigned long)

Error (Xcode): Undefined symbol: cv::mixChannels(cv::_InputArray const&, cv::_InputOutputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)

Error (Xcode): Undefined symbol: cv::namedWindow(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)

Error (Xcode): Undefined symbol: cv::polarToCart(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, bool)

Error (Xcode): Undefined symbol: cv::randShuffle(cv::_InputOutputArray const&, double, cv::RNG*)

Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternGenerator::getPattern()
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternGenerator::generatePattern()

Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternGenerator::RandomPatternGenerator(int, int)
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::loadPattern(cv::Mat const&)
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::loadPattern(cv::Mat const&, std::__1::vector<cv::KeyPoint, std::__1::allocator<cv::KeyPoint> > const&, cv::Mat const&)
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::getImagePoints()
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::getObjectPoints()
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::computeObjectImagePoints(std::__1::vector<cv::Mat, std::__1::allocator<cv::Mat> >)
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
Exited
`

**Comment by MertTanyur** [comment]
### With the help of frb static binding generation,after taking the warnings like that (6000 lines)

`std::__1::vector<cv::Mat, std::__1::allocator<cv::Mat> > const&)", referenced from: _cv_line_descriptor_BinaryDescriptorMatcher_match_const_MatR_vectorLDMatchGR_const_vectorLMatGR in librust_static.a(line_descriptor.o) "cv::line_descriptor::BinaryDescriptorMatcher::train()", referenced from: _cv_line_descriptor_BinaryDescriptorMatcher_train in librust_static.a(line_descriptor.o)`

### Build failed just because of  the undefined symbols for ios64_86 architectures 

```
Error (Xcode): Undefined symbol: cv::imreadmulti(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::vector<cv::Mat, std::__1::allocatorcv::Mat >&, int)

Error (Xcode): Undefined symbol: cv::imreadmulti(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, std::__1::vector<cv::Mat, std::__1::allocatorcv::Mat >&, int, int, int)

Error (Xcode): Undefined symbol: cv::large_kinfu::LargeKinfu::create(cv::Ptrcv::large_kinfu::Params const&)
Error (Xcode): Undefined symbol: cv::large_kinfu::Params::coarseParams()

Error (Xcode): Undefined symbol: cv::large_kinfu::Params::defaultParams()
Error (Xcode): Undefined symbol: cv::large_kinfu::Params::hashTSDFParams(bool)
Error (Xcode): Undefined symbol: cv::mixChannels(cv::_InputArray const&, cv::_InputOutputArray const&, int const*, unsigned long)

Error (Xcode): Undefined symbol: cv::mixChannels(cv::_InputArray const&, cv::_InputOutputArray const&, std::__1::vector<int, std::__1::allocator > const&)

Error (Xcode): Undefined symbol: cv::namedWindow(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int)

Error (Xcode): Undefined symbol: cv::polarToCart(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, bool)

Error (Xcode): Undefined symbol: cv::randShuffle(cv::_InputOutputArray const&, double, cv::RNG*)

Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternGenerator::getPattern()
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternGenerator::generatePattern()

Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternGenerator::RandomPatternGenerator(int, int)
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::loadPattern(cv::Mat const&)
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::loadPattern(cv::Mat const&, std::__1::vector<cv::KeyPoint, std::__1::allocatorcv::KeyPoint > const&, cv::Mat const&)
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::getImagePoints()
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::getObjectPoints()
Error (Xcode): Undefined symbol: cv::randpattern::RandomPatternCornerFinder::computeObjectImagePoints(std::__1::vector<cv::Mat, std::__1::allocatorcv::Mat >)
Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
Exited
```

**Comment by fzyzcjy** [comment]
Btw it looks more like a opencv-rust problem now

**Comment by MertTanyur** [comment]
It doesn't seem likea FRB library issue  directly , it's just related with the process, I thought. Thanks for your view

**Comment by dbsxdbsx** [comment]
> cargo.toml
> 
> ```
> [dependencies]
> opencv = ...
> ```
> 
> android build script
> 
> ```
> def _query_needed_android_env():
>     opencv_base_dir = flutter_wrapper_base_dir / 'android/OpenCV-android-sdk'
>     return {
>         'DYLD_FALLBACK_LIBRARY_PATH': query_dyld_fallback_library_path(),
>         'OPENCV_LINK_PATHS': ','.join([
>             str(val)
>             for android_abi in _all_android_abi_arr
>             for val in (
>                 opencv_base_dir / 'sdk/native/staticlibs' / android_abi,
>                 opencv_base_dir / 'sdk/native/3rdparty/libs' / android_abi,
>             )
>         ]),
>         'OPENCV_LINK_LIBS': "opencv_imgcodecs,opencv_imgproc,opencv_core,tbb,cpufeatures,ittnotify,tegra_hal,IlmImf,liblibpng,liblibtiff,liblibwebp,liblibopenjp2,liblibjpeg-turbo,z",
>         'OPENCV_INCLUDE_PATHS': str(opencv_base_dir / "sdk/native/jni/include/"),
>     }
> 
> def query_dyld_fallback_library_path():
>     # https://github.com/twistedfall/opencv-rust#troubleshooting
>     raw = run_command("xcode-select --print-path | tr -d '\n'", return_stdout=True)
>     ans = raw + '/Toolchains/XcodeDefault.xctoolchain/usr/lib/'
>     logger_main.message(f'query_dyld_fallback_library_path: {ans}')
>     return ans
> ```
> 
> and set them as env variable.
> 
> ios build script:
> 
> ```
> def ios_prepare_opencv():
>     # ref https://github.com/twistedfall/opencv-rust/issues/270
>     opencv_framework_parent = flutter_wrapper_base_dir / 'ios'
>     opencv_framework_name = "opencv2.framework"
> 
>     temp_header_dir = rust_base_dir / "target/temp_ios_headers"
>     shutil.rmtree(temp_header_dir, ignore_errors=True)
>     shutil.copytree(opencv_framework_parent / opencv_framework_name / 'Headers', temp_header_dir / 'opencv2')
> 
>     # ref https://github.com/twistedfall/opencv-rust/issues/270#issuecomment-930264481
>     ocl_hpp_path = temp_header_dir / 'opencv2/core/ocl.hpp'
>     ocl_hpp_content = ocl_hpp_path.read_text() \
>         .replace('int versionMajor() const;', '// NOTE XXX hack remove: int versionMajor() const;') \
>         .replace('int versionMinor() const;', '// NOTE XXX hack remove: int versionMinor() const;')
>     ocl_hpp_path.write_text(ocl_hpp_content)
> 
>     os.environ['OPENCV_LINK_PATHS'] = str(opencv_framework_parent)
>     os.environ['OPENCV_LINK_LIBS'] = opencv_framework_name
>     os.environ['OPENCV_INCLUDE_PATHS'] = str(temp_header_dir)
> 
> def ios_or_macos_prepare_opencv():
>     os.environ['DYLD_FALLBACK_LIBRARY_PATH'] = query_dyld_fallback_library_path()
> ```

@fzyzcjy, regarding the cross-compilation, there are things I am not clear about. Say, I am coding on windows, and the final app is for both windows and android.   Also, one of the crates used is depending on OpenCV.  When debugging and testing for windows, it is for sure that the lib of OpenCV should be downloaded and added to the windows environment first.  

But what about Android (the cross-platform)?   

Q1. when testing app performance for android on windows, I could launch the virtual Android emulator on windows, but how to inject the OpenCV lib into that virtual environment?
Q2. when deploying, how to put the OpenCV lib with the final APK file?---For this, the python script you referring to seems to be the solution, but I have no idea when to run the script.

**Comment by fzyzcjy** [comment]
> Q1. when testing app performance for android on windows, I could launch the virtual Android emulator on windows, but how to inject the OpenCV lib into that virtual environment?

Just do the normal things that you will do to develop an android app

> Q2. when deploying, how to put the OpenCV lib(for android) with the final APK file?---For this, the python script you referring to seems to be the solution, but I have no idea when to run the script.

The script compiles the final .so file *with opencv included*

**Comment by dbsxdbsx** [comment]
@fzyzcjy, if there are several apps doing this way(say there are 3 independant android apps which relies on OpenCV), does it mean there would 3 copies of opencv .so in android?

**Comment by fzyzcjy** [comment]
No, opencv can be .a and compiled into your so

**Comment by MertTanyur** [comment]
Hi again, I was building for android, I guess flutter-rust-bridge part has no problem. 

I wonder about how can I link lib$crate.so files and  opencv framework in flutter-android ?? 

Thanks

```
note: clang-14: warning: argument unused during compilation: '-F/usr/local/lib' [-Wunused-command-line-argument]
          ld: error: unable to find library -lopencv_gapi.4.6.0
          ld: error: unable to find library -lopencv_stitching.4.6.0
          ld: error: unable to find library -lopencv_alphamat.4.6.0
          ld: error: unable to find library -lopencv_aruco.4.6.0
          ld: error: unable to find library -lopencv_barcode.4.6.0
          ld: error: unable to find library -lopencv_bgsegm.4.6.0
          ld: error: unable to find library -lopencv_bioinspired.4.6.0
          ld: error: unable to find library -lopencv_ccalib.4.6.0
          ld: error: unable to find library -lopencv_dnn_objdetect.4.6.0
          ld: error: unable to find library -lopencv_dnn_superres.4.6.0
          ld: error: unable to find library -lopencv_dpm.4.6.0
          ld: error: unable to find library -lopencv_face.4.6.0
          ld: error: unable to find library -lopencv_freetype.4.6.0
          ld: error: unable to find library -lopencv_fuzzy.4.6.0
          ld: error: unable to find library -lopencv_hfs.4.6.0
          ld: error: unable to find library -lopencv_img_hash.4.6.0
          ld: error: unable to find library -lopencv_intensity_transform.4.6.0
          ld: error: unable to find library -lopencv_line_descriptor.4.6.0
          ld: error: unable to find library -lopencv_mcc.4.6.0
          ld: error: unable to find library -lopencv_quality.4.6.0
          ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
          clang-14: error: linker command failed with exit code 1 (use -v to see invocation)


```
