### ISSUE TITLE
Multiple files binding on macOS

### ISSUE THREAD

**Issue by rhobro** [fzyzcjy/flutter_rust_bridge#909]
### Describe the bug

I've been following the guide to binding multiple files from Rust to dart. As part of this, my binding gen taskrunner looks like this:
```
gen:
    flutter_rust_bridge_codegen \
        --rust-input "native/src/api_discover.rs" "native/src/api_extratest.rs" \
        --dart-output "lib/native/bridge_generated_api_discover.dart" "lib/native/bridge_generated_api_extratest.dart" \
        --rust-output "native/src/generated_api_discover.rs" "native/src/generated_api_extratest.rs" \
        --c-output "macos/Runner/generated_api_discover.h" "macos/Runner/generated_api_extratest.h" \
        --class-name ApiDiscover ApiExtratest
```

However when I run it, it gives the following error:
```
error: Found argument 'macos/Runner/generated_api_extratest.h' which wasn't expected, or isn't valid in this context
```

When I keep only the first one and set the output to `macos/Runner/bridge_generated.h`, it only seems to create the bindings for the first Rust file.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
in previous ^
```

### OS

macOS

### Version of `flutter_rust_bridge_codegen`

1.55

### Version of `clang++`

14.0.0

### Version of `ffigen`

7.2.4

**Comment by fzyzcjy** [comment]
Is this related: https://github.com/fzyzcjy/flutter_rust_bridge/pull/862

**Comment by rhobro** [comment]
Hi there, I think so. But just adding one header file seems to only include methods from the first input file but not the second.

**Comment by fzyzcjy** [comment]
Well I mean whether that PR solves this issue?

**Comment by rhobro** [comment]
Yes I think this is tackling my problem exactly. When can it be merged by?

**Comment by fzyzcjy** [comment]
current status: for @dbsxdbsx's review :)

**Comment by rhobro** [comment]
Right now, methods in the first rust file seem to be ok but when calling ones from the second one, stuff like this happens:
```
Failed to lookup symbol 'wire_discover': dlsym(RTLD_DEFAULT, wire_discover): symbol not found
```

**Comment by rhobro** [comment]
Just to confirm, for each file are we required to take the dylib and create a separate impl on it?

**Comment by fzyzcjy** [comment]
Would be great to ask in the PR since this part is implemented by them :)

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/pull/937 is merged

**Comment by dbsxdbsx** [comment]
@rhobro , now since [frb 1.59](https://github.com/fzyzcjy/flutter_rust_bridge/releases/tag/v1.59.0), whenever you want to generate the same c-output file in more than two places, please use flag `extra-c-output-path` (or `e` for short)  to define extra path without the c header file name. The example is refined [here](https://cjycode.com/flutter_rust_bridge/integrate/ios_gen.html). 

And the number of fields used in flag `c-output`(or `c` for short) should be consistent with that of `rust-input` if the flag is not omitted.

Hopefully, this release could alleviate or solve your issue.

**Comment by dbsxdbsx** [comment]
@rhobro, just a review, is there any issue with multi-block within macOS or ISO now? Could you please test with the latest version v1.65.0?

**Comment by rhobro** [comment]
Hi there @dbsxdbsx ,

Apologies that I didn't respond to your previous post, I'm not sure why but i didn't receive a notification for it.

I can't wait to test out v1.65. I should be able to do so at the end of the week, since I have exams at the moment. I've put a reminder to do so and will respond on this issue when I do.

Thank you again.

**Comment by rhobro** [comment]
Hi there,

Unfortunately, exam season has started for me and so I will not be able to test this for a while. Apologies for the inconvenience.

Thanks
