### ISSUE TITLE
Better error message if input files to codegen don't exist

### ISSUE THREAD

**Issue by w1th0utnam3** [fzyzcjy/flutter_rust_bridge#911]
**Is your feature request related to a problem? Please describe.**
Specifying an input file to `flutter_rust_bridge_codegen` that does not exist results in the following output:
```
flutter_rust_bridge_codegen --rust-input rust/api.rs --dart-output lib/bridge_generated.dart
thread 'main' panicked at 'panic with file: [...]/flutter_rust_bridge/frb_example/with_flutter/rust/api.rs', [...]/.cargo/registry/src/github.com-1ecc6299db9ec823/flutter_rust_bridge_codegen-1.55.0/src/config.rs:404:33
```
The output is not very helpful for quickly determining the cause of the panic. Specifying a wrong path is a very common mistake when using CLI tools so IMO it should show a better error message.

**Describe the solution you'd like**
It would be nice if the CLI would e.g. first check if the input file(s) exist and if not, print a respective error message.

**Comment by fzyzcjy** [comment]
Looks reasonable, feel free to PR!
