### ISSUE TITLE
More validation of input paths to codegen

### ISSUE THREAD

**Issue by w1th0utnam3** [fzyzcjy/flutter_rust_bridge#915]
**Is your feature request related to a problem? Please describe.**
Running the codegen from a wrong directory or with invalid paths sometimes leads to confusing error messages. For example invoking codegen from the parent folder of the flutter example with an invalid path for the input file results in:
```
flutter_rust_bridge/frb_example$ flutter_rust_bridge_codegen --rust-input rust/src/api.rs --dart-output=lib/bridge_generated.dart
thread 'main' panicked at 'fail to guess class_name, please specify it manually in command line arguments', frb_codegen/src/config.rs:254:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
which is not very helpful for new users.

**Describe the solution you'd like**
The CLI should print an error message like "rust input file "..." does not exist" to make it clearer to the user that something is wrong with the paths.

I will submit a PR for this that adds checks to the [argument parsing](https://github.com/fzyzcjy/flutter_rust_bridge/blob/f5f756947a7601e0054f16edb391fe9d42c10eb5/frb_codegen/src/config.rs#L104) that input files and other paths at least exist.

**Describe alternatives you've considered**
Alternatively, the entire configuration of the paths / working directories could be reworked. Ideally one would first start by clarifying & documenting which folders are supported as working directories, which input/output paths can be relative to what, which paths are needed and how they are inferred if not provided. From this one could rewrite the parsing of the arguments to clearly point out in an error case "this was given as input -> this was inferred -> this results in an invalid configuration". However I don't have the time to do this and I'm not sure how hard it is to do it properly when considering the external tools/libraries that are used by the codegen (as they have maybe their own assumptions and ways of treating paths).

**Comment by fzyzcjy** [comment]
Totally agree! This subpart looks a bit messy currently, and looking forward to your improvement/refactor PR!
