### ISSUE TITLE
Lint issue after running “just  precommit”

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#925]
After running `just precommit` after little code modification, the CI test on GitHub post 2 issues [here](https://github.com/dbsxdbsx/flutter_rust_bridge/actions/runs/3774922450/jobs/6417282128):

I wonder the one with the IOS, WHAT DOES THIS MEAN in step "start simulator":
```
Run # the extra "(" is to avoid matching things like "iPhone 12 Pro Max Simulator (15.2) + Apple Watch Series 5 - 44mm (8.0)"
UDID=
/Users/runner/work/_temp/d5[7](https://github.com/dbsxdbsx/flutter_rust_bridge/actions/runs/3774922450/jobs/6417282735#step:3:8)90[8](https://github.com/dbsxdbsx/flutter_rust_bridge/actions/runs/3774922450/jobs/6417282735#step:3:9)d4-def6-430b-ada4-a4cf27[9](https://github.com/dbsxdbsx/flutter_rust_bridge/actions/runs/3774922450/jobs/6417282735#step:3:10)bc309.sh: line 4: UDID: No Simulator with this name found
Error: Process completed with exit code 1.
```

**Comment by dbsxdbsx** [comment]
Strange, this issue doesn't happen in [pr](https://github.com/fzyzcjy/flutter_rust_bridge/pull/926).

**Comment by fzyzcjy** [comment]
I guess GitHub actions may upgrade its environment somehow, and sometimes an action is executed via new env and sometimes by old env?
