### ISSUE TITLE
support nest type alias with topology sort

### ISSUE THREAD

**Issue by huang12zheng** [fzyzcjy/flutter_rust_bridge#927]
**Is your feature request related to a problem? Please describe.**
```rs
pub type UserId = OwnerId;
pub type ObjectId = u64;
```
**Describe the solution you'd like**
1. Create a type_alias diagram
2. Topological sorting
3. Gets a new mapping type_alias

**Comment by fzyzcjy** [comment]
LGTM, looking forward to PR :)
