### ISSUE TITLE
Mutable methods

### ISSUE THREAD

**Issue by rhobro** [fzyzcjy/flutter_rust_bridge#933]
Hi there,

I created a struct with a method that needs to alter its inner state. However, when generating a binding, it says that mutable methods are unsupported because of safety reasons. Why is this? How can I get around this?

Thanks

**Comment by fzyzcjy** [comment]
Yes. indeed if a method is mutable, it is not changing the dart object, but a copy of it.

Maybe use `opaque` types?

**Comment by rhobro** [comment]
So if I use opaque types, I can use mutable methods?

**Comment by fzyzcjy** [comment]
Yes, just use Mutex etc

**Comment by rhobro** [comment]
Sorry I don't quite understand. Just to confirm, here's what I'm trying to do.

I've made a struct in Rust which I want to be available on the Dart side. I've implemented a 'pub fn (&mut self, ...)' on this struct which I want to call from the Dart side.When I try generate bindings, it throws an error saying it's not safe.

Will this work if the constructor returned RustOpaque<Type> instead of Type?

How would a mutex be involved?

**Comment by fzyzcjy** [comment]
What about having a look at: https://cjycode.com/flutter_rust_bridge/contributing/rust_opaque_type_safety.html

As well as https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/src/api.rs

**Comment by rhobro** [comment]
Apologies but I can't find any mention of mutable methods in either of the links? They all seem to take these objects as parameters.

**Comment by fzyzcjy** [comment]
Yes it does not mention, but idea is simple:

```
struct ArbitraryData { ... }

pub fn f(x: RustOpaque<Mutex<ArbitraryData>) {
  use x mutably (since it is inside a mutex)
}
```

That is not *method*s, but except for that, it is mutable.

If you want mutable methods, feel free to PR!

**Comment by rhobro** [comment]
Ok. I've tried it with an RwLock instead of a Mutex. But compiling the generated binding code says something of the following:
```
error[E0412]: cannot find type `RwLock` in this scope
  --> src/bridge_generated.io.rs:60:37
   |
60 |     fn wire2api(self) -> RustOpaque<RwLock<RawSpeaker>> {
   |                                     ^^^^^^ not found in this scope
```
That it can't find RwLock in scope.

Have I configured it incorrectly?

**Comment by fzyzcjy** [comment]
rwlock is the same. as for not found in scope, maybe should import it. see https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/src/api.rs for example

**Comment by rhobro** [comment]
Ahhh, I was previously just using it. Now i've pub used it and it works.

**Comment by rhobro** [comment]
When I tried this in debug mode, it worked perfectly. As soon as I tried it in release mode, it threw the following error and the rest of the application failed to open:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'store_dart_post_cobject': dlsym(RTLD_DEFAULT, store_dart_post_cobject): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34)
#1      NativeWire._store_dart_post_cobjectPtr (package:conductor/native/bridge_generated.dart:294)
#2      NativeWire._store_dart_post_cobject (package:conductor/native/bridge_generated.dart)
#3      NativeWire.store_dart_post_cobject (package:conductor/native/bridge_generated.dart)
#4      StoreDartPostCObjectExt.storeDartPostCObject (package:flutter_rust_bridge/src/ffi/io.dart:18)
#5      FlutterRustBridgeBase._setUpRustToDartComm (package:flutter_rust_bridge/src/basic.dart:60)
#6      new FlutterRustBridgeBase (package:flutter_rust_bridge/src/basic.dart:28)
#7      new NativePlatform (package:conductor/native/bridge_generated.dart:224)
#8      new NativeImpl (package:conductor/native/bridge_generated.dart:71)
#9      api (package:conductor/native/native.dart:11)
#10     Speaker.create (package:conductor/native/speaker.dart)
#11     _DiscoveryState.initState.<anonymous closure> (package:conductor/views/discovery.dart:35)
#12     new Future.delayed.<anonymous closure> (dart:async/future.dart:424)
#13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

For some reason the bridge is working for debug but not for release.

**Comment by rhobro** [comment]
Ahh, I changed it from `dummy_method_to_enforce_bundling()` to `print(dummy_method_to_enforce_bundling())`
