### ISSUE TITLE
 Support `SyncReturn<Struct>, SyncReturn<Enum>`

### ISSUE THREAD

**Issue by rogurotus** [fzyzcjy/flutter_rust_bridge#935]
`SyncReturn` has been recently redesigned (thanks @ngasull for the great implementation)
judging by the implementation, it became possible to use SyncReturn(Struct) SyncReturn(Enum), but for some reason I do not understand, this is restricted.

The restriction is imposed here.
frb_rust/src/lib.rs
```
/// Use this struct in return type of your function, in order to tell the code generator
/// the function should return synchronously. Otherwise, it is by default asynchronously.
pub struct SyncReturn<T: IntoDart>(pub T);
```

although frb generates `IntoDart` and if you do pub struct `SyncReturn<T>(pub T);`
in SyncReturn it will be possible to use structure

**Comment by fzyzcjy** [comment]
IMHO it should be possible to use struct/enum in sync return as well. What error does it generate when doing so?

**Comment by rogurotus** [comment]
In general, I understood
this works when the implementation is already there, but if you are generating for the first time then the error is caught before the code is generated


error like this
```
pub struct SyncReturn<T: IntoDart>(pub T);
     |                          ^^^^^^^^ required by this bound in `flutter_rust_bridge::SyncReturn`
```

In theory, we can remove the restriction from struct SyncReturn since there is already an IntoDart restriction in the generated code

**Comment by fzyzcjy** [comment]
Feel free to PR (and let's see how CI says)
