### ISSUE TITLE
[Bug] just gen generated using old flutter_rust_bridge version

### ISSUE THREAD

**Issue by kingfisherphuoc** [fzyzcjy/flutter_rust_bridge#941]
### Describe the bug

I used to use `flutter_rust_bridge` version 1.49.0. Now I want to update it to the version `flutter_rust_bridge: ^1.59.0`. After upgrading with clean && pub get again, it always used version 1.49.0.
Here my step:
1. clone the template repo
2. it could build an run normally
3. `pub clean && pub get` and `just clean && just gen`
4. it gave me those files:
```
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.49.0.
```
<img width="1474" alt="Screenshot 2022-12-30 at 12 14 31" src="https://user-images.githubusercontent.com/962484/210037046-f0a5f573-7ae7-413c-b0b3-f96bd0954c17.png">

Any suggestion?

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
no issue with code gen
```

**Comment by fzyzcjy** [comment]
try to update versions in cargo.toml

**Comment by kingfisherphuoc** [comment]
I did try to update cargo as well, but it's no use. 
<img width="1349" alt="Screenshot 2022-12-30 at 13 44 44" src="https://user-images.githubusercontent.com/962484/210042340-93af4b52-65f3-49b4-b920-31a354cd1bd2.png">
<img width="1370" alt="Screenshot 2022-12-30 at 13 44 32" src="https://user-images.githubusercontent.com/962484/210042329-a7dae938-a019-481d-8efe-e807217d22de.png">

**Comment by fzyzcjy** [comment]
maybe your (globally installed) flutter_rust_bridge_codegen binary is not updated?

**Comment by kingfisherphuoc** [comment]
thanks. It did the trick. However, I got another error when I run `just gen` command:
```
(base) kingfisher-phuoc@Doans-MacBook-Pro flutter_rust_bridge_template % just gen
flutter pub get
Running "flutter pub get" in flutter_rust_bridge_template...      1,360ms
flutter_rust_bridge_codegen --rust-input native/src/api.rs --dart-output lib/bridge_generated.dart --c-output ios/Runner/bridge_generated.h --c-output macos/Runner/bridge_generated.h --dart-decl-output lib/bridge_definitions.dart
error: --c-output's inputs should match --rust-input's length
```
Do you have any idea?

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/pull/937

**Comment by guchengxi1994** [comment]
> thanks. It did the trick. However, I got another error when I run `just gen` command:
> 
> ```
> (base) kingfisher-phuoc@Doans-MacBook-Pro flutter_rust_bridge_template % just gen
> flutter pub get
> Running "flutter pub get" in flutter_rust_bridge_template...      1,360ms
> flutter_rust_bridge_codegen --rust-input native/src/api.rs --dart-output lib/bridge_generated.dart --c-output ios/Runner/bridge_generated.h --c-output macos/Runner/bridge_generated.h --dart-decl-output lib/bridge_definitions.dart
> error: --c-output's inputs should match --rust-input's length
> ```
> 
> Do you have any idea?

same issue, could someone help?

**Comment by fzyzcjy** [comment]
does #937 work?

**Comment by guchengxi1994** [comment]
@fzyzcjy I was using 1.61.1, but every time using `cargo check` or `flutter build -d windows` , always got this.
![image](https://user-images.githubusercontent.com/33513462/213898171-e381c5b3-95e6-46f9-a60c-c953ef937d40.png)

1.58.0,1.58.2 are good

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/pull/937

**Comment by guchengxi1994** [comment]
@kingfisherphuoc I am only using frb on windows and   a simple solution is modify build.rs script like this.
![image](https://user-images.githubusercontent.com/33513462/213901289-29dd4fac-b3c8-4c32-ac47-780d2b9d8017.png)

**Comment by fzyzcjy** [comment]
Could you please provide a full bug report? And would be great to show text instead of screenshots in order for future readers to search it.

**Comment by sglim** [comment]
I found the solution.

The script in this [documentation](https://cjycode.com/flutter_rust_bridge/library/dart_only.html) contains a wrong build.rs script for the recent version of flutter_rust_bridge e.g., 1.62.1.

So I changed a code like this.

```rust
use lib_flutter_rust_bridge_codegen::{
    config_parse, frb_codegen, get_symbols_if_no_duplicates, RawOpts,
};

const RUST_INPUT: &str = "src/api.rs";
const DART_OUTPUT: &str = "../lib/src/bridge_generated.dart";

const IOS_C_OUTPUT: &str = "../../flutter_native_player/ios/Classes/frb.h";
const MACOS_C_OUTPUT_DIR: &str = "../../flutter_native_player/macos/Classes";

fn main() {
    // Tell Cargo that if the input Rust code changes, rerun this build script
    println!("cargo:rerun-if-changed={}", RUST_INPUT);

    // Options for frb_codegen
    let raw_opts = RawOpts {
        rust_input: vec![RUST_INPUT.to_string()],
        dart_output: vec![DART_OUTPUT.to_string()],
        c_output: Some(vec![IOS_C_OUTPUT.to_string()]),
        extra_c_output_path: Some(vec![MACOS_C_OUTPUT_DIR.to_string()]),
        inline_rust: true,
        wasm: true,
        ..Default::default()
    };

    // Generate Rust & Dart ffi bridges
    let configs = config_parse(raw_opts);
    let all_symbols = get_symbols_if_no_duplicates(&configs).unwrap();
    for config in configs.iter() {
        frb_codegen(config, &all_symbols).unwrap();
    }

    // Format the generated Dart code
    _ = std::process::Command::new("flutter")
        .arg("format")
        .arg("..")
        .spawn();
}
```

Main part is to use `extra_c_output_path` in the options.
```rust
const MACOS_C_OUTPUT_DIR: &str = "../../flutter_native_player/macos/Classes";
```

I think you can apply this to windows as well. @guchengxi1994

**Comment by fzyzcjy** [comment]
cc @GregoryConrad who created that tutorial - shall we somehow change the doc into a repository like flutter_rust_bridge_template or a brick? And even add into CI "the template should run well". Then we will never face such problems

**Comment by kingfisherphuoc** [comment]
> @fzyzcjy I was using 1.61.1, but every time using `cargo check` or `flutter build -d windows` , always got this. ![image](https://user-images.githubusercontent.com/33513462/213898171-e381c5b3-95e6-46f9-a60c-c953ef937d40.png)
> 
> 1.58.0,1.58.2 are good

Well, you can try this (modify the justfile):

```
gen:
    flutter pub get
    flutter_rust_bridge_codegen \
        -r native/src/api.rs \
        -d lib/bridge_generated.dart \
        -c ios/Runner/bridge_generated.h \
        -e macos/Runner/
```

**Comment by GregoryConrad** [comment]
I wasn't even aware there was an `extra_c_output_path`; thanks for bringing that up. I changed my own project to use `std::fs::copy`. Good to see there is a better solution.

I can PR to fix the docs for the time being since this isn't the first time someone ran into this issue since the docs were written.

> shall we somehow change the doc into a repository like flutter_rust_bridge_template or a brick? And even add into CI "the template should run well". Then we will never face such problems

That would be a really good idea, but I don't have the time to do that right now. I think a mason brick would be the proper solution since the library names are variables and it would greatly assist setup. Also, it'd be good to run custom scripts to do the setup which I think only mason bricks can do.

I also almost would want to wait until Native Assets are supported before working on a template. Most people would not need a monorepo & flutter wrapper then; just a dart-only package. Plus, a lot specified in the guide mentions and assumes a very particular workflow in order for everything to work (including using GitHub w/ GitHub releases), which I don't want to force on others with a template. The docs aren't perfect (in part because of how complex it is to setup Rust with FFI in Flutter today), but at least it can talk about what is going on so people can twist it in their own way more easily when setting it up.

**Comment by GregoryConrad** [comment]
PR for docs in #1050

**Comment by fzyzcjy** [comment]
Totally agree!

> wait until Native Assets

For future readers: https://github.com/dart-lang/sdk/issues/50565
