### ISSUE TITLE
Specify default values on the Dart caller

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#948]
**Is your feature request related to a problem? Please describe.**

Sometimes it is preferable for default values of flags to be written out on the Dart side:

```dart
void foo({bool makeIceCream = true});
```

If this is the case, the Rust binding code can skip using `Option<bool>`:

```rust
fn foo(make_ice_cream: bool)
```

**Describe the solution you'd like**

A new field attribute, `#[frb(default = ..)]` to annotate what the default value should be. Only types shared by both Dart and Rust, i.e. Strings, numbers, booleans and lists containing them to be supported for now.

**Describe alternatives you've considered**
Accepting an `Option` instead is a valid solution, however it introduces a small overhead and the semantics wouldn't match up, e.g. you can't pass in a "null" value.

**Additional context**
None

**Comment by Desdaemon** [comment]
Ideally, this should also be able to define default values on constructors as well:

```dart
class Foo {
  final String bar;
  Foo({this.bar = 'bar'});
}
```

**Comment by fzyzcjy** [comment]
The proposal LGTM :) Looking forward to your PR
