### ISSUE TITLE
What is the stage of supporting HashMap<K, V>?

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#954]
I currently met a situation needs to pass a struct with a field of `Vec<HashMap<String, String>>`, just like this: #329.
I tried to work around it by making the type of `Vec<Vec<(String,String)>>`, but then frb errors with : ` 'parse_type failed for ty=Vec<Vec<(String,String)>>'`.  

I wonder:

1. Is there some progress on this issue?
2. Should rust type `HashMap` be supported to map into `Map` in Dart, or other type?
3. If this issue is intended to be solved by directly mapping rust  `HashMap`  into a kind of `Map` in Dart, what about other map in rust, like `BtreeMap` or `SortedMap`-- say, doing the same as that on `HashMap`?

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/flutter_rust_bridge/issues/329

**Comment by fzyzcjy** [comment]
So, maybe we can discuss there? (Given there are already some discussions)

**Comment by dbsxdbsx** [comment]
@fzyzcjy， I‘ve not yet read the related code yet. And I think the first is to know what the stage is at present, I saw https://github.com/fzyzcjy/flutter_rust_bridge/issues/329#issuecomment-1035772862 by @Desdaemon. Is everything still at the early stage, and is there some plan changed with a roadmap of frb?

**Comment by fzyzcjy** [comment]
You may try to play with frb to see which parts error. IMHO the delegating-map-to-vec approach should work.

**Comment by dbsxdbsx** [comment]
> You may try to play with frb to see which parts error. IMHO the delegating-map-to-vec approach should work.

I worked around this by again replacing `Vec<Vec<(String,String)>>` with `Vec<Vec<CustomStruct>>`, so the issue resulted from no support for a tuple or map structure on rust side.
