### ISSUE TITLE
Is it possible to derive  a method of a rust struct in Dart?

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#956]
For example, for a struct 
```rust
pub struct VideoDoc {
    pub ids: Vec<VideoId>,
}

impl VideoDoc {
    pub fn get_uuid(&self){
        // dosomething with self.ids
    }
}
```
I found the class `VideoDoc` in dart, but no `getUUid` there.  How to derive it?  And is this behavior encouraged or discouraged?

**Comment by fzyzcjy** [comment]
https://cjycode.com/flutter_rust_bridge/feature/lang_methods.html

**Comment by dbsxdbsx** [comment]
> https://cjycode.com/flutter_rust_bridge/feature/lang_methods.html

I found that the methods would only be generated when their structs are defined in the API file. If structs are defined in a module,  then methods would be generated. Is this designed to be like this?

**Comment by fzyzcjy** [comment]
That seems to be a lack of feature. Feel free to PR!

**Comment by dbsxdbsx** [comment]
> That seems to be a lack of feature. Feel free to PR!

If a struct is defined in a module, then there would be extra code in generated API file, like:
```rust
// Section: impl IntoDart

impl support::IntoDart for SharedStruct {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.id.into_dart(),
            self.name.into_dart(),
            self.num.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for SharedStruct {}
````
What is it used for?

**Comment by fzyzcjy** [comment]
> What is it used for?

IntoDart. i.e. convert the rust struct into dart wire type. used when you want to *return* a SharedStruct object

**Comment by fzyzcjy** [comment]
https://cjycode.com/flutter_rust_bridge/contributing/design.html

**Comment by dbsxdbsx** [comment]
> > What is it used for?
> 
> IntoDart. i.e. convert the rust struct into dart wire type. used when you want to _return_ a SharedStruct object

If a shared struct is used as a return type for multiple blocks, where should it be defined?  Should everything related to it be defined in a new rust file?

**Comment by fzyzcjy** [comment]
Hmm I am not sure. As long as it does not conflict IMHO it is OK.

**Comment by fzyzcjy** [comment]
reopen since #1145 is going to fix this

**Comment by fzyzcjy** [comment]
v2 seems to have this feature :) If you find bugs, feel free to reopen or create a new issue!
