### ISSUE TITLE
[Bug] When a function is called `dynamic` errors arise

### ISSUE THREAD

**Issue by anstadnik** [fzyzcjy/flutter_rust_bridge#957]
### Describe the bug

When a function is called `dynamic` errors arise
```
lib/bridge_definitions.dart:10:22: Context: This isn't a type.
  Future<RwLockData> dynamic({dynamic hint});
                     ^^^^^^^
lib/bridge_definitions.dart:63:36: Error: 'dynamic' isn't a type.
      {required RwLockState state, dynamic hint});
```
etc.

Please add better error messages for that case.

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
Isn't applicable.
```

**Comment by fzyzcjy** [comment]
That's because `dynamic` is a keyword in dart :/

**Comment by anstadnik** [comment]
True, I knew it the hard way :)
I see that it might be a dumb problem, but it's a rather hard to debug. In such case, I believe the dynamic becomes a function name instead, which breaks code in unpredictable places. I'd suggest adding a check addressing this issue (maybe all keywords at all).

If you believe that it's beyond the scope of the crate, feel free to close the issue.

**Comment by fzyzcjy** [comment]
You are right, feel free to PR to check this!

**Comment by anstadnik** [comment]
@fzyzcjy Do you have any comments regarding #958?
