### ISSUE TITLE
Upstream changes from `polars_dart`

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#960]
General tracking issue for features/fixes to upstream while working on [Desdaemon/polars_dart](/Desdaemon/polars_dart), in chronological order:

- [x] fix: `Option<FieldlessEnum>`, WASM boxed primitives [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/8afb684d9443ff3298fd8ab95b3133041560a81c)
- [x] feat: implement `List<DateTime>`, `List<Duration>` [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/ceba4961b82e90722cb50c27339fcb116867f320)
  - PR: #972
  - should cherry-pick [this commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/5525e45bba7dd9eaf79e228e1c8e50f19433061e)
- [x] fix: WASM wire functions take typed BigInt arrays [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/e1a02cc41a9279cd6151e22855d8f5c7a574c2d7)
  - to be squashed into #972
- [x] feat: translate Rust method comments [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/f5204e4689cf2ee1f58a7c37d74ec74cf9bbf58e)
  - PR: #1094
- [x] feat: `default` field attribute [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/336393b02861da6d992c9440eccea5981a4e5832)
  - PR: #1095
  - closes #948
- [x] feat: const struct constructors [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/1c1e3fef996f676d2dd41fe64c4d6bbebb6d67cf)
  - PR: #1095
  - needed for previous feature to be useful
- [x] feat: Native Dart type of `usize` [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/369a7befaa31869eae30e52272d200a449cc343e)
  - PR: #1102
  - simple, could be out of order
- [x] feat: allow returning `dynamic` from Rust [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/5fb17a87c4190cef73611d48078098f75fd017b0)
  - PR: #1102
- [ ] feat: allow methods to take `self` by value [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/e21a234887916aa243efe04eed87994bf888b8c3)
- [ ] feat: handle Box and Arc slices [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/1e4fbdccf885720f6a5d49dab23ab274b4bff50c)
  - main purpose is to allow mirroring `Arc<str>`
- [ ] fix: overhaul Option and related types [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/81b26ef8b71a755a2396d40f590907f0405217be)
  - major, needs more scrutiny
  - Optional to be closer to a Delegate
  - related: #981
- [ ] feat: unbox structs and enums [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/2be6a41936dde22344fbc53d1b0cdbde80c07848)
  - breaking: requires [Dart 2.13 or later](https://medium.com/dartlang/announcing-dart-2-13-c6d547b57067)
  - related: #959
- [ ] feat: implement `char` and `Option<char>` [commit](https://github.com/Desdaemon/flutter_rust_bridge/commit/446f3fba32f561767ec6adfd775d603a9c8fe00c)
  - ~~blocked by sunshine-protocol/allo-isolate#36~~

**Comment by fzyzcjy** [comment]
That package looks great! (Btw I have recently started using Polars (as an alternative to Pandas) in my Python deep learning project for its speed and ease of interaction with Rust+Python.)

**Comment by Desdaemon** [comment]
:eyes:
