### ISSUE TITLE
[Bug] Compilation error when using StreamSink

### ISSUE THREAD

**Issue by 107295472** [fzyzcjy/flutter_rust_bridge#964]
### Describe the bug

lazy_static! { static ref log_stream_sink: StreamSink<string>;}
pub fn create_log_stream(s: StreamSink<string>) {
    stream_sink = s;
}

Compile Error

CUSTOMBUILD : error : failed to run custom build command for `frustrelease v0.1.0 (D:\flutter\my_app\rust)` [D:\flutter\my_app\build\windows\_cargo-build_frustrelease.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066:

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
generate  
build.rs  
https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/frb_example/pure_dart/rust/build.rs
```

**Comment by fzyzcjy** [comment]
could you please show full error log? I guess it should be `StreamSink<SomeType>` i.e. generic

**Comment by 107295472** [comment]
`Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
CUSTOMBUILD : error : failed to run custom build command for `frustrelease v0.1.0 (D:\flutter\my_app\rust)` [D:\flutter\my_app\build\windows\_cargo-build_frustrelease.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: ��D:\flutter\my_app\build\windows\CMakeFiles\b29d28492cc858ba9cf4321a30e9706e\_cargo-build_frustrelease.rule�����Զ����������˳�������Ϊ 101�� [D:\flutter\my_app\build\windows\_cargo-build_frustrelease.vcxproj]
Exception: Build process failed.
Exited (sigterm)`

![image](https://user-images.githubusercontent.com/6436116/211959294-66e17a69-3689-4ced-b3a6-0f92d527f31c.png)

**Comment by fzyzcjy** [comment]
Well, there should be more error logs...

**Comment by 107295472** [comment]
I've been looking for a long time, but I can't find it

**Comment by fzyzcjy** [comment]
Then that's not a problem of flutter_rust_bridge but instead Rust or your compilation system :/

**Comment by 107295472** [comment]
`lazy_static! { static ref log_stream_sink: StreamSink<LogEntry>; }

pub fn create_log_stream(s: StreamSink<LogEntry>) {
    stream_sink = s;
}`

The above can't, this one can

`pub fn foo(sink: StreamSink<String>) {
    while true {
        let ok = sink.add(format!("Hello!"));
        if !ok {
            break;
        }
    }
    sink.close(); // otherwise, sink doesn't close itself
}`

**Comment by fzyzcjy** [comment]
> could you please show full error log? I guess it should be `StreamSink<SomeType>` i.e. generic

That's why I say this above

**Comment by 107295472** [comment]
`
![image](https://user-images.githubusercontent.com/6436116/212448224-c746680d-9ea1-433c-93fd-27763b467b43.png)
`  
static GLOBAL_DATA: Lazy<Mutex<StreamSink<String>>> = Lazy::new(|| {
    let  m = StreamSink<String>;
    Mutex::new(m);
});
May I ask how this error is reported, the semicolon here

**Comment by fzyzcjy** [comment]
You may need to learn basic Rust... https://www.rust-lang.org/learn

**Comment by 107295472** [comment]
StreamSink transmits Chinese garbled characters
