### ISSUE TITLE
[Bug] StreamSink should close when `drop`ped

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#965]
### Describe the bug

Current behavior of StreamSink is to do nothing when dropped. However, this may lead to unexpected behavior from the Dart consumer's perspective, such as in this example:

```dart
Stream<T> getStreamFromBridge();

final data = await getStreamFromBridge().toList(); // Stream must have an end
```

If StreamSink never sends the closing message, `data` will never be resolved.

## Proposal

Implement `Drop` for StreamSink to close the stream. However, this would be a API-breaking change and requires at minimum feedback from users of StreamSink.

**Comment by 107295472** [comment]
Does rust push data to dart using this StreamSink?

**Comment by fzyzcjy** [comment]
Totally agree this should be implemented!

**Comment by 107295472** [comment]
Thank you, then rust will send data to dart after calling foo

**Comment by Desdaemon** [comment]
Tried this on an uncommitted branch, and this test fails:

```dart
final stream = api.handleStream(arg: 'hello');
var cnt = 0;
await for (final value in stream) {
  print("output from handle_stream's stream: $value");
  cnt++;
}
expect(cnt, 10);
```

```rust
pub fn handle_stream(sink: StreamSink<String>, arg: String) {
    println!("handle_stream arg={}", arg);

    let cnt = Arc::new(AtomicI32::new(0));

    // just to show that, you can send data to sink even in other threads
    let cnt2 = cnt.clone();
    let sink2 = sink.clone();

    spawn!(|| {
        for i in 0..5 {
            let old_cnt = cnt2.fetch_add(1, Ordering::Relaxed);
            let msg = format!("(thread=child, i={}, old_cnt={})", i, old_cnt);
            format!("send data to sink msg={}", msg);
            let _ = sink2.add(msg);
            sleep(Duration::from_millis(100));
        }
        sink2.close();
    });

    for i in 0..5 {
        let old_cnt = cnt.fetch_add(1, Ordering::Relaxed);
        let msg = format!("(thread=normal, i={}, old_cnt={})", i, old_cnt);
        format!("send data to sink msg={}", msg);
        let _ = sink.add(msg);
        sleep(Duration::from_millis(50));
    }
}
```

The current behavior expects this test to pass with `cnt == 10`, but in reality since one thread closed the stream prematurely the other didn't have a chance to post 5 messages causing the failure. So clearly some consideration is required if this change is to be made.
