### ISSUE TITLE
Detect unchanged bindings and skip generating

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#971]
**Is your feature request related to a problem? Please describe.**
Codegen takes a non-insignificant amount of time to run due to the necessary out-of-bands processes to run. It would be ideal to have a way to detect if no work is necessary and skip running them, especially when being used to generate bindings programmatically.

**Describe the solution you'd like**
As a rudimentary solution, cache `IrFile` after each run and compare it with a newly parsed one to determine if any of the `IrFunc`s have had their signatures changed.

**Describe alternatives you've considered**
A more granular approach is to implement an asset graph, however it takes a non-trivial amount of work to implement for potentially diminishing returns.

**Additional context**
None

**Comment by fzyzcjy** [comment]
The feature looks quite useful :)

> As a rudimentary solution, cache IrFile after each run and compare it with a newly parsed one to determine if any of the IrFuncs have had their signatures changed.

The main idea LGTM, but we may need to consider a bit more details: For example, are we sure that, with the same IrFunc, the outputs will be the same?

**Comment by fzyzcjy** [comment]
We may also need to implement a "force rebuild" flag (which is easy to implement, surely). And we should do it in our CIs, otherwise after we change the code, the CI uses the cache...

**Comment by Desdaemon** [comment]
> For example, are we sure that, with the same IrFunc, the outputs will be the same? (e.g. different configs must yield diff outputs; diff frb versions also does so; is there any other cases?)

Good idea. Let's try to enumerate some cache invalidations:

- Codegen version
- Config
- ffigen, cbindgen versions (probably not build_runner and friends)
- Requested by user
- etc.

**Comment by fzyzcjy** [comment]
Another possible approach: which part is indeed most time consuming - we may be able to detect the *direct input* to that part. 

For example, we know Dart's build_runner execution is quite slow, then we may hash the generated .dart files, and use that checksum to skip dart build_runner
