### ISSUE TITLE
Revisit `RustOpaque` moving semantics

### ISSUE THREAD

**Issue by Desdaemon** [fzyzcjy/flutter_rust_bridge#975]
**Is your feature request related to a problem? Please describe.**

Suppose we have an API that looks like this:

```rust
pub fn foo(value: RustOpaque<RwLock<UnsafeCell<..>>>) {
    // always panic if aliased
    let value = value.try_unwrap().unwrap().into_inner().unwrap();
    // do stuff...
}
```

Then correspondingly, one ought to communicate to users of `foo` that they must always pass in a unique opaque pointer, like this:

```dart
RwLockUnsafeCell opaqueString;
foo(opaqueString..move=true); // should work
```

Which works fine for one-off calls, even though it is already somewhat verbose. However, this breaks down when upcoming support for methods that take `self` by value arrives:

```rust
pub struct Wrap(pub RustOpaque<RwLock<String>>);
impl Wrap {
    pub fn append(self, value: String) -> Wrap {
        // some API that requires ownership of self
        let self_ = self.0.try_unwrap().unwrap().into_inner().unwrap();
        Wrap(RustOpaque::new(RwLock::new(self_ + value)))
    }
}
```

Then similarly, to call `Wrap::append` one has to mark the *inner* opaque pointer as moved:

```dart
Wrap wrap;
wrap.field0.move = true;
wrap = wrap.append("asd");
```

It quickly becomes unergonomic, however, when multiple of such methods are called in a chaining fashion:

```dart
Wrap wrap;
wrap.field0.move = true;
wrap = wrap.append("first")
  ..field0.move = true; // to allow the second chain
wrap = wrap.append("second");
```

**Describe the solution you'd like**

A way to uniformly and ergonomically mark opaque pointers as to be moved. However, it must be up to the user to decide what is the ergonomic convention for their library, so here are some proposals:

## Implicit (Rust-style)

Since support for methods that take `self` by value hasn't arrived, it can be baked into this new feature to implicitly mark pointers as moved. However, this will result in fragile code since it relies on communication and conventions to prevent runtime panics, since unlike Rust, Dart has no way to statically invalidate variables after they have been moved.

## Explicit (C++-style)

Provide an API to recursively mark classes and enums containing opaque pointers as "moved", such as a getter or a `move(value)` a la C++. This represents a contract on the end-users of the libraries, and IMO is not very Dart-friendly but perhaps fine for users who write and consume their own bindings.

```dart
// getters
class Wrap {
  final RwLockString field0;
  Wrap({required this.field0});

  Wrap append({required String value});

  // Tedious to write by hand, codegen can offer to write this boilerplate
  Wrap get move {
    return Wrap(field0: field0..move=true);
  }
}

// Explicitly get the moved version
Wrap wrap;
wrap = wrap
  .move.append(value: "first")
  .move.append(value: "second");
```

## Wrapper

A new wrapper, e.g. `Unique`, to enforce a type-level contract:

```dart
class Unique<T> {
  final T _value;
  Unique(T value) : _value = value;
  T unwrap() => _value;
}

class Wrap {
  // A signal to readers that by this point, this pointer should not be aliased.
  // However, it is not an absolute runtime contract.
  Unique<Wrap> get move {
    return Unique(Wrap(field0: field0..move=true));
  }
}

// Methods taking 'self' are defined on the wrapper, not the class itself
extension UniqueWrap on Unique<Wrap> {
  // could also return a Unique<Wrap>, depending on the desired semantics
  Wrap append({required String value}) { .. }
}

// same usage as the getter
Wrap wrap;
wrap = wrap
  .move // Unique<Wrap>
  .append(value: "first") // Wrap
  .move // Unique<Wrap>
  .append(value: "second"); // Wrap
```

**Describe alternatives you've considered**
The alternative is to *not* allow methods that take `self`, as is the case right now, however this takes away some of the expressiveness of Rust. Furthermore, while it is possible to construct the previously mentioned APIs with only a `&self`, it would result in large memory leaks due to the Dart runtime not cleaning up temporaries in a timely manner (and neither should anyone depend on that fact for correctness.)

**Additional context**
None.

**Comment by fzyzcjy** [comment]
That implicit move is great! Firstly here are my two cents where it can be used: Suppose we are developing an image processing page in Flutter using algorithms implemented in Rust (that's my real usage indeed ;) ). Suppose we have these APIs:

```rust
// algorithm.rs
fn image_read(path: &str) -> Image { ... }
fn image_rotate(image: Image) -> Image { ... }
fn image_scale(image: Image) -> Image { ... }
fn image_write(path: &str, image: Image) {}
```

Now what happens when we want to read-rotate-scale-write an image? My old solution was (well, ugly):

```rust
fn image_rotate(image_handle: ImageHandle) -> ImageHandle {
  let image = Pool::get_and_remove_the_original_object(image_handle); // <---
  algorithm::image_rotate(image)
}
```

in order to

```rust
var image = await api.imageRead("hi.png");
image = await api.rotate(image);
image = await api.scale(image);
await api.write(image);
```

Why I needed `get_and_remove_the_original_object` (notice it *removed* the original object)? Because when I write `api.rotate(image)`, I hope the original image is auto disposed.

Now, with the new proposal (non-reference self), things seems to get easier:

```rust
// api.rs
pub struct Image { ... } // opaque type indeed
impl Image {
  fn image_rotate(self) -> Imge { // self, not &self
    algorithm::rotate(self.data)
  }
}
```

Now, for a `self`, we mean it is consumed (and disposed) in Rust.

**Comment by fzyzcjy** [comment]
As for implementation in Dart, I personally like the type-safe approach most :)

Well I am really missing Rust, where such scenario is so trivial (compared to Dart) to model...
