### ISSUE TITLE
Can I set generate dart class name?

### ISSUE THREAD

**Issue by niuhuan** [fzyzcjy/flutter_rust_bridge#976]
**Is your feature request related to a problem? Please describe.**
There are many struct of trust name is `Model`, I want rename it in dart(gened codes).

**Describe the solution you'd like**
#[frb(dart_class_name="AModel")] or #[dart_class_name("AModel")]

**Describe alternatives you've considered**
I don't know how to change the name of the generated dart class. Other frameworks require the structure to be called Model. I can only copy one copy of each class.

**Comment by fzyzcjy** [comment]
Looks quite reasonble, feel free to PR!

**Comment by niuhuan** [comment]
I didn't read the code of frb and have no direction. What do you think about it? How he uses it? What code to start with?

**Comment by fzyzcjy** [comment]
https://cjycode.com/flutter_rust_bridge/contributing/design.html
