### ISSUE TITLE
Split Up Worker Pool and Flutter Bridge?

### ISSUE THREAD

**Issue by anlumo** [fzyzcjy/flutter_rust_bridge#982]
**Is your feature request related to a problem? Please describe.**

I need my Rust wasm code to handle JsValue objects ([OffscreenCanvas](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.OffscreenCanvas.html), specifically) across multiple requests. This is inherently incompatible with the web workers used by flutter_rust_bridge, because even if I got my OffscreenCanvas into a web worker through flutter_rust_bridge's mechanisms (which would require different patches), the next request might go to a different web worker and thus wouldn't have access to it.

Also, my code is singular long-running requests that don't benefit at all from parallelism anyways.

**Describe the solution you'd like**

The worker pool should be a separate crate that people can integrate or not, depending on their specific use case. Maybe even some already existing crate could be used for this.

**Describe alternatives you've considered**

The only way to do this at the moment I could come up with is to fork the project and get rid of the pool in it.

**Comment by fzyzcjy** [comment]
> The worker pool should be a separate crate that people can integrate or not, depending on their specific use case. Maybe even some already existing crate could be used for this.

Definitely. Indeed, currently you can customize your own worker pool (or even not use work pool) already - https://cjycode.com/flutter_rust_bridge/feature/handler.html

**Comment by anlumo** [comment]
Oh, I completely missed that! Thanks.

**Comment by fzyzcjy** [comment]
You are welcome!
