### ISSUE TITLE
Prefer require-corp over credentialless for Cross-Origin-Embedder-Policy

### ISSUE THREAD

**Issue by rob-mur** [fzyzcjy/flutter_rust_bridge#985]
**Is your feature request related to a problem? Please describe.**
To use this library with flutter in web we need a cross-origin isolated environment to enable access to shared buffers. The requirements for this is to set the following two headers:
- Cross-Origin-Opener-Policy: same-origin
- Cross-Origin-Embedder-Policy: credentialless OR require-corp

As per [this](https://developer.chrome.com/blog/coep-credentialless-origin-trial/) blog post, credentialless is only currently supported in Chrome. This leads to web builds not working in other browsers (firefox, safari etc).

Note however, that if require-corp is selected, canvaskit will then be blocked because it's not the same origin, unless it is possible to add Cross-Origin-Resource-Policy: cross-origin specifically to that request (further investigation needed). However the workaround is to use the html renderer. Further to the rest of the changes outlined below, we would need to pass web render html to flutter build web.

In the frb dart library, credentialless is the default for flutter projects and cannot be overridden with the relax-coep flag of flutter_rust_bridge_serve.

It would also be helpful to have this information in the documentation, so that if you wanted to support multiple browsers you would know it was necessary to specify require-corp.

**Describe the solution you'd like**
I am unsure if there would be any problems with just having require-corp as the default, but if not this seems like the easiest solution. This would be a simple change in the frb dart subproject around how relax-coep is parsed, plus passing in html-renderer.

Further, I would like a line around this added to the documentation so the next person doesn't spend the same effort I just did!

**Describe alternatives you've considered**
Alternatively, we could just document that you must use chrome for local development, and to use relax-corp + html renderer in production if you want to target more than just chrome.

**Additional context**
_(I currently have limited availability so just looking to discuss this -> can work on implementation later/anyone else can physically make any changes)_

**Comment by Desdaemon** [comment]
I must've glossed over that credentialless is only available on Chrome, because I was also hesitant to implement anything other than the output of `-t no-modules` since other targets are similarly unavailable for non-Chromium browsers. (see module workers)

**Comment by rob-mur** [comment]
Further information:

You can actually avoid falling back to the html renderer (which doesn't have great performance on mobile) by following the guidance at [this](https://github.com/flutter/flutter/pull/92134) link.

Essentially, you use ```--dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/``` in order to force flutter to use the locally produced copy rather than pulling from a cdn.
