### ISSUE TITLE
Let RustOpaque Expose the Arc

### ISSUE THREAD

**Issue by anlumo** [fzyzcjy/flutter_rust_bridge#988]
**Is your feature request related to a problem? Please describe.**

Working with async code (via `Stream`s) with this project means that I have to keep objects around even after the function call itself returns. Due to the ownership rules of Rust, I have to use something like `Arc` for this, because both my closure and Dart have to keep a reference to that object around and lifetimes are not transferred over the bridge. `RustOpaque` is already halfway there by using an `Option<Arc<_>>` internally. However, the Rust code doesn't have access to that field.

**Describe the solution you'd like**

`RustOpaque` should implement a function that returns a clone of the inner `Arc`.

**Describe alternatives you've considered**

It's possible to do it right now by using an `Arc` as part of the type wrapped by RustOpaque, but then it's an unnecessary double-`Arc`.

**Additional context**

The PR is incoming, this ticket is just there because you require one for the PR.

**Comment by fzyzcjy** [comment]
> It's possible to do it right now by using an Arc as part of the type wrapped by RustOpaque, but then it's an unnecessary double-Arc.

Totally agree that we should not have double arc if avoidable. (have cc in the PR)

**Comment by anlumo** [comment]
👀
