### ISSUE TITLE
Provide option to make generated rust code always use fully qualified paths 

### ISSUE THREAD

**Issue by Yohe-Am** [fzyzcjy/flutter_rust_bridge#996]
Before anything, I want to express my gratitude to the authors. I can easily imagine how arduous the project I'm working on would have been without this.   

**Is your feature request related to a problem? Please describe.**

I have a `Channel` type in my `api` which breaks the generated code as it's ambiguously resolved with a type from within `frb` with the same name.

**Describe the solution you'd like**
An option to allow the codegen to use fully qualified paths in all generated rust code should provide a lasting solution to this and any similar problems.

**Describe alternatives you've considered**
For now, I'm going to use a rust side wrapper to avoid the clash and a dart side alias to keep using the the `Channel` name elsewhere.

**Additional context**

This occurs on v 1.60.0 of `frb`.

![screenshot showing ide errors](https://user-images.githubusercontent.com/56622350/214466308-62c63f90-6bf4-471d-9106-ebfb436bffd8.png)

**Comment by fzyzcjy** [comment]
You are welcome!

That looks pretty reasonable. Roughly speaking, seems that we only need to modify a few places using things inside `flutter_rust_bridge` - just add prefix `flutter_rust_bridge::` to them. Feel free to PR!

**Comment by fzyzcjy** [comment]
P.S. overall design doc - https://cjycode.com/flutter_rust_bridge/contributing/design.html (may not be needed for this PR but just put it here for reference)
