### ISSUE TITLE
how to get debug log for  project `frb_codegen` ?

### ISSUE THREAD

**Issue by dbsxdbsx** [fzyzcjy/flutter_rust_bridge#999]
I am trying to add some feature to `frb_codegen` using vs code, but the debugging is a little frustrating. Since I don't know where the output is after changing code, then `build.rs` run automatically, though there are many `info!`, `debug!` in code.  

I guess it is related to:
```rust
 let raw_opts = RawOpts::parse();
    env_logger::Builder::from_env(Env::default().default_filter_or(if raw_opts.verbose {
        "debug"
    } else {
        "info,cbindgen=error"
    }))
    .init();
```

I hope there would be log output on local disk after  `build.rs` running.

**Comment by fzyzcjy** [comment]
`build.rs` is a standard thing in Rust ecosystem, so I guess maybe search how to see logs of a standard rust build.rs

**Comment by dbsxdbsx** [comment]
There is nothing with `build.rs`, `build.rs` of some sub examples are just triggered when code in `frb_codegen` is changed.    I  wonder how to catch output info when running `frb_codegen`.
Currently,  I just write some debug code like:
```rust
   let filepath = "./output.txt";
    std::fs::write(filepath, data).expect("Unable to write file");
```
then after `build.rs` auto-triggered, modified `frb_codegen` is running for those examples, so that I can catch data on local disk, but it is still a little inconvenient.

**Comment by fzyzcjy** [comment]
> how to catch output info when running frb_codegen

Not very sure about the question. Maybe you mean `RUST_LOG=debug flutter_rust_bridge_codegen your_args`?

Related: bug issue template

![image](https://user-images.githubusercontent.com/5236035/214838397-9cbe582e-1455-402a-a441-1c523cb4fe64.png)

**Comment by dbsxdbsx** [comment]
I solved it by using crate `fern`.
